### ISSUE TITLE
CliBuilder "error: Missing required options" when unknown options are provided

### ISSUE THREAD

**Issue by dhs-rec** [remkop/picocli#1013]
When passing an additional option to a script that doesn't know about this option, I get an error message about "missing required options", listing all required options that follow the unkown option.

The following example code reproduces the issue:
```
@Grab('info.picocli:picocli-groovy:4.2.0')
@GrabConfig(systemClassLoader=true)

import groovy.cli.picocli.CliBuilder

def cli = new CliBuilder(name: 'cliTest.groovy')
cli.h(type: Boolean, longOpt: 'help', usageHelp: true, required: false, 'Show usage information')
cli.a(type: String, longOpt: 'optA', required: true, args: 1, 'Option a (required)')
cli.b(type: String, longOpt: 'optB', required: true, args: 1, 'Option b (required)')
// NOTE: No "-c|--optC" here
cli.d(type: String, longOpt: 'optD', required: true, args: 1, 'Option d (required)')
cli.e(type: String, longOpt: 'optE', required: true, args: 1, 'Option e (required)')
cli.f(type: String, longOpt: 'optF', required: false, args: 1, 'Option f (optional)')
def opts = cli.parse(args)
opts || System.exit(1)
if(opts.h) {
  cli.usage()
  System.exit(0)
}
```
When invoked with an additional option, '-c C' for example, it produces the following, misleading output:
```
% ~/tmp/groovy-3.0.2/bin/groovy ./cliTest.groovy -a A -b B -c C -d D -e E
error: Missing required options [--optD=PARAM, --optE=PARAM]
Usage: cliTest.groovy [-h] -a=PARAM -b=PARAM -d=PARAM -e=PARAM [-f=PARAM]
  -a, --optA=PARAM   Option a (required)
  -b, --optB=PARAM   Option b (required)
  -d, --optD=PARAM   Option d (required)
  -e, --optE=PARAM   Option e (required)
  -f, --optF=PARAM   Option f (optional)
  -h, --help         Show usage information
```
The list of missing options varies depending on where "-c C" is inserted. There's no error when it's the last one.

I would expect it to either ignore the addtional option in all cases or emit an error message about an unknown option. But in no case should it error out because of missing required options when there are none missing.

**Comment by remkop** [comment]
Thank you for raising this!
This certainly looks like a bug in `CliBuilder`. 
I will take a look. Would you mind raising a JIRA ticket for this in the Groovy project or did you already do so?

**Comment by dhs-rec** [comment]
Not yet. Wanted to check with you first ;-)

**Comment by dhs-rec** [comment]
https://issues.apache.org/jira/browse/GROOVY-9528

**Comment by remkop** [comment]
As discussed on the Groovy JIRA ticket, the default behavior is the way it is for backward compatibility with the Commons CLI implementation of CliBuilder. 

However, a more intuitive behavior can be obtained with the following code:

```
def cli = new CliBuilder(name: 'cliTest.groovy')
cli.parser.stopAtPositional(false)
cli.parser.unmatchedOptionsArePositionalParams(true)
// ...
def opts = cli.parse(args)
// ...
```

The plan is to add some documentation to the Groovy CliBuilder docs to help future users avoid this issue. 

Closing this ticket since there’s no work that can be done in the picocli project.
