### ISSUE TITLE
Command line interface issue 

### ISSUE THREAD

**Issue by prt95** [remkop/picocli#1014]
Type a long command on picocli terminal on windows machine. The command should take more than one line. Now move the cursor to the first line of command and try to edit the command, the issue is that the characters of command starts getting omitted as you edit the command. To fix this you will need to maximize the command window so that given command gets sufficient space.

Given below is a long command which takes more than one line : 

<img width="700" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/8886750/80462062-d4944880-8953-11ea-8182-91a4805f7072.png">

On editing characters are getting omitted as shown in below image: 

<img width="693" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/8886750/80462074-d827cf80-8953-11ea-9657-48b49b4aeff9.png">

On maximizing terminal window issue gets fixed  as shown in below image : 

<img width="830" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/8886750/80462088-db22c000-8953-11ea-975e-5f6a924d8381.png">

**Comment by remkop** [comment]
Hi @prt95, thank you for raising this issue.
 
I believe this cannot be fixed in picocli: the editing functionality lives in the JLine 3 library. 

Can you create a ticket in the https://github.com/jline/jline3 issue tracker?

**Comment by remkop** [comment]
@prt95, did you have a chance to create an issue in the JLine 3 project for this?

I am tempted to close this ticket since there is no change that I can make in picocli to fix this: this requires a change in JLine. Does that make sense, or do you want to keep this ticket open?

**Comment by prt95** [comment]
Ok Remko, Please go ahead and close the ticket. I will check with Jline.
