### ISSUE TITLE
Support repeatable ArgGroups with positional parameters

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1027]
See https://stackoverflow.com/a/61606437/1446916

We would like to be able to parse user input like this (repeating pairs of `name grade`):

```
grades Abby 4.0 Billy 3.5 Caily 3.5 Danny 4.0
```

Ideally using strongly-typed positional parameters. 
A natural way to model this would be with an argument group, like this:

```java
// unfortunately this does not work...
static class StudentGrade {
    @Parameters(index = "0") String name;
    @Parameters(index = "1") BigDecimal grade;
}

@ArgGroup(exclusive = false, multiplicity = "1..*")
List<StudentGrade> gradeList;
```

However, this gives the following error:

```
Unmatched arguments from index 2: 'Billy', '3.5', 'Caily', '3.5', 'Danny', '4.0'
Usage: grades (<name> <grade>)... [-hV]
      <name>
      <grade>
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
```

**Comment by NewbieOrange** [comment]
Hi @remkop, I did some preliminary experiments and made somewhat sketchy changes to address this at #1036. It does pass the new test you added, and does not break any previous tests.

It might be incorrect or break things tho. 😛

**Comment by remkop** [comment]
@NewbieOrange I have updated the implementation a bit; specifically, I added a `GroupMatchContainer::canMatchPositionalParam` method that hopefully covers more edge cases.

If you have a chance to poke at it (perhaps with some different edge cases) that would be great.

**Comment by NewbieOrange** [comment]
@remkop I noticed you have ignored the test `testPositionalsInGroupAndInCommand`, does that mean the original behaviour is broken or the new behaviour is expected?

Also, are there any new edge-case tests that would fail without the new `canMatchPositionalParam` included in `ArgGroupTest`?

**Comment by remkop** [comment]
I think that test used to pass "by accident"; note that there are two similar test cases (testGroupWithOptionsAndPositionals_multiplicity0_1 and testGroupWithOptionsAndPositionals_multiplicity1_2). These did not pass before and with the new logic still do not pass. So it is a bit strange that testMultipleGroupsWithPositional used to pass.

I did not add any new tests for `canMatchPositionalParam`. I should. If you can help that would be great.

**Comment by remkop** [comment]
Overall, I think we made very good progress in this area and it is stable enough to do a release.
It may not be perfect but we can enhance in future versions.

I will try to release picocli 4.3 tomorrow morning.

**Comment by NewbieOrange** [comment]
Yes, I think the current progress is at least much better than previous versions.

I will post update if I could find any issues, but in most cases it seems fine.
