### ISSUE TITLE
attribute `splitSynopsisLabel`: incorrect usage message

### ISSUE THREAD

**Issue by deining** [remkop/picocli#1044]
Picocli 4.3.0 introduced the attribute `splitSynopsisLabel`, which is great.
I encountered a minor issue when trying out the new attribute:

```
1  package test;
2  import picocli.CommandLine;
3  import picocli.CommandLine.Command;
4  import picocli.CommandLine.Option;
5
6  public class ExecuteTest {
7   
8      static CommandLine cmd;

9      public static void main(String[] args) {
10       cmd = new CommandLine(new TestCommand());
11       cmd.usage(cmd.getOut());
12     }
13 
14    @Command(name = "ExecuteTest")
15     static class TestCommand implements Runnable {
16       
17      @Option(names = "x", split="\\|", splitSynopsisLabel = "|")
18         static String[] parts = {};
19 
20         @Override
21         public void run() {
22             }
23         }
24     }
25 }
```

This now results in a proper usage message:

`Usage: ExecuteTest [x=<parts>[|<parts>...]]...`

Now I remove the attribute `split` from the option while leaving the the attribute `splitSynopsisLabel` in place:

`17      @Option(names = "x", splitSynopsisLabel = "|")`

I'm still getting the same usage message (which is incorrect now):

`Usage: ExecuteTest [x=<parts>[|<parts>...]]...`

I see two possible remedies:
* when using attribute `splitSynopsisLabel`, check whether corresponding attribute `split` is given, throw an exception in case of missing attribute
* print corrrect usage message if `split` attribute is missing

**Comment by remkop** [comment]
Thank you for raising this!
This is now fixed in master (splitSynopsisLabel is ignored if `split` is missing).

If no other issues are reported I will do a bugfix release tomorrow morning.

**Comment by remkop** [comment]
@deining picocli 4.3.1 has been released with this fix. Thanks again for raising this!
