### ISSUE TITLE
Cause exception not printed by default execution exception handler

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1048]
When an exception occurs in the business logic, this is handled by the execution exception handler. By default, this prints the full stack trace of the exception.

Since 4.3.0, only the stack trace of the "outer" exception is printed. If that exception has any "cause" exceptions, these are incorrectly omitted.

With the work done in #484, #845 and #1008 (colors in exception handler), we no longer call `exception.printStackTrace()` but instead have a custom implementation that has the same effect but uses ANSI colors. This implementation incorrectly omits the stack trace for any nested "cause" exceptions (and their nested cause, if any).

A workaround is to register a custom execution exception handler as follows:

```java
new CommandLine(new MyApp())
        .setExecutionExceptionHandler(
            (Exception ex, CommandLine commandLine, ParseResult parseResult) -> {
                        ex.printStackTrace();
                        return commandLine.getCommandSpec().exitCodeOnExecutionException();
            })
        .execute(args);
```

**Comment by jerrylususu** [comment]
Sorry for the bug introduced. Working on a permanent fix.

**Comment by jerrylususu** [comment]
One easy fix would redirect all the output from ex.printStackTrace() to a string, as proposed in #845. However, doing so may harm the ability to split exception messages from stack traces.

**Comment by jerrylususu** [comment]
Seems extend StringWriter to write Style.on() before and Style.off() after is one viable solution. Testing locally.

**Comment by jerrylususu** [comment]
Mostly done...
![image](https://user-images.githubusercontent.com/17522475/82067105-d8212100-9702-11ea-9604-2c944e2a3430.png)

**Comment by jerrylususu** [comment]
By the way, here is a strange table about the compatibility of ANSI style.

![image](https://user-images.githubusercontent.com/17522475/82113371-1a407600-9788-11ea-9adb-2cec5e88fcc0.png)

**Comment by remkop** [comment]
Thanks for the help!
I just released picocli 4.3.2 with this fix.

About the terminals, there is not much we can do about that in the application. The best we can do is select colors and styles that look acceptable in most consoles. (Which I think we did.) :-)

**Comment by jerrylususu** [comment]
Sorry for the bug introduced! Hope 4.3.2 will be the last patch version of 4.3, and wish everything goes well!

**Comment by remkop** [comment]
No worries!
That’s software!
