### ISSUE TITLE
GenerateCompletion command only works if used as direct subcommand of root

### ISSUE THREAD

**Issue by charphi** [remkop/picocli#1051]
I'm trying to use it in a sub-subcommand such as `mycommand setup generate-completion`
instead of `mycommand generate-completion`

Unfortunatly, this generates autocompletion for `setup` and not `mycommand`.

**Comment by remkop** [comment]
Yes, currently the `AutoComplete.GenerateCompletion` command generates completions for its parent. I agree that it would be better if it would generate completions for the root command instead.

Will you be able to provide a pull request (with test) for this?

**Comment by remkop** [comment]
The implementation for this is fairly straightforward: just replace

```java
String script = AutoComplete.bash(
        spec.parent().name(),
        spec.parent().commandLine());
```

with 

```java
String script = AutoComplete.bash(
        spec.root().name(),
        spec.root().commandLine());
```

But we do need some tests to verify that this works for your use case (and perhaps another one where the completion command is nested even deeper).

**Comment by charphi** [comment]
The code is simple indeed.

But, there is one thing missing: a pre-defined variable for root name (ROOT-COMMAND-NAME?) so that the command description
`"Generate bash/zsh completion script for ${PARENT-COMMAND-NAME:-the parent command of this command}."` 
would become: 
`"Generate bash/zsh completion script for ${ROOT-COMMAND-NAME:-the root command of this command}."`

**Comment by remkop** [comment]
Yes, it makes sense to add a `${ROOT-COMMAND-NAME` variable.

**Comment by charphi** [comment]
I'm coding a PR.
