### ISSUE TITLE
NullPointException when using Argument Groups

### ISSUE THREAD

**Issue by waacc-gh** [remkop/picocli#1053]
When the example in chapter "8.4. Repeating Composite Argument Groups" is call with the options:
-a 1 -b 1 -c 1 -x -z
an NullPointException is thrown. The problem seams to be #that two values (-x and -z) are supplied for "Exclusive ". #

**Comment by remkop** [comment]
Hi @waacc-gh, thank you for raising this!

With the latest version (picocli 4.3.2) I am unable to reproduce the issue. The following test passes for me:

```java
@Test
public void testIssue1053NPE() {
    CompositeGroupDemo example = new CompositeGroupDemo();
    CommandLine cmd = new CommandLine(example);

    cmd.parseArgs("-a 1 -b 1 -c 1 -x -z".split(" "));

    assertEquals(2, example.composites.size());
    CompositeGroupDemo.Composite c1 = example.composites.get(0);
    assertTrue(c1.exclusive.x);
    assertFalse(c1.exclusive.y);
    assertFalse(c1.exclusive.z);
    assertEquals(1, c1.dependent.a);
    assertEquals(1, c1.dependent.b);
    assertEquals(1, c1.dependent.c);

    CompositeGroupDemo.Composite c2 = example.composites.get(1);
    assertFalse(c2.exclusive.x);
    assertFalse(c2.exclusive.y);
    assertTrue(c2.exclusive.z);
    assertNull(c2.dependent);
}
```

I suspect the code you are executing may be slightly different. 
Can you show the exact code that reproduces this issue?

**Comment by waacc-gh** [comment]
Sorry, my fault. I've overlooked the hint in the documentation - or more precisely, I was not able to remember the hint when creating a simple test-output-method.
