### ISSUE TITLE
How to parse argument as system default value

### ISSUE THREAD

**Issue by charphi** [remkop/picocli#1057]
My use case is to be able to ask for the default charset of the OS (see `Charset.defaultCharset()`) instead of a specific one while keeping the default to `UTF-8`.

My solution would be something like `mycommand --charset=.` with this custom converter:
```java
class CustomCharsetConverter implements CommandLine.ITypeConverter<Charset> {
	public Charset convert(String value) throws Exception {
		return ".".equals(value) ? Charset.defaultCharset() : Charset.forName(value);
	}
}
```

How would you do that with picocli? Is there a better way?

**Comment by remkop** [comment]
> How would you do that with picocli?

Not sure I understand the question. It looks like you already have the solution. If the question is how to wire this in, you can either use your converter for all `Charset` options with `CommandLine::registerConverter`, or only for a specific option with `@Option(converter = CustomCharsetConverter.class)`.

Does that answer your question?

**Comment by charphi** [comment]
It seems my question was not clear.
It is not about how to wire the converter but an open question to get alternatives and/or ideas for improvement.
For example: is dot the right character to use? Is there an existing pattern?

**Comment by remkop** [comment]
I see. 
My approach would be to simply always do `Charset.forName` on the specified value, without "special" values like a dot. The user can select the default charset by not specifying the `--charset` option at all. (It may be useful for users if the usage help shows the value of the default charset with `${DEFAULT-VALUE}`.)

**Comment by charphi** [comment]
Thanks for the help
