### ISSUE TITLE
ManPageGenerator does not ignore "hidden" options

### ISSUE THREAD

**Issue by bdemers** [remkop/picocli#1063]
I was expecting the ManPageGenerator to ignore "hidden" options the same way that the standard `--help` renderer ignores them, for example:

```java
@Option(names = "--color", hidden = true)
public void setColor(ColorOptions color) { 
  // ...
}
```

This does NOT render when `--help` is used, but it IS rendered to the manpage doc:

```txt
--color=<color>
```

**Comment by bdemers** [comment]
NOTE: hidden subcommands are rendered as well

**Comment by remkop** [comment]
@bdemers Thank you for reporting this!
This is an oversight and a bug.

**Comment by remkop** [comment]
Will you be able to provide a pull request for this?

**Comment by bdemers** [comment]
I think I've got it, doing a bit more testing and I'll send a PR

**Comment by remkop** [comment]
Merged the PR. Thanks for the contribution!

There may be an edge case where options in an argument group (with header) are not hidden, while all other options are hidden; would be good to have a test case for that... 
If you can take a look at this that would be great!
