### ISSUE TITLE
Get expanded @-file arguments?

### ISSUE THREAD

**Issue by mashlol** [remkop/picocli#1074]
Is it possible to get the parsed, expanded @-file arguments after parsing is complete? In `ParseResult`, I see there is a `tentativeMatch` which does have the correct arguments parsed out, but it doesn't seem to be exposed externally. The `originalArgs` object still has the un-expanded @-file arguments like `@/path/to/file.args`

Basically given `binary --arg @/path/to/file --other_arg @/path/to/second/file`, is it possible to get `binary --arg expanded_file --other_arg expanded_file`? Either as a raw string, or a list of parsed tokens (preferred).

The use-case is to be able to log the actual arguments even if you invoke the binary with a file, and support replayability with a copy/pastable repro command.

**Comment by remkop** [comment]
Hi, with the current version of picocli this feature does not exist.
We could add a method `ParseResult.expandedArgs()` that returns the argument list that was actually processed by the parser (so after `@file` expansion).

Will you be able to provide a pull request for this?

**Comment by mashlol** [comment]
Sure, I can submit a pull request for this.

**Comment by remkop** [comment]
This is a nice addition!
Thank you for the PR! Merged and will be included in the next release.
