### ISSUE TITLE
Show end-of-options `--` in manual page

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1077]
This is a follow-up ticket to https://github.com/remkop/picocli/issues/985: 

the ManPageGenerator needs special logic to show the `Help.END_OF_OPTIONS_OPTION` option
when `spec.usageMessage().showEndOfOptionsDelimiterInUsageHelp()` is `true`.

This special option should be rendered after the other options in the command, but before the option groups (if any).

**Comment by Linyer-qwq** [comment]
Hello, I want to try to fix work on issue, could you please provide some testcases so that I can better understand this purpose?

**Comment by remkop** [comment]
If you already started working on this, please fetch the latest master again since I just merged #1064.
I added a test case, see [here](https://github.com/remkop/picocli/commit/e742964c544958f58a567c473c534b283b06c38e).
