### ISSUE TITLE
picocli-codegen generates empty 'resources' array in resource-config.json

### ISSUE THREAD

**Issue by serpro69** [remkop/picocli#1078]
I have several resources in `main/resources`, and have setup picocli-gen with kotlin and kapt (tried explicit gradle tasks as well)

Reflect config seems to be correct.
Proxy config file is an empty array `[]`. Probably because I don't have any proxies in the application.
Resource config is:
```json
{
  "bundles" : [
  ],
  "resources" : [
  ]
}
```

Am I doing something wrong or missing some configuration to generate `resource-config.json` correctly?

Here's what I have in gradle build file (only important parts kept for brevity):
```
plugins {
    kotlin("jvm")
    kotlin("kapt")
}

dependencies {
    implementation("info.picocli:picocli:4.3.2")
    kapt("info.picocli:picocli-codegen:4.3.2")
}

kapt {
    arguments {
        arg("project", "${project.group}/${project.name}")
    }
}
```

The below gradle task gives the same result as kapt-based approach:
```
val generateGraalResourceConfig by tasks.creating(JavaExec::class) {
    dependsOn("classes")
    main = "picocli.codegen.aot.graalvm.ResourceConfigGenerator"
    classpath = codegen + sourceSets.main.get().runtimeClasspath
    val outFile = "${project.buildDir}/resources/main/META-INF/native-image/${project.group}/${project.name}/resource-config.json"
    args = listOf("--output=${outFile}", mainAppClass)
}
```

**Comment by serpro69** [comment]
Sorry, my bad, forgot to specify the pattern :)

**Comment by remkop** [comment]
No worries, thanks for the confirmation!
