### ISSUE TITLE
Order of configured global options should not be enforced

### ISSUE THREAD

**Issue by palade** [remkop/picocli#1105]
### Context 
I'm re-using a title that has been used in #895 and a dedicated feature to address this issue as discussed in #649 . Also, there is a [SO post](https://stackoverflow.com/questions/50228778/cli-with-picocli-call-main-command-before-sub-command-get-called) related. However, the available solutions do not work for me. 

### The problem
The order of the specified global options is important. I'm unsure if it is because how the library is used or there is a problem within the library, but will describe what I'm trying to do. 

Given a top command, one sub-command and three options in the following order:

> topCommand option1 option2 sub-command option3

`option1` and `option2`  are ignored and only `option 3` is considered.

However, all options are considered if this is changed to:
> topCommand sub-command option1 option2 option3

How the code looks like at the moment (which is in Kotlin):

    
    @Command(mixinStandardHelpOptions = true,...)
    abstract class Base {
 
        @Option(names = ["--logging-level"],
            completionCandidates = LoggingLevelConverter.LoggingLevels::class,
            converter = [LoggingLevelConverter::class])
        var loggingLevel: Level = Level.INFO

        @Option(names = ["-v", "--verbose", "--log-to-console"])
        var verbose: Boolean = false

        open fun initLoggin() {

        }

        override fun call() {
       
        }
    }

    abstract class WrapperBase: Base {
         
          // These will be programmatically added here
          val subCommands

          
        override fun call() {
       
        }
    }

    class SubCommand:  WrapperBase {
         // More options specific to registration
    }

    // This is the top command
    class TopCommand: WrapperBase {

         @Mixin
         val cmdLineOptions

         // This is where the subcommands are initialised and added to subCommands 
         val mySubCommand = SubCommand()
    }

**Comment by remkop** [comment]
@palade Thank you for raising this! 

I want to try to reproduce the issue, so we can fix it.
 
The code you provided gives some hints at what you are trying to do, but I had some trouble getting it to compile. I made some changes, and it compiles now, but it is still incomplete and does not run yet. 

My version is [here](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/kotlin/picocli/examples/kotlin/globaloptions1105/TopCommand.kt). Can you help me make the minimal changes to get this to run so it demonstrates the issue?

**Comment by palade** [comment]
package picocli.examples.kotlin.globaloptions1105
    
    import picocli.CommandLine
    import picocli.CommandLine.*
    import java.util.concurrent.Callable
    import java.util.logging.Level
    import kotlin.system.exitProcess
    
    /**
     * This class is not an example (yet)
     * but is work in progress to resolve this issue:
     * https://github.com/remkop/picocli/issues/1105
     */
    @Command(mixinStandardHelpOptions = true)
    abstract class Base(val alias: String, val description: String): Callable<Any> {
    
        lateinit var args: Array<String>
    
        @Option(names = ["-v", "--verbose", "--log-to-console"],
                description = ["If set, prints logging to the console as well as to a file."]
        )
        var verbose: Boolean = false
    
        @Option(names = ["--logging-level"],
                completionCandidates = LoggingLevelConverter.LoggingLevels::class,
                description = ["Enable logging at this level and higher. Possible values: \${COMPLETION-CANDIDATES}"],
                converter = [LoggingLevelConverter::class]
        )
        var loggingLevel: Level = Level.INFO
    
        open fun initLogging() {
            println("$this is initializing logging with verbose=$verbose and loggingLevel=$loggingLevel")
        }
    
        override fun call() {
            println("Hello from $this; verbose=$verbose and loggingLevel=$loggingLevel")
        }
    }
    
    abstract class WrapperBase(alias: String, description: String): Base(alias, description) {
    
        // These will be programmatically added here
        val cmd by lazy {
            CommandLine(this).apply {
                commandSpec.name(alias)
                commandSpec.usageMessage().description(description)
                subCommands.forEach {
                    val subCommand = CommandLine(it)
                    it.args = args
                    subCommand.commandSpec.usageMessage().description(it.description)
                    commandSpec.addSubcommand(it.alias, subCommand)
                }
            }
        }
    
        override fun call() {
            println("Hello from $this; verbose=$verbose and loggingLevel=$loggingLevel")
        }
    
        val subCommands: Set<Base> by lazy {
            additionalSubCommands()
        }
    
        protected open fun additionalSubCommands(): Set<Base> = emptySet()
    }
    
    class SubCommand: WrapperBase("sub-command", "does some sub-command work")
    
    class TopCommand: WrapperBase("top-command", "does top-command work") {
    
        private val subCommand by lazy { SubCommand() }
    
        override fun additionalSubCommands() = setOf(subCommand)
    
        override fun call() {
            super.call()
        }
    }
    
    fun WrapperBase.start(args: Array<String>) {
    
        this.args = args
    
        val exceptionHandler = object : DefaultExceptionHandler<List<Any>>() {
    
            override fun handleParseException(ex: ParameterException?, args: Array<out String>?): List<Any> {
                super.handleParseException(ex, args)
                return listOf()
            }
            override fun handleExecutionException(ex: ExecutionException, parseResult: ParseResult?): List<Any> {
    
                val throwable = ex.cause ?: ex
                if (this@start.verbose || this@start.subCommands.any { it.verbose }) {
                    throwable.printStackTrace()
                }
                return listOf()
            }
        }
    
        val results = cmd.parseWithHandlers(RunLast().useOut(System.out),
                exceptionHandler.useErr(System.err), *args)
    
        // If an error code has been returned, use this and exit
        results?.firstOrNull()?.let {
            if (it is Int) {
                exitProcess(it)
            } else {
                exitProcess(0)
            }
        }
    
        exitProcess(1)
    }
    
    fun main(args: Array<String>) {
        val cli = TopCommand()
    
        // This does change the logging-level
        // The logging level is correctly set
        //cli.start(arrayOf("sub-command", "--logging-level=FINEST", "--log-to-console"))
    
        // This does NOT change the logging-level
        // The logging-level should be FINEST after this but it shows as INFO
        cli.start(arrayOf("--logging-level=FINEST", "--log-to-console", "sub-command"))
    }
    
    class LoggingLevelConverter: ITypeConverter<Level> {
        object LoggingLevels: Iterable<String> {
            override fun iterator(): Iterator<String> {
                return listOf(Level.ALL.name,
                        Level.CONFIG.name,
                        Level.FINE.name,
                        Level.FINER.name,
                        Level.FINEST.name,
                        Level.INFO.name,
                        Level.OFF.name,
                        Level.SEVERE.name,
                        Level.WARNING.name).iterator()
            }
        }
    
        override fun convert(value: String?): Level {
            return Level.parse(value)
        }
    }

**Comment by palade** [comment]
If the main is replaced with one below:

    fun main(args: Array<String>) {
        val cli = TopCommand()

        // This does change the logging-level
        // The logging level is correctly set
        //cli.start(arrayOf("sub-command", "--logging-level=FINEST", "--log-to-console"))

        // This does NOT change the logging-level
        // The logging-level should be FINEST after this but it shows as INFO
        //cli.start(arrayOf("--logging-level=FINEST", "--log-to-console", "sub-command"))

        cli.start(arrayOf("--help"))

        val stream = ByteArrayOutputStream()
        val ps = PrintStream(stream)
        CommandLine.usage(cli, ps)

        println(stream.toString())
    }

The usage message shows like:

    Usage: top-command [-hvV] [--logging-level=<loggingLevel>] [COMMAND]

This can be confusing because it shows that the global options and COMMAND can be placed in any order

**Comment by remkop** [comment]
@palade Great, thank you! I will take a look. It may take me some time, I am not very fluent in Kotlin (so this is a nice learning opportunity for me :-) ...

**Comment by palade** [comment]
@remkop Cheers for all the help. Integrated your suggested changes and global options can now be specified in any order

**Comment by remkop** [comment]
You are very welcome!
Enjoy using picocli!
