### ISSUE TITLE
manpage generator: encoding issue

### ISSUE THREAD

**Issue by deining** [remkop/picocli#1109]
Using the new man page generation feature, I tried to generate a man page for the [I18NDemo](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/i18n/I18NDemo.java) given in the examples section of the repo.

When invoking `ascciidoctor` on the produced `.adoc` file, I'm getting:

`Failed to load AsciiDoc document - invalid byte sequence in UTF-8`

I can easily cure this by adding the `encoding` attribute to the produced .adoc file:

```
// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:encoding: ISO-8859-1
```

IMHO, encoding is something that should be considered by the man page generator.
AFAIK, since Java 9, to can use UTF-8 encoding for your resource bundles, so simply adding the `encoding` attribute to the generated file seems to be no valid option for me. Maybe we can overcome this by adding an additional encoding option to the `gen-manpage` command?

**Comment by remkop** [comment]
I see, yes that makes sense. 
The default value would be the platform encoding, I guess. 
Sounds like a good idea. 
Will you be able to provide a pull request for this?
