### ISSUE TITLE
How to use mixins with Arg group?

### ISSUE THREAD

**Issue by ranjansrao** [remkop/picocli#1114]
Currently if i try to use @Mixins with @Arg groups, i get the error:@Mixins are not supported on @ArgGroups

**Comment by remkop** [comment]
Can you give more details on what you’re trying to achieve? Maybe with some example code?

**Comment by ranjansrao** [comment]
Just as i asked this question i found out that i can use nested Arg groups.So this issue can be closed.

**Comment by ranjansrao** [comment]
In my case, I have  options which are used in multiple commands.In some commands they are used independently and in other cases they are used mutually exclusive with other options.

**Comment by remkop** [comment]
Glad to hear that you’ve been able to resolve the issue!
Enjoy picocli!
