### ISSUE TITLE
Map<String, String> i.e. -Dkey=value does not work on windows

### ISSUE THREAD

**Issue by maxandersen** [remkop/picocli#1122]
I noticed that when doing this:

```
@CommandLine.Option(names = { "-D" }, description = "set a system property")
	Map<String, String> properties = new HashMap<>();

```

which allows me to do `-Dxyz=123` on linux/osx breaks on windows with errors like:

`Value for option option '-D' (<String=String>) should be in KEY=VALUE format but was xyz`

Reason for that is that the values passed into picocoli under command.exe is:

"-Dxyz"
"123"

rather than "-Dxyz=123"

**Comment by remkop** [comment]
(Away from PC) Is this with a wrapper script or when typing the command into a Command Prompt shell directly? Also, (assuming the latter) were any parts of the typed command quoted?

**Comment by maxandersen** [comment]
I could have sworn I tested without wrapper but just verified again and yes its when wrapping...closing as then it must be yet another subtlety in windows batch scripting; not picocli.

**Comment by remkop** [comment]
Hi Max, the ticket is still open, but your comment says closing.
Just double-checking: you're okay to close this?

**Comment by maxandersen** [comment]
yes, closing - it happend because of use of "FOR /f" which does inexplicable things.

**Comment by remkop** [comment]
Understood. Thank you!
