### ISSUE TITLE
Seems like picocli tries interpolate variable when encounter dollar sign in user input parameter

### ISSUE THREAD

**Issue by alex-dukhno** [remkop/picocli#1135]
Hi 👋 

we have the following command:
```java
class UpdateUserPassword implements Runnable {
    @Option(names = {"-n", "--username"},
            required = true,
            paramLabel = "<username>",
            description = "Username for the user record."
    )
    private String username;

    @Option(names = {"-p", "--password"},
            paramLabel = "<password>",
            description = "Password for the user record. "
                    + "Provide value directly or use without value to enter securely with interactive prompt.",
            arity = "0..1",
            interactive = true
    )
    private String password;
}
```

running command with the following parameters:
```shell
update-password -n=read_only -p=t3stP@$s -v
```
the `password` field contains `t3stP@` value

`.getCommandSpec().interpolateVariables(false)` does not help

the only way to preserve `$` in the user input we found is to escape a dollar sign

**Comment by alex-dukhno** [comment]
Closing. We use shell script to run commands and it is shell problem to escape dollar sign. Sorry for inconvenience

**Comment by remkop** [comment]
Hi @alex-dukhno, no worries at all, thanks for the update! Your explanation makes sense.

Enjoy using picocli and don't hesitate to let me know if there are any questions.
