### ISSUE TITLE
Problems with readLine on Windows 7 cmd. Not all keystrokes are being picked up.

### ISSUE THREAD

**Issue by smalirizvi** [remkop/picocli#1139]
I have been working on a Linux machine and everything works great. As soon as I tried to run it on Windows 7 this started to create problems as the line reader is not picking up all keystrokes. I am on the latest version of picocli.

**Comment by remkop** [comment]
Hi, I suspect that you are using jline?
Picocli does not process keystrokes, the readline functionality is in the jline project.
Would you mind opening a ticket in either [jline2](https://github.com/jline/jline2) or [jline3](https://github.com/jline/jline3), depending on which version you are using?

**Comment by smalirizvi** [comment]
Created.
https://github.com/jline/jline3/issues/561

**Comment by remkop** [comment]
@smalirizvi Thanks!

If you can provide a way to reproduce the problem in that ticket, you improve your chances of the JLine maintainer being able to help you.

Either showing code or pointing to a public repo with a program demonstrating the issue.

**Comment by smalirizvi** [comment]
I just had to flush and close the terminal each time I built a new one.
