### ISSUE TITLE
Improve docs for interactive options (was:Input on interactive flag not working on Windows cmd)

### ISSUE THREAD

**Issue by smalirizvi** [remkop/picocli#1140]
Input is not being taken in on interactive flag set to true when entering input on windows cmd.

**Comment by remkop** [comment]
Are you using jline2? 
Is this issue perhaps similar to this one: https://github.com/remkop/picocli/issues/767

**Comment by remkop** [comment]
@smalirizvi, are you using JLine 2?

If so, there is a workaround:  use a [custom parameter consumer](https://picocli.info/#_custom_parameter_processing) that uses the JLine 2 API to read a password interactively from the console.

The picocli-shell-jline2 [README](https://github.com/remkop/picocli/tree/master/picocli-shell-jline2) has an example: see the `InteractiveParameterConsumer` class in the README.

**Comment by remkop** [comment]
@smalirizvi Can you provide more information on how to reproduce this issue?

**Comment by remkop** [comment]
I am going to assume that you expected picocli to prompt the user for input when the program is invoked without any options.
Instead, when an option is marked as `interactive = true`, then picocli prompts the user when the option is specified:

```bash
$ myprogram --interactive-option
Enter value for --interactive-option (...):
```

Applications that also need the user to be prompted when the option is _not specified_, need to do this in the business logic.
For example:

```java
@Command
public class Main implements Runnable {
    @Option(names = "--interactive", interactive = true)
    String value;

    public void run() {
        if (value == null) {
            // alternatively, use Console::readPassword
            value = System.console().readLine("Enter value for --interactive: ");
        }
        System.out.println("You provided value '" + value + "'");
    }

    public static void main(String[] args) {
        new CommandLine(new Main()).execute(args);
    }
}
```

I believe this question has come up before, so I will add this example to the user manual.
