### ISSUE TITLE
site picocli.info doesn't work

### ISSUE THREAD

**Issue by safronau** [remkop/picocli#1145]
Can not access to https://picocli.info/

**Comment by remkop** [comment]
I just tried on my phone and it looks fine to me. 

Do you get an error message? What do you see?

**Comment by safronau** [comment]
Sorry, it seems like all "info" sites are blocked in my country. It works from TOR browser. I just have not been realized this before.

**Comment by remkop** [comment]
Oh no! I did not realize that.
I will look into adding another domain, in addition to picocli.info (this will take me some time)...

**Comment by safronau** [comment]
I think it is not required. We had elections last Sunday. I believe it's temporary. They just do not know what to block.

**Comment by remkop** [comment]
I see. Thank you for the clarification. 
Be safe!
