### ISSUE TITLE
How to print options of subcommands during help usage

### ISSUE THREAD

**Issue by DeveloperJVM** [remkop/picocli#1146]
I have three commands and which have some options
1) -l --load
2) -v --validate
3) -g --generate

```
new CommandLine(mainCommand)
                .addSubcommand("-l", loadCommand,"--load")
                .addSubcommand("-v", validateCommand,"--validate")
                .addSubcommand("-g", validateCommand,"--generate");
```
When I use this line "commandLine.usage(System.out)" for printing my commands and their options 
it prints only name of the commands
```
-l, --load
-v, --validate
-g, --generate
```

I want to print command options too like this one

```
load command
-l --load (required)
                  -i --instance <instance file> (required) 
                  -lk --linkFile <link file> (optional)
                  -s --scheme <scheme file> (optional),
valid command
-v --validate (required)
                  -vf --validateFille <validate file> (required)
generate command
-g --validate (required)
                  -gf --generateFille <generate file> (required)

```
I see that there is way to generate it in a custom way [picocli.info/#_custom_synopsis](https://picocli.info/#_custom_synopsis)
but I need to do it automatically.
Is it possible to do?

**Comment by remkop** [comment]
Each command can have many options, so picocli by default only shows the options and subcommands of the command for which help was requested. 

So, if you do :

```
<cmd> --load --help
```

... then picocli will display the synopsis, options and subcommands of the `--load` command. 

It is possible to customize this, see some examples here: https://github.com/remkop/picocli/tree/master/picocli-examples/src/main/java/picocli/examples/customhelp

(I don’t think there’s an example that shows subcommands _and_ their options.)

**Comment by DeveloperJVM** [comment]
thank you for answer
It is clear now How it works

**Comment by remkop** [comment]
Glad to hear that. 
Let me know if you have follow-up questions or whether you want to close this ticket.

**Comment by remkop** [comment]
Closing this ticket. Feel free to open new tickets as new questions come up.
