### ISSUE TITLE
Is there a way to get the default value of an unset option from a ParseResult?

### ISSUE THREAD

**Issue by metacosm** [remkop/picocli#1148]
If my option is unset, `parseResult.matchedOption('o')` returns `null` but I would have expected a way to get the "matched by default" option value without having to basically duplicate the default value that I already provided when defining my option. Is this possible?

**Comment by remkop** [comment]
Yes, you can use the `OptionSpec::getValue` method to get the value that ended up being assigned to that option. In your example, you could do `parseResult.commandSpec().findOption('o').getValue()`.

The return value of `OptionSpec::getValue`  may be the default value or it may be a command line argument if the option was specified on the command line.

The methods in the `ParseResult` class focus on what was actually specified on the command line. That is why `ParseResult::matchedOption`  returns `null` if the option was not specified on the command line. This allows applications to differentiate between default values and user-specified values.

**Comment by metacosm** [comment]
Thank you, this works perfectly!

**Comment by remkop** [comment]
Glad to hear that!
Enjoy picocli!
