### ISSUE TITLE
Gradle Module Metadata for picocli 4.4.0+ missing from Maven Central

### ISSUE THREAD

**Issue by fpavageau** [remkop/picocli#1152]
[picocli-4.4.0.pom](https://repo1.maven.org/maven2/info/picocli/picocli/4.4.0/picocli-4.4.0.pom) was generated with the following comment
```xml
<!--  This module was also published with a richer model, Gradle metadata,   -->
<!--  which should be used instead. Do not delete the following line which   -->
<!--  is to indicate to Gradle or any Gradle module metadata file consumer   -->
<!--  that they should prefer consuming it instead.  -->
<!--  do_not_remove: published-with-gradle-metadata  -->
```
which triggers the download by Gradle of the `picocli-4.4.0.module` artifact, however that artifact was not published to Maven Central. This is probably a consequence of the upgrade to Gradle 6 in 98dc696565d8a0c215ed98a9a403bf3262b47af4.

This is a problem when using Artifactory as a Maven proxy, because by default Artifactory returns a 403 HTTP status code for missing artifacts, and Gradle only ignores an absent `.module` when the repository returns a 404 HTTP status code. In my case (and others, probably), that means my build fails when it cannot download `picocli-4.4.0.module`. 😭 

See rsocket/rsocket-java#746 for a similar issue in another project (resolved by rsocket/rsocket-java#751).

**Comment by remkop** [comment]
Ouch! I wasn’t aware of this, thanks for letting me know!

I’ll probably use the same fix: disable the feature for now.

**Comment by remkop** [comment]
I pushed a change that fixes the issue (disables generation of the `picocli-4.4.0.module` artifact).
I will do a release for this as soon as possible.

**Comment by remkop** [comment]
Picocli 4.5.1 has been released. This should fix the issue.

Don't forget to star ⭐ picocli on GitHub if you like the project! 😉
