### ISSUE TITLE
jline3 example should close Terminal (using try-with-resource or try-finally)

### ISSUE THREAD

**Issue by dwalluck** [remkop/picocli#1168]
Should this line ensure that the terminal is closed? https://github.com/remkop/picocli/blob/72e1d4f2d35f8c12a0b64d8fcd47c2df02269c9f/picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java#L165

In the docs https://www.javadoc.io/doc/org.jline/jline/3.14.1/org/jline/terminal/Terminal.html it states that "Terminals should be closed by calling the Closeable.close() method in order to restore their original state" although I cannot tellw ithout looking at the code what resources it might actually free and what constitutes the "original state".

**Comment by remkop** [comment]
Yes, looking at some Terminal implementations it seems quite important that `close` is called.
See for example [`AbstractWindowsTerminal`](https://github.com/jline/jline3/blob/fdc2fb53f9dc618bfccc3b20ae447cabce3a809f/terminal/src/main/java/org/jline/terminal/impl/AbstractWindowsTerminal.java#L216).

I will fix this when I get a chance.

**Comment by dwalluck** [comment]
> Yes, looking at some Terminal implementations it seems quite important that `close` is called.
> See for example [`AbstractWindowsTerminal`](https://github.com/jline/jline3/blob/fdc2fb53f9dc618bfccc3b20ae447cabce3a809f/terminal/src/main/java/org/jline/terminal/impl/AbstractWindowsTerminal.java#L216).
> 
> Thank you for pointing this out!
> I will fix this when I get a chance.

It seems it is doing quite a bit, thanks! If you want I can make a PR for you for the example. If I remember correctly, you are on Java 1.5, so try-with-resource is not an option.

**Comment by remkop** [comment]
A PR would be really great!

That module (`picocli-shell-jline3`) is compiled with Java 8 because JLine3 requires Java 8, so actually both the doc and the running example could use try-with-resources.

Thanks as always for your help!
