### ISSUE TITLE
Disabling POSIX format in help

### ISSUE THREAD

**Issue by madeinjapan** [remkop/picocli#1177]
I want to disabling POSIX format if I print help.

actual result:
`Usage: command [-hu] [-j JSON] other`

expected result:
`Usage: command [-h] [-u] [-j JSON] other`

**Comment by remkop** [comment]
This can be accomplished by subclassing the `Help` class and overriding the `detailedSynopsis` method: the last parameter (`clusterBooleanOptions`) controls whether boolean POSIX options are clustered in the synopsis of the usage help message.

I added [this example](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/customhelp/CustomSynopsisNonPosix.java) to demonstrate.

Does that meet your requirements?

**Comment by madeinjapan** [comment]
Yes, exactly! It's perfect! Thank you.

And

I want cusomize my positional arguments omit in help. Create a new issue from this?

**Comment by remkop** [comment]
Glad to hear that!

> I want to customize my positional arguments omit in help. Create a new issue from this?

Yes, if you can create a separate ticket that would be good.

----
Don't forget to star ⭐ picocli on GitHub if you like the project! 😉
