### ISSUE TITLE
Can't pass values to the int[] option

### ISSUE THREAD

**Issue by realkarmakun** [remkop/picocli#1180]
I don't really have idea where to seek for help so I'm writing an issue here. 
So a bit of clarification I have parent command `cimp` which have subcommand `affine` which have subcommand `encrypt`. I only have a problem with passing a pair of integers as option in array.
(I also have some parameters but they are not necessary right now)

So I have following code in encrypt class:
```
@CommandLine.Command(name = "encrypt", aliases = "e")
public class AFEncrypt implements Callable<Integer> {

    @CommandLine.Option(names= {"-k, --key"}, split = ",")
    protected int[] key;


    @Override
    public Integer call() {
        System.out.println(Arrays.toString(key));
        return 0;
    }
}
```

But when I try to do `java -jar kmzi-1.0-SNAPSHOT-all.jar cmip affine encrypt --key 1,2` 
I get following output:
```
Unknown options: '--key', '1,2'
Usage: cmip affine encrypt [-k, --key=<key>[,<key>...]]...
      -k, --key=<key>[,<key>...]
```

I'm really not sure what is going on. Is my input wrong or something?

**Comment by remkop** [comment]
Hi, 

The problem is that the option names should be quoted individually:

```
names= {"-k, --key"}
```

Should be:

```
names= {"-k", "--key"}
```

**Comment by realkarmakun** [comment]
I see, oh my god such a stupid mistake. Sorry for disturbance and thanks for your help :)

**Comment by remkop** [comment]
No worries. 👍  We're only human. 😉 

How do you like picocli so far? ❓

**Comment by remkop** [comment]
Don’t forget to star ⭐️ picocli on GitHub if you like the project! 😉

**Comment by realkarmakun** [comment]
Hey @remkop, I hope it's okay to tag you. I do like picocli (I made a little project for my assignment with it before, but now I ran into some problems)
So my goal is to make a program with following command structure:
```
cmip
│
├── affine
│      │
│      ├── encrypt
│      │ 
│      └── decrypt
│
└── some other command for next tasks
```
But I keep getting `Unmatched argument at index 0: 'cmip'` if I use my subcommand properly. So right now I have the following code:

```java
@CommandLine.Command(name = "encrypt", aliases = "e")
public class AFEncrypt implements Callable<Integer> {

    @CommandLine.Parameters()
    public String file;

    @Override
    public Integer call() {
        System.out.println(file);
        return 0;
    }
}
```
So executing `java -jar kmzi-1.0-SNAPSHOT-all.jar cmip affine e test.txt` should just print `test.txt` in console, but I get `Unmatched argument at index 0: 'cmip'` instead. 
Just for the sake of context I'm running my jar in WSL2 and building it with Gradle and ShadowJar plugin.

Also for context how I handle subcommands (it's pretty much the same everywhere):
```java
@CommandLine.Command(name = "affine", aliases = "af", subcommands = {
        AFEncrypt.class,
        AFDecrypt.class
})
public class AffineCipher {
    // nothing here
}
```

The help message works just fine by the way (If I try to run command without `file` paramter) I get following message:
```
Missing required parameter: '<file>'
Usage: cmip affine encrypt <file>
      <file>
```
I guess it would be more convenient to ask such kind of question on StackOverflow, but since I made an issue here I thought to give it a try while I'm at it. I hope that's okay.

**Comment by remkop** [comment]
@realkarmakun First of all, I welcome all questions. It is no problem to use GitHub issues for questions or to tag me in questions, I do prefer to have a new GitHub issue for each question; that way, if the question reveals some problem in picocli, it is easier to track for me if the full history is in the GitHub issue. 😉 

About your question (why does this command result in an error):

```
java -jar kmzi-1.0-SNAPSHOT-all.jar cmip affine e test.txt
Unmatched argument at index 0: 'cmip'
```

This (without `cmip`) should work correctly:
```
java -jar kmzi-1.0-SNAPSHOT-all.jar affine e test.txt
```

Why: the way I think of it, `java -jar kmzi-1.0-SNAPSHOT-all.jar` _is_ the `cmip` command.

This allows you to create a wrapper script called `cmip` that invokes `java -jar kmzi-1.0-SNAPSHOT-all.jar @*`, or even use GraalVM to convert kmzi-1.0-SNAPSHOT-all.jar into a native image called `cmip`: that way, your end users can just invoke the application like this:

```
cmip affine e test.txt
```

The picocli manual has a section on [packaging your application](https://picocli.info/#_packaging_your_application), in case you are interested in creating such wrapper scripts or using GraalVM. 

This stackoverflow [question](https://stackoverflow.com/questions/62963202/why-doesnt-picocli-recognize-my-option-from-the-command-line) has some more thoughts on this topic.

Don't hesitate to ask more questions!

**Comment by realkarmakun** [comment]
Oh, that actually makes sense. Thank you very much, now it works. By the way Graal native image looks interesting I'll look into that. And thank you again :smile:
