### ISSUE TITLE
Custom subcommand summary description and name

### ISSUE THREAD

**Issue by madeinjapan** [remkop/picocli#1185]
Is there a way to make a summary description for subcommands and change name in the help?

actual result:
```Usage: [-h] action
optional arguments:
  -h, --help   Show this help message and exit.
positional arguments:
  action1
  action2
  action3
```

expected result:
```Usage: [-h] action
positional arguments:
  action       Change action from actions list.
optional arguments:
  -h, --help   Show this help message and exit.
```

I use subcommands and I run the class which matching the first argument. My classes are ```@Command``` annotation and name key (the first argument).

Here is my main class annotation:

```
@CommandLine.Command(name = "",
        subcommands = {
            Command1.class,
            Command2.class,
            Command3.class },
        synopsisSubcommandLabel = "action",
        commandListHeading = "positional arguments:%n",
        optionListHeading = "optional arguments:%n",
        separator = " ",
        synopsisHeading = "Usage:")
```

Thank you for help!

**Comment by remkop** [comment]
Yes, you can reorder the sections of the usage help message.
It looks like you want to display the command list heading and the command list before the option list heading.

The documentation for reordering sections is here: https://picocli.info/#_reordering_sections

What you want to do is something like this:

```java
CommandLine cmd = new CommandLine(new MyApp());

// create a modifiable list that contains the help section ordering
List<String> keys = new ArrayList<>(cmd.getHelpSectionKeys());

// remove the command list heading and command list 
keys.remove(CommandLine.Model.UsageMessageSpec.SECTION_KEY_COMMAND_LIST_HEADING);
keys.remove(CommandLine.Model.UsageMessageSpec.SECTION_KEY_COMMAND_LIST);

// find the insertion point
int index = keys.indexOf(CommandLine.Model.UsageMessageSpec.SECTION_KEY_OPTION_LIST_HEADING);

// put the sections back at the new location
keys.add(index, CommandLine.Model.UsageMessageSpec.SECTION_KEY_COMMAND_LIST_HEADING);
keys.add(index + 1, CommandLine.Model.UsageMessageSpec.SECTION_KEY_COMMAND_LIST);

// and install the new ordering
cmd.setHelpSectionKeys(keys);
```

**Comment by madeinjapan** [comment]
Ooooh man... sorry. I didn't look around carfully :/

I didn't think it was that simple. Thank you!

And what is the solution or how do I look for this problem:

I want to pack the name of subclasses into one with one description.
The `actions` is the name of subclasses (e.g.action = {action0, action1, acttion2}).

synopsisSubcommandLabel = "actions",
synopsisSubcommandName = "actions",
synopsisSubcommandDescription = "Select action from actions list",


```positional arguments:
  actions       Select action from actions list.
optional arguments:
  -h, --help   Show this help message and exit.```

**Comment by remkop** [comment]
I don't think there is an easy way to accomplish this.
The picocli default (which follows conventions I have seen for other command suite CLIs) is to show the name for each subcommand, and a description of what each subcommand does. Isn't that better than having one description for multiple commands?

**Comment by remkop** [comment]
Well, there is a way (with picocli there is always a way 😄 ):

* make all subcommands hidden (via `@Command(hidden = true)`. This means that the individual subcommands are not shown in the usage help. (And, when all subcommands are hidden, the `commandListHeading` is also not shown.)
* put the packed single description for subcommands in the _option list heading_. Something like this:

```java
@Command(name = "...",
optionListHeading = "positional arguments:%n  action       Change action from actions list.%noptional arguments:%n"
...
```

**Comment by remkop** [comment]
@madeinjapan Did this answer your question?

**Comment by remkop** [comment]
@madeinjapan Can this ticket be closed?

**Comment by madeinjapan** [comment]
Sorry to answer late....

Yes, it is a good solution. Thank you. Although I take a dfferent way... and you are right about conventions.
I replaced the subcommand heading :)

This is my solution:

`
possible actions:
  action1
  action2
  action3
optional arguments:
  -h, --help   Show this help message and exit.`


You are right: 'with picocli there is always a way' :)

**Comment by remkop** [comment]
Great to hear that you found a solution you are happy with!

Enjoy using picocli!
