### ISSUE TITLE
How to make subcommand required?

### ISSUE THREAD

**Issue by r2mzes** [remkop/picocli#1193]
I would like to make a subcommand required, could you please advise how to do it? ;>

Let' say I have one main command defined like this:
```
@CommandLine.Command(name = "main", subcommands = { LoadCommand.class, ValidateCommand.class, RenderCommand.class }, subcommandsRepeatable = true) 
public class MainCommand
```

How can I make LoadCommand subcommand required and other subcommands optional?
I use the basic parsing approach with ParseResult.

I would appreciate your help :)

**Comment by remkop** [comment]
To make it mandatory for users to specify a subcommand (so they cannot specify the top-level command on its own), the [easiest way](https://picocli.info/#_required_subcommands) is for the top-level command class to _not_ implement `Callable` or `Runnable`, and start the application with the [execute API](https://picocli.info/#execute).

This makes _any_ subcommand mandatory. 

To make the `LoadCommand` required and the `ValidateCommand` and `RenderCommand` optional, I would suggest making these last two commands subcommands of the `LoadCommand`:

```
main
  |
  +-- load
       |
       +-- verify
       +-- render
```

I am not sure what you mean by "I use the basic parsing approach with ParseResult".
Are you not using the `execute` API? That makes it a bit harder. :-) You will basically need to duplicate the [RunLast execution strategy](https://picocli.info/#_executing_commands_with_subcommands) in your application. Can you clarify why the `execute` API does not meet your requirements?

**Comment by r2mzes** [comment]
Thank you for your answer :) 
Yes, you got it right :P I fell like I cannot use execute API, but maybe I am missing sth :P

My scenario:
In my application I have couple of steps that are launched in a pipeline manner:
load **->** validate (validation_1,  validation_2) **->** render (rendering_1, rendering_2)

Validate step requires artifacts that are created in the load step
Render step requires artifacts that are created in the load step and in the validate step

Now when I thought about how to design a command line interface i came up with sth like this

![image](https://user-images.githubusercontent.com/3853198/94803080-0d47ba80-03e9-11eb-927a-6a3343e782c1.png)

where:

- load, validate, render are commands

- validation_1, validation_2 are validate subcommands

- rendering_1, rendering_2 are render subcommands

This is how I designed it and I feel like it would be hard to fit execute API here. Thus I decided to use only ParseResult to have more control over the application flow and so on.

Another thing is repeatable subcommands not going up hierarchy (#1149), which makes it impossible to parse command line args using the above interface.

But maybe I misunderstood sth and I chose not neceserriily the best path, thus if you feel like there is a better aproach to it, I would be glad to hear :)

**Comment by remkop** [comment]
Perhaps you could consider the `RunAll` execution strategy? 
[This section](https://picocli.info/#_executing_commands_with_subcommands) in the user manual has a short example.

If you do need to create your own handling of the `ParseResult`, I recommend you start with these two lines, to handle requests for `--help` or `--version` for any of the subcommands:

```java
        Integer helpExitCode = CommandLine.executeHelpRequest(parseResult);
        if (helpExitCode != null) { return helpExitCode; }
```

**Comment by r2mzes** [comment]
Ok, thank you, I will give it a try and will come back with some remarks if I have any ;)
