### ISSUE TITLE
required parameter does not exclude negated options

### ISSUE THREAD

**Issue by keturn** [remkop/picocli#1197]
Given code like this:

```java
    @Option(names = "--crash-report", defaultValue = "true", negatable = true)
    private boolean crashReportEnabled;

    @Option(names = "--homedir")
    private Path homeDir;
```

if invoked with `--homedir --crash-report`, it quits as expected with this message:

> Expected parameter for option '--homedir' but found '--crash-report'

But if invoked with the boolean option's negated form `--homedir --no-crash-report` it assigns `--no-crash-report` as the value of `homeDir`.

using picocli and picocli-codegen version 4.5.1.

**Comment by remkop** [comment]
Thank you for reporting this!
That looks like a bug. Looking into it.

**Comment by remkop** [comment]
Sorry for the delay.
I found the cause and pushed a fix to master.
This fix will be included in the next release.
Thanks again for raising this!

**Comment by remkop** [comment]
Picocli 4.5.2, which contains the fix for this issue, has been released.
Enjoy!
