### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by RobAltena** [remkop/picocli#120]
Even though all one needs is the CommandLine.java file, the project should benefit from having a jar in the maven repository. That will make it that much easier for other projects to pull in.

**Comment by remkop** [comment]
Your wish is our command:
Please see [https://search.maven.org/#search%7Cga%7C1%7Cpicocli](https://search.maven.org/#search%7Cga%7C1%7Cpicocli)
and [https://bintray.com/remkop/picocli/picocli](https://bintray.com/remkop/picocli/picocli)

Closing as fixed. Please reopen if there's any issue.
