### ISSUE TITLE
Stopping command while having an endless loop

### ISSUE THREAD

**Issue by Blubb324** [remkop/picocli#1206]
Hey guys,

I have a simple program and wanted to try it with picocli. My question is, what´s the "best" design for a stopping command while having an endless loop. E.g. my application is printing all 5 seconds the current date. So it´s an endless loop and there is never an exit command. Addionally I have seen that the Thread is still running if I´m closing the cmd.

Source:
```
import java.util.Date;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.Option;
import picocli.CommandLine.Spec;

@Command(name = "java -jar example.jar")
public class PicocliExample implements Runnable {

	@Option(names = { "-d", "--delay" }, required = false)
	private int delay = 5000;

	@Option(names = { "-h", "--help" }, usageHelp = true, description = "Hilfe")
	private boolean helpRequested = false;

	@Override
	public void run() {
                // Maybe some condition here when e.g. ctrl + c is pressed?
		while (true) {
			System.out.println(new Date());
			try {
				Thread.sleep(delay);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
	}

	public static void main(final String... args) throws Exception {
		int exitCode = new CommandLine(new PicocliExample()).execute(args);
		System.exit(exitCode);
	}
}
```
Do you have any ideas?
Thank you in advance, I really appreciate this project. :)

**Comment by remkop** [comment]
For a long-running program, the user would need to send some signal to the process to tell it to stop running.
Ctrl-C is a commonly used signal, that will cause the Java runtime to exit. Before exiting, all [shutdown hooks](https://docs.oracle.com/javase/8/docs/technotes/guides/lang/hook-design.html) are executed. If you have any logic that needs to run before exiting, that would be the place to do it.

Does this answer your question?

About exit codes:
The `main` method currently calls `System.exit`; this is only called when the user made a syntax mistake (entered a non-numeric value for `--delay`, for example) or when the `run` block throws a `RuntimeException`. (Exit code will be 2 for invalid user input and 1 for runtime exceptions.)

I don't think there is a way to control the exit code from a shutdown hook.

**Comment by remkop** [comment]
An alternative design (a bit more complex) is to have the command start a server socket, and wait for some command text to be received via the network. Users could then use the `nc` utility to send this text, something like this:

```
echo -n 'Line of text' | nc <ip> <port>
```

**Comment by Blubb324** [comment]
All right. Thank you!
