### ISSUE TITLE
Can you put Parameter before Options?

### ISSUE THREAD

**Issue by hegerdes** [remkop/picocli#1207]
Hi,

I'm just getting started with picocli but I'm impressed by its features and the **very** good support. 
I have a very basic question that I wasn't able to answer with the docs.

My program has two major features: Utility apps and Simulations.
I want to: `java -jar my.jar app | simulation`

The apps and simulation scenarios have names(required) and optional parameter
I configured app and simulation to be subcommands.

So I want to do:
`java -jar my.jar simulation <name> [scenario options]` or 
`java -jar my.jar app <name> [app options]`

another example would be something like: `git merge  master -s recursive`

But if I try I only get it working to `java -jar my.jar simulation [scenario options] <name> `

It feels like I'm missing one simple trick.

Also I know that I could make every scenario a subcommand but:
- They have many options in common
- Want cli and models separated
- The CLI parsing only creates a internal config that is than used by the scenarios. This helps to keep the input methods modular and independent. 

Would appreciate any help.

**Comment by remkop** [comment]
Hi,

It sounds like you are doing everything correctly. Not sure if I understood the problem. 

Picocli doesn’t care about the order of named options and positional parameters: for example, this:

```
java -jar my.jar simulation [scenario options] <name>
```

is interpreted the same as this:

```
java -jar my.jar simulation <name> [scenario options]
```

The end user is free to specify positional parameters before or after the named options. 

Does that answer your question?

**Comment by hegerdes** [comment]
Thanks, seams like I did some other error than. Input works now.

Just need to figure out how I can customize the help messages but this shouldn't be a problem.

Thanks a lot. Questions is answerd.

**Comment by remkop** [comment]
Great to hear that!
Enjoy picocli!

If you like the project, please star ⭐ picocli on GitHub and tell your friends! 😉
