### ISSUE TITLE
Support Map options with key-only (support -Dkey as well as -Dkey=value)

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1214]
From the picocli google group by @maxandersen:

> I might already asked this but couldn't find the answer...
> 
> is there a way to have something like:
> 
> @CommandLine.Option(names = { "--D" })
> Map<String, Optional<String>> properties;
> 
> similar to how key/value properties works in maven that -Dxyx means xyz is set.
> 
> in other words - anyway to mark that the [=value] part is optional ?

----
(my reply on the mailing list)

Currently (as of picocli 4.5.1), unfortunately not: 
picocli will throw an exception (Value for option -D should be in KEY=VALUE format but was xyz)
if the value for the -D option does not contain a '=' character.

Would you mind raising a ticket on the picocli GitHub issue tracker for this? (It is easier for me to track TODO items on GitHub than on Google groups...)

There are several ways this could be improved:

* make the value optional if the Map is defined with Optional for the value type: Map<KeyType, Optional<ValueType>>
* have a parser option like CommandLine.setMapOptionsRequireValue (default true for backwards compatibility)
* have an annotation attribute like fallbackValue (perhaps a different one, unsure if it is a good idea to use the existing `fallbackValue` attribute for this)
* it would also be nice to have some way for applications to customize the Key-Value separator (currently it is hard-coded to '=')

**Comment by dwalluck** [comment]
@remkop Someone had just asked about one of our tools supporting `-Dkey` as being equivalent to `-Dkey=true` similar to what `mvn` allows.

At first I hoped that it could be done via the [customer parameter processing](https://picocli.info/#_custom_parameter_processing ) feature. If I could simply preprocess the command line to change `-Dkey` to `-Dkey=true` as if that was literally what the user had typed on the command line, then no changes to the `Map` processing would be necessary.

Also, a lot of the handling for the `Map` type is complex and all the methods are `private` anyway so it really doesn't seem possible to override this behavior.

**Comment by remkop** [comment]
I’m working on this now. 
This will be in the next release.

**Comment by dwalluck** [comment]
As a general question, I was just wondering if preprocessing the tokens on the command line to agree with the expected input of the parser might help as a general solution rather than having to add custom code the parser every time. 😃

**Comment by remkop** [comment]
I can see why a custom `IParameterConsumer` is not easy to create for this case. The map processing is quite complex.

It may be interesting to introduce a new `IParameterPreProcessor` API, where the difference with `IParameterConsumer` is that after the preprocessor is invoked, picocli may still process the value (perhaps depending on the return value of the preprocessor). This may also be a good solution for #1217. Thanks for raising this idea!

**Comment by remkop** [comment]
My current thoughts on the behaviour for when `-Dkey` is specified without value:

* if the Map is defined as `Map<K, Optional<V>>`, picocli will add an entry for the specified key and value `Optional.empty()`
* Otherwise, the default value becomes `""` (an empty String). This is similar to the behaviour of system properties when `-Dkey` is specified without value on the command line.
* For some value types, converting the empty String to that type will cause an exception. This is not a real change: it is similar to end users previously specifying `-Xkey=`; with this change, the `=` simply becomes optional when there is no value.
* Previously, picocli would throw an exception ("Value for option -D should be in KEY=VALUE format but was xyz"). Applications relying on this exception will need to make changes and add validation to their business logic.

It would be nice to also support other key-value separators for Map options.
I am thinking this should be a new attribute in `@Option` and `@Parameters`, perhaps `mapKeyValueSeparator`.
I will create a separate ticket for that.

**Comment by remkop** [comment]
I may split off the support for `Map<K, Optional<V>>` to another ticket (I will add a comment to #1108),
and go ahead with implementing this so that the value becomes `""` (empty space) when `-Dkey` is specified.

Support for `Optional` is more involved because it may requires changes to type converters and to how types are represented internally.

**Comment by remkop** [comment]
After looking at this some more, it may be more generic to let the value become `null` instead of `""` (empty String) when `-Dkey` is specified. This would allow Map options with other generic types than String to work without error, for example:

```java
@Option(names = "-x") Map<String, Integer> map;
```

One potential drawback is that applications that relied on the picocli validation may not be ready to deal with `null` map values and get `NullPointerException` at runtime.

**Comment by maxandersen** [comment]
but that code would also not have supported `-Dkey` before ...so I would say this sounds like a ok compromise.

**Comment by remkop** [comment]
True.

That said, it could be argued that this change breaks existing applications: we went from user-facing validation (nice error message like "Value for option -D should be in KEY=VALUE format but was key") to an internal error (stacktrace with a `NullPointerException` somewhere in the business logic).

What would be a nice way to be backwards compatible? 

One idea: retain the validation by default. Then, applications who want to allow key-only map options (like `-Dkey`) can do either:
* enable this globally with a new parser option like `CommandLine.setMapOptionsRequireValue(false)`  (_better naming ideas welcome_). This allows `null` values in Map options.
* use `Optional` in the map type: `Map<K, Optional<V>>` (TODO check if it is feasible to switch off the validation based on the map generic type)

Thoughts?

**Comment by dwalluck** [comment]
Why is is better globally vs. adding a new parameter on the annotation?

You could also specify on the annotation how to map default/empty values, so that instead of `null` maybe you can specify `Boolean.TRUE` or some method returning an `Object`.

Although in general I do agree that `null` is better that `""` which implies `Map<String,String>` only, but again, in that case you could still have a `static <T> T valueOf(String)` option to map any string back to the object you want.

**Comment by dwalluck** [comment]
What I am thinking is you already have the `defaultValue` annotation that could be useful here https://picocli.info/#defaultValue-annotation.

**Comment by remkop** [comment]
> Why is is better globally vs. adding a new parameter on the annotation?

Good question. I was thinking that a global option would be more convenient than having to specify an `enableKeyOnlyMapArgs` (or something like that) attribute on every `Map` option or positional parameter.

> You could also specify on the annotation how to map default/empty values, so that instead of null maybe you can specify Boolean.TRUE or some method returning an Object.
> ...
> What I am thinking is you already have the defaultValue annotation that could be useful here (...)

Also a good point, let's analyze this. 

## defaultValue

I think `defaultValue` is slightly different and cannot be used here: the `defaultValue` is assigned when the option was not specified on the command line at all. 

## fallbackValue

We could appropriate [`fallbackValue`](https://picocli.info/#fallbackValue-annotation) for Map options to mean the value to put in the map when only the key is specified., but this would have the drawback that `fallbackValue` is never `null`. Many (most?) applications may like to have `null` map values when only the key was specified. (We could define a special value like `fallbackValue = "NULL"` to mean that picocli should assign `null` when only the key is specified, but that is not very intuitive.) 

## New attribute

Perhaps a better idea is to introduce a new attribute like `mapFallbackValue`, with a default value like `"_NULL_MAP_VALUE"`. This special value signals picocli  to put `null` in the map for key-only map options. 

With this, the _default_ behaviour would be to put `null` in Maps when only the key was specified. Applications can specify any other value. (I like this idea better than trying to use `fallbackValue` for this.)

## Enabling still required

Note that to preserve backwards compatibility, applications still need to explicitly enable key-only map options with either a global option, a type of `Map<K, Optional<V>>` or a new  `enableKeyOnlyMapArgs` attribute. 

A new  `mapFallbackValue` attribute can only be used to automatically enable key-only map options when the application wants non-`null` values in the map. Applications that want `null` map values still need to use one of the other ways to explicitly enable key-only map options. This is a bit unfortunate and to me lessens the value of such a  `mapFallbackValue` attribute somewhat.

Thoughts?

**Comment by remkop** [comment]
Still thinking about this...
 
If we make it a goal to **only introduce one attribute**, we get this trade-off:
* `enableKeyOnlyMapArgs` (with existing `fallbackValue`): drawback is that users need to use a "special value" to put `null` values for key-only args. However, that special value may be useful in other use cases than key-only Maps.
* `mapFallbackValue`: no "special values" for users (good), and good default (`null`) for non-String maps, but drawback is that there is no attribute to explicitly enable key-only Maps with `null` values on a per-option basis (it can only be done globally)

So, I have started to lean towards `enableKeyOnlyMapArgs` (with existing `fallbackValue` for the value) now. Usage patterns will likely look something like this:


```java
class Examples {
  @Option(names = "-A")                              Map<String, String> m1; // key-only values not allowed
  @Option(names = "-B")                    Map<String, Optional<String>> m2; // auto-enabled, default = Optional.empty()
  @Option(names = "-C", fallbackValue = "_NULL_")    Map<String, String> m3; // auto-enabled,       default value = `null`
  @Option(names = "-D", enableKeyOnlyMapArgs = true) Map<String, String> m4; // explicitly enabled, default value = `""`
}
```

**Comment by dwalluck** [comment]
Apparently, I did mean `fallbackValue`, not `defaultValue`, sorry.

So, we've got three different cases for the key mapping (is this good or overly complicated?) and still no way to automatically map to, say, `Boolean.TRUE`. Or are we meant to check `if ("".equals(value))`?

**Comment by remkop** [comment]
> So, we've got three different cases for the key mapping (is this good or overly complicated?) 

There are three ways to _enable_ key-only Map args like `-Dkey`. Applications need to use only one of them. I think this can be explained in the manual fairly succinctly.

Can you see a way to simplify further?
(We can make this simpler by not supporting `Optional`, but I think supporting `Optional` is a nice feature.)

> and still no way to automatically map to, say, `Boolean.TRUE`. Or are we meant to check `if ("".equals(value))`?

No, that is covered. Simply use the `fallbackValue` to specify the desired value. For example:

```java
class App {
  @Option(names = "-E", fallbackValue = "true") Map<String, Boolean> m5; // -Ekey ok, gives [key : true]
  @Option(names = "-F", fallbackValue = "-1")   Map<String, Integer> m6; // -Fkey ok, gives [key : -1]
}
```

About Optional:

I started to work on implementing support for `Optional`, and it turns out that since the default fallbackValue is `""`, applications who want to get `Optional.empty()` for key-only arguments need to do this:

```java
// -Bkey ok, gives [key : Optional.empty()]
@Option(names = "-B", fallbackValue = "_NULL_") Map<String, Optional<String>> m2; 
```

Thoughts?

**Comment by remkop** [comment]
Well darn! I just realized we cannot use `fallbackValue` after all.

The current parser implementation for Map values already uses `fallbackValue` to supply the `key=value` pair when the `-D` option is specified on the command line by itself without a parameter... 

So, we need to introduce a new attribute like `mapFallbackValue` after all.

As discussed above, we only want to introduce _one_ new attribute. The default value for `mapFallbackValue` will be some internal String meaning "undefined". We can then use this attribute to enable/allow key-only Map arguments. Map options that do not have the `mapFallbackValue` attribute do not allow key-only values like `-Dkey`, and such values result in the "Value for option -D should be in KEY=VALUE format but was key" error message.

Example usage:

```java
class Examples {
  @Option(names="-A")                            Map<String, String> m1;           // -Akey NOT allowed, only -Akey=value
  @Option(names="-X")                            Map<String, Optional<String>> mx; // -Xkey NOT allowed, only -Xkey=value
  @Option(names="-B", mapFallbackValue="_NULL_") Map<String, Optional<String>> m2; // -Bkey gives [key: Optional.empty()]
  @Option(names="-C", mapFallbackValue="_NULL_") Map<String, String> m3;           // -Ckey gives [key: null]
  @Option(names="-D", mapFallbackValue="")       Map<String, String> m4;           // -Dkey gives [key: ""]
}
```

This actually looks simpler and more consistent than the previous proposal. 😄 

Thoughts?

**Comment by remkop** [comment]
Initial implementation done and pushed to master.

See [MapOptionsOptionalTest](https://github.com/remkop/picocli/blob/master/picocli-examples/src/test/java/picocli/MapOptionsOptionalTest.java) and [OptionalTest](https://github.com/remkop/picocli/blob/master/picocli-examples/src/test/java/picocli/OptionalTest.java).

**Comment by remkop** [comment]
@maxandersen @dwalluck Please take a look at these tests and let me know if you can think of any more use cases/test cases.
