### ISSUE TITLE
How to specify default value if not in environment ?

### ISSUE THREAD

**Issue by fmarot** [remkop/picocli#1218]
Hello

this is more a request for a feature (or improved doc if the feature already exists ;) ).
One of my option is defined like this:

> @Option(names = { "--directoryToScan" }, description = "directory to scan", required = false, defaultValue = "${env:directoryToScan}")
> private File directoryToScan;

this way I can use a value from the environment variables if one is available.
Additionally I would like to specify an hardcoded default value if none is available from the environment. Is it possible today ?
For rxemple in Spring boot there is this syntax to specify an hardcoded default:

> ${env.directoryToScan:/tmp/dir}

In this regard, I think Spring Boot is exemplar because it defines a list of locations where the framework will look in order to find the value for a given property (see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config ): it will automatically look into command line args, then in java properties, then in system env variables, then xxxxx and so on...

**Comment by remkop** [comment]
Hi @fmarot, yes, this feature already exist, and the syntax is more like the unix bash syntax than the Spring syntax: `${VAR:-DEFAULTVALUE}`. So, for your example:

```
${env.directoryToScan:-/tmp/dir}
```

For more details, see the user manual section on [Default Values for Custom Variables](https://picocli.info/#_default_values_for_custom_variables).

**Comment by remkop** [comment]
To clarify, in this example:

```
${env.directoryToScan:-/tmp/dir}
```

picocli will look up the key `env.directoryToScan` first in the system properties, then environment variables, and finally the resource bundle of the command. If not found anywhere, then the default value `/tmp/dir` is assigned.

You can restrict the lookup to specific sources by using a prefix. For example `${env:env.directoryToScan:-/tmp/dir}` would only look in the environment variables.

See also [Custom Variables](https://picocli.info/#_custom_variables).

**Comment by fmarot** [comment]
Thank you ! I did not test yet but closing this issue because your explanation seem crystal clear. And following your links to the official doc sorry, I totally missed them. Thanks !

**Comment by remkop** [comment]
Excellent!
Don’t forget to star ⭐️ picocli on GitHub if you like the project! 😉
