### ISSUE TITLE
Doc: update DI section on Quarkus

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1235]
The user manual has an example of using a custom factory to enable dependency injection in a Quarkus "command mode" CLI application.

Since that example was written, Quarkus has added more integrated picocli support: https://quarkus.io/guides/picocli .
Update the picocli manual to show a standalone command and a command suite, and link to the Quarkus manual.

**Comment by deining** [comment]
I'm willing to work on this. You may expected a PR soon, so stay tuned!

**Comment by remkop** [comment]
That is great, thank you!
