### ISSUE TITLE
Manual:  Spring Boot Example (chapter 22.2)

### ISSUE THREAD

**Issue by deining** [remkop/picocli#1245]
I'm trying to get the Spring Boot Example (chapter 22.2) to run with latest spring-boot starter 2.3.5, and I'm experiencing difficulties here. What I did so far: I took over the two given files `MySpringApp .java` and `MyCommand.java` as is into a skeleton Spring-boot-starter sample. After running `mvnw spring-boot:run`, I'm getting

```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 0 of constructor in info.picocli.demo.MySpringApp required a bean of type 'picocli.CommandLine$IFactory' that could not be found.
Action:
Consider defining a bean of type 'picocli.CommandLine$IFactory' in your configuration.
```

I could make the sample work by modifiying the code a bit, including defining a bean:

```
@SpringBootApplication
public class MySpringApp implements CommandLineRunner, ExitCodeGenerator {

	private int exitCode;
	/*private IFactory factory;    // auto-configured to inject PicocliSpringFactory
	private MyCommand myCommand; // your @picocli.CommandLine.Command-annotated class

	// constructor injection
	MySpringApp(IFactory factory, MyCommand myCommand) {
		this.factory = factory;
		this.myCommand = myCommand;
	} */

	@Autowired 	IFactory factory;
	@Autowired	MyCommand myCommand;
	@Bean
	IFactory factory() {
		return CommandLine.defaultFactory();
	}

	@Override
	public void run(String... args) {
...
```

Is this the intended way to make the sample work?? For me it looks like auto-injection of factory does not work here. Maybe you can have a look at this. IMHO, the code should be corrected so that it works out of the box. That's not the case right now, at least not for me.

Thanks for helping out here!

**Comment by deining** [comment]
Sorry for the noise, after adding the `picocli-spring-boot-starter` dependency everything works like expected.
Closing this ticket.

**Comment by remkop** [comment]
Maybe unrelated to the problem, but why are we returning `CommandLine.defaultFactory()` from the `@Bean`-annotated `factory()` method? Shouldn’t we return a `PicocliSpringFactory` instance?

I can try taking a more detailed look later.

**Comment by remkop** [comment]
Ah, ok. 👍 
Looks like our messages crossed. 😀
