### ISSUE TITLE
What automatic source code formatter is used by picocli?

### ISSUE THREAD

**Issue by jossiey** [remkop/picocli#1257]
Hi, I want to set automatic code formatter for my code. Since I include picocli as my source code, I wonder if I use Google Java Format, will it cause a conflict? Or I could use the same source code formatter as picocli is using. What automatic source code formatter is used by picocli now?

**Comment by remkop** [comment]
Hi @jossiey, I am not using an automatic code formatter for picocli.
Feel free to use any formatter you want for your own project that uses the picocli source code; it should not cause a conflict.
That said, I have not tried, and it is possible that some formatters complain about the large size of the CommandLine.java source file...  Let me know how it goes.

**Comment by remkop** [comment]
Did the code formatter work as expected?

Don't forget to give picocli a star :star: on GitHub if you like the project! :wink:

**Comment by jossiey** [comment]
Hi @remkop  Google-Java-Format works fine on my code. I also set SpotBugs as a linter, because there are some tiny bugs in picocli part, Therefore, I limited SpotBugs to check my code part instead.

**Comment by remkop** [comment]
Interesting! Did SpotBugs report any actual bugs, or were the issues more coding style-related?
Could you post the result?
