### ISSUE TITLE
Is it possible to run multiple subCommands under a single command in parallel?

### ISSUE THREAD

**Issue by ranjansrao** [remkop/picocli#1268]

**Comment by remkop** [comment]
Yes: https://picocli.info/#_repeatable_subcommands

**Comment by ranjansrao** [comment]
but in the example provided are the add commands all running together at the same time or are they running one after the other? i want them to run all in parallel

**Comment by remkop** [comment]
Picocli does not provide a mechanism for this, but this can easily be accomplished in the application.
In the `run` or `call` method of the subcommand, start a separate thread that does the actual work, and immediately return from the `run` or `call` method.
