### ISSUE TITLE
positional parameter lookbehind

### ISSUE THREAD

**Issue by xenoterracide** [remkop/picocli#1269]
So I'm looking at creating a java replacement for hygen due to a showstopper I encountered for it. What hygen does is essentially take [spaced out subcommands, and use it to look up a directory structure](http://www.hygen.io/docs/quick-start#bootstrapping-your-project), e.g. `hygen generator new foo` looks in `_templates/generator/new`.

What I'd like to be able to specify is something like this

```java
  @CommandLine.Parameters( index = "0", description = "first configuration directory") // mostly because of how Path.resolve works
  private String arg;

  @CommandLine.Parameters( index = "1..*-1", description = "path to configuration directories separated by space" ) // everything but the last argument
  private String[] args = new String[] {};

  @CommandLine.Parameters( index = "-1", description = "name" ) // last argument
  private String name;
```

now obviously I can just pull the last string off the path myself, but this won't do me the favor of generating help, or making it required. I don't have a specific need right now, but I think that being able to specify a negative range would be good too.

**Comment by remkop** [comment]
Hi @xenoterracide, that is a good idea, I think it is very similar to #370.

I like the idea, but have not spent much time thinking about how to implement it. It is not obvious, it probably involves some postprocessing of the arguments, after the parser has determined which of the arguments was the "last" positional parameter. (Positional parameters may be followed by options or by other subcommands, so often the parser can only tell for sure after all parameters have been processed.)

Are you interested in providing a pull request for this?

**Comment by xenoterracide** [comment]
probably not, it's not that big of a thing to me currently, since right now I'm just implementing the scaffolding thing for myself. Maybe somewhere way down the line, but I can't really see it happening, got too many other things that need fixing upstream first. yeah #370 is very similar, if not the same.

**Comment by remkop** [comment]
Let me close this ticket, this feature request is already tracked in #370.
