### ISSUE TITLE
ReflectionConfigGenerator should not generate method section in subclass for private superclass methods (was: Bug in ReflectionConfigGenerator)

### ISSUE THREAD

**Issue by sebthom** [remkop/picocli#1274]
I am trying to compile a Java cli app with GraalVM native-image and realized that it emits warnings like `WARNING: Method com.example.MyCommand.setVerbosity(boolean[]) not found.`

The issue was, that the `setVerbosity` method was declared as private method in an abstract parent command class, but ReflectionConfigGenerator generates this `reflect-config.json`

```json
[
  {
    "name" : "com.example.MyCommand",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "methods" : [
      { "name" : "setVerbosity", "parameterTypes" : ["[Z"] }
    ]
  },
  {
    "name" : "com.example.AbstractCommand",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "commandSpec" }
    ],
    "methods" : [
      { "name" : "setVerbosity", "parameterTypes" : ["[Z"] }
    ]
  }
]
```

Looking at the ReflectionConfigGenerator I realized that the logic is broken at https://github.com/remkop/picocli/blob/f2f2ac3230b9f6b5f52d159bda515ce805c0be88/picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ReflectionConfigGenerator.java#L482

I actually believe it should say
```java
if (scope.get().getClass().equals(method.getDeclaringClass())) {
```
instead of
```java
if (!scope.getClass().equals(method.getDeclaringClass())) {
```
which always evaluates to `true`

**Comment by remkop** [comment]
Thanks for raising this!
I’ll take a look.

**Comment by remkop** [comment]
I finally have time to look at this. Is my understanding below correct?

Given the code below to reproduce the issue:

```java
package picocli.codegen.aot.graalvm;

import picocli.CommandLine.Command;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.Option;
import picocli.CommandLine.Spec;

@Command
public class Issue1274AbstractCommand {
    @Spec
    CommandSpec commandSpec;

    @Option(names = {"-v", "--verbose"})
    private void setVerbosity(boolean[] verbosity) {
    }
}
```

```java
package picocli.codegen.aot.graalvm;

@picocli.CommandLine.Command
public class Issue1274Command extends Issue1274AbstractCommand {
}
```

The expected `reflect-config.json` is:

```json
[
  {
    "name" : "picocli.codegen.aot.graalvm.Issue1274AbstractCommand",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "commandSpec" }
    ],
    "methods" : [
      { "name" : "setVerbosity", "parameterTypes" : ["[Z"] }
    ]
  },
  {
    "name" : "picocli.codegen.aot.graalvm.Issue1274Command",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
  }
]
```

but the `reflect-config.json` that is actually generated is:

```json
[
  {
    "name" : "picocli.codegen.aot.graalvm.Issue1274AbstractCommand",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "commandSpec" }
    ],
    "methods" : [
      { "name" : "setVerbosity", "parameterTypes" : ["[Z"] }
    ]
  },
  {
    "name" : "picocli.codegen.aot.graalvm.Issue1274Command",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "methods" : [
      { "name" : "setVerbosity", "parameterTypes" : ["[Z"] }
    ]
  }
]
```

The `Issue1274Command` class does not declare a `setVerbosity` method, so the json for that class should not contain this section:

```
    "methods" : [
      { "name" : "setVerbosity", "parameterTypes" : ["[Z"] }
    ]
```

Is that an accurate description of the problem?

**Comment by sebthom** [comment]
Yes, that is the issue I am facing.

**Comment by remkop** [comment]
Thanks for the confirmation.
I pushed a change that I believe fixes the issue.
This will be included in the upcoming 4.6 release.

Thank you again for raising this!

**Comment by sebthom** [comment]
The fix works. Thanks! Just as a side note, without this fix GraalVM native-images require the option `--allow-incomplete-classpath` to build without failure.

**Comment by remkop** [comment]
@sebthom Thanks for letting me know there is a workaround!
I am happy to mention the workaround in the documentation if that makes sense, perhaps in the release notes for 4.6?

(If you can think of a place in the user manual where it would make sense to mention this problem with older picocli versions, and the workaround, we could do that too. I can't think of any off the top of my head, but I have not looked very hard yet.) 

:-)
