### ISSUE TITLE
[Docs] Interactive Prompt conditionally at runtime

### ISSUE THREAD

**Issue by xenoterracide** [remkop/picocli#1275]
what I need to do is at runtime check whether a file exists, and if "overwrite" is not set, prompt the user yes/no. This seems like it's underdocumented. `OptionSpec.Builder.interactive()` does exist, but it's a little unclear how you might add this *after* the command is executed... I'm not even sure the builder is the right tool, maybe there's an even lower level API I should be using? Also it's a bit unclear from the docs whether I can mix the annotation/programatic apis.

**Comment by remkop** [comment]
If I understood the use case correctly, you don't need an `interactive = true` option; I would do this in the business logic:

```java
public class Interactive implements Runnable {
    @Option(names = {"-o", "--outputFile"}, required = true, description = "The file to write to.")
    private File file;

    @Option(names = {"-f", "--force"}, description = "Don't prompt to overwrite if file exists.")
    private boolean force;

    public void run() {
        if (file.exists() && !force) {
            String response = null;
            while (!"Y".equalsIgnoreCase(response)) {
                response = System.console().readLine("Overwrite %s? Y/N", file.getName());
                if ("N".equalsIgnoreCase(response)) { return; }
            }
        }
        // overwrite file...
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new Interactive()).execute(args);
    }
}
```

**Comment by xenoterracide** [comment]
hmmm... yeah that'd work (although outputfile/overwrite in my case isn't an option, it's read in from a yaml file that's specified (sort of) as a parameter. I haven't actually tried the interactive prompt, so I wasn't certain if it was being extra nice like the other options are. Doing what you're suggesting should work for me.

Maybe this is also an interesting case for improvement? handling `Y/yes/n/no`. I'm not certain if it's helpful to add an additional API for prompting inside business logic. Heh, one could go extra far and add a statemachine for traversing prompt this then that, and autocompletion. Though all that seems like it's maybe going too far? thinking aloud at this point.

**Comment by remkop** [comment]
> Doing what you're suggesting should work for me.

Great to hear that!

> ... if it's helpful to add an additional API for prompting inside business logic.

Frankly it is hard to see how picocli can add value here: the existing (Java) APIs are not that painful, and very flexible. That said, I am interested in interfaces that are a hybrid between line-input console UIs and text-based form UIs. Some exploration is mentioned on this ticket: https://github.com/remkop/picocli/issues/633 (This is very early thinking...)

How are you finding picocli so far?

**Comment by xenoterracide** [comment]
> Frankly it is hard to see how picocli can add value here: the existing (Java) APIs are not that painful, and very flexible.

It's been a long time, but IIRC there are annoyances reading in types other than string? I mean, when you think about it I really want to get a boolean from readline based on y/n. What I'm doing isn't really complex enough to worry about that but... depending on what you're getting being able to have picocli validate and return the correct type might be nice. More thinking aloud though.

> How are you finding picocli so far?

I like it, probably what I'm going to use whenever I need to parse the cli in java (which is admittedly rare)

**Comment by remkop** [comment]
> It's been a long time, but IIRC there are annoyances reading in types other than string? I mean, when you think about it I really want to get a boolean from readline based on y/n. What I'm doing isn't really complex enough to worry about that but... depending on what you're getting being able to have picocli validate and return the correct type might be nice. More thinking aloud though.

In terms of validation, there are a few approaches that are [documented in the manual](https://picocli.info/#_validation).
For interactive, form-like terminal user interfaces, I think we are getting into the area I mentioned earlier, related to https://github.com/remkop/picocli/issues/633. This is quite a large area and I have not had time to look in more detail. It is very interesting though and requires a significant block of time, that I have not been able to set aside for this yet.

> I like it, probably what I'm going to use whenever I need to parse the cli in java

Cool! 👍 
Please star picocli on GitHub if you like the project. 😉

**Comment by xenoterracide** [comment]
> In terms of validation, there are a few approaches that are documented in the manual.

I guess I don't mean validation so much as type conversion which is already possible. I feel like this might already be possible with the existing code, except you can't trigger the spec inside of your business logic.

**Comment by xenoterracide** [comment]
Another advantage I just thought of, testing, with using command() directly I have to test that code, with picocli, if it had a testmode parameter, I could probably avoid testing that it actually creates a console input.

**Comment by remkop** [comment]
I am not sure I follow...
Can you sketch out a code example of how you would like it to work?

**Comment by xenoterracide** [comment]
hmm... presuming that you'd use existing programatic apis,

```java
public static void main(@NonNull String... args) {
    CommandLine.Model.CommandSpec spec = CommandLine.Model.CommandSpec.create();
    spec.mixinStandardHelpOptions(true); // usageHelp and versionHelp options

    spec.addOption( CommandLine.Model.OptionSpec.builder()
      .interactive(true)
      .type(int.class)
      .description("How many times should we execute?")
      .lazyPrompt() // do not prompt until requested
      .build()
    );
    var cli = new CommandLine(spec, new Application()); // application uses annotations
    System.exit(cli.execute(args));
  }

  static int run( CommandLine.ParseResult pr) {
    // implement the business logic
    int count = pr.matchedOptionValue( 'c', 1 ); // would block program and wait for prompt here.
  }
```

**Comment by remkop** [comment]
@xenoterracide I see, interesting.

Have you considered using a [custom `IParameterConsumer`](https://picocli.info/#_custom_parameter_processing)?
That allows you to define a callback that is called as soon as the option is recognized on the command line. Within the callback you can then decide to take parameters from the stack (the args passed to the command line), or prompt the user for input. This gives a lot of flexibility.

I prefer to keep the library simple here.

**Comment by xenoterracide** [comment]
`IParameterConsumer` looks like something I'm trying to avoid, and perhaps more complicated than just doing readline.

**Comment by remkop** [comment]
`IParameterConsumer` can be useful in some scenarios, like either consume a count from the parameters, or prompt the user for input if the argument following the `--count` option is not a number. But I agree that overall just doing readline is the simplest approach.

**Comment by remkop** [comment]
@xenoterracide are you okay for this ticket to be closed?

**Comment by xenoterracide** [comment]
Sure
