### ISSUE TITLE
unexpected MissingParameterException when a help-option is supplied

### ISSUE THREAD

**Issue by waacc-gh** [remkop/picocli#128]
The example from chapter 2.3, extended by an help-option (e.g. -?), fails if just the help-option is supplied:
```
@Parameters(hidden = true)  // "hidden": don't show this parameter in usage help message
List<String> allParameters; // no "index" attribute: captures _all_ arguments (as Strings)

@Parameters(index = "0")    InetAddress  host;
@Parameters(index = "1")    int          port;
@Parameters(index = "2..*") File[]       files;

@Option(names = "-?", help = true) boolean help;  // <-- added
```
Called just with "-?" leads to:
`Exception in thread "main" picocli.CommandLine$MissingParameterException: Missing required parameter: port`

**Comment by remkop** [comment]
Thanks for the bug report! Investigating...

**Comment by remkop** [comment]
Tracked it down to over-eager validation. This is now fixed in master.

**Comment by remkop** [comment]
I released picocli v0.9.6 for this.
Thanks again for the bug report!

**Comment by waacc-gh** [comment]
Thanks for the fixing quickly.
And thanks for the nice tool - helps me much.

**Comment by remkop** [comment]
Glad to hear that!
If you like this project please star it on GitHub and tell your friends! :-)
