### ISSUE TITLE
[Feature] constructor injection

### ISSUE THREAD

**Issue by xenoterracide** [remkop/picocli#1281]
instead of this

```java
 @CommandLine.Parameters(
    index = "1..*",
    description = "path to configuration directories separated by space"
  )
  @SuppressWarnings({ "NullAway.Init" })
  private List<String> args;
```

write this

```java
private final List<String> args;

MyFoo(
 @CommandLine.Parameters(
    index = "1..*",
    description = "path to configuration directories separated by space"
  )
List<String> args
)
{
   this.args = args;
}
```

this makes the code easier to test and safer to use. It also follows the Dependency Inversion principle.

**Comment by remkop** [comment]
Have you had a chance to read previous discussions on this topic in https://github.com/remkop/picocli/pull/1107 and https://github.com/remkop/picocli/issues/1195 ?

**Comment by remkop** [comment]
... but long story short: my conclusion after all that analysis is that this will be a lot of work to get it right, with relatively little benefit.
To be honest, I don't see myself working on this in the near future.

That said, if someone is willing to provide a high-quality PR (docs, tests, preserves backwards compatibility, etc), I will consider it. (No guarantees: I would still need to see how much additional complexity this would introduce in practice...)

**Comment by xenoterracide** [comment]
hmm... I just went about starting to try my hand at writing some tests against my application class, and I realized that it's hard because of the lack of this, and that there doesn't immediately seem to be a way to tell picocli to inject args like it would if I called `new CommandLine(new Application()).execute(args);` without actually executing it.

**Comment by remkop** [comment]
Hey @xenoterracide! 
There is the `CommandLine.parseArgs` method that populates the annotated fields from the command line arguments without invoking the `Runnable`/`Callable`.
Is that what you are looking for?

**Comment by remkop** [comment]
I renamed  #1195 to make it easier to find.
Closing this ticket since the feature request is already tracked in  #1195.
