### ISSUE TITLE
inject immutable Collections (was: inject immutable objects)

### ISSUE THREAD

**Issue by xenoterracide** [remkop/picocli#1282]
I've notice that writing

```java
  @CommandLine.Parameters(
    index = "1..*",
    description = "path to configuration directories separated by space"
  )
  @SuppressWarnings({ "NullAway.Init" })
  private List<String> args;
```
that I can mutate the list, I think the list should be immutable. I think that any type that can be immutable should be, obviously not every type can be.

**Comment by remkop** [comment]
I can see how this could be implemented, but I am not sure we should:
this may break existing applications that rely on the collection being mutable.

Is this really a problem? Applications can declare the field as `private`, and provide an accessor method that wraps the returned collection in an immutable wrapper, to prevent client code from modifying the list.

**Comment by xenoterracide** [comment]
to me, mutating private fields directly is naughty and violates basic OOP principles, also makes it harder to write a test, without writing code specifically for that test.

**Comment by remkop** [comment]
I think this ship has sailed: there may be applications that depend on the injected collections being mutable, and I strongly prefer not to break existing applications.

The current design allows applications to expose either immutable or mutable collections, as suitable for the application. Arguably that is what a library should strive to achieve; I am happy with the current design.
