### ISSUE TITLE
Option inheritance with Scala / Looking for valid example

### ISSUE THREAD

**Issue by dduquesne** [remkop/picocli#1287]
Hello,

I am trying to implement 
https://picocli.info/#_inherited_options
using Scala.

I have tried using Scope.
I have tried @ParentCommand.
I have tried Mixin.

I don't get any valid result.
Here is my code (Working version without any option inheritiance).

Maybe a scala example in the doc could help.
Many thanks for your support.

Best,

```
import picocli.AutoComplete.GenerateCompletion
import picocli.CommandLine
import picocli.CommandLine._

import java.io.File
import java.math.BigInteger
import java.nio.file.Files
import java.security.MessageDigest
import java.util.concurrent.Callable


@Command(name = "addition", 
version = Array("operation 1.0"),
description = Array("addition sur des opérandes"),
subcommands = Array(classOf[GenerateCompletion],classOf[Nombres],classOf[Mots]),
mixinStandardHelpOptions = true
)
class Addition extends Callable[Int]{

	@Option(names = Array("--crochets"), description = Array("le résustat est mis entre corchet"))
	var crochets:Boolean = false

	def call(): Int = {
		println("crochets :" + crochets)
		println("utlisez une sous-commande")
		0
	}

}


@Command(name = "nombres",
version = Array("nombres 1.0"),
description = Array("addition sur des nombres"),
mixinStandardHelpOptions = true
)
class Nombres extends Callable[Int] {

	@Parameters(index = "0", paramLabel = "<nombre_1>", description = Array("premier nombre"))
	var nombre_1: Int = 0

	@Parameters(index = "1", paramLabel = "<nombre_2>", description = Array("second nombre"))
	var nombre_2: Int = 0

	def call(): Int = {
		println("Premier nombre : " + nombre_1)
		println("Second nombre : " + nombre_1)
		println("Résultat : " + (nombre_1 + nombre_2))
		0
	}

}

@Command(name = "mots",
version = Array("mots 1.0"),
description = Array("addition sur des mots"),
mixinStandardHelpOptions = true
)
class Mots extends Callable[Int] {

	//@ParentCommand
	//var parent:Addition = null
	//if (parent.crochets){
	//	println("crochet is true")
	//}else{
	//	println("crochet is flase")
	//}

	@Parameters(index = "0", paramLabel = "<mot_1>", description = Array("premier mot"))
	var mot_1: String = ""

	@Parameters(index = "1", paramLabel = "<mot_2>", description = Array("second mot"))
	var mot_2: String = ""

	def call(): Int = {
		println("Premier mot : " + mot_1)
		println("Second mot : " + mot_1)
		println("Résultat : " + (mot_1 + " " + mot_2))
		0
	}

}


object Addition {
	def main(args: Array[String]): Unit = {
		System.exit(new CommandLine(new Addition()).execute(args: _*))
	}
}

```

**Comment by remkop** [comment]
When you used `scope = ScopeType.INHERIT`, you mention you didn’t get any valid result. 

Can you describe what you _actually_ saw and what you _expected_ to see?

**Comment by dduquesne** [comment]
Hello @remkop 

Thank for your feedback.

I use the INHERIT flag on a specific option "crochets" in my TOP command. I see this option as a global option.
![image](https://user-images.githubusercontent.com/12520088/102890122-36ae3a80-445c-11eb-8d62-05aae86f7b2b.png)

Then , in my SUB command , i try to use/access this  "crochets" option value.
![image](https://user-images.githubusercontent.com/12520088/102890179-4cbbfb00-445c-11eb-9e27-63eb535b96ef.png)

The compiler complains. I think it is right. I don't understand how i can avoid that.
![image](https://user-images.githubusercontent.com/12520088/102889777-8c361780-445b-11eb-8c17-fbd14ba7fc3b.png)

I have set my SBT project with the folowing dependencies.
![image](https://user-images.githubusercontent.com/12520088/102889883-ba1b5c00-445b-11eb-84b1-fb554f14d65f.png)

Is the module able to do anything at compile time to avoid this error ?
Maybe my understanding and expectation regarding this feature are completely wrong :)

Thank for your help.

**Comment by remkop** [comment]
Thank you for the clarification! Now I understand what you are trying to do: the business logic in the subcommand needs to access the value of the inherited option.

There are two ways this can be done:

* combine `scope = ScopeType.INHERIT` (in the parent) with `@ParentCommand` (in the subcommand)
* define the `--crochets` option in a separate class, and use the `@Mixin` annotation to add that option to both the parent command and the subcommand(s)

# With ScopeType.INHERIT

With `ScopeType.INHERIT`, there is only one memory location that holds the value for the `--crochets` option, and that is the `var crochets:Boolean` field in the `Additions` class. So, if a subclass needs to read that value, we can use `@ParentCommand` to access it:

```scala
@Command(name = "mots",
version = Array("mots 1.0"),
description = Array("addition sur des mots"),
mixinStandardHelpOptions = true
)
class Mots extends Callable[Int] {

	@ParentCommand
	var parent:Addition = null

	@Parameters(index = "0", paramLabel = "<mot_1>", description = Array("premier mot"))
	var mot_1: String = ""

	@Parameters(index = "1", paramLabel = "<mot_2>", description = Array("second mot"))
	var mot_2: String = ""

	def call(): Int = {
		if (parent.crochets){
			println("crochet is true")
		}else{
			println("crochet is false")
		}
		println("Premier mot : " + mot_1)
		println("Second mot : " + mot_1)
		println("Résultat : " + (mot_1 + " " + mot_2))
		0
	}
}
```

# With Mixins

If we define the `--crochets` option in a separate class, and use the `@Mixin` annotation to add that option to both the parent command and the subcommand(s), there are two separate `--crochets` options: one in each command. Which one gets set depends on where the user specified this option:

```bash
# here, the option mixed into the parent command is set
addition --crochets mots A B

# here, the option mixed into the subcommand is set
addition mots --crochets A B
```

This can be useful if the  `--crochets` option should be mixed in to _some_ subcommands, but not all.

The user manual has an [example](https://picocli.info/#_use_case_configure_log_level_with_a_global_option) that uses a mixin. This example has an `@Option`-annotated setter method instead of a `@Option`-annotated field. The setter finds the top-level command, and updates the value of the mixin of the top-level command. Now the information is again in just one place.

The example shows a setter, you can similarly add a getter, so the `Mots` subcommand can get the value from its own mixin (and let this mixin do the lookup to the top-level command that holds the value).

**Comment by dduquesne** [comment]
Hello @remkop 

Thank a lot for your detailled answer.
Realy apreciated.
I did not notice the fact that @ParentCommand and ScopeType.INHERIT were complementary.
So now, i understand the folowing semantic :

- ScopeType.INHERIT ( in a top command ) expose an option.
- @ParentCommand provides access to exposed option ( from sub command ).

I have tested your first proposal and it works as expected.
Thank again for your clear explanations.

Best regards,




![image](https://user-images.githubusercontent.com/12520088/103037861-289c0f00-456d-11eb-92aa-052923a88e42.png)


```
import picocli.AutoComplete.GenerateCompletion
import picocli.CommandLine
import picocli.CommandLine._

import java.io.File
import java.math.BigInteger
import java.nio.file.Files
import java.security.MessageDigest
import java.util.concurrent.Callable


@Command(name = "addition", 
version = Array("operation 1.0"),
description = Array("add the argument"),
subcommands = Array(classOf[GenerateCompletion],classOf[Numbers],classOf[Words]),
mixinStandardHelpOptions = true
)
class Addition extends Callable[Int]{

	@Option(names = Array("--brackets"), scope = ScopeType.INHERIT, description = Array("put result between brackets"))
	var brackets:Boolean = false

	def call(): Int = {
		println("brackets option : " + brackets)
		println("please, use a sub command")
		0
	}

}


@Command(name = "numbers",
version = Array("numbers 1.0"),
description = Array("add numbers"),
mixinStandardHelpOptions = true
)
class Numbers extends Callable[Int] {

	@ParentCommand
	var parent:Addition = null

	@Parameters(index = "0", paramLabel = "<number_1>", description = Array("first number"))
	var number_1: Int = 0

	@Parameters(index = "1", paramLabel = "<number_2>", description = Array("second number"))
	var number_2: Int = 0

	def call(): Int = {
		
		println("First number : " + number_1)
		println("Second number : " + number_2)
		val result = number_1 + " " + number_2
		if (parent.brackets){
			println("brackets is true")
			println("{" + result + "}")
		}else{
			println("brackets is false")
			println(result)
		}
		0
	}

}

@Command(name = "words",
version = Array("words 1.0"),
description = Array("add words"),
mixinStandardHelpOptions = true
)
class Words extends Callable[Int] {
	
	@ParentCommand
	var parent:Addition = null

	@Parameters(index = "0", paramLabel = "<word_1>", description = Array("first word"))
	var word_1: String = ""

	@Parameters(index = "1", paramLabel = "<word_2>", description = Array("second word"))
	var word_2: String = ""

	def call(): Int = {
		
		println("First word : " + word_1)
		println("Second word : " + word_1)
		val result = word_1 + " " + word_2
		if (parent.brackets){
			println("brackets is true")
			println("{" + result + "}")
		}else{
			println("brackets is flase")
			println(result)
		}
		0
	}
}


object Addition {
	def main(args: Array[String]): Unit = {
		System.exit(new CommandLine(new Addition()).execute(args: _*))
	}
}

```

**Comment by remkop** [comment]
Great, glad to hear that!
Enjoy picocli!

Please star picocli on GitHub if you like the project! 😉
