### ISSUE TITLE
Make "allow option overwriting" configurable

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#129]
Currently picocli accepts multiple occurrences of options with arity=1 and uses the last value.
It may be desirable to throw a `SuperfluousParameterException` instead.

@ddimtirov suggested making validation behaviour configurable: 

1. accept and silently use last value
1. accept and emit warning while using last value
1. reject (throw exception)

**Comment by ddimtirov** [comment]
Also "warn" if parameters values diverge may be a good idea.

**Comment by remkop** [comment]
#138 has been implemented, with  an option to switch the validation off (the last specified value is used in that case). What hasn't been done yet is providing an option to emit warnings

**Comment by remkop** [comment]
Created #158 for the remaining work. Closing this ticket.
