### ISSUE TITLE
Cannot compile with picocli-shell-jline3 dependency using Maven

### ISSUE THREAD

**Issue by sualeh** [remkop/picocli#1291]
Since the change to [Fix gradle warnings](https://github.com/remkop/picocli/commit/758558b9817660b6c6e497aab28cb8ac7421127e), Maven compilation of any project with [picocli-shell-jline3](https://search.maven.org/search?q=a:picocli-shell-jline3) as a dependency is broken, since the artifact published to The Central Repository has a changed the scope of transitive dependencies to jline - see the following changes to scope in the published pom.xml:

```xml
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline</artifactId>
      <version>3.17.1</version>
      <scope>runtime</scope>
    </dependency>
```
whereas in former versions of picocli it was

```xml
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline</artifactId>
      <version>3.16.0</version>
      <scope>compile</scope>
    </dependency>
```

In order words, the change in how the Gradle dependency is defined has broken the Maven scope, and compilation fails.

**Comment by sualeh** [comment]
@deining - copying you for information too.

**Comment by remkop** [comment]
@sualeh Thank you for raising this!

Will applications be able to work around this by explicitly adding this dependency to their POM? 

```xml
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline</artifactId>
      <version>3.16.0</version>
      <scope>compile</scope>
    </dependency>
```

If so, we can try to fix this in the next release, but in the meantime add a note for this to the documentation.

**Comment by sualeh** [comment]
Here is the way I suggest:

```xml
    <dependency>
      <groupId>info.picocli</groupId>
      <artifactId>picocli-shell-jline3</artifactId>
      <version>4.6.0</version>
      <exclusions>
        <exclusion>
          <groupId>org.jline</groupId>
          <artifactId>jline</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline</artifactId>
      <version>3.17.1</version>
    </dependency>
```

**Comment by dejan2609** [comment]
Related issue #1294 is reported by @remal (I will try to expand my PR asap).

**Comment by sualeh** [comment]
@remkop  - may I request a point release with this fix?

**Comment by remkop** [comment]
Yes will do.

**Comment by remkop** [comment]
Thanks again for raising this!
This is fixed in the 4.6.1 release.

**Comment by deining** [comment]
> @deining - copying you for information too.

Sorry for messing up things here. A huge thanks to everyone involved in ironing this fault out so quickly.

**Comment by remkop** [comment]
@deining No worries at all! 😉 
I now finally sat down to learn the difference between `api` and `implementation`. So thank you! 😄 
And I also think it is pretty cool how a whole bunch of people got together to help fix things so quickly. 🙏 Truly grateful!

**Comment by dejan2609** [comment]
Don't mention it @deining !  No man is able to be a jack off all trades.. and besides that: you gave us a chance to return something to the community :relaxed:

@remkop feel free to ping me in case of some Gradle related issues :wink:
