### ISSUE TITLE
Random usage indentation

### ISSUE THREAD

**Issue by ymenager** [remkop/picocli#1293]
I've got a simple sub-command that's generating usage with random indentation, with some options having more indentation than others

```
Usage: emt application create [-hV] [-ev=<emtVersion>] [-g=<groupId>] [-n=<name>] [-pd=<parentDir>] [-pn=<projectName>] [-rsv=<muleRuntimeSubVersion>]
                              [-rv=<muleRuntimeVersion>] <artifactId>
      <artifactId>          Project artifactId
      -ev, --emtVersion=<emtVersion>
                            Enhance Mule Tools version
                              Default: 1.2.7-beta4-SNAPSHOT
  -g, --groupId=<groupId>   Maven group id
                              Default: com.company
  -h, --help                Show this help message and exit.
  -n, --name=<name>         Name of the project directory
      -pd, --parentdir=<parentDir>
                            directory where the project directory will be created
      -pn, --projectName=<projectName>
                            Project name
      -rsv, --runtimeSubVersion=<muleRuntimeSubVersion>
                            Mule runtime sub-version
                              Default: 20201013
      -rv, --runtimeVersion=<muleRuntimeVersion>
                            Mule runtime version
                              Default: 4.3.0
  -V, --version             Print version information and exit.
```

My code:

```
@Command(name = "create", aliases = "cr", mixinStandardHelpOptions = true)
public class ApplicationCreateCmd implements Callable<Integer> {
    @Parameters(arity = "1",description = "Project artifactId")
    private String artifactId;
    @Option(names = {"--parentdir", "-pd"}, description = "directory where the project directory will be created")
    private File parentDir;
    @Option(names = {"--name", "-n"}, description = "Name of the project directory")
    private String name;
    @Option(names = {"--groupId", "-g"}, description = "Maven group id", defaultValue = "com.company", showDefaultValue = ALWAYS)
    private String groupId;
    @Option(names = {"--projectName", "-pn"}, description = "Project name")
    private String projectName;
    @Option(names = {"--runtimeVersion", "-rv"}, description = "Mule runtime version", defaultValue = "4.3.0", showDefaultValue = ALWAYS)
    private String muleRuntimeVersion;
    @Option(names = {"--runtimeSubVersion", "-rsv"}, description = "Mule runtime sub-version", defaultValue = "20201013", showDefaultValue = ALWAYS)
    private String muleRuntimeSubVersion;
    @Option(names = {"--emtVersion", "-ev"}, description = "Enhance Mule Tools version", showDefaultValue = ALWAYS)
    private String emtVersion;
```

Full project is here: https://gitlab.com/aeontronix/oss/enhanced-mule/enhanced-mule-tools

**Comment by remkop** [comment]
Hi @ymenager, the usage help shows one-character POSIX [short options](https://picocli.info/#_short_posix_options) in the first column, and any other options in the second column.

**Comment by ymenager** [comment]
That doesn't explain the mis-alignment. for example both those lines have short options and long options, and they're on different indents:

  -n, --name=<name>         Name of the project directory
      -pd, --parentdir=<parentDir>
                            directory where the project directory will be created

**Comment by ymenager** [comment]
on, it considers single character options only as short options, i get it

**Comment by ymenager** [comment]
Is there a way to disable or customize that behavior ?

**Comment by remkop** [comment]
Hi @ymenager, yes it is possible to customize this.

# Background
By default, the usage help message has a [Layout](https://picocli.info/apidocs/picocli/CommandLine.Help.Layout.html), which has a [TextTable](https://picocli.info/apidocs/picocli/CommandLine.Help.TextTable.html) with the following columns:

* marker for required options (2 chars)
* short options (2 chars)
* `,` separator between short and long options (1 char)
* long options (by default 24 but customizable with `CommandLine::setUsageHelpLongOptionsMaxWidth`)
* description (remaining, by default 51 for the standard 80-char width)

# Customized Example

This ticket has [example code to customize that layout](https://github.com/remkop/picocli/issues/774#issuecomment-516355359).
With the customized layout, there are just three columns:
* marker for required options
* all options, comma-separated if necessary
* description

I believe that adding this code to your application should give the desired result.
Can you give that a try?

**Comment by remkop** [comment]
Hi @ymenager, did the sample code in #774 meet your needs?

**Comment by remkop** [comment]
@ymenager I assume that the layout customization code solved the issue, so closing this ticket.
Feel free to comment here or open another ticket if there is any work remaining. :-)
Enjoy picocli!

**Comment by bric3** [comment]
@remkop Just a thanks for this answer !
