### ISSUE TITLE
Best way to support ''--lines=[+]NUM' ?

### ISSUE THREAD

**Issue by bric3** [remkop/picocli#1301]
Hi there,

Thanks again for making picocli. So I developed a small too with similar options to tail, and I didn't found a straightforward
way to express an option like this : 

```
Mandatory arguments to long options are mandatory for short options too.
  -c, --bytes=[+]NUM       output the last NUM bytes; or use -c +NUM to.
                             output starting with byte NUM of each file
  -f, --follow[={name|descriptor}]
                           output appended data as the file grows;
                             an absent option argument means 'descriptor'
  -F                       same as --follow=name --retry
  -n, --lines=[+]NUM       output the last NUM lines, instead of the last 10;  <<===
                             or use -n +NUM to output starting with line NUM
```

Programmatically I can handle the optional plus, if it is a string, but I wonder if it's possible to do that easily within the logic of picocli ?

By the way my project is there : https://github.com/bric3/drain-java
The command line parsing is still quite dumb as I focused on other aspects but I will eventually commit to make it better and leveraging more picocli.

**Comment by remkop** [comment]
My first thought is that it may be good to model this with some sort of composite type, that has an attribute for the absence or presence of the `+` character, and an attribute for the numerical value.

Something like this:

```java
class Chunk {
    boolean isStartingPoint; // true if + was specified
    int number;
}
```

And use that as the type for these options:

```java
@Command
class MyApp {
    @Option(names = {"-n", "--lines"}, converter = ChunkConverter.class, paramLabel = "[+]NUM")
    Chunk lines;
    // ...
}
```

And then have a custom converter for the `Chunk` type:

```java
class ChunkConverter implements CommandLine.ITypeConverter<Chunk> {

    @Override
    public Chunk convert(String value) throws Exception {
        Chunk result = new Chunk();
        if (value.startsWith("+")) {
            result.isStartingPoint = true;
            value = value.substring(1);
        }
        result.number = Integer.parseInt(value);
        if (result.number < 0) {
            throw new CommandLine.TypeConversionException("Invalid value " +
                        value + ": must be 0 or more.");
        }
        return result;
    }
}
```

**Comment by bric3** [comment]
@remkop Exactly what I had somewhat in mind, I was close. Thanks for the help !
Thank you !

By the way happy new year and best wishes.

**Comment by remkop** [comment]
No worries!
Please star ⭐ picocli on GitHub if you like the project! 😉 

Enjoy picocli!

**Comment by bric3** [comment]
@remkop Already did ;)

It's a great and useful project. I probably won't have much visibility in my project, an implementation of DRAIN in java. This allows to discover log patterns on-the-go and count the occurences of these patterns. This works well, but there's some features that are lacking.
