### ISSUE TITLE
Subcommand names: `gen-manpage` vs `generate-completion`

### ISSUE THREAD

**Issue by adamsmd** [remkop/picocli#1302]
The `ManPageGenerator` and `GenerateCompletion` classes produce subcommands named `gen-manpage` and `generate-completion`, respectively.  One using `gen` and the other using `generate` is inconsistent and the `--help` message looks strange when both of these are present as subcommands.  In addition, it makes auto-complete not work well.

I would like to suggest standardizing on one of the two terms.  (Personally, I prefer to standardize on `generate`, but I care more that it is standardized than which term is used.)

In the meantime, is there a way for me to override their command names in my own code?

(It also might be worth being consistent with the class names (e.g., suffix `Generator` vs prefix `Generate`), but that is not a user facing issue and so is less important to me.)

**Comment by remkop** [comment]
Hi @adamsmd, nice to hear from you! I hope all is well with you.

Good point about the names, I hadn't realized.  😅  Thanks for pointing that out.

One idea is to name both commands `generate-*` and give them an alias `gen-*`.
That would ensure that existing scripts/applications that use the previous command name will continue to work.

This does change the usage help message: the usage displays the command name and all aliases of each subcommand.
To give you some idea, here is a small command that has both `gen-manpage` and `generate-completion` as subcommands:

```
Usage: mycommand [-hV] [COMMAND]
Just some randome command
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  generate-manpage, gen-manpage        Generates man pages for all commands in
                                         the specified directory.
  generate-completion, gen-completion  Generate bash/zsh completion script for
                                         mycommand.
```

It does make the column for subcommand names appear a bit wide.

Perhaps we need to add a way for users to control the width of the subcommand name column, similar to what https://github.com/remkop/picocli/issues/934 did for the option long name column.

**Comment by remkop** [comment]
Hi @adamsmd, I finally found a solution for this.

Picocli 4.6 introduced [model transformers](https://picocli.info/#_model_transformations) as a way to modify the command hierarchy at runtime.

An example transformer that changes the name of the `gen-manpage` subcommand to `generate-manpage` looks like this:

```java
class MyTransformer implements CommandLine.IModelTransformer {
    public CommandLine.Model.CommandSpec transform(CommandLine.Model.CommandSpec commandSpec) {
        CommandLine gen = commandSpec.removeSubcommand("gen-manpage");
        commandSpec.addSubcommand("generate-manpage", gen);
        return commandSpec;
    }
}
```

Here is a test that demonstrates: https://github.com/remkop/picocli/blob/main/src/test/java/picocli/ModelTransformerTest.java

Note that picocli 4.6.3 fixes an issue with adding and removing subcommands, so you will need that version for this to work correctly.
