### ISSUE TITLE
Windows ANSI not working

### ISSUE THREAD

**Issue by rlogiacco** [remkop/picocli#1311]
Apologies for posting again a question which has already been touched multiple times, but I'm having some troubles on Windows 10 even after checking other related and closed issues like #66, #581 and the documentation.

I'm trying using two windows terminals (_Console Z_ and _Fluent Terminal_) which both support ANSI colouring (tested using [this script](https://gist.github.com/k-takata/2d4f562bacf8bae6691973a540970117#file-color256-bat)) but in both cases I receive the ANSI codes in output rather than the styled text.

I've obviously enabled the environment variables `CLICOLOR` and `CLICOLOR_FORCE` setting them both to `1` with no effect.

I know a lot of effort has been put into this, so I'm pretty sure I am doing something wrong.
ANSI colours work perfectly fine under Linux, so I guess there's nothing wrong in my application and I'm asking here to double-check how dumb I am.

![ansi](https://user-images.githubusercontent.com/199473/105167101-93167f80-5b18-11eb-8de1-3820e53afba2.png)

Thanks for the patience,
   Roberto

**Comment by rlogiacco** [comment]
To make things even worse, ANSI colouring works perfectly when maven is involved:

![image](https://user-images.githubusercontent.com/199473/105160189-3747f880-5b10-11eb-9ca5-05aec0990172.png)

**Comment by remkop** [comment]
Hi @rlogiacco, thank you for raising this, and thank you for carefully checking the related issues!
This looks quite tricky...
I am not familiar with the Console Z and Fluent Terminal terminals, I need some time to install them and play with them.

Some quick questions:
Do these terminals have a code page or character encoding set (and if so, what is the value)?
Can you show the output of your program after setting system property `picocli.trace` to `DEBUG`?
Can you redirect the output to a file and share the contents (if `CLICOLOR_FORCE` is non-zero, picocli should output ANSI escape codes even when STDOUT is redirected) - I would like to see the actual bytes.

**Comment by rlogiacco** [comment]
WIth `picocli.trace=DEBUG`:
```
[picocli DEBUG] Creating CommandSpec for com.example.it.CLI@13a5fe33 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for class com.example.it.Convert with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@768b970c with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Adding subcommand 'convert' to 'soa-cli'
[picocli DEBUG] Getting a com.example.it.Convert instance from factory picocli.CommandLine$DefaultFactory@6366ebe0
[picocli DEBUG] Factory returned a com.example.it.Convert instance (44f75083)
[picocli DEBUG] Creating CommandSpec for class com.example.it.Deploy with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Getting a com.example.it.Deploy instance from factory picocli.CommandLine$DefaultFactory@6366ebe0
[picocli DEBUG] Factory returned a com.example.it.Deploy instance (dbd940d)
[picocli DEBUG] Creating CommandSpec for com.example.it.Remote@2df32bf7 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for com.example.it.Transfer@588df31b with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@11e21d0e with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Adding subcommand 'deploy' to 'soa-cli'
[picocli DEBUG] Creating CommandSpec for class com.example.it.Undeploy with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Getting a com.example.it.Undeploy instance from factory picocli.CommandLine$DefaultFactory@6366ebe0
[picocli DEBUG] Factory returned a com.example.it.Undeploy instance (1372ed45)
[picocli DEBUG] Creating CommandSpec for com.example.it.Remote@6a79c292 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@80ec1f8 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Adding subcommand 'undeploy' to 'soa-cli'
[picocli DEBUG] Creating CommandSpec for class com.example.it.Upload with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Getting a com.example.it.Upload instance from factory picocli.CommandLine$DefaultFactory@6366ebe0
[picocli DEBUG] Factory returned a com.example.it.Upload instance (1c72da34)
[picocli DEBUG] Creating CommandSpec for com.example.it.Remote@6b0c2d26 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for com.example.it.Transfer@27c6e487 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@59717824 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Adding subcommand 'upload' to 'soa-cli'
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@77be656f with factory picocli.CommandLine$DefaultFactory
[picocli INFO] Picocli version: 4.5.2, JVM: 11.0.3 (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 11.0.3+12-LTS), OS: Windows 10 10.0 amd64
[picocli INFO] Parsing 1 command line args [--help]
[picocli DEBUG] Parser configuration: optionsCaseInsensitive=false, subcommandsCaseInsensitive=false, abbreviatedOptionsAllowed=false, abbreviatedSubcommandsAllowed=false, aritySatisfiedByAttachedOptionParam=false, atFileCommentChar=#, caseInsensitiveEnumValuesAllowed=true, collectErrors=false, endOfOptionsDelimiter=--, expandAtFiles=true, limitSplit=false, overwrittenOptionsAllowed=false, posixClusteredShortOptionsAllowed=true, separator=null, splitQuotedStrings=false, stopAtPositional=false, stopAtUnmatched=false, toggleBooleanFlags=false, trimQuotes=false, unmatchedArgumentsAllowed=false, unmatchedOptionsAllowedAsOptionParameters=true, unmatchedOptionsArePositionalParams=false, useSimplifiedAtFiles=false
[picocli DEBUG] (ANSI is enabled by default: systemproperty[picocli.ansi]=null, isatty=true, TERM=xterm-256color, OSTYPE=null, isWindows=true, JansiConsoleInstalled=false, ANSICON=null, ConEmuANSI=null, NO_COLOR=null, CLICOLOR=null, CLICOLOR_FORCE=null)
[picocli DEBUG] Initializing command 'soa-cli' (user object: com.example.it.CLI@13a5fe33): 3 options, 0 positional parameters, 0 required, 0 groups, 4 subcommands.
[picocli DEBUG] Set initial value for field boolean[] com.example.it.CLI.verbosity of type class [Z to null.
[picocli DEBUG] Set initial value for field boolean picocli.CommandLine$AutoHelpMixin.helpRequested of type
boolean to false.
[picocli DEBUG] Set initial value for field boolean picocli.CommandLine$AutoHelpMixin.versionRequested of type boolean to false.
[picocli DEBUG] [0] Processing argument '--help'. Remainder=[]
[picocli DEBUG] '--help' cannot be separated into <option>=<option-parameter>
[picocli DEBUG] Found option named '--help': field boolean picocli.CommandLine$AutoHelpMixin.helpRequested,
arity=0
[picocli INFO] field boolean picocli.CommandLine$AutoHelpMixin.helpRequested has 'usageHelp' annotation: not validating required fields
[picocli INFO] Setting field boolean picocli.CommandLine$AutoHelpMixin.helpRequested to 'true' (was 'false') for option --help on AutoHelpMixin@77be656f
[picocli DEBUG] Applying default values for command 'soa-cli'
[picocli DEBUG] defaultValue not defined for field boolean[] com.example.it.CLI.verbosity
[picocli DEBUG] defaultValue not defined for field boolean picocli.CommandLine$AutoHelpMixin.versionRequested
[picocli DEBUG] getTerminalWidth() executing command [stty, -a, -F, /dev/tty]
[picocli DEBUG] getTerminalWidth() ERROR: java.io.IOException: Cannot run program "stty": CreateProcess error=2, Impossibile trovare il file specificato
[picocli DEBUG] getTerminalWidth() returning: -1 in 27,4ms
Usage: ?[1msoa-cli?[21m?[0m [?[33m-hVv?[39m?[0m] [COMMAND]
  ?[33m-h?[39m?[0m, ?[33m--help?[39m?[0m      Show this help message and exit.
  ?[33m-v?[39m?[0m              Aumenta il grado di verbosita', cumulabile. Ad esempio, `?[3m-v ?[23m?[0m
                 ?[3m   -v -v?[23m?[0m` or `?[3m-vvv?[23m?[0m`
  ?[33m-V?[39m?[0m, ?[33m--version?[39m?[0m   Print version information and exit.
Commands:
  ?[1mconvert?[21m?[0m   Converte il file ?[1m.prop?[21m?[0m di un servizio nel suo equivalente .conf
  ?[1mdeploy?[21m?[0m    Deploya uno o piu' servizi in un ambiente costituito da uno o piu'
              nodi
  ?[1mundeploy?[21m?[0m  Rimuove uno o piu' servizi in un ambiente costituito da uno o piu'
              nodi
  ?[1mupload?[21m?[0m    Effettua il trasferimento di una o piu' trasformazioni in un
              ambiente costituito da uno o piu' nodi
```

**Comment by rlogiacco** [comment]
Here is the output redirected to a file (I zipped it to prevent manipulation from github)
[out.zip](https://github.com/remkop/picocli/files/5841964/out.zip)

**Comment by remkop** [comment]
Thank you! The output looks good as far as I can see: what is printed as `?[1m` is actually `ESC[1m`, which is what it should be.

The DEBUG output confirms what you said about the `TERM` environment variable:

> [picocli DEBUG] (ANSI is **enabled** by default: systemproperty[picocli.ansi]=null, **isatty=true**, **TERM=xterm-256color**, OSTYPE=null, isWindows=true, JansiConsoleInstalled=false, ANSICON=null, ConEmuANSI=null, NO_COLOR=null, CLICOLOR=null, CLICOLOR_FORCE=null)

Very strange. I will try to look at this more tomorrow, family time now! 😄

**Comment by rlogiacco** [comment]
To add more info, I've seen there is a reference in the documentation to a [StackOverflow answer](https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes/51681675#51681675), but I cannot test if that will make any change as I don't have the rights to alter my registry (corporate PC).
I guess though Maven is also using ANSI codes to style its output, so I believe that feature has already been enabled by the terminal program.

If it provides any additional insight, also PowerShell with `CLICOLOR` set, outputs the same escape codes:

![image](https://user-images.githubusercontent.com/199473/105171991-3cf90a80-5b1f-11eb-9188-4c1ff0125e74.png)

**Comment by remkop** [comment]
If the underlying problem is that we need to [call the `SetConsoleMode` API](https://picocli.info/#_for_reference_without_jansi_on_windows_10_command_console_and_powershell), we may not be able to do much... 

I wonder why Maven works though... I am guessing they use Jansi. Have you tried that?

**Comment by rlogiacco** [comment]
Sorry for the quick posting, but I might have found at least some decent information for this.

I installed ConEmu, as I was trying to understand if the problem was somewhere with my environment, and I discovered ConEmu displays ANSI codes nicely, Then I went to the ConEmu settings and the _Inject ConEmuHk.dll into all processes started in ConEMu tabs_ got my attention: disabling it and opening a new tab immediately broke the ANSI codes parsing.

I then tried to add the JANSI library and activate it and... BAM! Everything is working nicely.

So I guess my dumbness was not properly reading the documentation: if you want ANSI colors on Windows you **MUST** include the `jansi` library and activate it by calling `AnsiConsole.systemInstall()` in your `main`.

Sorry for the bother, I believe this issue can be closed unless I'm missing something else.

**Comment by remkop** [comment]
Oh interesting! I did not know that about ConEmu. So ConEmu kind of bends over backwards to help applications display ANSI codes, even if these applications did not bother to call the `SetConsoleMode` API. Very nice!

Perhaps we should petition the java maintainers to call the `SetConsoleMode` API in the Windows executable, so that Java programs can natively show ANSI colors.

**Comment by rlogiacco** [comment]
I'm willing to bring in a few signatures for such a petition!

**Comment by rlogiacco** [comment]
BTW, I can confirm Maven uses Jansi and I wish to suggest to any fellow developer to use Maven as a reference test: if you believe you have done everything fine but your ANSI colouring is not working, while Maven does, you know you are missing Jansi 😉

**Comment by remkop** [comment]
PS. don't hesitate to give picocli a star ⭐  on GitHub if you like the project! 😉
