### ISSUE TITLE
For multiple subcommands, factory is called to create derived class

### ISSUE THREAD

**Issue by alexey-tr** [remkop/picocli#1312]
CommandUserObject.getInstance doesn't use configured factory, instead it uses default factory:
```
...
try {
            t.debug("Getting a %s instance from factory %s%n", this.type.getName(), this.factory);
            this.instance = CommandLine.DefaultFactory.create(this.factory, this.type); // <-- the problem is here
            this.type = this.instance.getClass();
            t.debug("Factory returned a %s instance (%s)%n", this.type.getName(), Integer.toHexString(System.identityHashCode(this.instance)));
...
```

**Comment by remkop** [comment]
Hi @alexey-tr, thanks for looking at this!

I am not sure I see the problem. 

```java
// CommandUserObject
public Object getInstance() {
    ....
    instance = DefaultFactory.create(factory, type);
```
That line calls the static method `DefaultFactory::create`, passing the configured factory as a parameter.

The static method `DefaultFactory::create` is implemented to call `create` on the passed factory parameter:

```java
// DefaultFactory
static <T> T create(IFactory factory, Class<T> cls) {
    try { return factory.create(cls); }
    catch ...
```

So, the factory that is used is the one that is configured for the `CommandUserObject` instance.
Am I missing something?

**Comment by alexey-tr** [comment]
You are right, no issue here. I'm actually having problem with subcommands creation, somehow one of them create via given factory and one via constructor. I thought that this is the cause, but I was wrong, sorry

**Comment by alexey-tr** [comment]
My subcommand is abstract, and factory when asked to creates subcommand class creates derived class, but for second subcommand factory is asked to create derived class. See test below
```java
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Test;
import picocli.CommandLine;
import picocli.CommandLine.ParentCommand;

public class CliTest {

  @Test
  public void singleSubCommand() {
    assertEquals(0, new CommandLine(new Top(), new XFactory())
        .execute("x"));
  }

  @Test
  public void doubleSubCommand() {
    assertEquals(0, new CommandLine(new Top(), new XFactory())
        .execute("x", "x"));
  }

  @CommandLine.Command(name = "top", subcommands = Subcommand.class, subcommandsRepeatable = true)
  static class Top implements Runnable {

    @Override
    public void run() {

    }
  }

  @CommandLine.Command(name = "x")
  abstract static class Subcommand implements Runnable {

    @ParentCommand
    Top runnable;

    private String id;

    Subcommand() {
      super();
    }

    Subcommand(String id) {
      this.id = id;
    }

    @Override
    public void run() {

    }
  }

  static class Impl extends Subcommand {

    Impl() {
      fail("should not be called");
    }

    Impl(String id) {
      super(id);
    }
  }

  static class XFactory implements CommandLine.IFactory {

    @Override
    public <K> K create(Class<K> aClass) throws Exception {
      if (Subcommand.class.equals(aClass)) {
        return (K) new Impl("abcd");
      }
      return CommandLine.defaultFactory().create(aClass);
    }
  }
}
```

**Comment by remkop** [comment]
Thank you for providing that test case.
I was able to reproduce the problem. I see this stack trace:

```
java.lang.AssertionError: should not be called

	at org.junit.Assert.fail(Assert.java:88)
	at picocli.CliTest$Impl.<init>(CliTest.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5488)
	at picocli.CliTest$XFactory.create(CliTest.java:70)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5514)
	at picocli.CommandLine$Model$CommandUserObject.getInstance(CommandLine.java:11819)
	at picocli.CommandLine$Model$CommandUserObject.get(CommandLine.java:11844)
	at picocli.CommandLine$Model$FieldBinding.set(CommandLine.java:11667)
	at picocli.CommandLine$Model$CommandSpec.injectParentCommand(CommandLine.java:6858)
	at picocli.CommandLine$Model$CommandSpec.parent(CommandLine.java:6551)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13275)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13078)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13349)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13266)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13078)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13047)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:12948)
	at picocli.CommandLine.parseArgs(CommandLine.java:1478)
	at picocli.CommandLine.execute(CommandLine.java:2077)
	at picocli.CliTest.doubleSubCommand(CliTest.java:21)
        ...
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        ...
```

If I put a breakpoint in the `XFactory` class, I see our factory is getting called with the `CliTest$Impl` class.

The XFactory only has special logic for `if (Subcommand.class.equals(aClass))` but not for the `CliTest$Impl` class, so the XFactory class delegates to the default picocli factory, which calls the no-arg constructor, leading to the error above.

The tests pass if I change the `XFactory` implementation a little bit:

```java
static class XFactory implements CommandLine.IFactory {
    public <K> K create(Class<K> aClass) throws Exception {
        if (Subcommand.class.equals(aClass) || Impl.class.equals(aClass)) { // also handle Impl.class
            return (K) new Impl("abcd");
        }
        return CommandLine.defaultFactory().create(aClass);
    }
}
```

**Comment by alexey-tr** [comment]
Thank you for looking, I understand workaround. But why factory is called with Impl.class? Is it intentional?

**Comment by remkop** [comment]
When the first "x" parameter is encountered, and the subcommand is recognized, picocli creates a `CommandUserObject` where the instance of that subcommand is tracked. When the `CommandUserObject` is first created, it takes the class from the `@Command`-annotated class. The `@Command`-annotated class is the `Subcommand` class, and the factory returns an `Impl` instance. The `CommandUserObject` now has an instance, and its class has been changed from `Subcommand` to the `Impl` class (the class of the instance).

Then, when the second "x" is encountered (and `subcommandsRepeatable = true`), picocli will create another instance of the same `CommandUserObject`. When the `CommandUserObject` is asked to create another instance, it now passes the class of the instance (`Impl`) to the factory.

**Comment by alexey-tr** [comment]
> When the CommandUserObject is asked to create another instance, it now passes the class of the instance (Impl) to the factory.

In my opinion use of `Impl` for second and subsequent instances while specification says `Subcommand` looks bit illogical, but perhaps there are some design considerations, which I don't know. Anyway thank you for looking and for great library.

**Comment by remkop** [comment]
@alexey-tr I see your point that the factory being called with the `Impl` class is not what you would expect. This may be fixed at some point in the future, but for now, other things will take priority. Thank you for pointing this out though, I had not thought about this.

Glad to hear you like picocli! :pray: 
Please give picocli a star :star: on GitHub to help promote the project when you get a chance! :stuck_out_tongue_winking_eye:
