### ISSUE TITLE
Document application distribution

### ISSUE THREAD

**Issue by charphi** [remkop/picocli#1315]
Similar to the chapter [Packaging Your Application](https://picocli.info/#_packaging_your_application) in the documentation, it would be great to have a chapter dedicated to the distribution (for example: "Distributing Your Application").

Distribution can be done by downloading binaries directly or by using a package manager such as
- homebrew, macports
- chocolatey, scoop, winget
- apt-get, yum, dnf
- Snap, FlatPak, AppImage
- ...

**Comment by remkop** [comment]
Not sure about this one...

First, my knowledge in this area is very limited. I know how to publish the picocli binaries to bintray, in a way that they also get published to Maven Central, and that is pretty much it. On the other side, I have consumed packages from chocolatey, apt-get and yum, but that is the full extent of my knowledge. :-)

Second, even just writing about how to publish jar files and documentation for a library to Bintray/Maven Central is not easy to explain in a few paragraphs. If we provide enough detail to be useful, there is enough material for an article of a few pages.

And this is just Bintray/Maven Central. I imagine that documentation for each of these repositories and distribution mechanisms would be a similar amount of material. So overall, this is a lot of documentation. And is this not already available elsewhere? I am not sure how much value can we add by mentioning these in the picocli manual.

**Comment by charphi** [comment]
Indeed, it would be to much to documentation to write.
Maybe some links to some relevant documentation?

To my knowledge, all package managers work similarly but the details are different. It is annoying and time consuming to support several.
The ideal solution would be to have a "magic" Maven plugin that takes care of the tedious steps and generates everything that is needed for each package manager.

**Comment by remkop** [comment]
Do you feel like contributing some documentation? :-)

**Comment by charphi** [comment]
Why not?
I will try to gather links in this conversation as a starting point.

**Comment by charphi** [comment]
Just for fun, here is a list a package managers:
https://en.wikipedia.org/wiki/List_of_software_package_management_systems
I didn't know there were so many.  :sweat_smile:

**Comment by remkop** [comment]
I am perfectly happy not to pursue this further. 😉

**Comment by remkop** [comment]
Shall we close this ticket?

**Comment by charphi** [comment]
Sure.

**Comment by charphi** [comment]
It seems that someone is automating the distribution 😄  
https://github.com/jreleaser/jreleaser and https://github.com/remkop/picocli/issues/1359
