### ISSUE TITLE
Gradle build: switch from 'jcenter()' to 'mavenCentral()' [JCenter will not accept new artifacts after March 31st 2021]

### ISSUE THREAD

**Issue by dejan2609** [remkop/picocli#1322]
I have a two news for you @remkop 
This is a bad one: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter 😞 
> **_May 1st | Bintray, JCenter, GoCenter, and ChartCenter services will no longer be available_**

Good news is that I am here to help 😉 

Complete solution will enable publishing to a Maven Central as easy as possible (and obviously all references to JCenter will be removed in favor of Maven Central).

Stay tuned, I will try to come up with something.

**Comment by remkop** [comment]
Wonderful, much appreciated!

**Comment by remkop** [comment]
Hello @dejan2609, have you had  a chance to look into this?
I hope to do another picocli release in the next week or so, after fixing #1319 and maybe #1318, so this will become relevant soon.

If you can provide links to articles, that would also be useful. 👍

**Comment by dejan2609** [comment]
I have a few updates for you @remkop !

JFrog partially reversed their decision (they made one thing on Feb 3rd and then changed their mind on Feb 08th).
Now they decided to server artifacts via JCenter until **_February 1st 2022_** (but they will stop receiving **new** artifacts after March 31st 2021). https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure

> ### Update 8th Feb
> 
> #### JFrog have released an update to their original blog post to clarify that the date has been extended:
> 
> > _**UPDATE:** To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021._
> > 
> > _To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021._
> 
> (You may have to [refresh the post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter) if since it may have been cached by your browser since you last visited in order to see the update.)

**Comment by dejan2609** [comment]
Some related links:
- https://medium.com/@nmauti/publishing-a-project-on-maven-central-8106393db2c3 
- https://medium.com/@nmauti/sign-and-publish-on-maven-central-a-project-with-the-new-maven-publish-gradle-plugin-22a72a4bfd4b 
- https://getstream.io/blog/publishing-libraries-to-mavencentral-2021
- https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven

Now, I was quite busy investigating (going down the rabbit hole I found out **_many_** things:  `https://github.com/signalapp/Signal-Android/issues/10906`) 
Note: related github issue link is intentionally posted like this (because it contains many related links from around the internet and requires about 20 minutes of reading :relaxed:)

**Comment by dejan2609** [comment]
To sum it up: it seems that you are free to release to JCenter **now**; herewith a new (changed) schedule:
> - _**March 31st, 2021  | No more submissions will be accepted to JCenter**_
> - **_February 1st, 2022  | JCenter will no longer be available for non-Artifactory clients_**

But then again.... it is clear that many projects will seek for a new (permanent) place and that transition to a Maven Central is only a question of time.

I hope I will be able to create some solution and push PR for your project in a few weeks (say, by the Marchmid-March at the latest). Does that works for you ?

**Comment by remkop** [comment]
@dejan2609 Sorry for my late reply.
Yes, in a few weeks is fine. It turns out I am a bit caught up in other projects than picocli at the moment... 👍

**Comment by remkop** [comment]
I may try to do a bugfix release this week in the next few days.
The links you provided are very helpful, started to look into them.
If you have any work in progress that you would like to share, please let me know!
