### ISSUE TITLE
Scan subcommands into a given package or based on an Interface.

### ISSUE THREAD

**Issue by marco-brandizi** [remkop/picocli#1324]
[I've been using picocli][10] for a while and it's great!

Today, I'm faced with the problem of building a package of command/subcommands, which could be extended with subcommands (even in separated jars). This is a use case where having to list all the possible subcommands explicitly isn't very practical, it would be much better if I could tell @Command to pick all subcommands by scanning a package, and/or considering implementations of a given interface.

At the moment, something similar could be done by combining picocli with either [Spring's IoC][20], or the good old [SPI API][30]. In either case, having this feature implemented directly in picocli would make things easier.

[10]: https://marcobrandizi.info/my-maven-archetype-for-java-command-line-projects/
[20]: https://stackoverflow.com/questions/40286047/spring-get-all-beans-of-certain-interface-and-type
[30]: https://www.baeldung.com/java-spi

**Comment by remkop** [comment]
Hi @marco-brandizi, glad you like picocli!

About your proposal that picocli should provide a classpath scanning feature to auto-discover commands, I am not sure I understand how you envision this to work.

A picocli command hierarchy is a tree structure with a single top-level command at the root. Scanning the classpath would result in finding multiple commands, without details on where these commands should be connected into the tree. They may be subcommands of the root command, or sub-subcommands or sub-sub-subcommands etc. 

Somewhere, there needs to be information provided on how to connect a command into the hierarchy.

In picocli, building a command hierarchy can be done statically via the annotations api: `@Command(subcommands = {A.class, B.class})`, or dynamically via the programmatic API with [CommandLine.addSubcommand](https://picocli.info/apidocs/picocli/CommandLine.html#addSubcommand-java.lang.String-java.lang.Object-).

May I suggest that you create the classpath-scanning logic for your application, and use picocli's programmatic API to create the command hierarchy?

Once you have it working for your application we may be in a better position to discuss the pros/cons trade-offs of pulling this logic into the library.

What do you think?

**Comment by marco-brandizi** [comment]
Hi @remkop, thanks for the answer. Do you mean that, if I declare subcommand=Root.class, the command will have Root and all its descendants as subcommands? Would this include descendants in jars other that the one where Root (and the embedding command) is? That is, does the existing mechanism support extensions?

If yes, it already has what I was thinking about, else, I was thinking of telling the main command the packages (eg, com.foo.cli.*) where to to look for subcommand classes (ie, classes annotated with @Command), possibly with the addition of a super-class or super-interface filter.

[Spring works this way](https://www.baeldung.com/spring-component-scanning).

The main reason for doing this, apart from saving from writing a few annotations, is the possibility to add subcommands to an existing package without having to change the latter (ie, open/closed principle).

**Comment by remkop** [comment]
> Do you mean that, if I declare `subcommand=Root.class`, the command will have Root and all its descendants as subcommands? 

No, sorry if I caused any confusion.  Only the specified class or classes in `@Command(subcommands = {A.class, B.class}) class X` would be subcommands of `X`.

> Would this include descendants in jars other that the one where Root (and the embedding command) is? 

When using the `@Command(subcommands = A.class)` API, picocli may need to create an instance of `A`, so `A` needs to be on the classpath. Java does not care whether A lives in another jar, as long as it is on the classpath. 

> That is, does the existing mechanism support extensions?

I am guessing picocli currently does not do what you have in mind. :-)

To clarify:

- If all the subcommands for your command are _known in advance,_ then you can use the annotations API.

- If the subcommands are _not all known in advance_, and your application is discovering them dynamically in some way, then you can use the programmatic API with [CommandLine.addSubcommand](https://picocli.info/apidocs/picocli/CommandLine.html#addSubcommand-java.lang.String-java.lang.Object-) to construct the command hierarchy.

How your application discovers subcommands is completely up to you. Classpath scanning, config files, downloading from another server, the possibilities are endless. There is no limit other than your imagination! :-)

My suggestion is that you build, in your application, the logic for discovering commands. You can use classpath scanning for the `@Command` annotation, or design some other mechanism. (I have other commitments and I will not be able to help you with this.)
Once you have this working we will have a lot more concrete knowledge and we will be in a better position to discuss the pros/cons trade-offs of pulling this logic into the library.

**Comment by marco-brandizi** [comment]
Thanks, very useful clarifications! For the moment, it's likely I'll go with manual annotations.  

For a future improvement, I'm thinking of integrating Spring (to scan all the subcommands from a package and/or root interface specification) and programmatic subcommand addition, after they're discovered.  

If and when I develop this, I'll write an independent/reusable component, that could be considered as a picocli extension (likely, I'll initially put in in [my own toolbox library][10] :-)). Possibly, I'll let you know!

[10]: https://github.com/marco-brandizi/jutils

**Comment by remkop** [comment]
Sounds like a plan! 👍
Enjoy!

**Comment by remkop** [comment]
Closing this ticket for now. Feel free to reopen or open another one at any time.
