### ISSUE TITLE
Hide Java variable name

### ISSUE THREAD

**Issue by zappee** [remkop/picocli#1335]
Hello,

I would like to generate Unix-style documentation but it seems that Picoli not able to generate help without Java variable names.

As you can see in your example [here](https://picocli.info/images/checksum-usage-help.png) the Java variable name is shown:
`-a, --algorithm=<algorithm>`

I would like to have this:
`-a, --algorithm`

For me, this is a little bit weird. The end-user is not interested in seeing the internal representation of the options. She only wants to see the pure options.

Is there any option that hides the Java variable names?

**Comment by remkop** [comment]
One thing: the option parameter label can be controlled with the [paramLabel](https://picocli.info/#_parameter_labels) annotation attribute. 

So you can pick a better name independent from the variable name. 

Boolean options don’t accept a variable, so the usage help for boolean options doesn’t show a parameter label. 

The presence of a parameter label signals to the end user that they cannot just specify an option name: it must be followed by a value. 

That’s why the default usage help message looks the way it does. It is possible to customize this to hide the parameter label. I think there’s an example in a previous issue or one of the `picocli-examples`. I’ll take a look and try to find it.

**Comment by remkop** [comment]
I found the example:

picocli-examples/src/main/java/picocli/examples/customhelp/HideOptionParams.java

Hope this helps. 
Enjoy!

**Comment by zappee** [comment]
I thought that this "feature" was added to the new release and I can get rid of the custom code ;)

**Comment by remkop** [comment]
Not sure what you mean by hides the default value. Can you provide a sample program that demonstrates the issue, and explain what you expected to see and what’s actually happening?

**Comment by remkop** [comment]
Also note that you can embed a variable in the description to show the default value. 

Please see this section of the manual for details: https://picocli.info/#_default_value_variable

**Comment by zappee** [comment]
And I can see still the variable names in the summary despite I use the additional `OptionRender`:

```
Usage: SqlRunner [-?qsv] [-c=<dialect>] [-e=<sqlCommandSeparator>] -U=<user> (-P=<password> | -I)
                 (-j=<jdbcUrl> | (-h=<host> -p=<port> -d=<database>)) <sqlStatements>
```

End users do not care about the Java variable names.

This is what I would like to have:
```
Usage: SqlRunner [-?qsv] [-c] [-e] -U (-P | -I)
                 (-j | (-h -p -d)) <sqlStatements>
```

**Comment by zappee** [comment]
Example for hiding the default value issue:

**This is the original code I used:**
```
@Option(names = {"-c", "--dialect"},
        defaultValue = Dialect.ORACLE_VALUE,
        showDefaultValue = CommandLine.Help.Visibility.ALWAYS,
        description = "SQL dialect used during the execution of the SQL statement. "
                + "Supported SQL dialects: ${COMPLETION-CANDIDATES}.")
private Dialect dialect;
```

But the custom `OptionRender` hides the default value somehow. 

**So I had to add the default value manually:**
```
@Option(names = {"-c", "--dialect"},
        defaultValue = Dialect.ORACLE_VALUE,
        description = "SQL dialect used during the execution of the SQL statement. "
                + "Supported SQL dialects: ${COMPLETION-CANDIDATES}.%n"
                + " Default: " + Dialect.ORACLE_VALUE)
private Dialect dialect;
```

The source code available from [here](https://github.com/zappee/sql-runner).

**Comment by remkop** [comment]
> **So I had to add the default value manually:**
> 
> ```
> @Option(names = {"-c", "--dialect"},
>         defaultValue = Dialect.ORACLE_VALUE,
>         description = "SQL dialect used during the execution of the SQL statement. "
>                 + "Supported SQL dialects: ${COMPLETION-CANDIDATES}.%n"
>                 + " Default: " + Dialect.ORACLE_VALUE)
> private Dialect dialect;
> ```
> 
> The source code available from [here](https://github.com/zappee/sql-runner).

That is almost what I had in mind, yes, I would just suggest using the `${DEFAULT-VALUE}` variable in the description. 

```java
@Option(names = {"-c", "--dialect"},
        defaultValue = Dialect.ORACLE_VALUE,
        description = "SQL dialect used during the execution of the SQL statement. "
                + "Supported SQL dialects: ${COMPLETION-CANDIDATES}.%n"
                + " Default: ${DEFAULT-VALUE}")
```


> End users do not care about the Java variable names.

They are not Java variable names.
[Parameter labels](https://picocli.info/#_parameter_labels) are one-word _descriptions_ of the value that the end user needs to provide.  
You can show any label, it does not need to be the Java variable name.

> And I can see still the variable names in the summary despite I use the additional `OptionRender`:
> 
> ```
> Usage: SqlRunner [-?qsv] [-c=<dialect>] [-e=<sqlCommandSeparator>] -U=<user> (-P=<password> | -I)
>                  (-j=<jdbcUrl> | (-h=<host> -p=<port> -d=<database>)) <sqlStatements>
> ```
> 
> This is what I would like to have:
> 
> ```
> Usage: SqlRunner [-?qsv] [-c] [-e] -U (-P | -I)
>                  (-j | (-h -p -d)) <sqlStatements>
> ```


Quick question: have you asked your end users? You may be surprised. 😉

Anyway, if that is what you want to do, then this is certainly possible.

I added a new example [HideOptionParamsFromSynopsis.java](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/customhelp/HideOptionParamsFromSynopsis.java) that shows how to hide the parameter label from the options in the synopsis. That should give you what you have in mind.  😉 

Enjoy!

**Comment by remkop** [comment]
Hi @zappee, did this solve the issue?

**Comment by zappee** [comment]
Yes, thanks for the help!
