### ISSUE TITLE
missing tags for empty items in adoc man page

### ISSUE THREAD

**Issue by crotwell** [remkop/picocli#1337]
By default the asciidoc man page templates include lines like:
```
include::{includedir}/xxx.adoc[tag=picocli-generated-man-section-exit-status]
```

But a commands without an exit status, these tags are missing in the generated asciidoc man files. This causes asciidoctor to emit a warning like:
```
WARNING: xxx.adoc: line 19: tag 'picocli-generated-man-section-exit-status' not found in include file: xxxxxx/build/picocli/man/xxx.adoc
```

While commenting out the import lines in the template is easy enough, it would be nice if the asciidoc generator could put in empty tages like:
```
// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]
```
so that the no warning is printed.

A fix would be to change
```
    static void genExitStatus(PrintWriter pw, CommandSpec spec) {
        if (spec.usageMessage().exitCodeList().isEmpty()) {
            return;
        }
```
to
```
    static void genExitStatus(PrintWriter pw, CommandSpec spec) {
        if (spec.usageMessage().exitCodeList().isEmpty()) {
            pw.printf("// tag::picocli-generated-man-section-exit-status[]%n");
            pw.printf("// end::picocli-generated-man-section-exit-status[]%n");
            pw.println();
            return;
        }
```

Similar issue with commands, arguments and footer, maybe others.

Using picocli 4.6.1 and gradle asciidoctor plugin 3.3.0.

**Comment by remkop** [comment]
Good point, and thank you for providing the #1338 PR! I added some comment on that ticket.
