### ISSUE TITLE
set exclusive ArgGroup values by implementation of IDefaultValueProvider or by commandline

### ISSUE THREAD

**Issue by McBluna** [remkop/picocli#1343]
### What version are you using?  
4.6.1 from maven

### What is the actual behaviour?
I cannot set the value of an exclusive option in ArgGroup by implementation of IDefaultValueProvider.
```
@Command(name = "demo", defaultValueProvider = PropertyDefaultProvider.class)
public class SimpleDemo implements Runnable {
	@ArgGroup(exclusive = true, multiplicity = "1")
	private final Group group = new Group();
	private static class Group {
		@Option(names = "-d", required = true)
		String d;
		@Option(names = "-e", required = true)
		String e;
	}
	@Override
	public void run() {
		System.out.printf("-> %s, %s", group.d, group.e);
	}
	public static void main(String[] args) {
		new CommandLine(new SimpleDemo()).execute(args);
	}
}
class PropertyDefaultProvider implements IDefaultValueProvider {
	private Properties properties;
	@Override
	public String defaultValue(ArgSpec argSpec) throws Exception {
		if (properties == null) {
			properties = new Properties();
			File file = new File(System.getProperty("user.home"), "defaults.properties");
			try (Reader reader = new FileReader(file)) {
				properties.load(reader);
			}
		}
		return argSpec.isOption() ? properties.getProperty(((OptionSpec) argSpec).longestName()) : properties.getProperty(argSpec.paramLabel());
	}
}

```
Default.properties
`-d=defaultValueForD`
`-e=defaultValueForE`
Commandline
`demo`
```
[picocli DEBUG] Applying default values for command 'demo'
[picocli DEBUG] Applying default values for group '([-d=<d>] | [-e=<e>])'
[picocli DEBUG] Applying defaultValue (defaultValueForD) from net.mcbluna.zidoo.PropertyDefaultProvider@6f7fd0e6 to field String net.mcbluna.zidoo.SimpleDemo$Group.d on Group@47c62251
[picocli DEBUG] 'defaultValueForD' doesn't resemble an option: 0 matching prefix chars out of 2 option names
[picocli INFO] Setting field String net.mcbluna.zidoo.SimpleDemo$Group.d to 'defaultValueForD' (was 'null') for field String net.mcbluna.zidoo.SimpleDemo$Group.d on Group@47c62251
[picocli DEBUG] Applying defaultValue (defaultValueForE) from net.mcbluna.zidoo.PropertyDefaultProvider@6f7fd0e6 to field String net.mcbluna.zidoo.SimpleDemo$Group.e on Group@47c62251
[picocli DEBUG] 'defaultValueForE' doesn't resemble an option: 0 matching prefix chars out of 2 option names
[picocli INFO] Setting field String net.mcbluna.zidoo.SimpleDemo$Group.e to 'defaultValueForE' (was 'null') for field String net.mcbluna.zidoo.SimpleDemo$Group.e on Group@47c62251
Error: Missing required argument (specify one of these): ([-d=<d>] | [-e=<e>])
Usage: demo ([-d=<d>] | [-e=<e>])
  -d=<d>
  -e=<e>
```

Default.properties
`-d=defaultValueForD`
`#-e=defaultValueForE`
Commandline
`demo -e valueForE`
```
[picocli DEBUG] Creating CommandSpec for net.mcbluna.zidoo.SimpleDemo@63e31ee with factory picocli.CommandLine$DefaultFactory
[picocli INFO] Picocli version: 4.6.1, JVM: 14.0.2 (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 14.0.2+12-46), OS: Windows 10 10.0 amd64
[picocli INFO] Parsing 2 command line args [-e, valueForE]
[picocli DEBUG] Parser configuration: optionsCaseInsensitive=false, subcommandsCaseInsensitive=false, abbreviatedOptionsAllowed=false, abbreviatedSubcommandsAllowed=false, aritySatisfiedByAttachedOptionParam=false, atFileCommentChar=#, caseInsensitiveEnumValuesAllowed=false, collectErrors=false, endOfOptionsDelimiter=--, expandAtFiles=true, limitSplit=false, overwrittenOptionsAllowed=false, posixClusteredShortOptionsAllowed=true, separator=null, splitQuotedStrings=false, stopAtPositional=false, stopAtUnmatched=false, toggleBooleanFlags=false, trimQuotes=false, unmatchedArgumentsAllowed=false, unmatchedOptionsAllowedAsOptionParameters=true, unmatchedOptionsArePositionalParams=false, useSimplifiedAtFiles=false
[picocli DEBUG] (ANSI is disabled by default: systemproperty[picocli.ansi]=null, isatty=false, TERM=null, OSTYPE=null, isWindows=true, JansiConsoleInstalled=false, ANSICON=null, ConEmuANSI=null, NO_COLOR=null, CLICOLOR=null, CLICOLOR_FORCE=null)
[picocli DEBUG] Initializing command 'demo' (user object: net.mcbluna.zidoo.SimpleDemo@63e31ee): 2 options, 0 positional parameters, 0 required, 1 groups, 0 subcommands.
[picocli DEBUG] [0] Processing argument '-e'. Remainder=[valueForE]
[picocli DEBUG] '-e' cannot be separated into <option>=<option-parameter>
[picocli DEBUG] Found option named '-e': field String net.mcbluna.zidoo.SimpleDemo$Group.e, arity=1
[picocli INFO] Adding match to GroupMatchContainer ([-d=<d>] | -e=<e>)={} (group=1 ([-d=<d>] | -e=<e>)).
[picocli DEBUG] Creating new user object of type class net.mcbluna.zidoo.SimpleDemo$Group for group ([-d=<d>] | -e=<e>)
[picocli DEBUG] Created net.mcbluna.zidoo.SimpleDemo$Group@77caeb3e, invoking setter FieldBinding(net.mcbluna.zidoo.SimpleDemo$Group net.mcbluna.zidoo.SimpleDemo.group) with scope net.mcbluna.zidoo.SimpleDemo@63e31ee
[picocli DEBUG] Initializing -d=<d> in group ([-d=<d>] | -e=<e>): setting scope to user object net.mcbluna.zidoo.SimpleDemo$Group@77caeb3e and initializing initial and default values
[picocli DEBUG] Set initial value for field String net.mcbluna.zidoo.SimpleDemo$Group.d of type class java.lang.String to null.
[picocli DEBUG] Applying defaultValue (defaultValueForD) from net.mcbluna.zidoo.PropertyDefaultProvider@42d80b78 to field String net.mcbluna.zidoo.SimpleDemo$Group.d on Group@77caeb3e
[picocli DEBUG] 'defaultValueForD' doesn't resemble an option: 0 matching prefix chars out of 2 option names
[picocli INFO] Setting field String net.mcbluna.zidoo.SimpleDemo$Group.d to 'defaultValueForD' (was 'null') for field String net.mcbluna.zidoo.SimpleDemo$Group.d on Group@77caeb3e
[picocli DEBUG] Initializing -e=<e> in group ([-d=<d>] | -e=<e>): setting scope to user object net.mcbluna.zidoo.SimpleDemo$Group@77caeb3e and initializing initial and default values
[picocli DEBUG] Set initial value for field String net.mcbluna.zidoo.SimpleDemo$Group.e of type class java.lang.String to null.
[picocli DEBUG] defaultValue not defined for field String net.mcbluna.zidoo.SimpleDemo$Group.e
[picocli DEBUG] Initialization complete for group ([-d=<d>] | -e=<e>)
[picocli DEBUG] 'valueForE' doesn't resemble an option: 0 matching prefix chars out of 2 option names
[picocli INFO] Setting field String net.mcbluna.zidoo.SimpleDemo$Group.e to 'valueForE' (was 'null') for option -e on Group@77caeb3e
[picocli DEBUG] Applying default values for command 'demo'
[picocli DEBUG] Applying default values for group '([-d=<d>] | -e=<e>)'
[picocli DEBUG] Applying defaultValue (defaultValueForD) from net.mcbluna.zidoo.PropertyDefaultProvider@42d80b78 to field String net.mcbluna.zidoo.SimpleDemo$Group.d on Group@77caeb3e
[picocli DEBUG] 'defaultValueForD' doesn't resemble an option: 0 matching prefix chars out of 2 option names
[picocli INFO] Setting field String net.mcbluna.zidoo.SimpleDemo$Group.d to 'defaultValueForD' (was 'defaultValueForD') for field String net.mcbluna.zidoo.SimpleDemo$Group.d on Group@77caeb3e
-> defaultValueForD, valueForE
```

### What is the expected behaviour?
**Case 1:** no default value from PropertyDefaultProvider and value -d and -e from commmandline
Default.properties
`#-d=defaultValueForD`
`#-e=defaultValueForE`
Commandline
`demo -d=valueForD -e=valueForE`
`Error: -d=<d>, -e=<e> are mutually exclusive (specify only one)`

**Case 2:** no default value from PropertyDefaultProvider and no value from commmandline
Default.properties
`#-d=defaultValueForD`
`#-e=defaultValueForE`
Commandline
`demo`
`Error: Missing required argument (specify one of these): ([-d=<d>] | [-e=<e>])`

**Case 3:** default values for -d and -e from PropertyDefaultProvider and no value from commmandline
Default.properties
`-d=defaultValueForD`
`-e=defaultValueForE`
Commandline
`demo`
`Error: -d=<d>, -e=<e> are mutually exclusive (specify only one)`

**Case 4:** default value for -d from PropertyDefaultProvider and value -e from commmandline
Default.properties
`-d=defaultValueForD`
`#-e=defaultValueForE`
Commandline
`demo -e=valueForE`
`Error: -d=<d>, -e=<e> are mutually exclusive (specify only one)`

**Case 5:** default value for -e from PropertyDefaultProvider and value -d from commmandline
Default.properties
`#-d=defaultValueForD`
`-e=defaultValueForE`
Commandline
`demo -d=valueForD`
`Error: -d=<d>, -e=<e> are mutually exclusive (specify only one)`

**Case 6:** default value for -d and -e from PropertyDefaultProvider and value -d and -e from commmandline
Default.properties
`-d=defaultValueForD`
`-e=defaultValueForE`
Commandline
`demo -d=valueForD -e=valueForE`
`Error: -d=<d>, -e=<e> are mutually exclusive (specify only one)`

**Case 7:** default value for -d from PropertyDefaultProvider and value -d and -e from commmandline
Default.properties
`-d=defaultValueForD`
`#-e=defaultValueForE`
Commandline
`demo -d=valueForD -e=valueForE`
`Error: -d=<d>, -e=<e> are mutually exclusive (specify only one)`

**Case 8:** default value for -e from PropertyDefaultProvider and value -d and -e from commmandline
Default.properties
`#-d=defaultValueForD`
`-e=defaultValueForE`
Commandline
`demo -d=valueForD -e=valueForE`
`Error: -d=<d>, -e=<e> are mutually exclusive (specify only one)`

**Case 9:** default value for -d from PropertyDefaultProvider and value -d from commmandline
Default.properties
`-d=defaultValueForD`
`#-e=defaultValueForE`
Commandline
`demo -d=valueForD`
`-> valueForD, null`

**Case 10:** default value for -d from PropertyDefaultProvider and no value from commmandline
Default.properties
`-d=defaultValueForD`
`#-e=defaultValueForE`
Commandline
`demo`
`-> dafaultValueForD, null`

**Case 11:** default value for -e from PropertyDefaultProvider and value -e from commmandline
Default.properties
`#-d=defaultValueForD`
`-e=defaultValueForE`
Commandline
`demo -e=valueForE`
`-> null, valueForE`

**Case 12:** default value for -e from PropertyDefaultProvider and no value from commmandline
Default.properties
`#-d=defaultValueForD`
`-e=defaultValueForE`
Commandline
`demo`
`-> null, defaultValueForE`

**Comment by remkop** [comment]
I can see what you are trying to do, but I believe the current behaviour is correct.

I disagree with the expected behaviour cases you mention. For example, case 4:
If a mutually exclusive group has 2 options, and one of them has a default value, then the expected behaviour mentioned in case 4 is that the other option (without a default value) can never be specified... Would that not be highly surprising to the end user? The end user correctly specified only one of these exclusive options, but still gets an error... That does not sound right.

Picocli applies default values to options in groups, but these values are not taken into account for validation purposes. I believe this results in the most intuitive behaviour for end users.

**Comment by McBluna** [comment]
Thank you for your anwser and all your hard work.
May be I'll inject the default values read from the config file directly to the args array before the picoli processing or I'll do my own validation.

**Comment by McBluna** [comment]
I've even found a better solution for my case. To avoid the error _Missing required argument_ I've added another option -config to my ArgGroup. So it's the users choice to use the default values from the config file or provide them by cli.
![grafik](https://user-images.githubusercontent.com/32108408/111027919-82390a80-83f3-11eb-8cbc-a74b7a3f9e45.png)

**Comment by remkop** [comment]
Great! Glad you found a solution. :-)
Enjoy!
