### ISSUE TITLE
picocli-codegen: Generate Bash / zsh completions?

### ISSUE THREAD

**Issue by helpermethod** [remkop/picocli#1345]
Hi!

It would be great if picocli-codegen would also spit out Bash/ZSH completion scripts. Maybe by default or hidden behind a configuration flag?

Would you accept a PR? Wdyt?

**Comment by remkop** [comment]
Pull requests would be very welcome!

I was [planning](https://github.com/remkop/picocli/milestones/4.7) to improve this but other commitments are taking my time recently. Any help would be much appreciated!

Related issue #294 has some links that may be useful. 

The `AutoComplete` class may need to be refactored a bit to facilitate completion for multiple shells.

**Comment by remkop** [comment]
@helpermethod I just realized you mentioned `picocli-codegen`, but I assumed you meant the `AutoComplete` class. Just checking: did I jump to the wrong conclusion, and did you actually have something else in mind?

**Comment by helpermethod** [comment]
What I actually had in mind was to generate the Bash completion script  during the Maven build.

Because the script is basically generated code I thought it may make sense to add it to the codegen plugin.

**Comment by remkop** [comment]
Ah, I see!
Yes, that can already be done: see [this section](https://picocli.info/autocomplete.html#_generating_completion_scripts_during_the_build) in the Autocompletion docs.
Is that what you had in mind?

**Comment by helpermethod** [comment]
Awesome, thank you very much! Somehow I've missed this when scanning the docs 😄.

**Comment by remkop** [comment]
Great, glad to hear that solves the issue!
:-)
