### ISSUE TITLE
Required properties of parent commands cause errors in subcommands

### ISSUE THREAD

**Issue by CoderCoco** [remkop/picocli#1350]
Not sure if this has been opened before but I've been trying to see if there was a solution for this in the library and couldn't find one.

Basically I have created a simple CLI that has an interactive and non-interactive mode and am using this project. By default I have it go down the non-interactive path which requires some command line arguments. In the interactive path, it will prompt for all values.

I structured this cli to have the interactive command be triggered as a subcommand. So you would call it like `cmd interactive`. This has caused some issue with the parsing of non-shared  parent properties. Below is an example of what can cause this.

```Kotlin
@Command(
  name = "interactive",
  description = ["Interactive Walkthrough"]
)
class SubTest : Callable<Int> {
  override fun call(): Int {
    println("in interactive")
    return 0
  }
}

@Command(
  name = "test",
  mixinStandardHelpOptions = true,
  version = ["CLI V1.0"],
  description = ["Parent Command"],
  subcommands = [SubTest::class],
)
class Test : Callable<Int> {
  @Option(
    names = ["-v", "--verbose"],
    description = [
      "Generate more detailed log information"
    ],
    scope = ScopeType.INHERIT
  )
  var isVerbose: Boolean = false
    private set
  
  @Option(
    names = ["-r", "--required-in-parent"],
    description = ["Is required by the parent but not child"],
    required = true
  )
  var isRequiredInParent: Boolean = true
    private set
  
  override fun call(): Int {
    println("In Test")
    
    return 0
  }
}

fun main(args: Array<String>) : Unit = exitProcess(CommandLine(Test()).execute(*args))
```

- If you issue `test` it will complain that the required param isn't set which I agree with.
- If you issue `test interactive` it will also complain that `--required-in-parent` isn't set even though it wasn't shared to the child
  - Adding this flag resolves the issue but it should not be needed in the first place.

I plan on working around this by setting required to false on the parent command option and doing the check myself.

**Comment by remkop** [comment]
The way that picocli's validation works is that if there are any required options for `test`, and the `test` command is specified on the command line, then picocli will complain if any required options are missing, regardless of whether any subcommands are also specified...

So yes, I guess that for your use case it may be better to not make  `--required-in-parent` required, and do the validation in the application (only when the parent command's run method is invoked, and not when the child command's run method is invoked).

Hope this helps! :-)
Enjoy using picocli!

**Comment by CoderCoco** [comment]
Sounds good, I wasn't too sure about this as I couldn't find any notes or issues on the subject. The work around isn't really that bad either.

I just do

```kotlin
@Command(
  name = "test",
  mixinStandardHelpOptions = true,
  version = ["CLI V1.0"],
  description = ["Parent Command"],
  subcommands = [SubTest::class],
)
class Test : Callable<Int> {
  @Option(
    names = ["-v", "--verbose"],
    description = [
      "Generate more detailed log information"
    ],
    scope = ScopeType.INHERIT
  )
  var isVerbose: Boolean = false
    private set
  
  @Option(
    names = ["-r", "--required-in-parent"],
    description = ["Is required by the parent but not child"],
    required = true
  )
  var isRequiredInParent: Boolean = true
    private set

  @Spec
  lateinit var spec: Model.CommandSpec
  
  override fun call(): Int {
    println("In Test")

    val command = spec.commandLine().parseResult
    if(command.matchedOption("required-in-parent") == null) {
      System.err.println("missing argument --required-in-parent")
      return 1
    }
    
    return 0
  }
}
```

**Comment by remkop** [comment]
Awesome, glad you found a solution!

Is there any work remaining, or are you okay to close this ticket?

Enjoy picocli!
:-)

**Comment by remkop** [comment]
@CoderCoco I will go ahead and close this ticket; let me know if I missed something, we can always reopen it! :-)
