### ISSUE TITLE
completionCandidates() called during help output even if not going to be used

### ISSUE THREAD

**Issue by vstriz** [remkop/picocli#1351]
I have some cli commands that interact with the server. One of parameters has a completionCandidates setting that talks to the server to figure out the list of possible values, which can be dynamic. It looks like when I ask for "--help" of the command it also invokes the completionCandidates, even though the result is not going to be used. It gets it just in case it will need to use in the description if `"${COMPLETION-CANDIDATES}"` is specified. But in my case it's not used in description.  My situation is even worse, sometimes I have no connection to the server, and therefore I'm unable to display the command help at all.

It would be nice, and more optimal in case of expensive operation, if the completionCandidates for help of commands was invoked only if needed. I.e. when `"${COMPLETION-CANDIDATES}"` is actually specified in description.

The code in question is in `picocli.CommandLine.Model.ArgSpec.expandVariables(String[])`

**Comment by remkop** [comment]
I see, interesting.
Will you be able to provide a pull request for this, ideally with tests?
I would be happy to accept a patch but currently a bit overwhelmed with other commitments to work on this myself...

**Comment by vstriz** [comment]
I'll see what I can do, but probably not for some time. Busy myself :)

I'm also on an older version picocli right now, which looks like might require some changes on my side to upgrade to latest. We'll have to look at that later.

**Comment by Lanninger08** [comment]
Hello, I wonder if this issue is still open, and I would like to work on this issue :).

**Comment by remkop** [comment]
@Lanninger08 Hi!
As far as I know nobody has done any work on this. 
Contributions are very welcome!

Great pull requests include tests and documentation (docs not always needed, like for bug fixes). Also nice to be consistent with the existing code style (spaces vs tabs, code layout etc), but that is not documented and I'm flexible. 

Thanks for offering to spend time on this!

**Comment by Lanninger08** [comment]
Hi! @remkop 
Sorry for the bothering but may I ask a question about the code..when will `desc.length` greater than 1? Thanks a lot for your help! :)
``` java
private String[] expandVariables(String[] desc) {
    if (desc.length == 0) { return desc; }
    StringBuilder candidates = new StringBuilder();
    if (completionCandidates() != null) {
        System.out.println("invoked here!");
        for (String c : completionCandidates()) {
            if (candidates.length() > 0) { candidates.append(", "); }
            candidates.append(c);
        }
    }
    String defaultValueString = defaultValueString(false); // interpolate later
    String fallbackValueString = isOption() ? ((OptionSpec) this).fallbackValue : ""; // interpolate later
    String mapFallbackValueString = String.valueOf(mapFallbackValue); // interpolate later
    String[] result = new String[desc.length];
    for (int i = 0; i < desc.length; i++) {
        result[i] = format(desc[i].replace(DESCRIPTION_VARIABLE_DEFAULT_VALUE, defaultValueString.replace("%", "%%"))
                .replace(DESCRIPTION_VARIABLE_FALLBACK_VALUE, fallbackValueString.replace("%", "%%"))
                .replace(DESCRIPTION_VARIABLE_MAP_FALLBACK_VALUE, mapFallbackValueString.replace("%", "%%"))
                .replace(DESCRIPTION_VARIABLE_COMPLETION_CANDIDATES, candidates.toString()));
    }
    return interpolate(result);
}
```

**Comment by remkop** [comment]
@Lanninger08 `desc.length` can be between 0 and the max size of an array: the description of a command or option is an array that can contain multiple strings. For example:

```java
@Command(description = {
            "line 1",
            "line 2",
            "line 3"})
class Example {
    @Option(name = "-x", description = {
            "line 1",
            "line 2",
            "line 3"})
    String x;
}
```

**Comment by vstriz** [comment]
@remkop I am  excited to see this issue fixed in upcoming release, but it's been a while since 4.6.1 was done. Any plan/word on when 4.6.2 will be released? Thanks.

**Comment by remkop** [comment]
@vstriz picocli 4.6.2 has just been released. Enjoy!
