### ISSUE TITLE
Add the ability to access `Interpolator` functionality

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#1353]
It would be very useful to be able to leverage the same interpolation functionality that the library does in an application context. For example, I have a `Terminal` abstraction that helps commands write output to stdout / stderr. There are several contexts in which I need to reuse message bundle resources for this output. It would be nice to be able to do either inject a `Interpolator` or be able to call `CommandLine#interpolate`, `CommandLine#getInterpolator`, etc. to access this facility.

**Comment by remkop** [comment]
Will you be able to provide a pull request with tests and documentation, and ideally help support future issues related to this functionality? 😉

**Comment by remkop** [comment]
To be fully honest, I don't have the bandwidth to do this now, and I don't see that changing in the near future. I also hesitate to increase my own workload with regards to future support tasks.

So, if you cannot volunteer to take care of these things (which is totally fine of course), then I don't really see it happen. Sorry to disappoint but I figured it is better to be clear.

What do you think?

**Comment by bobtiernay-okta** [comment]
That's fair. Thoughts on adding a CommandLine getter for the Interpolator? Would you be open to a PR?

**Comment by remkop** [comment]
My previous two comments summarize my thoughts. I’d be asking for a PR with tests and documentation, and a willingness to support issues and requests for future enhancements that undoubtedly will arise from this. :wink:

**Comment by sustc11810424** [comment]
It seems that interpolators are created implicitly and differ only in the CommandSpecs they belong to. What about making them directly associated with resource bundles and adding getter/setters for CommandLine? Am I understanding it right? If yes, I'm willing to implement it.

**Comment by remkop** [comment]
I am not sure that I want to expose picocli's interpolator functionality as a reusable generic API: I imagine that this will result in multiple follow-up requests for further enhancements and features, and I am not sure that I  will have the bandwidth to give those the attention they deserve...

Applications looking for this functionality: would a generic interpolator like [commons-text StringSubstitutor](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringSubstitutor.html) or [commons-lang3 StrSubstitutor](https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/text/StrSubstitutor.html) meet your requirements?

**Comment by remkop** [comment]
Looking closer at [commons-text StringSubstitutor](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringSubstitutor.html), this seems to provide exactly the functionality that is being asked for here, and more. For all the reasons mentioned above I believe that this is the best solution long term. I will close this ticket.
