### ISSUE TITLE
print entire help of CLI

### ISSUE THREAD

**Issue by kaushalkumar** [remkop/picocli#1356]
Hi - we are developing a CLI with several subcommands and each subcommand has options and parameters (few of which are common and few are specific).
In pursuit of providing a better usage documentation, users at times look towards checking all subcommands and each command usage. Its like a wiki of CLI. If there is an option available in picocli to print entire usage, then the users may find it useful. 

Can you please let us know if this is available/possible.

**Comment by remkop** [comment]
Is [the ShowCommandHierarchy example](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/customhelp/ShowCommandHierarchy.java) (in picocli-examples) similar to what you are looking for?

**Comment by remkop** [comment]
I am hoping that the ShowCommandHierarchy answered the question.
Closing the ticket for now, please reopen or comment as needed.
