### ISSUE TITLE
spring-boot-starter and ExceptionHandler

### ISSUE THREAD

**Issue by xenoterracide** [remkop/picocli#1357]
I was doing this f*before* now

```java
    var cli = new CommandLine( new Application() );
    cli.setCaseInsensitiveEnumValuesAllowed( true );
    cli.registerConverter( Level.class, Level::valueOf );
    cli.setExecutionExceptionHandler( new ExceptionHandler() );
    System.exit( cli.execute( args ) );
```

```java
  static class ExceptionHandler implements CommandLine.IExecutionExceptionHandler {

    @Override
    public int handleExecutionException(
      Exception ex,
      CommandLine commandLine,
      CommandLine.ParseResult parseResult
    ) {
      var log = LogManager.getLogger( this.getClass() );
      log.debug( "", ex );
      log.error( ex );
      return 1;
    }
  }
```

now I'm doing this

```java
@Component
class CliRunner implements CommandLineRunner, ExitCodeGenerator, CommandLine.IExecutionExceptionHandler {

  private int exitCode = 0;
  private final CliCommand cliArgs;
  private final CommandLine.IFactory iFactory;

  CliRunner( CliCommand cliArgs, CommandLine.IFactory iFactory ) {
    this.cliArgs = cliArgs;
    this.iFactory = iFactory;
  }

  @Override
  public void run( String... args ) {
    var cli = new CommandLine( cliArgs, iFactory );
    cli.setCaseInsensitiveEnumValuesAllowed( true );
    cli.registerConverter( Level.class, Level::valueOf );
    cli.setExecutionExceptionHandler( this );
    this.exitCode = cli.execute( args );
  }

  @Override
  public int getExitCode() {
    return exitCode;
  }

  @Override
  public int handleExecutionException(
    Exception ex,
    CommandLine commandLine,
    CommandLine.ParseResult parseResult
  ) {
    var log = LogManager.getLogger( this.getClass() );
    log.debug( "", ex );
    log.error( ex );
    return 1;
  }
}
```

I created an [upstream issue which has a suggested workaround](https://github.com/spring-projects/spring-boot/issues/25945#issuecomment-816323615) but it seems inelegant, also seems like you could provide helper classes, or perhaps do the rethrow yourself.

**Comment by remkop** [comment]
I don't see anything wrong with the code you posted.
Are things not working as expected?

Are you anticipating issues when converting this code to code that uses the Spring boot starter?
Or are you actually experiencing issues with some code that uses the Spring boot starter? If the latter, what do you see is happening?

**Comment by xenoterracide** [comment]
no, sorry, I think I left out the important details, assuming for some reason that it was obvious via mention of spring boot, and the return code. Also, it was originally a question. Updating the code (note: I've suggested to upstream a better upstream interface)

**Comment by remkop** [comment]
Ok, but I still don't understand the problem.
Your code is working, but you want it to be more elegant, or something?
Can you be like super-super clear about what you want me to do?
