### ISSUE TITLE
Support for records

### ISSUE THREAD

**Issue by Pante** [remkop/picocli#1358]
I currently have the a class which holds the configuration options passed in from the command line which seems like a candidate for replacing with a record in JDK 16. 
```java
public class Configuration {
   @Option(names = {"--user"}, description = "username for database")
    public String user;
    @Option(names = {"--pass"}, description = "password for database")
    public String pass;
}
```
However, the syntax for records does not allow field declarations which makes it impossible to use with picocli.  Is is possible to support annotating the parameters of a record's constructor instead? I understand it's a really minor issue since we can always use a class instead of a record but I feel it's still worth exploring.

**Comment by remkop** [comment]
Hi @Pante, please take a look at previous discussions about the topic of constructor injection in  #1107 and #1195.

Long story short: this is actually quite complex to design and implement and I don't have the bandwidth to work on this at the moment. :-)

**Comment by Pante** [comment]
Ahh I see, I guess I’ll stick to normal classes for the time being then, it’s not a big issue anyways.

**Comment by remkop** [comment]
No worries! :-)
Closing this ticket.
