### ISSUE TITLE
builder injection

### ISSUE THREAD

**Issue by xenoterracide** [remkop/picocli#1361]
re: https://github.com/remkop/picocli/issues/1281#issuecomment-751356302 I don't think the proposed solution is great since it kind of assumes I want to run all tests that take the object using picocli, which I would prefer to avoid. Mocking seems to be one current solution.

so an alternative to constructor injection (especially as it occurs to me that constructor injection won't work much of the time) is other kinds of "bean" injections, such as setter injection, or perhaps more preferably builder style injection, such as what you can do with [Jackson](https://www.baeldung.com/jackson-deserialize-immutable-objects). You could even make it work with [immutables](https://immutables.github.io), by annotating getters instead (ideally even on an interface.

**Comment by remkop** [comment]
Hi @xenoterracide!
picocli currently supports [`@Option` and `@Parameters`-annotated methods](https://picocli.info/#option-parameters-methods).

Applications can annotate getter methods of an interface (where picocli creates a proxy-backed instance), and setter methods of a concrete class.

Hopefully this goes some way towards your needs.

**Comment by xenoterracide** [comment]
@remkop had trouble finding that, but it wouldn't work (easily) for the immutables case would it, and I'm not actually certain it would work for a builder as it wouldn't call build.

**Comment by remkop** [comment]
Sorry, I am having trouble reading between the lines.
If there is a question or change request, could you make it explicit?

**Comment by remkop** [comment]
Revisiting older tickets. Is there a remaining action item for this ticket? Can we clarify or alternatively close this?
