### ISSUE TITLE
Handling multiple default values for multiple value parameter

### ISSUE THREAD

**Issue by demongolem-biz** [remkop/picocli#1365]
I have a Parameter (in that they are free-text based entries that are not constrained).  This parameter, could have multiple values as specified in Section 6 of the documentation.  And by default, I would like the parameter to have 2 values (a Java list of size 2).  The `defaultValue` of a parameter is a String, so it does not seem to nicely take 2 values.  Is there a way I can do this?

`
    @Parameters(paramLabel="myparams" description="test multiple parameters", defaultValue=???) 
    private List<String> myParams;
`

I could imagine doing
`private List<String> myParams = Arrays.asList("hamburger", "bench");`
but then I would not be using picocli?

Oh and I should say these really are freeform labels and therefore cannot be options.  Nor do they constitute individual parameters.

**Comment by remkop** [comment]
Yes, this would work:

```java
@Parameters(paramLabel="myparams", description="test multiple parameters") 
private List<String> myParams = Arrays.asList("hamburger", "bench");
```

alternatively, if you want to use the annotations (perhaps because you want to show the default value in the usage help with the `${DEFAULT-VALUE}` variable), you can specify a single string and split on a space:

```java
@Parameters(paramLabel="myparams", description="test multiple parameters, default: ${DEFAULT-VALUE}",
       defaultValue = "hamburger bench", split = " ") 
private List<String> myParams;
```

**Comment by demongolem-biz** [comment]
This does work for me.  I did not know about `split` and knowing about that makes it much easier to think about the problem.  I see it is sort of talked about in 6.2 Split Regex, but I was not thinking about it in this context I guess.
