### ISSUE TITLE
Arragement of Exclusive and Dependent Arg Groups

### ISSUE THREAD

**Issue by demongolem-biz** [remkop/picocli#1367]
I was going through sections 8.1 and 8.2 of the guide and see how both work independently: exclusive and dependent option groups.  What I am trying to do is something like (writing down the boolean logic) a | (b & c).  So first, I have an arg group for the right side (a dependent one) to do b & c.  Then I would want to do and exclusive arg group which would somehow select option a if it is given on the command line and if not enforce that both b and c are on the command line.

Is ArgGroup the correct way to do this using picocli?  If not how would it be done?  Essentially, I am saying enter a known name in option a and if I don't know that name, then define it through options b and c.

and just to be clear what I am going after, let me draw a truth table.  A few of them might be don't care's but I want the user to enter exactly the correct information.

A   B   C    COND
Y   Y    Y    ERROR
Y   Y    N   ERROR
Y   N    Y    ERROR
Y   N    N   VALID
N   Y    Y    VALID
N   Y    N    ERROR
N   N   Y     ERROR
N   N    N    ERROR

**Comment by remkop** [comment]
Yes, ArgGroups can help accomplish that.

Here is a simple example command with synopsis `cmd -a <a> | (-b <b> & -c <c>)`:

```java
@Command(name = "cmd")
public class Composite {

    @ArgGroup(exclusive = true, multiplicity = "1")
    Composite composite;

    static class Composite {
        @Option(names = "-a", required = true) int a;

        @ArgGroup(exclusive = false, multiplicity = "1")
        Dependent dependent;
    }

    static class Dependent {
        @Option(names = "-b", required = true) int b;
        @Option(names = "-c", required = true) int c;
    }
}
```

**Comment by demongolem-biz** [comment]
Thanks, I was trying to put the Dependent and the Exclusive together instead of Dependent and Composite as you have.

I do have a follow-up question to this scenario.  Argument `a` from above is a custom type for me and I was already successfully using a converter to create it.  Now that I have arguments `b` and `c` if the user were to enter `b `and `c`, I want to create the same sort of custom type from that.  I see I cannot apply converter to the ArgGroup so while `a` in the composite can specify converter how would I specify a converter for the Dependent?  I am looking at 4.2.2 Multi Parameter Type Converters as that might be the correct path but I don't see how I can get both `b` and `c` to go to the same converter at once.  If I made `b` and `c` a collection I am sure that would help, but could I maintain `b` and `c` as separate command line arguments?  Also, I am wondering should I use the same converter for both the `a` and the `b`,`c` routes or a different one, perhaps a question of best practice.

**Comment by remkop** [comment]
@demongolem-biz Sorry I just realized your question had dropped below my inbox horizon.

You want to have a custom composite type for `b` and `c`?
I guess this is a question of how to do validation, to ensure that the user-specified values for `b` and `c` are a valid composite value. One way I can think of is to have a getter method in the ArgGroup for `b` and `c`, that returns the custom type from the user-specified values for `b` and `c`. 
Your application would call that getter method from its business logic.
If the user input is invalid, the getter method could throw a `ParameterException`, as detailed in the user manual section on [custom validation](https://picocli.info/#_custom_validation).

For example:

```java
@Command(name = "cmd")
public class CompositeCommand implements Runnable {
    
    @Spec CommandSpec spec;

    @ArgGroup(exclusive = true, multiplicity = "1")
    Composite composite;

    static class Composite {
        @Option(names = "-a", required = true) int a;

        @ArgGroup(exclusive = false, multiplicity = "1")
        Dependent dependent;
    }

    static class Dependent {
        @Option(names = "-b", required = true) String b;
        @Option(names = "-c", required = true) String c;

        MyType getCustomType() {
            if (invalidValues) {
                throw new ParameterException(spec.commandLine(),
                    String.format("Invalid combination '-b=%s', '-c=%s'", b, c));
            }
            return new MyType(b, c);
        }
    }

    static MyType {
        public MyType(String b, String c) {
            //...
        }
    }

    public void run() {
        MyType myType = composite.dependent.getCustomType();
        // do stuff with myType
    }
}
```
