### ISSUE TITLE
Problem interaction between ArgGroup/boolean/sub-command

### ISSUE THREAD

**Issue by gwinstanley** [remkop/picocli#1368]
There seems to be a conflict when using i18n alongside boolean options within sub-commands, in which the booleans are apparently misidentified. I've attached a minimal example Gradle project to demonstrate, but the definition is essentially as follows:
```
@Command(name = "foo",
         resourceBundle = "foo.Main",
         version = "1.0",
         subcommands = {
           Main.List.class,
         }
)
public final class Main
{
  @Spec
  CommandSpec spec;

  @Command(name = "list", resourceBundle = "foo.Main")
  final static class List implements Callable<Integer>
  {
    @ArgGroup(exclusive = true, multiplicity = "1")
    Exclusive args;

    static class Exclusive
    {
      @Option(names = {"-a", "--all"}, required = true, descriptionKey = "foo.list.a")
      boolean all;
      @Option(names = {"-l", "--label"}, required = true, paramLabel = "<label>", descriptionKey = "foo.list.d")
      String label;
    }

    @Override
    public Integer call() throws Exception
    {
      //...etc.
      return 0;
    }
  }
  
  public static void main(String[] argv) throws IOException
  {
  	//...etc.
  }
}

```
As I understand it, for this code the **list** sub-command should allow either `-a` or `-d=...` options, but not both. However it fails with the message "**Invalid value for option '--all': '...' is not a boolean**", when clearly it is a _boolean_. The non-i18n equivalent of the same class works as expected.

Unrelated, I'm finding i18n with picocli a rather frustrating experience, in particular reliably identifying which keys to use for sub-commands' options, and being unable to determine how to assign i18n to option parameter labels (e.g. for `paramLabel = "<label>"` above).

[picofoo.zip](https://github.com/remkop/picocli/files/6404884/picofoo.zip)

**Comment by sustc11810424** [comment]
I've checked you code and the problem seems to be caused by

```java
    Properties props = new Properties();
    try (InputStream in = Main.class.getResourceAsStream("Main.properties"))
    {
      props.load(in);
    }
    if (!props.isEmpty())
      cmd.setDefaultValueProvider(new CommandLine.PropertiesDefaultProvider(props));
```

This code tries to set default values for the options using what's in `property` (i,e. all="list all element") and this is why it says `Invalid value for option '--all': 'list all items' is not a boolean`. 

In this case it looks like specifying the resource bundle when defining the class is sufficient to let it read the descriptions from file. You can have a try by removing the code mentioned above.

**Comment by remkop** [comment]
@sustc11810424 Thank you for looking into this! Awesome.

**Comment by gwinstanley** [comment]
What a foolish oversight of mine! Many thanks @sustc11810424, I clearly failed to spot that when pruning down my main app to this example. I'll persist in trying to wrangle i18n for my main app, and appreciate the fast response.
