### ISSUE TITLE
ReadConsoleInputW failed after upgrade to jansi 2.3.2

### ISSUE THREAD

**Issue by auricgoldfinger** [remkop/picocli#1369]
Today, we upgraded some libraries in our picocli tool. Amongst them, there was a serious upgrade from Jansi 1.8 to 2.3.2.
Suddenly, `picocli-shell-jline3` crashed on us. I tried to run [the example](picocli-shell-jline3) and it suffers from exactely the same issue:

```
WARNING: Error in WindowsStreamPump
java.io.IOException: ReadConsoleInputW failed: The specified procedure could not be found.
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:530)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:126)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
        at java.base/java.lang.Thread.run(Thread.java:831)
```
.. then the console crashes.

In our tool, after `AnsiConsole.systemInstall()`, we also do `Ansi.setEnabled(true);`. Then this error is thrown:

```
WARNING: Error in WindowsStreamPump
java.io.IOException: ReadConsoleInputW failed: Incorrect function.
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:530)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:126)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

Important to note, we're using Git Bash in ConEmu. I had the latest stable version running, some older version, so I upgraded it as well (to Build 210422) and that didn't solve the problem.
When I run the command (both the example as well as our own tool) in Windows Terminal, it works fine.

Does anyone have any idea how to solve this?

**Comment by remkop** [comment]
This looks like a Jansi issue. Have you raised this in the Jansi issue tracker?

**Comment by auricgoldfinger** [comment]
When I disable Jansi completely, the problem is that a dumb terminal is created in stead of a real one. Then everying crashes in a stackoverflow.

I was able to solve it by forcing jline to be the latest version as well in the gradle build:
```
constraints {
    implementation("org.jline:jline") {
        version{
            require "3.19.0"
        }
    }
}
```
... then everything works fine in Git Bash and ConEmu... 

It's broken again in Windows Terminal but I can live with that. It used to be broken anyway. Terminals on Windows, it stays a complex story

**Comment by remkop** [comment]
Is there something that can be done in picocli to help with this?
Maybe a note in the picocli-shell-jline3 README?
Would you be interested in providing a pull request for this?

**Comment by auricgoldfinger** [comment]
Done! It's just a simple upgrade of the jline3 version :-)
