### ISSUE TITLE
java.lang.reflect.AccessibleObject to be sealed in Java 17

### ISSUE THREAD

**Issue by kaspernielsen** [remkop/picocli#1372]
CommandLine.Model.MethodParam extends it.

It is currently being integrated here https://github.com/openjdk/jdk/pull/4133

**Comment by remkop** [comment]
@kaspernielsen Thank you for raising this!

Fortunately it was decided that Executable would be sealed, not AccessibleObject, to prevent existing versions of Guava and picocli to stop working with Java 17.

The AccessibleObject constructor will been marked as `@Deprecated` from java 17, so perhaps picocli should consider an alternative design than extending AccessibleObject. Still need to do analysis to see whether that is feasible: such a change may impact binary compatibility for applications that use or customize picocli.

**Comment by remkop** [comment]
Closing this ticket; no action required.
