### ISSUE TITLE
How can I get a list of entered options?

### ISSUE THREAD

**Issue by stepanstefan** [remkop/picocli#1375]
Hello, maybe this has already been asked or is in the documentation, but I really couldn't find anything. How do I can a list of entered options?
I have multiple optionals and want to perform certain actions in call () if options data was entered? Thank you.

**Comment by remkop** [comment]
Hi @stepanstefan, is this what you are looking for?

https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/parseresult/ParseResultDemo.java

**Comment by stepanstefan** [comment]
> Hi @stepanstefan, is this what you are looking for?
> 
> https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/parseresult/ParseResultDemo.java

yes, thanks! 


And if it's not difficult for you, please tell me. Why is it showing false for all options here? Although if you display any field, then it will be filled with a value with an argument.

` @CommandLine.Command(name = "resizer", mixinStandardHelpOptions = true, version = "resizer 0.0.1")
public class ResizerApp implements Callable<Integer> {

    @CommandLine.Spec
    CommandLine.Model.CommandSpec spec;

    @CommandLine.Parameters(description = {"Image to be changed"}, paramLabel = "IMAGE")
    private File inputImage;

    @CommandLine.Option(names = {"-r", "--resize"}, arity = "2", parameterConsumer = ResizeConverter.class)
    private ResizeConverter.ResizingSize resizingSize;

    @CommandLine.Option(names = {"-c", "--crop"}, arity = "4", parameterConsumer = CropConverter.class)
    private CropConverter.CroppingSize croppingSize;

    public static void main(String... args) {
        int exitCode = runConsole(args);
        System.exit(exitCode);
    }

    protected static int runConsole(String[] args) {
        return new CommandLine(new ResizerApp()).execute(args);
    }

    @Override
    public Integer call() throws Exception {
        CommandLine.ParseResult pr = spec.commandLine().getParseResult();

        List<CommandLine.Model.OptionSpec> options = spec.options();
        for (CommandLine.Model.OptionSpec opt : options) {
            System.out.printf("%s was specified: %s%n",
                    opt.longestName(), pr.hasMatchedOption(opt));
            System.out.printf("%s=%s (-1 means this option was not matched on command line)%n",
                    opt.shortestName(), pr.matchedOptionValue(opt.longestName(), -1));
            System.out.printf("%s=%s (arg value or default)%n",
                    opt.longestName(), opt.getValue());
            System.out.println();
        }
        return 1;
    }
} `

**Comment by remkop** [comment]
> And if it's not difficult for you, please tell me. Why is it showing false for all options here? Although if you display any field, then it will be filled with a value with an argument.

Can you show me what arguments you provided, what the actual output was, and what output you expected?

**Comment by stepanstefan** [comment]
> > And if it's not difficult for you, please tell me. Why is it showing false for all options here? Although if you display any field, then it will be filled with a value with an argument.
> 
> Can you show me what arguments you provided, what the actual output was, and what output you expected?

arguments - "st.in --resize 10.0 10.0 --crop 1.0 1.0 1 1"
options fields are updated, but all options "specified" = false.
![image](https://user-images.githubusercontent.com/64232056/119775162-e8e6a400-becb-11eb-8b68-5654bc2ca3a8.png)

**Comment by remkop** [comment]
Oh wait, I think it is because of the custom [`parameterConsumer`](https://picocli.info/#_custom_parameter_processing)...

The custom `IParameterConsumer` suspends all picocli processing, and that is why those options are not registered in the ParseResult even when they are matched.
I had a quick look but there is no public API that allows you to update the `ParseResult` while parsing the input.

One thing you could consider is using [`IParameterPreprocessor`](https://picocli.info/#IParameterPreprocessor_Parser_Plugin) instead of `IParameterConsumer`. That allows you to take some custom action first, and then let picocli's resume processing that option. When picocli's processing is resumed, it will register the matched options in the ParseResult. Not sure if that is feasible for your use case.

Another option is to manually track which options were matched in your custom `IParameterConsumer` implementation; you may need to use a static Map or a ThreadLocal to share that information with the business logic of your command.

**Comment by stepanstefan** [comment]
> Oh wait, I think options are reported as "not matched" in the ParseResult because of the custom [`parameterConsumer`](https://picocli.info/#_custom_parameter_processing)...
> 
> The custom `IParameterConsumer` suspends all picocli processing, and that is why those options are not registered in the ParseResult even when they are matched.
> I had a quick look but there is no public API that allows you to update the `ParseResult` while parsing the input.
> 
> One thing you could consider is using [`IParameterPreprocessor`](https://picocli.info/#IParameterPreprocessor_Parser_Plugin) instead of `IParameterConsumer`. That allows you to take some custom action first, and then let picocli resume processing that option. When picocli's processing is resumed, it will register the matched options in the ParseResult. Not sure if that is feasible for your use case.
> 
> Another option is to manually track which options were matched in your custom `IParameterConsumer` implementation; you may need to use a static Map or a ThreadLocal to share that information with the business logic of your command.

Thank you so much for your time and for your answers, I am very grateful. Have a good day.
