### ISSUE TITLE
[Feature Request] Support specification of DefaultValueProvider within @Parameter/@Option annotation

### ISSUE THREAD

**Issue by sebthom** [remkop/picocli#1376]
I am heavily using picocli's handy mixin feature to reuse option definitions.
I am also make heavy use of dynamic default values for options (based on default config file values).

Since my commands directly declaring some unique options (with dynamic default values) and also each using different combinations of mixins I feel very limited in the creation of a good, expressive class design (separation of concerns, modularity, reusablity, DRY etc) because I can only specify a single DefaultValueProvider per command and it has to be specified at command level and thus needs to provide all dynamic default values for all direct options and all options declared within any mixin.

Therefore I would like to request the possibility to also being able to specify a DefaultValueProvider  directly as part of the option annotation. E.g.

```java
class AuthMixin {
  @Option(defaultValueProvider=MyAuthDefaultValueProvider.class)
  String user;

  @Option(defaultValueProvider=MyAuthDefaultValueProvider.class)
  String password;
}

class LimitsMixin {
  @Option(defaultValueProvider=MyLimitsDefaultValueProvider.class)
  int maxRam;

  @Option(defaultValueProvider=MyLimitsDefaultValueProvider.class)
  int maxCPU;
}

@Command
class ListCommand {
  @Mixin
  AuthMixin auth;
}

@Command
class ConfigureCommand {
  @Mixin
  AuthMixin auth;

  @Mixin
  LimitsMixin limits;
}

class picocli.CommandLine.Option {

    String defaultValue() default "__no_default_value__";

    /**
     * Specifying @{@link #defaultValue()) or @{@link #defaultValueProvider()) is mutually exclusive.
     */
     Class<? extends IDefaultValueProvider> defaultValueProvider() default NoDefaultProvider.class;

     // ...
}

class picocli.CommandLine.Parameters {
    String defaultValue() default "__no_default_value__";

    /**
     * Specifying @{@link #defaultValue()) or @{@link #defaultValueProvider()) is mutually exclusive.
     */
     Class<? extends IDefaultValueProvider> defaultValueProvider() default NoDefaultProvider.class;

     // ...
}

```

**Comment by remkop** [comment]
Hi @sebthom, can you clarify a bit what the problem is with having a default provider per command? I understand the proposed solution but I am not sure I understand what problem we are trying to solve.

Can you show a concrete example of what the pain point is with the current available mechanisms?

**Comment by remkop** [comment]
@sebthom Looking at this issue again after a long break, thanks for your patience!

One idea is to have a delegating default provider that, based on the option, delegates to some sub default provider.
You could use the option `descriptionKey` to manage this.
For example:

```java
class AuthMixin {
  @Option(descriptionKey = "auth.user")
  String user;

  @Option(descriptionKey = "auth.password")
  String password;
}

class LimitsMixin {
  @Option(descriptionKey = "limits.maxRam")
  int maxRam;

  @Option(descriptionKey = "limits.maxCPU")
  int maxCPU;
}
```

I believe the current mechanisms are sufficient and can even provide the separation and expressiveness you are looking for in most cases.
So, apologies, but I won't be developing this proposal. 🙏
