### ISSUE TITLE
Git Bash weird characters with PicoCLI

### ISSUE THREAD

**Issue by MyNameIsAres** [remkop/picocli#1379]
**The problem**
When I run a command through Git Bash, and try to get the -help or exit message, I get a bunch of odd symbols on my screen. This also happens when errors occur.

This seems to be an isolated issue to commands I developed with PicoCLI. I've googled around and found multiple solutions to change the TERM to _cygwin_ or _xterm-256color_. Unfortunately, that didn't work.

**Reproduce issue**
I run a command with the help property or an error occurs, because of a missing parameter, option, etc.

**Screenshot**
![weridbash](https://user-images.githubusercontent.com/32432637/120889910-c5280a00-c5ff-11eb-8da6-afc884e27266.png)

**Comment by remkop** [comment]
HI @MyNameIsAres, thank you for raising this.
Picocli emits ANSI escape codes to produce colored output when its [heuristics](https://picocli.info/#_heuristics_for_enabling_ansi) conclude that it is safe to do so.

Can you run your command in Git Bash with the `--help` option, and with system property `-Dpicocli.trace=DEBUG`, and post the output in a comment here? That will give me some details about your system that may help investigate the issue.

**Comment by MyNameIsAres** [comment]
Hi remkop, thanks for your reply.

Thanks to your reference to the documentation about ANSI escape codes, I was able to learn a lot about this part of PicoCLI. I didn't know about that part yet.

I've just come to the realisation that Git Bash actually works fine. It's the C:\Program Files\Git\bin\bash.exe that's having the ANSI problem. 

I wasn't able to get the system property you requested in your comment. Can you clarify how I'm supposed to get it? I couldn't find a reference to it in the documentation or PicoCLI code; and System.getProperty() didn't find it either.

Either way, this probably no longer a PicoCLI specific issue as the fault seems to be with bash.exe's lack of ANSI color support.
I'll have to find a way to work around this.

**Comment by remkop** [comment]
> I wasn't able to get the system property you requested in your comment. Can you clarify how I'm supposed to get it?

When you run your command, add the `-Dpicocli.trace=DEBUG` system property, something like this:

```
java -Dpicocli.trace=DEBUG -cp myjar.jar com.mypackage.MyClass --help
```

> Is there a way to disable ANSI commands for all commands?

One idea is to set system property `picocli.ansi` to `false` in your main method before calling the picocli `CommandLine` class.

**Comment by MyNameIsAres** [comment]
Hi Remkop,

The system property -Dpicoli.trace=DEBUG is not providing any feedback. I also used your example as a reference.
However, your suggestion to disable ANSI entirely has worked successfully.

Thank you so much for your help!

Have a good weekend,

Ares
