### ISSUE TITLE
Support command initialization methods in the picocli lifecycle

### ISSUE THREAD

**Issue by cbeams** [remkop/picocli#1385]
Often several subcommands will need to wire up the same dependency based on common option values passed to a parent command, as is seen in the following example:

```java
@Command(name = "top", subcommands = { SubCommand.class })
public class TopCommand {

    @Option(names = "--host")
    private String host;

    @Option(names = "--port")
    private int port;

    @Command(name = "sub")
    static class SubCommand {
        @ParentCommand
        TopCommand top;

        @Command(name = "create")
        public void create() {
            new MyClient(top.host, top.port).create());
        }

        @Command(name = "read")
        public void read() {
            new MyClient(top.host, top.port).read());
        }

        @Command(name = "update")
        public void update() {
            new MyClient(top.host, top.port).update());
        }

        @Command(name = "delete")
        public void delete() {
            new MyClient(top.host, top.port).delete());
        }
    }
}
```

Notice how a `new MyClient(host, port)` must be created in each of the `create`, `read`, `update` and `delete` command methods.

A convenience method such as

```java
public void myClient() {
    return new MyClient(top.host, top.port);
}
```

could be declared in the `SubCommand` class, and called from the CRUD command methods in order to eliminate this duplication, but that assumes that a given command only ever calls the method once. If a command method needs to make multiple `MyClient` calls, then we must create a `SubCommand#myClient` field and conditionally initialize it, e.g.:

```java
@Command(name = "sub")
static class SubCommand {

    @ParentCommand
    TopCommand top;

    private MyClient myClient;

    private MyClient myClient() {
        if (myClient == null)
             myClient = new MyClient(top.host, top.port);
        return myClient;
    }

     // CRUD command methods follow ...
}
```

So it's starting to get pretty ugly and boilerplate-ish, especially if the application has many such sub and sub-subcommands.

Better would be to allow for an explicit init method to be called in the picocli lifecycle after all picocli-injected fields have been wired up, but before any command method execution has occurred, e.g.:

```java
@Command(name = "sub")
static class SubCommand {

    @ParentCommand
    TopCommand top;

    private MyClient myClient;

    @ComandLine.CommandInitializer
    private void init() {
        myClient = new MyClient(top.host, top.port); // where the 'top' field is guaranteed to have already been injected by picocli
    }

     // simplified, POJO-ish command methods follow, e.g.:

    @Command(name = "create")
    public void create() {
        myClient.create();
    }

    // ...
}
```

Alternatively, the `@Command` annotation could be enhanced to support an `initMethod` attribute, e.g.:

```java
@Command(name = "sub", initMethod="init")
static class SubCommand {

    private void init() {
        // ...
    }
}
```

And as another alternative, picocli could provide e.g. an `InitializableCommand` interface that guarantees the same semantics (shown here in conjunction with `Runnable` for extra clarity):

```java
@Command(name = "sub")
static class SubCommand implements Runnable, InitializableCommand {

    @Override // from InitializableCommand
    private void init() {
        // guaranteed to run after any picocli-injected fields have been initialized and before the run() method below is called
    }

    @Override // from Runnable
    private void run() {
        // guaranteed to run after the init() method above
    }

}
```

One advantage of the annotation-based approach would be that the annotated init method could accept any number of parameters injected by picocli, e.g. `@Option`s, the `@ParentCommand`, etc. Doing it this way would further cut down on boilerplate as it would avoid the need for fields in many cases.

Note that I am aware of picocli's existing `CommandLine#setExecutionStrategy` approach, as documented at https://picocli.info/#_initialization_before_execution, but upon experimenting with it, it appeared that the strategy only applied to the top-level command class, i.e. the one provided to `new CommandLine(...)`. If this approach can achieve what I'm looking for above, then I missed it.

Thanks for your consideration.

**Comment by remkop** [comment]
It is hard to know where to draw the line for some of these things, but it seems to me that the `myClient` convenience method that caches the MyClient object in a field is not bad. In terms of lines of code it is actually not that different from the proposed solution with the `@ComandLine.CommandInitializer`-annotated `init` method. And it is easy for anyone who reads the manual initialization code to understand what it does, without needing to go to the picocli documentation to find out about the exact timing of when `@CommandInitializer`-annotated methods are called. :-)

I would like to keep things simple in the library.
It is an interesting suggestion, and I may change my mind at some point 😉  but for now I am inclined to say no to this.

**Comment by cbeams** [comment]
Thanks for getting back, @remkop. It may be that my use case is relatively rare, and I understand the desire to keep picocli as pico as possible 😉 Should implementing something like this become a possibility in the future, I'd think that the interface-based approach described above would be the least magical for users and probably the simplest to implement.

**Comment by cbeams** [comment]
@cbeams wrote:
> Note that I am aware of picocli's existing `CommandLine#setExecutionStrategy` approach [... ] if this approach can achieve what I'm looking for above, then I missed it.

On a second look, it was possible to achieve what I wanted with the existing `IExecutionStrategy` hook:

```java
import picocli.CommandLine;
import picocli.CommandLine.ExecutionException;
import picocli.CommandLine.ParameterException;

public class InitializeAndRunLast implements CommandLine.IExecutionStrategy {

    @Override
    public int execute(CommandLine.ParseResult parseResult) throws ExecutionException, ParameterException {
        var topLevelCommand = parseResult.commandSpec().commandLine().getCommand();
        initialize(topLevelCommand);
        parseResult.subcommands().forEach(subcommandParseResult -> {
            var subcommand = subcommandParseResult.commandSpec().commandLine().getCommand();
            initialize(subcommand);
        });
        return new CommandLine.RunLast().execute(parseResult);
    }

    private void initialize(Object command) {
        if (command instanceof InitializableCommand)
            ((InitializableCommand) command).init();
    }
}
```

where `InitializableCommand` is defined as an interface

```java
public interface InitializableCommand {
    void init();
}
```

that any `@Command` class can implement, e.g.

```java
@Command(names="example")
public class ExampleCommand implements Runnable, InitializableCommand {
    @Override
    public void init() {
        // do any initialization logic prior to run() being called.
    }

    @Override
    public void run() {
        // ...
    }
}
```

And the `InitializeAndRunLast` execution strategy is configured against the `CommandLine` instance prior to execution as usual:

```java
public static void main(String... args) {
    new CommandLine(ExampleCommand.class)
                .setExecutionStrategy(new InitializeAndRunLast())
                .execute(args);
}
```

For concision the example command above does not declare any subcommands, but the `InitializeAndRunLast` implementation does support them. Each command and subcommand is initialized in the order declared on the command line and then the last command is executed.

This approach is working well for my needs, so I'll close the issue.

**Comment by remkop** [comment]
Nice! 👍
