### ISSUE TITLE
Default value for mutually exclusive groups

### ISSUE THREAD

**Issue by andre15silva** [remkop/picocli#1386]
Hi,

I'm trying to get a default value for a mutually exclusive group:

```java
@CommandLine.ArgGroup(exclusive = true, multiplicity = "0..1")
FormatOption formatOption;

static class FormatOption {
	public enum Format {
		CSV,
		JSON
	}

	@Option(names = {"--format"}, description = "Format of the output. Valid values: ${COMPLETION-CANDIDATES}", defaultValue = "CSV")
	Format format;

	@Option(names = {"--formatter"}, description = "Path to java file of a custom FlacocoExporter.")
	String customExporter;
}
```

Ideally, when calling with none of the options from this group specified, the `formatOption` would still be initialized with a default value.

Sorry if this is not the way to do it, or if there is a feature for this already, but I couldn't find a better way than parsing `formatOption` myself and check if it is `null`.

Thanks!

**Comment by remkop** [comment]
Have you tried initializing the field?
Something like this:

```java 
@CommandLine.ArgGroup(exclusive = true, multiplicity = "0..1")
FormatOption formatOption = new FormatOption(CSV);
```

You’ll need to add a constructor to `FormatOption`. 

This default value is overwritten when the end user specifies an option in the arg group.

**Comment by andre15silva** [comment]
Hi @remkop 

That is a good call. It indeed works, thanks!

Thanks for the awesome framework too :)
