### ISSUE TITLE
Capturing user entered options order

### ISSUE THREAD

**Issue by kasramp** [remkop/picocli#1392]
Hi,

Is it possible to capture options with the orders that a user has entered them in subcommands?

For example,

```java
@CommandLine.Command(name = "order-support", description = "Example")
public class OrderSupport implements Callable<Integer> {

   @CommandLine.Option(names = {"-l", "--list"}, defaultValue = "false")
   private boolean list;

   @CommandLine.Option(names = {"-u", "--usage"}, defaultValue = "false")
   private boolean usage;
```

Let say a user enters `$ order-support -u -l`. Is it possible to capture options in an orderly fashion? 
So in code I can find out `-u` option entered prior to `-l`.

The reason for it is I am trying to implement a search filter that a user can enter options in any order but depending on the options orders, effects of some options will be discarded or their precedence will be changed. For example, `-u -l` means `-u` option will be either discarded or `-u` will have lower precedence.

**Comment by remkop** [comment]
This may be possible by looking at the `ParseResult` class.

Using the annotations API, you can inject a `@Spec` in your command, from which you can get the `ParseResult`, see [this example](https://picocli.info/#_was_a_value_defaulted). 

The [ParseResult.matchedOptions](https://picocli.info/apidocs/picocli/CommandLine.ParseResult.html#matchedOptions--) method will return a list of matched options, in order they were matched on the command line.

**Comment by kasramp** [comment]
Thanks a lot. It works like a charm 🙏
