### ISSUE TITLE
How can I override the default value of an option in a Mixin?

### ISSUE THREAD

**Issue by szaluk** [remkop/picocli#1395]
Suppose I have a class defining common options like this:

```
public class CommonOptions {
    @CommandLine.Option(names = {"--firstOption"}, defaultValue = "10", description = "First Option", required = true)
    private int firstOption;

    public int getFirstOption() {
        return firstOption;
    }
}
```

In my command class I am including it like this:

```
@CommandLine.Mixin
private CommonOptions commonOptions;
```

For most of my commands I am fine with the default value of 10 for the firstOption option, but I have one command where I would like the default value to be 5.  Is there a way to override the default value in that one command using a MixIn like this?

Thanks,
Steve

**Comment by remkop** [comment]
Hmm that’s tricky. 
One idea is to use a variable in the default value:

`defaultValue = "${actualDefault}"`

And then have a resource bundle with different values for each command. Not sure if this will actually work though… 😅

```
#Resource bundle 

command1.actualDefault=10

command2.actualDefault=5
```

Again, this may not work, sorry. 
You may not be able to reuse the same mixin for the command with the different default value.

**Comment by szaluk** [comment]
No worries!  I had a feeling this would be a tough ask.  Thanks for looking into this!

BTW, I absolutely love picocli.  One of the best projects I have used
