### ISSUE TITLE
Use generic types in containers (e.g. List, Map)

### ISSUE THREAD

**Issue by mgorniew** [remkop/picocli#1396]
Hi,

I would like to be able to parse arguments which will map to list for generic types, e.g.
```java
    static final class GenericValue<T> {
        private final T value;
    }

    class App {
        @Parameters(arity = "0..*", converter = GenericValueConverter.class)
        List<GenericValue<?>> values;
    }
```
This is now not possible. Is this limitation introduced to ensure better type safety? I've modified code to support such use case, but my solution sacrifices types safety by removing information about generic types:

https://github.com/mgorniew/picocli/commit/6a6f7731fc09da420a5fee922d32314deb53734b

Is such solution acceptable or this approach was considered before and rejected?

Thanks
Michał

**Comment by remkop** [comment]
Hi @mgorniew, the logic in picocli for types only looks up to 2 levels: the first level is for containers like `List` or `Map`, and the second level is for the type itself (the type to which the input String values will be converted).

The logic for getting type information is in `CommandLine.Model.RuntimeTypeInfo.inferTypes` and `extractTypeParameters`.

It may be quite tricky to change picocli to handle generic types; picocli's type model currently models types in a `ITypeInfo` data structure that has a "type" and an auxiliary type; and the auxiliary type is used for the converter. For collections, the "type" is the collection and the aux type is the element type, for simple types, both the "type" and the aux type are the simple type. So this does not take into account situations where the aux type is some generic type `T` that should be ignored by the type converter...

**Comment by mgorniew** [comment]
Simple idea here is to cut any additional generics information from aux types. So in case from my example this means that `DciReward<?>` will just be treated as `DciReward`. Such change (as in [commit](https://github.com/mgorniew/picocli/commit/6a6f7731fc09da420a5fee922d32314deb53734b)) seems to be backward compatible - all tests (beside `ModelTypedMemberTest.testInferTypes` ofc) still passes. But this change moves burden of using correct converter on users - e.g. if you will register global convert for `DciReward` then it will be used for both `List<DciReward<Integer>> `and `List<DciReward<String>>`. So local converters (defined in `@Option` and `@Parameters`) would be preferred for such types.

**Comment by remkop** [comment]
That works for multi-value options like:

```
@Parameters(arity = "0..*", converter = GenericValueConverter.class)
 List<GenericValue<?>> values;
```

Would it also work for single-value options like:

```
@Parameters(converter = GenericValueConverter.class)
 GenericValue<?> value;
```

**Comment by mgorniew** [comment]
Did dig to much into code, but I've added tests (new [commit](https://github.com/mgorniew/picocli/commit/7b141eac8fcba4c73485bbec2c0df5dfed34bd48)) and it seems to work fine. Should I create PR? We could discuss details there.

**Comment by remkop** [comment]
Okay please create a PR. 

(Note I have very little time to work on picocli recently, you may need to be patient.)
