### ISSUE TITLE
Use picocli heuristic instead of jline2 one ?

### ISSUE THREAD

**Issue by sbernard31** [remkop/picocli#1397]
I'm using Jline2 (I can not using Jline3 for now because I need a java 7 compliant library)

I faced a classicissue as JLine seems to not be able to detect correctly if a terminal is ANSI compatible or not.
(see https://github.com/jline/jline2/issues/185)

I find a way to use Picocli heuristic instead of the not so good Jline2 one (see https://github.com/jline/jline2/issues/185#issuecomment-889119519)

I don't know if this should be added to the example in the [README](https://github.com/remkop/picocli/tree/master/picocli-shell-jline2#example) ?

**Comment by remkop** [comment]
Will you be able to provide a pull request for this?

**Comment by sbernard31** [comment]
I can give it a try. 

Should I just add it in the `main` example with a comment ? 
Or should I create a dedicated chapter (so so don't push it in the example) ?

**Comment by remkop** [comment]
The main example is fine. 

Please add a link to the JLine 2 ticket that you mentioned.
