### ISSUE TITLE
Behaviour doesn't match documentation for boolean Option arity

### ISSUE THREAD

**Issue by joca-bt** [remkop/picocli#1398]
https://picocli.info/apidocs/picocli/CommandLine.Option.html#arity-- says:

- By default, flags (boolean options) have arity zero
- By default picocli does not expect boolean options (also called "flags" or "switches") to have a parameter.

However specifying a parameter is not resulting in error by default:

```
@Command(name = "test")
public class Main implements Runnable {
    @Option(names = { "--option" })
    private boolean option;

    @Override
    public void run() {
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new Main()).execute(args);
        System.exit(exitCode);
    }
}
```

The error only appears when we explicitly add `arity = "0"` to the above `@Option` declaration:

`option '--option' (<option>) should be specified without 'true' parameter`

 which, by the documentation, should already be the default.

**Comment by remkop** [comment]
You are correct, the documentation is incorrect.
The arity for boolean options is actually `"0..1"` now.

Do you feel like contributing a pull request for this?

**Comment by joca-bt** [comment]
Revert the code behaviour or doc?

**Comment by remkop** [comment]
We’ll change the documentation. 
There’s no reason to break existing applications that depend on the current behaviour. :-)
