### ISSUE TITLE
Autocompletion for non-shell environments

### ISSUE THREAD

**Issue by soccermitchy** [remkop/picocli#1402]
So, I just want to start off and say I'm using `picocli` in an environment that isn't a shell (specifically, for parsing Minecraft commands on my own server). I have something written already to let us run commands using `picocli` and I'm trying to add autocompletion. I was thinking, at first, that this would be as simple as doing something like this, with the code in the loop (not written because I couldn't even get this to work) looking at the exception class's fields to generate suggestions:
```java
public List<String> getCompletionSuggestions(String[] args) {
    ArrayList<String> completions = new ArrayList<>();
    CommandLine cmd = new CommandLine(command);
    cmd.getCommandSpec().parser().collectErrors(true);
    ParseResult r = cmd.parseArgs(args);
    for (Exception ex : result.errors()) {
        ....
    }
    return completions;
}
```
However, the array returned from `result.errors()` was empty. Is there another way I can generate autocompletions given an argument array?
Here's the command and the command line I tested with:
```java
@Command(name = "spigottest", mixinStandardHelpOptions = true)
public class SpigotTestCommand extends SpigotParksCommand {
    @Parameters(description = "test parameter")
    String test;

    @Override
    public void runCommand(CommandSender sender) {
        sender.sendMessage("hello from spigot");
        sender.sendMessage("test parameter: " + test);
    }
}
```
Command: `/spigottest` <kbd>Tab</kbd>
My expected result would a List<String> like the following:
```java
{
    "<test>",
    "-h",
    "-v"
}
```

**Comment by remkop** [comment]
Please take a look at the `complete` method in the `AutoComplete` class. 
The `List<CharSequence> candidates` passed to that method will be filled with completion candidates.

**Comment by soccermitchy** [comment]
I got a simple working version working with this code:
```java
    public List<String> getCompletions(String[] args) {
        CommandSpec spec = new CommandLine(caller).getCommandSpec();
        int argIndex = args.length - 1;
        if (argIndex < 0) argIndex = 0;
        
        int positionInArg = args[argIndex].length() - 1;
        if (positionInArg < 0) positionInArg = 0;

        int cursor = 0;
        List<CharSequence> candidates = new ArrayList<>();
        AutoComplete.complete(spec, args, argIndex, positionInArg, cursor, candidates);
        
        ArrayList<String> completions = new ArrayList<>();
        for (CharSequence seq : candidates) {
            completions.add(seq.toString());
        }
        return completions;
    }
```
However, now whenever I type `--` and hit tab, it seems that it returns autocompletions without the first `-` (see attached video). Is there a way I can get the AutoComplete class to preserve the current contents of the argument that's being autocompleted and just append the suggestions to it? All I get that's useful from the Minecraft server itself on autocompletion is the arguments, and I have no way to tell if the last argument is what is being autocompleted or if the suggestions are for an additional argument.

https://user-images.githubusercontent.com/443155/127961907-cd80cf39-131d-49d3-9a7c-632176cfe52d.mp4

**Comment by remkop** [comment]
Thanks for the video. 
Strange, it looks as if pressing TAB takes the cursor back one space... I don't know what the Minecraft specs are for Autocompletion but it looks strange. 

The AutoComplete class will return the _remainder_, so if you type `--` it will return `help` and `version`, not `V` or `h`... 
You could try massaging the list of completion candidates and prepend the prefix that was already typed before returning the list.

**Comment by soccermitchy** [comment]
Do you have any suggestions for how to try and massage the completion
candidates list? I can't just prepend the prefix because I don't know if
the completions are being returned for a new argument or to finish an
existing one. If it's for a new argument, I don't want to prepend the
contents of the last argument in the array because then I'd end up with
completions like `/spigottest --help--version`, but to finish an existing
argument I could prepend the last argument contents find.

**Comment by soccermitchy** [comment]
After looking some more, Spigot is still passing the argument array with both hyphens. I'm wondering now if it's something about how I'm creating the values for argIndex/positionInArg (not counting cursor because that's only used as a return value it looks like)

**Comment by remkop** [comment]
The complete method could use better javadoc... :-(

Maybe this test helps explain: 
https://github.com/remkop/picocli/blob/master/src/test/java/picocli/AutoCompleteTest.java#L1073

**Comment by soccermitchy** [comment]
So, I figured out that with how Spigot/Minecraft does command completion, the way I have to do it is set `positionInArg` to 0 - it replaces the *entire* argument with whatever the completion function returns, not just the part after the cursor. I got around that by telling `picocli` that the `positionInArg` is 0 so it returns the full argument, then filtering the results after the fact to only things that start with the last argument.
So, here's the completion function I have, in case anyone else is doing something similar:
```java
    public List<String> getCompletions(String[] args) {
        CommandSpec spec = new CommandLine(caller).getCommandSpec();
        int argIndex = args.length - 1;
        if (argIndex < 0) argIndex = 0;
        List<CharSequence> candidates = new ArrayList<>();
        AutoComplete.complete(spec, args, argIndex, 0, 0, candidates);
        ArrayList<String> completions = new ArrayList<>();
        String lastArg = args[argIndex];
        for (CharSequence seq : candidates) {
            // Only suggest things that start with the last argument
            if (seq.toString().startsWith(lastArg))
                completions.add(seq.toString());
        }
        return completions;
    }
```

**Comment by remkop** [comment]
Nice! Glad you got it working!
