### ISSUE TITLE
Print help usage before spring boot application startup

### ISSUE THREAD

**Issue by bonlai** [remkop/picocli#1406]
Hi,

My spring boot application startup process take about 7 second to startup.
I need to wait 7 seconds for the help usage to be printed out.
However, it is not necessary for the help usage waiting for the spring boot stuffs to be initialized.

Is it possible to print the help usage and exit before spring boot application to startup?

Thanks.

**Comment by remkop** [comment]
One idea is to do parsing [in two phases](https://github.com/remkop/picocli/issues/1326#issuecomment-781078042):
* first only look for `--help` (and `--version`) and ignore all other options and positional parameters
* next, parse again, this time with the "real" application and all other options and positional parameters

Example

```java
@Command(name = "mycommand", mixinStandardHelpOptions = true, version = "mycommand 1.0",
         exitCodeOnUsageHelp = 3, exitCodeOnVersionHelp = 3,
         description = "...")
class Dummy {
  @Unmatched List<String> ignored;
}

@Command(name = "mycommand", mixinStandardHelpOptions = true, version = "mycommand 1.0",
         description = "...")
class ActualCommand implements Runnable {
  @Option(names = "-x", description = "some actual option..."
  int x;

  public static void main(String[] args) {
    // phase 1: parse without initializing any Spring beans
    int exitCode = new CommandLine(new Dummy()).execute(args);
    if (exitCode == 3) {
      return; // the user requested help or version info 
    }
    // phase 2: initialize the Spring beans before parsing
    System.exit(SpringApplication.exit(SpringApplication.run(ActualCommand.class, args)));
  }
}
```

**Comment by bonlai** [comment]
Solved my problem. Many thanks!
