### ISSUE TITLE
Using same option in different ArgGroup

### ISSUE THREAD

**Issue by sbernard31** [remkop/picocli#1412]
I have a command line with some complex combination of options.
I try to simplify it to explain my usecase but this will maybe look not so complex and so you could maybe not get the issue :grimacing: 

I try anyway :crossed_fingers:.

Until now, I used abstract example but I will try to use something more soon to real world case. 
My command can be launched either using publickey + privatekey or x509 certificate + privateKey.
The clearer way to express this to the user for me would be a synopsis like this :
```
[-pubk=<pubk> -prik=<prik>] | [-cert=<cert> -prik=<prik>] 
// which can be clearly read  as "use Public Key Mode OR Certificate Mode"
```
and a help usage like this : 
```
X509 Options
------------------

By default  use non secure connection.
To use CoAP over DTLS with X509 certificate, -cert -prik  options 
should be used together.

      -cert, --x509-certificate=<cert>
               The path to your certificate.
               The certificate should be in X509v3 format (DER or PEM encoding).
      -prik, --private-key=<prik>
               The path to your server private key file
               The private key should be in PKCS#8 format (DER encoding).
  
RPK Options
-----------------

By default use non secure connection.
To use CoAP over DTLS with Raw Public Key, -pubk -prik options should 
be used together.

      -pubk, --public-key=<pubk>
               The path to your public key file.
               The public Key should be in SubjectPublicKeyInfo format (DER
                 encoding).
      -prik, --private-key=<prik>
               The path to your private key file
               The private key should be in PKCS#8 format (DER encoding).

```
Even if `-prik` is duplicated this sounds to be the clearer way to me to present this to the user.  (because the user only read RPK or X509 section and just focus on this)

-------------------------------------------

Picocli does not allow to do that. 
You need to do something like : `[-prik=<prik> [[-pubk=<pubk>] | [-cert=<cert>]]`  // less clear to read with my semantic
It also make the code more complex adding more ArgGroup level (not so visible here but in my case with more options and logic this is actually more complex)
And also got a help usage which is less clear to me : 
```
X509 Options
-------------------

By default Leshan use non secure connection.
To use CoAP over DTLS with X509 certificate, -cert -prik  options 
should be used together.

      -cert, --client-certificate=<ccert>
                             The path to your  certificate file.
                             The certificate should be in X509v3 format (DER
                               encoding).
RPK Options
----------------------

By default Leshan use non secure connection.
To use CoAP over DTLS with Raw Public Key, -pubk -prik options should 
be used together.

      -pubk, --public-key=<cpubk>
                             The path to your client public key file.
                             The public Key should be in SubjectPublicKeyInfo
                               format (DER encoding).

 -prik must be used with RPK or X509

      -prik, --private-key=<prik>
                             The path to your private key file
                             The private key should be in PKCS#8 format (DER
                               encoding).

```

-------------------------------
One workaround I find is to create 2 different option for private key but this is a bit painful at usage and it's also a bit strange because those 2 options have really the same meaning. 

So this looks like : 
```
X509 Options
------------------

By default  use non secure connection.
To use CoAP over DTLS with X509 certificate, -cert -prik  options 
should be used together.

      -xcert, --x509-certificate=<cert>
               The path to your certificate.
               The certificate should be in X509v3 format (DER or PEM encoding).
      -xprik, --x509-private-key=<prik>
               The path to your server private key file
               The private key should be in PKCS#8 format (DER encoding).
  
RPK Options
-----------------

By default use non secure connection.
To use CoAP over DTLS with Raw Public Key, -pubk -prik options should 
be used together.

      -rpubk, --rpk-public-key=<pubk>
               The path to your public key file.
               The public Key should be in SubjectPublicKeyInfo format (DER
                 encoding).
      -rprik, --rpk--private-key=<prik>
               The path to your private key file
               The private key should be in PKCS#8 format (DER encoding).

```

I don't know if you have any idea about how to solve this with current version of picocli or if you can imagine a new API which could solve this ? 
This is mainly a help presentation issue.
Maybe custom synopsis from #1411 could help a little. 
But for having same option visible in 2 different ArgGroup help section I don't know. 

(My fear is that you will maybe not feel there is a real issue here :fearful:)

(Get relief, I haven't more feedback in stock for now :grin:)

**Comment by remkop** [comment]
I understand the issue,  but the only solution now is to use two differently named options for private key.
One of the limitations of argument groups is that the same option can only appear in one group.

**Comment by remkop** [comment]
Closing this issue: to support this will likely require an extensive rewrite of the parser, and I don't envision myself doing this in the near future.
