### ISSUE TITLE
Applying Command.showDefaultValue attribute to boolean options

### ISSUE THREAD

**Issue by ermyas** [remkop/picocli#1414]
Hi,
Thanks for creating this nice framework!

Currently, a Command's `showDefaultValues` attribute does not apply to boolean options. If I am not mistaken, this requires setting the `showDefaultValues` attribute for each boolean option individually so that they can be displayed in the usage help message. For commands with a few boolean options, it could get slightly repetitive and potentially out-of-sync with the general preference expressed at the command level. I was wondering what the rationale was for not applying the `Command.showDefaultValues` to all options? thanks!

**Comment by remkop** [comment]
I don't remember for sure, but I guess that I thought it looked overly noisy, especially since the default is "false" almost all of the time.

For the cases where the default is "true", I recommend using the [`${DEFAULT-VALUE}` variable](https://picocli.info/#_default_value_variable) in the description.

**Comment by ermyas** [comment]
I see. In the case of the project that I am contributing to, there are a number of boolean options some of which represent behavior that is enabled by default and thus are true by default, while others are not. Hence, communicating the defaults of all options to the user is a requirement. It would have been ideal to control the visibility of all defaults at a command level, but for now, I will either set the`showDefaultValue` attributes or embed them in the description as you suggested. Thanks again
