### ISSUE TITLE
Positional Parameters autocompletion vs Sub-Commands

### ISSUE THREAD

**Issue by shannonbay** [remkop/picocli#1416]
Hi Remko,

I am enjoying picocli very much.  It is quite fast and simple to work with.

I had a few issues with positional parameters, which are already documented.

My workaround, which you may find interesting, was to programmatically generate sub-commands instead.
This is working great for autocompletion and so on.  

Perhaps you could internally remodel positional parameters as a special case of sub-commands.

```
            CommandLine cmd = new CommandLine(commands);

            CommandLine regionCommandLine = new CommandLine(new RegionQueryCommand());

            for(String region: RegionQueryCommand.Regions.regions()) {
               regionCommandLine.addSubcommand(region,
                       new RegionSubCommand(region));
            }

            cmd.addSubcommand("region", regionCommandLine);
```

I used the @Parent annotation on RegionSubCommand the to pass the "parameter" to the RegionQueryCommand, then invoke the parent's run().

Thanks again for the great project!

**Comment by remkop** [comment]
I am not sure that I want to bring this idea into the library, but it may still be interesting for others. 

If you were to write an article about this idea, I can link to it from the picocli documentation. Does that sound interesting to you?

**Comment by remkop** [comment]
@shannonbay Thanks again for raising this.
