### ISSUE TITLE
Un deprecate the help attribute - to provide support for multiple help option

### ISSUE THREAD

**Issue by kaushalkumar** [remkop/picocli#1422]
Hi - We have a scenario, where we would like to provide multiple option for help to our user. Actually, our command has a number of parameters (option + parameter). A good number of these parameters have default value or are read from a separate file. Since the parameters with default values are not very prime for our users to see, so we made those option hidden and introduced an option of "-H, --help-all-args" whose purpose is to unhide the parameters and display entire help.

This was working fine till we did not have any required option/parameter. The moment we added a command with required option/parameter, the command failed in validating required data check.

I tried to use preprocessor API (IParameterPreprocessor) to by pass the validation, but it did not work, as we have subcommands and the preprocessor API exits at top level command.

Can you please provide your input on this. Whether this is achievable in current version, if so, what shall be done to make it work. What we need to do is to unhide the options and invoke usage, if -H is passed as an argument (without any validation).

By the way, when we tried to put usageHelp=true on this new option, then we got a warning stating that multiple help option is configured.

Thanks

**Comment by remkop** [comment]
Please try adding `help = true` to the `-H` option, instead of `usageHelp = true`.

**Comment by kaushalkumar** [comment]
This works. Wonderful... thanks @remkop . 
Only thing to worry about is the deprecated annotation on Option.help.  Do we have any alternate mechanism to a achieve this functionality, without using deprecated APIs.

**Comment by remkop** [comment]
I should take the deprecation off. 
Your use case is exactly why the `help` attribute is still useful. 

Let’s change the title of this ticket and make it about undeprecating the `help` attribute.

**Comment by kaushalkumar** [comment]
Undeprecating will help us. I have updated the title of this ticket. Thanks

**Comment by remkop** [comment]
I removed the deprecated annotation from the `@Option ``help` attribute and updated the javadoc.

This will be part of the next picocli release.
Thank you for raising this!
