### ISSUE TITLE
Mono CommandLine file decision

### ISSUE THREAD

**Issue by kakawait** [remkop/picocli#143]
Is there any reason why every pieces of code are inside a single class?

This is not so easy to read and contribute to project if you're new.

**Comment by remkop** [comment]
Thanks for asking the question instead of giving up and walking away! 

My aim was to allow small command line applications to include picocli as source, so they could be run from a single jar. A longer answer is [here](https://github.com/remkop/picocli/wiki/FAQ#what-s-the-big-deal-about-the-single-source-file). 

To be honest, I hadn't considered that people would like the project enough that they'd want to contribute. I hope you will still fork the project!

**Comment by moaxcp** [comment]
I definitely respect your decision but I'm not sure it is worth the complexity of having a single class. I was thinking that if I use your project I could use something like FatJar to create a single runnable jar. Or it could be used in a groovy script. Either way if it causes complexity in the development of your project then let me deal with figuring out how to make a single jar as a user.

**Comment by remkop** [comment]
Thanks for the feedback. I'll think about it. 

What areas were you thinking about improving?

**Comment by kakawait** [comment]
Hi I didn't see the FAQ wiki sorry... Anyway thank you for the explanations. When I've opened that issue is not because I wanted to contribute and I was blocked by that choice but I used to read source code (partially) of what I'm using (as ext lib). Is a that moment I saw the single class file architecture.

Anyway I respect your choice because I can't represent every user and usage since I'm always using dependency manager (maven) to include some external piece of code and not source directly.

That why I can't force you to split the source code into multiple files! It only depend on you if you think that splitting can be worth or not, maybe by allowing easier contribution thus more contributors (but is not sure that splitting will increase contribution too... No one can claim such things)

**Comment by remkop** [comment]
By the way, I recently learned that GitHub ranks projects with more forks higher in its search results, so you can help picocli just by forking it (if you want to).

**Comment by kakawait** [comment]
I think I can close the issue, thank for response

**Comment by NicolasMassart** [comment]
Yes we like this project and want to  contribute. I admit it would be easier not to have one file and who creates apps without at least maven or gradle now ?

**Comment by RobertZenz** [comment]
> I admit it would be easier not to have one file and who creates apps without at least maven or gradle now ?

A lot of people, actually.

**Comment by remkop** [comment]
I’m thinking of doing something in the build to split up the source file temporarily to work on individual classes and then put it back together before committing but haven’t been able to spend much time thinking about this.

**Comment by RobertZenz** [comment]
@remkop I was thinking the other way around, have the code in separate classes and provide a build artifact of a merged source file in addition to regular jars (with separate classes). The downside would be that it would mean that code examples *might* not be portable, depending on how the example is written...and that I don't think there is tool doing that.
