### ISSUE TITLE
content format when missing required option 

### ISSUE THREAD

**Issue by kunlk** [remkop/picocli#1443]
Hi,

This issue should be a question other than bug. Thank you for your help in advance !

The question is when one required option was missing, the usage out put doesn't display the command in one line. 

For example as below, I expect that "synctl export -baselineselector=<blSelector> -loadrule=<loadRule> -snapath=<snapshotPath>" could be displayed in one line but it's wrapped.

c:\shared\vvctl>synctl.bat export -baselineselector wp_zxm_proj1_Int_0.12.0 -snapath C:\myview1
Missing required option '-loadrule=<loadRule>'
export data
Usage: synctl export -baselineselector=<blSelector> -loadrule=<loadRule>
                     -snapath=<snapshotPath>
      -baselineselector=<blSelector>
                             baseline selector name
      -loadrule=<loadRule>   load rule
      -snapath=<snapshotPath>
                             snapshot path

**Comment by remkop** [comment]
Thanks, the screenshot helped!

By default the usage help width is 80 characters, but this is configurable: 

see https://picocli.info/#_usage_width

**Comment by kunlk** [comment]
yes, it works perfect, thank you !
