### ISSUE TITLE
Suppress empty lines if option description is empty

### ISSUE THREAD

**Issue by rsenden** [remkop/picocli#1445]
If the width of the option column is exceeded (20 characters by default), then picocli will insert a newline in order to display the option description in the description column. However, this results in an empty line being inserted for options that do not provide a description, for example:

```
...
      --url=<url>
      --proxy-url=<proxyUrl>

      --proxy-user=<proxyUser>

      --proxy-password
  -k, --insecure          Disable SSL checks
  -u, --user=<user>
  -p, --password[=<password>]

  -t, --token[=<token>]
```

What would be the easiest way to suppress these empty lines?

**Comment by remkop** [comment]
Hi @rsenden, is there any work or open questions remaining on this ticket?
