### ISSUE TITLE
Completion for positional arguments is not working under Windows

### ISSUE THREAD

**Issue by eqvis** [remkop/picocli#1448]
Hi,

I'm new to picocli and jline and perhaps I'm missing something. I'm using 

    implementation group: 'info.picocli', name: 'picocli-shell-jline3', version: '4.6.1'
    implementation group: 'org.jline', name: 'jline-terminal-jansi', version: '3.20.0'

Under Windows 10 calling java with the build jar-file (gradle) in the cmd.exe I cannot use TAB-completion for parameters (options are working only with "=" syntax). Pressing TAB results in nothing (no error, no completion).

This is my command:

```java
@CommandLine.Command(name = "test")
public class TestCmd implements Callable<Void> {
  /*enum Fruit {apple, banana, peach}
  @CommandLine.Parameters(paramLabel = "FRUIT", index = "0")
  Fruit fruit;*/

  static class MyFruitCandidates extends ArrayList<String> {
    MyFruitCandidates() { super(Arrays.asList("apple", "banana", "peach")); }
  }
  @CommandLine.Parameters(paramLabel = "FRUIT", index = "0", completionCandidates = MyFruitCandidates.class)
  String fruit;

  @CommandLine.Parameters(paramLabel = "AMOUNT", index = "1")
  int amount;

  @Override
  public Void call() {
    System.out.println(amount + " " + fruit + "(s)");
    return null;
  }
}
```
Note: I tried both: enum (comment) and internal class MyFruitCandidates, but no results

I'm also trying to get dynamic completion dependending on the command context and found answers in an other issue pointing to micronaut, but the links are death and it is groovy code. Can you suggest some java examples?

Thank you in advance,
Mayra

**Comment by remkop** [comment]
JLine does require the Jansi library to show colors and interact with the terminal; can you double-check that the Jansi jar is also in your runtime classpath?

Are you saying that pressing the TAB key does work for options when the option name is followed by the "=" character (so completion _does_ work in some cases but not in all cases)?

Another thing to try is to use an older minor version of JLine 3 and see if that makes a difference.

**Comment by eqvis** [comment]
Hi Remko,

thank you for your fast response. Well, the Jansi-jar is not in my runtime classpath, but I see colors and the completion works when I use options followed by "=" like: `--option=value`, yes, but it does not work when I use option-space-value: `--option value`, neither for positional arguments. I haven't tried an other minor version of JLine 3, but I hope I have time to try it today.

Best regards,
Mayra

**Comment by eqvis** [comment]
I tried some earlier versions, but got no different result. Next week I can try my example in on linux (I have some trouble with network configuration at home-office).

**Comment by eqvis** [comment]
Hi, it was my failure: I missed passing the "PicocliJLineCompleter" to the LineReader.
Thank you again.
Mayra

**Comment by remkop** [comment]
Hi @eqvis, glad you found the solution! 🎉 
Enjoy picocli! 😉

**Comment by eqvis** [comment]
For people having a similar problem, here is my solution:
```java
// https://github.com/jline/jline3/wiki/Completion#systemcompleter
List<String> cmdNames = picocliCommands.commandNames().stream().collect(Collectors.toList());
PicocliJLineCompleter pjCompleter = new PicocliJLineCompleter(cmd.getCommandSpec());

SystemCompleter systemCompleter = builtins.compileCompleters();
// systemCompleter.add(picocliCommands.compileCompleters()); // <--- Not needed, instead...
systemCompleter.add(cmdNames, pjCompleter);                 // <----- ...add PicocliJLineCompleter here
systemCompleter.compile();

LineReader reader = LineReaderBuilder.builder()
  .terminal(terminal)
  .completer(systemCompleter)
  .parser(parser)
[...]
```
