### ISSUE TITLE
Upgrade JLine

### ISSUE THREAD

**Issue by asashour** [remkop/picocli#1450]
It seems JLine has newer version (3.21.0) than the one mentioned [here](https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/README.md?plain=1#L60). 

I hope there is a delivery with the latest from both libraries, since there are still errors with `picocli-shell-jline3` 4.6.1 and `jline` 3.21.0

**Comment by remkop** [comment]
Can you be more specific? "there are still errors" does not tell me what the problem is, or how to reproduce it.

**Comment by remkop** [comment]
@asashour Is this still an issue? Can you provide more details about the issue and how to reproduce it?

**Comment by asashour** [comment]
I had a compilation error, but it seems with `4.6.2`, it is fine.

Thanks.
