### ISSUE TITLE
Multiple `@Option` for a single field

### ISSUE THREAD

**Issue by dmlloyd** [remkop/picocli#1451]
Hopefully I didn't overlook a duplicate issue here.  My problem is basically that I want to have two different options that both apply to the same field.  The type of the field is a base type and the option types are subtypes of the base type.

Here's an example of what I'd like to be able to do:

```java
// this converter outputs an ArtifactClassPathEntry
@Option(names = "--boot-class-path-artifact", converter = ArtifactConverter.class)
// this converter outputs a FileClassPathEntry
@Option(names = "--boot-class-path-file", converter = FileConverter.class)
List<ClassPathEntry> bootPathEntries;
```

Right now I think I can accomplish this by doing a dance with argument groups, something like this:

```java
@ArgGroup(exclusive = true)
static class BCPHolder {
    ArtifactClassPathEntry artifact;
    FileClassPathEntry file;
}
```

And then make a list of those and *then* traverse the list checking to see which thing is non-`null` and flatten that back into the list that I want.  And repeat the process for each kind of class path option I want.

But I'd really prefer to just have the one list, and let more than one option map to that list using a repeating annotation, and then specify a separate converter for each one, if that is at all architecturally possible.

Thanks!

**Comment by remkop** [comment]
Have you tried using an [annotated method](https://picocli.info/#option-parameters-methods) for one (or both) of the options?

Of course, you would have to make sure that the list can contain both ArtifactClassPathEntry and FileClassPathEntry type elements.

```java
List<ClassPathEntry> entries = new List<?>;

// this converter outputs an ArtifactClassPathEntry
@Option(names = "--boot-class-path-artifact", converter = ArtifactConverter.class)
void addBootArtifact(ArtifactClassPathEntry e) {
    entries.add(e);
}

// this converter outputs a FileClassPathEntry
@Option(names = "--class-path-file", converter = FileConverter.class)
void addArtifact(FileClassPathEntry e) {
    entries.add(e);
}
```

**Comment by dmlloyd** [comment]
Ah okay, yeah I think that works as a workaround. It's still a little bit clunky in comparison to multiple options per field, but it gets me past my problem at any rate. Thanks.

**Comment by remkop** [comment]
Great, glad to hear that works for you.
Let me close this ticket for now, don't hesitate to let me know if more questions come up.
Enjoy picocli! :-)
