### ISSUE TITLE
Can not execute interpreted command

### ISSUE THREAD

**Issue by StephanStofer** [remkop/picocli#1453]
We are revamping an existing app with picocli and jline3. Within the old program, instructions can be saved as a standalone txt file. I have implemented an interpreter which parses these instructions into picocli commands. So far so good.
After parsing, I want to execute the interpreted command internally. Unfortunately, the command is not recognized correctly, although this command is suggested by picocli. If I copy-paste the command and execute it again, it works as expected.

```console
app> load -f=pathToFile\\instructions.txt
Interpreted command: base -p=1935.387 -p=1196.751 -o=1234 -q=60.54468
Unmatched argument at index 0: 'base -p=1935.387 -p=1196.751 -o=1234 -q=60.54468'
Did you mean: base?
...
app> base -p=1935.387 -p=1196.751 -o=1234 -q=60.54468
Successfully send command.
app>
```

The `load` command is a subcommand of an unnamed, or empty (`""`) parent command. I inject the `CommandSpec` into `load` and execute the parsed command with `spec.commandLine().getParent().execute(interpretedCommand)`.

Do you have any idea what I missed?

**Comment by remkop** [comment]
You should pass the interpreted command to the `execute` (or `parseArgs`) method as a `String[]` array, not as a single `String` with spaces.

The error shows that a single string `'base -p=1935.387 -p=1196.751 -o=1234 -q=60.54468'` is passed to picocli, instead of an array.

**Comment by StephanStofer** [comment]
How true.. Thanks for fast reply and your help!
