### ISSUE TITLE
Dynamic completion candidates using spec doesn't work as expected

### ISSUE THREAD

**Issue by eqvis** [remkop/picocli#1454]
Hi,

I'm playing around with picocli and jline to see if our requirements could be accomplished with this framework (we were using aesh until now, but this project seems more or less unmantained). 

Our shell-application helps the user to interact with more or less a database on a server. A lot of commands are similar to choose a branch (name-space) and the a concrete leaf of this branch. Both parameters are mandatory and the chosen branch determines the completion for the leaves.

This is my code (I’m using options, because the completion for positional arguments is not working for me, see #1448):

```java

@Command(name = "test", description = "my cmd @|magenta test|@ cmd", mixinStandardHelpOptions=true)
public class Test2Cmd implements Callable<Void> {

  enum Branch { A, B, C };

  private static CommandSpec commandSpec;

  @Option(names="--leaf", completionCandidates= LeafCandidates.class)
  String leaf;

  // Default value and initialized "branch" <= NullPointer in LeafCandidates iterator-function
  @Option(names="--branch", defaultValue = "A")
  Branch branch = Branch.A;

  @Spec
  void setCmdSpec(CommandSpec cmdSpec) {
    commandSpec = cmdSpec;
    LeafCandidates.initArgs(this);
  }

  @Override
  public Void call() {
    System.out.println(branch + " / " + leaf);
    return null;
  }

  static class LeafCandidates implements Iterable<String> {
    Test2Cmd mycmd;

    static void initArgs(Test2Cmd command){
      command.commandSpec.options().stream().forEach(optSpec -> init(optSpec.completionCandidates(), command));
      command.commandSpec.positionalParameters().stream().forEach(paramSpec -> init(paramSpec.completionCandidates(), command));
    }

    private static void init(Iterable<String> candidates, Test2Cmd command) {
      if (candidates instanceof LeafCandidates) {
        ((LeafCandidates) candidates).mycmd = command;
      }
    }

    @Override
    public Iterator<String> iterator() {
      if (mycmd == null) {
        return Collections.emptyIterator();
      }
      // Dummy results to see if the branch-option was set:
      return Arrays.asList("foo", mycmd.branch.name()).iterator();
    }
  }
}
```

I used the AbstractCreateCommand.groovy from Micronaut as reference:
https://github.com/micronaut-projects/micronaut-core/blob/107aae18ce07a2255cce815272f7c13c38c574ba/cli/src/main/groovy/io/micronaut/cli/profile/commands/AbstractCreateCommand.groovy

The problem is: I always get the completion for the last time I used the command, not as expected the completion for the current command input:

```shell
caiman$ test --branch=B --leaf=foo
B / foo
caiman$ test --branch=A --leaf=
B     foo
```

What am I doing wrong?

I’m using gradle and shadowJar ("com.github.johnrengelman.shadow" version "6.1.0") under Windows 10 with cmd.exe:

* 'info.picocli', name: 'picocli-shell-jline3', version: '4.6.1'
* 'org.jline', name: 'jline-terminal-jansi', version: '3.21.0'

Thankful for your advice.
Mayra

**Comment by eqvis** [comment]
Okay, it worked this way now:

```java
@Command(name = "test")
public class Test3Cmd implements Callable {

  @Parameters(completionCandidates = MyAbcCandidates.class)
  List<String> args;

  public Test3Cmd() {
    MyAbcCandidates.cmd = this;
  }

  @Override
  public Object call() {
    return ExitCodes.SUCCESS.code();
  }

  // See also: https://github.com/remkop/picocli/issues/837
  static class MyAbcCandidates implements Iterable<String> {
    static Test3Cmd cmd;

    @Override
    public Iterator<String> iterator() {
      if (cmd == null){
        return Arrays.asList("oh", "no").iterator();
      } else if (cmd.args == null || cmd.args.size() == 1){
        return Arrays.asList("one", "eins").iterator();
      } else {
        return Arrays.asList("more", "mehr").iterator();
      }
    }
  }
}
```

**Comment by remkop** [comment]
@eqvis Glad to hear you have a solution! 🎉  😅 

PS
You may want to upgrade to picocli 4.6.2, which was recently released, just to get the latest bugfixes etc.

Enjoy picocli!

**Comment by eqvis** [comment]
@remkop Yeah, thank you!
