### ISSUE TITLE
Scroll forward of the cli cause tailtips to collide with text

### ISSUE THREAD

**Issue by arphiox** [remkop/picocli#1456]
If I scroll down the cli and then input some commands the cli bugs and collides suggestion with the tailtip. It gets worse when I ask for an input with readline  and I scroll down than write something. The only solution i found to that is do disable scroll forword in the properties of cmd Terminal>Terminal Scrolling>Disable Scroll-Forward
Do you have any other solution for that? Or can I preset Disable Scroll-Forward when i launch the Jar?
Thanks. 
![Capture](https://user-images.githubusercontent.com/93778979/140526740-1871212a-1291-463a-b77c-6fbe9060262e.PNG)

**Comment by remkop** [comment]
@arphiox Thank you for raising this. It may be better to raise this issue in the JLine 3 project though.

**Comment by arphiox** [comment]
@remkop Thank you for your response, I will do it.

**Comment by remkop** [comment]
Closing this ticket.
