### ISSUE TITLE
Bad Autocomplete Output When Tab Completing a File With a Space

### ISSUE THREAD

**Issue by zpater345** [remkop/picocli#1458]
I am currently experiencing an issue with tab completion on an installed application running PicoCLI 4.6.1 and java 11 on Fedora 34.

Here is a snippet of the command line class for this project:
```
...
import picocli.CommandLine.*;
import picocli.CommandLine.Model.*;
...

@Command(name = "bcc")
public class BccCommands implements Runnable{

    @Spec
    CommandSpec spec;

    @Option(names = {"-s", "--snapshot"}, description = "Loads the specified snapshot file immediately upon launch.  Use full paths.")
    public File snapshotFile;

   ...
}

...
	_cmd = new BccCommands();
       	_cmdParser = new picocli.CommandLine(_cmd);
        _cmdParser.setCaseInsensitiveEnumValuesAllowed(true);
        _cmdParser.setOverwrittenOptionsAllowed(true);
...
```
I am currently generating the AutoComplete using Maven and picocli.AutoComplete to generate a bcc11_completion script.

With the generated completion script in `/etc/bash_completions.d/` I can  do the following:
```
bcc11 --snap<TAB><TAB>
```
and get
```
bcc11 --snapshot 
```
as expected

However when I try to add the file path and use tab completion to fill in the file path like this:
```
bcc11 --snapshot /home/zpater/Snapshots/2<TAB><TAB>
```
I get the following output:
![image](https://user-images.githubusercontent.com/63657169/141185418-7380b060-47aa-4780-8043-8b8e0c48dd33.png)

but I would expect something similar to this:
![image](https://user-images.githubusercontent.com/63657169/141185607-3b91170b-92c4-4719-af1d-016756c12329.png)

If I tab complete on a combination that doesn't find a file with a space in it, I get the expected result:
![image](https://user-images.githubusercontent.com/63657169/141185980-f9e732c5-94fe-4b4c-be21-665c8b933196.png)

There seems to be an issue with the completion script I generated and spaces. Is there anything I can do to resolve this issue?

**Comment by remkop** [comment]
Hi @zpater345, thank you for raising this!
Picocli 4.6.2 has just been released, can I ask you to check if the problem still exists in the latest version?

**Comment by zpater345** [comment]
I updated this morning and the behavior didn't change
