### ISSUE TITLE
Bash complains of a missing compopt command

### ISSUE THREAD

**Issue by aalmiray** [remkop/picocli#1464]
I've got the following output every time I press <tab> after generating the completion script using the default AutoComplete subcommand from PicoCLI 4.6.2:

```
-bash: compopt: command not found
```

```sh
$ echo $BASH_VERSION
3.2.57(1)-release

$uname -a
Darwin aalmiray2.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```

Apparently `compopt` is an alias for `complete` that's added only if $ZSH_VERSION is set, however the functions applied for Bash will still call that alias.

**Comment by remkop** [comment]
Ok, interesting. Apparently the shell builtin `compopt` is not available on the outdated bash
version 3.2.57 that ships with Mac OS.

I found a nice suggestion [here](https://git.iitd.ac.in/cs1140221/docker/commit/9d8f9943e99b87aa637921bbf582a767cbab6cf1) to replace `compopt +o default` with this:

```bash
type compopt &>/dev/null && compopt +o default
```

I will fix that in the next release of picocli.

Meanwhile, you can ask your users to run the following command (or make it part of the installation):

```bash
sed -i 's/compopt +o default/type compopt &>/dev/null && compopt +o default/g' path/to/completion_script
```

Would that work?

**Comment by remkop** [comment]
I committed the fix described above.
If you have any feedback that would be great. ;-)
