### ISSUE TITLE
Root command heading overrides subcommand

### ISSUE THREAD

**Issue by aalmiray** [remkop/picocli#1465]
I noticed that PicoCLI 4.6.1 and 4.6.2 will output the root command heading (at least `usage.header.0 `) as the given text for every subcommand when displaying the root's help. I had to manually reset `usage.headerHeading` to empty for every subcommand.

For example, just adding `AutoComplete.GenerateCompletion.class` as a subcommand on JReleaser's root command yields the following

```
$ jreleaser -h
JReleaser is a release automation tool for Java projects.
Its goal is to simplify creating releases and publishing
artifacts to multiple package managers while providing
customizable options.

Usage: jreleaser [-hV] [-D=<key=value>]... [COMMAND]

Options:
  -D=<key=value>    Sets a System property. Repeatable.
  -h, --help        Show this help message and exit.
  -V, --version     Print version information and exit.

Commands:
  init                 Create a jreleaser config file.
  config               Display current configuration.
  template             Generate a packager/announcer template.
  assemble             Assemble distributions.
  changelog            Calculate the changelog.
  checksum             Calculate checksums.
  sign                 Sign release artifacts.
  upload               Upload all artifacts.
  release              Create or update a release.
  prepare              Prepare all distributions.
  package              Package all distributions.
  publish              Publish all distributions.
  announce             Announce a release.
  full-release         Perform a full release.
  generate-completion  Its goal is to simplify creating releases and publishing

Documentation found at https://jreleaser.org
```

Notice every other subcommand has a proper heading (because of the override) while the newly added subcommand displays the wrong text.

**Comment by remkop** [comment]
Just to make sure we are on the same page, we are talking about descriptions etc obtained from resource bundles, right?

I think when I designed it, that the idea was that subcommands would sort of "inherit" values from the root command (without any prefix), so that they would not have to repeat the same value for each command in the resource bundles. They would only need to specify where things are different. This would make it easy to have, for example, a footer in the usage help message that is shared for all commands.

A possible solution for your use case (I haven't tried this) is to prefix the resource bundle entry with the command name.
So, instead of having this:

```
# shared between all commands
usage.header.0=Its goal is to simplify creating releases and publishing
```

Can you try this instead?

```
# ensure that this header line is specific only to the root command (named `jreleaser`)
jreleaser.usage.header.0=Its goal is to simplify creating releases and publishing
```

**Comment by aalmiray** [comment]
Yup, it's related to loading descriptions from resources. and yes, prefixing the headers with the root command works. Thanks!

**Comment by remkop** [comment]
Great, glad to hear that!

**Comment by aalmiray** [comment]
Might be worth enabling Discussions on this repo to allow questions like these and keep issues for bug/features 😏 
An issues template can be used to redirect users to the discussions page.

**Comment by remkop** [comment]
Hey interesting! 
I was not aware of this feature. I may use this and retire the picocli Google group to consolidate things.
Thanks for pointing this out!

**Comment by rsenden** [comment]
@remkop @aalmiray For reference, the solution provided above doesn't work if `scope = ScopeType.INHERIT` is declared on the top-level command; sub-commands will inherit the usage header and description from the top-level command even if the resource bundle keys are prefixed with the top-level command name, i.e. `toplevel.usage.description.0 = Some description`.

As we have several command attributes that we'd like to have on all commands, I have implemented a work-around to avoid having to specify `ScopeType.INHERIT` on the top-level command. This work-around is based on the fact that all our command implementations extend from a common base class, moving all 'global' command attributes to a mixin declared in this common base class:

```java
public class AbstractMyAppCommand {
    @Mixin private StandardCommandConfiguration standardCommandConfiguration;
    
    // Other common functionality shared by all command implementations
    
    @Command(
            usageHelpAutoWidth = true,
            sortOptions = false, 
            showAtFileInUsageHelp = true,
            defaultValueProvider = MyDefaultValueProvider.class)
    public static final class StandardCommandConfiguration {}
}
```

```java
// Common command attributes defined on the mixin declared in our abstract
// base class are applied to this command.
@Command(name = "my-command")
public class SomeConcreteCommand extends AbstractMyAppCommand {
    ...
}
```

This approach seems to work fine, both with regards to not inheriting the usage header/description from the top-level command (if resource keys are prefixed with top-level command name), while still inheriting the command attributes (only verified with the `showAtFileInUsageHelp` attribute for now, need to check the other attributes but I assume these will work fine as well).

**Comment by remkop** [comment]
@rsenden Thanks for that information!

**Comment by rsenden** [comment]
@remkop Unfortunately, the alternative approach that I described above causes a significant performance degradation as shown in the screenshot below, and as such isn't really usable.

![image](https://github.com/remkop/picocli/assets/8635138/96334ed5-d255-48a5-a799-2522ce356a68)

Might be worth investigating why applying command attributes through a mixin mixed into all commands results in such a performance degradation, compared to inheriting those attributes, but for now I've implemented yet another alternative work-around.

This alternative approach depends on the fact that all direct sub-commands of our top-level command define their own resource bundle:
```
- rootCommand: scope=INHERIT, resourceBundle="common"
|--- module1Command: resourceBundle="module1"
|  |- module1Sub1Command: no resource bundle declared
|  |- module1Sub2Command: no resource bundle declared
|--- module2Command: resourceBundle="module2"
|--- ...
```

The `common` resource bundle defines `usage.*` properties to define default header and description for all commands. However, each of the module resource bundles override these properties with empty values. So, effectively, `usage.header` and `usage.description` in the common resource bundle are only applied to rootCommand, with all other commands using empty values as header and description default values.

I think the only unintended side effect is that the empty default header and description now result in an extra blank line in the usage output for commands that don't define their own header/description. Would be nice if we can somehow get rid of these extraneous empty lines, but for now I can live with this.
