### ISSUE TITLE
Existing LOGs are not getting printed in console

### ISSUE THREAD

**Issue by SubhadeepSen** [remkop/picocli#1470]
Console does not output the info from logger but it outputs the SYSO statement. Could someone please help this if I'm missing any configuration.

Let's say there are some dependent classes coming from different dependencies where standard logger is used. What should be done in my CLI application so that it prints those LOG statements on the console. 

Appreciate any help or suggestions :-) 

```java
public class Application {
	
	private static final Logger LOG = LoggerFactory.getLogger(Application.class);
	
	public static void main(String[] args) {
		LOG.info("Fom logger >> CLI <<<");         // does not output in console
		System.out.println("Fom SYSO >> CLI <<<");    // outputs in console
		CommandLine cli = new CommandLine(new RootCmd());
		int execute = cli.execute(args);
                System.exit(execute);
	}

}
```

**Comment by SubhadeepSen** [comment]
external logger configuration issue, thanks

**Comment by remkop** [comment]
@SubhadeepSen Glad to hear that you found a solution.
Enjoy picocli! :-)
