### ISSUE TITLE
Provide a programmatic way to configure Picocli's TraceLevel

### ISSUE THREAD

**Issue by ekinano** [remkop/picocli#1471]
The current pattern is to set the `picocli.trace` system property. It would be nice if there were a more programmatic way to do this, e.g. something like

```
cmdLine.setTraceLevel(OFF)
```

For context, we are currently using Picocli's parsing capabilities in an environment where a pattern like System.setProperty is heavily discouraged and requires a security exception.

**Comment by remkop** [comment]
Hi @ekinano, thanks for raising this. 

One could call `System.setProperty` in the main method before doing anything else to accomplish this programmatically, or am I missing something?

**Comment by ekinano** [comment]
Thanks for the quick reply @remkop. `System.setProperty` works, but it is a highly discouraged practice at my company to the point where you need a security exception to be able to use it.  While we can probably get that exception for our use-case, it seems better for us to avoid that conversation entirely if there can be another way of setting the trace level without using `System.setProperty`. It would be nice if that way would be through the Picocli objects directly like e.g. `CommandLine`. Hopefully the request makes more sense now.

(If you're curious, we have a server for processing CLI-like arguments. We are leveraging Picocli's annotations to specify our "command" classes and its parser to parse those subcommands from the request. We would like to turn off Picocli's tracing to avoid filling our logs).

**Comment by remkop** [comment]
@ekinano Thank you for the clarification. That makes sense.

Will you be able to provide a pull request for this?
