### ISSUE TITLE
Annotation Processing: options were not recognized by any processor

### ISSUE THREAD

**Issue by lorenzleutgeb** [remkop/picocli#1472]
With `-Averbose=true` I get

```
warning: The following options were not recognized by any processor: '[verbose]'
```

I suspect that this is because the option is not listed at

https://github.com/remkop/picocli/blob/5ee80a3ff1bc1d3ac0e326a6be8a1b8c06b9f50b/picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/processor/NativeImageConfigGeneratorProcessor.java#L20-L27

Could you please verify that, and consider adding the constant

https://github.com/remkop/picocli/blob/5ee80a3ff1bc1d3ac0e326a6be8a1b8c06b9f50b/picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/processor/AbstractGenerator.java#L12

Thanks.

**Comment by remkop** [comment]
HI @lorenzleutgeb thank you for raising this!
Will you be able to provide a pull request for this?

**Comment by lorenzleutgeb** [comment]
You probably know much more about annotation processors (and how their arguments are discovered by the compiler). If you think that my analysis is plausible, then I'd have a go, yes.

**Comment by remkop** [comment]
I think your analysis is correct. It would be great if you could provide a PR, ideally with a test, similarly to the testOption ones here: picocli-annotation-processing-tests/src/test/java/picocli/codegen/aot/graalvm/processor/NativeImageConfigGeneratorProcessorTest.java
:-)

**Comment by remkop** [comment]
Thank you again for raising this.
I pushed a fix to the master branch.

Interestingly/unfortunately, I was unable to reproduce the issue in the unit test.
Can you verify that the problem goes away when you build picocli from master?
