### ISSUE TITLE
Typo in error message from AbstractCommandSpecProcessor#extractTypedMember(Element, String)?

### ISSUE THREAD

**Issue by rgoldberg** [remkop/picocli#1476]
I think there's another typo in the error message from `AbstractCommandSpecProcessor#extractTypedMember(Element, String)`.

It currently outputs:

"Can only process %s annotations on fields, methods and method parameters, not on %s"

But the `element.getKind() == ElementKind.PARAMETER` check is commented, so I think the correct message should be:

"Can only process %s annotations on fields and methods, not on %s"

Or maybe the `element.getKind() == ElementKind.PARAMETER` should be uncommented…

As an aside, I also think the code should use a `switch` statement instead of chained `if`s.

I can make a PR, but just wanted to check first.

**Comment by remkop** [comment]
Thank you for raising this!
I'll take a look when I get to my PC.

**Comment by remkop** [comment]
I had a quick look, and it seems that `@Option`-annotated method parameters are handled in  `AbstractCommandSpecProcessor#buildOptionsAndPositionalsFromMethodParameters`.

I suspect that the `extractTypedMember` method is not called for annotated elements other than fields and methods.
There is a test for `@Option`-annotated method parameters: `picocli.annotation.processing.tests.AbstractCommandSpecProcessorTest#testCommandWithMixin`, and this test does not result in a compiler error.

I did not look in more detail, however.

I am going to leave this error message as it is for now; the error message itself is correct (for example, if a class is annotated with `@Option`, this error message would be shown, and it would be useful to have it state all valid places where the `@Option` annotation can be used).

**Comment by rgoldberg** [comment]
I got the error when I annotated a Kotlin primary constructor parameter with `@Parameters`:

```
error: Cannot only process @Parameters annotations on fields, methods and method parameters, not on PARAMETER
    java.lang.String software, @org.jetbrains.annotations.NotNull
```

It's saying that `@Parameters` can only be processed on a, b & method parameters, but not on `PARAMETER`. Since `PARAMETER` is a method parameter, the message is incorrect.

**Comment by remkop** [comment]
> I got the error when I annotated a Kotlin primary constructor parameter with `@Parameters`:

Oh I see, interesting. So this is related to #1195.

You could try uncommenting the `|| element.getKind() == ElementKind.PARAMETER) {` condition in `extractTypedMember`.

Also, (and this may not be important, but)  `buildOptionsAndPositionalsFromMethodParameters` has some extra logic for calculating position for `@Parameters` elements that do not have an explicit `index` set. The `extractTypedMember` does not have that logic. (But it may not be needed, not sure).  If it is possible to invoke  `buildOptionsAndPositionalsFromMethodParameters` for constructors, that may be good - but this is just a random thought, I have not looked at the implications of doing this.

**Comment by rgoldberg** [comment]
Yep, I saw this while investigating #1195.

I'm not trying to change this now to implement #1195.

The current error output must be incorrect, since it says that the annotation can be processed on method parameters, but then says but not on `PARAMETER`.  But `PARAMETER` is a method parameter.

Unless I've completely missed something…

**Comment by remkop** [comment]
Yes, good point.
I improved the error message to clarify that currently only parameters in `@Command`-annotated methods are supported.
