### ISSUE TITLE
Multiple threads

### ISSUE THREAD

**Issue by himanshumps** [remkop/picocli#1479]
I want to execute the command multiple times in parallel. How can that be achieved?

**Comment by remkop** [comment]
@himanshumps interesting! Can you share your use case? Why do you want to do this?

**Comment by himanshumps** [comment]
I am writing a multi threaded application and want to pass the command line parsed arguments. I can do it in run method but I want to see if I can prevent that.

**Comment by remkop** [comment]
The simplest way to accomplish this is to create a new `CommandLine` instance and a new instance of your top-level command object every time you are parsing command line arguments. 

Is this doable for your use case?

If you try to reuse objects across multiple threads you will get unpredictable results.

**Comment by remkop** [comment]
If you *do* have shared state that you must share between multiple threads, then I would use a design that wraps this shared state in a thread-safe "wrapper service". Then, create only one instance of this thread-safe wrapper service, and give this single shared instance to all of the threads.

For example:

```java
// Wrap your shared state in a thread-safe service.
// All access to the shared state should go through this singleton instance of the thread-safe service.
MyThreadSafeService sharedService = MyThreadSafeService.singletonInstance(); // or use DI to manage the singleton

// in every separate thread:
new CommandLine(new MyCommand(sharedService)).execute(args);

// Example command implementation
class MyCommand implements Runnable {
    @Option(names = "-x") String x;
    @Option(names = "-y") String y;

    final MyThreadSafeService sharedService;
    MyCommand(MyThreadSafeService sharedService) {this.sharedService = sharedService;}

    public void run() {
        // business logic in the command uses the wrapper service
        // to update the shared state in a thread-safe way
        sharedService.updateSharedState(x, y);

        // commands can also use the wrapper service to get data from the shared state in a thread-safe way
        Object snapshot = sharedService.getInfo();
        // ... so something
    }
}
```

This way, the parsing is done in parallel using separate memory for each thread, and these threads only act on the shared state via the thread-safe service, which has been designed for this purpose. That is, designed to provide thread-safe access to this shared state.

It remains important to create a new `CommandLine` instance and a new instance of your top-level command object (the `MyCommand` class in the example above), every time that a thread parses command line arguments.

**Comment by remkop** [comment]
@himanshumps Did this answer your question?

**Comment by himanshumps** [comment]
Thanks @remkop .. you have been very helpful.

**Comment by remkop** [comment]
@himanshumps Glad to hear that. Do you have follow-up questions, or can this be closed?

**Comment by remkop** [comment]
Closing this ticket. Don't hesitate to ask more questions.
