### ISSUE TITLE
ClearScreen removes the Status-Pane in JLine3

### ISSUE THREAD

**Issue by eqvis** [remkop/picocli#1507]
Hi Remko,

To fix this myself, I used:
```java
reader.callWidget(LineReader.CLEAR_SCREEN);
```
in a little command instead of your ClearScreen command, where reader is a static LineReader used in my main-while-readline-loop :-)

Getting the current LineReader-Object from the CommandLine would be cool, I'm using this static object to print messages, call other widgets (and make my own keyboard-shortcuts command!)

Best regards,
Mayra

**Comment by eqvis** [comment]
I'm very sorry, this does not work! ;-)

**Comment by eqvis** [comment]
I'm using this for now: `((LineReaderImpl)reader).clearScreen();`

**Comment by remkop** [comment]
Glad to hear that you found a solution!
