### ISSUE TITLE
inherted fields are not parsed 

### ISSUE THREAD

**Issue by nagkumar** [remkop/picocli#151]
If a command class inherits parent class. which has few private, protected or package or public files, these are not parsed.. it says 
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unmatched argument [-h]

I wish to put help and version part of every command, which can be put in AbstractCommand and each command can inherit the AbstractCommand  so that help handling code is not duplicated in each command.

In fact, it would be nice for picocli to handle -h and --help etc automatically with simple annotation variables.. i.e @Command can have one option to say auto support help etc

**Comment by remkop** [comment]
@nagkumar Thanks for the feedback! I'm still thinking about how to do automatic help. See #145 for discussion and thoughts so far. 

About inheritance, this should work if the fields in the parent class are annotated with `@Option` or `@Parameters`. If not, can you provide a failing test that demonstrates the issue?

**Comment by nagkumar** [comment]
Sorry, as you said, it is working.. Thanks, it was my mistake

**Comment by remkop** [comment]
Great, thanks for the confirmation.
