### ISSUE TITLE
ClassNotFoundException 'oracle.jdbc.OracleDriver' raised with picocli-groovy

### ISSUE THREAD

**Issue by grational** [remkop/picocli#1510]
Could you help me understanding why I obtain the following exception: 
```
Caught: groovy.lang.GroovyRuntimeException
groovy.lang.GroovyRuntimeException
        at picocli.groovy.PicocliBaseScript2.afterExecution(PicocliBaseScript2.java:188)
        at picocli.groovy.PicocliBaseScript2.run(PicocliBaseScript2.java:161)
Caused by: java.lang.ClassNotFoundException: 'oracle.jdbc.OracleDriver'
        at complete_task.call(complete_task.gy:60)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java
:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at picocli.groovy.PicocliBaseScript2.run(PicocliBaseScript2.java:160)
``` 
when I execute the minimal groovy script below?
```groovy
@Grab('info.picocli:picocli-groovy:4.6.2')
@GrabConfig(systemClassLoader=true)
@Command (
	name = 'complete_task',
	mixinStandardHelpOptions = true,
	version = '1.0',
	description = 'complete a jBPM task'
) @picocli.groovy.PicocliScript2
import static picocli.CommandLine.*
import groovy.transform.Field

@Grab('com.oracle.database.jdbc:ojdbc10:19.10.0.0')
@GrabConfig(systemClassLoader=true)
import groovy.sql.Sql

@ArgGroup(
	exclusive = false,
	multiplicity = "1"
) @Field Database db

class Database {
	@Option (
		names = ['--db-url'],
		paramLabel = 'jdbc url',
		description = "The jdbc encoded url of the database (ex. 'jdbc:hsqldb:mem:testDB')",
		required = true
	) String url
	@Option (
		names = ['--db-username'],
		paramLabel = 'username',
		description = "The username part of the db credentials",
		required = true
	) String username
	@Option (
		names = ['--db-password'],
		paramLabel = 'password',
		description = "The password part of the db credentials",
		required = true
	) String password
	@Option (
		names = ['--db-driver'],
		paramLabel = 'className',
		description = "The class name of the driver to use",
		required = true
	) String driver
}

def sql = Sql.newInstance(db.url, db.username, db.password, db.driver)
```

**Comment by remkop** [comment]
Sorry for the late response.

My guess would be that the `com.oracle.database.jdbc:ojdbc10:19.10.0.0` dependency does not contain the `oracle.jdbc.OracleDriver` class, and the groovy script needs to `@Grab` additional dependencies.

Since this has been a while (apologies), have you been able to resolve the issue?
(Not sure that the picocli library can do anything to help here though...)

**Comment by grational** [comment]
Thank you @remkop for your response.

Unfortunately that is one of the first thing I have checked.

You can do it yourself downloading the jar from [here](https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc10/19.10.0.0/ojdbc10-19.10.0.0.jar) and unpacking the archive.

The class is there. To me is a real mystery why it is not found. I think it could be related to the classloader or something related to it...

**Comment by remkop** [comment]
I see.
It may be worth going through Groovy's Grapes / @Grab related Jira tickets to see if someone else encountered something similar: https://issues.apache.org/jira/browse/GROOVY-4079?jql=project%20%3D%20GROOVY%20AND%20text%20~%20%22grab%22

And if not, raise a ticket for this with the Groovy project.

**Comment by remkop** [comment]
@grational This seems more like a Groovy issue than a picocli issue...
I am not sure there is any way that picocli can be enhanced to address this.
Have you had any luck interacting with the Groovy project?
