### ISSUE TITLE
defaultValue from environment variable with required=true

### ISSUE THREAD

**Issue by jexp** [remkop/picocli#1511]
Hi,

I'm trying to populate an option from an environment variable as default value.
Because the option is mandatory to set either via command line or env-variable I set required=true.

But even if the env-variable is set it complains about the missing parameter?

I didn't find anything on that in the docs or other issues. Version: 4.6.2

```
    @Option(names = "-p", description = "Password of the provided Neo4j user, or environment variable NEO4J_PASSWORD", required=true, defaultValue = "${env:NEO4J_PASSWORD}")
    String password;
````

Trying it out:

```
echo $NEO4j_PASSWORD            
test

jbang rdbms2neo4j.java Customers
Missing required option: '-p=<password>'
Usage: rdbms2neo4j [-a=URI] [-j=JDBC] -p=<password> [-u=<username>] <tables>...
      <tables>...   JDBC Tables
  -a=URI            URI to connect to (defaults to neo4j://localhost:7687) or
                      environment variable NEO4J_URL
  -j=JDBC           JDBC-URL to read from, or environment variable JDBC_URL
  -p=<password>     Password of the provided Neo4j user, or environment
                      variable NEO4J_PASSWORD
```

**Comment by remkop** [comment]
The program requires environment variable `NEO4J_PASSWORD` (all uppercase) to be set. 

Looking at your message, you have set `NEO4j_PASSWORD` (lowercase ’j’) instead. 

Can you try setting environment variable `NEO4J_PASSWORD` (all uppercase)?

**Comment by jexp** [comment]
Oh sorry, I'm soo stupid. You're right.
That's what you get for coding at 4am :)

Thanks a lot, enjoy your weekend.

**Comment by remkop** [comment]
Glad to hear that solved the issue. 
Enjoy picocli!
