### ISSUE TITLE
Extra/Duplicate dependency of jline-console in picocli-shell-jline3 (pom.xml/build.gradle)

### ISSUE THREAD

**Issue by kaushalkumar** [remkop/picocli#1516]
pom.xml/build.gradle of picocli-shell-jline3 defines a compile time dependency on jline and jline-console. The second dependency of jline-console is unwanted as jline contains all the required dependency including the classes of jline-console. Ref: https://github.com/jline/jline3#artifacts. The dependency of jline-console pulls other individual jars of jline in maven classpath. 
These additional dependency jars throws warning when we use proguard maven plugin to optimise the package. A snippet of the warning is "Note: duplicate definition of library class [org.jline.console.ArgDesc]".

Can we please remove the extra dependency from build.gradle.

**Comment by remkop** [comment]
@kaushalkumar Thank you for raising this!
Will you be able to provide a pull request for this?

**Comment by remkop** [comment]
I pushed a fix for this, and this will be included in the next release.
