### ISSUE TITLE
how to improve new CommandLine run time?

### ISSUE THREAD

**Issue by Howar-sz** [remkop/picocli#1523]
I use picocli(version: 4.6.2) to build my cmd cli tools. It has four commands under root. When I build it as jar and run it. I found my cli took more than 1 second in run time, `CommandLine rootCmd = new CommandLine(new AGWAdmin());` this line took more 1.2 second in my machine. How can I improve preformance in new CommandLine?

**Comment by remkop** [comment]
Hi @Howar-sz, thank you for raising this!

The best way to approach this is to use a profiler to find out where the program is actually spending time.
Some IDEs have profiling plugins or capabilities, and there are standalone ones.
I would be interested to hear your findings.

**Comment by remkop** [comment]
@Howar-sz how did your investigation go?
Did the profiler show that the startup time was spent in picocli initialization, or elsewhere in the application?

**Comment by remkop** [comment]
Hi @Howar-sz was that a public project? Can you give a link to it so I can try to reproduce it?

**Comment by Howar-sz** [comment]
Hi @remkop, thank you for your reply! And I apologize for my late reply~
It is a private project use to manage some daemon services and it need to start up in every command. I think the most cost was java cold starts. So, this issue can be close now.
Thanks again for your attention!

**Comment by remkop** [comment]
Thank you 🙏
