### ISSUE TITLE
Optional argument-groups not resetted between multiple command-executions

### ISSUE THREAD

**Issue by bbodnar** [remkop/picocli#1536]
Members (object-type) of command-objects representing optional argument-groups are not resetted between multiple command-executions in interactive applications. 
Once set, command-executions where none of that options were specified, get the value of the last specified options.
Unlike #1531, the annotations are applied here directly to the members, setter-methods aren't involved.

Reproducing:
- unpack the attached sample application and build it using `mvn clean install`
- execute `java -jar target/arggroup-not-resetted-1.0-SNAPSHOT.jar`
- enter `cmd`; the output is `null, opt3=0` (group opt1/opt2 unset)
- enter `cmd -opt1=33 -opt2=44 -opt3=55`; the output is `Args{opt1=33, opt2=44}, opt3=55`
- enter `cmd` (without options) again; the output is `Args{opt1=33, opt2=44}, opt3=0` (opt3 resetted correctly, the argument-group kept)
[arggroup-not-resetted.zip](https://github.com/remkop/picocli/files/7797023/arggroup-not-resetted.zip)

**Comment by remkop** [comment]
Thank you for the test code. I used it to create a unit test to help with the analysis.

The workaround is as follows:

* define a default value for the options in the argument group
* give the argument group declaration an initial value in the command where it is used

```java
static class Args {
    @Option(names = {"-opt1"}, defaultValue = "0") int opt1; // <--- define default value
    @Option(names = {"-opt2"}, defaultValue = "0") int opt2; // <--- define default value
}

@Command(name = "cmd")
 static class Cmd implements Runnable {
    @ArgGroup(exclusive = false) Args args = new Args(); // <--- give the group an initial value

    @Option(names = {"-opt3"}) int opt3;

    // ...
}
```

For more details, see: https://picocli.info/#_assigning_default_values_in_argument_groups

**Comment by remkop** [comment]
@bbodnar Can you verify if that resolves the issue?

**Comment by bbodnar** [comment]
The workaround is usable, thanks for that.

**Comment by remkop** [comment]
Great, thank you for the confirmation!
