### ISSUE TITLE
Error: "value" not unique - when matching name and alias for same object

### ISSUE THREAD

**Issue by StaffanArvidsson** [remkop/picocli#1537]
Found that having e.g. the `name` and `aliases` begin with the same letters result in strange bahaviour when it comes to allowing abbreviated commands. Say I have the following snippet out of the generated usage text;
```
COMMANDS
  chemical-files, chem-formats ...
```
and then running with `.. chem` will fail with the following stack trace (running `CommandLine.execute(String)`):
```
picocli.CommandLine$ParameterException: Error: 'chem' is not unique: it matches 'chemical-files', 'chem-formats'
	at picocli.CommandLine$AbbreviationMatcher.match(CommandLine.java:18426)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13306)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13122)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13395)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13310)
```
I guess that's because the code builds up a Map<String,Object> of each name/alias and the AbbreviationMatcher doesn't check that they reference the same objects?

**Comment by remkop** [comment]
Hi @StaffanArvidsson, thanks for raising this!

Unfortunately I cannot reproduce the issue. Please take a look at the [test I added](https://github.com/remkop/picocli/blob/02d2ab454fb1780113ba894877499b64940c13b6/src/test/java/picocli/Issue1537Ambiguous.java).
In my test, both the `execute` method and the `parseResult` method behave as I expect them to behave:
* The `execute` method does not throw an exception, and does not show a stack trace, but shows a user-friendly error message.
* The `parseArgs` method does throw an exception, but the stacktrace looks very different from the one in the question. This is the stack trace I am seeing:

```
picocli.CommandLine$UnmatchedArgumentException: Unmatched argument at index 0: 'chem'

	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13202)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13154)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13100)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13001)
	at picocli.CommandLine.parseArgs(CommandLine.java:1478)
	at picocli.Issue1537Ambiguous.testParseArgs(Issue1537Ambiguous.java:38)
```

Can you provide a way to reproduce the issue?

**Comment by NewbieOrange** [comment]
@StaffanArvidsson probably means following:

```java
int exitCode = new CommandLine(new MyCommand()).setAbbreviatedSubcommandsAllowed(true).execute("chem");
```

Which does give a user-friendly error message:
```
Error: 'chem' is not unique: it matches 'chemical-files', 'chem-formats'
Usage: <main class> [COMMAND]
Commands:
  chemical-files, chem-formats
```

I can create a pull request to get this fixed if needed.

**Comment by StaffanArvidsson** [comment]
Yes @NewbieOrange is correct, I had set `setAbbreviatedSubcommandsAllowed(boolean)`, perhaps I should have stated that explicitly more than the stack trace and given that `'chem'` doesn't match any of the names. So I guess it could be thought of like a feature request, but my assumption would be that given that the matches produced by the `AbbreviationMatcher` are unique for a single command object - that object should be selected and executed. Is there a situation where this is undesireble?

**Comment by remkop** [comment]
Thank you for your patience. I was finally able to reproduce the issue. 😅 

Yes, I agree that it would be nice improvement to not fail when there are multiple matching candidate names which all reference the same command object (so there is no real ambiguity).

@NewbieOrange if you can work on this, that would be great! 🙏
