### ISSUE TITLE
Case Insensivity of commands, options and parameters

### ISSUE THREAD

**Issue by nagkumar** [remkop/picocli#154]
It would be good support case in sensitivity of commands..(annotation attribute controlled, with ignoreCase as true)

@CommandLine.Command(name = 'Status')

this way CLI parser should recognize even status, sTatus etc..

**Comment by remkop** [comment]
Related to #9 and #14. I hadn't thought of also making commands case-insensitive in addition to options. 

Not sure if this should be an annotation: note that other attributes for controlling how picocli should do parsing have getter and setter methods on CommandLine. For example, `setOverwrittenOptionsAllowed` and `setUnmatchedArgumentsAllowed`. So it would be more consistent to add `is/setCaseSensitive` methods.

**Comment by jansohn** [comment]
+1, `setCaseSensitive` method on `CommandLine` would be my preferred solution.

**Comment by remkop** [comment]
Fixed in #9; this will be available from picocli 4.3.
