### ISSUE TITLE
[Documentation] Looking for more examples

### ISSUE THREAD

**Issue by binkley** [remkop/picocli#1540]
I'm looking for more examples of mixing Picocli with JLine for a rich-featured command line tool.
My use case is simple: rolling dice expressions (ref: https://github.com/binkley/kotlin-dice)

My goals are multiple modes of operation:

- Support-type flags, such as `--help` should have colorized output
- Testing -- test `main()` and the modes when possible without hosing streams or hanging
- REPL -- full colorizing and keyboard controls (_eg_, `Ctrl-a`, _et al_)
- Rolls on the command line -- no colorizing, just print to STDOUT, suitable in scripting
- Rolls from STDIN (ie, pipe, etc) -- no colorizing, just print to STDOUT, suitable in scripting

In these, distinguish STDOUT from STDERR.

**Comment by remkop** [comment]
You may be interested in the [Micronaut Starter CLI](https://github.com/micronaut-projects/micronaut-starter/tree/3.2.x/starter-cli/src/main/java/io/micronaut/starter/cli); that uses JLine and picocli.

**Comment by binkley** [comment]
Thanks for that.  I like Micronaut.  Might the example be pulled into the docs as a reference?
If the link is there, apologies for missing it.

**Comment by remkop** [comment]
Another example is the quarkus cli: https://github.com/quarkusio/quarkus/tree/main/devtools/cli/src/main/java/io/quarkus/cli

It may be good to link to both frameworks or even more if possible.

**Comment by binkley** [comment]
Cool.  I am inclined for a docs PR, but it will take me time.
My example usages might not cover enough.  My goal of a UNIX-friendly command line tool might not match other use cases.

**Comment by remkop** [comment]
The source code of the [micronaut-starter CLI](https://github.com/micronaut-projects/micronaut-starter/tree/3.3.x/starter-cli/src/main/java/io/micronaut/starter/cli) may be of interest: it shows how JLine2 and picocli can be combined to provide a complex, full-featured interactive command line REPL application.
