### ISSUE TITLE
Missing GPL v2 + CPE license

### ISSUE THREAD

**Issue by kswartz26** [remkop/picocli#1544]
Our company has been using this code for a while, and we recently noticed that it contains some code under GPL v2 with Classpath Exception (https://github.com/remkop/picocli/blob/master/docs/apidocs/search.js), but we can't find a copy of that license accompanying the project. Can you please add one, either as a separate file or in a NOTICE file?

Thanks!

**Comment by remkop** [comment]
Hi @kswartz26 thank you for raising this.

Will you be able to provide a pull request for this?

**Comment by kswartz26** [comment]
Hopefully that will do it.

**Comment by remkop** [comment]
Thank you for the contribution! Much appreciated.

**Comment by remkop** [comment]
@harbulot Yes that makes sense. 

I will probably rename the NOTICE file to NOTICE-DOCUMENTATION, and clarify that the file in question that is under the GPL is [`docs/apidocs/search.js`](https://github.com/remkop/picocli/blob/master/docs/apidocs/search.js).

I will also clarify that this file is not in any binary distribution and is only included in source code distributions that include the documentation.

**Comment by harbulot** [comment]
@remkop Great, thank you.

**Comment by remkop** [comment]
@harbulot I created https://github.com/remkop/picocli/issues/1750 for this.
