### ISSUE TITLE
Make usage help width configurable

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#159]
As suggested by @waacc-gh in #142:

> You could think about adding an additional attribute to the @command annotation and/or an additional parameter to the CommandLine.usage() methods to change the maximum allowed characters in a line. The improved usage() methods might be helpful to align the output to different windows/screen widths.

**Comment by remkop** [comment]
There are two aspects to this: what should be the API, and can picocli autodetect the console screen width. 

API-wise, I imagine something like this:
```
// programmatically
CommandLine.setUsageWidth(int) : void
CommandLine.getUsageWidth() : int

// declaratively
Command.usageWidth(int);
```

The above would make it possible for command line applications to set a different usage help width than the default 80, but it still puts the burden on these applications to figure out what width to use (and what width is available).

----
In addition, picocli could make an effort to autodetect the console width and adapt the `usageWidth` to the console width. Some options for accomplishing this are documented here:
https://stackoverflow.com/questions/1286461/can-i-find-the-console-width-with-java

Autodetection should be explicitly enabled, likely with a new Command attribute:

```
Command.autoUsageWidth(true|false); // default false
```

**Comment by pditommaso** [comment]
Auto-detection would be a plus, but the giving the ability the usage usage text width would be enough. I would go for a global setting `CommandLine.setUsageWidth(n)` that's applied to all commands (or sub-commands).

**Comment by remkop** [comment]
Yes, sounds good. Do you think you can provide a pull request for this?

**Comment by pditommaso** [comment]
I will try to give a look at the code base and see how much I'm confident with it.

**Comment by remkop** [comment]
Cool. 

FYI, there’s currently a private field `usageHelpWidth` in the `Help` class. I’ve tried to take care to ensure that all alignment is driven off that field (but I could have missed something so needs tests).

**Comment by remkop** [comment]
PR #289 merged into master and the 2.x branch.

System property `picocli.usage.width` can be used to specify a custom width.
The minimum width that can be configured is 55 characters.
