### ISSUE TITLE
Extending / Appending default help message

### ISSUE THREAD

**Issue by SpanVagyTeso** [remkop/picocli#1598]
Hi!
The way i currently extend the default help message is this way
```
@CommandLine.Option(names = {"-h","--help"}, description = "prints this help message")
    boolean usageHelpRequested=false;
    
//at the start of the run()
  if(usageHelpRequested){
      spec.commandLine().usage(System.out);
      printAdditionalHelp();
  }
```
And my question is, is there a better way to append/extend the default help message?

**Comment by remkop** [comment]
One idea is to add a [footer](https://picocli.info/#_header_and_footer) in the `@Command` annotation of your command:

`@Command(footer = {"Additional help line 1.", "Additional help line 2."})`

**Comment by SpanVagyTeso** [comment]
Thank you!
