### ISSUE TITLE
Disabling inherited option in a subclass

### ISSUE THREAD

**Issue by marco-brandizi** [remkop/picocli#1605]
This is similar to #983, though not the same.

I have this situation:  

`class GeneralCmd` is annotated with `@Command` and a few of its fields are annotated with `@Option`.
`class SpecificCmd extends GeneralCmd` has to do very similar things, except it is more specific and doesn't require certain CLI options for which private fields are defined and annotated in `GeneralCmd`, for instance, `GeneralCmd` has a `connectionUrl`  option, while `SpecificCmd` already knows the URL to use for its specific web service and shouldn't allow the user to pass it to the command line.

I can't find any way to disable/remove/ignore an `@Option` that was defined in the super-class.  

I've tried to re-declare the `connectionUrl` field in  `SpecificCmd` as private and without any annotations, picocli keeps reporting the option in the help message as it was declared in `GeneralCmd`.  

I've tried to re-declare `connectionUrl` and re-annotate it with: 
`@Option( names = { "-u", "--url" }, hidden =  true )`, but picocli triggers `DuplicateOptionAnnotationsException`.  I don't want `hidden = true` on the super-class, not when most of the sub-classes actually support a given option, I'd like to be able to tweak a local extension and remove inherited bits. Moreover, I'd like to remove it completely, not just hidden from the '--help'  output.  

Is there a way to do it, with declarations or programmatically?

**Comment by remkop** [comment]
Unfortunately this is not possible. This is similar to how public methods in a superclass always exist in all subclasses, and there is no way to remove one of the methods from the superclass in a subclass.

What I would suggest is, if there are options that do not apply to _all_ subcommands, that you remove those options from the superclass, and move them into a mixin. Then include that mixin only in the subcommands that need those options.

**Comment by remkop** [comment]
@marco-brandizi Does that answer your question?

**Comment by marco-brandizi** [comment]
thanks, @remkop. Yes, mixins seem a good alternative to this use case!

**Comment by remkop** [comment]
Ok great!
I will close this ticket then.
Enjoy picocli!
