### ISSUE TITLE
Make picocli-spring-boot-starter a named JPMS module

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1608]
Make picocli-spring-boot-starter a named JPMS module with the following `module-info`:

```java
/**
 * Defines Spring-based implementations of picocli APIs and picocli-based implementations
 * of Spring APIs for integrating picocli with Spring Boot and Spring Boot AutoConfiguration.
 *
 * @since 4.7.0
 */
module info.picocli.spring.boot {
    requires info.picocli;
    requires java.util.logging;

   // TBD: or spring.boot.starter (see #1604)
    requires spring.boot;
    requires spring.boot.autoconfigure;

    exports picocli.spring;
    exports picocli.spring.boot.autoconfigure;
}
```

The exact dependencies still TBD (see also #1604)

Related to #1298

**Comment by obfischer** [comment]
Hi @remkop, the current released jar for the Picocli Spring Boot Starter does not contain the module info class. Is this a bug or do I miss something?

**Comment by remkop** [comment]
This is a bug. Can you please create a new ticket for this?

**Comment by obfischer** [comment]
@remkop Yes, will to it today

**Comment by obfischer** [comment]
@remkop Issue created and linked to this issue.

**Comment by remkop** [comment]
Thank you 🙏
