### ISSUE TITLE
Warn if input @Parameters is empty and interactive tty

### ISSUE THREAD

**Issue by heuermh** [remkop/picocli#1612]
I am thinking on how best to implement this recommendation:

>  If your command is expecting to have something piped to it and `stdin` is an interactive terminal, display help immediately and quit. This means it doesn’t just hang, like `cat`. Alternatively, you could print a log message to `stderr`.

https://clig.dev/

Is `@IExecutionStrategy` the right extension point for this?

Thank you in advance!

**Comment by remkop** [comment]
@heuermh Perhaps I misunderstood your question...
If you are looking for how to detect whether the current process is connected to a TTY or not, this is not easy to do in pure Java.
The closest thing I have been able to find is invoke `System.console()` and see if it returns a non-null object. (See also https://picocli.info/#_forcing_ansi_onoff)

If you need more fine-grained information, you can use the Jansi library; it has an isTTY method, I believe.

You would call that method and, if the process is not connected to a TTY, then do not start reading from STDIN.
Another additional idea, if your application really cannot afford to hang forever, is to start reading from STDIN in a separate thread, and wait in the main thread for some timeout threshold (like 60 seconds), and then abort if no data has been entered before that timeout. 

As for the place to put this logic, I would put it in the business logic of the application, so in the `run`/`call` method.
I usually only create a separate `IExecutionStrategy` if all commands need to do some shared initialization (like initializing logging or something). 

Hope that is useful.

**Comment by heuermh** [comment]
Thank you for the feedback!

Yes, I was looking into `calcTTY()`, `isTTY()`, `isPseudoTTY()`, etc. methods and noticed it is not exactly easy to determine.

My thinking was that checking if `@Parameters` was empty and in an interactive tty, that was more a command line parameter validation & warning rather than a business logic consideration.  I'll code it up both ways and see what feels better.

**Comment by remkop** [comment]
Sounds great, go for it!

**Comment by heuermh** [comment]
Please do, thanks!
