### ISSUE TITLE
[Question] What is better way to call external command from picocli app

### ISSUE THREAD

**Issue by nqminhuit** [remkop/picocli#1637]
Hello,

I am developing a command line application which is a "wrapper" for `git`, so I have to call it like this:
```
Runtime.getRuntime().exec("/usr/bin/git status", null, path.toFile())
```
to take result and show it.
My question is Am i doing it correctly or is there a better way to support calling external command?

Many thanks,

**Comment by remkop** [comment]
That is one way, but I would recommend taking a look at the [ProcessBuilder](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html) API.

I use it for testing some picocli functions (see
https://github.com/remkop/picocli/blob/main/src/test/java/picocli/test/ProcessExecution.java).

**Comment by nqminhuit** [comment]
Wow thank you very much for your quick reply, I was able to migrate to ProcessBuilder.

**Comment by remkop** [comment]
Ok great! Feel free to ask more questions when they come up. :-)
