### ISSUE TITLE
Cannot accept jvm option like Xms Xmx

### ISSUE THREAD

**Issue by iseehk** [remkop/picocli#1640]
as captioned, how to handle it 

```bash
java MyClass -Xms100k
```
Unknown options: '-Xmx', '1024k'

```bash
java MyClass -Xms=100k
```
Unknown option: '-Xms=100k'

```bash
java MyClass  -Xms 100k
```

Invalid value for positional parameter at index 0 (FILE): '100k' is not an int
Usage: UseArgGroup (([-c] [-f=ARCHIVE] FILE [-h]) | (-x=<x> -y=<y> -z=<z>))
Test to use {@code ArgGroup}, test different option combination validation
UpdateCustomerInfo mode args

**Comment by remkop** [comment]
JVM options (options that you want to pass to the `java` launcher) should be after the `java` command and before the name of your class. For example:

```
java -Xms100k -Xmx1024k MyClass --my-picocli-option1 --my-picocli-option2
```

Any options that follow your class name on the command line are passed to your application's `main` method, and are not interpreted as JVM options but as application options.

**Comment by remkop** [comment]
@iseehk I hope I understood your question correctly. Did this solve the issue?

**Comment by iseehk** [comment]
@remkop  thank you for your help. it is resolved. However the official document does not mention this trick.
