### ISSUE TITLE
new option attribute aboutHelp

### ISSUE THREAD

**Issue by waacc-gh** [remkop/picocli#165]
The new `versionHelp` and `usageHelp` is a good idea. Maybe `aboutHelp` can also be useful.

For this about-text I have the typical about-dialog of nearly every Windows program in mind (menu: Help -> About Eclipse). Ok, for small programs this about-text would not be very different to the version-text, but maybe ...

**Comment by remkop** [comment]
Sorry for my late reply. 

What I had in mind for `versionHelp` is roughly what you describe for `aboutHelp`. The `@Command` annotation already has quite a few attributes - quite a few things to learn for new users. I'd prefer not to add more unless we have a clear use case that cannot be accomplished with the existing annotations/attributes.

**Comment by waacc-gh** [comment]
Never mind, this issue is not a bug, not even an urgent issue. So, no reason to hurry. And by the way, on discussions like that, I'm not impatiently waiting for an answer. Especially not now, in the current season - it's summertime, people should spent their time outside, not in front of a monitor ... ;-) 

In my mind, the difference between `aboutHelp` and `versionHelp` is:
`aboutHelp` is a pleasing presented summary of the program, easy readable for human (like `usageHelp`).
`versionHelp` is a simple output of the version-number, easy machine-analyzable (so another tool can check compatibility).

This issue is more an idea (for discussion), rather than a request.

**Comment by remkop** [comment]
Command line apps commonly only have version help and usage help. 
If an app wants to do something in addition they can always do something custom. 
I’ll close this for now.
