### ISSUE TITLE
call between sub commands cannot get parent command reference?

### ISSUE THREAD

**Issue by lucas-myx** [remkop/picocli#1651]
the code is as follows:
```
@Command(name = "parent",
        subcommands = {SubCommandA.class, SubCommandB.class})
public class ParentCommand implements Runnable {

    PrintWriter out;

    public void setReader(LineReader reader){
        out = reader.getTerminal().writer();
    }
    @Override
    public void run() {}
}
```

`SubCommandA` because business logic needs to call `SubCommandB`

```
@Command(name = "SubCommandA")
public class SubCommandA implements Runnable {

    @Override
    public void run() {
        new CommandLine(new SubCommandB()).execute(args);
    }
}
```
but if it is called in this way, SubCommandB internal parent reference will not instantiate it:
```
@Command(name = "SubCommandB")
public class SubCommandB implements Runnable {

    @CommandLine.ParentCommand
    ParentCommand parent;

    @Override
    public void run() {
        parent.out.println("SubCommandB"); // NPE, because parent is null
        ...
    }
}
```
if it is a SubCommandB called through the ParentCommand class, it can be instantiated. 
so, can SubCommandB get the reference of the parent class when called by SubCommandA ?
(maybe my calling method is wrong)

any suggestions will be appreciated.

**Comment by remkop** [comment]
This can be done.
The issue is that in the `run` method of subcommandA, when you create a new instance (with `new CommandLine(new SubCommandB())`), that instance is not connected to the current command hierarchy.

Instead of creating a new instance, you can try finding the existing instance of `SubCommandB` and calling that:

```java
@Command(name = "SubCommandA")
public class SubCommandA implements Runnable {

    @Spec CommandSpec spec;

    @Override
    public void run() {
        CommandLine subB = spec.parent().subcommands().get("SubCommandB");
        subB.execute(args);
    }
}
```

**Comment by lucas-myx** [comment]
It's **OK** to use this way. Thank you again!

Picocli is great. I will recommend picocli to my colleagues.
