### ISSUE TITLE
Does picocli support server mode operation?

### ISSUE THREAD

**Issue by lucas-myx** [remkop/picocli#1657]
hi @remkop my friend，sorry to bother you again.

I now have a scenario where I want to remotely connect to the server through CMD (interact through Telnet Protocol). 
I want to put **picocli** on the server to parse the command, and then assign it to outputstream, and the client CMD to display the results:

client(tcp) <--> server(picocli)

I don't know whether this is feasible or whether **picocli** supports it? Do you have sample code if you can? 

Thank you very much for any suggestions!

**Comment by remkop** [comment]
Hi @lucas-myx, no, picocli does not support this directly.
You will have to build this yourself.

Essentially, you will need to build a client and server that send each other messages; the client sends `String[]` arrays to the server, the server invokes your commands and captures the response, and sends back this response string to the client, with an indication of whether this is a standard error stream or a standard output stream response (the server may also send two responses for a single `String[]` request).

If I were to write this, I would make a single top-level command with subcommands. 
The client can call the subcommands. The server will always invoke the top-level command with the specified user input.

Rough example:

```java
@Command(name = "server", subcommands = {A.class, B.class, C.class }
class TopLevelCommand { // does not implement Runnable or Callable - subcommand is required
}
```
The server would somehow receive `String[]` requests from client(s) and execute those requests as follows:

```java
// some server class
public void handleRequest(String[] requestArgs, MyConnection client) {
    CommandLine cmd = new CommandLine(new TopLevelCommand());
    StringWriter out = new StringWriter();
    StringWriter err = new StringWriter();
    cmd.setOut(new PrintWriter(out, true));
    cmd.setErr(new PrintWriter(err, true));

    // request args is expected to be something like ["a", "--option1", "--option2"]:
    // the subcommand followed by the parameters for that subcommand
    cmd.execute(requestArgs);

    client.sendReply(out.toString(), err.toString());
}
```

Hope this is useful.

**Comment by lucas-myx** [comment]
Yes, thank you. 
your response is always so timely. 
This suggestion and code are helpful to me. I'll try it according to this idea.
Thank you again!
