### ISSUE TITLE
Define a prefix for arg group 

### ISSUE THREAD

**Issue by SpanVagyTeso** [remkop/picocli#1675]
Hi!
I'd like to create 2 arg groups where everything would be the same but with different prefixes
    --from-store          
    --from-pass                         fromGroup
    --to-provider-name

    --to-store               
    --to-pass                             toGroup
    --to-provider-name
 is there a way to make them?
 It'd would be helpful to have a single function where i could
 initFrom(fromGroup)
 initFrom(toGroup)

**Comment by remkop** [comment]
Hi @SpanVagyTeso,
I'm not sure I understand the question. 
You can simply make two classes that have those options. 
Does that not meet your needs?

**Comment by SpanVagyTeso** [comment]
It does, but the difference would be between, the two classes would be
classA options would start with --from-
classB options would start with --to-
Everything else would be identical

**Comment by SpanVagyTeso** [comment]
So for Example
```
class KeyStoreGroupFrom {
    @Option(
        names = ["--from-store"]
    )
    lateinit var keyStore: File

    @Option(
        names = ["--from-pass"]
    )
    lateinit var password : CharArray

    @Option(
        names = ["--from-provider-params"]
    )
    lateinit var providerParams : String
}
```
and
```
class KeyStoreGroupTo {
    @Option(
        names = ["--to-store"]
    )
    lateinit var keyStore: File

    @Option(
        names = ["--to-pass"]
    )
    lateinit var password : CharArray

    @Option(
        names = ["--to-provider-params"]
    )
    lateinit var providerParams : String
}
```

**Comment by remkop** [comment]
@SpanVagyTeso I see, thank you for the clarification.
I can see the similarity and understand that you are looking for a way to get rid of the duplication.

However, I don't think that there is a way to accomplish that in picocli.
For now, you will have to live with the duplication.

**Comment by SpanVagyTeso** [comment]
I see, thank you very much for you answers!
