### ISSUE TITLE
optional `CommandLine.Option` field shows improperly

### ISSUE THREAD

**Issue by zappee** [remkop/picocli#1679]
Maybe this is my fault, but it seems that the `CommandLine.Option` field shows improperly if `defaultValue` is not provided.

**Use case 1:**
```
@CommandLine.Option(
        names = {"-d", "--date"},
        description = "The price on a certain date in the past.")
private String date;

output:
(... | -d=<date> | ...)
``` 

**Use case 2:**
```
@CommandLine.Option(
        names = {"-d", "--date"},
        description = "The price on a certain date in the past.",
        defaultValue = "null")
private String date;

output:
(... | [-d=<date>] |  ...)
```

In `case 1`, without providing the default value, the field shows as a mandatory field and the `[` and  `]` symbols are not shown.

If I provide a default value (`case 2`), then the field appears optional, and the `[` and  `]` symbols appear as it is expected. Unfortunately, there is no way to assign `null` as a default value. If I assign a fake default value, then the variable is not `null` anymore so my app not able to decide whether the option value was set by the user or not.

**Comment by remkop** [comment]
To be honest, I'm not 100% clear on what it is you're trying to achieve. 

It is possible to specify `null` as default value in the annotations with the constant `defaultValue = Option.NULL_VALUE`. (See https://picocli.info/#_optionalt)

Bear in mind that when an option has a default value, picocli will not give the user an error when this option is not specified on the command line, even if the option is declared as `required = true`.

**Comment by remkop** [comment]
Actually, looking at the output and noticing the round brackets `(` and )`, I realized that this option is part of an argument group. A mutually exclusive group, to be precise. 

The brackets around the group are round not square, so the group itself is required. 
Within an exclusive group, options are [required by default](https://picocli.info/#_non_required_options_in_mutually_dependent_groups), but when the option has a default value, it is no longer required. So, when the option has a default value it’s displayed in square brackets in the synopsis of the usage help message. 

Does this help clarify the issue?

**Comment by zappee** [comment]
thx, it helped.
