### ISSUE TITLE
feature request: possiblity to refer recursively to another option in the default expression of an option

### ISSUE THREAD

**Issue by pbillen** [remkop/picocli#1683]
Hi,

I have a use case which, I believe, requires the default value of an option to be resolved recursively. Something like:

```
@Option(names = "-e", defaultValue = "prd", required = false)
String environment;
@Option(names = "-u", defaultValue = "http://www.${env}.mywebsite.com/some/endpoint", required = false)
String url;
```
This allows the user of the application to either alter the environment via `-e` and have the URL resolved automatically, or in custom/special cases (assuming that the default URL template isn't sufficient), to manually override the URL via `-u`.

Does that make any sense? What do you think?

Thank you.

**Comment by remkop** [comment]
Interesting use case!
However, you may need to support this in the application, 
I feel that supporting this in the library would introduce too much complexity.

Implementation-wise, the application could do a String replace on `${env}` , it seems to me that no library support is required:

```java
public void run() {
    String actualUrl = url.replace("${env}", environment); // if user specified a value, it won't contain the ${env} string
    // use actual url...
```
