### ISSUE TITLE
Is it possible to manually invoke binding for options and parameters?

### ISSUE THREAD

**Issue by budjb** [remkop/picocli#1689]
I have a somewhat complex setup with subcommands and I'm running into issues with argument binding to `@Options` and `@Parameters` properties. I do not have code, unfortunately, but I'll do my best to explain what I'm trying to do.

I have a fully-built `CommandSpec` tree with subcommands of an undetermined depth. Each subcommand is itself a `CommandSpec`, which may have been partially build through the use of `CommandSpec.forAnnotatedObject()` against an object with annotated properties and then further configured (such as command name, etc).

Using the root of the `CommandSpec` tree, I am able to parse a list of argument which may point at some subcommand somewhere in the tree. For the target subcommand, if an object with annotated properties was used to build the subcommand's `CommandSpec`, I need to bind the command's arguments to an instance of that object.

I'd like to reuse the logic that exists within the picocli library already so that I don't need to write custom logic, and the other injection logic works (such as `@Spec`, for example).

Is there some way to manually invoke the binding logic with a ParseResult and an object with annotated fields?

**Comment by remkop** [comment]
Hi @budjb, thanks for your question.
I have trouble following what you are trying to do... 
I think I understood the first two paragraphs, but have trouble with the third paragraph.

Does your application have custom parsing logic, or is it using one of picocli's `CommandLine::parseArgs` or `CommandLine::execute` methods to parse the command line arguments?

The reason I am asking is that, when a CommandSpec is created with `CommandSpec.forAnnotatedObject()`, picocli's built-in parsing is supposed to automatically invoke the bindings of the annotated properties of the application class/object used to build that `CommandSpec`. So I don't understand why your application would need to do this manually...

The binding logic is created at `CommandSpec` initialization time (during the call to `CommandSpec.forAnnotatedObject()`): all `OptionSpec` and `PositionalParamSpec` objects that are in that `CommandSpec` will have `IGetter` and `ISetter` bindings when the `CommandSpec` is created. If you need to have custom bindings, then probably the best way is to programmatically create the `OptionSpec` and `PositionalParamSpec` objects and set their `IGetter` and `ISetter` bindings **before** adding them to the `CommandSpec`.

During parsing, these bindings are invoked when the parser matches this option or positional parameter with a command line argument. Simultaneously, the parser also populates a `ParseResult` (or chain of `ParseResult` objects for commands with subcommands), so that applications can also process the result programmatically.

So you can see that creating such bindings after parsing would be too late, as the bindings will not be invoked after parsing, but during parsing.

Is this useful? Don't hesitate to ask follow-up questions.

**Comment by budjb** [comment]
Thanks for the reply @remkop!

Hopefully this will provide some more context. I'm building a complete tree of subcommands into a single `CommandSpec` based on Spring beans. I am not using the Spring bean as a user object because state should not be stored in singletons in a multithreaded environment, and so that bean may define another object (basically a POJO) which will serve as the user object.

For each level, I create a `CommandSpec` and add immediate subcommands in a recursive fashion, as so:
```
CommandSpec getCommandSpec() {
        CommandSpec commandSpec = CommandSpec.create();

        // getCommandOptions may return a POJO which will have properties annotated with picocli and JSR380 annotations
        if (getCommandOptions() != null) {
            commandSpec = CommandSpec.forAnnotatedObject(getCommandOptions());
        }

        // I'm always overriding the spec name to match a name contained on the Spring bean, and I do not annotate the user objects with @Command
        commandSpec.name(getName());
        commandSpec.mixinStandardHelpOptions(true);

        // The spring bean may provide a list of subcommands as other Spring beans, so recursively iterate to build the subcommand tree into a CommandSpec.
        for (SlackCommand sub : getSubCommands()) {
            commandSpec.addSubcommand(sub.getName(), sub.getCommandSpec());
        }

        return commandSpec;
    }
```

When I am accepting a list of args (which will parsed and tokenized from some method besides a CLI instantiation), I pass the `CommandSpec` to the `CommandLine` and then run `parseArgs`.
```
CommandLine commandLine = new CommandLine(commandSpec);
ParseResult result = commandLine.parseArgs(args);
```

Based on the command/subcommand that was requested, I have code that will determine which Spring bean to execute myself. The problem is I am unsure of how to get the user object with the bound options/parameters properties from the parsed args in order to provide to the Spring bean for execution.

Does this help?

**Comment by remkop** [comment]
Thank you for the clarification.
One idea is to encapsulate your custom logic (that determines which Spring bean to execute) in a picocli [`IExecutionStrategy`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.IExecutionStrategy.html).
That would enable you to stay within the picocli framework and have your code look like this:

```java
CommandLine commandLine = new CommandLine(commandSpec);
commandLine.setExecutionStrategy(createCustomExecutionStrategy());
int exitCode = commandLine.execute(args);
System.exit(exitCode);
```

The default execution strategy is [`RunLast`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.RunLast.html).
The javadoc for the `RunLast` strategy actually shows an example implementation that you can follow.

That javadoc is slightly out of date, especially supporting help requests is better done as shown below:

```java
// class MyCustomExecutionStrategy implements IExecutionStrategy
public int execute(ParseResult parseResult) throws ExecutionException {
    // user may have requested help for the top-level command or for a subcommand
    Integer helpExitCode = CommandLine.executeHelpRequest(parseResult); //display the appropriate usage help msg
    if (helpExitCode != null) { return helpExitCode; } //helpExitCode is null if help was not requested

    Tracer t = CommandLine.tracer();
    t.debug("%s: handling ParseResult...", getClass().getSimpleName()); // for debugging your stuff

    // flatten the nested ParseResult objects into a list
    List<CommandLine> parsedCommands = parseResult.asCommandLineList();

    // assuming your application does not support Repeatable Subcommands
    // (https://picocli.info/#_repeatable_subcommands),
    // then the last command in the list is the most specific subcommand: that is the one you want
    CommandLine last = parsedCommands.get(parsedCommands.size() - 1);
    t.debug("%s: user specified subcommand '%s'", getClass().getSimpleName(), last.getCommandName());

    // get the user object for that most specific subcommand
    Object userObject = last.getCommand();
    t.debug("%s: executing user object %s", getClass().getSimpleName(), userObject.toString());

    // your custom execution logic comes here:
    // find and run the Spring bean to execute, based on the user object of the most specific subcommand
    // you may want to surround that execution call with try/catch
    // and return `parseResult.commandSpec().exitCodeOnExecutionException()` when an exception occurs
    // and otherwise return `parseResult.commandSpec().exitCodeOnSuccess()`
}
```

That's it. That allows you to have custom logic for executing your Spring beans and still get the benefits of automatic handling of user requests for help, exit code, etc.

**Comment by budjb** [comment]
Thanks! Unfortunately, I need to pass a custom context object to the
execution method I will be invoking, and it will return some
arbitrary object type that I also need to capture and further process. I
don't think the execution strategy above allows me to do so because of its
inputs and return types. That's why I was specifically trying to figure out
a way to perform the user object binding: that user object will be
contained as part of a larger context object that I pass to some method to
execute the command.

**Comment by remkop** [comment]
Ok. I don't see how that is a problem, isn't that just a matter of how things are wired together?

For example:

```java
CommandLine commandLine = new CommandLine(commandSpec);
MyCustomExecutionStrategy strategy = createCustomExecutionStrategy(customContextObject);
commandLine.setExecutionStrategy(strategy);
int exitCode = commandLine.execute(args);

CustomResult result = strategy.getExecutionResult(); // get your custom result for further processing
// do stuff with result...
// and exit
System.exit(exitCode);
```

```java
// MyCustomExecutionStrategy
public int execute(ParseResult parseResult) throws ExecutionException {

    // ... (see code in previous comment)
    Object userObject = lastCmd.getCommand();

    try {
        // cast to your application interface that has a getter for the Spring bean to execute
        MyBeanProvider mbp = (MyBeanProvider) userObject;

        // get the actual executable Spring bean from the user object
        MyExecutableSpringBean bean = mbp.getExecutableSpringBean();

        // execute it, passing the custom context object (that this execution strategy was constructed with)
        CustomResult result = bean.execute(customContextObject);
        this.setExecutionResult(result); // store result for retrieval by other components
    } catch (Exception ex) {
        throw new ExecutionException(lastCmd, ex);
    }
    return lastCmd.exitCodeOnSuccess();
```

The command user object is determined by what is passed in to the `CommandSpec.forAnnotatedObject()` method.
This cannot be changed, but you can wire your user object so that it has a reference to the Spring Bean that needs to be executed.

**Comment by budjb** [comment]
That makes a lot of sense (thinking about an execution strategy as a
per-invocation object). I'll give this a shot and let you know where I end
up! Thanks!

**Comment by budjb** [comment]
It looks like the piece I needed was this:

```
Object userObject = lastCmd.getCommand();
```

This gets me the bound object that I can pass along as needed without needing to implement an execution strategy.

One last question: is a `CommandSpec` modified by the `parseArgs` method (or anything underneath it) in any way, or is it effectively immutable during that process? In other words, can I reuse a `CommandSpec` multiple times without state changes in that object through subsequent uses?

**Comment by remkop** [comment]
The CommandSpec does not change during parsing. The CommandLine object has a ParseResult, that is reset before any call to parseArgs/execute. Both CommandLine and CommandSpec are intended to be reusable.

Areas that need care when reusing CommandLine/CommandSpec objects:
* There is one [known edge case](https://github.com/remkop/picocli/issues/1010) that does not work, which has to do with [Repeatable Subcommands](https://picocli.info/#_repeatable_subcommands) combined with the programmatic API. If your application does not have Repeatable Subcommands this is not a concern for you.
* If your application uses ArgGroups, make sure to read the section on [default values in argument groups](https://picocli.info/#_default_values_in_argument_groups).

**Comment by remkop** [comment]
One more thing:

> (...)
> This gets me the bound object that I can pass along as needed without needing to implement an execution strategy.

Cool. No need to create a full-blown execution strategy. 
However, this does mean that your application becomes responsible for handling end user's requests for `--help` and `--version`.
You still may want to do the below with the `ParseResult` before any other processing, to ensure your application handles that correctly:

```java
    // user may have requested help for the top-level command or for a subcommand
    Integer helpExitCode = CommandLine.executeHelpRequest(parseResult); //display the appropriate usage help msg
    if (helpExitCode != null) { return; } 

    //only run the application code if helpExitCode is null (help was not requested)
```

The above will display help or version info for the correct subcommand.

**Comment by budjb** [comment]
Ah right. Currently in checking the last command's flags for whether help
or version was requested and running the better method which returns the
appropriate message as a string.

I'm basically implementing a cli style interface into a slack bot that
reacts to messages where the bot is mentioned. That makes the bot's name
the root command and everything else is a sub from there. I need to capture
all the output and send it back to the user over API requests to slack's
API. That also means the application itself is kind lived, which led me
down this path.

Thanks to all your help, I have a working framework for all of this!

**Comment by remkop** [comment]
ok great. I will close this ticket, feel free to open another one any time.
