### ISSUE TITLE
Overrideable factory for annotation based subcommands instantiation

### ISSUE THREAD

**Issue by kakawait** [remkop/picocli#169]
Since latest version is now possible to declare subcommands using annotations, however unlike programmatic way those subcommands must have and will use empty constructor.

In some use case it could be cool to override the code that is responsible to instantiate those subcommands classes to apply another logic, like grabbing some already existing instance from bean context or other something else. In my case is more about re-using existing bean to be able to use application context and dependency injection.

**Comment by remkop** [comment]
I can see how this would be useful. I assume you want to set the factory programmatically, or would this also be an annotation?

**Comment by kakawait** [comment]
I though about programmatically way because I didn't know how you can describe it with annotations.

**Comment by kakawait** [comment]
Thank a lot

**Comment by remkop** [comment]
This issue has been addressed in picocli 2.2, which is now available on JCenter and Maven Central. 
See the [release notes](https://github.com/remkop/picocli/releases/tag/v2.2.0) for details. 

Any updates planned for Picocli Spring Boot Starter?
