### ISSUE TITLE
Why does Picocli use Graalvm

### ISSUE THREAD

**Issue by HelloTo4x** [remkop/picocli#1693]
Hi, why does Picocli use Graalvm instead of JVM. Does it in order to build native image faster, compile faster and low foot print

**Comment by remkop** [comment]
Hi @HelloTo4x. 
Picocli does not use GraalVM itself, but it can generate configuration files for your application, if it uses picocli, such that _your application_ can easily be compiled to a GraalVM native image. 

The advantages are indeed that your application's native image will have a lower memory footprint and ultra-fast startup.

Compiling a native image is actually not fast; after compiling your Java source to .class files, there is an additional compilation step that uses native compilers to generate the native image for the target platform. This can take several minutes to build.

The advantage is for end users of your application: they get a single-file application that requires no installation, no JVM to run, and is blazingly fast.

**Comment by remkop** [comment]
You may like this article:
https://www.infoq.com/articles/native-java-aligning/
