### ISSUE TITLE
Option values starting with dash (-) and passed in quotes "" are interpreted as another option

### ISSUE THREAD

**Issue by fabio-franco** [remkop/picocli#1701]
Example: I have an option that uses -x (verbose) and a second option using --java-opts (java option for JVM). Also, it is important to mention that for all my commands, I would like the flexibility to be case insensitive (i.e., `setOptionsCaseInsensitive(true)`). 

The options are something like:

```
@Option(names = {"-x", "--verbose"})
@Option(names = { "--java-opts" }, description =  "The value need to be inserted using double-quotes, i.e., \"<string>\"")
```

So the end user would use the `--java-opts` to pass a value for JVM consume. Since commonly the JVM options starts with dash, as for example, "-Xmx512m", I was expecting that asking the end user to pass the value within the double-quotes should be enough.

However, when the user pass something like `myapp --java-opts "-Xmx512m"` or `myapp --java-opts="-Xmx512m"` picocli is interpreting it as the -x command, for verbose, instead of get it as the value for `java-opts` option.

**Comment by remkop** [comment]
Hi @fabio-franco, yes I can see how the picocli parser would not be able to distinguish those.

One idea is to do [custom parameter processing](https://picocli.info/#_custom_parameter_processing). 
The manual has an [example](https://picocli.info/#_example_use_case) for parameter preprocessors that is similar to your use case, that looks at whether a value is attached to the option with an `=` equals character (e.g. `--java-opts=-Xmx512m`), and use that to determine whether to consider that a option parameter or not.

**Comment by fabio-franco** [comment]
Hi @remkop, thank you so much for the quick reply. 

Yes, I think that the suggestion makes sense and probably works for me. 

Just a curiosity... based on the Picocli parser limitation to distinguish parameters and values passed by double-quotes, do you think it is valid to change the issue to a request for enhancement?

**Comment by remkop** [comment]
I don't think double-quotes make any difference in this case. They help if you want to pass a value that contains spaces, for example.

But will always be some ambiguity that picocli cannot solve.
For example, [this one](https://picocli.info/#_optional_parameter_limitations).

It will be difficult to improve the library to cater for all such cases.
I think the custom parameter handling mechanisms give applications the ability to have ambiguity in their options/parameters, and still make the application work exactly the way they want.
