### ISSUE TITLE
CommandSpec is null in constructor

### ISSUE THREAD

**Issue by antimatter84** [remkop/picocli#1702]
In a command class (abstract class) I have a `@Spec` field. I have observed, however, that the spec is not injected before the constructor of that command class is run. Therefore, the spec field is null and can not be accessed from the constructor. 

All the actual command classes, which inherit from the abstract command class, as well as some non-command classes require information obtained from the command spec. So I want to extract that information in one place.

Is it possible to have the spec injected before the constructor is called or as a constructor parameter? Example:
`public MyCommand(@Spec CommandSpec spec) { ... }`

**Comment by remkop** [comment]
I am not sure I understand:
if the constructor is not called yet, the object does not exist yet, so there is no object (yet) to inject the spec into...
Am I missing something?

**Comment by antimatter84** [comment]
You are correct. I took a wrong turn here.
What I actually need is a way to run some code after the spec has been injected and before a command is executed. That code requires the spec.

A solution may be something similar to `@PostConstruct`, so we could annotate a method of a command class with `@AfterSpecInjection` and Picocli would run it as described above.

**Motivation:**
For my app I wrote a class (CliPrinter) that prints data nice and pretty on stdout and is used by all my commands.
Options defined in my root command influence the way the printer works and I don't want to provide these options to printer every time it is used. The printer (not a command) should read this information from some place. An after-injection-method would then come in handy to read the global options and store the data at said place for the printer to read.

**Comment by remkop** [comment]
Thank you for the clarification.
Two ideas:

1. run your custom code after creating the `CommandLine` object for the top-level command, but before parsing the arguments. For example:

```java
MyClass myObject = new MyClass(); // spec is not injected yet
CommandLine cmd = new CommandLine(myObject); // spec is now injected

myObject.doStuffWithInjectedSpec(); // do custom stuff

cmd.execute(args); // finally execute the command
```

2. set up an execution strategy to do [initialization before execution](https://picocli.info/#_initialization_before_execution). This method will be invoked after the arguments were successfully parsed:

```java
CommandLine cmd = new CommandLine(new MyClass());
cmd.setExecutionStrategy(new IExecutionStrategy() {
    public int execute(ParseResult parseResult) {
        MyClass myObject = (MyClass) parseResult.commandSpec().userObject();
        // ... do your custom stuff

        return new RunLast().execute(parseResult); // finally, delegate to the default execution strategy
    }
});
cmd.execute(args);
```

**Comment by remkop** [comment]
@antimatter84 Did this resolve the issue?

**Comment by antimatter84** [comment]
Yes, sorry for the delay.
I went with suggestions number 2 and I am very happy with that.
