### ISSUE TITLE
Option descriptions not read from parent command resource bundle

### ISSUE THREAD

**Issue by rsenden** [remkop/picocli#1706]
Suppose we have the following command hierarchy:

```
  RootCommand (resourceBundle=RootMessages)
  - ModuleCommand (resourceBundle=ModuleMessages)
     - Cmd1
     - Cmd2
```

Behaviour:
- As expected: If we define `usage.footer` in the RootMessages bundle, this footer will be displayed on all commands.
- As expected: If we define `option1` in the ModuleMessages bundle, any `option1` in any of the leaf commands displays the proper description.
- Not as expected: If we define `option2` in the RootMessages bundle, any `option2` in any of the leaf commands displays an empty description

Since our modules are maintained by different teams, we want to have a dedicated resource bundle for each module. However, as we also have some common options that are used throughout the application (mostly through generic mixins), we would like to define the descriptions for those generic options in the RootMessages bundle.

Unfortunately that doesn't seem to work, so for now we have to replicate those command option descriptions across every ModuleMessages bundle in each module. Obviously this is something that we would like to avoid.

Is there any way to make this work with the current picocli version, or will this require a fix in picocli?

**Comment by remkop** [comment]
> * As expected: If we define `usage.footer` in the RootMessages bundle, this footer will be displayed on all commands.
> * As expected: If we define `option1` in the ModuleMessages bundle, any `option1` in any of the leaf commands displays the proper description.
> * Not as expected: If we define `option2` in the RootMessages bundle, any `option2` in any of the leaf commands displays an empty description

To clarify: you are saying that the (non-empty) description for `option2` in the RootMessages bundle gets lost because of the intermediate ModuleMessages bundle?

And, the behaviour for options is different from the behaviour for things like the footer?
So the scenario is that ModuleMessages bundle does not contain a `usage.footer` key, only the top-level RootMessages bundle has this key, but still, while Cmd1 and Cmd2 can access the `usage.footer` keys from the top-level RootMessages bundle, they cannot access the `option2` in the RootMessages bundle?

That seems a bit strange, to be honest... Can you verify that this is really what is happening?

Generally speaking, the easiest way with current picocli would be to have a single ResourceBundle that is set at the top-level command, that has all the keys for all commands. This can be done by prefixing the option names with the command name.

For example:

```
# single resource bundle set on RootCommand, other commands do not have a resource bundle
RootCommand.ModuleCommand.Cmd1.option1 = description for this option1
RootCommand.ModuleCommand.Cmd2.option1 = description for cmd 2 option1
option2 = generic option2 description for all commands
usage.footer = generic footer for all commands
RootCommand.ModuleCommand.Cmd2.usage.footer = only this command has a special footer
```

One idea of how to manage this is could be to have separate teams manage separate resource bundles for their own modules, and merge them into a single bundle during the build.

**Comment by rsenden** [comment]
Your understanding is correct, this is what seems to be happening. I'm currently running our application through a debugger, will add a comment if I find out more details.

Merging the bundles during the build is also an option, but that could potentially cause some other complications. For example, you can't have module-specific default descriptions. For example, multiple modules may have a `--url` option, for module 1 you may want to set a generic description 'URL for system 1' and for module 2 'URL for system 2'.

**Comment by rsenden** [comment]
I think the reason that this is working for footers and most/all other `usage.*` properties is because of the `UsageMessageSpec#footer()` method:

```
public String[] footer() { return arr(resourceArr("usage.footer"), footer, DEFAULT_MULTI_LINE); }
```

If no footer is defined in the ModuleMessages bundle, `resourceArr("usage.footer")` returns null, in which case the `footer` instance variable is used instead. Apparently this variable gets initialized with the `usage.footer` value defined in the RootMessages bundle.

I guess in order for this to work for options as well, the `Messages` class would need to look in resource bundles of parent commands if it can't find the property in its own resource bundle. Is this something that you would consider for inclusion in a next version of picocli? I can look into creating a PR for this.

**Comment by remkop** [comment]
Thank you for the analysis of why footers work differently.


> I guess in order for this to work for options as well, the `Messages` class would need to look in resource bundles of parent commands if it can't find the property in its own resource bundle. Is this something that you would consider for inclusion in a next version of picocli? I can look into creating a PR for this.

Yes, I think that would be a nice improvement. If you could create a PR with tests, that would be great!

**Comment by rsenden** [comment]
@remkop, I looked into having the Messages class take resource bundles from parent commands into account, but ran into an issue. Apparently, `CommandSpec` doesn't allow for accessing the top-level command that was used to construct the `CommandLine` object. 

Extract from our code:

```java
// CommandLine construction
new CommandLine(FCLIRootCommands.class, micronautFactory)

// FCLIRootCommands
@Command(name="fcli", resourceBundle="...", subcommands={ConfigCommands.class, ...})
public class FCLIRootCommands { ... }

// ConfigCommands
@Command(name="config", resourceBundle="...", subcommands={...})
public class ConfigCommands { ... }
```

For the `config` command, I'd expect both `parent` and `root` to point to the `fcli` command, however `parent` is null and `root` points to the `config` command itself:

```
command 'fcli' (user object: class com.fortify.cli.app.FCLIRootCommands), parent: null, root: command 'fcli' (user object: class com.fortify.cli.app.FCLIRootCommands)
command 'config' (user object: class com.fortify.cli.config.picocli.command.ConfigCommands), parent: null, root: command 'config' (user object: class com.fortify.cli.config.picocli.command.ConfigCommands)
```

Is this behavior by design, or can this be considered a bug? Is there any other way for accessing the `CommandSpec` of the top-level `FCLIRootCommands` class while processing the `CommandSpec` of subcommands?

**Comment by remkop** [comment]
Hi @rsenden, that sounds strange, but I cannot reproduce the issue you describe.

I tried with this test:

```java
public class HierarchyTest {

    // FCLIRootCommands
    @Command(name="fcli", /*resourceBundle="...",*/ subcommands={ConfigCommands.class})
    public static class FCLIRootCommands { }

    // ConfigCommands
    @Command(name="config", /*resourceBundle="...",*/ subcommands={ConfigChild.class})
    public static class ConfigCommands { }

    @Command(name="config-child", /*resourceBundle="...",*/ subcommands={})
    public static class ConfigChild { }

    public static void main(String[] args) {
        CommandLine.IFactory factory = CommandLine.defaultFactory();
        CommandLine cmd = new CommandLine(FCLIRootCommands.class, factory);
        print(cmd);
    }

    private static void print(CommandLine cl) {
        Object userObject = cl.getCommand();
        CommandLine.Model.CommandSpec spec = cl.getCommandSpec();
        System.out.printf("%s.name=%s, parent.name=%s, root.name=%s%n",
                userObject.getClass().getSimpleName(),
                spec.name(),
                spec.parent() == null ? "null-parent" : spec.parent().name(),
                spec.root().name());
        for (CommandLine c : cl.getSubcommands().values()) {
            print(c);
        }
    }
}
```

and it produces the following (correct-looking) output:

```
FCLIRootCommands.name=fcli, parent.name=null-parent, root.name=fcli
ConfigCommands.name=config, parent.name=fcli, root.name=fcli
ConfigChild.name=config-child, parent.name=config, root.name=fcli
```

**Comment by remkop** [comment]
Oh, I see you edited your comment, and the issue is related to timing during the initialization phase. Understood.

**Comment by rsenden** [comment]
Hi @remkop, the following implementation of the `Messages` class seems to work fine for my application. It uses lazy loading to avoid the issue described in my previous comment; any idea whether there's a risk of Messages instances being called by multiple threads, requiring synchronization?

Summary of changes:

- Add `parent()` method (and instance field) for lazy instantiation of a parent Messages instance, searching for parent `CommandSpec` instances that have a different resource bundle base name than the current Messages instance
- Update `isEmpty()` method to return true only if both current and parent Messages instances are empty
- Add `getStringForExactKey()` and `getStringArrayForExactKey()` methods that look up the given key in either current Message object or its parent if available
- Update `getString()`, `getStringArray()` methods to use the `getString*ForExactKey()` methods, resulting in the following lookup order:
    - Fully qualified key in current Messages instance
    - Fully qualified key in the closest parent Messages instance that contains that key
    - Simple key in current Messages instance
    - Simple key in the closest parent Messages instance that contains that key

```java
        public static class Messages {
            private final CommandSpec spec;
            private final String bundleBaseName;
            private final ResourceBundle rb;
            private final Set<String> keys;
            private Messages parent;
            public Messages(CommandSpec spec, String baseName) {
                this(spec, baseName, createBundle(baseName));
            }
            public Messages(CommandSpec spec, ResourceBundle rb) {
                this(spec, extractName(rb), rb);
            }
            public Messages(CommandSpec spec, String baseName, ResourceBundle rb) {
                this.spec = Assert.notNull(spec, "CommandSpec");
                this.bundleBaseName = baseName;
                this.rb = rb;
                this.keys = keys(rb);
                if (rb != null) {
                    CommandLine.tracer().debug("Created Messages from resourceBundle[base=%s] for command '%s' (%s)", baseName, spec.name(), spec);
                }
            }
            private static ResourceBundle createBundle(String baseName) {
                return ResourceBundle.getBundle(baseName);
            }
            private static String extractName(ResourceBundle rb) {
                try { // ResourceBundle.getBaseBundleName was introduced in Java 8
                    return (String) ResourceBundle.class.getDeclaredMethod("getBaseBundleName").invoke(rb);
                } catch (Exception ignored) { return "?"; }
            }
            public Messages parent() {
            	CommandSpec parentSpec = this.spec.parent();
            	if ( parent==null || parent.spec!=parentSpec ) {
            		parent = null; // Refresh if parentSpec doesn't match
            		while ( parent==null && parentSpec!=null ) {
		            	String parentResourceBundleBaseName = parentSpec.resourceBundleBaseName();
		            	if ( parentResourceBundleBaseName!=null && !parentResourceBundleBaseName.equals(this.bundleBaseName)) {
		            		parent = new Messages(parentSpec, parentResourceBundleBaseName);
		            	} else {
		            		parentSpec = parentSpec.parent();
		            	}
            		}
            	}
	            return parent;
            }
            private static Set<String> keys(ResourceBundle rb) {
                if (rb == null) { return Collections.emptySet(); }
                Set<String> keys = new LinkedHashSet<String>();
                for (Enumeration<String> k = rb.getKeys(); k.hasMoreElements(); keys.add(k.nextElement()));
                return keys;
            }

            /** Returns a copy of the specified Messages object with the CommandSpec replaced by the specified one.
             * @param spec the CommandSpec of the returned Messages
             * @param original the Messages object whose ResourceBundle to reference
             * @return a Messages object with the specified CommandSpec and the ResourceBundle of the specified Messages object
             */
            public static Messages copy(CommandSpec spec, Messages original) {
                return original == null ? null : new Messages(spec, original.bundleBaseName, original.rb);
            }
            /** Returns {@code true} if the specified {@code Messages} is {@code null}, has a {@code null ResourceBundle}, or has a {@code null parent Messages}. */
            public static boolean empty(Messages messages) { return messages == null || messages.isEmpty(); }

            /** Returns the String value found in the resource bundle for the specified key, or the specified default value if not found.
             * @param key unqualified resource bundle key. This method will first try to find a value by qualifying the key with the command's fully qualified name,
             *             and if not found, it will try with the unqualified key.
             * @param defaultValue value to return if the resource bundle is null or empty, or if no value was found by the qualified or unqualified key
             * @return the String value found in the resource bundle for the specified key, or the specified default value
             */
            public String getString(String key, String defaultValue) {
                if (isEmpty()) { return defaultValue; }
                String cmd = spec.qualifiedName(".");
                String qualifiedKey = cmd + "." + key;
                String result = getStringForExactKey(qualifiedKey);
                if ( result==null ) { result = getStringForExactKey(key); }
                return result!=null ? result : defaultValue;
            }
            
            private String getStringForExactKey(String key) {
            	if (keys.contains(key)) { return rb.getString(key); }
            	else if (parent()!=null) { return parent().getStringForExactKey(key); }
            	else { return null; }
            }

            boolean isEmpty() { return (rb == null || keys.isEmpty()) && (parent()==null || parent().isEmpty()); }

            /** Returns the String array value found in the resource bundle for the specified key, or the specified default value if not found.
             * Multi-line strings can be specified in the resource bundle with {@code key.0}, {@code key.1}, {@code key.2}, etc.
             * @param key unqualified resource bundle key. This method will first try to find a value by qualifying the key with the command's fully qualified name,
             *            and if not found, it will try with the unqualified key.
             * @param defaultValues value to return if the resource bundle is null or empty, or if no value was found by the qualified or unqualified key
             * @return the String array value found in the resource bundle for the specified key, or the specified default value
             */
            public String[] getStringArray(String key, String[] defaultValues) {
                if (isEmpty()) { return defaultValues; }
                String cmd = spec.qualifiedName(".");
                String qualifiedKey = cmd + "." + key;
                String[] result = getStringArrayForExactKey(qualifiedKey);
                if ( result==null ) { result = getStringArrayForExactKey(key); }
                return result!=null ? result : defaultValues;
            }
            private String[] getStringArrayForExactKey(String key) {
            	List<String> result = addAllWithPrefix(rb, key, keys, new ArrayList<String>());
            	if (!result.isEmpty()) { return result.toArray(new String[0]); }
            	return parent()==null ? null : parent().getStringArrayForExactKey(key);
            }
            private static List<String> addAllWithPrefix(ResourceBundle rb, String key, Set<String> keys, List<String> result) {
                if (keys.contains(key)) { result.add(rb.getString(key)); }
                for (int i = 0; true; i++) {
                    String elementKey = key + "." + i;
                    if (keys.contains(elementKey)) {
                        result.add(rb.getString(elementKey));
                    } else {
                        return result;
                    }
                }
            }
            /** Returns the ResourceBundle of the specified Messages object or {@code null} if the specified Messages object is {@code null}.
             * @since 4.0 */
            public static String resourceBundleBaseName(Messages messages) { return messages == null ? null : messages.resourceBundleBaseName(); }
            /** Returns the ResourceBundle of the specified Messages object or {@code null} if the specified Messages object is {@code null}. */
            public static ResourceBundle resourceBundle(Messages messages) { return messages == null ? null : messages.resourceBundle(); }
            /** Returns the base name of the ResourceBundle of this object or {@code null}.
             * @since 4.0 */
            public String resourceBundleBaseName() { return bundleBaseName; }
            /** Returns the ResourceBundle of this object or {@code null}. */
            public ResourceBundle resourceBundle() { return rb; }
            /** Returns the CommandSpec of this object, never {@code null}. */
            public CommandSpec commandSpec() { return spec; }
        }
```

Any other ideas or suggestions for improvement? Next up would be to develop associated unit tests, not sure when I'll have time for that though.
