### ISSUE TITLE
Convert enum snake_case to and from kebab-case.

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#1707]
I'm getting ready to add an [enum option](https://picocli.info/#_enum_types) to my CLI, and it would have values like `FOO_BAR`. I could define this enum in a non-best-practices approach as lowercase `foo_bar` so users wouldn't be required to enter values in uppercase. Or I could use `setCaseInsensitiveEnumValuesAllowed()`, as also discussed in #556.

But either way sidesteps what I really want. We're talking about two "compound tokenization" systems. One is "UPPER_SNAKE_CASE" tokenization. The other is "lower-kebab-case" tokenization. I don't want case sensitivity or case insensitivity. I want to define my enum in `UPPER_SNAKE_CASE`, but have my users enter the value in `lower-kebab-case`. In particular case insensitivity doesn't address the use of `_` versus `-`. (What I'm referring to is nothing strange; things like angular.js and many other frameworks regularly convert between `kebab-case` for HTML attributes and `camelCase` for JavaScript identifiers.)

To better see what I'm talking about, see my [`CompoundTokenization` classes](https://github.com/globalmentor/globalmentor-base/blob/master/core/src/main/java/com/globalmentor/lex/CompoundTokenization.java). It works something like this:

```
String uiName = CompoundTokenization.SNAKE_CASE.toKebabCase(enum.name().toLowercase());
String enumName = CompoundTokenization.KEBAB_CASE.toSnakeCase(uiName).toUppercase();
```

See also Guava's [`CaseFormat`](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/base/CaseFormat.html). See also Jackson's [`PropertyNamingStrategy.SnakeCaseStrategy`](https://fasterxml.github.io/jackson-databind/javadoc/2.8/com/fasterxml/jackson/databind/PropertyNamingStrategy.SnakeCaseStrategy.html).

I could limp along using `setCaseInsensitiveEnumValuesAllowed()` as a blunt tool (even though it would force me to allow allow `fOoBAr`, which isn't ideal), but there's no way I can work around the current implementation to allow the user to enter a compound token such as `foo-bar`, is there? I don't want them to enter `foo_bar`. Why? Because it's not the convention, and reflects a limitation of the underlying implementation and not a choice based on UI best practices.

Thanks for your time in reading and considering this.

**Comment by remkop** [comment]
Hi @garretwilson, good to hear from you.
I see the value of what you are proposing, and I would not object to such an enhancement, if someone is willing to do the work of providing a PR with implementation, tests and documentation. I do have some questions.

### Enhancing the library

When it comes to enhancing the library, some questions come to mind:
* Would this snakeCase-to-kebabCase conversion feature be useful for enum values only, or would it also be valuable for option names and/or subcommand names?
* Would it be useful to allow abbreviated enum values, similarly to how picocli can [recognize abbreviated subcommands and option names](https://picocli.info/#_abbreviated_options_and_subcommands)? Some enum constants can be very long, which is fine in code (given IDE code completion etc) but less user-friendly on the command line.
* Some applications may want to be lenient with some conversion but strict in others, like you mention you want to allow `foo-bar` (and I am guessing `FOO_BAR`) but not `fOoBAr` or `foo_bar`. How to allow for such fine-grained control?

### Application-level customization

Note that you should be able to achieve your exact requirements (including disallowing `fOoBAr` and `foo_bar` but allowing  `foo-bar` and `FOO_BAR` and maybe even `fB`) by creating a custom `ITypeConverter`, and use that type converter for the options that accept that enum value as a parameter. 
Depending on your requirement perhaps a `String.replaceAll("-", "_")` is sufficient, perhaps I should consider making picocli's `AbbreviationMatcher` class public to allow people with more complex requirements...

**Comment by garretwilson** [comment]
> Would this snakeCase-to-kebabCase conversion feature be useful for enum values only, or would it also be valuable for option names and/or subcommand names?

Well option names are free-form in a Java string, so the developer can specify anything they want, right? But yeah, subcommand names (if formed from methods, for example) are a candidate for a conversation—specifically a camelCase to kebab-case conversion. Basically I think that everything on the command line (flags, options, parameter values, etc.) should be using lower kebab-case.

> Some applications may want to be lenient with some conversion but strict in others, like you mention you want to allow foo-bar (and I am guessing FOO_BAR) but not fOoBAr or foo_bar

No, I don't want to allow `FOO_BAR`. That's an implementation detail in the programming language. The interface (the "I" in the "CLI" uses `foo-bar`—nothing more, nothing less. The CLI could be implemented in assembly language, for all I care. The fact that it uses Java with some Java-specific naming conventions and restrictions for Java enums should not be visible or affect the C-L-Interface in any way.

> Note that you should be able to achieve your exact requirements … by creating a custom `ITypeConverter`, and use that type converter for the options that accept that enum value as a parameter.

Oh, that's cool. Thanks for the suggestion. I may just implement that in the GlobalMentor base `AbstractApplication` (on top of picocli) that takes care of all these conveniences. I assume it would automatically apply to all enums, and I wouldn't have to manually specify it in each subcommand/option/whatever?

> Depending on your requirement perhaps a `String.replaceAll("-", "_")` is sufficient in your type converter …

Well since I spent days (partly on a long flight, if I remember correctly) implementing a full suite of `SNAKE_CASE`, `camelCase`, `PascalCase`, and `kebab-case` conversions (with full unit tests and extensive documentation) as mentioned in the description, I'll skip `String.replaceAll()` and just use that. 😅 hehe

**Comment by garretwilson** [comment]
I just looked into `ITypeConverter`, and unless I'm misunderstanding it, it appears that I would have to create a separate converter for each enum type! 😢 I just want to register a single converter and say, "use this converter whenever you're converting from a string to any enum type".

It's a shame that `ITypeConverter` doesn't look like this:

```
public interface ITypeConverter<K> {
  K convert(String value, Class<K> toType) throws Exception;
 }
```

Then I could just make sure `toType` is a type of `Enum<?>`, and then return e.g. `((Enum<?>)toType).valueOf(KEBAB_CASE.toSnakeCase(uiName).toUppercase())`, giving me the correct enum type without creating a separate converter for each of them.

In fact this signature would be useful in general, as I could imagine several use cases for creating a single converter implementation that supports different output types. I see that there is a `registerConverter(Class<K> cls, ITypeConverter<K> converter)` that allows me to register a single converter for the entire `Enum<?>` hierarchy, but I think the problem is that the converter wouldn't know at conversion type which type of enum it should be producing.

Does any other entry point exist to allow me to implement a general string-to-enum converter in my `BaseCliApplication` base class?

**Comment by remkop** [comment]
I don't think you need to create a separate type converter class for each target enum type, but yes, you will need to create a separate converter instance for each target enum type. 

Something like:

```java 
registerConverter(MyEnum1.class, new MyConverter(MyEnum1.class));
registerConverter(MyEnum2.class, new MyConverter(MyEnum2.class));
//... 
```

I see your point about the signature of `ITypeConverter`,
but I like the simplicity of the current signature and the penalty for your use case doesn't seem too horrible. 😅

**Comment by remkop** [comment]
I forgot to answer your question about alternative ways to deal with this. 

There is one: you can create a custom parameter preprocessor or parameter consumer:
https://picocli.info/#_custom_parameter_processing

(If it was me I would probably choose the type converter idea, but please take a look.)

**Comment by garretwilson** [comment]
> the penalty for your use case doesn't seem too horrible

We have a single `BaseCliApplication`. All our CLI applications extend this. Once `MyBrandNewCli` is created and extends the base class, I don't want developers to have to have to register something additional just because they used an enum (and using an enum is encouraged over a plain string for obvious reasons). So yes an extra registration for every single enum type (which should technically be completely unnecessary) is a pretty big penalty over "do nothing extra".

Think about it this way: what if we had to manually call the following method every time we used an integer argument?

```
registerConverter(Integer.class, new IntConverter());
```

You could say, "oh, but you don't have to actually write a new integer converter—you just need to register it each time you use an `int` parameter". Would it seem reasonable to say "the penalty for your use case doesn't seem too horrible"? I don't think so. It would seem pretty horrible. Why should the analysis be any different with enums than with integers?

But I'll look into the custom parameter processor, thanks.

**Comment by garretwilson** [comment]
> I like the simplicity of the current signature

But you can have it both ways. Just add this to `ITypeConverter`:

```
default K convert(String value, Class<K> toType) throws Exception {
  return toType.cast(convert(value));
}
```

Then modify picocli to call `convert(value, type)` instead of `convert(value)`. (I would imagine picocli knows the expected type at this point.)

* All existing implementations of `ITypeConverter` work 100% like they did before with no modifications.
* If a developer cares about the type, they can use the new method. Everyone else can ignore it.
* You get the benefit that the code checks early for the correct type in existing `ITypeConverter.convert(value)` implementations. (I don't know how much of an improvement this is, but surely it is net positive.)

This is not a huge issue for me right at this very moment. I'm merely responding to your comments because the suggestion seems to easy and useful with no downsides I'm having trouble understanding why anyone wouldn't want it.

Have a great week.

**Comment by remkop** [comment]
It is a good suggestion if we were to require Java 8, but I want to continue to support picocli for Java 5+ users so unfortunately we cannot use default methods in interfaces.

**Comment by garretwilson** [comment]
I see; I had forgotten the Java 5 requirement. And I completely understand where you're coming from, and I share the sentiment in theory, but sincerely I think in 2022 you're doing more harm that good. As you know Java 8 was really the start of the modern Java era; even that is not supported anymore for the most part. Java 11 wast the last LTS; that has come and gone. The latest LTS is 17, which has been released. Sure, many people are still using Java 11, but even huge products such as Hadoop which are stuck in the "dark ages" still [at least support Java 8](https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+Java+Versions).

If there is some project stuck on pre-8 Java, they probably won't be using a modern CLI library like picocli. If they are, picocli dropping Java 5/6/7 support might be the final straw that finally convinces the project to move to Java 8. And that would be a good thing for everybody. (No really. The more people still using ancient Java versions hurts us all. Just like people who were still using IE 6. If you remember that, you understand what I'm talking about.)

Do you know for a fact that someone is actually using picocli with Java 5?

**Comment by remkop** [comment]
> I see; I had forgotten the Java 5 requirement. (...)

I am not willing to be convinced on this, sorry about that.

Circling back, I think we have found a way to allow users to enter a tokens such as `foo-bar` and have those be matched with enum values like `FOO_BAR`, which solves the original problem. 
The solution may not be perfect, but it's better than no solution. 😉 

I will close this ticket for now, let me know if there's anything else I can help with.

**Comment by garretwilson** [comment]
>  … you can create a custom parameter preprocessor or parameter consumer:
https://picocli.info/#_custom_parameter_processing

I'm not quite getting this. All the examples for `IParameterPreprocessor` show that I need to explicitly set a `preprocessor` or `parameterConsumer` value in the definition of a particular e.g. `@Option`. How can I install a some sort of processor for _all_ enum values?

Basically I want to install _a single time in a base class_ some processing for all `Enum` based values, as I do for `Duration` in #1800. But as we discussed above  we can't use `ITypeConverter` for this, because picocli doesn't pass the type (the `Enum` subclass) of the `@Option`. But I don't see how `IParameterConsumer` or `IParameterPreprocessor` can be installed globally.

If there is a workaround, I'll do the work to implement it. But are you saying that there is no workaround for me to implement a general converter for all enum types?

**Comment by garretwilson** [comment]
If I could somehow override `getActualTypeConverter(final Class<?> type, ArgSpec argSpec)`, then I could skip the `converterRegistry` altogether and create an `ITypeConverter<>` on the fly for each enum type specified by `type`. But unfortunately `getActualTypeConverter()` is `private`. 😦 

Maybe you could add a "hook" that `getActualTypeConverter()` calls. Thus I could register a global `ITypeConverterFactory` which would preprocess the type converter lookup before the registry even becomes involved.

That would give us something like this:

```java
private ITypeConverter<?> getActualTypeConverter(final Class<?> type, ArgSpec argSpec) {
     ITypeConverter<?> typeConverter = typeConverterFactory.convert(type, argSpec);
     if(typeConverter!=null) {
               return typeConverter;
     }
    if (char[].class.equals(argSpec.type()) && argSpec.interactive()) { return converterRegistry.get(char[].class); }
    if (converterRegistry.containsKey(type)) { return converterRegistry.get(type); }
    …
}
```

In fact, you could just move all existing logic from `getActualTypeConverter()` into the default `ITypeConverterFactory`! If I wanted to add my own preprocessing, I could merely add the creation of the enum  `ITypeConverter`, and then for non-enum values I could delegate to the original `ITypeConverterFactory` (which would contain basically the code currently inside `getActualTypeConverter()`. This would be simple to do and very clean. (It wouldn't be as good as my suggestion above to simply improve the `ITypeConverter` interface, but it would be almost as good.)

**Comment by garretwilson** [comment]
While my last suggest above is good for general cases, if we only concentrate on my current need (converting enums), then I see that you have this:

```java
private ITypeConverter<Object> getEnumTypeConverter(final Class<?> type)
```

Unfortunately there's no way for me to override that, either. 😢

And I noted that you actually call this method explicitly if there is no registered converter, passing the type!

```java
if (type.isEnum()) {
  return getEnumTypeConverter(type);
}
```

So you must have already realized when you were writing the code that there was a problem with the conversion interface model (i.e. not providing a type to the converter at conversion time).

If if enums are the only thing that need to know the type at conversion time (I doubt it), I still need way to patch in my custom conversion to override the dynamic creation you do inside `getEnumTypeConverter()`.

Let me put it another way: from the perspective of API design, if it was valid for the library implementor to need to call `getEnumTypeConverter(final Class<?> type)` and create the enum converter separately, it's not unreasonable that a user might want the same functionality to effect the same conversion but in a different manner.
