### ISSUE TITLE
ArgGroup validation fails when only defaultValues are specified

### ISSUE THREAD

**Issue by siilike** [remkop/picocli#1718]
From #844.
```
class TestCmd
{
	@CommandLine.ArgGroup(exclusive = true, multiplicity = "1")
	GroupOpts group = new GroupOpts()

	static class GroupOpts
	{
		@CommandLine.Option(names = ["--test1"], defaultValue = '${env:TEST}')
		String test1

		@CommandLine.Option(names = ["--test2"], defaultValue = '${env:TEST2}')
		String test2
	}
}

def cmd = new CommandLine(...).addSubcommand(TestCmd.class)

cmd.parseArgs(args)
```
When TEST and/or TEST2 environment variables have been defined, the validation fails:
```
picocli.CommandLine$MissingParameterException: Error: Missing required argument (specify one of these): ([--test1=<test1>] | [--test2=<test2>])
	at picocli.CommandLine$Model$ArgGroupSpec.validate(CommandLine.java:10552)
	at picocli.CommandLine$Model$ArgGroupSpec.access$19300(CommandLine.java:10126)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.validate(CommandLine.java:12659)
	at picocli.CommandLine$ParseResult.validateGroups(CommandLine.java:12303)
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13252)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13200)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13468)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13374)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13177)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13146)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13047)
	at picocli.CommandLine.parseArgs(CommandLine.java:1478)
	at Test.createCommandLine(Test.groovy:281)
	at Test.executeResult(Test.groovy:324)
	at Test.main(Test.groovy:370)
```
In GroupMatchContainer.validate() the group is treated as an unmatched subgroup:
```
                for (ArgGroupSpec missing : unmatchedSubgroups) {
                    if (missing.validate() && missing.multiplicity().min > 0) {
                        int presentCount = 0;
                        boolean haveMissing = true;
                        boolean someButNotAllSpecified = false;
                        String exclusiveElements = missing.synopsisUnit();
                        String missingElements = missing.synopsisUnit(); //ArgSpec.describe(missing.requiredArgs());
                        validationResult = missing.validate(commandLine, presentCount, haveMissing, someButNotAllSpecified, exclusiveElements, missingElements, missingElements);
                    }
                }
```
and in that case `haveMissing` is always set to `true` which causes validate() to fail. Instead, it should check whether any of the arguments has a default value and set `haveMissing = false` in that case.

Log with TEST=test and TEST2=test2:
```
[picocli DEBUG] Applying default values for group '([--test1=<test1>] | [--test2=<test2>])'
[picocli DEBUG] Applying defaultValue (test) to field String Test$GroupOpts.test1 on GroupOpts@13579834
[picocli DEBUG] 'test' doesn't resemble an option: 0 matching prefix chars out of 18 option names
[picocli INFO] Setting field String Test$GroupOpts.test1 to 'test' (was 'null') for field String Test$GroupOpts.test1 on GroupOpts@13579834
[picocli DEBUG] Applying defaultValue (test2) to field String Test$GroupOpts.test2 on GroupOpts@13579834
[picocli DEBUG] 'test2' doesn't resemble an option: 0 matching prefix chars out of 18 option names
[picocli INFO] Setting field String Test$GroupOpts.test2 to 'test2' (was 'null') for field String Test$GroupOpts.test2 on GroupOpts@13579834
```
There are a few issues:
1. in case both TEST and TEST2 are defined, both fields are set, but this should not happen
2. the previous might also apply when one field has a default and the other one is set via an argument

**Comment by remkop** [comment]
@siilike Thank you for raising this, apologies for the delay. I am looking into this.

**Comment by siilike** [comment]
The use case is that there are several required mutually exclusive options (e.g. name or ID, encryption or signing key) which can be defined via the command line or via environment variables. Validation and exclusivity are a must.

Currently I use it as a way to load common configuration, so it could likely be replaced by @-files, but then there is no way to override the options. I currently don't need this, but someone using the program might.

Another issue is that for exclusive options only one of them should ever be set, even if they have a default defined. Otherwise it is not possible to detect which one has been defined and can cause unexpected behaviour. Currently if you run `TEST2=123 program --test1=123` both fields would be set.

Also, I was thinking that it would be great if there would be a way to validate options after everything has been injected. For example:
```
class TestCmd
{
	@CommandLine.ArgGroup(exclusive = true, multiplicity = "1")
	GroupOpts group = new GroupOpts()

	static class GroupOpts
	{
		@CommandLine.Option(names = ["--test1"], defaultValue = '${env:TEST}')
		String test1

		@CommandLine.Option(names = ["--test2"], defaultValue = '${env:TEST2}')
		String test2

                @Validate
                void validate()
                {
                        // called after test1 or test2 has been set
                } 
	}
}
```
Then the additional validation wouldn't have to be called manually which would be especially nice with groups and mixins. It could be done by defining setters, but that would be very verbose. This would also provide an easy way to resolve the environment variables issue by doing the validation manually:
```
class TestCmd
{
	@CommandLine.ArgGroup
	GroupOpts group = new GroupOpts()

	static class GroupOpts
	{
		@CommandLine.Option(names = ["--test1"], defaultValue = '${env:TEST}')
		String test1

		@CommandLine.Option(names = ["--test2"], defaultValue = '${env:TEST2}')
		String test2

                @Validate
                void validate()
                {
                        // throws when both defined or both missing
                        Utils.validateExclusiveRequired([ '--test1', test1 ], [ '--test2', test2 ])
                } 
	}
}
```

**Comment by remkop** [comment]
Everything you are describing should be possible with the current version of picocli,
however, you may need to do some validation in the application.

> The use case is that there are several required mutually exclusive options (e.g. name or ID, encryption or signing key) which can be defined via the command line or via environment variables. Validation and exclusivity are a must.

Understood; you will need to decide in your application what to do when the end user has defined environment variables for both options in an exclusive group.

> Currently I use it as a way to load common configuration, so it could likely be replaced by @-files, but then there is no way to override the options. I currently don't need this, but someone using the program might.

An alternative may be to use [PropertiesDefaultProvider](https://picocli.info/#_propertiesdefaultprovider) for common defaults. (These are still user-editable, by the way.)

> Another issue is that for exclusive options only one of them should ever be set, even if they have a default defined. Otherwise it is not possible to detect which one has been defined and can cause unexpected behaviour. Currently if you run `TEST2=123 program --test1=123` both fields would be set.

Yes, exactly. Picocli will only validate what is specified on the command line, and I believe the current behaviour is correct.
So, if the end user specifies two options _on the command line_ that are mutually exclusive, then picocli will show an error. 

To find out which options were specified on the command line (as opposed to values that were assigned a default value), you can use the `ParseResult`. Alternatively, you can simply not assign a default value in the annotations (or in the DefaultProvider), but simply get environment variables in the business logic of your application, rather than relying on the picocli library to assign defaults before your business logic is run.

> Also, I was thinking that it would be great if there would be a way to validate options after everything has been injected. For example:
> 
> ```
> class TestCmd
> {
> 	@CommandLine.ArgGroup(exclusive = true, multiplicity = "1")
> 	GroupOpts group = new GroupOpts()
> 
> 	static class GroupOpts
> 	{
> 		@CommandLine.Option(names = ["--test1"], defaultValue = '${env:TEST}')
> 		String test1
> 
> 		@CommandLine.Option(names = ["--test2"], defaultValue = '${env:TEST2}')
> 		String test2
> 
>                 @Validate
>                 void validate()
>                 {
>                         // called after test1 or test2 has been set
>                 } 
> 	}
> }
> ```
>
> Then the additional validation wouldn't have to be called manually which would be especially nice with groups and mixins. It could be done by defining setters, but that would be very verbose. This would also provide an easy way to resolve the environment variables issue by doing the validation manually:
> 
> ```
> class TestCmd
> {
> 	@CommandLine.ArgGroup
> 	GroupOpts group = new GroupOpts()
> 
> 	static class GroupOpts
> 	{
> 		@CommandLine.Option(names = ["--test1"], defaultValue = '${env:TEST}')
> 		String test1
> 
> 		@CommandLine.Option(names = ["--test2"], defaultValue = '${env:TEST2}')
> 		String test2
> 
>                 @Validate
>                 void validate()
>                 {
>                         // throws when both defined or both missing
>                         Utils.validateExclusiveRequired([ '--test1', test1 ], [ '--test2', test2 ])
>                 } 
> 	}
> }
> ```


Regarding [validation](https://picocli.info/#_validation), my recommendation is that applications do custom validation in the beginning of the business logic. I have given it much thought and I do not see how picocli can add much value by creating a framework for this.

**Comment by remkop** [comment]
@siilike Were you able to work around picocli's limitations and get your application to work the way you want to?

**Comment by remkop** [comment]
Very nice! I think this is a great example of using the `IExecutionStrategy` framework to plug in your own validation framework.

I see your point that this validation framework would be generally useful, but at the moment I am not considering adding validation to the library (I think the role of picocli is to provide extension points that allow applications to plug in their own validation).

**Comment by remkop** [comment]
@siilike Are you okay with closing this ticket, or is there more work to do?

**Comment by remkop** [comment]
I see...
Would it be useful if there was a method that returned the [IAnnotatedElement](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Model.IAnnotatedElement.html) for the arg group?

I can see how this would be useful in some cases.
I created https://github.com/remkop/picocli/issues/1746 for this.
