### ISSUE TITLE
Application Output Color

### ISSUE THREAD

**Issue by ahmedsaheed** [remkop/picocli#1724]
Hi,

> First, this library is exceptional!

But i have a question about the coloration.
Given a non static String, how can i call that String variable in `Ansi.AUTO.string`
```java
JSONObject jsonObject = new JSONObject(makeRequest(url));
JSONObject data = jsonObject.getJSONObject("data");
String names = data.getString("name");
//like so
String NAME = Ansi.AUTO.string("@|bold,blue,underline names|@")
```

When i do this i get `name` printed. But i would like to print the variable stored name instead

**Comment by remkop** [comment]
The easiest is to just do string concatenation:

```java
Ansi.AUTO.string("@|bold,blue,underline " + names + "|@")
```

**Comment by ahmedsaheed** [comment]
I Absolutely forgot about something that little. Thanks a ton!

**Comment by remkop** [comment]
Great, glad to hear that was useful! 👍 
Enjoy!
