### ISSUE TITLE
Missing required parameters error (error)

### ISSUE THREAD

**Issue by ashr123** [remkop/picocli#1734]
When I define parameters that I want to be required only for the main command but not in the sub command I still get `Missing required parameters` error:
```java
@CommandLine.Command(name = "java -jar hash-verifier.jar",
		mixinStandardHelpOptions = true,
		versionProvider = HashVerifier.class,
		description = "Verify file's hash with given hash.")
public class HashVerifier implements Runnable, CommandLine.IVersionProvider
{
	@CommandLine.Parameters(converter = MessageDigestConverter.class,
			description = "Which hash algorithm to use? (values: md2, md5, sha1, sha256, sha384, sha512, sha3-224, sha3-256, sha3-384, sha3-512)")
	private MessageDigest algorithm;
	@CommandLine.Parameters(converter = PathConverter.class,
			description = "Path to file for digestion.")
	private Path pathToFile;
	@CommandLine.Parameters(description = "Hash string to verify against.")
	private String hash;

	public static void main(String... args)
	{
		new CommandLine(HashVerifier.class).execute(args);
	}

	@CommandLine.Command(mixinStandardHelpOptions = true,
			versionProvider = HashVerifier.class,
			showDefaultValues = true,
			description = "Generates hash from file according to given hash algorithm.")
	public void generateHashFromFile(
			@CommandLine.Parameters(converter = MessageDigestConverter.class,
					description = "Which hash algorithm to use? (values: md2, md5, sha1, sha256, sha384, sha512, sha3-224, sha3-256, sha3-384, sha3-512)")
			MessageDigest algorithm,
			@CommandLine.Parameters(converter = PathConverter.class,
					description = "Path to file for digestion.")
			Path pathToFile
	)
	{
		System.err.println("Generating hash...");
		try
		{
			System.out.println(HexFormat.of().formatHex(algorithm.digest(Files.readAllBytes(pathToFile))));
		} catch (IOException e)
		{
			//noinspection ThrowablePrintedToSystemOut
			System.err.println(e);
		}
	}

	@Override
	public void run()
	{
		System.err.println("Starting hash verification...");
		try
		{
			System.out.println(MessageDigest.isEqual(
					algorithm.digest(Files.readAllBytes(pathToFile)),
					HexFormat.of().parseHex(hash)
			));
		} catch (IOException e)
		{
			//noinspection ThrowablePrintedToSystemOut
			System.err.println(e);
		}
	}
}
```
I think (at least in my opinion) that it should work, instead I get

> ```
> Missing required parameters: '<algorithm>', '<pathToFile>', '<hash>'
> Usage: java -jar hash-verifier.jar [-hV] <algorithm> <pathToFile> <hash>
>                                    [COMMAND]
> Verify file's hash with given hash.
>       <algorithm>    Which hash algorithm to use? (values: md2, md5, sha1,
>                        sha256, sha384, sha512, sha3-224, sha3-256, sha3-384,
>                        sha3-512)
>       <pathToFile>   Path to file for digestion.
>       <hash>         Hash string to verify against.
>   -h, --help         Show this help message and exit.
>   -V, --version      Print version information and exit.
> Commands:
>   generateHashFromFile  Generates hash from file according to given hash
>                           algorithm.
> ```
Why do I get this error?

**Comment by remkop** [comment]
How do you invoke the program when you get that output?

**Comment by remkop** [comment]
Oh I see:
If you make positional parameters required, they are required, whether a subcommand is specified or not. 

If you want positional parameters (or options for that matter) to be required under some circumstances but not always then the application needs to do the validation. 

You can accomplish this by throwing a MissingParameterException from the `run` method of the top-level command. (See https://picocli.info/#_validating_option_combinations)

**Comment by remkop** [comment]
> So the only way to fully separate those commands is to make them both sub-commands?

Separate subcommands is one way, yes.

The other way is to make them optional in the top-level command (with `arity = "0..1"`) and do validation in the `run` method:

```
@Spec CommandSpec spec;

public void run() {
    if (algorithm == null || pathToFile == null || hash == null) {
        throw new MissingParameterException(spec.commandLine(), spec.positionalParameters(), 
                "The algorithm, pathToFile and hash parameters are required for the HashVerifier command.");
        // or 
        // throw new ParameterException(spec.commandLine(), 
                "The algorithm, pathToFile and hash parameters are required for the HashVerifier command.");
    }

    // remaining business logic...
}
```

> Is there a way to make `algorithm` and `pathToFile` like general parameters and `hash` relevant to only one of the sub-commands (for reuse purposes)?

When you say "general parameters", you mean that they apply to every subcommand? 

* One way to do that is to use [inherited scope](https://picocli.info/#_inherited_scope). This is most often used for options but it may also work well for positional parameters, give it a try...
* Another way to reuse options and parameters is with [mixins](https://picocli.info/#_mixins). That gives you more control in case not each and every subcommand should inherit those options.

**Comment by ashr123** [comment]
@remkop I'll try it, thanks

**Comment by remkop** [comment]
Hi @ashr123, have you been able to find a solution? Can this ticket be closed?

**Comment by ashr123** [comment]
I didn't try your suggestion, I went with the solution of 2 sub-commands and comand that doesn't extends anything

**Comment by remkop** [comment]
Okay great!
I’ll close this ticket then.
