### ISSUE TITLE
Subcommand overrides option value set in parent command with default value

### ISSUE THREAD

**Issue by xtaixe** [remkop/picocli#1735]
Hi. We are currently not using inherited options and because we are using Picocli through Quarkus we are sharing options between command and subcommands by making them a `@Singleton` (which should be equivalent to having them on a static field but then they can be injected).So we have something like this:

```java
@Singleton
public class MyOption {
    @Option(names = "-m", defaultValue = "default", description = "My option")
    String my;
}
```

then both the parent and the subcommand have the following:

```java
@Mixin
@Inject
MyOption myOption;
```

When sub command is called with the option specified in the parent, the option value is overwritten with the default:

```shell
command -m bla subcommand # Value of MyOption.my is 'default' instead of `bla`
```

I don't know if this affects inherited options or other ways of sharing (e.g. static fields), but I guess in this case Picocli is only checking if the options are defined on the children before setting the default value. Could Picocli also check if the value is already set and if it is don't set the default value?

**Comment by remkop** [comment]
Apologies for my late reply; this slipped off my inbox horizon...

That is a tricky one...
Picocli parses the parameters one by one, so first `-m` and `bla` (resulting in MyOption.my having the value "bla"), then `subcommand`, and when no further parameters are detected, picocli will assign default values for the options of `subcommand`. This last step is where MyOption.my is reset to the default value.

One idea is to implement the `-m` option as am `@Option`-[annotated setter method](https://picocli.info/#option-parameters-methods) instead of a field. That would allow you to implement the logic you requested:

> Could Picocli also check if the value is already set and if it is don't set the default value?

```java
@Singleton
public class MyOption {
    String my;
    @Option(names = "-m", defaultValue = "default", description = "My option")
    void setMy(String newValue) {
        if (my != null && !"default".equals(newValue)) {
            this.my = newValue;
        }
    }
}
```

**Comment by xtaixe** [comment]
I see... I thought that using the setter could be a workaround, but it's a bit annoying, since there's only one place where we need a default value and it would be inconsistent with the rest of the code that doesn't use setters...

Would this also happen with inherited options? If not I might look into switching to them...

**Comment by remkop** [comment]
If there is only one place where you need special behaviour, then doesn't it make sense that the code for that one place looks different...? 😅 

I think using a setter for this is fine. 👍 

I will go ahead and close this ticket, but feel free to let me know if it needs to be reopened.

**Comment by xtaixe** [comment]
> If there is only one place where you need special behaviour, then doesn't it make sense that the code for that one place looks different...?

Well it's about cognitive load, having to add comments to explain the behavior very precisely, etc. because deviating from the norm usually means tricky edge cases, for example, with your setter if the user is explicitly setting the default value in the children, it will be ignored... Is that the right thing to do? Should we give an error? So, lots of question I'd rather not deal with...

I understand our usage with Quarkus might not be directly supported, so closing is fine, but could you let me know if you think this should work properly with inherited options? If it doesn't, then I think there's still a bug, but it could be tracked in a new issue.
