### ISSUE TITLE
Allowing subcommands as first parameter only

### ISSUE THREAD

**Issue by lpellegr** [remkop/picocli#1744]
Let's say you have a top level command _mycommand_ and multiple subcommands like _subcommand1_ and _subcommand2_.

What I am trying to achieve is to allow the top level command _mycommand_ to be invoked with 0 or more parameters without subcommands but if a subcommand is used, then only one is allowed and only as the first parameter of the top-level command.

Invoking only the top level commands with non subcommand parameters is working well. However, after reading the docs I cannot figure out how to limit the number of subcommands to 1 and ensure that the subcommand name, if there is one, is passed as the first parameter of the top level command.

For instance, what I would like to allow:

```bash
$ mycommand
$ mycommand 1
$ mycommand 1 2 3 4
$ mycommand subcommand1 1 2
$ mycommand subcommand2 1
```

However, this must not be possible:

```bash
$ mycommand 1 subcommand1 1 2
$ mycommand 1 2 subcommand2 1
$ mycommand 1 2 3 subcommand2 1
$ mycommand subcommand1 1 2 subcommand1 1 2
$ mycommand 1 subcommand2 1 subcommand2 1
```

Is it possible to force subcommands to be used only once in the commands hierarchy and as the first parameter of another command?

**Comment by remkop** [comment]
Hi @lpellegr sure that is possible.
You just need to do a bit of [validation](https://picocli.info/#_custom_validation) in the application.

Below is a simple example that I believe meets your requirements:

```java
@Command(name = "myapp", mixinStandardHelpOptions = true, version = "1.0")
static class Issue1744App implements Runnable {
    @Spec CommandSpec spec;

    @Parameters
    List<Integer> positionalParams;

    public void run() {
        System.out.printf("Top-level command was run with %s%n", positionalParams);
    }

    @Command
    public void subcommand1(@Parameters List<Integer> sub1Params) {
        if (this.positionalParams != null) {
            throw new ParameterException(spec.commandLine(),
                "Parameters must follow subcommand1, cannot precede it");
        }
        System.out.printf("subcommand1 was run with %s%n", sub1Params);
    }

    @Command
    public void subcommand2(@Parameters List<Integer> sub2Params) {
        if (this.positionalParams != null) {
            throw new ParameterException(spec.commandLine(),
                "Parameters must follow subcommand2, cannot precede it");
        }
        System.out.printf("subcommand2 was run with %s%n", sub2Params);
    }
}
```

The below tests pass, so I think that may be a start for you?

```java
@Test
public void testIssue1744() {
    CommandLine cmd = new CommandLine(new Issue1744App());
    assertEquals(0, cmd.execute()); // no params
    assertEquals(0, cmd.execute("1")); // one params
    assertEquals(0, cmd.execute("1", "2", "3", "4")); // multiple params
    assertEquals(0, cmd.execute("subcommand1", "1", "2")); // subcommand and its params
    assertEquals(0, cmd.execute("subcommand2", "1")); // subcommand and its params

    //now test that the below are rejected by validation (non-zero exit code)
    assertEquals(2, cmd.execute("1", "subcommand1", "1", "2"));
    assertEquals(2, cmd.execute("1", "2", "subcommand2", "1"));
    assertEquals(2, cmd.execute("subcommand1", "1", "2", "subcommand1", "1", "2"));
    assertEquals(2, cmd.execute("1", "subcommand2", "1", "subcommand2", "1"));
}
```

**Comment by remkop** [comment]
Note that you don't need to do anything to validate multiple subcommands:

```
mycommand subcommand1 1 2 subcommand1
```

The below would only be accepted by picocli if
* your app is using [repeatable subcommands](https://picocli.info/#_repeatable_subcommands) (very rare)
* you defined `subcommand1` to have its own subcommand, also named `subcommand1`, with code like `@Command(name = "subcommand1", subcommands = AnotherSubcommand1.class)`

Other than this, picocli would not recognize multiple subcommands and return a non-zero exit code and print an error message.

**Comment by lpellegr** [comment]
@remkop Thanks a lot for your clear answer. Picocli is very nicely designed! 

However, there is still one thing that is a bit obscure to me: my subcommands are defined in their own Java classes and the parent references them with `@Command(name = "mycommand", subcommands = {Subcommand1.class, Subcommand2.class)}`.

Is it possible to apply validation but without moving subcommands code into the parent command class?

**Comment by remkop** [comment]
You can reference objects in the command hierarchy with the `@Spec` annotation:

```java
class MySub implements Runnable {
  @Spec CommandSpec spec;

  public void run() {
    CommandLine top = spec.root();
    Issue1744App userObject = top.getCommand();
    if (userObject.positionalParameters == null) { throw ...
```

**Comment by lpellegr** [comment]
Fantastic. Thanks again!
