### ISSUE TITLE
Means to leverage picocli's terminal width detection.

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#1756]
It's a common need to detect the terminal width in Java—see [Can I find the console width with Java?](https://stackoverflow.com/questions/1286461/can-i-find-the-console-width-with-java) and fusesource/jansi#24, not to mention #634.

It appears that in #634 you wrote some awesome code in `detectTerminalWidth()` that detects the terminal width. I'm sure it's not perfect, as this is a hard thing to do, but it would probably be useful for me most of the time, defaulting to some reasonable value (like picocli does) if it can't be determined.

But `detectTerminalWidth()` is `private` inside `UsageMessageSpec`. 😢 All that code is so useful, abstracted away behind a single call. Could you please expose that so that my application can call `PicocliSomethingOrOther.detectTerminalWidth()` so I won't have to reinvent all this? Thank you!

**Comment by remkop** [comment]
Hi @garretwilson , this was recently discussed here: https://github.com/remkop/picocli/discussions/1753

Essentially, this can be accomplished with the existing API, as follows:

```java
CommandSpec spec = myCommandLine.getCommandSpec();
spec.usageMessage().autoWidth(true); // use terminal width
int width = spec.usageMessage().width(); // obtain the terminal width
```

**Comment by garretwilson** [comment]
Thanks for the quick response. So it looks like you're saying I have to turn on auto-width of picocli to be able to retrieve this information.

So will `spec.usageMessage().width()` always return the latest determined value? (I wasn't sure from the API docs.) That is, if I call it before and after resizing the console window, will I get different values?

Lastly is there any way to get the `CommandSpec` in use? Currently I run the application using `picocli`, but don't keep a reference to the `CommandSpec`. (Of course I could keep a reference around; I just wanted to check first for the options.)

```java
	/**
	 * {@inheritDoc}
	 * @implSpec This implementation uses picocli to execute the application using {@link CommandLine#execute(String...)}.
	 */
	@Override
	protected int execute() {
		final IExecutionExceptionHandler errorHandler = (exception, commandLine, parseResult) -> {
			reportError(exception);
			return EXIT_CODE_SOFTWARE;
		};
		//run the application via picocli instead of using the default version, which will call appropriate command methods as needed
		return new CommandLine(this).setExecutionExceptionHandler(errorHandler).execute(getArgs());
	}
```

**Comment by remkop** [comment]
> .... So it looks like you're saying I have to turn on auto-width of picocli to be able to retrieve this information.

That is what is available in the current version of picocli. I am open to pull requests to improve this.

> So will `spec.usageMessage().width()` always return the latest determined value? (I wasn't sure from the API docs.) That is, if I call it before and after resizing the console window, will I get different values?

The [UsageMessageSpec.width](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Model.UsageMessageSpec.html#width()) method goes and detects the terminal width if the spec's [autowidth](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Model.UsageMessageSpec.html#autoWidth()) is set to true (or when system property `picocli.usage.width` is set to `AUTO`). When autoWidth is false, the [explicitly set](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Model.UsageMessageSpec.html#width(int)) value or the default width is used.
(Of course, if you call `width()`, then resize the terminal, you will need to call `width()` again to get the latest value.)

> Lastly is there any way to get the `CommandSpec` in use? Currently I run the application using `picocli`, but don't keep a reference to the `CommandSpec`. (Of course I could keep a reference around; I just wanted to check first for the options.)

If you need to get a reference to the `CommandSpec` from inside a picocli command, then you can use the [`@spec` annotation](https://picocli.info/#spec-annotation), and picocli will inject the correct reference for you. The application could then pass it on to deeper layers of the business logic of the command.

**Comment by remkop** [comment]
I think we are good on this one too, closing this ticket.

**Comment by garretwilson** [comment]
There's still a tiny issue. If I call `spec.usageMessage().width()` as you mentioned, it's always going to return some value, even if it doesn't know the value, because it falls back to `DEFAULT_USAGE_WIDTH`.

```java
public int width() { return getSysPropertyWidthOrDefault(width == null ? DEFAULT_USAGE_WIDTH : width, autoWidth()); }
```

But what if I want to set my own default width?

And more important for my use case (I don't care so much what the picocli usage message width defaults to), if I'm wanting my application to be aware of the current width, I want to know whether picocli found a width, or if it doesn't know (in which case I'll choose my own default width, which may not be `80`). And I can't just check the return of `width()` and compare it to `DEFAULT_USAGE_WIDTH` to see if picocli actually found a width, because the terminal width may indeed be `80`!

Part of the problem here is that picocli imagines the auto-width mechanism to be only for the usage message, when in fact it should be a general query for a CLI application, with many use cases outside of merely the usage message. Thus `width()` should really be part of something more general such as `CommandLine`, and it should provide the ability to return some indication of "unknown" (e.g. `-1`). The `UsageMessageSpec.width()` should be calling this more general function. In fact you could even maintain current functionality by allowing `UsageMessageSpec.width()` to fall back to its current `DEFAULT_USAGE_WIDTH` (although in a perfect world that would be configurable at a higher level as well). The important thing is that `CommandLine.width()` could then be leveraged by the application as a whole (such as my `BaseCliApplication`) and decide on its own default as needed.

**Comment by remkop** [comment]
I see.
If your application uses the Jansi library, you may be interested to know that they support this: 
* v1.18: http://fusesource.github.io/jansi/documentation/native-api/org/fusesource/jansi/internal/CLibrary.WinSize.html
* v2.4: https://javadoc.io/doc/org.fusesource.jansi/jansi/latest/org/fusesource/jansi/io/AnsiOutputStream.WidthSupplier.html

**Comment by garretwilson** [comment]
> If your application uses the Jansi library, you may be interested to know that they support this:

Oh, interesting, I'll investigate!

It's nice that you found it. I had been [asking](https://github.com/fusesource/jansi/issues/24#issuecomment-1198670644) at fusesource/jansi#24 with no response.

**Comment by garretwilson** [comment]
So the Jansi version is actually available much more directly, using [`AnsiConsole.getTerminalWidth()`](https://javadoc.io/static/org.fusesource.jansi/jansi/2.4.0/org/fusesource/jansi/AnsiConsole.html#getTerminalWidth()). That delegates to the `stdout` wrapper class it has created, which delegates to the `AnsiOutputStream.WidthSupplier` you mentioned, which eventually calls a `Kernel32.GetConsoleScreenBufferInfo()` method which is a native method, directly calling a [Windows API](https://docs.microsoft.com/en-us/windows/console/getconsolescreenbufferinfo)! 🎉  This should be really efficient (and perhaps even more accurate) --- more than the picocli approach which spins up a separate process, sends ANSI sequences, and listens for responses.

So if I should switch to the Jansi version, can I leave auto-width off in picocli, but manually set the picocli width to what I get from Jansi?

**Comment by remkop** [comment]
Yes the picocli approach is much slower.
If you are using Jansi anyway, then why not go that route? Makes sense to me!

**Comment by garretwilson** [comment]
> If you are using Jansi anyway, then why not go that route? Makes sense to me!

Just FYI, this is now available in [`BaseCliApplication`](https://github.com/globalmentor/globalmentor-application/blob/master/src/main/java/com/globalmentor/application/BaseCliApplication.java) available on Maven Central as part of [`com.globalmentor:globalmentor-application:0.7.6`](https://search.maven.org/artifact/com.globalmentor/globalmentor-application/0.7.6/jar). Cheers!

**Comment by garretwilson** [comment]
Your tip on how to get the console with from Jansi was marvelous. As I mentioned I'm using it now, but I've just noticed a hiccup.

In the [BaseCliApplication](https://github.com/globalmentor/globalmentor-application/blob/master/src/main/java/com/globalmentor/application/BaseCliApplication.java) mentioned above, I have the main `execute()` code for my base application that does this:

```
//run the application via picocli instead of using the default version, which will call appropriate command methods as needed
this.commandLine = new CommandLine(this);
try {
  commandLine.setExecutionExceptionHandler(errorHandler);
  commandLine.registerConverter(Duration.class, Durations::parseUserInput);
  final int detectedTerminalWidth = System.out instanceof AnsiPrintStream ? ((AnsiPrintStream)System.out).getTerminalWidth() : 0;
  //set the picocli width manually because 1) Jansi's detection is faster and maybe more accurate; and 2) we have a different preferred default width
  commandLine.getCommandSpec().usageMessage().width(detectedTerminalWidth > 0 ? detectedTerminalWidth : DEFAULT_TERMINAL_WIDTH);
  return commandLine.execute(getArgs());
} finally {
  commandLine = null;
}
```

I have a new utility `foo` which I'm about to publish, and it has a subcommand `bar`. I did this:

```
foo --help`
```

I got the wide usage message as expected.

But then I did the following. (The `bar()` subcommand has `mixinStandardHelpOptions = true`.)

```
foo bar --help
```

The usage output for the subcommand wasn't wide like `foo --help`!

I confess I haven't dug into this (because I don't want to get distracted trying to do this release, creating the web page, setting up Maven publishing, etc.), but don't all the subcommands go through `commandLine.execute(getArgs())` just like for the main command? Shouldn't `commandLine.getCommandSpec().usageMessage().width()` apply to everything? Offhand I can't think of any other entry point that I'm using. Why would the behavior be different?

**Comment by remkop** [comment]
[CommandLine.setUsageHelpWidth](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.html#setUsageHelpWidth(int)) sets the width for the full hierarchy.

[CommandLine.Model.UsageMessageSpec.width](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Model.UsageMessageSpec.html#width(int)) sets the width for that specific command or subcommand.

Sounds like you want to use `CommandLine.setUsageHelpWidth`.

**Comment by garretwilson** [comment]
That seems to have done the trick. Thank you very much.
