### ISSUE TITLE
Get real path when forming parameters.

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#1758]
If I provide a `Path` parameter to picocli on Windows like `a:\foo.bar`, picocli gives me something back that is the equivalent to probably `Path.of("a:\\foo.bar")`. The problem is that the file is actually `A:\FOO.bar`. Due to the unfortunate decision of DOS to ignore path case eons ago, both will work, but for various reasons we want to use the canonical one, for example showing progress to users or outputting to file contents.

To solve this problem picocli should first call [`Path.toRealPath(NOFOLLOW_LINKS)`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toRealPath-java.nio.file.LinkOption...-) on any path it provides as parameters. This way the application will always be getting the "true" path.  (Don't forget to call [Files.exists`(NOFOLLOW_LINKS)`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#exists-java.nio.file.Path-java.nio.file.LinkOption...-) first; if the path does not exist, there is no "real" path, and no way to make it better unless you want to parse out the path components and find any existing base path and convert it to the real path, which might be useful and something I might write in the future.) I use `NOFOLLOW_LINKS` because you're just wanting to canonicize the path itself, irrespective of whether it points to anything.

For `File` I think you want to use [`File.getCanonicalFile()`](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getCanonicalFile--) (if the file exists).

The counterargument would be, "We want to know exactly what the user entered because this provides some value to the application." But I can't think of any use cases in which this would be valuable. If the user entered the integer string `"  1,234 "` obviously we want this normalized to the integer `1234`. Similarly if the path is really `A:\FOO.bar`, I can't think of any circumstances in which we would care to know they referred to some other case such as `a:\foo.bar` that is the same path as `A:\FOO.bar`. They are entering a path (not a string), so we want the canonical path. If we want them to enter something other than the true path and not have it normalized, we should ask for a string, not a path.

See discussion at e.g. [Get file case-sensitive name, with case-insensitive spelling](https://stackoverflow.com/questions/8750013/get-file-case-sensitive-name-with-case-insensitive-spelling).

**Comment by remkop** [comment]
I follow your reasoning, but I am not confident that this won't have unforeseen drawbacks.
I think for a generic library like picocli it is wise to follow the principle of least surprise, and use something very vanilla like `Path.of(String)`.

Applications with specialized needs can use a type converter with their exact requirements.

**Comment by garretwilson** [comment]
> I follow your reasoning, but I am not confident that this won't have unforeseen drawbacks.

Fair enough, but I thought I'd at least point it out. It's something I didn't think of when I wrote the CLI I'm working on now, but then now that I do think of it, I wish that all my other CLIs would normalize the paths—and some/many of them do! For example I wouldn't expect to use `xcopy FOO.BAR dest` and expect that it winds up in `dest` as `FOO.BAR` when it is really `foo.bar`. Or forget to use uppercase `C:\` instead of `c:\` and have an output file with a mix of cases.

So I'll be adding this to all my CLI apps. Eventually I may make that utility I mentioned even for non-existent paths to find the existing base path, canonicize it, and then resolve the rest of the path to it so that all path segments will be canonical even if the full path doesn't exists. Then I may even hack into picocli in `BaseCliApplication` to make this happen automatically as I have suggested here.

In any case, it might be something to point out the developers in case they didn't think of it (with a note by `Path` somewhere in the docs), with a pointer to how they can rectify it. Cheers!

**Comment by garretwilson** [comment]
Note that combined with #1743, if I have a `List<Path> argPaths` option, unfortunately I have to do all this ugly "cleanup" behind picocli:

```
List<Path> useThesePathsNotThePicocliArgs = argPaths != null
    ? argPaths.stream()
        .map(throwingFunction(path -> exists(path) ? path.toRealPath(NOFOLLOW_LINKS) : path))
        .collect(toUnmodifiableList())
    : List.of();
```

And I hope that in one of the many command methods I don't forget to add the fix-up, and that I don't forget to use `useTHesePathNotThePicocliArgs` instead of the `argPaths` that picocli gives me. It's a lot of clutter boilerplate.

I know you're all about backwards-compatibility even with decisions I don't agree with made eons ago, and Java versions no one uses, but maybe for this and #1743 you might consider adding some setting that says "use empty collections not `null`" and "convert existing paths to real paths"? That way I could turn on the flags in the base application class and be done with it.

**Comment by remkop** [comment]
Not sure if this is useful, but this came to mind:

If you register your custom Path converter in the `main` method before invoking `execute`, it will be the type converter used for all commands in the hierarchy, so it only needs to be done once.

```java
public static void main(String... args) {
  new CommandLine(new MyApp())
    .registerConverter(Path.class, new MyRealPathConverter())
    .execute(args);
}
```

I will close this ticket; https://github.com/remkop/picocli/issues/1743 will get a solution when I get a chance to work on https://github.com/remkop/picocli/issues/879 .
