### ISSUE TITLE
Is picocli expanding wildcards on Windows?

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#1761]
I have a strange problem that just surfaced, and until I do further investigation I'm completely puzzled by what's going on. Soon I have to stop working so I thought I'd post this here to get feedback and see if picocli is involved; I'll investigate more later.

On Windows 10 I have a CLI `do` with a command `something`. It takes `@Parameters` for `List<Path> dataPaths`, an `@Option` for `-o` for `Path outputPath`, and multiple `Option` for `--exclude-filename-globs` for `List<String> excludeFilenameGlobs`.

Normally I would use it like this to do something to the entire directory:

```
do something A:\ -o B:\output.dat
```

But if I want to ignore log files, I can do:

```
do something A:\ -o B:\output.dat --exclude-filename-globs *.log
```

But here's the strange thing. If I don't put `*.log` in quotes, somehow `dataPaths` gets not only `A:\`, but also _the log files in my current directory_! That is, it's as if I typed this:

```
do something -o B:\output.dat A:\ C:\current\directory\foo.log C:\current\directory\bar.log 
```

It's as if it's doing wildcard expansion on `*.log` before the command-line-options are even passed to the application. But this is the Windows 10 command line, which should not be doing wildcard expansion as far as I know. (I'm using the command prompt, not PowerShell.) I thought that only happened on *nix systems.

Is picocli doing some wildcard expansion? I did a search for "asterisk" and "wildcard" and "expansion" and couldn't find anything. I don't know that picocli is the culprit, but I wanted to ask here while I search elsewhere. Thanks.

**Comment by remkop** [comment]
I suspect it is the shell doing the expansion.

To help with the investigation, you can run the command with system property `-Dpicocli.trace=DEBUG`, (or INFO) and that will print the arguments that the application received and details of picocli's processing.

**Comment by garretwilson** [comment]
Thanks for the tip. I don't want to distract you too much as it's nowhere clear that this has anything to do with picocli.

But this has me completely puzzled. Using `-Dpicocli.trace=INFO` gives me something like:

```
[picocli INFO] Parsing 10 command line args [something, A:\, -o, B:\output.dat, --exclude-filename-globs, C:\current\directory\foo.log, C:\current\directory\bar.log ]
```

This tells me that picocli is seeing `*.log` expanded. But everywhere I read (and past experience) says Windows command line does not expand wildcard (like Linux does).

For full disclosure I'm really invoking something like this:

```
java -jar C:\project\target\do-1.0.0-SNAPSHOT-exe.jar something A:\ -o B:\output.dat --exclude-filename-globs *.log
```

Ah, here's another details. If I use `*.log` it gets expanded from my current directory as mentioned above, and if I use `A:\*.log` it gets expanded from the files in `A:\`:

```
java -jar C:\project\target\do-1.0.0-SNAPSHOT-exe.jar something A:\ -o B:\output.dat --exclude-filename-globs A:\*.log
```

If I put quotes around it like `"*.log"`, then it is not expanded—and picocli shows it is receiving `*.log` (without quotes and without wildcard expansion).

I am completely unable to explain this—unless Windows were expanding wildcards, in which case the output would make perfect sense. But how could Windows be expanding wildcards?

**Comment by garretwilson** [comment]
But if I put `echo %*` in a batch file, it does not expand wildcards.

Surely the `java -jar` command isn't expanding wildcards? But it shouldn't.

**Comment by garretwilson** [comment]
Oh, my—look at this: [How to pass * to a java program without wildcard expansion?](https://stackoverflow.com/questions/48949668/how-to-pass-to-a-java-program-without-wildcard-expansion)

They seem to be saying that OpenJDK does wildcard expansion! 😮 Are they trying to make `java -jar` behavior consistent across platforms by mimicking Linux on Windows?! Does the Sun JDK do this?

This is complete news to me. And I would think it would be quite relevant to picocli as well, to at least know this.

Wow. I'll have to digest this a bit to decide if I think this is good or horrible. But at least I (think I) know where it's coming from now. It's odd I haven't heard more about this before.

**Comment by remkop** [comment]
This may be relevant: https://docs.microsoft.com/en-us/cpp/c-language/expanding-wildcard-arguments?view=msvc-170

> Wildcard argument expansion is Microsoft-specific.
>
> When you run a C program, you can use either of the two wildcards, the question mark (`?`) and the asterisk (`*`), to specify filename and path arguments on the command line.
> 
> By default, wildcards aren't expanded in command-line arguments. You can replace the normal argument vector `argv` loading routine with a version that does expand wildcards by linking with the `setargv.obj` or `wsetargv.obj` file.

Which sounds like applications like `java` and `jar` have no choice: they need to make a decision whether to expand wildcards or not (they cannot delegate this to the environment); so yes I can see it would make sense for them to use the version that results in expanded wildcards to make behaviour similar across platforms...

This is very interesting, I never knew that the `cmd` shell did not expand wildcards. Thank you for bringing this to my attention!

**Comment by remkop** [comment]
I will close this since picocli receives the expanded wildcards so picocli is not involved.
