### ISSUE TITLE
[Question] static auto completion options that allow custom values as well

### ISSUE THREAD

**Issue by yeikel** [remkop/picocli#1770]
For the following option : 

```java
@CommandLine.Option(names = {"--project"}, description = "Project Name", required = true)
String project;
```
I have a list of static projects that I know in advance and that would be useful to give it as suggestions to my users. At the same time, I do not know all the projects in advance and I should allow my users to enter custom values

I understand that I could define an enum with this list, but that would prevent users from entering other values

Is there any recommended way to do this?

**Comment by remkop** [comment]
Hi @yeikel, yes you can define a `completionCandidates` attribute on the `@Option` annotation:

```java
@Option(names = "-o", completionCandidates = MyAbcCandidates.class, ...
```

See here for more details:
https://picocli.info/#_completion_candidates_variable

**Comment by yeikel** [comment]
That's exactly what I needed. Thanks!
