### ISSUE TITLE
[Question] Nested `completionCandidates` or `completionCandidates` with dependencies

### ISSUE THREAD

**Issue by yeikel** [remkop/picocli#1771]
For the following options :

```java


@CommandLine.Option(names = {"--project"}, description = "Project Name", required = true, completionCandidates= ProjectCandidates.class )
String project;

@Option(names = {"--service"}, description = "Service Name", required = true)
String service;

```

Where 

```java
public class ProjectCandidates extends ArrayList<String> {
    public ProjectCandidates() { super(List.of(
            "Project1",
             "Project2",
)); }
}

```

I have a list of static services that map to a given project. While autocompleting, I'd like to pass the selected project to my service auto completion and calculate them dynamically. 

For example : 

```java
Map.of (

"Project1",List.of("service1","service2"),
"Project2",List.of("service3","service2")
)

```

For the example above, passing `--project project1 --service` should give service1 or service2 as a possible option but not service3

Is there any recommended way to do this?

**Comment by remkop** [comment]
I think this is probably possible but it won't be trivial.

One way I can think of is to make the `--project` option a `@Option`-[annotated setter method](https://picocli.info/#option-parameters-methods), and in that method, change the model of the `--service` option.

The [`ArgSpec.completionCandidates()`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Model.ArgSpec.html#completionCandidates()) is a read-only method, so we cannot replace that object, but you could make the object itself mutable. Something like this:

```java
public class ServiceCandidates implements Iterable<String> {

    // mutable field
    public List<String> candidates = new ArrayList<>(List.of("Service1", "Service1"));

    public Iterator<T> iterator() { return candidates.iterator(); }
}
```

Then you could do something with picocli's programmatic model, like this:

```java
class MyCommand {
    @Spec CommandSpec spec;

    private String project;
    @CommandLine.Option(names = {"--project"}, description = "Project Name", required = true, 
            completionCandidates= ProjectCandidates.class )
    void setProject(String project) {
        this.project = project;
        OptionSpec service = spec.findOption("service");
        ServiceCandidates serviceCandidates = (ServiceCandidates) service.completionCandidates();
        if ("projectX".equals(project)) {
            serviceCandidates.candidates.clear();
            serviceCandidates.candidates.addAll(List.of("X", "Y", "Z");
        }
    }

    @Option(names = {"--service"}, description = "Service Name", required = true, 
            completionCandidates= ServiceCandidates.class )
    String service;
}
```

I haven't tested this, but please give it a try.

**Comment by yeikel** [comment]
> ```java
> private String project;
>     @Option(names = {"--project"}, description = "Project Name", required = true, 
>             completionCandidates= ProjectCandidates.class )
>     void setProject(String project) {
>         this.project = project;
>         OptionSpec service = spec.findOption("service");
>         ServiceCandidates serviceCandidates = (ServiceCandidates) service.completionCandidates();
>         if ("projectX".equals(project)) {
>             serviceCandidates.candidates.clear();
>             serviceCandidates.candidates.addAll(List.of("X", "Y", "Z");
>         }
>     }
> ```

Thank you for your suggestion, but who calls setProject? I tried that example above and it does not seem to be doing anything

This is how I have it : 

```java

@CommandLine.Spec private CommandLine.Model.CommandSpec spec; // injected by picocli

 private String project;
    @Option(names = {"--project"}, description = "Project Name", required = true,
            completionCandidates= ProjectCandidates.class )
    public void setProject(String project) {
        System.out.println("Calling set project");
        this.project = project;
        CommandLine.Model.OptionSpec service = spec.findOption("service");
        ServiceCandidates serviceCandidates = (ServiceCandidates) service.completionCandidates();

        var possibleServices = readCandidates()
                .stream()
                .filter(e-> e.getProjectName().equalsIgnoreCase(project))
                .map(e-> e.getServiceName())
                .collect(Collectors.toSet());

        System.out.println("serviceCandidates for project=" + project + "=" + possibleServices);

        serviceCandidates.candidates.clear();
        serviceCandidates.candidates.addAll(possibleServices);
    }
```

**Comment by remkop** [comment]
My bad. 

I think picocli can’t help you here and you’d have to write a custom bash completion script.

**Comment by yeikel** [comment]
> My bad. 
> 
> I think picocli can’t help you here and you’d have to write a custom bash completion script. 

This kind of nested auto completion might be common. Can we convert this to a feature request instead?

Additionally, how would I customize the suggestions so that running  `generate-completion` includes my customized script?

**Comment by remkop** [comment]
> > I think picocli can’t help you here and you’d have to write a custom bash completion script.
> 
> This kind of nested auto completion might be common. Can we convert this to a feature request instead?

I am not sure I can see how this would work, and in addition I am busy with other stuff and not personally interested in spending time on this particular area. 😅 

> Additionally, how would I customize the suggestions so that running `generate-completion` includes my customized script?

I imagine you would have to take the generated script and modify it to meet your needs.

**Comment by remkop** [comment]
> > Additionally, how would I customize the suggestions so that running `generate-completion` includes my customized script?
> 
> I imagine you would have to take the generated script and modify it to meet your needs.

You could have a custom command (named `generate-completion`) that would print your custom script to standard output stream.

**Comment by yeikel** [comment]
> > > Additionally, how would I customize the suggestions so that running `generate-completion` includes my customized script?
> > 
> > 
> > I imagine you would have to take the generated script and modify it to meet your needs.
> 
> You could have a custom command (named `generate-completion`) that would print your custom script to standard output stream.

I understand. What I am trying to say, is how can I plug a custom script into that process. At the moment, the only configuration I have is an annotation pointing to `AutoComplete.GenerateCompletion.class`

Do I need to perhaps create my own AutoComplete.GenerateCompletion and point to it?

**Comment by remkop** [comment]
The way I see this could work is that your custom `generate-completion` command would simply print a massive String to standard out.
You may read that string from a separate file in the jar at runtime, or just package it inside your class.

**Comment by yeikel** [comment]
> The way I see this could work is that your custom `generate-completion` command would simply print a massive String to standard out. You may read that string from a separate file in the jar at runtime, or just package it inside your class.

I'd like to stay within the same picoli framework as much as possible to avoid having a separate process just for this command for my users

**Comment by remkop** [comment]
You would not use `AutoComplete.GenerateCompletion`, instead you have your own command.

```java
@Command
class MyCommand {
    @Option...

    @Command(name = "generate-completion")
    void generateCompletion() {
        String script = "... massive long string with the customized completion script";
        System.out.print(script);
        System.out.flush();
    }
```

**Comment by yeikel** [comment]
> You would not use `AutoComplete.GenerateCompletion`, instead you have your own command.
> 
> ```java
> @Command
> class MyCommand {
>     @Option...
> 
>     @Command(name = "generate-completion")
>     void generateCompletion() {
>         String script = "... massive long string with the customized completion script";
>         System.out.print(script);
>         System.out.flush();
>     }
> ```

That should work. I'll try that out. Thank you for the suggestion

**Comment by remkop** [comment]
You are very welcome!
Enjoy using picocli!
