### ISSUE TITLE
Custom factory not used when creating CommandSpec

### ISSUE THREAD

**Issue by charphi** [remkop/picocli#1779]
Custom factory as [described here](https://picocli.info/#_custom_factory) is not used when creating a CommandSpec. The default one is always used instead.

See `picocli.CommandLine.Model.CommandReflection#extractCommandSpec`.

The faulty line is 
```java
CommandSpec result = CommandSpec.wrapWithoutInspection(userObject);
```
and should be replaced by 
```java
CommandSpec result = CommandSpec.wrapWithoutInspection(userObject, factory);
```

**Comment by remkop** [comment]
Thank you for raising this. 

Will you be able to provide a pull request for this?

**Comment by remkop** [comment]
Fixed in `main`.
Thanks for raising this!

If you could provide a test to verify this, that would be super helpful. 🙏 
Thank you again!
