### ISSUE TITLE
Autocompletion bug for subcommands in zsh

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#178]
on ZSH, the `hierarchy` test command always shows the top-level completions, even after a subcommand was selected.

Expected:
```
$ hierarchy sub2
-d           --directory  --num2       subsub1      subsub2
```

Actual:
```
$ hierarchy sub2
-h         --help     sub1       sub2       -V         --version
```

**Comment by remkop** [comment]
Tracked it down to a problem in the `ArrContains` function. The following code works in both bash and zsh:
```
function ArrContains() {
  local lArr1 lArr2
  declare -A tmp
  eval lArr1=("\"\${$1[@]}\"")
  eval lArr2=("\"\${$2[@]}\"")
  for i in "${lArr1[@]}";{ [ -n "$i" ] && ((++tmp[$i]));}
  for i in "${lArr2[@]}";{ [ -n "$i" ] && [ -z "${tmp[$i]}" ] && return 1;}
  return 0
}
```

**Comment by remkop** [comment]
```
Index: src/main/java/picocli/AutoComplete.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/picocli/AutoComplete.java	(revision )
+++ src/main/java/picocli/AutoComplete.java	(revision )
@@ -249,8 +249,8 @@
             "  declare -A tmp\n" +
             "  eval lArr1=(\"\\\"\\${$1[@]}\\\"\")\n" +
             "  eval lArr2=(\"\\\"\\${$2[@]}\\\"\")\n" +
-            "  for i in \"${lArr1[@]}\";{ [ -n \"$i\" ] && ((++tmp['$i']));}\n" +
-            "  for i in \"${lArr2[@]}\";{ [ -z \"${tmp[$i]}\" ] && return 1;}\n" +
+            "  for i in \"${lArr1[@]}\";{ [ -n \"$i\" ] && ((++tmp[$i]));}\n" +
+            "  for i in \"${lArr2[@]}\";{ [ -n \"$i\" ] && [ -z \"${tmp[$i]}\" ] && return 1;}\n" +
             "  return 0\n" +
             "}\n" +
             "\n";
```

**Comment by Fadelis** [comment]
Hello,

I'm having the same issue in bash. 
When creating autocompletion script I'm passing the top level command with subcommands added via annotations. The generated script seems to have subcommands options in it, but when subcommand is typed only the top level suggestions are shown via tab.

**Comment by remkop** [comment]
Can you provide a small program that demonstrates the issue so I can try to reproduce it?

**Comment by remkop** [comment]
Aha! Thank you for figuring that out. This is certainly fixable. 

The problem is the `AutoComplete.bashify` method: it drops “invalid” characters and the current implementation only considers letters, digits and the underscore character ‘_’ as valid. At the very least the hyphen character should also not be discarded. (Need to check what other characters are “valid” bash identifier characters.)

Would you mind opening a separate ticket for this?

**Comment by remkop** [comment]
Closing this ticket: following up on supporting hyphens in subcommands in #371.
