### ISSUE TITLE
Checking import specifications for Picocli examples

### ISSUE THREAD

**Issue by Markus-Elfring** [remkop/picocli#1788]
I tried [a variant of the CheckSum example](https://github.com/remkop/picocli/blob/3583b5d9dcea8f33e1dc03b2e59b9d1ed1921f7a/picocli-examples/src/main/java/picocli/examples/cjk/CheckSum.java#L1 "Demonstration code") out also within the tool “Eclipse IDE for Java Developers 2022-06 (4.24.0)”.
How do you think about to extend the demonstration source code? :thinking:

**Comment by remkop** [comment]
Sorry I don’t understand the question. 
Can you clarify what you want me to do?

**Comment by Markus-Elfring** [comment]
The “[Picocli example 4.0](https://github.com/remkop/picocli/blob/dbf907e1b42ddd36711f6624fc822e7adca75eaa/README.md#example "Demonstration source code")” is especially mentioned in one document.
How do you think about to improve the awareness for details from additional [test applications](https://picocli.info/#_example_application "checksum 4.0") and [related examples](https://github.com/remkop/picocli/blob/6364e1b19523a1d69744bb2b6f082f61cf566eda/picocli-examples/README.md "Further Picocli examples")? :thinking:

**Comment by remkop** [comment]
Sorry, I don't understand what you are trying to say...

There is an example (called `Example`) in the README,
there is another example (called `CheckSum`) in the user manual,
and there are a number of examples that are not in the documentation but can be found in the picocli git repository under `picocli-examples`.

Do you mean that the user manual should mention and link to the `picocli-examples` directory?

**Comment by Markus-Elfring** [comment]
:thought_balloon: I imagine that additional links (and data formats) can become helpful for better connections of some information sources.

**Comment by remkop** [comment]
Thank you for the clarification!
I added a link to `picocli-examples` under the `CheckSum` example in the user manual.
The README already has many links to the user manual, I will leave the README as is for now.

The change will be reflected in the published HTML of the user manual with the next release.

Thank you again for raising this.

**Comment by Markus-Elfring** [comment]
Thanks for [another small documentation adjustment](https://github.com/remkop/picocli/commit/c0bd48b6ad009051405fd6a51b3ea33b91571a89 "add link to picocli-examples in the user manual").

:thought_balloon: I became curious if further collateral evolution will happen.
