### ISSUE TITLE
Add Compact Profile Support

### ISSUE THREAD

**Issue by webfolderio** [remkop/picocli#179]
Hi,

Is it possible to remove Full JRE dependency. Picocli use `java.awt.Point` which requires Full JRE.

Thanks

`jdeps -P picocli-1.0.0.jar`

```
picocli-1.0.0.jar -> C:\Java\jdk1.8.0_141\jre\lib\rt.jar (Full JRE)
   picocli (picocli-1.0.0.jar)
      -> java.awt                                           Full JRE
      -> java.io                                            compact1
      -> java.lang                                          compact1
      -> java.lang.annotation                               compact1
      -> java.lang.reflect                                  compact1
      -> java.math                                          compact1
      -> java.net                                           compact1
      -> java.nio.charset                                   compact1
      -> java.sql                                           compact2
      -> java.text                                          compact1
      -> java.util                                          compact1
      -> java.util.concurrent                               compact1
      -> java.util.regex                                    compact1
```

**Comment by remkop** [comment]
Ok, I can see the value of doing this.

Two things:
* `TextTable#putValue` is a public method in a public inner class, so the class replacing `java.awt.Point` also needs to be public. (Also, we may take this opportunity to name the class something clearer than Point... `Position`, `Cell`, `Address`, `At` come to mind. Other suggestions welcome...)
* this is a breaking API change, so the next version needs to become 2.0.0 since picocli follows semantic versioning 

(These are not objections, just noting them)

**Comment by remkop** [comment]
I also noticed that the type converter for `java.sql.Time` introduces a dependency on `compact2`, everything else is `compact1`. 

I wonder if it is worth using reflection to avoid a hard dependency on `compact2`...

Background: there is an outstanding ticket (#83) to support more built-in types. Some of the types I'm planning to support were introduced in java 7 and java 8. At the same time, I would like picocli to continue be compatible with java 5. To solve this, I plan to use reflection to implement type converters for `java.time.*` classes, `java.nio.file.Path`, etc. 

So if we will be using reflection anyway, why not use reflection for anything other than `compact1`?
Thoughts?

**Comment by webfolderio** [comment]
> I wonder if it is worth using reflection to avoid a hard dependency on compact2...

Its OK, there is no big difference between compact 1 and compact2 profile.

Here is JRE 8 size for windows platform:
* compact1 15MB
* compact2 20MB
* cmpact3 23MB
* j2re-full 54MB

> So if we will be using reflection anyway, why not use reflection for anything other than compact1?

`CommandLine.java` and common types (Date, Time, BigDecimal...) should dependen on compact profile. If a type requires Full JRE you might place them as an extension project.
