### ISSUE TITLE
jakarta.validation-api with picocli

### ISSUE THREAD

**Issue by ashr123** [remkop/picocli#1798]
is there a way to use jakarta.validation-api with plain picocli (without Springboot/Hibernate etc.)? it may be silly but I'm trying to use it as it is but is doesn't work.
Example:
```java
@CommandLine.Parameters(description = "Is to show sum calculation? (values: true, false)")
private boolean isDetailed;
@Positive
@CommandLine.Parameters(description = "How many roles should the program make?")
private long roles;
@Min(3)
@CommandLine.Parameters(description = "Used to tell the number of side the dice has.")
private int d;
@PositiveOrZero
@CommandLine.Parameters(
		description = "Used to be added per role.",
		defaultValue = "0"
)
private int constantAddition;
```

**Comment by remkop** [comment]
I suspect that is not possible but you can ask the maintainers of the jakarta.validation-api project, they may be better positioned to answer that question.

**Comment by ashr123** [comment]
@remkop I see that [hibernate-validator](https://github.com/hibernate/hibernate-validator) is an implementation that uses [validation](https://github.com/jakartaee/validation) but there is need to create `Validator` (see https://docs.jboss.org/hibernate/validator/8.0/reference/en-US/html_single/#_validating_constraints) can this integrate dynamically to picocli (i.e. recognize the existence of hibernate-validator and initiate a `Validator`)?

**Comment by remkop** [comment]
There are several ways to think about this.
I don't plan on adding built-in support for jakarta.validation-api to the picocli library.

However, the [example in the user manual](https://picocli.info/#_jsr_380_beanvalidation)  (calling a helper method from the `run` method) is only one way to accomplish this.

Perhaps a nicer way is to have a [custom `IExecutionStrategy`](https://picocli.info/#_initialization_before_execution) which does the validation before executing the command.

Such a custom `IExecutionStrategy` could look something like this:

```java
class ValidatingExecutionStrategy implements IExecutionStrategy {
    public int execute(ParseResult parseResult) {
        validate(parseResult.commandSpec());
        return new CommandLine.RunLast().execute(parseResult); // default execution strategy
    }

    void validate(CommandSpec spec) {
        Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
        Set<ConstraintViolation<Object>> violations = validator.validate(spec.userObject());
        if (!violations.isEmpty()) {
            String errorMsg = "";
            for (ConstraintViolation<?> violation : violations) {
                errorMsg += "ERROR: " + violation.getMessage() + "\n";
            }
            throw new ParameterException(spec.commandLine(), errorMsg);
        }
    }
}
```

The application would wire it in like this:

```java
    public static void main(String[] args) {
        MyApp app = new MyApp();
        new CommandLine(app)
                .setExecutionStrategy(new ValidatingExecutionStrategy())
                .execute(args);
    }
```

I have added this example to the user manual (the HTML will be published with the next release), 
and updated the [java examples](https://github.com/remkop/picocli/tree/main/picocli-examples/src/main/java/picocli/examples/jsr380/beanvalidation)
and added a [kotlin example](https://github.com/remkop/picocli/tree/main/picocli-examples/src/main/kotlin/picocli/examples/kotlin/jsr380/beanvalidation).

**Comment by ashr123** [comment]
@remkop thanks 😃
eventually I went with the following code:
```java
Logger.getLogger("org.hibernate").setLevel(Level.OFF);
final CommandLine commandLine = new CommandLine(DiceRoller.class);
CommandLine.IExecutionStrategy executionStrategy = commandLine.getExecutionStrategy();
commandLine.setExecutionStrategy(parseResult ->
		{
			try (ValidatorFactory validatorFactory = Validation.buildDefaultValidatorFactory())
			{
				Set<ConstraintViolation<Object>> violations = validatorFactory.getValidator().validate(parseResult.commandSpec().userObject());
				if (!violations.isEmpty())
				{
					final StringBuilder errorMsg = new StringBuilder();
					for (ConstraintViolation<?> violation : violations)
						errorMsg.append("ERROR: ").append(violation.getPropertyPath()).append(' ').append(violation.getMessage()).append(System.lineSeparator());
					throw new CommandLine.ParameterException(parseResult.commandSpec().commandLine(), errorMsg.toString());
				}
			}
			return executionStrategy.execute(parseResult);
		})
		.execute(args);
```

**Comment by roded** [comment]
Is this solution expected to work for subcommands as well?
In my case, it seems like the userObject is the parent command which passes validation successfully even if the executed subcommand should not.
