### ISSUE TITLE
Output all args but exclude few args that contains sensitive information about the user who is running the cli application 

### ISSUE THREAD

**Issue by sau3078** [remkop/picocli#1818]
command name
--clientId=<sensitive information>
--<token>- <sensitive information>
-- option1 - <non sensitive information>

I know we can output all the args using ParseResult object.

I wanted to exclude all the args that contains sensitive information and then wanted  that args to be saved in the database,

My instension is to serialize all the args in the json format excluding args which contains sensitive.

**Comment by remkop** [comment]
@sau3078 Does that answer your question?

**Comment by sau3078** [comment]
yes its answer my question. We can close this.
