### ISSUE TITLE
Looking for examples of using picocli from other JVM languages

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#183]
[Picocli](https://github.com/remkop/picocli) is an annotation-based command line parser written in Java that scales down to [very small](http://picocli.info/#_introduction) applications, generates [customizable](http://picocli.info/#_usage_help) usage help [with ANSI colors and styles](http://picocli.info/#_ansi_colors_and_styles), and features [TAB autocompletion](http://picocli.info/autocomplete.html)(!), nested [subcommands](http://picocli.info/#_subcommands) (to any depth) and more.

I'm working on the user manual for the upcoming v2.0 release, and I'm looking for examples of how picocli can be used with JVM languages other than Java. (Work in progress is [here](https://github.com/remkop/picocli/wiki/Manual#picocli-in-other-languages).)

If you have tips, suggestions or (ideally) code snippets, please add them to this ticket. 

----

* (/) [Groovy](http://groovy.codehaus.org/)
* (/) [Scala](http://www.scala-lang.org/)
* (/) [Kotlin](http://kotlin.jetbrains.org/)
* [JRuby](http://jruby.org/)
* [Clojure](http://www.clojure.org/)
* [Jython](http://www.jython.org/)
* [Ceylon](http://ceylon-lang.org/)
* [Xtend](https://www.eclipse.org/xtend/)
* [Fantom](http://www.fantom.org/)
* [X10](http://x10-lang.org/)
* ...other?

**Comment by remkop** [comment]
## Kotlin
https://kotlinlang.org/docs/reference/annotations.html

Kotlin does not allow specifying array annotation attribute as a single value, so be aware that you will have to write `arrayOf(...)` for the `names`, `description` and `type` attributes.
```
class Args {
    @field:Option(names = arrayOf("-h", "--help"), usageHelp=true, 
                   description=arrayOf("Print this help and exit"))
    var helpRequested = false;
}
```

## Scala
Scala does not allow specifying array annotation attribute as a single value, so be aware that you will have to write `Array(...)` for the `names`, `description` and `type` attributes.
```
class Args {
    @field:Option(names = Array("-h", "--help"), usageHelp=true, 
                   description=Array("Print this help and exit"))
    var helpRequested = false;
}
object App {
  def main(args: Array[String]) {
    val commandLine= new CommandLine(Args)
    commandLine.parse(args.toArray: _*)
    if (Args.helpRequested) {
      commandLine.usage(System.err)
      System.exit(0)
    }
    // do something with Args
  }
}

```
## Groovy

In Groovy, use `[` and `]` to surround array values, instead of the `{` and `}` used in Java.
```
class Args {
    @Option(names = ["-h", "--help"], usageHelp=true, 
                   description="Print this help and exit")
    boolean helpRequested = false;
}
```

**Comment by binkley** [comment]
I note that Kotlin 1.2 (still in beta) lifts the requirement of `arrayOf` for multiply-valued annotation parameters, using standard array notation instead (`param = [value1, value2]`):

https://blog.jetbrains.com/kotlin/2017/06/early-access-program-for-kotlin-1-2-has-been-started/

**Comment by remkop** [comment]
@binkley Thank you very much for letting me know! I've just started to update the [manual](https://github.com/remkop/picocli/wiki/Manual#picocli-in-other-languages) for the upcoming picocli 2.0 release, so this is very timely!

**Comment by remkop** [comment]
Closing this ticket for the picocli-2.0 release.
(I may open another one for additional JVM language examples.)
