### ISSUE TITLE
Incorrect synopsis for char[] options

### ISSUE THREAD

**Issue by rsenden** [remkop/picocli#1834]
I have some password options defined like the following:
```java
@Option(names = {"--password", "-p"}, interactive = true, echo = false, arity = "0..1", required = true)
@Getter private char[] password;
```

Likely due to this option being defined as an array, the command synopsis in help output and man page show this as a repeatable option:

```
-p[=<password>] [-p[=<password>]]...
```

This is confusing for users, as it makes them think they can specify multiple passwords, whereas in reality they can only specify a single password consisting of multiple characters.

**Comment by rsenden** [comment]
I'll look into providing a PR with fix and unit test either myself or by my colleague.

**Comment by remkop** [comment]
Looking at this more closely, I think https://github.com/remkop/picocli/issues/1846 (treating `char[]` as single value type) is a better solution. I will make the changes.
