### ISSUE TITLE
Interactive prompts if `-h` option specified

### ISSUE THREAD

**Issue by rsenden** [remkop/picocli#1835]
I have some password options defined like the following:
```java
@Option(names = {"--password", "-p"}, interactive = true, echo = false, arity = "0..1", required = true)
@Getter private char[] password;
```

Now, suppose the user has already been specifying some options for the command but wants to review the help information once more, so executes a command like the following:
`<someCommand> <someOptions> -p -h`

Because of the interactive `-p` option, picocli will prompt for the password even though the user just wants to view the help information.

It's just a minor nuisance and the user can simply press `<enter>` on the password prompt, but it would be nice if this can eventually be fixed.

**Comment by remkop** [comment]
The parser will process the command line parameters one by one, and the `-p` will trigger the prompting for a value.
I think there is some checking that the next value is not a value (that it is either a subcommand or another option).

It is possible to add logic to that next-value-check to check that the next value is a help option or version option, or a helpCommand. But that will only help if the `-h` option immediately follows the `-p` interactive option.
It will not help for cases like 

```
<someCommand> <someOptions> -p <comeOtherOption> -h
```

In the above case, we will still see the behaviour you are currently seeing, even after the code change I mentioned.
Alternatively picocli needs to make two passes through the input... I am not looking forward to the edge cases that this will introduce. 
I am afraid we will have to live with this behaviour. I don't think it is that surprising for end users anyway... :sweat_smile:
