### ISSUE TITLE
CommandLine.setSeparator() is ignored when generating usage text.

### ISSUE THREAD

**Issue by defnull** [remkop/picocli#184]
Title says it all. A call to `cmd.usage(system.err)` will print the default or annotated separator and ignores the value set by `cmd.setSeparator("XXX")`.

**Comment by remkop** [comment]
Thanks for looking at picocli.

This behaviour is documented in the user manual.
Please see http://picocli.info/#_option_parameter_separators and http://picocli.info/#_custom_separators

Basically, the `setSeparator` is for the parser only, not for the usage help message.
Declaratively setting a separator via annotations like `@Command(separator = ":")` impacts both the usage help message and the parser.

The idea was to allow users to separately control the usage help and the parser separator.

**Comment by remkop** [comment]
I realize now that this could be confusing, but on the other hand I would like to support allowing  users to separately control the usage help and the parser separator.

I just saw that the javadoc on `CommandLine.setSeparator` is not very explicit about this. I will improve the javadoc. 

I hope that will be sufficient, what do you think?

**Comment by remkop** [comment]
Updated the javadoc.
Closing this issue; please reopen if more work is required.

**Comment by remkop** [comment]
I have come to my senses after realizing I could not think of any scenario where it would be useful for users to have a different separator in the parser and the usage help. It would only be confusing.

I will make changes such that the separator set programmatically via `CommandLine.setSeparator` will be reflected in the usage help message. If different separator values are specified declaratively (in `@Command(separator="xxx")` and programmatically, the programmatically set value will be used.
