### ISSUE TITLE
Spring Boot 3 support

### ISSUE THREAD

**Issue by brunomace** [remkop/picocli#1840]
Hello,
The actual Spring Boot autoconfiguration registration method will not be supported anymore in Spring Boot 3.

The current milestone M5 have alreday removed the support of the "spring.factories" file in flavor of the "META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports" file.

This new method have been introduced in Spring Boot 2.7.

It's a blocker since the Picocli Spring Boot Starter can't be used with the upcoming release of Spring Boot 3 (and current milestone) .

See comments here;
  https://github.com/spring-projects/spring-boot/issues/32566
  https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration

**Comment by brunomace** [comment]
Hello,
Adding a new file "/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports" with this content works:
`picocli.spring.boot.autoconfigure.PicocliAutoConfiguration`

**Comment by remkop** [comment]
Hi @brunomace I believe this was completed in https://github.com/remkop/picocli/pull/1778

**Comment by brunomace** [comment]
Duplicate
