### ISSUE TITLE
Command line options not being picked up when executed from graalvm binary

### ISSUE THREAD

**Issue by agibsonccc** [remkop/picocli#1845]
I have an odd issue where command line options work fine in java but not in graalvm.
The command class can be found here:
https://github.com/KonduitAI/kompile/blob/main/src/main/java/ai/konduit/pipelinegenerator/main/models/samediff/ChangeVariableType.java

The CLI is nested as follows:
MainCommand
         SamediffMain
                ChangeVariableType

None of my other commands under the same group have this problem. I've tried changing the visibility of the values and I have the reflect-config.json up to date. That can be found here:

https://github.com/KonduitAI/kompile/blob/f6f588c1914dbaf056f4965f34489564587ddfb7/src/main/resources/META-INF/native-image/reflect-config.json#L52808

Anything else I might be missing?

**Comment by remkop** [comment]
Sorry, I did not dive in to investigate, but if the reflect-config.json contains all the picocli-annotated fields and methods, but the native image still does not work correctly (you did not report what you were seeing, whether these options are not showing up in the usage help, or not recognized by the parser, or whether that command did not work at all...)

Anyway, this may be a native-image issue rather than a picocli issue.

However, if there is a problem in the generated reflect-config.json, not containing all annotated classes fields or methods, then that would be something that needs to be fixed in picocli.

Which do you think it is?

**Comment by agibsonccc** [comment]
@remkop sorry let me be clearer! The concrete issue I'm running in to is the relevant command here doesn't resolve any flags. The only thing it seems to accept are no flags at all. It does not exhibit this behavior under normal java.

My reflect-config.json already exposes everything about the class.

**Comment by agibsonccc** [comment]
@remkop sorry for pushing this...I don't for a fact know if this is  a bug on picocli side but I do think it'd be good to just get this out there for people. I've been attempting to play with my own CLI seeing what happens. I can reliably reproduce this for an arbitrary dummy class such as:
```java
ackage ai.konduit.pipelinegenerator.main;

import org.apache.commons.io.FileUtils;
import picocli.CommandLine;

import java.io.File;
import java.util.concurrent.Callable;

@CommandLine.Command(name = "bootstrap-dummy",description = "Sets up SDK for building images.")
public class DummyCommand implements Callable<Integer> {
    @CommandLine.Option(names = {"--createFolder"},description = "Whether to create home folder or not, defaults to true",required = false)
    private boolean createFolder = true;

    @CommandLine.Option(names = {"--forceBootstrap"},description = "Whether to force creation of directory or not.",required = false)
    private boolean forceBootstrap = false;

    public DummyCommand() {
    }

    @Override
    public Integer call() throws Exception {
       if(createFolder) {
           File user = new File(System.getProperty("user.home"),".kompile");
           if(user.exists() && forceBootstrap) {
               FileUtils.deleteDirectory(user);
               System.err.println("Forcing recreation of " + user.getAbsolutePath());
           }

           if(!user.exists() && !user.mkdirs()) {
               System.err.println("Unable to create directory.");
           } else {
               System.out.println("Created directory " + user.getAbsolutePath());
           }
       } else {
           System.err.println("Not creating folder. createFolder was false.");
       }


        return 0;
    }
}
```


When I run my CLI I do:
```bash
 ./kompile bootstrap-dummy -h
Unknown option: '-h'
Usage: kompile bootstrap-dummy
Sets up SDK for building images.

```

For whatever reason no parameters are picked up.

This is *with* in my reflect-config.json:
```
  {
    "name":"ai.konduit.pipelinegenerator.main.DummyCommand",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
  } 
```

When I try to pass a parameter I get:
```bash
./kompile bootstrap-dummy --createFolder=true
Unknown option: '--createFolder=true'
Usage: kompile bootstrap-dummy
Sets up SDK for building images.

```

I raised an issue here because I'm not really sure what else the cause might be.

**Comment by agibsonccc** [comment]
@remkop Found it...sorry for bugging you.
```
  {
    "name":"ai.konduit.pipelinegenerator.main.DummyCommand",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true,
** "allDeclaredFields":true**
  } 
```

So it wasn't specific to picocli/graal just missing the needed declaration for fields.  Hopefully this helps someone who's overlooking something simple in the future.

**Comment by remkop** [comment]
Awesome 🤩 glad to hear that!
