### ISSUE TITLE
Mutually exclusive positional parameters, or perhaps subcommands of subcommands

### ISSUE THREAD

**Issue by MagnusMG** [remkop/picocli#1852]
OK, so this is more of a question, but perhaps a feature request.

I have program `hsthandler` with several subcommands, one of which is `delete`. Depending on what I choose to delete, different arguments are needed. So, if I want to delete `LU` I need to specifiy YEAR and MONTH. If I want to delete `ORDINST` I need to specify FACULTY.

Example 1:
`hsthandler load LU 2021 8`

Example 2:
`hsthandler load ORDINST Humanities`

`load` is a subcommand. `LU` and `ORDINST` I refer to as 'variants'.

I attempted to do this as ArgGroups, with no success. (To simplify things I made variant a paramater of the main command `hsthandler`, so we dont have to worry about that part here.):

````
public class DeleteParameters {
		@ArgGroup(exclusive=true, multiplicity="1")
		lateinit var argGroupLU: LUDeleteParameters
		@ArgGroup(exclusive=true, multiplicity="1")
		lateinit var argGroupOrdInst: OrdInstDeleteParameters
	}

	public class LUDeleteParameters {
		@Parameters(paramLabel = "YEAR", description = ["Year to delete."]) 
		var year: Int = 0
		@Parameters(paramLabel = "MONTH", description = ["Month (number) to delete."]) 
		var month: Int = 0
	}

	public class OrdInstDeleteParameters {
		@Parameters(paramLabel = "FACULTY", description = ["Faculty to delete."]) 
		lateinit var faculty: Faculty
	}

	@Command(name="delete", description = ["Deletes some things."])
	fun delete(
		@ArgGroup(exclusive=true, multiplicity="1") 
		lateinit var dp: DeleteParameters
	){
	  // Actually delete stuff.
	}

	
````
This resulted in `error: 'var' on function parameter is not allowed[nl] lateinit var dp: DeleteParameters[nl]`.

I am not sure this can be solved with mutually exlusive positional parameters. Another alternative would be to let LU and ORDINST be subcommands of `load`. But that is not possible, right?

Any suggestions?

**Comment by MagnusMG** [comment]
Sub-subcommands ARE allowed! It is right there, in the documentation. Sorry.

**Comment by remkop** [comment]
No worries 😉
