### ISSUE TITLE
FileCompleterDemo doesn't work for Bash completion

### ISSUE THREAD

**Issue by tadayosi** [remkop/picocli#1871]
Hi, thank you for this great tool!

I'm trying to enable file path completion for a positional parameter for [a CLI](https://github.com/apache/camel/tree/main/dsl/camel-jbang) on Bash. I applied the [FIleCompleterDemo](https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/completioncandidates/FileCompleterDemo.java) but found out that the generated Bash completion script always contains the set of files where the script is generated by the `AutoComplete` command. Therefore, it doesn't suggest the actual file set from the current directory but only the initial one.

As you can see the fixed set of files is directly embedded in the completion script:
```
  local files_pos_param_args=".vscode dsl tooling catalog apache-camel etc .project .flattened-pom.xml tests log-camel-lsp.out archetypes components bom LICENSE.txt camel-dependencies test-infra .gitmodules Jenkinsfile.full.pipeline SECURITY.md .idea jdt.ls-java-project .metadata .git buildingtools core .settings parent .mvn docs init .github README.md NOTICE.txt jbang-catalog.json .gitignore .gitattributes CONTRIBUTING.md KEYS Jenkinsfile.deploy Jenkinsfile.jdk11 Jenkinsfile.jdk17 Jenkinsfile.s390x doap.rdf mvnw mvnw.cmd .asf.yaml target pom.xml GTAGS GPATH GRTAGS" # 0-2147483647 values
```

**Comment by remkop** [comment]
Hi, thank you for the kind words!

Okay, so `FIleCompleterDemo` does not work great.
What happens if you do not use any completer, so the positional parameter looks like this:

```java
@Parameters(arity = "1", description = "A file.")
File file;
```

For the above, does the generated bash completion script work better?

**Comment by tadayosi** [comment]
Ah, thanks. Yes, I noticed that if I change the type to `File` completion should work, but unfortunately it's a bit hard for my project to refactor it from `String` to `File` because the parameter may also accept something other than a real file, e.g. `github:tadayosi/myproject/hello.java`.

Does it make sense if I contribute a `FilePathCompleter` as a builtin completer class which just serves as a marker, and when it's specified as `completionCandidates` then it falls into this condition of code generation?
https://github.com/remkop/picocli/blob/main/src/main/java/picocli/AutoComplete.java#L789-L793

**Comment by remkop** [comment]
> Ah, thanks. Yes, I noticed that if I change the type to `File` completion should work, but unfortunately it's a bit hard for my project to refactor it from `String` to `File` because the parameter may also accept something other than a real file, e.g. `github:tadayosi/myproject/hello.java`.

That is great. I actually believe that you can capture any string in a `File` object, it is only when you invoke methods like `getAbsolutePath` that the file system is actually accessed. So your application may be fine representing this parameter as a `File` or `Path` object.

> Does it make sense if I contribute a `FilePathCompleter` as a builtin completer class which just serves as a marker, and when it's specified as `completionCandidates` then it falls into this condition of code generation? https://github.com/remkop/picocli/blob/main/src/main/java/picocli/AutoComplete.java#L789-L793

Hmm... I don't see the need for this... Given that you can capture any string, including `github:tadayosi/myproject/hello.java`, in a `File` or `Path`, I don't think a special marker completer is necessary.

**Comment by tadayosi** [comment]
I understand. I'm still concerned about representing something which may not be a file as `File` or `Path` just for file path completion, as it may force the logic of the command to be a bit awkward or non-intuitive. I thought it would be great if Picocli could provide a flexibility to the case.

Anyway, I'll try your suggestion and see if it works. Thank you!

**Comment by remkop** [comment]
Well, one idea is to represent the field as a String, and use a picocli-annotated setter method that uses a `Path` type:

```
private String file;

@Parameters(arity = "1", description = "A file.")
void setFile(Path path) {
    this.file = path.toString();
}
```

Then your application deals with the String most of the time, except for this setter, which is used only for the CLI interface.

**Comment by tadayosi** [comment]
Thanks, the solution works perfect!

There is one remaining issue: the generated completion script doesn't work as 100% expected.
```
    local positionals=""
    local currIndex
    currIndex=$(currentPositionalIndex "run" "${arg_opts}" "${flag_opts}")
    if (( currIndex >= 0 && currIndex <= 2147483647 )); then
      local IFS=$'\n'
      type compopt &>/dev/null && compopt -o filenames
      positionals=$( compgen -f -- "${curr_word}" ) # files
    fi
    COMPREPLY=( $(compgen -W "${commands} ${positionals}" -- "${curr_word}") )
```

With the script when I hit TAB (the command name is `camel run`) it shows two candidate files:
```
$ camel run [TAB]
 test1.yaml test2.yaml
```
however as soon as I input `t` and hit TAB, it immediately goes to the last candidate `test2.yaml`:
```
$ camel run t[TAB] -> test2.yaml
```
even though what I expect is:
```
$ camel run test[TAB]
test1.yaml test2.yaml
```
So the generated script has some problem with completion. I suspect the beginning space ' ' of `' 'test1.yaml` in the candidates is doing something wrong.

**Comment by remkop** [comment]
Yes that looks like a problem with the generated bash completion script… Can you help figure out what the issue is?

**Comment by tadayosi** [comment]
My bad. I was fixing the issue but then found that the project still uses the previous Picocli version 4.6.3. Upgrading to 4.7.0 seems to have fixed everything. Now I think all the problem has been settled.

Thank you for your help!

**Comment by tadayosi** [comment]
@remkop

Unfortunately I found a problem with the suggested approach. `Path`/`File` -> `String` conversion only works fine until the parameter also accepts URLs such as `https://github.com/tadayosi/myproject/blob/main/hello.java`. Both `Paths.get(str)` and `new File(str)` expect `str` to be a path, so double slashes `//` are converted to single ones `/` from the internal string representation of them.

So what I would get after the following conversion is `https:/github.com/...`, and since the string is not a valid HTTP URL (`https:/...`) the subsequent code fails.
```
Parameters(arity = "1", description = "A file.")
void setFile(Path path) {
    this.file = path.toString();
}
```

So now I'd think that the suggested approach is not the ideal solution where there are some corner cases that don't work perfectly. I'd think Picocli should provide a clear solution that can solve the situlation, and it gets me back to this idea:
> Does it make sense if I contribute a FilePathCompleter as a builtin completer class which just serves as a marker, and when it's specified as completionCandidates then it falls into this condition of code generation?
> https://github.com/remkop/picocli/blob/main/src/main/java/picocli/AutoComplete.java#L789-L793

**Comment by remkop** [comment]
I see the problem but I don’t like the proposed solution. 

An alternative idea is to set a [parameter consumer](https://picocli.info/#_custom_parameter_processing) for that positional parameter, and in that consumer, populate a separate `String` field from the original command line argument (without converting to a Path and back to String). 
The `@Parameters` annotation would be on a `File` or `Path` member so that the completion script works as desired.

**Comment by tadayosi** [comment]
Thanks, interesting idea... Could you provide me with an example of how you can populate multiple `@Parameters` fields based on the values with a `ParameterConsumer` please?  The example in the doc isn't clear to me about how I can handle multiple fields.

So, the recommended approach for the cases like mine where a `@Parameters` field can be of different types is to define multiple fields with a distinct type respectively and use a `ParameterConsumer` to dispatch them based on the values. Is that correct?

**Comment by remkop** [comment]
Maybe something like this?

```java
class MyApp {

    @Parameters(parameterConsumer = MyApp.CustomConsumer.class)
    Path path; // type is Path for completion; field not actually used.
  
    String urlOrPath; // here is where we store the command line arg

    static class CustomConsumer implements IParameterConsumer {
        @Override
        public void consumeParameters(Stack<String> args, ArgSpec argSpec, CommandSpec cmdSpec) {
            if (args.isEmpty()) {
                throw new ParameterException(cmdSpec.commandLine(),
                    "Error: missing required parameter");
            }
            String arg = args.pop();
            MyApp myApp = (MyApp) cmdSpec.userObject();
            myApp.urlOrPath = arg;
        }
    }
```

**Comment by tadayosi** [comment]
Many thanks. It works!  I finally reached a satisfactory solution for the case. Thanks again for your help.
