### ISSUE TITLE
Allow inheritance of Options from ParentCommand to Subcommand on need basis.

### ISSUE THREAD

**Issue by kaushalkumar** [remkop/picocli#1890]
Hi - At present in picocli, a subcommand inherits all options of its parent command. The option in parent command is considered as global command. (Ref: https://picocli.info/#parentcommand-annotation).
We have a use case where we have a family of commands (like "backup", "backup list", "backup status"). Here backup was considered as a ParentCommand and list/status as subcommand. The "backup" command needs a required option "backupname", whereas "backup list" command does not need this "backupname".
When we use this setup then "backup list" command also inherits backupname option and thus it does not solve the purpose.

Is there any way to restrict the option to not get passed to subcommand.

**Comment by remkop** [comment]
@kaushalkumar Did that solve the issue?

**Comment by kaushalkumar** [comment]
Hey @remkop  - I apologies for the delay in my response. Yes, your suggestion/approach helped us to move forward. Thanks for your quick help.
There was one small thing noted - as the backupname was marked as optional, so the default help display content puts this option in square bracket. 

Regards,
Kaushal
