### ISSUE TITLE
Optional subcommand before required parameter?

### ISSUE THREAD

**Issue by sinux-l5d** [remkop/picocli#1892]
Hi,

this is a question.

I have a fairly simple app to try Picocli, that consist in storing snippets and retrieving them.
So I have a subcommand `myapp search <query>`, but I'd like sometimes to be more specific like `myapp search name <query>`.

I tried this so far:
```java
@Command(name = "search", description = "search in snippets name and content", mixinStandardHelpOptions = true)
public class SearchCommand implements Runnable {

    @Parameters(index = "0", description = "The query to search")
    String query;

    @Command(name = "name", description = "Search in snippets name")
    public void searchNames() {
        // processing using this.query
    }

    @Override
    public void run() {
        // processing using this.query
    }
}
```

But this result in a usage like this : `myapp search <query> name`.

Is there any way to swap `query` and `subcommand` when the later is provided?

**Comment by sinux-l5d** [comment]
Fair enough, I just wanted to avoid myself a few hyphen I guess. Thanks anyway :)

**Comment by remkop** [comment]
Great, glad that worked for you! Enjoy using picocli!
