### ISSUE TITLE
How do you know which option of the exclusive ArgGroup has been given?

### ISSUE THREAD

**Issue by MartenBE** [remkop/picocli#1899]
In the documentation, you'll find following example:

```java
@Command(name = "exclusivedemo")
public class MutuallyExclusiveOptionsDemo {

    @ArgGroup(exclusive = true, multiplicity = "1")
    Exclusive exclusive;

    static class Exclusive {
        @Option(names = "-a", required = true) int a;
        @Option(names = "-b", required = true) int b;
        @Option(names = "-c", required = true) int c;
    }
}
```

How do you know which option has been set? For example, if I specify `-b 1337` the following method gives `0 1337 0`  which is a valid `int` for each possibility which makes it so I cannot use `if else` to determine if `a`, `b` or `c` has been set.

```java
// ...
System.out.println(exclusive.a);
System.out.println(exclusive.b);
System.out.println(exclusive.c);
// ...
```

Is the solution to just use `Integer` here or is there another cleaner way?

**Comment by remkop** [comment]
Yes there are multiple ways to achieve this.

* using Integer is simple and clean: end users cannot assign a null value
* alternatively you can use an [annotated setter method](https://picocli.info/#option-parameters-methods) and put some logic in there
* finally, you can inspect the [ParseResult](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.ParseResult.html) object (obtainable from [CommandLine.getParseResult](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.html#getParseResult())) and call one of its `hasMatchedOption` or `matchedOptions` methods.

**Comment by MartenBE** [comment]
I went with `Integer` and it did the trick :) thank you for work invested in this library!
