### ISSUE TITLE
Zero bug commitment link is 404

### ISSUE THREAD

**Issue by Jiehong** [remkop/picocli#1910]
In the Readme, the Zero Bug Commitment link results in a 404: https://github.com/classgraph/classgraph/blob/latest/Zero-Bugs-Commitment.md

This happened with the removal of that file on the target project with https://github.com/classgraph/classgraph/commit/a434fb46e11f1e198a3649f08a112d16961650e3

Perhaps committing a copy in this repository could be a fix, unless a shared, independently hosted document can be found.

**Comment by remkop** [comment]
Thank you @Jiehong for raising this, and @deining for the pull request!
