### ISSUE TITLE
native image error CommandLine$InitializationException: CommandLine$AutoHelpMixin@74101cef is not a command

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#1916]
Created new ticket from @zipper01's below comment on #631: 

Same here. Code:

    import java.awt.GraphicsEnvironment;
    import java.awt.HeadlessException;
    import java.util.concurrent.Callable;
    import picocli.CommandLine;
    import picocli.CommandLine.Command;
    import picocli.CommandLine.Option;
    import com.myapp.util.SYS;
    
    @Command(name = "myapp", mixinStandardHelpOptions = true, description = "MyApp", version = "1.0")
    public class Main implements Callable<Integer> {
    
        //comman-line option to set tui mode under gui environment
        @Option(names = "--tui", description = "Use Text User Interface")
        boolean _tui;
    
        //command-line option to turn debug on
        @Option(names = "--debug", description = "Turn On Debug")
        boolean _debug;
    
        public static boolean supportGUI;
        
        static {
            try {
                supportGUI = !GraphicsEnvironment.isHeadless()
                        && GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices().length > 0;
            } catch (HeadlessException | java.lang.UnsatisfiedLinkError e) {
                supportGUI = false;
            }
        }
    
        @Override
        public Integer call() {
            //set debug
            if (_debug) {
                SYS.DBG_LEVEL = 2;
            }
    
            //set user interface
            if (supportGUI && _tui) {
                supportGUI = false;
            }
    
            if (supportGUI) {
                //Init GUI ...
            } else {
                //Init TUI ...
            }
            return SYS.ResultCode.SUCCEEDED;
        }
    
        public static void main(String args[]) {
            int exitCode = new CommandLine(new Main()).execute(args);
            System.exit(exitCode);
        }
    }

result running the generated native image it shows: _Exception in thread "main" picocli.CommandLine$InitializationException: picocli.CommandLine$AutoHelpMixin@74101cef is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations_. graalvm-ce-java17-22.3.0, picocli 4.7.0, CentOS Linux release 8.2.2004 (Core).

**Comment by remkop** [comment]
@zipper01 does the native image generate a stack trace when the error happens? Can you post this stack trace please?

If you used the `picocli-codegen` annotation processor, that should have generated a `reflect-config.json` file under `META-INF/native-image/picocli-generated/$project` during compilation.
Can you post the content of the generated `reflect-config.json` file please?

**Comment by zipper01** [comment]
@remkop Thank you. After adding the picocli-codegen plugin, the native image works fine.

**Comment by remkop** [comment]
Glad to hear that!
