### ISSUE TITLE
README.md: Travis CI badge: broken link

### ISSUE THREAD

**Issue by deining** [remkop/picocli#1918]
At the top of `README.md`, several badges are shown, amongst them a badge linking to Travis CI. When clicking on this badge, you are encountering `404 Page or file not found`. As far as I can see, picocli does not use Travis CI for build checks any more. Can the travis build badge be removed or do you want to keep it for historical reasons? If so, the link where the badge points to should be corrected to `https://app.travis-ci.com/github/remkop/picocli`.

**Comment by remkop** [comment]
I think it is fine to remove it. As you said, it is not used any more. Thanks for raising this, I had completely forgotten about it! 😅
