### ISSUE TITLE
How does picocli know to turn colors on?

### ISSUE THREAD

**Issue by rnveach** [remkop/picocli#1922]
Identified at https://github.com/checkstyle/checkstyle/pull/12545 ,

It was identified at https://github.com/checkstyle/checkstyle/pull/12545#issuecomment-1378719744 , that when our project's tests on Git Bash on Windows, which in turn run picocli and look at it's output, the picocli part of the run in the tests differed than the expected results and failed the run.

The command being run is: `mvn clean verify`

After testing, it was identified at https://github.com/checkstyle/checkstyle/pull/12545#issuecomment-1380783716 , that it is actually colors causing the difference in the output. By using `Ansi.OFF`, running our tests in Git Bash passed and there was no longer differences on color.

The question comes because I was not seeing colors anywhere else until I used Git Bash. Power Shell, Command Prompt, and Eclipse IDE were not having issues and did not show colors. I assume picocli defaults to colors is `auto`/`on` but only if the environment supports it.

We are currently thinking over if we will disable colors completely in our picocli usage. If there is a way to identify when colors might be used and just fail a test with a message, however, we aren't sure how to do this.

Hence the question, how does picocli know when to turn on colors?

Also, just to note, I tried running maven with `-B` and `--batch-mode` which is suppose to disable colors, but picocli ignores it. That may be a bug.

Edit: I apologize, I forgot about "Discussions" and this probably would have been better there.

**Comment by remkop** [comment]
Picocli uses some heuristics to determine whether to emit ANSI escape sequences or not.
They are documented here:
https://picocli.info/#_heuristics_for_enabling_ansi

Git Bash on Windows is capable of displaying colors correctly, so picocli will emit ANSI escape sequences in that environment.
You may be able to configure your tests with environment variables.

**Comment by remkop** [comment]
@rnveach Does that answer your question?

**Comment by rnveach** [comment]
Yes it does, thanks.

I assume there is no easy access method in picocli to check if colors will be on or not?

One last question is, how is colors controlled through the CLI? Does it use the ESCAPE character?

**Comment by remkop** [comment]
> I assume there is no easy access method in picocli to check if colors will be on or not?

There is: you can call [`CommandLine.Help.Ansi.enabled()`](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Help.Ansi.html#enabled()) which returns a boolean value, `true` if picocli will emit ANSI escape sequences in this environment.

> 
> One last question is, how is colors controlled through the CLI? Does it use the ESCAPE (`\u001B`) character?

Yes, correct.
If you are interested in the internals, see the [Ansi](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Help.Ansi.html) class, [Ansi.Style](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Help.Ansi.Style.html) class (for parsing [markup strings](https://picocli.info/#_usage_help_with_styles_and_colors)) and the [Ansi.Text](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Help.Ansi.Text.html) class for working with text sequences, which may contain styled markup subsequences.

**Comment by rnveach** [comment]
Thank you for your assistance. We are going to decide what to do in https://github.com/checkstyle/checkstyle/issues/12667 .

**Comment by adriens** [comment]
:clap:
