### ISSUE TITLE
Support optional fundamental types

### ISSUE THREAD

**Issue by JanStureNielsen** [remkop/picocli#1927]
In v4.7, there is first-class support for `java.util.Optional<T>`:

```
@Option(
    names        = {"--manager"},
    paramLabel   = "id",
    defaultValue = CommandLine.Option.NULL_VALUE,
    description  = "manager id (default: <current user>)")
private Optional<Long> managerId;
```

which is really nice. It would be a little nicer if optional fundamental types also had first-class support:

```
@Option(
    names        = {"--manager"},
    paramLabel   = "id",
    defaultValue = CommandLine.Option.NULL_VALUE,
    description  = "manager id (default: <current user>)")
private OptionalLong managerId;
```

That is, add support for:

```
java.util.OptionalDouble
java.util.OptionalInt
java.util.OptoinalLong
```

In my case, calculating `<current user>` requires the application to fully start so I cannot provide the actual value at start-up. Initially, I used -1 as a moniker value but optional values make the implementation a bit cleaner, and optional fundamental types removes a few un/boxing operations.

**Comment by remkop** [comment]
@JanStureNielsen Thank you for raising this!

You can already achieve this with the current version of picocli, as follows:

```java
CommandLine commandLine = new CommandLine(new MyApp())
        .registerConverter(OptionalDouble.class, s -> OptionalDouble.of(Double.parseDouble(s)))
        .registerConverter(OptionalInt.class, s -> OptionalInt.of(Integer.parseInt(s)))
        .registerConverter(OptionalLong.class, s -> OptionalLong.of(Long.parseLong(s)));

int exitCode = commandLine.execute(args);
```

**Comment by JanStureNielsen** [comment]
That works for me -- thanks, @remkop!

**Comment by remkop** [comment]
Picocli will never pass a `null` value to the converter, so you can simplify that to `OptionalLong.of(Long.parseLong(s))`.

Did you get a NullPointerException? If so, can you show the stack trace please?
