### ISSUE TITLE
Return status code different from zero when there is an error

### ISSUE THREAD

**Issue by fabio-franco** [remkop/picocli#1928]
Picocli always returns status code 0, even when an error happens. For example, I forced an error by not passing an option value:

```
./myCLI myOption -s
Missing required parameter for option '--srcdir' (<path>)
```
And then, checking the status code, it's zero:
```
echo $?                
0
```
I'm wondering if Pococli could return status 1 when an issue happens. That would be very useful for automation purposes. For instance, I have some automation and I am relying on the status code to know that an issue happened.

**Comment by remkop** [comment]
This should not happen. 
Picocli’s `execute` method returns a non-zero value if required options are missing. 
Your application should call `System.exit` with the return value of the `execute` method. 

```java 
int exitCode = new CommandLine(new MyApp()).execute(args);
System.exit(exitCode);
```

Can you show what your code looks like?

**Comment by fabio-franco** [comment]
I'm so sorry, I did a mistake. The tests did not include the `System.exit(exitCode);` as you mentioned. I fixed that and Picocli is working very well. sorry about the false alarm.

**Comment by remkop** [comment]
Great, glad to hear it works as expected. 😅

Enjoy picocli!
