### ISSUE TITLE
Add support for Options that can only come from the environment

### ISSUE THREAD

**Issue by sewe** [remkop/picocli#1954]
ATM, it is quite easy to implement an `@Option` that, if it not given on the command-line, is instead looked up in an environment variable. All it takes is `defaultValue = "${env.OPTION_VARIABLE}"`. With this scheme, however, you get an either/or behavior: _Either_ you supply the option on the command-line _or_ you fall back onto the environment.

What is much trickier to implement is using the _union_ of environment variable(s) and explicit command-line option.

The best workaround I could come up with is the following:

```java
@Option(names = "--url", paramLabel = "URL")
private List<URI> urlsFromCommandLine;

@Option(names = "URLS_OPTION_VARIABLE", paramLabel = "URLs", //
	hidden = true, //
	defaultValue = "${env:URLS_OPTION_VARIABLE}",
	split = "\s+")
private List<URI> urlsFromEnvironment;
```

This allows you to use zero or more `--url` command-line options but also parses the `URLS_OPTION_VARIABLE` into zero or more URLs (splitting on whitespace).

The advantage of the above is that you get good error messages using the same format as those for the `--url` command-line option:

```
Invalid value for option 'URLS_OPTION_VARIABLE' (URLs): cannot convert '%%' to URI (java.net.URISyntaxException: Malformed escape pair at index 0: %%
```

The disadvantage is that, while the `URLS_OPTION_VARIABLE` is `hidden`, it is still parsed as an option. In particular, you cannot have a file called `URLS_OPTION_VARIABLE` assigned to a positional `@Parameter` which is certainly non-obvious to the user should they ever find themselves in this situation.

Hence this **feature request**: Maybe we could have `names`-less `@Option`s that then can only get assigned via their `defaultValue`? Or perhaps it is even worth adding a dedicated `@EnvironmentVariable` annotation to picocli?

FWIW, I also considered the following **alternative** (in fact, I am using it due to the aforementioned disadvantage): parsing the environment variable manually similar to https://picocli.info/#_validating_option_combinations in the body of the `run` method.

But that gets awkward if you want to re-use the `TypeConverter`:

```java
urlsFromEnvironment = Stream.ofNullable(System.getenv("URLS_OPTION_VARIABLE"))
	.flatMap(Splitter.on(CharMatcher.whitespace())::splitToStream)
	.map(option -> {
		try {
			return ... // Unfortunately, no access to the converter registry.
		} catch (TypeConversionException e) {
			throw new ParameterException(spec.commandLine(), e.getMessage(), e);
		}
        }).collect(toList());
```

Moreover, you manually have to make sure that a `ParameterException` rather than a `TypeConversionException` leaves `run()` to get the default error behavior showing the usage help. If you let the `TypeConversionException` "escape", picocli just prints the raw stack trace.

**Comment by remkop** [comment]
That’s an interesting use case but I don’t think it should be supported in the library. 

The solution that you found looks very nice to me. It’s pretty concise at 9 lines of code, and it expresses its intent quit clearly. It even leverages the fact that one can throw a ParameterException from the business logic to get user-facing errors that look like the built-in validation. 

On the other hand, building support for this in the library would easily be a source of confusion. What is the difference between a nameless option and a positional parameter? (And why not use positional parameters for this use case?)

So, it’s an interesting idea but I don’t think it’ll be incorporated in the library.

**Comment by sewe** [comment]
> On the other hand, building support for this in the library would easily be a source of confusion. What is the difference between a nameless option and a positional parameter? (And why not use positional parameters for this use case?)

I agree that positional parameters and "nameless" options are quite different things, but I think this is really about how you phrase it in the API.

I think something along the lines of a dedicated `defaultOnly` annotation property would be clearest:

```java
@Option(names = "URLS_OPTION_VARIABLE", paramLabel = "URLs",
	hidden = true,
	defaultValue = "${env:URLS_OPTION_VARIABLE}",
	defaultOnly = true,
	split = "\s+")
private List<URI> urlsFromEnvironment;
```

As I imagine it, the property would be orthogonal to `hidden`; while most of the time you want to hide a `defautOnly` option from the automatically generated usage help and display something custom instead, sometimes the automatically generated desciption might be enough, particular if using `${DEFAULT-VALUE}` in the description.

That being said, whether to support something like `defaultOnly` certainly depends on how many implicit assumptions in the existing code are violated by it. If this admittedly somewhat niche feature would require a major restructuring, then I would agree that it's not worth it.

It's your call, of course.

**Comment by sewe** [comment]
One more reason why it would be great to have this as special kind of `@Option`: With `@ArgGroup(validate = false, heading = "Environment Variables")` it is super-easy to add them the environment variables in a [dedicated section to the usage help](https://picocli.info/#_option_sections_in_usage_help).

Using the low-level [`getHelpSectionMap()` API](https://picocli.info/#_custom_help_section_example) instead is rather cumbersome. This is particularly true if your environment variables are spread out across across multiple mix-ins, as you _still_ need to know the full list of environment variables in one place when installing the section renderer (following [`EnvironmentVariablesSection.java`](https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/customhelp/EnvironmentVariablesSection.java)). So you would either have to write some logic the queries the various mix-ins or duplicate the list of variables.

**Comment by remkop** [comment]
Every feature comes with trade-offs.
In this case, I estimate that the potential target audience is quite small (this is a niche feature), and the benefits don't outweigh the drawbacks.

It is not that the desired functionality cannot be achieved with the existing version of picocli, this request is about making this more convenient, and generally I err on the side of not providing more convenience mechanisms.

So I will close this ticket as won't-do.

Thank you for raising this and for the thoughtful and interesting discussion!
