### ISSUE TITLE
Links in the apidocs are broken

### ISSUE THREAD

**Issue by deining** [remkop/picocli#1957]
I just realized that many links in the apidocs are broken. E.g. have a look at the api doc page for  annotation type [CommandLine.Option](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Option.html):

At the top of the page you will see these two failing links (many more in the further course of the page):

[@Retention](https://docs.oracle.com/en/java/javase/11/docs/api/java/lang/annotation/Retention.html?is-external=true)([RUNTIME](https://docs.oracle.com/en/java/javase/11/docs/api/java/lang/annotation/RetentionPolicy.html?is-external=true#RUNTIME))

Investigating the problem, I realized that `/module-name/` is part of the link. The broken link incorrectly uses module name `java`, it should be `java.base`. I guess we can overcome this problem by customizing the `javadoc` task in `/gradle/docs.gradle`. Haven't looked into this in detail though.

@remkop: can you have a look please? Thanks.

**Comment by remkop** [comment]
Interesting! Thanks for raising this.

I see:

https://docs.oracle.com/en/java/javase/11/docs/api/java/lang/annotation/Retention.html (actual)
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Retention.html (correct)

I do use Java 11 to create the Javadoc, logic is here:
https://github.com/remkop/picocli/blob/main/gradle/modular-javadoc.gradle

Strange that the Javadoc tool for Java 11 creates broken links to pages in Oracle's Java 11 javadoc... 
Maybe there is some javadoc option that needs to be specified. I will look in more detail later.

**Comment by remkop** [comment]
Great find! I was using Java 11 (no minor version)

```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

So upgrading to a later minor version may fix this! Thank you for investigating. I will try this soon.
