### ISSUE TITLE
newbie question about option names override for arg groups. 

### ISSUE THREAD

**Issue by ajantha-bhat** [remkop/picocli#1967]
Hi, as mentioned in the PR description. I am new to picocli. 
I did go through the documentation and didn't find examples of what I was looking for. 

```
class CatalogOptions {
    @CommandLine.Option(names = "--catalog-type")
    String type;
    
    @CommandLine.Option(names = "--catalog-prop")
    Map<String, String> properties;
}
```

In the main command, I need to have two instances of this `CatalogOptions`.

```
@CommandLine.ArgGroup(
      exclusive = false,
      multiplicity = "1",
      heading = "source catalog options: %n")
  private CatalogOptions sourceCatalogOptions;

  @CommandLine.ArgGroup(
      exclusive = false,
      multiplicity = "1",
      heading = "target catalog options: %n")
  private CatalogOptions targetCatalogOptions;
```

Is it possible to override the option names of `--catalog-type` into `--source-catalog-type` and `--target-catalog-type`
and `--catalog-prop` into `--source-catalog-prop` and `--target-catalog-prop` in the arg group? 

If I am using it wrongly. please suggest to me how to achieve the same without duplicating `CatalogOptions`?

**Comment by remkop** [comment]
Hi @ajantha-bhat, thanks for asking!

I don't think what you are asking is possible in picocli; I would recommend just having a separate class with different option names in the annotations.

**Comment by ajantha-bhat** [comment]
@remkop: Thanks for the clarification.
