### ISSUE TITLE
Enforcement of required arguments in Option sections?

### ISSUE THREAD

**Issue by galaxyrise** [remkop/picocli#1972]
This request may reflect my own misunderstanding of how to use Option Sections, but I'd be grateful for some feedback.  Please see the code below... is there any way to have picocli enforce `required = true` for the argument in SectionOne?  (Removing `validate = false` does not help.)  Thanks!

To clarify my objective: I have code that contains a large number of arguments and I was trying to follow the guidance in the manual on using ArgGroups to better organize the help message using subheadings.

```
public class PicocliTest implements Runnable {
	@Option(names = {"-o"}, required = true)
	protected File fileOutput;
	
	@ArgGroup(validate = false, heading = "%n== Group#1 ==%n")
	SectionOne sectionOne;
	static class SectionOne {
		@Option(names = {"-i"}, required = true)
		protected File fileInput;
	}

    @Override
    public void run() {}
    
    public static void main(String[] args) {
        new CommandLine(new PicocliTest()).execute(args);
    }
}
```

**Comment by remkop** [comment]
Hi @galaxyrise, thank you for raising this!
You can try `@ArgGroup(multiplicity = "1")` (removing the `validate = false`).
That will require the group to be specified at least once, and the `-i` option is required within the group, so that should make the `-i` option required within the command as a whole.

**Comment by galaxyrise** [comment]
Hello @remkop, thanks for the rapid response!  Your suggestion partially works for my toy example, except that it doesn't actually inform the user that the `-i` argument is required unless they have supplied the required `-o` argument that exists outside the section.  It also doesn't seem to extend to my "real world" use cases where I have multiple required arguments within one or more "Option Sections".  

Is picocli unable to handle this use case?

**Comment by remkop** [comment]
Hi @galaxyrise, no worries, discussing here is fine. 😊

After making the changes I suggested, the usage help looks like this:

```
Usage: <main class> -o=<fileOutput> -i=<fileInput>
```

This shows that the `-o` option is `required`, and the arg group (containing `-i`) is required, so both are required and that is what the usage help is showing. I thought that that was your intention, based on the original example.

But with your new comment, I understand your intention is actually different, and what you want is:

> (...) the `-i` argument is required unless they have supplied the required `-o` argument that exists outside the section.

This sounds like you want to have mutually [exclusive groups](https://picocli.info/#_mutually_exclusive_options), one containing the `-o` option, and the other containing the `-i` option.

> It also doesn't seem to extend to my "real world" use cases where I have multiple required arguments within one or more "Option Sections".
> 
> Is picocli unable to handle this use case?

What makes you say "it doesn't seem to extend to my real use case with multiple required arguments within one or more groups"? Can you clarify what the problem is you are encountering?

**Comment by remkop** [comment]
By the way, groups can contain other groups, they can be nested.

Some examples: 
* https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/arggroup/CompositeGroupDemo.java
* https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/arggroup/SO61203155.java
* https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/arggroup/SO61963756.java

**Comment by galaxyrise** [comment]
Apologies, I think I oversimplified my initial example to the point where it distracted from my real intent.  I've added an expanded version below that is closer to my real use case, but I'll describe it more clearly here as well:

- My CLI has roughly 20 arguments (complex bioinformatics tool)
- In order to make the usage help more readable I would like to organize those arguments by subgroup (e.g. 'input options', 'output options', 'tuning parameters').  
  - These subgroups are _not mutually exclusive_, just a means to improve readibility in the usage help.  
  -  They also contain mixtures of required and optional Options
- I tried following the guide ([section 8.3.1 Use Heading to Enable Option Sections](https://picocli.info/#_option_sections_in_usage_help)), but I eventually realized that this approach did not enforce `required = true`
- The solutions proposed above do not appear handle this use case
- As a side note, you mentioned that for my toy example your proposed change does show that the options are required.  This is true, but when no arguments are supplied it reports `Missing required option: '-o=<fileOutput>` right before showing the usage (rather than the desired `Missing required options: '-o=<fileOutput>', '-i=<fileInput>`).

```
public class PicocliTest implements Runnable {
	
	@ArgGroup(validate = false, heading = "%n== Section One Options ==%n")
	SectionOne sectionOne;
	static class SectionOne {
		@Option(names = {"-a"}, required = true)
		protected String sectionOneArgOne;
		
		@Option(names = {"-b"}, required = true)
		protected String sectionOneArgTwo;
		
		@Option(names = {"-c"})
		protected boolean sectionOneArgThreeOptional;
	}
	
	@ArgGroup(validate = false, heading = "%n== Section Two Options ==%n")
	SectionTwo sectionTwo;
	static class SectionTwo {
		@Option(names = {"-d"}, required = true)
		protected String sectionTwoArgOne;
		
		@Option(names = {"-e"}, required = true)
		protected String sectionTwoArgTwo;
		
		@Option(names = {"-f"})
		protected String sectionTwoArgThree;
	}

    @Override
    public void run() {}
    
    public static void main(String[] args) {
    	args = new String[] {"-a", "ok"};
        new CommandLine(new PicocliTest()).execute(args);
    }
}
```

**Comment by remkop** [comment]
Thanks for the clarification!

If the main goal is to make the usage help message more readable, and the use of ArgGroups has unintended side effects that are not acceptable, then perhaps we should consider another approach.

One idea is the customize the usage help message in a different way.
There is another way to do this that is not covered in the user manual, which is to subclass the [`CommandLine.Help` class](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Help.html) and override the method that is responsible for generating the options list. (One of the `optionList()` methods.)

Some examples are in the [customhelp directory](https://github.com/remkop/picocli/tree/main/picocli-examples/src/main/java/picocli/examples/customhelp) of the `picocli-examples` subproject:

https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/customhelp/CustomParamList.java

https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/customhelp/HideOptionParams.java[optionList](https://picocli.info/apidocs-all/info.picocli/picocli/CommandLine.Help.html#optionList())()

**Comment by galaxyrise** [comment]
Thanks very much.  I will give your suggestion a try.
