### ISSUE TITLE
RepeatableCommands=true, need for repeatableCommandArity="0..1"

### ISSUE THREAD

**Issue by sergproua** [remkop/picocli#1981]
I've created simple spring boot app which takes two commands A and B, each with required option -r and enabled repeatable commands so that I can run it with arguments 'A -r 1 B -r 2'

Everything works great however when I run with arguments 'A -r 1 B -r 2 B -r 3'

Issue: my command B is executed twice with the value 3 instead of 2 and 3

Feature request: I'd like to prevent the command listed multiple times, is it possible?

Repo is here
https://github.com/sergproua/learn-picocli

**Comment by remkop** [comment]
You may have found a bug.

It is still unclear to me whether the bug is Spring-related (Spring may be caching the instance of `CommandB` so the same instance gets reused for the second `B` commandline argument), or whether there is an issue in the picocli parsing logic.

**Comment by remkop** [comment]
> Feature request: I'd like to prevent the command listed multiple times, is it possible?

This may be a duplicate of https://github.com/remkop/picocli/issues/1194; 
can you check if the suggested solution works for you?

**Comment by sergproua** [comment]
> > Issue: my command B is executed twice with the value 3 instead of 2 and 3
> 
> You may have found a bug.
> 
> It is still unclear to me whether the bug is Spring-related (Spring may be caching the instance of `CommandB` so the same instance gets reused for the second `B` commandline argument), or whether there is an issue in the picocli parsing logic.

It is Spring @Component, Singleton scope used by default. I added below and it is working as expect. 

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)

Thanks!
Serge

**Comment by sergproua** [comment]
> > Feature request: I'd like to prevent the command listed multiple times, is it possible?
> 
> This may be a duplicate of #1194; can you check if the suggested solution works for you?



> > Feature request: I'd like to prevent the command listed multiple times, is it possible?
> 
> This may be a duplicate of #1194; can you check if the suggested solution works for you?

Yes, #1194 solution works however it executes first command then second then throws an error. I think it is ok to close this ticket and I'll propose a better solution in that ticket. 

Thanks!

**Comment by sergproua** [comment]
duplicate of #1194
