### ISSUE TITLE
Does picocli support dynamic set prompt?

### ISSUE THREAD

**Issue by lucas-myx** [remkop/picocli#1983]
hi @remkop ,May I ask you a question：
Does picocli support the modification prompt function, based on input from the previous command.
similar to the following: （`picocli> `is the default prompt）
```
picocli> _
picocli> ls -o orderInfoApi
.......
picocli> orderInfoApi> ls -o userInfoApi
.......
picocli> userInfoApi> _
```

I think this can easily inform the user under which API they are currently operating.
Thank you very much for any suggestions!

**Comment by remkop** [comment]
This sounds more like a JLine question than a picocli question. 

I assume you are using [picocli-shell-jline2](https://github.com/remkop/picocli/tree/main/picocli-shell-jline2) or [picocli-shell-jline3](https://github.com/remkop/picocli/tree/main/picocli-shell-jline3)?

Please check the JLine API for a method like `setPrompt(String)`; from memory I believe something like this should be there.

**Comment by lucas-myx** [comment]
Yes, I am using picocli-shell-jline3, thank you for your suggestion!
