### ISSUE TITLE
hiding variable names should be default in help output

### ISSUE THREAD

**Issue by kenyee** [remkop/picocli#1984]
Hiding the variable names as described here:
https://stackoverflow.com/questions/65130421/picocli-cli-parser-hide-the-java-variable-name-while-rendering-the-output

should be the default behavior IMHO.  I can't see why anyone would want the current default behavior...
e.g., if you use a parser for the option, it prints this out:
```
  -d, --baseDirectory=<baseDirectory$parser>
```

Not sure why you'd ever want to show the $parser bit unless you're in some sort of parser debug mode...

**Comment by remkop** [comment]
Interesting question.

How did you get that variable name `baseDirectory$parser`? That's an unusual variable name!

Also, please be aware, you can customize unhelpful variable names with the [`paramLabel` annotation attribute](https://picocli.info/#_parameter_labels).

Most CLI tools that I am aware of do display a parameter label for options that take a parameter.
This communicates to users that the option takes a parameter (as opposed to boolean flags) and gives a hint as to what kind of information the user should provide (a number, a String, a URL, file name, directory, etc).

Some examples: [ping](https://linux.die.net/man/8/ping), [ls](https://man7.org/linux/man-pages/man1/ls.1.html) and [git](https://git-scm.com/docs/git).

So, I am curious why you believe that hiding the option parameter label should be the default.

**Comment by kenyee** [comment]
> How did you get that variable name baseDirectory$parser? That's an unusual variable name!

```
    @CommandLine.Option(
        names = ["-d", "--baseDirectory"],
        required = true,
        description = ["Base directory from the repo (useful for mono-repos)"],
        defaultValue = ".",
        showDefaultValue = CommandLine.Help.Visibility.ALWAYS,
        scope = CommandLine.ScopeType.INHERIT,
    )
    internal fun setBaseDirectory(dir: String) {
        baseDirectory = dir
    }
```

Thanks...paramLabel would cover what I'd want to do (mainly to hide that ugly variable name) :-)
Might be worth hiding the variable name if it's a method?

**Comment by remkop** [comment]
Oh interesting!
Picocli takes the `@Option`-annotated method name and uses its "property name" (remove leading `get`  or `set` and decapitalize the remainder) as the auto-generated parameter label.

Still, in the example you provided, that should result in picocli generating the label `baseDirectory`, so I still wonder where the `$parser` bit comes from...

Unless the method name `setBaseDirectory$parser`  is somehow generated by Kotlin? Hm, curious. 

Glad to hear that explicitly specifying the `paramLabel` string solves the issue for you.

**Comment by kenyee** [comment]
Yep, it's a kotlin'ism....which is why the default didn't work 🙂

**Comment by remkop** [comment]
Okay, I did some reading and it seems that Kotlin does "name mangling" for members of `internal` classes so they cannot easily be called from Java. Apparently that is implemented by appending `$<SOMESTUFF>` to the method name.

I will look at truncating the `$` and everything following it from the method name when inferring `paramLabel` from method names.

**Comment by remkop** [comment]
@kenyee 

I pushed a fix for this, and from the next version of picocli (4.7.2), the `$` and everything following it will be removed from the automatically generated `paramLabel` for annotated methods.

Thank you again for raising this.
