### ISSUE TITLE
Add support for mutual exclusive options

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#199]
Something like this:

```java
@Command(autoHelp = true, sortOptions = false, groups = {
@OptionGroup(name = "dest", required = true, exclusive = true,
           heading = "Destination: The data can be sent either to a file or to a socket"),
@OptionGroup(name = "other",
           heading = "Other:%n  Some other options")})
class ExclusiveOptionsExample {

  @Option(names = "-f", description = "Target file", group = "dest")
  File file;
  
  @Option(names = "-s", description = "Target socket", group = "dest")
  InetAddress adr;
  
  @Option(names = "-d", description = "Data file", group = "other")
  File data;
}
```

Usage help:
```
Usage: <main class> [-hV] [-d=<data>] (-f=<file> | -s=<adr>)
Destination: The data can be sent either to a file or to a socket
  -f= <file>                  Target file
  -s= <adr>                   Target socket
Other:
  Some other options
  -d= <data>                  Data file
  -h, --help                  Show this help message and exit.
  -V, --version               Print version information and exit.
Commands:
  help  Displays help information about the specified command
```

**Comment by remkop** [comment]
```
Index: src/main/java/picocli/CommandLine.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/picocli/CommandLine.java	(revision )
+++ src/main/java/picocli/CommandLine.java	(revision )
@@ -1406,8 +1406,15 @@
          * is set {@code true} on the command. Use this attribute to specify whether the default value
          * for this specific option should always be shown or never be shown, regardless of the command setting.
          * @return whether this option's default value should be shown in the usage help message
-         */
+         * @since 3.0 */
         Help.Visibility showDefaultValue() default Help.Visibility.ON_DEMAND;
+
+        /** The group that this option belongs to. By default options are not grouped. Specify the name of the
+         * {@link OptionGroup OptionGroup} for this option if this option is part of a mutually exclusive set of options
+         * or if you want to group options in the usage help message.
+         * @return name of the {@link OptionGroup OptionGroup} this option belongs to
+         * @since 3.0 */
+        String group() default "";
     }
     /**
      * <p>
@@ -1532,7 +1539,7 @@
          * is set {@code true} on the command. Use this attribute to specify whether the default value
          * for this specific positional parameter should always be shown or never be shown, regardless of the command setting.
          * @return whether this positional parameter's default value should be shown in the usage help message
-         */
+         * @since 3.0 */
         Help.Visibility showDefaultValue() default Help.Visibility.ON_DEMAND;
     }
 
@@ -1613,6 +1620,43 @@
         String name() default "";
     }
 
+    /** <p>OptionGroups can be used to define mutually exclusive options, or a group of options of which at least one
+     * must be specified, or they can simply be used to control the layout of options in the usage help message.</p>
+     * <pre>
+     * &#064Command(autoHelp = true, sortOptions = false, groups = {
+     * &#064OptionGroup(name = "dest", required = true, exclusive = true,
+     *              heading = "Destination: The data can be sent either to a file or to a socket"),
+     * &#064OptionGroup(name = "other",
+     *              heading = "Other:%n  Some other options")})
+     * class ExclusiveOptionsExample {
+     *     &#064Option(names = "-f", description = "Target file", group = "dest")
+     *     File file;
+     *
+     *     &#064Option(names = "-s", description = "Target socket", group = "dest")
+     *     InetAddress adr;
+     *
+     *     &#064Option(names = "-d", description = "Data file", group = "other")
+     *     File data;
+     * }</pre>
+     * @since 3.0
+     */
+    @Retention(RetentionPolicy.RUNTIME)
+    @Target({ElementType.TYPE, ElementType.LOCAL_VARIABLE, ElementType.PACKAGE})
+    public @interface OptionGroup {
+        /** Option group name, used to refer to the group from {@link Option#group} */
+        String name();
+        /** Returns whether the group is required, that is, if at least one of the options in the group must be specified.
+         * @return {@code true} if at least one of the options in the group must be specified, {@code false} otherwise */
+        boolean required() default false;
+        /** Returns whether the group is exclusive, that is, no two options in this group may be specified together.
+         * @return {@code true} if the options in this group are mutually exclusive, {@code false} otherwise */
+        boolean exclusive() default false;
+        /** Returns the usage help heading of this group, or an empty string if this group has no heading in the usage help.
+         * @return the usage help heading of this group, or an empty string
+         */
+        String heading() default "";
+    }
+
     /**
      * <p>Annotate your class with {@code @Command} when you want more control over the format of the generated help
      * message.
@@ -1807,6 +1851,11 @@
          * @return text to display after the list of options
          * @see Help#footer(Object...) */
         String[] footer() default {};
+
+        /** Returns the option groups for this command, if any.
+         * @return an array of {@link OptionGroup OptionGroups}, or an empty array if this command has no option groups
+         * @since 3.0 */
+        OptionGroup[] groups() default {};
     }
     /**
      * <p>
@@ -2115,8 +2164,8 @@
             Class<?> cls = command.getClass();
             boolean hasCommandAnnotation = false;
             while (cls != null) {
-                hasCommandAnnotation |= updateCommandAttributes(cls, result, factory);
                 hasCommandAnnotation |= initFromAnnotatedFields(command, cls, result, factory);
+                hasCommandAnnotation |= updateCommandAttributes(cls, result, factory);
                 cls = cls.getSuperclass();
             }
             validateCommandSpec(result, hasCommandAnnotation, command);
```

**Comment by lenkite** [comment]
Also:  Sometimes its common to have a single option as an alternative with a group of options. Like in the below `-u`, `-p`, `-c` are only required if `-P` (profile) is not present.
```
list-nodes -c <controlHost> -u <user> -p <pass>  OR list-nodes -P <profileName>
```

**Comment by kravemir** [comment]
Would this support something like `[( --json-def | --std-def | ( [--prop-a] [--prop-b] [--prop-c] ...))]`? Ie. pass configuration as;

* option for each property: `--prop-a`, `--prop-b`, `--prop-c`,
* json file with definition: `--json-def`,
* name of standard definition: `--std-def`.

And, it would be good to support multiple groups.

**Comment by NicolasMassart** [comment]
Would this only concern required options or could we imagine indicating exclusive option like -a can't be used if -b is defined ?

**Comment by remkop** [comment]
Individual options and option groups will have both a `requires` and an `excludes` attribute where the name of other options (or other groups) to require or exclude can be specified. 

Use cases like “if `-a` is specified, `-b` is excluded” will certainly be supported, as well as  “if `-a` is specified, `-b` is required”.

**Comment by remkop** [comment]
A first cut of support for `ArgGroup`s has landed in master. This adds support for:

* mutually exclusive options and positional parameters
* co-occurring options and positional parameters (require all elements in the group, or none)
* composite groups

Example:
 
```java
 @Command(argGroups = {
         @ArgGroup(name = "EXCL",      exclusive = true,  required = true),
         @ArgGroup(name = "ALL",       exclusive = false, required = true),
         @ArgGroup(name = "COMPOSITE", exclusive = false, required = false,
                   subgroups = {"ALL", "EXCL"}),
 })
 class App {
     @Option(names = "-x", groups = "EXCL") boolean x;
     @Option(names = "-y", groups = "EXCL") boolean y;
     @Option(names = "-a", groups = "ALL") boolean a;
     @Option(names = "-b", groups = "ALL") boolean b;
 }
```
 
This defines a composite group with the following synopsis:
```
 [(-x | -y) (-a -b)]
```

The composite group consists of the required exclusive group `(-x | -y)` and the required co-occurring group `(-a -b)`.

Valid user input for this group would be:
* no options at all (because the composite group itself is non-required)
* -x -a -b (in any order)
* -y -a -b (in any order)

Any other combination of -x, -y, -a and -b would give a validation error.

----
Still TODO:
* show group synopsis in usage help message 
* show group headings in options list
* documentation in user manual

That said, the majority of the functionality is there.
I would appreciate it if people would try this to see if it meets their requirements and to find any places where the API should be improved.

**Comment by remkop** [comment]
# Back to the drawing board

The current design works well for many cases, but it has two major drawbacks:
* it does not play nice with positional parameters
* it does not support repeating groups

## Positional Parameters
Example:
```java
@Command(argGroups = @ArgGroup(name = "x", exclusive = false))
class App {
    @Option(names = "-a", groups = "x") int a;
    @Parameters(index = "0", groups = "x") File file;
    @Parameters(index = "1") String string;
}
```
This gives a command with the following synopsis:
```
<cmd> [-a=<a> <file>] <string>
```
Based on the synopsis, we expect that both of the following invocations are valid:

```
# this works fine
<cmd> -a=123 /my/file somestring

# this fails: "Missing parameter <string>"
<cmd> somestring
```
The seconds invocation fails, because the "somestring" argument is assigned to the first positional parameter, the positional parameter with index 0, which is the `file` field...

The current parser implementation is not `ArgGroup`-aware; `ArgGroup`s are validated _after_ the parser completes. This is clearly not sufficient.

## Repeating Groups
This relates to #358. A common use case is to allow repeating groups of arguments.

Example: the Groovy `grape` command line tool:
```
grape resolve [-adhisv] (<groupId> <artifactId> <version>)...
```

This command can accept repeating groups of `groupId`, `artifactId`, and `version` positional parameters. 

 Another example could be where a combination of options and positional parameters form a repeating group:

```
<cmd> (--mode=MODE <file>)...
```
To illustrate, a concrete invocation of a command with repeating composite arguments could look like this:
```
<cmd> --mode=SOFT ~/input1 --mode=BRITTLE ~/input2 --mode=STEADY ~/input3
```
We would need some way to capture the repeated combination of option and positional parameter in a collection. Instead of having separate collections for each option or positional parameters, I think it makes more sense to model the group itself with a class, and have a collection of this grouping class:

```
@Command
class App {
    @ArgGroup(exclusive = false, validating = true, arity = "1..*",
              heading = "This is the options list heading (See #450)", order = 1)
    List<MyComposite> compositeArguments;

    private static class MyComposite {
        @Option(name = "--mode") Mode mode; // where Mode is an enum
        @Parameters(index = "0") File file;
    }
}
```

In this new proposed model, the `required` boolean has been replaced with an `arity` attribute, which allows values like `"0..*"` for optional repeating groups, `"1..*"` for mandatory repeating groups, or some specified number of minimum and maximum occurrences. The `exclusive`, `validate`, `heading` and `order` attributes still work exactly as before.

In this model, an option or positional parameter can no longer belong to multiple groups. I'm not sure yet if this is a good or a bad thing.

Groups can still be composed, for example:

```
@Command
class App {
    @ArgGroup(exclusive = false, arity = "0..1") CompositeGroup compositeGroup;
}

class CompositeGroup {
    @ArgGroup(exclusive = true, arity = "1") ExclusiveGroup exclusiveGroup;
    @ArgGroup(exclusive = false, arity = "1") CooccurringGroup cooccurringGroup;
}

class ExclusiveGroup {
     @Option(names = "-x") boolean x;
     @Option(names = "-y") boolean y;
}

class CooccurringGroup {
     @Option(names = "-a") boolean a;
     @Option(names = "-b") boolean b;
 }
````
This defines a composite group with the following synopsis:
````
 [(-x | -y) (-a -b)]
````

Thoughts?

**Comment by remkop** [comment]
Continuing from the previous comment...

Another aspect that the new model needs to cover is programmatic access. 

Applications that dynamically generate groups structures, like @bbottema mentions in #358 and #434, should be able to build the model programmatically instead of letting picocli build the model reflectively from a class with annotations.

For example, to build the model for the `[(-x | -y) (-a -b)]` composite group programmatically:

```java
ArgGroupSpec cooccurring = ArgGroupSpec.builder()
    .exclusive(false)
	.arity("1")
    .addOption(OptionSpec.builder("-a").type(boolean.class).build())
	.addOption(OptionSpec.builder("-b").type(boolean.class).build())
	.build();

ArgGroupSpec exclusive = ArgGroupSpec.builder()
    .exclusive(true)
	.arity("1")
    .addOption(OptionSpec.builder("-x").type(boolean.class).build())
	.addOption(OptionSpec.builder("-y").type(boolean.class).build())
	.build();

ArgGroupSpec composite = ArgGroupSpec.builder()
    .exclusive(true)
	.arity("0..1")
    .addGroup(exclusive)
	.addGroup(cooccurring)
	.build();
```

The application would need to call the `CommandLine::parseArgs` method and inspect the resulting `ParseResult` object.
Perhaps the `ParseResult` class needs to be enhanced with methods to query which group was specified on the command line.

**Comment by remkop** [comment]
Note about synopsis syntax:

* https://unix.stackexchange.com/questions/187946/convention-standard-on-using-curly-braces-around-options
* https://developers.google.com/style/code-syntax
* http://docopt.org/

**Comment by remkop** [comment]
Picocli 4.0.0-alpha-1 has been released which includes support for mutually exclusive options.
See https://picocli.info/#_argument_groups for details.

_Please try this and provide feedback. We can still make changes._

_What do you think of the annotations API? What about the programmatic API? Does it work as expected? Are the input validation error messages correct and clear? Is the documentation clear and complete? Anything you want to change or improve? Any other feedback?_

**Comment by remkop** [comment]
Picocli 4.0.0-alpha-1 has been released which includes support for mutually exclusive options.
See https://picocli.info/#_argument_groups for details.

_Please try this and provide feedback. We can still make changes._

_What do you think of the annotations API? What about the programmatic API? Does it work as expected? Are the input validation error messages correct and clear? Is the documentation clear and complete? Anything you want to change or improve? Any other feedback?_

**Comment by kravemir** [comment]
Looks, great! I have not yet tried it. However, after reading the docs, I assume, that also something like this would be possible:

```
    @ArgGroup(exclusive = false, multiplicity = "1..*")
    List<Action> actions;

    static class Action {
        @ArgGroup(exclusive = true, multiplicity = "1")
        ActionContext context;

        @Parameters(index = "0")
        String action;
    }

    static class ActionContext {
        @Option(names = "--context-json")
        Path contextJsonPath;

        @ArgGroup(exclusive = false, multiplicity = "1")
        ManualContext context;
    }
```

Where `ManualContext` contains arguments to define action's context using CLI. 

Is my understanding correct?

**Comment by remkop** [comment]
Yes that should work.

**Comment by wenhoujx** [comment]
hi @remkop  seems that the `-h` help message isn't printing the description of the static class.

**Comment by remkop** [comment]
@wenhoujx, would you mind creating a separate ticket if you find any issue?

**Comment by wenhoujx** [comment]
sure

**Comment by wenhoujx** [comment]
@remkop  i was using the library wrong, all good now. thanks!
