### ISSUE TITLE
Option arity of zero is ignored when value is attached via equals sign

### ISSUE THREAD

**Issue by sitepark-schaeper** [remkop/picocli#1999]
Specifying the `arity` of a `Option` like this
```java
@Option(
    names = "-v",,
    arity = "0")
private boolean[] verbose = new boolean[0];
```

does prevent invoking `<program> -v false` as intended, but `<program> -v=false` works.

```
[picocli DEBUG] [2] Processing argument '-v=false'. Remainder=[-vv]
[picocli DEBUG] Separated '-v' option from 'false' option parameter
[picocli DEBUG] Found option named '-v': field boolean[] test.Test.verbose, arity=1
[picocli DEBUG] 'false' doesn't resemble an option: 0 matching prefix chars out of 11 option names
[picocli INFO] Adding [false] to field boolean[] test.Test.verbose for option -v on Test@5c29bfd
```

I scimmed through the code and found [this line](https://github.com/remkop/picocli/blob/main/src/main/java/picocli/CommandLine.java#L13972):
```java
            if (lookBehind.isAttached()) {
                arity = arity.min(Math.max(1, arity.min)); // if key=value, minimum arity is at least 1
            }
```

Hence the question: Is this intended? And if so, how can I circumvent this behaviour?

**Comment by remkop** [comment]
Yes this is intended.

As you know, for boolean values the default arity is zero (no parameters required), and it is possible to _force_ the end user to specify a parameter by setting `arity=1`.

The idea was that , even with the default arity of zero (no parameter required), from the parser's point of view there is no harm in accepting a parameter to a boolean option, if it is unambigously clear that the end user intended to specify this value for the boolean option. Hence, only attached values like `-v=false` are allowed, whereas `-v false` is not accepted as the `false` argument could be a subcommand or positional parameter.

If you really want to prevent this (sounds a bit strict, to be honest 😅 ), please take a look at [customized parameter processing](https://picocli.info/#_custom_parameter_processing) in the manual. The [`IParameterPreprocessor`](https://picocli.info/#IParameterPreprocessor_Parser_Plugin) section has an example that has some similarities to your use case. 
Also look at the [Custom Validation](https://picocli.info/#_custom_validation) section for how to throw a `ParameterException` that results in the nice end-user facing message.

**Comment by sitepark-schaeper** [comment]
> sounds a bit strict, to be honest :sweat_smile:

Yeah, that's fair.  I just had a hard time determining the level of verbosity in this example by `this.verbose.length`, since it would still be `1` if the invokation was `-v=false`, which is obviously not what the user intended.  Yes, I could check wether all items are `true` or subtract the amount of `false` items, but those options seem a bit hacky to me since in my opinion there should not be a usecase of someone calling the program similar to `-v=false -vv`, which is why I'd like to prevent it entirely.  

I guess I will resort to implementing custom logic.  Thank you for the quick reply!

**Comment by remkop** [comment]
Oh, now I see the issue! 😅 
Yes, what to do if someone calls the program with `-v=false -vv`.  Interesting question.
Personally I would not worry about it too much.
Maybe put a description like "verbosity increases with every occurrence on the command line" and if someone complains you can just say the program ignores the parameter and that was intended.
Is throwing an error better? Not sure...
(But that depends on the app, perhaps.)

Thanks for raising this and enjoy using picocli!
