### ISSUE TITLE
[SOVLED] Q: running multiple "sub" commands  (see `subcommandRepeatable = true`)

### ISSUE THREAD

**Issue by whatdoineed2do** [remkop/picocli#2004]
I'd like to run a number of commands in one execution:  something like this
```
./java appl  \
   cmd0  --arg0=xxx --arg1 \
   cmd1 --arg1 --arg2=yyy \ 
   cmd2
```
`cmd0`,  `cmd1`, `cmd2`  would be their own indepedant command with their own class implementation and indepedant handling of args.  some arg names may be identical.

Is this possible?

**Comment by remkop** [comment]
Yes, you can set a custom `IExecutionStrategy`.
Picocli provides some built-in execution strategy, the default one is `RunLast`, which runs the last specified subcommand.
Another built-in execution strategy is `RunAll`, which may do what you have in mind, give it a try:

```java
public static void main(String... args) {
  new CommandLine(new MyApp()).setExecutionStrategy(new RunAll()).execute(args);
}
```

See also https://picocli.info/#_initialization_before_execution

**Comment by whatdoineed2do** [comment]
thanks for the pointers.  in fact it was a combination of:
* `setExecutionStrategy(new RunAll()).execute(args)`
* toplevel `@Command(subcommands = { ... }, subcommandsRepeatable = true)`

Without the `subcommandsRepeatable = true` the execuation of:
```
./java appl  \
   cmd0  --arg0=xxx  \
   cmd1  --arg1=yyy
```
would result in
```
Unmatched arguments from index 2: 'cmd1, '--arg1=yyyy'
```
