### ISSUE TITLE
v4.7.3 not available on Maven Central

### ISSUE THREAD

**Issue by albertus82** [remkop/picocli#2006]
The latest release has not yet been published on Maven Central Repository.

https://repo1.maven.org/maven2/info/picocli/picocli/4.7.3/ returns HTTP 404.

**Comment by remkop** [comment]
Thanks for raising this. Checking...

**Comment by remkop** [comment]
Yes I cannot find 4.7.3 in Maven Central either, but it looks like the publishing process completed normally... 
Not sure what went wrong...

![image](https://user-images.githubusercontent.com/5917763/232777874-404df842-eca9-4a43-bca9-f8e1f3e9fc0b.png)
![image](https://user-images.githubusercontent.com/5917763/232778005-494a7df8-6d3b-4b66-adcf-7d0c998f491b.png)
![image](https://user-images.githubusercontent.com/5917763/232778100-5fa86be4-3175-4662-ba5b-e6f9d6fd2185.png)

**Comment by albertus82** [comment]
You could try to manually release the repository using the "Release" button.

**Comment by aalmiray** [comment]
Once this is sorted out, may I suggest having a look at JReleaser as an alternative to GNPP? https://jreleaser.org/guide/latest/examples/maven/maven-central.html#_gradle

**Comment by remkop** [comment]
> You could try to manually release the repository using the "Release" button.

Interesting idea 😆  Let me try that! 😅

**Comment by albertus82** [comment]
Resolved, thanks!
