### ISSUE TITLE
showDefaultValues = true prints null as default value

### ISSUE THREAD

**Issue by jansohn** [remkop/picocli#201]
I wasn't expecting member variables initialized with `null` (mostly Strings...) to be displayed with `Default: null` after activating `showDefaultValues = true`. Is there a possibility to only display `not null` default values?

**Comment by remkop** [comment]
Thanks for raising this!
The fix has been pushed to master. Please verify.

**Comment by jansohn** [comment]
Thanks for fixing this. I can confirm that it works. Is there any particular reason that the default values are being printed on a new line? I'm more familiar with the default values being displayed on the same line as the description (e.g. http://docopt.org/).

**Comment by remkop** [comment]
Putting the default value on a new line looks reasonably good even if the last description sentence does not end in a period. The docopt way also looks good though. 

Could consider making this configurable but I need to think about how to do that without overcomplicating things.
