### ISSUE TITLE
Stay at the current option instead of exiting the application if parameter value is invalid

### ISSUE THREAD

**Issue by gitusersr90** [remkop/picocli#2010]
Halo There!
Kudos to you for introducing and maintaining this awesome Command Line Interface 🥇 

I am using interactive options and using the user inputs obtained via prompts for my business operations.
As and when user provides value to every prompt, I want to validate it.
I've looked at the Custom Validation section of the documentation. The section describes throwing a Parameter Exception during failed validation which is really helpful in many cases.
Now, I am looking for something that does not throw an exception and stop the execution of the program but display a simple message and stay at the current option so that users can provide the correct value without exiting from the program and trying again. 
Is there any way to acheive this?

Thanks!

**Comment by remkop** [comment]
Have you tried using [custom parameter processing](https://picocli.info/#_custom_parameter_processing)?
In your IParameterConsumer or IParameterPreprocessor you could use `System.console().readLine()`, to continue asking the user for input, similar to the example for [Forcing Interactive Input](https://picocli.info/#_forcing_interactive_input).
I haven't tried this, but this may get your started...

**Comment by gitusersr90** [comment]
This is helping! System.console().readLine()  prevents the application from stopping and waits on input.
Hope I can go ahead with this! Thanks!
