### ISSUE TITLE
How can I implement an completer to auto complete an option's arguments, showing argument's name and description both in each line?

### ISSUE THREAD

**Issue by peterzh4ng** [remkop/picocli#2012]
I found that picocli-shell-jline3 has a awesome builtin command `history`. It can iterate each option in this view:

![图片](https://user-images.githubusercontent.com/86906331/234137011-95878706-0e99-4a57-a7c8-8b6c00ddba37.png)

the name and description of each option both show in a line. And I am wondering is there a graceful ( well, simple too ) way to implement a familiar auto completion function to auto complete an option's argument, like:

```
Prompt> scan --type<TAB><TAB>
fastly         ( scan fastly without considering the potential impact to the system )
medium    ( just so so )
low           ( be gentle to the system )

```

**Comment by remkop** [comment]
Hi @peterzh4ng, have you seen the [example](https://github.com/remkop/picocli/tree/main/picocli-shell-jline3#jline-316-and-picocli-44-example) in the `picocli-shell-jline3` README?

**Comment by peterzh4ng** [comment]
Yeah I use it as my startpoint, did I miss something?

**Comment by remkop** [comment]
Does that not give autocompletion for your commands and its options?

For option parameters it generates completion candidates when the option type is an enum, or when `completionCandidates` is defined, as in this example: https://picocli.info/#_completion_candidates_variable

**Comment by peterzh4ng** [comment]
First, thanx for your reply. I indeed explored the official documentation, currently I have arrived here:

![图片](https://user-images.githubusercontent.com/86906331/234577194-1cb224b5-3c7a-44ba-89d7-e31b15db9efd.png)

What I want to implement is just like I show in this picture.

Is that possible to gracefully get it done? 😊

**Comment by peterzh4ng** [comment]
I mean, picocli provided copmletionCandidates parameter to specify a class extending Iterablt<String>, but I think it may not supports showing their description while auto completing arguments of an option ( not to auto complete the name of options, but the choices of an option ).

**Comment by remkop** [comment]
Thank you for the clarification. Now I understand.

Options have a description, but the possible option parameter values do not have separate descriptions. 
So there is simply no such information available to display.
