### ISSUE TITLE
WEIRD issue.  picocli is changing a value of '/solr' to a fully qualified Windows path.

### ISSUE THREAD

**Issue by elyograg** [remkop/picocli#2023]
Here is a log from my script and program that uses picocli:

```
2023-05-13_15:41:47.083 INFO  Passing control to java.
2023-05-13_15:41:47.404 INFO  JAVABIN=/c/Program Files/Common Files/Oracle/Java/javapath_target_308304359/java
2023-05-13_15:41:47.749 INFO  Options given: -ss https://oh1p4sol7:8443/solr -tz 10.75.87.83:2181 -tz 10.75.88.240:2181 -tz 10.75.89.176:2181 -tr /solr -su SolrPrd4Admin -sp REDACTED -sc activity03-06-2021 -tc testactivity -w -uk record_id -ib 1000 -qb 20000 -qs 150000 -t2 -Djavax.net.ssl.trustStore=cacerts -Dfoo=bar -th 8
15:41:49.085 [main] INFO  o.e.s.migration.Main targetChroot 'C:/Users/sheisey/AppData/Local/Programs/Git/solr'
15:41:49.089 [main] INFO  o.e.s.migration.Main Property javax.net.ssl.trustStore=cacerts added.
15:41:49.089 [main] INFO  o.e.s.migration.Main Property foo=bar added.
15:41:49.089 [main] INFO  o.e.s.migration.Main Source collection activity03-06-2021 URL https://oh1p4sol7:8443/solr
15:41:49.089 [main] INFO  o.e.s.migration.Main Target collection testactivity zkHost [10.75.87.83:2181, 10.75.88.240:2181, 10.75.89.176:2181] C:/Users/sheisey/AppData/Local/Programs/Git/solr 
15:41:49.098 [main] INFO  o.e.s.migration.Main Setting source credentials
15:41:49.098 [main] INFO  o.e.s.migration.Main Setting target credentials
15:41:49.146 [main] DEBUG o.a.s.c.s.i.Http2SolrClient Create Http2SolrClient with HTTP/2 transport
15:41:49.721 [main] DEBUG o.a.s.c.s.i.Http2SolrClient Create Http2SolrClient with HTTP/1.1 transport
```

Logged after this is an exception ... The ZK client in SolrJ complains that the chroot must start with a forward slash.  The value that I passed on the commandline DID start with a forward slash.

This is the option definition:

```
  @Option(names = { "-tr",
      "--target-chroot" }, arity = "1", paramLabel = "</chroot>", description = "Target chroot. Must start with a forward slash. Example: '/solr'")
  private static String targetChroot;
```

I specify `-tr "/solr"` on the commandline.  Why is picoclli changing `/solr` to `C:/Users/sheisey/AppData/Local/Programs/Git/solr` and what can I do to fix it?  I added the quotes when using the option without the quotes produced the same behavior.

The windows path that it changed the option value to is one that does not exist.

I am running this in Git Bash on Windows 10 Enterprise.  Git Bash is part of GIt for Windows.

**Comment by elyograg** [comment]
ChatGPT to the rescue, but its first two suggestions did not work.  Third time's the charm.  This is the new definition for the option, which will work once I have the program remove a trailing semicolon:

```
  @Option(names = { "-tr",
      "--target-chroot" }, arity = "1", paramLabel = "/chroot;", description = "Target chroot. Must start with a forward slash and end with a semicolon.  The semicolon is required to keep the value from being expanded into an absolute path. It will be removed before the value is used. Example: '/solr;'")
  private static String targetChroot;

```

**Comment by remkop** [comment]
This must be an artifact of Git Bash, I have never seen that behaviour before... 
Interesting, thanks for raising it.

**Comment by remkop** [comment]
You can see what value picocli _receives_ on the command line by switching on [picocli Trace logging](https://picocli.info/#_tracing).

**Comment by elyograg** [comment]
ChatGPT said that by default, picocli will turn anything that looks like a path into an absolute path.  And it had suggestions to turn off that behavior, which didn't work.  The third suggestion it made when I told it the others didn't work was to add a semicolon to the option.  That works.  What a strange road this sent me down.

The first ChatGPT suggestion was to change `arity` from `1` to `0..1` ... the second was to set expandAtFiles to false on the CommandLine object.  Looking at what that actually does, I know why the second suggestion did not work.

Running it on Linux without the semicolon and without the quotes does work, so it does indeed look like a Git Bash problem.  I would have expected the quotes to prevent that, so it's VERY weird and probably a bug in Git Bash.

**Comment by remkop** [comment]
ChatGPT is known to talk out of its **s. 😅  That is the problem with LLM Large Language Models, they are famous for that, no?

It is fun to play with but far from a reliable source of information!

Any conversion that picocli does is done by [type converters](https://picocli.info/#_strongly_typed_everything).
I initially thought that the option was defined as  `@Option File` with type `File`, and there was an issue in the converter, but if it is just String, then there is no conversion happening and it is just the value that is passed in.

**Comment by elyograg** [comment]
I take what it says as a guide, the answers I get are typically not usable as-is.  They usually do inspire me to find the right solution, though.
