### ISSUE TITLE
Improved feedback on mistyped subcommands

### ISSUE THREAD

**Issue by mauvo** [remkop/picocli#2026]
Hi,

I've had some feedback via our support team that including the command name and the subcommand suggestions would be helpful. I'm not sure if this is the accepted convention in CLIs.

Anyway, here's a branch with updated tests and my attempt to fix the code for your consideration.  https://github.com/mauvo/picocli/tree/subcommand-suggestions

Thanks,
David

**Comment by remkop** [comment]
Looks good. Can you turn this into a pull request please?

**Comment by mauvo** [comment]
Done - thank you.
