### ISSUE TITLE
Option "mapFallbackValue" ignored when inherited to subcommand

### ISSUE THREAD

**Issue by zman0900** [remkop/picocli#2035]
With an @Option defined like this: 
```java
@Command(
    name = "main"
    subcommands = {
        SubCmd.class,
        CommandLine.HelpCommand.class
    }
)
public class Main {
    @Option(
            names = "-D",
            paramLabel = "<key=value>",
            mapFallbackValue = Option.NULL_VALUE,
            scope = ScopeType.INHERIT
    )
    private final Map<String, String> javaOpts = new HashMap<>();
}

@Command(name = "sub")
public class SubCmd {
    @ParentCommand
    private Main parent;
}
```

Running with args like ["sub", "-Dxyz"] results in error message:

    Value for option option '-D' (<key=value>) should be in KEY=VALUE format but was xyz

This seems like it might be because the ArgSpec Builder copy constructor doesn't copy the "mapFallbackValue" field in picocli 4.7.3:  https://github.com/remkop/picocli/blob/v4.7.3/src/main/java/picocli/CommandLine.java#L9496

**Comment by remkop** [comment]
Thank you for raising this, and thank you for the analysis!
It’s very plausible that that’s the cause. 

Will you be able to provide a pull request for this?

**Comment by zman0900** [comment]
PR #2036 opened
