### ISSUE TITLE
FormatString bug in AutoComplete found by Error Prone

### ISSUE THREAD

**Issue by vorburger** [remkop/picocli#2053]
I'm running https://errorprone.info/ on this project, and it claims to have found a bug:

```
picocli/src/main/java/picocli/AutoComplete.java:788 : error: [FormatString] extra format arguments: used 2, provided 3
                buff.append(format("%s      positionals=$( compReplyArray \"${%s_pos_param_args[@]}\" )\n", indent, paramName, currWord));

picocli/src/main/java/picocli/AutoComplete.java:832 : error: [FormatString] extra format arguments: used 2, provided 3
                buff.append(format("%s      COMPREPLY=( $( compReplyArray \"${%s_option_args[@]}\" ) )\n", indent, bashify(option.paramLabel()), currWord));
```

See https://errorprone.info/bugpattern/FormatString ... @remkop  from a quick glance, I think this is a real bug, not a false positive? As far as I understand it in both of those cases there are indeed only x2 `%s` but 3 arguments. 

I would by happy to send a CL, but it's not immediately clear to me which of the 3 is wrong and should be removed.

**Comment by remkop** [comment]
@vorburger Thank you for raising this!
Looks like these changes were made as part of PR https://github.com/remkop/picocli/pull/1759 .
I added a [comment on that PR](https://github.com/remkop/picocli/pull/1759#pullrequestreview-1502524578) and I propose we wait for @jsotuyod to take a look and let us know.

**Comment by vorburger** [comment]
Following @jsotuyod [response](https://github.com/remkop/picocli/pull/1759#discussion_r1245058532) the I had a look at this again, and it seems that on the current `main` branch this may already have been fixed? The line numbers, and code, has changed, see [here](https://github.com/jsotuyod/picocli/blob/a2edb1f5ed613b6fb8a7e4d56aa8ff477a063b73/src/main/java/picocli/AutoComplete.java#L752) and [here](https://github.com/jsotuyod/picocli/blob/a2edb1f5ed613b6fb8a7e4d56aa8ff477a063b73/src/main/java/picocli/AutoComplete.java#L795)... probably actually already all good as-is.

**Comment by vorburger** [comment]
@remkop actually I was wrong above, this was never fixed!

BTW you can now even easily reproduce that Error Prone message above locally using #2054.

I've now raised #2175 to propose a fix for this.
