### ISSUE TITLE
Add Error Prone

### ISSUE THREAD

**Issue by vorburger** [remkop/picocli#2054]
How about adding https://errorprone.info/docs/installation to PicoCLI? Using (https://github.com/tbroyer/gradle-errorprone-plugin.)

It would have found the #2053 problem, and possibly others, and will prevent regressions of them, and future new bugs.

@remkop would a PR for this be a welcome contribution?

**Comment by remkop** [comment]
Hi @vorburger, yes that seems like a good idea!

One note of caution may be with the different Java versions.
When building picocli and creating releases, I use JDK 8.
Additionally, the GitHub Actions-based CI compiles and runs tests using various other JDK versions.
Both use cases would need to be supported.

If that is possible, then let's go for it!

**Comment by clebertsuconic** [comment]
I have a love / hate relationship with errorprone.

While it gets some issues eventually, it generates a lot of noise that unless you are willing to fix every single warning coming from errorprone those will get ignored.

Picocli is not that huge, so it won't add much time to the build, but one issue I have with it in artemis is that it takes a good amount to time to process.


IMO though, picocli is very small. and I appreciate the fact it is small. I don't see much benefit from using errorprone.

**Comment by vorburger** [comment]
> IMO though, picocli is very small. and I appreciate the fact it is small. 

@clebertsuconic adding Error Prone to the PicoCLI build (only!) will keep the PicoCLI JAR and API as small as it is... 😺 

> When building picocli and creating releases, I use JDK 8. Additionally, the GitHub Actions-based CI compiles and runs tests using various other JDK versions. Both use cases would need to be supported.

@remkop I see! Because [you use a Matrix Build](https://github.com/remkop/picocli/blob/main/.github/workflows/ci.yml) it wouldn't "just work". Given https://errorprone.info/docs/installation stating _"Please note that Error Prone must be run on JDK 11 or newer.",_  the best way maybe to simply have the [`gradle-errorprone-plugin`](https://github.com/tbroyer/gradle-errorprone-plugin) run only on Java 11+ ... I've never done this with Gradle, but given how imperative Gradle is, and that it can bake Pizzas in addition to building software, presumably there is some way to [make it so](https://www.youtube.com/watch?v=FaLyasJPyUU)... does anyone reading this happen to know how to do that? Otherwise I'll look a bit more into it when I have some time.

**Comment by vorburger** [comment]
> presumably there is some way to [make it so](https://www.youtube.com/watch?v=FaLyasJPyUU)

Asked on https://discuss.gradle.org/t/how-to-skip-disable-plugin-execution-based-on-java-version/47274

Will also update https://stackoverflow.com/a/77668885/421602 (which comes up when searching for this).

**Comment by vorburger** [comment]
WIP on https://github.com/remkop/picocli/compare/main...vorburger:picocli:errorprone ...

... currently shows _2 errors, 100 warnings_ - I think at least for an initial version the simplest here is to hide the warnings and fix the 2 errors.
