### ISSUE TITLE
What's the picocli idiomatic way to implement subcommands?

### ISSUE THREAD

**Issue by velit** [remkop/picocli#206]
I have this code that implements a main command that basically only prints usage and two subcommands that actually do things. What's the idiomatic picocli way that invokes specific code based on the subcommand used and correctly gives user feedback (prints error and usage) in case the subcommand had invalid parameters given?

If i use the code that parses subcommands given in the documentation that is `List<CommandLine> parsed = commandLine.parse(args);` this explodes if any of the parameters were incorrect that were given to subcommands and there's no way to figure out which subcommand was invoked so you could print the correct subcommand's usage for the user.

On the other hand the picocli documentation suggests to use `Object result = CommandLine.call(new MyCallable(), System.err, args);
` which automatically catches exceptions and prints proper usage, but this doesn't seem to support subcommands directly, or at least I can't figure out from the documentation how it could be used with subcommands directly.

Here's the code that I ended up using, is there a better way?
```
@Command(name = "import",
    description = "Import <redacted things>, validate and do something with their content based on the given subcommand",
    subcommands = {
        Print.class, Import.class
    }
)
public class MainApplication implements Callable<Void> {

  public static void main(String[] args) throws Exception {
    if (args.length > 0 && args[0].equalsIgnoreCase(("print"))) {
      CommandLine.call(new Print(), System.err, Arrays.copyOfRange(args, 1, args.length));
    }
    else if (args.length > 0 && args[0].equalsIgnoreCase("import")) {
      CommandLine.call(new Import(), System.err, Arrays.copyOfRange(args, 1, args.length));
    }
    else {
      CommandLine.call(new MainApplication(), System.err, args);
    }
  }

  @Override
  public Void call() throws Exception {
    CommandLine.usage(this, System.err);
    return null;
  }
}
```

The Import and Print classes implement Callable<Void> as well and their call methods actually invoke the functionality that their subcommands should do.

**Comment by remkop** [comment]
Ouch! It is very painful that you need to do this... Thanks for pointing this out!

It sounds like what is needed is the ability to find out which subcommand threw the exception.

I'm thinking to add a method `ParameterException::getCommandLine` that returns the `CommandLine` instance that threw the exception.

Then you could write code like this:
```
PrintStream out = System.err;
CommandLine top = new CommandLine(new MainApplication());
List<CommandLine> parsedCommands;
try {
    parsedCommands = top.parse(args);
} catch (ParameterException ex) { // incorrect user input for one of the subcommands
    out.println(ex.getMessage());
    ex.getCommandLine().usage(out); // get the offended subcommand from the exception
    return;
}
```

After the parsing succeeds, applications need to check if the user requested help and if not, execute the command. Below is is some idiomatic code for that.

I have some work in progress (https://github.com/remkop/picocli/issues/115) to provide convenience methods that reduces all of the below code to one line of code for you. This is currently in progress in master (`CommandLine::parseWithHandler methods`). Your feedback would be much appreciated.
```
for (CommandLine parsed : parsedCommands) {
    if (parsed.isUsageHelpRequested()) {
        parsed.usage(out);
        return;
    } else if (parsed.isVersionHelpRequested()) {
        parsed.printVersionHelp(out);
        return true;
    }
}
Object last = parsedCommands.get(parsedCommands.size() - 1).getCommand();
if (last instanceof Runnable) {
    ((Runnable) last).run();
    return;
} else if (last instanceof Callable) {
    Object result = ((Callable) last).call();
    // ... do something with result 
} else {
    throw new IllegalArgumentException("Last subcommand (" + last + ") is not Runnable or Callable");
}
```

**Comment by remkop** [comment]
I created #207 to Provide ability to find which subcommand threw a ParameterException.

**Comment by remkop** [comment]
#207 has been pushed to master. 
Please give it a try and let me know if there’s other things to improve.

**Comment by remkop** [comment]
Picocli 2.0 will provide convenience methods that support subcommands (#115).

In picocli 2.0, idiomatic usage will look like this:
```
@Command(name = "import",
    description = "Import <redacted things>, validate and do something with their content based on the given subcommand",
    subcommands = {
        Print.class, Import.class
    }
)
public class MainApplication implements Callable<Void> {

  public static void main(String[] args) throws Exception {
    CommandLine cmd = new CommandLine(new MainApplication());

    // Use of of the built-in handlers: RunAll, RunFirst, RunLast, or create a custom handler.
    // The RunAll handler would run (or call) all commands and subcommands that appeared
    // on the command line (if they implement Runnable or Callable)
    List<Object> results = cmd.parseWithHandlers(new RunAll(), System.err, args);
  }
}

  @Override
  public Void call() throws Exception {
    CommandLine.usage(this, System.err);
    return null;
  }
}
```

**Comment by remkop** [comment]
This has been pushed to master. It would be great if you could give it a try and let me know if it works for your use case.

**Comment by velit** [comment]
The new parseWithHandler method works perfectly. I'll be sure to use it when 2.0 officially releases.

**Comment by remkop** [comment]
If you don't mind I will close this ticket then.
Please re-open or create a separate ticket if there are any issues.

**Comment by srinarayanant** [comment]
nice feature !

**Comment by RailRunner166** [comment]
yes, this really helps when creating full CLI applications :D thanks!

**Comment by remkop** [comment]
@RailRunner166 Thanks for the feedback. Don't forget to star the project if you like it! ;-)
