### ISSUE TITLE
Improve documentation for generating GraalVM native image with Gradle build tool

### ISSUE THREAD

**Issue by bhavikp19** [remkop/picocli#2077]
I think that picocli documentation around generating GraalVM native image with gradle build tool can be improved a lot. Here are couple of things that I have in mind : 

1. In this section of documentation https://picocli.info/#_how_do_i_create_a_native_image_for_my_application we ask users to check out [gradle-graal](https://github.com/palantir/gradle-graal) gradle plugin but this plugin is not actively maintained. This was last released in June 2022 and lot of the recent commits are from Excavator bot. I think we should instead direct users to use the official GraalVM gradle plugin. 
2. In this section of documentation https://picocli.info/#_where_can_i_get_more_details we link to demo gradle project where we can improve on the github action https://github.com/remkop/picocli-native-image-demo/blob/master/.github/workflows/gradle.yml. Official GraalVM gradle plugin now makes it very easy to generate native images on Linux, MacOS and specially Windows. Documentation can be found here : https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html.

If you agree with these suggestions then I am happy to work on and submit the PR for above changes.

**Comment by remkop** [comment]
Yes please! Thank you!

**Comment by bhavikp19** [comment]
For 1. above, do I edit the `.adoc` file or the `.html` file? 

For 2. I should raise the PR directly for https://github.com/remkop/picocli-native-image-demo/tree/master repository?

**Comment by remkop** [comment]
> For 1. above, do I edit the `.adoc` file or the `.html` file?

Only the  `.adoc` files is fine. The HTML files are generated from the ADOC files upon release.

> For 2. I should raise the PR directly for https://github.com/remkop/picocli-native-image-demo/tree/master repository?

Yes that is fine.

Thank you!

**Comment by bhavikp19** [comment]
For 2. above I have raised the PR : https://github.com/remkop/picocli-native-image-demo/pull/5

**Comment by bhavikp19** [comment]
For 1. above I have raised the PR : https://github.com/remkop/picocli/pull/2080

**Comment by remkop** [comment]
Both are now merged. Thank you for the contribution!
