### ISSUE TITLE
40 MB gradle-1.12-bin.zip in the repo

### ISSUE THREAD

**Issue by rsvoboda** [remkop/picocli#2086]
This repo contains 40 MB gradle-1.12-bin.zip

https://github.com/remkop/picocli/blob/main/picocli-tests-java567/gradle/wrapper/dists/gradle-1.12-bin/2qvnajdoo11hasdfkikjaci26k/gradle-1.12-bin.zip 

Gradle 1.12 is from ~2014, Is it necessary to keep that binary in the repo?

**Comment by remkop** [comment]
Yes, please see https://github.com/picocli-tests-java567/README.md

**Comment by rsvoboda** [comment]
ok, I checked https://github.com/remkop/picocli/tree/main/picocli-tests-java567, closing
