### ISSUE TITLE
When using picocli + jline3, is it possible to support "|" (pipe) and "&&" in the terminal?

### ISSUE THREAD

**Issue by hengyunabc** [remkop/picocli#2088]
picocli is a great project. Currently, I'm using picocli + jline3 to build a terminal tool, and it works very well. However, it does not support commands like "|" (pipe) and "&&".

I have searched the documentation, but there seems to be little information on this. I would like to know if there is a way to support these commands.

In the jline3 demo, I found that jline-gogo supports commands like "|" (pipe) and "&&". However, it requires the felix gogo dependency and seems a bit complex.

**Comment by remkop** [comment]
I had a look at some [bash documentation](https://linux.die.net/man/1/bash) (see the Pipelines section).

The `|` and `&&` tokens are not considered commands, but are _control operators_. They tell the shell to combine the output of various commands in some way. 

This is not something that picocli can do. This is the domain of the shell, so this needs to be implemented at the JLine level. 

It may be best to contact the JLine maintainers to ask for advice on how to proceed with this.

**Comment by remkop** [comment]
I will close this ticket since I don't think picocli can help with this use case (please ask the JLine maintainers). 
Let me know if I'm mistaken and we should reopen this.

**Comment by hengyunabc** [comment]
Thank you very much.
