### ISSUE TITLE
Feature request: PropertiesDefaultProvider at first try to load properties from classpath

### ISSUE THREAD

**Issue by rimuln** [remkop/picocli#2102]
Would be possible enhance this class to load properties from resources too?

Actual state:
1. try to load from user.home
2. try to load from environment

Wanted state:
1. try to load from classpath via getResourceAsStream
2. try to load from user.home
3. try to load from environment

or allow configure IDefaultValueProviders as ordered list?

**Comment by remkop** [comment]
That sounds like a good enhancement!
One caveat is that I am very hesitant to modify existing default behavior. 
So my preference would be to load from classpath after trying the current methods, not before. 

My time to work on picocli is extremely limited. 
Will you be able to provide a pull request for this?

**Comment by rimuln** [comment]
I understood your opinion. But the oposite order is for us problematic. 
In general. 
You as developer distribute application with some default settings that could be bundled in jar. Then you expect that user is able override this default settings from outside.

If you pass the loading defaults from classpath as last in order then you always override user defined settings.
And if jar doesn't contains the settings then I would say the default logic is unchanged.

But if I look on it from implementation. You are right first is current code and after this is load from classpath. So theoreticaly this way:
```
        private static Properties loadProperties(CommandSpec commandSpec) {
            if (commandSpec == null) { return null; }
            Properties p = System.getProperties();
            for (String name : commandSpec.names()) {
                String propertiesFileName = "." + name + ".properties";
                URL resource = CommandLine.class.getClassLoader().getResource(propertiesFileName);
                String path = p.getProperty("picocli.defaults." + name + ".path");
                File defaultPath = new File(p.getProperty("user.home"), propertiesFileName);
                File file = path == null ? defaultPath : new File(path);
                if (file.canRead()) {
                    return createProperties(file, commandSpec);
                } else if (resource != null) {
                    file = new File(resource.getFile());
                    if (file.canRead()) {
                        return createProperties(file, commandSpec);
                    }
                }
            }
            return loadProperties(commandSpec.parent());
        }
```

**Comment by rimuln** [comment]
ad 1) ok no problem

ad 2) yes this come to my mind to. In our case it is all in one fat jar made by maven, but I see in docu that picocli.jar could be separate jar so wasn't sure how it works. The command class is 100% better, just I didn't look yet how get it from CommandSpec object.

ad 3) not sure what you mean. The original logic try to load from -Dpicocli.defaults.<name>.path, and if not present then from user.home This is still present. 

ad 4) I expect no exception as not always user of picocli want provide some defaults on classpath. I see some warning in createProperties will not be enough?

In general I created PR #2107 to discuss directly on code
