### ISSUE TITLE
Allow default value of field to be different from field's toString()

### ISSUE THREAD

**Issue by wiwie** [remkop/picocli#213]
I am attempting to use one of my existing classes for an option, but would like to provide a different default string value than the field's toString().

The mentioned toString() implementation returns a human-readable string, that is not suited to be used as the default value string of the option. I'd like to be able to provide some shorter string instead, without needing to adapt the current toString() implementation.

Is this currently possible somehow?

If not, the most straight forward way of achieving this I can think of would be to add a "default" parameter to the @Option annotation.
Alternatively, one could introduce a new annotation @OptionDefault, that could be used to annotate a string field / getter method of the option class. To allow a getter to be annotated would also allow for additional flexibility.

**Comment by remkop** [comment]
One idea (that would work out of the box) is to add the description of the default value to the option description:

```
@Option(names = “-o”, 
  description = {“Aaaaa bbbb cccc dddd eeee ffff”,
                 “Default: SHORTSTRING”})
MyClass myClass; // null so it won’t show in usage

//...

// if no user-specified value, 
// set the default in application code 
if (myClass == null) {
    myClass = MyClass.valueOf(“SHORTSTRING”);
}
//... businesses logic follows
```

**Comment by wiwie** [comment]
nice! I wasn't aware that the description parameter takes an array and prints them as indented consecutive lines.

thanks!

**Comment by remkop** [comment]
Cool! Glad to hear that solved the problem.

**Comment by remkop** [comment]
If you don't mind I'll close this ticket. Please reopen or open a new ticket if there's any problem.

**Comment by wiwie** [comment]
well I don't think that the current design is optimal and that it would be nicer to have a better handling of default values. But it can see that it may also be overkill.

**Comment by wiwie** [comment]
See also JCommander's IDefaultProvider interface.

**Comment by remkop** [comment]
I've looked at JCommander's IDefaultProvider and I confess that until now I also considered it overkill.

However, my opinion on this is not set in stone and I'm willing to reconsider if there is a good use case.
Would it solve your use case if picocli had something like IDefaultProvider?
