### ISSUE TITLE
How to solve the problem of garbled Chinese output

### ISSUE THREAD

**Issue by Afterlll** [remkop/picocli#2160]
How to solve the problem of garbled Chinese output
![image](https://github.com/remkop/picocli/assets/116958691/b3929f30-414d-44f7-b914-0c393bc4c61b)
![image](https://github.com/remkop/picocli/assets/116958691/cc13fa41-61f7-49bd-9f22-2f1793daccf2)

**Comment by Afterlll** [comment]
> Which version of picocli are you using, and which operating system (and version) and which shell application are you using?



> Which version of picocli are you using, and which operating system (and version) and which shell application are you using?

The picocli version used is 4.7.5, the operating system is Windows11, and the programming language is java

**Comment by Afterlll** [comment]
> The shell application is Command Prompt? (`%windir%\system32\cmd.exe`)?

![image](https://github.com/remkop/picocli/assets/116958691/4a2abf4b-3dee-49ba-8e17-4d10ccba9bee)

**Comment by remkop** [comment]
Okay, Git Bash.

In the Git Bash (MINGW64) window, right-click on the title bar; this will bring up a pop-up menu.
Select `Options...` from the pop-up menu; this will show an Options dialog window.

In the Options dialog, select `Text` on the left, to show "Text and Font properties".
Select the desired `Locale` and perhaps also the desired `Character set`.

You can also try changing the font (if the selected font does not support Chinese characters).

**Comment by remkop** [comment]
@Afterlll did this resolve the issue?
