### ISSUE TITLE
Build is Broken

### ISSUE THREAD

**Issue by vorburger** [remkop/picocli#2173]
`git clone https://github.com/remkop/picocli.git && cd picocli && ./gradlew build` fails.

https://github.com/remkop/picocli/actions is all red.

https://github.com/remkop/picocli/commits/main/ has "red cross" since the changes on Nov 12 (was still green on Sep 18).

#2148 broke it.

#2172 fixes it for me locally, but is still red _(37 cancelled and 3 failing checks)_ on GitHub; I haven't looked more closely into why.

@remkop

**Comment by vorburger** [comment]
It seems to have gotten a bit better now, but I think the build on Java 6 is still broken and fails on the `main` branch?

Note https://github.com/remkop/picocli/actions?query=branch%3Amain

Let's see what's green and red e.g. on Test #2177 ...

The failures on #2176 and #2170 may be due to this, not caused by the changes in those PRs.

@remkop

**Comment by remkop** [comment]
Okay I will merge your outstanding PRs, then we can see if any problems remain...

Thank you for your help!

**Comment by vorburger** [comment]
see #2177
