### ISSUE TITLE
Create badge for projects using picocli

### ISSUE THREAD

**Issue by aadrian** [remkop/picocli#224]
Add a page with links of projects that are using picocli :) .

Thank you.

**Comment by remkop** [comment]
I created this page on the Wiki: https://github.com/remkop/picocli/wiki/Project-Using-Picocli

Are you able to modify it?

**Comment by aadrian** [comment]
@remkop yes.

**Comment by remkop** [comment]
Thanks for confirming. I will update the README to point people to this page.
Don't be shy to add your project also! :-)

**Comment by remkop** [comment]
@JsaParDeveloper  sorry for my late reply. There is a badge at the top of the readme file: https://img.shields.io/github/release/remkop/picocli.svg . Is that what you have in mind?

**Comment by remkop** [comment]
@JsaParDeveloper It would actually be great if you could create the badge (or badges) and create a pull request for the picocli README.

**Comment by JsaParDeveloper** [comment]
@remkop I wouldn't know where to edit the README to add something like this:

Adding a PicoCLI badge to your project repository.

When your project is using PicoCLI, consider mentioning it in your project README file.

README.md code
[![PicoCLI](https://img.shields.io/badge/PicoCLI-3.0-green.svg)](https://github.com/remkop/picocli)

Badge itself:
https://img.shields.io/badge/PicoCLI-3.0-green.svg

**Comment by remkop** [comment]
This has been added to the README.
Thanks for the suggestion!
