### ISSUE TITLE
Support extracting options/parameters/subcommand information

### ISSUE THREAD

**Issue by virtuald** [remkop/picocli#229]
It appears that picocli.AutoComplete is able to do this via extractOptionsAndParameters (which uses CommandLine.init), which is private. It would be great if there were a way to extract all of those.

My use case is I'm using picocli to parse arguments for a REPL, and I'm looking at using jline to do interactive tab-completion (via implementing the `jline.Completer` interface). While it's easy enough to extract the subcommands, I would like the various parameter/option names too.

Thanks for all the work on picocli, it's a joy to use!

**Comment by remkop** [comment]
Glad to hear you like picocli!

About the `init` method, I can you why you want to use it or something like it, but I’m not comfortable making that public API yet. 

It still needs quite a bit of work.  It will come eventually but it’ll take some time.

**Comment by virtuald** [comment]
In reality, the thing that I need is the ability to enumerate all of the Options and Parameters for a given CommandLine object.... so however one does that would be fine to me.

**Comment by remkop** [comment]
In that case I suggest extracting these annotations with the standard Java APIs. Something like this:

```
public static void main(String[] args) {
    class Example {
        @Option(names = "-o") boolean option;
        @Option(names = "-v") boolean verbose;
        @Parameters String[] args;
    }
    List<Option> options = extract(Example.class, Option.class);
    System.out.println(options);

    List<Parameters> params = extract(Example.class, Parameters.class);
    System.out.println(params);
}

private static <T extends Annotation> List<T> extract(Class<?> appClass, Class<T> annotationClass) {
    return Arrays.asList(appClass.getDeclaredFields()).stream()
            .filter(f -> f.isAnnotationPresent(annotationClass))
            .map(f -> f.getAnnotation(annotationClass))
            .collect(Collectors.toList());
}
```

**Comment by remkop** [comment]
Are you okay to close this ticket?

**Comment by virtuald** [comment]
I suppose that is an adequate solution.
