### ISSUE TITLE
[Question] Is it possible to get suggestion list dynamically?

### ISSUE THREAD

**Issue by nqminhuit** [remkop/picocli#2314]
For example, when i type:
```
git checkout <Tab>
```
It list all they branches on my current git repo.
Is this usecase possible with picocli?

**Comment by remkop** [comment]
Hi @nqminhuit , have you had a chance to read this?

https://picocli.info/autocomplete.html

**Comment by nqminhuit** [comment]
thank you for your quick reply, so it's possible then, I will try to learn more about it.

**Comment by remkop** [comment]
There's JLine and bash completion. 
Dynamic completion is easier with JLine. 

It's possible with bash but you would have to customize the bash completion script generated by picocli. So picocli would only do the first half...

**Comment by nqminhuit** [comment]
So if I use bash completion, I have to write additional bash functions for the dynamic parts?

**Comment by remkop** [comment]
Yes probably.
