### ISSUE TITLE
native-image Runtime Error

### ISSUE THREAD

**Issue by donpwinston** [remkop/picocli#2322]
Here is the stack trace:

<pre>
~ ./address-converter-1.0.0 -h
Error: picocli.CommandLine$AutoHelpMixin@62b9655f is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations
picocli.CommandLine$InitializationException: picocli.CommandLine$AutoHelpMixin@62b9655f is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations
	at picocli.CommandLine$Model$CommandReflection.validateCommandSpec(CommandLine.java:12029)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11859)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6392)
	at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7389)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11854)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6392)
	at picocli.CommandLine.<init>(CommandLine.java:230)
	at picocli.CommandLine.<init>(CommandLine.java:224)
	at picocli.CommandLine.<init>(CommandLine.java:199)
	at gov.uscourts.bnc.app.AddressConverter.main(AddressConverter.java:39)
	at java.base@22.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
➜  ~
</pre>

Here is the source code:

<pre>
package gov.uscourts.bnc.app;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;

import com.diogonunes.jcolor.Ansi;
import com.diogonunes.jcolor.Attribute;

import gov.uscourts.bnc.RecipientAddresses;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "address-converter.jar", mixinStandardHelpOptions = true, version = "1.0.0", description = "Verify and Convert 1 up formatted addresses to pipe delimited addresses.")
public class AddressConverter implements Runnable {
  @Option(names = { "-h", "--help" }, usageHelp = true, description = "Print usage help and exit.")
  boolean usageHelpRequested;
  @Option(names = { "-v",
      "--version" }, versionHelp = true, description = "Print version information and exit.")
  boolean versionHelpRequested;
  @Option(names = { "-f", "--addresses" }, description = "File of addresses")
  private String filename;
  @Option(names = { "-o", "--output" }, description = "Output file name")
  private String outFilename = null;
  @Option(names = { "-1UpToPipe"}, description = "Convert 1 up formatted addresses to pipe delimited addresses.")
  boolean convert1UpToPipeDelimited = false;
  @Option(names = { "-verify"}, description = "Verify addresses and output results.")
  boolean verify = false;

  private PrintWriter pw = null;

  public static void main(String[] args) {
    int exitCode = 0;
    try {
      exitCode = (new CommandLine(new AddressConverter())).execute(args);
    } catch (RuntimeException e) {
      System.err.println("Error: " + e.getMessage());
      e.printStackTrace();
      System.exit(1);
    }
    System.exit(exitCode);
  }

  @Override
  public void run() {
    if (!Files.exists(Paths.get(filename))) {
      throw new RuntimeException("File not found: " + filename);
    }
    if (outFilename != null) {
      try {
        pw = new PrintWriter(outFilename);
      } catch (FileNotFoundException e) {
        e.printStackTrace();
      }
    } else {
      pw = new PrintWriter(System.out);
    }
    RecipientAddresses addresses = null;
    try {
      addresses = new RecipientAddresses(Files.readAllLines(Paths.get(filename)).toArray(new String[0]));
    } catch (IOException e) {
      e.printStackTrace();
      pw.close();
      System.exit(1);
    }
    if ((!verify && !convert1UpToPipeDelimited) || (verify && convert1UpToPipeDelimited)) {
      System.err.println("Error: Must specify -verify XOR -1UpToPipe");
      pw.close();
      System.exit(1);
    }
    if (verify) {
      addresses.verify();
      int errorCount = addresses.getVerifyErrorCount();
      System.out.println(Ansi.colorize("Error count: ", Attribute.RED_TEXT(), Attribute.BOLD()) 
        + Ansi.colorize(String.valueOf(errorCount), Attribute.RED_TEXT(), Attribute.BOLD()));
      if (errorCount > 0) {
        pw.println(addresses.getVerifyErrors());
        pw.close();
        System.exit(0);
      }
    }
    if (convert1UpToPipeDelimited) {
      addresses.convert1UpToPipe();
      Arrays.asList(addresses.getLineStrings()).forEach(line -> pw.println(line));
    } 
    pw.close();
  }
}
</pre>

Here is the MANIFEST.MF:
<pre>
Manifest-Version: 1.0
Created-By: Maven Jar Plugin 3.2.0
Build-Jdk-Spec: 22
Class-Path: libs/JColor-5.5.1.jar libs/picocli-4.7.6.jar libs/picocli-co
 degen-4.7.6.jar libs/bnc-1.0.0.jar
Specification-Title: address-converter
Specification-Version: 1.0
Implementation-Title: address-converter
Implementation-Version: 1.0.0
Main-Class: gov.uscourts.bnc.app.AddressConverter
</pre>

Here is the META-INF/native-image/picocli-generated/reflect-config.json:
<pre>
[
  {
    "name" : "gov.uscourts.bnc.app.AddressConverter",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "convert1UpToPipeDelimited" },
      { "name" : "filename" },
      { "name" : "outFilename" },
      { "name" : "usageHelpRequested" },
      { "name" : "verify" },
      { "name" : "versionHelpRequested" }
    ]
  }
]
</pre>

There are also proxy-config.json and resource-config.json but they just show empty arrays/objects.

I used GRAAL_HOME/bin/native-image -jar address-converter-1.0.0.jar to create the  address-converter.jar binary file. I assume  native-image knows about the reflect-config.json file since it is in the jar file? (Couldn't get the maven-native-plugin to work)

**Comment by donpwinston** [comment]
Don't know why the formatting is messed up.

**Comment by remkop** [comment]
Please try removing `mixinStandardHelpOptions = true` from the `@Command` annotation.
You already have your own help and version options, so you do not need this mixin,
and from the error message, it is picocli's  `picocli.CommandLine$AutoHelpMixin` that is causing the problem.
This `AutoHelpMixin` is brought in when an application has `@Command(mixinStandardHelpOptions = true)`,

I suspect that removing `mixinStandardHelpOptions = true` will fix the problem.

**Comment by donpwinston** [comment]
Thanks. That was it. I love picocli. It is awesome.

**Comment by donpwinston** [comment]
Thanks that was it. I love picocli. It is awesome
