### ISSUE TITLE
AutoComplete with jline3 is showing hidden commands.

### ISSUE THREAD

**Issue by clebertsuconic** [remkop/picocli#2331]
#2074 fixed an issue with jline3 showing auto-complete for hidden attributes.

I just realized that hidden commands are also showing, so the fix for hidden attributes has to be somehow applied into commands as well.

As I was working on https://github.com/apache/activemq-artemis/pull/5132, I wanted to hide a command from the Shell, but hiding is not working for the Shell.

It's not such a big deal for me, so I will just remove the command for good in this case.. but it would be nice to have this fixed eventually.

**Comment by remkop** [comment]
Thank you for raising this!
Will you be able to provide a pull request for this?

**Comment by remkop** [comment]
Fixed in the main branch. Could you test this if you have a chance?

**Comment by clebertsuconic** [comment]
Sorry I couldn't fix this myself this time. 

I will test this soon and let you know here.
