### ISSUE TITLE
Plus extra options?

### ISSUE THREAD

**Issue by aadrian** [remkop/picocli#235]
Hi,

What would be the picocli way of having "plus extra options", e.g.
```bash
command subcommand <options> +extraOoption1 +extraOption2
```
e.g. this project is using this style of extra options https://github.com/luminus-framework/luminus-template

Thank you.

**Comment by remkop** [comment]
My initial take would be to simply define those options to have names that start with `+`. Something like:

```
class Extra {
  @Option(names = “+aleph”)
  boolean aleph;

  @Option(names = “+jetty”)
  boolean jetty;
}
```
So I believe it should work out of the box, unless I’m missing something?

**Comment by aadrian** [comment]
> My initial take would be to simply define those options to have names that start with

OK. Thank you, that should work too.

Just thought that operators have special handling, like '-', '--', '=', etc. and it would be possible to change that over a global setting.

**Comment by remkop** [comment]
No, in fact you can even have options that are just alphanumeric without a distinctive prefix. 

The only special processing is for posix clustered short options (like `tar -xvf FILE`). Those must start with a single hyphen.
