### ISSUE TITLE
Hide variable name from option description

### ISSUE THREAD

**Issue by Hakky54** [remkop/picocli#2354]
I am raising this issue as I haven't find a solution yet. I have found similar issues such as https://github.com/remkop/picocli/issues/1335 and https://github.com/remkop/picocli/issues/1984 I have even used the example provided [here](https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/customhelp/HideOptionParamsFromSynopsis.java) to improve the generated output from the help command.

I am using picocli in [certificate ripper](https://github.com/Hakky54/certificate-ripper)

This is initially what I had:
```
Usage: crip export pkcs12 [-hV] [--proxy-password] [--resolve-ca]
                          [-d=<destination>] [-p=<password>]
                          [--proxy-host=<proxyHost>] [--proxy-port=<proxyPort>]
                          [--proxy-user=<proxyUser>]
                          [-t=<timeoutInMilliseconds>] -u=<urls> [-u=<urls>]...
Export the extracted certificate to a PKCS12/p12 type truststore
  -d, --destination=<destination>
                         Destination of the to be stored file. Default is
                           current directory if none is provided.
  -h, --help             Show this help message and exit.
  -p, --password=<password>
                         TrustStore password. Default is changeit if none is
                           provided.
      --proxy-host=<proxyHost>
                         Proxy host
      --proxy-password   Password for authenticating the user for the given
                           proxy
      --proxy-port=<proxyPort>
                         Proxy port
      --proxy-user=<proxyUser>
                         User for authenticating the user for the given proxy
      --resolve-ca       Indicator to automatically resolve the root ca
  -t, --timeout=<timeoutInMilliseconds>
                         Amount of milliseconds till the ripping should timeout
  -u, --url=<urls>       Url of the target server to extract the certificates
  -V, --version          Print version information and exit.
```

Basically I don't prefer to have the java variable name printed in the console when getting the output of the help command. With the example code [here](https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/customhelp/HideOptionParamsFromSynopsis.java) I have been able to remove the variable names from the usage section.

I was able to get it to the following snippet:
```
Usage: crip export pkcs12 [-hV] [--proxy-password] [--resolve-ca] [-d] [-p]
                          [--proxy-host] [--proxy-port] [--proxy-user] [-t] -u
                          [-u]...
Export the extracted certificate to a PKCS12/p12 type truststore
  -d, --destination=<destination>
                         Destination of the to be stored file. Default is
                           current directory if none is provided.
  -h, --help             Show this help message and exit.
  -p, --password=<password>
                         TrustStore password. Default is changeit if none is
                           provided.
      --proxy-host=<proxyHost>
                         Proxy host
      --proxy-password   Password for authenticating the user for the given
                           proxy
      --proxy-port=<proxyPort>
                         Proxy port
      --proxy-user=<proxyUser>
                         User for authenticating the user for the given proxy
      --resolve-ca       Indicator to automatically resolve the root ca
  -t, --timeout=<timeoutInMilliseconds>
                         Amount of milliseconds till the ripping should timeout
  -u, --url=<urls>       Url of the target server to extract the certificates
  -V, --version          Print version information and exit.
```

So the usage section doesn't have the java variable names, however in the explanation of the options I still see the variable names wrapped in arrows such as `=<proxyPort>` `=<destination>` `=<proxyPort>` `=<timeoutInMilliseconds>`. Any idea how I can remove it from that section?

**Comment by remkop** [comment]
Sorry I didn't read your message carefully so let me know if I misunderstood but might you be looking for `paramLabel` (https://picocli.info/#_parameter_labels)?

**Comment by Hakky54** [comment]
Correct, it is indeed the paramLabel. I can define a custom one as shown on the link you have shared, however I am not able to hide it. I highlighted the sections below which I want to hide.

<img width="650" alt="Screenshot 2024-12-09 at 00 48 11" src="https://github.com/user-attachments/assets/5ceebf7e-43d7-4b61-be8b-c8f088c6494a">

Do you think it is possible to hide all of the red marked labels?

By the way, I would like to thank you for providing this amazing library to simplify the creation of a CLI app. It does the job very well and it is easy, and the dependency injection part is also really well done!

**Comment by remkop** [comment]
Hi @Hakky54 , there is another example that shows how to remove the param labels from the options table:
https://github.com/remkop/picocli/blob/main/picocli-examples/src/main/java/picocli/examples/customhelp/HideOptionParams.java

I believe this should do what you want.

**Comment by Hakky54** [comment]
Thank you for guiding me into the right direction. I got it working with combining the both examples. The resulting code is here: https://github.com/Hakky54/certificate-ripper/blob/6aafe47c073fd057f74a5970c440ac26933e6af5/src/main/java/nl/altindag/crip/util/HelpFactory.java#L26

I am closing this issue.
