### ISSUE TITLE
Code sample to catch empty parameters and get help message instead of exception

### ISSUE THREAD

**Issue by adriens** [remkop/picocli#243]
Hi,

when running the command line without any parameters (even the required ones), what's the best way to catch that and display the help essage instead of ``` picocli.CommandLine$MissingParameterException``` ?

Thanks in advance for your help. I'm starting to protoype on your lib and CLI color syntaxing is really nice !

**Comment by remkop** [comment]
Take a look at the first example in the http://picocli.info/picocli-2.0-do-more-with-less.html article.

Basically, the convenience methods (`run`, `call` and `parseWithHandler`) take care of a lot of boilerplate code, including exception handling.

If, for any reason, you want to use the `parse` method, I would recommend catching `ParameterException` and printing the exception message and the usage help message:
```
App myApp = new App();
try {
    new CommandLine(myApp).parse(args);
} catch (ParameterException ex) {
    System.err.println(ex.getMessage());
    new CommandLine(myApp).usage(System.err);
}
```

**Comment by adriens** [comment]
Thanks a lot, this is exactlt the code i was looking for !
Have a nice we 😸
