### ISSUE TITLE
subcommands are not parsed when usageHelp = true and required param is missing

### ISSUE THREAD

**Issue by mkavanagh** [remkop/picocli#244]
I'm implementing a CLI where the top-level command has two params (a `required = true` param and a `usageHelp = true` param), plus a number of subcommands

When the command is parsed with the `required` param missing and the `usageHelp` param supplied, I can check `isUsageHelpRequested` and print the usage for the top level command

When a subcommand is included I have to either:
- include the required param as well in order to get the subcommand parsed without error (so that I can print the usage for it), or
- annotate the help param with `help = true` as well as `usageHelp = true` in order to pass the check at https://github.com/remkop/picocli/blob/master/src/main/java/picocli/CommandLine.java#L2094 and still be able to tell whether help was requested (I can't see any way to tell if a param with just `help = true` was parsed)

**Comment by remkop** [comment]
Thank you for reporting this!

I've fixed the issue in master. I will roll a release for this as soon as possible, hopefully within 24 hours.
