### ISSUE TITLE
License file still contains unfilled template

### ISSUE THREAD

**Issue by Col-E** [remkop/picocli#246]
Link to [specific line.](https://github.com/remkop/picocli/blob/master/LICENSE#L189)

Text of line:
```
   Copyright {yyyy} {name of copyright owner}
```

**Edit:** As @RobertZenz stated in the source the template is used and is filled in, but the actual license file itself still has the template format unfilled. Could be removed or filled in.

**Comment by RobertZenz** [comment]
That line is not part of the license, though. It is the template to use for the source headers. That whole section could be removed.

**Comment by Col-E** [comment]
Good point, edited title.

**Comment by remkop** [comment]
Hi guys!

I just took a copy of the license from http://www.apache.org/licenses/LICENSE-2.0 and although it would probably be okay to remove the appendix I prefer to keep the original. 

I do appreciate the scrutiny though!
Please let me know if there’s any other potential improvement. 

Kind regards, Remko

**Comment by Col-E** [comment]
If you prefer it that way, then ok.
