### ISSUE TITLE
Programatically added subcommands don't appear in help

### ISSUE THREAD

**Issue by vromero** [remkop/picocli#249]
When I add my commands like this:

```java
subcommands = {
    TransformCommand.class,
    ValidateCommand.class
}
```

This shows the help as it should be:

```
Commands:
  transform  Transforms ...
  validate   Validates ...
```

However, when I add them like this:
```java
        commandLine.addSubcommand("transform", new TransformCommand());
        commandLine.addSubcommand("validate", new ValidateCommand());
```
Nothing appears in help, and to make things very ackward, the commands actually work when I call them, they are just not appearing in the help.

Am I missing something?

**Comment by remkop** [comment]
That is strange indeed. I need some more detail to try to reproduce the issue. What version of picocli are you using? What does your program look like?

**Comment by remkop** [comment]
I was unable to reproduce the issue with this program:
```
public class SubCommandHelpTest {
    
    static class Top {
        @Option(names = "-h", usageHelp = true, description = "Prints this help and exits")
        boolean help;
    }

    @Command(description = "subcommand 1")
    static class Sub1 {
        @Option(names = "-o", description = "option 1")
        int intOption;

        @Option(names = "-d", description = "option 2")
        double doubleOption;
    }
    
    public static void main(String[] args) {
        CommandLine commandLine = new CommandLine(new Top());
        commandLine.addSubcommand("sub", new Sub1());
        commandLine.usage(System.out);
    }
}
```
The above produces the expected output:
```
Usage: <main class> [-h]
  -h                          Prints this help and exits
Commands:
  sub  subcommand 1
```

Can you show more of your program?

**Comment by vromero** [comment]
Let me create a minimalistic version to reprodudce

**Comment by vromero** [comment]
I have been able to reproduce here: `https://github.com/vromero/try-subcommand` instructions in the `README.md`

**Comment by vromero** [comment]
Actually I found **my mistake** while writing it. I was passing `this` instead of the actual command line when printing the help. That is why only when added as annotation worked.

Apologies for the unnecessary noise and THANKS! for the absolutely great piece of software. Would add a star now but already did!

**Comment by remkop** [comment]
Glad to hear that!

By the way, since you are writing an application with subcommands you may be interested in the new `@ParentCommand` annotation that will be in the upcoming 2.2 release (hopefully end of this week).

For details, see https://github.com/remkop/picocli/wiki/Manual-(2.2.0-SNAPSHOT)#code-parentcommand-code-annotation
