### ISSUE TITLE
Support @Inject annotation to inject CommandSpec into command implementation

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#259]
See for example the auto-help use case: a `command help subcommand` command should print help for the specified subcommand of the parent command. This means it needs to obtain a subcommand `CommandLine` or `CommandSpec` object from the parent command. The `@ParentCommand` annotation does not work because it injects the user-defined command object, not the picocli class.

Another use cases is custom commands that need to know exactly which options were actually specified on the command line. This could be accomplished by injecting the `ParseResult` (#257).

A generic `@Inject` annotation is generic and flexible enough to allow future extensions, while at the same time the meaning is intuitively clear to many users because of its similarity to JSR-330 (`javax.inject.Inject`).

**Comment by kakawait** [comment]
@remkop Nice addition. First at all, I didn't try why I will speak about but currently on _picocli-spring-boot-starter_ command use to be a _Spring component/bean_. And _Spring_ in addition to `@Autowired` annotation is also aware of `@Inject` annotation for DI.

But `CommandSpec`, `CommandLine` and `ParseResult` will  not be registered on _Spring context_ (no sense to register it), so I'm afraid that _Spring_ will complain about:

```
No bean of type ... found
```

What do you think about?

How we can solve that? I think with alternative and _more old school_ way to inject that component for example by implementing a _picocli_ `interface` which defined 3 setters (or whatever) that will be used by _picocli_ to inject that components.

**Comment by remkop** [comment]
I think Spring is looking for the `javax.inject.Inject` annotation, while this is a custom `picocli.CommandLine.Inject` annotation. I don't think Spring will see the picocli annotation. 

If a class uses both the picocli and the javax `@Inject` annotation, then at least one of them needs to be annotated with the fully qualified class name.

**Comment by kakawait** [comment]
Lol my bad I read to quickly I though it was `javax.inject.Inject`. Sorry

**Comment by remkop** [comment]
No worries. Thanks for checking!

**Comment by kakawait** [comment]
Are you not afraid that people will have confusion between both annotations, and some of them will still import `javax.inject.Inject` instead of `picocli.CommandLine.Inject`

**Comment by remkop** [comment]
Yes there is some risk there. The benefits are no external dependency and a name that is intuitively obvious in what it does. So there’s a trade-off. I’ll add a note in the documentation. Thanks for pointing this out.

**Comment by remkop** [comment]
It turns out that the custom HelpCommand use case also required that the `Help.Ansi` object and the output `PrintStream` are injected...  It’s becoming a bit too “magical”...

Reconsidering defining a `IHelpCommand` interface instead.

**Comment by remkop** [comment]
I introduced interface `picocli.CommandLine.IHelpCommandInitializable` to implement the custom help command use case.

I reverted commits 2cb8d66 and a781f80 to remove the `@Inject` functionality for now, until another use cases comes up.

**Comment by fcorneli** [comment]
I'm also looking for a way to "help subcommand" properly.

**Comment by remkop** [comment]
@fcorneli Can you try with current master?

**Comment by remkop** [comment]
Picocli 3.0 (in master) has a built-in help command that can give help on a specified subcommand or on the preceding command. 

See https://github.com/remkop/picocli/wiki/Manual-(3.0.0-SNAPSHOT)#built-in-help-subcommand

**Comment by remkop** [comment]
FYI: I ran into a use case that requires access to the picocli command model from the application, so this will be available from picocli 3.2.

The use case has to do with JLine completion candidates (#393, also in v3.2).
 Some completion candidates need to be looked up dynamically from some resource that is only available at runtime. Access to the CommandSpec is needed to update the option's ArgSpec.completionCandidates after the lookup.
