### ISSUE TITLE
Feature request: mask default value

### ISSUE THREAD

**Issue by ymenager** [remkop/picocli#262]
Hi,

Could you please allow to mask the default value of an option (for example if the option is a password).

Might sound a rare use-case, but in my case I'm loading default properties from a config file, some of which might be credentials

**Comment by ymenager** [comment]
I've implemented this feature and made a pull request for it: #263

**Comment by remkop** [comment]
Would it meet your requirements if we added a `@Option(showDefaultValue = true|false)` attribute instead? 

This would allow users to control whether default values should be displayed or not on a per-option basis, which is probably useful to have anyway, and would accomplish your goal of hiding sensitive information.

Example:

```java
@Test  
public void testOptionAttributeShowDefaultValue() throws UnsupportedEncodingException {  
    @Command
    class Params {
        @Option(names = {"-p"}, description = "password", showDefaultValue = false)
        String password = "mypassword";
        
        @Option(names = {"-u"}, description = "user", showDefaultValue = false)
        String user = "guest";
    }
    String result = usageString(new Params(), Help.Ansi.OFF); 
    assertEquals(format("" +
            "Usage: <main class> [-p=<password>] [-u=<user>]%n" +
            "  -p= <password>              password%n" +
            "  -u= <user>                  user%n" +
            "                                Default: guest%n"), result);  
}  
```

**Comment by ymenager** [comment]
Yes that would work too, the masking is just a little bit nicer on a usage point of point IMO, but I'd be happy just with showDefaultValue per option

**Comment by remkop** [comment]
This is now implemented in master. Please verify if this meets your requirements.

The wiki shows the updated user manual (see relevant [section on default values](https://github.com/remkop/picocli/wiki/Manual-(3.0.0-SNAPSHOT)#show-default-values)).

**Comment by ymenager** [comment]
Yup looks good thanks :)
