### ISSUE TITLE
positional parameter defaults not shown 

### ISSUE THREAD

**Issue by ymenager** [remkop/picocli#263]
I've just noticed something odd... the documentation for 'showDefaultValues' says 'default values for options and parameters should be shown'

However it doesn't display default values for parameters... I'm guessing it's just the javadoc that's wrong ?

**Comment by remkop** [comment]
Thanks for raising this. I did not realize until now, but positional parameter help is not as full-featured as option help. Default values are not displayed and the required marker is not displayed. This should be fixed in the code.
