### ISSUE TITLE
Add gradle dependency line to README.

### ISSUE THREAD

**Issue by ror6ax** [remkop/picocli#272]
Thanks for this terrific library!
I would like to add gradle config line to README.
It's inconvenient to look for it elsewhere, usually is in the first manual there is for a library.

**Comment by remkop** [comment]
Thanks for the kind words! 
Not sure I understand what you have in mind. Can you show what you want to change exactly?

**Comment by ror6ax** [comment]
I mean, there's usually smth like

`compile group: 'org.hibernate', name: 'hibernate-core', version: '3.6.7.Final'` in the docs, so I can grab it and paste to my gradle file.

I was suggesting adding it as I'm now spending about 10 minutes and can't find how to do it correctly...

**Comment by ror6ax** [comment]
Found one at https://mvnrepository.com/artifact/info.picocli/picocli/0.9.5

**Comment by remkop** [comment]
Oh I see what you mean now. 
It’s in the manual: http://picocli.info/#_gradle
But I’ll add it to the readme also.

**Comment by remkop** [comment]
Pushed to master. Thanks for raising this!
