### ISSUE TITLE
Add the ability to hide a command 

### ISSUE THREAD

**Issue by pditommaso** [remkop/picocli#277]
It would be useful to have a `hidden` attribute in the `Command` annotation to not include such command in the produced usage text, eg:

```
@Command(name="foo", hidden=true )
class Foo {

}
```

**Comment by remkop** [comment]
Ok, interesting. Should not be too hard to implement. 

I’m curious about your use case though. Why would one want to do this?

**Comment by pditommaso** [comment]
Because we have some experimental commands, we want to keep undocumented.

**Comment by remkop** [comment]
Ok, I see how that could be useful. 

Do you think you can provide a pull request for this? I don’t mind doing this but I’m currently working on other picocli issues and I don’t know when I’ll get to it.

**Comment by pditommaso** [comment]
I can surely give a try to this.

**Comment by remkop** [comment]
Thanks for the pull request!
This has been merged with some minor changes.

Keep ‘em coming!

**Comment by pditommaso** [comment]
Nice. If I'm understanding well this goes into version 3.0. Is there a planned release date or just estimated?

**Comment by remkop** [comment]
No planned release date yet. Picocli 3.0 is still very much a work in progress, especially the new programmatic API (CommandSpec, OptionSpec etc.) - this is not feature complete without #257. Other bits also still need polishing.

I am considering doing one or more 3.0-alpha (early access) releases, so people can provide feedback, with the understanding that the API may change between now and the final 3.0 release. Would that be useful for you?

**Comment by pditommaso** [comment]
sure thing
