### ISSUE TITLE
Command Line History Accessible via Up Arrow

### ISSUE THREAD

**Issue by aspearman** [remkop/picocli#296]
Is it possible to access previous command history using Picocli? Like how a regular terminal can toggle through previous commands using the up arrow?

If not, this would be an excellent feature to add!

**Comment by remkop** [comment]
This is a good feature to add to a picocli-based interactive shell (#242). Nice idea!

**Comment by Awesomekiwi** [comment]
Okay, is there some sort of a workaround for now? I'm not sure how to implement it. 

Maybe capture raw input and append it to a list of previous commands before I send the input to CommandLine? In which case command line history is totally independent of picocli.

Yeah, it really would be nice to have this in-built.

**Comment by remkop** [comment]
The upcoming picocli 3.0 release will have a new class `ParseResult` which has the original input. An application could keep references to these `ParseResult` objects to maintain a history.

There’s work in progress (#293) to provide a command tokenizer which will be an important building block for an interactive shell. To be honest, I haven’t given this area much thought yet other than what is happening on #293. This may grow in the future.

**Comment by PorygonZRocks** [comment]
I'll look into something for this at some point, hopefully this week because it is spring break here. It would probably be in the new `picocli.interactive` package, or the normal one?

**Comment by remkop** [comment]
Nice! `picocli.interactive` would be the right package.

**Comment by remkop** [comment]
Looks like I forgot to close this.
I believe that JLine has built-in support for navigating through the history of executed commands with the up/down arrow keys.
