### ISSUE TITLE
separator inheritance

### ISSUE THREAD

**Issue by fcorneli** [remkop/picocli#300]
Would be handy that subcommand would inherit the separator from the parent command.
Now I have to define the separator on every subcommand separately.

**Comment by remkop** [comment]
Mixins (coming in 3.0) will help with this: first set up a command hierarchy without specifying a separator, then add a mixin that defines your custom separator. The mixin will be applied to the full hierarchy. (You can try this with current master.)

**Comment by remkop** [comment]
Also, did you know that if you register the subcommands first, and then set the separator on the top-level command, the new setting will be applied to all registered subcommands?

**Comment by remkop** [comment]
Closing this issue as the requested functionality has been implemented (see above comments). Feel free to reopen if there's any issue.
