### ISSUE TITLE
[Feature Request] Requiring at least one from a given set of options

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [remkop/picocli#304]
Kindly consider adding feature to validate that atleast one of given options must be provided. Example: either --config-file or --config-string must be specified. But if --config-file is specified, --config-string is not needed and vice-versa.

**Comment by remkop** [comment]
Hi, thank you for raising this!

Is this similar to this ticket: "Add support for mutual exclusive options" #199 ?

**Comment by Kshitiz-Sharma** [comment]
Thanks for this awesome library. Its the best arg parser there is.

Yes its the same thing.

**Comment by remkop** [comment]
Cool! 
#199 is in progress. It won't be in the 3.0.0-alpha-1 release, but in one of the subsequent releases. Please be patient! :-)
