### ISSUE TITLE
How to parse single string, not string array?

### ISSUE THREAD

**Issue by saaadel** [remkop/picocli#324]
[just question]
Can I use picocli to parse single String, not String array?
For example, I have system property that contains all args with spaces, quotes and escaped quotes there.
How to parse it?

**Comment by remkop** [comment]
There is work in progress (see #293) on a tokenizer that splits up a single string into an array of command line arguments, which can then be processed with the `CommandLine` class as usual. 

Can you try using the `CommandTokenizer` class in #293 and see if it does what you need? (Feedback very welcome.)

**Comment by remkop** [comment]
Did this answer your question?

**Comment by saaadel** [comment]
I need two days to check this

**Comment by saaadel** [comment]
Ok, I've reviewed this PR and ran some tests. It works like ArgumentTokenizer class from DrJava project.

Feedback on your implementation: 
- Throws ArrayIndexOutOfBoundsException for empty command line or for command line with spaces only. I think it will be better to return empty array, ArgumentTokenizer works and returns zero length array.
- if we will have multiple spaces between params - we will get this as empty params in the array. Example: "abc   xyz" (three spaces between params) -> Returns: [abc, , , xyz].  FYI ArgumentTokenizer skips those repeatable spaces

Conclusion: 
DrJava's class works better now. Please, fix issues.

PS. anyway, I'm searching for something with escapes in windows notation too (with caret symbol. Example: ^" escaped quote) - in separate method or in the same

**Comment by saaadel** [comment]
also, why you have two methods with separate implementation? what needs?
`new CommandTokenizer().parse(str)`
`new CommandTokenizer().parse(scanner)`

I mean, why you not replaced parse(str) with short code:
`parse(new Scanner(cmd))` 
?

if in following code: 
`new CommandTokenizer(cmd).getTokens()`

you make something same (meta code):
```
input = new Scanner(cmd);
parse(input);
```

**Comment by saaadel** [comment]
Closing the question, temporary imported the ArgumentTokenizer class, but plan to switch your version, when you will publish it in maven with that PR and fixed issues.

**Comment by saaadel** [comment]
Closing the question, temporary imported the ArgumentTokenizer class, but plan to switch your version, when you will publish it in maven with that PR and fixed issues.

**Comment by remkop** [comment]
Cool. Thanks for reviewing the CommandTokenizer class!

**Comment by ibalashov** [comment]
Sorry to revive the old thread, but was the `CommandTokenizer` finally published? Somehow I can't locate it in the latest Maven release.

**Comment by remkop** [comment]
No, it wasn’t. 
Instead, we decided to add two modules, `picocli-shell-jline2` and `picocli-shell-jline3`, and leverage the tokenizer built in to JLine.

**Comment by ibalashov** [comment]
@remkop Thanks! 

However, I don't see any relevance of jline to solve the problem of this thread, i.e. parsing the full text command into the arguments. Do I miss something? 😕  It looks jline is about interactive command input only.

Just to clarify my use case: I want to use picocli to parse a raw user command which comes as a single text line. Does picocli provide this, or should I use some external tool to parse it to the list of arguments?

**Comment by remkop** [comment]
Picocli does not provide functionality to parse a single String into separate command arguments. See also https://github.com/remkop/picocli/issues/242 for more discussion and background.

The reason I mention JLine is that this library [does provide it](https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/DefaultParser.java) in its `DefaultParser` class.
