### ISSUE TITLE
Create command map like "jar" program

### ISSUE THREAD

**Issue by amsitlab** [remkop/picocli#331]
Any one can guide me , how to create command map like "jar" program?
```bash
jar c[efmMnv0] [entrypoint] [jarfile] [manifest] [-C dir] file ... [-Joption ...] [@arg-file ...]
```
when **-C** option can repeated call.

**Comment by amsitlab** [comment]
how to handle **-C** flag(s) if command like this?

```bash
jar cvf output.jar -C images . -C audio . 
```

**Comment by amsitlab** [comment]
@remkop tank for answers, I will try it.

**Comment by amsitlab** [comment]
Btw .. **-C** flags in "jar" program is truly change directory to process or just replace filename when we packing to jar archive?
I not have jar program on my davice.

**Comment by amsitlab** [comment]
I run it on android with ecj batch compiler and compile again to dex bytecode  .. so I want to create program like "jar" .. for packaging my programs.

**Comment by remkop** [comment]
To be honest I’ve never experimented with the `-C` option of the `jar` command. You’ll have to try yourself, the docs are a bit brief...

Anyway, you don’t need to copy what other applications do, just provide functionality that makes sense for your application and your users.  :-)

**Comment by remkop** [comment]
Did that answer your question?

**Comment by amsitlab** [comment]
Can you guide me to implementing ITypeCoverters ?

**Comment by remkop** [comment]
The user manual has some examples:
http://picocli.info/#_custom_type_converters

**Comment by remkop** [comment]
Did that answer your question?

**Comment by amsitlab** [comment]
Yess..
But now I will ask again.
Can I put code like this? :
```java
@Parameters(name="phone-num")
private String phonenum;

@Parameters(name="message")
private String message;
```

and wiil give command map like:
```bash
command-name [phone-num] [message]
```

can I do that?
I had tried it. But when I put command like:
```bash
command-name 123456
```
value of "[phone-num]" parameter is set to 123456
value of "[message]" parameter is set to 123456 

how to validate if [phone-num] has set, then [message] reqiured.
but if [phone-num] is not set, [message] is optional.

**Comment by remkop** [comment]
If you don't specify the index of a positional parameter, the default index is `0`.
So both `phonenum` and `message` had index=0 and received the same value (the first positional parameter).

I think what you want to do is this:
```java
// index=0: this is the first positional parameter
// You can set arity=1 to make this positional parameter mandatory
@Parameters(index = "0", arity = "1", paramLabel="phone-num")
private String phonenum;

// index=1: this is the second positional parameter
// You may set arity=0..1 to make a positional parameter optional
@Parameters(index = "1", arity = "0..1", paramLabel="message")
private String message;
```
Any validation logic that involves multiple fields needs to be implemented by the application.

**Comment by amsitlab** [comment]
Thank you for answer.

how to add "help" subcommand,
I was followed http://picocli.info/#_built_in_help_subcommand
and this mycode

```java 
import picocli.CommandLine.HelpCommand;


@Command(name = "cmd",                                            version = "1.1",                                            mixinStandardHelpOptions = true,                            helpCommand = true,                                         subcommands = {                                                     
        Main.Sender.class,                                          
        HelpCommand.class
}
)
```

but when I execute:
```bash
cmd help
```

no given anything, no error , no output.

**Comment by remkop** [comment]
You don’t want to use `helpCommand=true`.

**Comment by amsitlab** [comment]
I was removed that, but still no output.

**Comment by remkop** [comment]
Can you switch on tracing and show the output here?
http://picocli.info/#_tracing

**Comment by remkop** [comment]
Has the problem been resolved?

**Comment by remkop** [comment]
Closing this ticket. Feel free to reopen or open a new one if more questions come up.
