### ISSUE TITLE
Adding sub command description on generated usage help

### ISSUE THREAD

**Issue by jcapsule** [remkop/picocli#333]
The generated help with included subcommands, does not show how to apply the subcommand.

For example:
<pre><code>public class DemoApp {

    @Command(name = "demo", subcommands = DemoCmd.class)
    static class Demo implements Runnable {

        @Option(names = {"-h", "--help"}, usageHelp = true)
        private boolean help;

        public void run() {
            System.out.println("Print help message.");
        }
    }

    @Command(name = "cmd")
    static class DemoCmd implements Runnable {

        @ParentCommand
        private Demo parent;

        @Override
        public void run() {
            System.out.println("DONE");
        }
    }

    public static void main(String[] args) {
        CommandLine.run(new Demo(), System.out, "-h");
    }
}</code></pre>
prints to the console:
<pre><code>Usage: demo [-h]
  -h, --help
Commands:
  cmd
</code></pre>

The user may be asking how to apply the subcommand since it is only showing `demo [-h]`.

Could be possible to show for example:

<pre><code>Usage: demo [-h] <b>[command]</b>
</code></pre>

**Comment by remkop** [comment]
I think that's a good idea.
Do you think you can create a pull request for this?

**Comment by jcapsule** [comment]
I created the pull request for this feature.

**Comment by remkop** [comment]
Nice work, thank you!
I merged the PR into master and this will be part of the upcoming 3.0 release (no timeline yet).
