### ISSUE TITLE
ArgSpec should not implement `equals` and `hashCode`

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#335]
Rename to `equalsImpl(ArgSpec)` and `hashCodeImpl` and make protected.

NOTE: the current implementation excludes these attributes:
* showDefaultValue
* converters
* getter
* setter
* initialValue
* toString

TBD remove equals/hashCode altogether from this object hierarchy?

**Comment by bbottema** [comment]
I'm curious what the reasoning for this was. What was the issue?

**Comment by bbottema** [comment]
Ahh, equals symmetry, got it. Yep, excellent book, I liked Refactoring (Martin) and Clean Coder (of course, Uncle Bob) as well.
