### ISSUE TITLE
Add integration testing support by never calling System.exit

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#367]
At the very least, there should be some documentation describing how one is expected to test applications built with picocli. However, much can be improved by never calling `System.exit`, but instead deferring this to the actual application. This way, one can easily test applications by asserting on exit codes. This is currently possible in JCommander for example. Something similar to the [Spring Boot starter](https://github.com/kakawait/picocli-spring-boot-starter)'s `ExitStatus` is what I'm thinking.

**Comment by remkop** [comment]
I'm not sure that I understand the problem: picocli only calls `System.exit` if requested by the application, as documented here: http://picocli.info/#_exit_code . If the `andExit(int)` method is not called, picocli will not call `System.exit`.

Good point about documenting how to test picocli-based applications. This topic came up before (see #218) and it's on my todo list to write an article about testing. 

To give you a quick tip: I've started to use Stephan Birkner's [SystemErrAndOutRule](http://stefanbirkner.github.io/system-rules/#SystemErrAndOutRule) and [ExpectedSystemExit](http://stefanbirkner.github.io/system-rules/#ExpectedSystemExit) rule. This works very well for JUnit 4. If you using JUnit 5, and you need this urgently, you can offer Stefan to help with his [work in progress](https://github.com/stefanbirkner/system-rules/issues/55) on a JUnit 5 extension.

**Comment by remkop** [comment]
From this ticket's title I am guessing there may have been a misunderstanding, am I correct?

**Comment by bobtiernay-okta** [comment]
Correct, sorry, and thank's for the links!
