### ISSUE TITLE
Add ability to run by class literal

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#369]
For commands with a parent command which is not to be invoked, it would be nice to allow class literals as input to the `run` command.

Here's a simple example:

```java
@Command(... subcommands = {
        A.class,
        B.class,
        C.class})
interface All  {
}

...

public final class Main {

    public static void main(String[] args) {
       CommandLine.run(All.class, args);
    }

}
```

I was thinking this could also be applied to `abstract` classes for `@ParentCommand` injection. Such commands would not influence the CLI, but would simply be a handy way to aggregate commands.  Perhaps a `@AggregateCommand` annotation is more appropriate?

**Comment by remkop** [comment]
For the `run` and `call` convenience methods, all commands in the hierarchy must implement either `Runnable` or `Callable`. The simplicity of this API is what makes it so easy to understand and use. So I'm hesitant to drop this requirement.

That said, I do plan to support annotated interfaces. Specifically, in a future version it will be possible to call `CommandLine.populate(MyInterface.class, args)` and get back an _instance_ of `MyInterface`. Picocli will return a [Proxy](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Proxy.html)-backed instance for the methods that were annotated with `@Option` and `@Parameters`, similar to [JewelCli](http://jewelcli.lexicalscope.com/). 

However I was only thinking about single commands so far. I'd be interested to hear your thoughts on applying this to command hierarchies.

**Comment by bobtiernay-okta** [comment]
Well, if the command in my example extended `Runnable`, wouldn't that satisfy your desire to keep that a requirement? There would be no obligation to implement the method since it's an interface. Same would be true of an abstract class.

**Comment by remkop** [comment]
To be honest, I don't understand the original use case. What is a "parent command which is not to be invoked"? 

So, while I don't (yet) understand the upside, I do see some potential downside, in that users can shoot themselves in the foot.

For example, in your original example, what happens when the command is invoked without any parameters? This would invoke the parent command, but there's no instance...

Or when an interface (without implementation) is specified but the program is started with:

```java
public static void main(String[] args) {
    CommandLine.parseWithHandler(new RunFirst(), args); // invokes the parent command
}
```

**Comment by bobtiernay-okta** [comment]
Maybe you're right. I guess having something like this isn't too bad:

```java
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.HelpCommand;

import java.util.concurrent.Callable;

@Command(name = "all", mixinStandardHelpOptions = true, versionProvider = ManifestVersionProvider.class, subcommands = {
        HelpCommand.class,
        CheckCommand.class,
        CountCommand.class,
        ExplainCommand.class,
        IdentifyCommand.class,
        DeleteCommand.class})
public class AlllCommand implements Callable<Integer> {

    @Override
    public Integer call() {
        new CommandLine(this).usage(System.out);

        return 0;
    }

}
```

**Comment by remkop** [comment]
Are you okay to close this ticket?

**Comment by bobtiernay-okta** [comment]
Yep!
