### ISSUE TITLE
Support indexing relative to 'last' position (was: Unbounded arity param)

### ISSUE THREAD

**Issue by 0rtis** [remkop/picocli#370]
Is it possible to use unbounded arity parameter without being the last parameters ?
The following code

```
	@Parameters(index = "0", description = "Folder")
	private String folder;

	@Parameters(index = "1", arity = "1...*", description = "Source paths")
	private String [] sources;

	@Parameters(index = "2", description = "Destination folder path")
	private String destination;
```

 is throwing `picocli.CommandLine$MissingParameterException: Missing required parameter: <destination>`  when called with `MyClass folder source1 source2 source3 destination`

**Comment by remkop** [comment]
If you switch on [tracing](http://picocli.info/#_tracing), you can see how picocli is processing these arguments:

```
[picocli INFO] Parsing 5 command line args [folder, source1, source2, source3, destination]
[picocli DEBUG] Parser configuration: posixClusteredShortOptionsAllowed=true, stopAtPositional=false, stopAtUnmatched=false, separator=null, overwrittenOptionsAllowed=false, unmatchedArgumentsAllowed=false, expandAtFiles=true, limitSplit=false, aritySatisfiedByAttachedOptionParam=false
[picocli DEBUG] Set initial value for field String picocli.CommandLineArityTest$7App.folder of type class java.lang.String to null.
[picocli DEBUG] Set initial value for field String[] picocli.CommandLineArityTest$7App.sources of type class [Ljava.lang.String; to null.
[picocli DEBUG] Set initial value for field String picocli.CommandLineArityTest$7App.destination of type class java.lang.String to null.
[picocli DEBUG] Initializing picocli.CommandLineArityTest$7App: 0 options, 3 positional parameters, 3 required, 0 subcommands.
[picocli DEBUG] Processing argument 'folder'. Remainder=[source1, source2, source3, destination]
[picocli DEBUG] 'folder' cannot be separated into <option>=<option-parameter>
[picocli DEBUG] Could not find option 'folder', deciding whether to treat as unmatched option or positional parameter...
[picocli DEBUG] folder doesn't resemble an option
[picocli DEBUG] No option named 'folder' found. Processing remainder as positional parameters
[picocli DEBUG] Processing next arg as a positional parameter at index=0. Remainder=[folder, source1, source2, source3, destination]
[picocli DEBUG] Position 0 is in index range 0. Trying to assign args to field String picocli.CommandLineArityTest$7App.folder, arity=1
[picocli INFO] Setting field String picocli.CommandLineArityTest$7App.folder to 'folder' (was 'null') for args[0] at position 0
[picocli DEBUG] Consumed 1 arguments, moving position to index 1.
[picocli DEBUG] Processing argument 'source1'. Remainder=[source2, source3, destination]
[picocli DEBUG] 'source1' cannot be separated into <option>=<option-parameter>
[picocli DEBUG] Could not find option 'source1', deciding whether to treat as unmatched option or positional parameter...
[picocli DEBUG] source1 doesn't resemble an option
[picocli DEBUG] No option named 'source1' found. Processing remainder as positional parameters
[picocli DEBUG] Processing next arg as a positional parameter at index=1. Remainder=[source1, source2, source3, destination]
[picocli DEBUG] Position 1 is in index range 1. Trying to assign args to field String[] picocli.CommandLineArityTest$7App.sources, arity=1..*
[picocli INFO] Adding [source1] to field String[] picocli.CommandLineArityTest$7App.sources for args[1] at position 1
[picocli INFO] Adding [source2] to field String[] picocli.CommandLineArityTest$7App.sources for args[1] at position 1
[picocli INFO] Adding [source3] to field String[] picocli.CommandLineArityTest$7App.sources for args[1] at position 1
[picocli INFO] Adding [destination] to field String[] picocli.CommandLineArityTest$7App.sources for args[1] at position 1
[picocli DEBUG] Consumed 4 arguments, moving position to index 5.

picocli.CommandLine$MissingParameterException: Missing required parameter: <destination>

	at picocli.CommandLine$Interpreter.assertNoMissingParameters(CommandLine.java:5568)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:4797)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:4694)
	at picocli.CommandLine.parse(CommandLine.java:523)
	at picocli.CommandLine.populateCommand(CommandLine.java:504)
```

The unbounded arity means that the `sources` positional parameter consumes all following input from index 1. So the parameter with unbounded arity will effectively always come last.

This is very similar to how in Java, in a method with a varargs parameter, the varargs parameter should always come last in the parameter list. So perhaps the best way to solve this is to swap parameters so that `destination` comes before `sources`.

**Comment by 0rtis** [comment]
Sure, swapping the parameters would works but I find `sources destination` order to be more natural. 

I tried to set the arity of `destination` to 0 so I could just used the last entry of `sources` as the value for `destination` while keeping a consistent help :

```
	@Parameters(index = "0", description = "Folder description")
	private String folder;

	@Parameters(index = "1", arity = "1...*", description = "Sources")
	private String [] sources;

	@Parameters(index = "2", arity = "0", description = "Destination")
	private String destination;

```

Turns out the help will not show `destination` in usage but is listing the description anyway:
```
Usage: <main class> [-hV] <folder> <sources>...
Test command
      <folder>       Folder description
      <sources>...   Sources
                     Destination
  -h, --help         Show this help message and exit.
  -V, --version      Print version information and exit.

```
Could 0 arity parameters be displayed in the usage as well ?

**Comment by remkop** [comment]
I think we’re on the wrong path here.

I understand what you’re trying to do, but positional parameters with arity zero doesn’t really make sense generally. Also, having a special usage help message format for a parameter whose value is actually captured in the previous parameter is not something I want to support. :-)

If you really want to keep that ordering, I can see two solutions. 

* Use an `@Option` for destination. Perhaps make it a required option. Options don’t need to precede positional parameters, so `<cmd> folder src1 src2 src3 --destination dest` would be valid input. 
* Make `source` a single String parameter that accepts a comma-separated list of sources. You’ll have to split this comma-separated list in the application.

**Comment by 0rtis** [comment]
Agreed, 0 arity param sounds weird. But I found it strange that even thought `destination` is skipped in the usage, its description "Destination" shows up on line 5.

I think I will settle for a unique unbounded parameter `paths` from which I will take the last entry as the destination.

**Comment by remkop** [comment]
Thanks for raising this topic. I’ve started to think it may be worth supporting some `index = last` syntax in the future. That would allow something like:

```
@Parameters(index = “0..$-1”)
String[] sources;

@Parameters(index = “$”)
String destination;
```

The parsing logic for this is not straightforward though so this will be something for a future release.

**Comment by remkop** [comment]
One idea is to use negative indexes as meaning "from the end", like Groovy ranges:
http://mrhaki.blogspot.jp/2009/03/use-negative-index-in-groovy-lists-to.html
More examples: http://grails.asia/groovy-substring

So the above example would become:
```
@Parameters(index = “0..-2”) // all args except the last one
String[] sources;

@Parameters(index = “-1”) // the last argument
String destination;
```

We should consider also supporting exclusive ranges. Groovy uses the `<` character for this. For example: `0..<3` would be equivalent to `0..2` (a range containing elements `0`, `1` and `2`).

Exclusive ranges look a bit more natural when specifying "all args except the last":
```
@Parameters(index = “0..<-1”) // all args except the last one
String[] sources;
```

**Comment by 0rtis** [comment]
Python use this type of indexing as well so it should be natural to use for most people. I like this :+1:

**Comment by remkop** [comment]
While this is a nice idea, it turns out this is actually non-trivial to implement.
I don't see myself working on this in the near future.
Closing this ticket.
