### ISSUE TITLE
Subcommands with hyphen not working with autocompletion

### ISSUE THREAD

**Issue by Fadelis** [remkop/picocli#371]
When generating autocompletion script, subcommands with hyphen are stripped of it and are no longer matched for autocompletion.

As discussed in #178 , contained example can be found in [comment](https://github.com/remkop/picocli/issues/178#issuecomment-384400719).

**Comment by remkop** [comment]
This is now fixed in master. Please verify if you have the chance. 
Thanks for the bug report!
