### ISSUE TITLE
arity of PositionalParamSpec 

### ISSUE THREAD

**Issue by katoquro** [remkop/picocli#373]
Hello, 

I'm trying picocli instead of groovy CliBuilder because of nice subcommands feature ☺️

I have issue with help, i.e. i don't know how to say that there should be only one required value at the end of args. Like `$ tool ./my_file.txt`

I've used this configuration and help says that `FILE` is array
```groovy
static void main(String[] args) {
        CommandSpec cmdSpec = CommandSpec.create()
                .mixinStandardHelpOptions(true)
                .name('tool')
                .version('0.0.0')
                .addPositional(
                PositionalParamSpec.builder()
                        .paramLabel('FILE')
                        .arity('1')
                        .type(String)
                        .description('Path to file')
                        .build())

        CommandLine cmdLine = new CommandLine(cmdSpec)
        ParseResult pr = cmdLine.parseArgs(['-h'] as String[])

        CommandLine.printHelpIfRequested(pr)
    }
```

```
Usage: tool [-hV] FILE...
      FILE...     Path to file
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
```

expected 

```
Usage: tool [-hV] FILE
      FILE     Path to file
...
```

Is such behaviour an issue or I misconfigured my picocli

p.s. 

And in would be nice to have next for `.arity('0..1')`

```
Usage: tool [-hV] [FILE]
      FILE     Path to file
...
```

Thanx

**Comment by remkop** [comment]
The default index range is `“0..*”`, so multiple arguments can be captured by this `PositionalParamSpec`. 

Try setting `builder.index(“0”)` to match only the argument at the first position.

**Comment by katoquro** [comment]
@remkop thank you for the quick reply. 

Thank you ! That is what i was looking for. I guess I didn't catch relation between arity and index for PositionalParamSpec

**Comment by remkop** [comment]
You’re very welcome! Enjoy using picocli!
I’ll close this one but feel free to create more tickets.
