### ISSUE TITLE
@Parameters arity exception could be more verbose

### ISSUE THREAD

**Issue by gpettey** [remkop/picocli#375]
Deleted incorrect bug source assumptions from original issue.

When `@Parameters` exist, and initial parameters (index = 0 or 1 or so) are removed during coding, runtime throws an exception 

Exception in thread "main" picocli.CommandLine$ParameterIndexGapException: Missing field annotated with `@Parameter`(index=0). Nearest field 'file' has index=2
        at picocli.CommandLine.validatePositionalParameters(CommandLine.java:2066)

Maybe the message could, instead of (or in addition to) saying "missing field", say "not a valid index". I read the "missing" message as a missing command line parameter and thought it was saying "field X annotated with Y was not supplied to the Command" or something and being overly verbose about just where in the code that option/parameter being asked for was.

Regardless, the message should use the correct annotation `@Parameters`, not `@Parameter`.

**Comment by remkop** [comment]
Thanks for pointing that out! I’ll improve the error message.

**Comment by remkop** [comment]
Do you think you’ll be able to provide a pull request for this?

**Comment by remkop** [comment]
I improved the error message. It now looks like this:
```
throw new ParameterIndexGapException(
    "Command definition should have a positional parameter with index="
     + min +
    ". Nearest positional parameter '"
     + positional.paramLabel() + "' has index=" + index.min);
```
Thanks for the suggestion!
