### ISSUE TITLE
Map option problem when value contains '=' separator (was: How to quote / escape option values)

### ISSUE THREAD

**Issue by MarkusKramer** [remkop/picocli#378]
I would like to pass a map of options into my application like:
`-p AppOptions="-Dspring.profiles.active=test -Dspring.mail.host=smtp.mailtrap.io"`

picocli seems to get confused by the equals sign in the value. My class:

```
public class MyCommand implements Callable<Object> {
    @Option(names = {"-p", "--parameter"})
    @Getter
    Map<String, String> parameters;

    public static void main(String[] args) throws Exception {
        Object result = CommandLine.call(new MyCommand(), System.out, args);
        System.exit(result != null ? 0 : 1);
    }

    @Override
    public Object call() throws Exception {
        System.out.println(this.parameters.get("AppOptions"));
        return new Object();
    }
}
```

I expect it to output the entire value, but I'm only getting `-Dspring.profiles.active`. How can I escape the value correctly?

I don't want to make AppOptions part of my CLI directly, because I don't control the content and users should be able to pass in an arbitary set of parameters.

**Comment by remkop** [comment]
_Note to self (Markus, please ignore): a test to reproduce the issue:_

```
@Test
public void testMapValuesContainingSeparator() {
    class MyCommand {
        @Option(names = {"-p", "--parameter"})
        Map<String, String> parameters;
    }
    String[] args = new String[] {"-p", "AppOptions=\"-Dspring.profiles.active=test -Dspring.mail.host=smtp.mailtrap.io\""};
    MyCommand c = CommandLine.populateCommand(new MyCommand(), args);
    assertEquals("\"-Dspring.profiles.active=test -Dspring.mail.host=smtp.mailtrap.io\"", c.parameters.get("AppOptions"));

    args = new String[] {"-p", "\"AppOptions=-Dspring.profiles.active=test -Dspring.mail.host=smtp.mailtrap.io\""};
    c = CommandLine.populateCommand(new MyCommand(), args);
    assertEquals("-Dspring.profiles.active=test -Dspring.mail.host=smtp.mailtrap.io", c.parameters.get("AppOptions"));
}
```

**Comment by MarkusKramer** [comment]
Awesome! Thanks for the very fast response. Looking forward to the fix.

**Comment by remkop** [comment]
[Picocli 3.0.1](https://github.com/remkop/picocli/releases/tag/v3.0.1) is released with the fix for this bug. Thanks again for the bug report!

**Comment by remkop** [comment]
Can you verify that this solves the problem?

**Comment by MarkusKramer** [comment]
Yes, it's fixed. Thanks again!

Btw, I've noticed that it doesn't work as expected if I use
```
@Option(names = {"-p", "--parameter"}, split = ",")
```
with arguments `-p AppOptions="-Dspring.profiles.active=foo,bar -Dspring.mail.host=smtp.mailtrap.io",OtherOptions=""`
But it's not a big problem problem for me.

**Comment by remkop** [comment]
Would you mind creating a new ticket for that to discuss further?

**Comment by MarkusKramer** [comment]
Sure, I've created #379
