### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [remkop/picocli#383]
Hello,

I am a graphic designer. I like to contribute by designing a logo for open source software. Do you want me to design a logo for picocli?

you can see many logo design examples on my github profile.

https://github.com/reallinfo

**Comment by remkop** [comment]
That would be awesome, thank you very much!
Let me know how I can return the favor!

**Comment by reallinfo** [comment]
Thank you @remkop  I just want to contribute. I designed a few logo. How is these?

![picocli](https://user-images.githubusercontent.com/36298335/40877512-bdd2766e-668a-11e8-912c-e707dbb913a5.jpg)

**Comment by remkop** [comment]
@reallinfo  I will be sure to mention you when using the logo. Should I link to your github account or do you have another portfolio page I should link to?

About the proposed icons, I like the strength idea (I believe people like the many features of the library) but the first impression of the bottom images is that it's an elephant. Could I ask you to have another go?

**Comment by reallinfo** [comment]
![picocli2](https://user-images.githubusercontent.com/36298335/40887551-3c56157c-6753-11e8-91c9-e9451183af3c.jpg)

How is these? Also, If there is your an idea, I can design it.

**Comment by remkop** [comment]
I actually liked the strength metaphor. (Picocli: the mighty tiny command line interface).
How about a weight-lifting idea:  the `>_` icon lifting a barbel or something?

**Comment by reallinfo** [comment]
WOW good idea. How is these? logo designs must be minimalist. for this reason I did not make it very detailed. Being simple and minimalist is always good.

![1](https://user-images.githubusercontent.com/36298335/40933257-94d4e4ee-6839-11e8-870c-2f227cd18107.jpg)

**Comment by remkop** [comment]
YES! That’s what I had in mind. (And I completely agree that we’re aiming for a minimalistic logo with little detail.)

Can we try a variation with spindly thin arms? Also, I actually really liked the orange of the first proposal. Can we try that, perhaps with a variation where the barbell is gray? (That might make the barbell look like a headphone, but I’d like to see what it looks like.)

**Comment by reallinfo** [comment]
Haha :D I admire your imagination. :D Elephant- headphone. It really looks like.

I customized the barbell. Which is better? 1 or 2?

![1](https://user-images.githubusercontent.com/36298335/40944768-a4f3cdc0-685e-11e8-82ac-d39b01901196.jpg)

**Comment by remkop** [comment]
I like the barbell shape and color of number 6 best I think.
Can we try having really thin stick-like arms? 

Also, what do you think of a single handed barbell press idea like this: https://www.123rf.com/photo_65656305_stock-vector-weightlifter-cartoon-man-lifting-a-heavy-weight-by-one-hand.html

**Comment by reallinfo** [comment]
I tried to do 

![pp](https://user-images.githubusercontent.com/36298335/40981082-c315db16-68e2-11e8-90a9-5e92237b0504.jpg)

**Comment by remkop** [comment]
This is great. Thank you so much! I think we are pretty much there.

Can I ask for a final version of these last two logos, each with the word "picocli" next to them (like in your second proposal)? If possible also one version with a color gradient and one version where the word "picocli" is in black (like in the left side of your second proposal).

This is really really awesome! I am about to publish some articles on DZone and Java Code Geeks and I will use these logos in these articles and on the picocli site going forward. 

Do you have a portfolio page that I can link to so people can see more of your work?

**Comment by reallinfo** [comment]
You're welcome. I've added all the variations to make it perfect.

Please tell me the numbers of the variations you want. I wil send a pr. Also, Do you want me to update the readme file? 

I do not have a portfolio but You can add my github profile. Thanks!

![picocli](https://user-images.githubusercontent.com/36298335/41046907-fe35635c-69b3-11e8-90d3-21ce2daec40a.jpg)

**Comment by remkop** [comment]
I like Font variation 2 and Gradient single hand 1. For the Font variation, can you add a version where the word “picocli” uses the same gradient colors as the logo? (So there’s 3 image files: with text  in black, in gradient and without text.)

In the PR please put these in `docs/images`. Please go ahead and update the readme.

**Comment by reallinfo** [comment]
I sent a pr. Please check it. https://github.com/remkop/picocli/pull/385

Also, I will send editable files very soon.

**Comment by remkop** [comment]
Can I ask for one more version without the empty arm?

**Comment by reallinfo** [comment]
Sure, here you are.

![p](https://user-images.githubusercontent.com/36298335/41095355-db041292-6a59-11e8-81ee-705fe392d744.jpg)

**Comment by remkop** [comment]
Thank you! This looks simpler and better I think.
Do you want to do another PR?

**Comment by remkop** [comment]
I'm really excited about the logos! They look great!

**Comment by reallinfo** [comment]
Sure,

https://github.com/remkop/picocli/pull/386

If you need logo for another project, you can write me.

**Comment by remkop** [comment]
I updated the readme, user manual (asciidoc and html) and release notes for the new logo, and closing this ticket. Thank you, @reallinfo !

**Comment by remkop** [comment]
Excellent, thank you! Out of curiosity, what is the name of the font you used?

**Comment by reallinfo** [comment]
https://www.dafont.com/typographica.font

**Comment by remkop** [comment]
Nice! I also like your steemit page:
https://steemit.com/utopian-io/@realinfo/picocli-logo-design
