### ISSUE TITLE
Provide interface for registering multiple converters from a collection

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [remkop/picocli#384]
The signature of method to register a converter has a formal type parameter, which works well when registering individual converters:

`public <K> CommandLine registerConverter(Class<K> cls, ITypeConverter<K> converter);`

But if you have a collection of converters of different types and want to register them all it doesn't work:
```
val customConverters: MutableMap<Class<*>, CommandLine.ITypeConverter<*>>
customConverters.forEach { t, u -> cli.registerConverter(t, u) } // Does not work
```

The hack I'm using is to use reflection to get at the underlying registry and then add the converters:
```
val registry: MutableMap<Class<*>, CommandLine.ITypeConverter<*>> = 
Reflect.on(Reflect.on(cli).get<Any>("interpreter")).get("converterRegistry")

registry.putAll(customConverters)
```
Kindly consider exposing the registry via a getter method or provide an API method to work with multiple converters.

**Comment by Kshitiz-Sharma** [comment]
> Quick question: is there not some way to cast t to Class<K> and u to ITypeConverter<K>?

I'm afraid not. This is due to Java's type erasure of Generic types.

Yes, I know reflection is fragile and I'll have to adjust my code if the internal structure of the library changes in a future release. Which is why I raised this request to have it as part of public API, _if possible_.

**Comment by remkop** [comment]
OK, I see now that we cannot cast to a generic `Class<K>`.
However, you should be able to cast a `Class<*>` to a `Class<Any>` (and same for the type converter), so this should work:
```
val customConverters: MutableMap<Class<*>, CommandLine.ITypeConverter<*>>
customConverters.forEach { t, u -> cli.registerConverter((Class<Any>) t, (ITypeConverter<Any>) u) }
```

**Comment by Kshitiz-Sharma** [comment]
Ah, yes it does. Excuse my ignorance.

**Comment by remkop** [comment]
No worries, glad to hear the problem is solved!
