### ISSUE TITLE
Allow omitting of quotation marks for arguments with arity of 1

### ISSUE THREAD

**Issue by Mikusch** [remkop/picocli#394]
Hello,
quotation marks are required for arguments with an arity of 1 if the argument itself contains a space. I personally think it should behave differently.

Assuming both the `name `parameter and the `--nickname` option have an arity of 1,
`adduser "Niko Bellic" --nickname "This is a test"`
could also be written as
`adduser Niko Bellic --nickname This is a test`

Right now, the second version would result in a `positional parameter at index 0..* (name) should be specified only once` error message.

Would this be possible to implement?

Kind regards,
Mikusch

**Comment by remkop** [comment]
I’m not sure this is possible. Consider the case where an option expects two parameters (arity=2) and both parameter values contain spaces. The quotes are needed to be unambiguous:

```
<cmd> -option “1st param” “2nd long param”
```

**Comment by remkop** [comment]
I believe that without quotes there are many cases where input would be ambiguous. Consider this case:

```
class App {
    @Option(names = "--name") // arity = 1
    String name;

    @Parameters
    String[] address;
}
```
Given this input:
```
<cmd> --name Niko Bellic 123rd Street, New York
```
Without quotes, the input is ambiguous.

This is why quoting is standard in all command line shells when specifying values with embedded spaces. (It's not just picocli.) 

Always requiring quotes for embedded spaces follows the "principle of least surprise". It could be made to work for some specific cases but then users are left to wonder why input without quotes works in some cases but not in others...

**Comment by Mikusch** [comment]
I see, but wouldn't it be possible to make this a boolean option when building an argument?

**Comment by remkop** [comment]
To be honest, I can't see why this is desirable. This does not look like a good feature to have. At best it will work _sometimes_, but not for cases like
```
<cmd> --name Niko Bellic 123rd Street, New York
```

I think sticking to standards here and require quotes if an argument contains embedded whitespace is the correct thing to do.
