### ISSUE TITLE
Autocomplete support for OSX

### ISSUE THREAD

**Issue by cornelcreanga** [remkop/picocli#396]
Hi,
Currently the autocomplete feature does not work on OSX, at least not on Darwin (bash 3.2.57). Any plan to add support for it?

If not I might try to do it by myself.

Picocli version: 3.0.1
Sample code (if you need it): https://github.com/cornelcreanga/various/tree/master/src/main/java/commandline

Thanks.

**Comment by remkop** [comment]
I wasn’t aware there was a problem with autocompletion on OSX, thanks for letting me know! Can you provide more details on what isn’t working as expected?

It would be great if you could provide a pull request!

**Comment by cornelcreanga** [comment]
The bash version (3) used by Apple is extremely old (licensing issues) and does not support associative arrays. I see two options:
a)manually upgrade the bash version on OSX (or install zsh), check if it works and add a note into the Picocli documentation
b)change the auto completion script to work with bash 3 (not sure how long it will take)
I'll be back next week with a pull request related to a) or b) - unless you have a third suggestion.

**Comment by remkop** [comment]
I don’t see other options than what you mentioned. A pull request would be great! Take your time.

**Comment by remkop** [comment]
@cornelcreanga Did you have any luck with this?

**Comment by remkop** [comment]
@cornelcreanga I just pushed a change to master that eliminates the use of associative arrays from the generated autocompletion scripts. That should allow the completion scripts to work on OSX as well.
Can you verify?

**Comment by remkop** [comment]
@cornelcreanga , All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including this fix. Enjoy!
