### ISSUE TITLE
Make subcommands required in @Command

### ISSUE THREAD

**Issue by lao974** [remkop/picocli#403]
My main app has several subcommands, and has no valid invocation without any subcommand specified. Using "commandLine.parseWithHandler(new RunAll(), args)" kind of parsing if I invoke myapp without any additional arguments it passes cli validation and I can see no declarative way of telling picocli @Command that subcommands field is required.

To be more precise, say I have an app "myapp", having 2 subcommands "sub1" and "sub2".
Invoking "myapp" alone is not valid and should print usage. Only "myapp sub1" or "myapp sub2" or "myapp help" is valid.

**Comment by remkop** [comment]
Instead of `RunAll`, you could use `RunLast` so only the most specific subcommand is executed. 

Then in the `run` method of the top-level command you could print an error message and the usage help message.

**Comment by lao974** [comment]
I still have to print usage manually in this case, while usage printing is automatic in case any other required argument is missing.

**Comment by remkop** [comment]
Yes, I believe that should meet your requirements. Printing usage help is a one-liner:

```
CommandLine.usage(this, System.err);
```

**Comment by lao974** [comment]
Sure, thats fine, I thought it is more complicated :)
Thanks for the quick response, and thanks for picocli in general!
