### ISSUE TITLE
Long option parsing fail

### ISSUE THREAD

**Issue by 0rtis** [remkop/picocli#407]
Parsing a long option `file` fail:

```
@Command(description = "Simple test command", name = "test", mixinStandardHelpOptions = true, showDefaultValues = true)
public class TestCommand implements Callable<Void>
{

	@Option(names = { "-a" }, description = "Option a")
	private String a = null;

	@Option(names = { "-b" }, description = "Option b")
	private String b = "B";

	@Option(names = { "--file" }, description = "File path")
	private String file = "default file";

	@Override
	public Void call() throws Exception
	{

		System.out.println("a -> " + this.a);
		System.out.println("b -> " + this.b);
		System.out.println("file -> " + this.file);

		return null;

	}

	public static void main(String[] args)
	{
		 args = new String[] { "-amya", "-bmyb", "--file myfile" };// fails
		//args = new String[] { "-amya", "-bmyb", "--filemyfile" };// fails as well
		//args = new String[] { "-amya", "-bmyb", "--file=myfile" };// works
		CommandLine.call(new TestCommand(), System.err, args);
	}

}
```

Using `=` separator works though

**Comment by remkop** [comment]
The above test program results in `Unmatched argument [--file myfile]`, because it passes the string `""--file myfile"` as a single argument to the parser.

(I did not realize until I ran the program with `-Dpicocli.trace=DEBUG` and saw this:
```
[picocli DEBUG] Processing argument '--file myfile'. Remainder=[]
[picocli DEBUG] '--file myfile' cannot be separated into <option>=<option-parameter>
```

If you pass `--file` and `myfile` as separate arguments, things work as expected:

```
String[] args = new String[] { "-amya", "-bmyb", "--file", "myfile" };// works
```
Prints:
```
a -> mya
b -> myb
file -> myfile
```

**Comment by remkop** [comment]
I'll close this issue. Feel free to reopen if I missed something.

**Comment by RobertZenz** [comment]
Could a possible compromise be that it is split based on the first part of it?

    --file myfile with spaces
          ^ Split happens there

So if picocli encounters a single argument with a leading long (or short) option (a valid one, obviously) should it treat the rest of the argument as value?

**Comment by remkop** [comment]
@RobertZenz, the application will only receive arguments with embedded spaces if the user quoted part of the command line to ensure that the quoted part is treated as a single parameter.

**Comment by remkop** [comment]
Be aware there is the use case where the user specifies command line parameters where some part needs to be passed on to a second application. For example:

```
rsync -v -e "ssh -p2222" /home/localuser/testfile.txt remoteuser@X.X.X.X:~/transfer
```

In the above example, `"ssh -p2222"` has embedded quotes but the `rsync` command should not try to split it up and process it.

I am fairly sure that the current picocli behaviour is correct.

**Comment by RobertZenz** [comment]
> In the above example, `"ssh -p2222"` has embedded spaces but the `rsync` command should not try to split it up and process the individual parts.

I see what you mean, though I have to point out that this would be used as is with my suggestion because it does not start with a valid option. But I understand where you are coming from.

**Comment by 0rtis** [comment]
So the shell will take care of separating `--file` and `myfile` and picocli will sperate `--file=myfile` on the `=` sign. Alright. But what happens on `-amya` and `-bmyb` ? Obviously, the separation is done by picocli. If so, why does it have different behavior between `--filemyfile` which fails and `-amya` which succeed ?

**Comment by remkop** [comment]
@0rtis  The POSIX standard allows for [clustered short options](http://picocli.info/#_posix_clustered_short_options), so if you have options `-v`, `-x` (both boolean flags) and `-f` (that takes a file argument), the below user input is equivalent:
```
-v -x -f someFile
-vx -f=someFile
-vxfsomeFile
```
(see also [Utility Conventions](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02).)

POSIX options are a single character and are preceded with a single dash (`-`).

Long options may have more than one character and are preceded with two dashes. These are a [GNU extension](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html#Command_002dLine-Interfaces). Long options may be separated from their option parameter value with whitespace, or they may be attached to their option parameter with the `=` separator.

**Comment by 0rtis** [comment]
Thanks for for the explanation. Is much clearer now.
So how would a two char short option be parsed ?

For example:

```
@Command(description = "Simple test command", name = "test", mixinStandardHelpOptions = true, showDefaultValues = true)
public class TestCommand implements Callable<Void>
{

	@Option(names = { "-a" }, description = "Option a")
	private String a = null;

	@Option(names = { "-b" }, description = "Option b")
	private String b = "B";

	@Option(names = { "-ff" }, description = "File path")
	private String file = "default file";

	@Override
	public Void call() throws Exception
	{

		System.out.println("a -> " + this.a);
		System.out.println("b -> " + this.b);
		System.out.println("file -> " + this.file);

		return null;

	}

	public static void main(String [] args)
	{
		args = new String[] { "-amya", "-bmyb", "-ffmyfile" };// fails
		// args = new String[] { "-amya", "-bmyb", "-ff myfile" };// fails as well
		// args = new String[] { "-amya", "-bmyb", "-ff=myfile" };// works
		CommandLine.call(new TestCommand(), System.err, args);
	}

}
```
`-ffmyfile` -> fails
`-ff myfile` -> fails
`-ff=myfile` -> works

**Comment by remkop** [comment]
Only short options can be clustered. The definition of a "short option" is one character, prefixed with a single dash. So `-ff` is not a short option because it has two characters. 

Everything that is not a short option (and cannot be clustered) is treated like a long option (so needs a space or a `=` separator).

**Comment by 0rtis** [comment]
Thanks for the all the details

**Comment by remkop** [comment]
You're welcome! :-)
