### ISSUE TITLE
Using ResourceBundle

### ISSUE THREAD

**Issue by amsitlab** [remkop/picocli#415]
Hay remkop, can I use ResourceBundle for option help message?

**Comment by remkop** [comment]
Hi @amsitlab, I have been planning to add this for a long time (https://github.com/remkop/picocli/issues/22) but never got around to it.

Do you think you'll be able to submit a patch or pull request for this?

**Comment by remkop** [comment]
Fixed in master.
This feature will be available from the upcoming 3.6 release.

**Comment by amsitlab** [comment]
Great job.
Btw, is available api to overriding exception message from `picocli.CommandLine.Parameter#getMessage()` with ResourceBundle?
Likes message `Unknown option: -blah`.

**Comment by amsitlab** [comment]
Sorry `picocli.CommandLine.ParameterException#getMessage()` I mean.

**Comment by remkop** [comment]
@amsitlab No, it is not yet possible to localize picocli error messages. 
There is an outstanding ticket #485 that I haven't got around to.
Will you be able to provide a pull request for this?
