### ISSUE TITLE
Support mixin parent in subcommand

### ISSUE THREAD

**Issue by gpettey** [remkop/picocli#421]
```
@Mixin
@ParentCommand
MyCommand myCommand;
```
results in a StackOverflowException, as the parent loads the subcommand mixes in the parent loads the subcommand mixes in the parent ad inifitum. I'd like to be able to have some subcommands inherit base options from their parent, e.g. `--verbose` and various base directory locations, and have those parent options be included in usage output on subcommands. Is inheriting `@Option`s from `@ParentCommand` a viable feature request, or should I be creating a separate `@Mixin` and including it in every command?

**Comment by remkop** [comment]
The field annotated with `@ParentCommand` will get the command line options for the parent command, while the field annotated with `@Mixin` will get options for _this_ command. For example:

```
class Parent {
    @Option(names = "--dir") 
    protected File dir;
}

@Command(name = "subcmd")
class SubCmd extends Parent {
}
```
The user may specify a different `--dir` value for the parent command and the subcommand:
```
<cmd> --dir /parent/dir subcmd --dir /sub/dir
```
You application would not be able to get both values if you annotate a single field with both `@Mixin` and `@ParentCommand`. Should the `dir` option of this field get the value `/parent/dir` or the value `/sub/dir`?

Subcommands can inherit `@Option`s from the parent command by subclassing (as in the example above), or by creating a separate `@Mixin` and including it in every command like you said.

**Comment by gpettey** [comment]
I'm trying to have `--dir` be the same instance in the parent and every subcommand without duplicating code. I can access ParentCommand's fields, and they're set appropriately, but then the options have to be specified before the subcommand name and they aren't shown when `com sub --help` is called. I can mangle the help output to pull in the parent options well enough, but unifying `--dir` and `--verbose` in command and subcommands is the issue. Can `@Mixin` be forced to use the same instance in every command somehow?
