### ISSUE TITLE
Exit on help, version or invalid arguments

### ISSUE THREAD

**Issue by gerardbosch** [remkop/picocli#424]
Typically, when you run a command line application using the help or version flag (`--help`, `--version`) you expect that the program exits itself after printing usage information.

Picocli has a built-in feature to alleviate the programmer of writing the help and version logic, but in this case Picocli doesn't exit application —invoking for example system exit with a status code of success— but let the application to continue running.

When using the convenience `CommandLine.run()`, `CommandLine.call()` I would expect the described behavior to happen. Currently, usage information is printed but application doesn't exit and continues running with no simple way to configure it to work as described (related discussion:  #397 ).

I propose to print usage and exit to be the default behavior. I don't know if any other use case could need the application to continue but in that case I would propose an annotation based configuration to override the defaults like the one proposed in ticket #397 .

Kind regards!

**Comment by remkop** [comment]
Thanks for raising this. I agree this can be improved.

I like your idea for annotation attributes, something like:

```java
@Command(name = "cmd",
        exitCodeOnUsageHelp = 0, 
        exitCodeOnVersionHelp = 0, 
        exitCodeOnInvalidInput = 64)
class MyCommand { ... }
```

The javadoc for these attributes should clearly say that these settings are only used when the input is processed with one of the convenience methods: `run`, `call` or `parseWithHandlers`, and ignored otherwise (that is, ignored when `parse`, `parseArgs` or `populateCommand` are used to process arguments).

Picocli should _only_ call `System.exit` if these exitCode values are explicitly set.

Do you think you'll be able to provide a pull request for this?

**Comment by gerardbosch** [comment]
As I have been trying a little more in depth Picocli for my Spring Command Line/Application Runner, I have realized that **I can achieve the behavior I was looking for**, simply by delegating the start of Spring application inside the `run()` or `call()` method of the `Runnable/Callable` class that contains the Picocli annotations (aka _annotated object_) instead of starting it in the `main` method.

That is because Picocli will never call `run()/call()` methods when `--help` or `--version` are present or when invalid arguments are provided, and application simply finishes and exits in these cases. The **only objection** here is that the exit code on invalid arguments is equally 0, which denotes success (but it is not).

So at this point, probably this issue stops making sense, at least partially. But maybe this way of working could be pointed in the Github and website documentation.

I put here an example of how I start my Spring application, handling command line arguments with Picocli. In my case I made the Main class itself the one holding CLI annotations:

```java
@SpringBootApplication
@Command(description = "Application description",
        versionProvider = MyVersionProvider.class,
        mixinStandardHelpOptions = true)
public class ValidatorApplication implements Runnable {

    @Parameters(paramLabel = "FILE", description = "Primary XML file to validate.")
    public static String primaryFile;

    @Option(names = {"-p", "--previous-year"}, paramLabel = "PREV_YEAR_FILE",
            description = "Previous year XML file. Some specific validations require previous year file. If not " +
                    "provided, these validations are not performed.")
    public static String prevYearFile;


    public static void main(String[] args) {
        CommandLine.run(new ValidatorApplication(), args);
    }

    @Override
    public void run() {
        // Start Spring application
        SpringApplication.run(ValidatorApplication.class);
    }
```

**Note** that command line parameters and options are `public static`. This way I can easily access it from any class in the application simply doing e.g. `ValidatorApplication.primaryFile`.

**Comment by remkop** [comment]
An initial version just landed in master. Please check it out if you have a chance.

**Comment by remkop** [comment]
@gerardbosch 

picocli-4.0-alpha-3 has been released with improved [exit code support](https://picocli.info/#execute) and [exception handling](https://picocli.info/apidocs/picocli/CommandLine.IExecutionExceptionHandler.html).

This is the last alpha! Please take a look and provide feedback if you have a chance.

**Comment by gerardbosch** [comment]
Thanks @remkop , I cannot check it out at this moment, but I keep it present :)
