### ISSUE TITLE
Specialized Enum classes not handled well

### ISSUE THREAD

**Issue by thargor** [remkop/picocli#426]
picocli does not handle specialized enums correctly. The reason for this is that specialized enum classes do not return isEnum() -> true.
For more details on this see here or JRE sources.
https://bugs.openjdk.java.net/browse/JDK-6708424

Since I need this I will provide a pull request for specialized enum soon. Stay tuned.

Example code of a specialized enum:

```java
public enum SpecializedEnum{
  A(null),
  B(new Object());
  SpecializedEnum(Object o){
    this.o = o;
  }
  public final Object o;
}
```

**Comment by thargor** [comment]
Well... that was a false alarm, which was triggered by another bug in my application.

The declared type of the field is actually the non specialized enum - so this works nonetheless.

**Comment by remkop** [comment]
Glad to hear that!
