### ISSUE TITLE
nested subcommands declared programatically not listed in usage

### ISSUE THREAD

**Issue by fish-4-fun** [remkop/picocli#427]
When declaring subcommands programatically, the subcommands are not listed when printing the usage. This goes for subcommands of subcommands (nested). When I declare them using annotations, everything works as expected. 

I have some requirements where I need to pass some specific objects to each command (via parameterized constructor), therefore I cannot use the annotations.

I feel like I am missing the approach here...as I am trying to avoid global objects. I could probably come up with a DI (using Dagger2) to inject the correct instance of the objects I need, but its getting pretty convoluted. 

The usage works fine if I call it directly, but if pass in, say a bad parameter using the following 
```java
List<Object> results = commandLine.parseWithHandlers(
       new CommandLine.RunAll().useOut(System.out).useAnsi(CommandLine.Help.Ansi.ON), 
       CommandLine.defaultExceptionHandler(), new String[]{"project"}
);
```

The automatic usage will only print subcommands of subcommand that are declared via annotation...

**Comment by remkop** [comment]
Away from pc now, but I thought there was a unit test for that. The intention is that the usage help prints all subcommands, regardless of whether they were added programmatically or declaratively. 

Can you provide an example that demonstrates the issue?

**Comment by remkop** [comment]
By the way, the default exception handler will print the usage help _for the subcommand where parsing failed_. Not for the top-level command.

**Comment by fish-4-fun** [comment]
Awesome lib BTW...well thought out and designed...

Simple example...my simple commands take a PrintStream as a constructor param...
``` java
 CommandLine commandLine = new CommandLine(new CLICommand(System.out))
                .addSubcommand("project", new CommandLine(new ProjectCommand(System.out)).addSubcommand("list", new ProjectListCommand(System.out)) )
                .addSubcommand("test", new TestCommand());
```
and then call...
```java
List<Object> results = commandLine.parseWithHandlers(new CommandLine.RunAll().useOut(System.out).useAnsi(CommandLine.Help.Ansi.ON),CommandLine.defaultExceptionHandler(), new String[]{"project"} );
```
so in the above, I am essentially just faking someone running the command with the parameter of ```project``` which is a subcommand, and ```project``` has a subcommand called ```list```

So since no other arguments are passed, it does err, which is expected and prints the usage...

```
Usage: project [-h]
project command
  -h, --help   Help
```

above, it doesn't print the subcommands (```list```). If I provide via annotation (can have a custom constructor i don't think) it works as expected.

**Comment by fish-4-fun** [comment]
And for the record, I am implementing a console / socket solution, hence the reason to pass the in the PrintStream, as well, I will have other dependencies in the commands, as well as a custom error handler but for simplicity I've just used the default.

**Comment by remkop** [comment]
Looks like I need a bit more information to be able to reproduce the issue.
I don't understand this sentence in your comment:

> So since no other arguments are passed, it does err, which is expected and prints the usage...

Why does the `project` subcommand have an error if no other arguments are passed? Does it have any required options or positional parameters? (I did not see any "missing required option..." error message...)

Here is my test code:
```java
public class Issue427 {

    @Command
    static class CLICommand implements Runnable {
        public CLICommand(OutputStream out) {}
        public void run() {
            System.out.println("running cli");
        }
    }

    @Command
    static class ProjectCommand implements Runnable {
        public ProjectCommand(OutputStream out) {}
        public void run() {
            System.out.println("running project");
        }
    }

    @Command
    static class ProjectListCommand implements Runnable {
        public ProjectListCommand(OutputStream out) {}
        public void run() {
            System.out.println("running list");
        }
    }

    @Command
    static class TestCommand implements Runnable {
        public void run() {
            System.out.println("running test");
        }
    }

    public static void main(String[] args) {
        CommandLine commandLine = new CommandLine(new CLICommand(System.out))
                .addSubcommand("project", new CommandLine(new ProjectCommand(System.out))
                        .addSubcommand("list", new ProjectListCommand(System.out)))
                .addSubcommand("test", new TestCommand());

        List<Object> results = commandLine.parseWithHandlers(
                new CommandLine.RunAll()
                        .useOut(System.out)
                        .useAnsi(CommandLine.Help.Ansi.ON),
                CommandLine.defaultExceptionHandler(),
                new String[]{"project"} );
    }
}
```

When I execute this, it simply executes the `run` method of the top-level command and the `project` subcommand:

```
running cli
running project
```

**Comment by fish-4-fun** [comment]
Away from the code, I'll look and post more in the AM.

Sorry, err is the wrong word, but because no other commands are referenced,
ie, list ; it prints out the usage command for the subcommand. I don't
know, but I assume this is the desired behaviour? It is the behaviour I am
seeking.

What i am trying to achieve is to a have commands that have subcommands,
with no default action, but a requirement for the caller to pass in the
subcommmand. In other words, if a command (parent) is called with no
arguments, it should be considered invaild and display the usage for that
sub command. I am pretty sure this is happening for me by default, but your
example seems to contradict that. I am pretty sure that what I just
explained happens when I do your example but using annotations to define
the subcommands but I can't be positive at the moment.

Also, if the parent command is CLI, as an example, and the subcommand is
run, I wouldn't want the parent command to do anything. Is this acheived by
swapping RunAll() for RunLast() ?

My commands all have 1 option, defined for help, not required...if that
helps. Not sure how helpful this is at the moment, but I'll edit this with
a more concrete example. Thanks!

**Comment by remkop** [comment]
Interesting. So you want to make it invalid for a command to be invoked without a subcommand.
This can be accomplished by throwing a `ParameterException` from the `run` method. The default exception handler will catch `ParameterException` and treat it as invalid input.

Here is my updated example:

```java
public class Issue427 {

    @Command(name = "cli", mixinStandardHelpOptions = true)
    static class CLICommand implements Runnable {
        public CLICommand(OutputStream out) {}
        public void run() {
            System.out.println("running cli");
        }
    }

    @Command(name = "project", mixinStandardHelpOptions = true, description = "manage projects")
    static class ProjectCommand implements Runnable {
        @Spec
        CommandLine.Model.CommandSpec spec; // injected by picocli

        public ProjectCommand(OutputStream out) {}
        public void run() {
            throw new CommandLine.ParameterException(spec.commandLine(),
                    "This command requires a subcommand");
        }
    }

    @Command(name = "list", mixinStandardHelpOptions = true,
            description = "shows a list of projects")
    static class ProjectListCommand implements Runnable {
        public ProjectListCommand(OutputStream out) {}
        public void run() {
            System.out.println("running list");
        }
    }

    @Command(name = "test", mixinStandardHelpOptions = true)
    static class TestCommand implements Runnable {
        public void run() {
            System.out.println("running test");
        }
    }

    public static void main(String[] args) {
        CommandLine commandLine = new CommandLine(new CLICommand(System.out))
                .addSubcommand("project", new CommandLine(new ProjectCommand(System.out))
                        .addSubcommand("list", new ProjectListCommand(System.out)))
                .addSubcommand("test", new TestCommand());

        List<Object> results = commandLine.parseWithHandlers(
                new CommandLine.RunAll()
                        .useOut(System.out)
                        .useAnsi(CommandLine.Help.Ansi.ON),
                CommandLine.defaultExceptionHandler(),
                new String[]{"project"} );
    }
}
```

When your run it, it gives the following output:
```
This command requires a subcommand
Usage: cli project [-hV] [COMMAND]
manage projects
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  list  shows a list of projects
```

I believes this does what you have in mind.

**Comment by remkop** [comment]
> Also, if the parent command is CLI, as an example, and the subcommand is
run, I wouldn't want the parent command to do anything. Is this acheived by
swapping RunAll() for RunLast() ?

Yes, that is correct. If you use `RunLast`, it will execute the most specific subcommand. This is the default behaviour and this is probably what you want.

As a side note, from the end-user point of view, it may be user-friendly if every command does something useful even without subcommand (if possible). For example, `git branch --list` shows a list of branches, but when invoked without any options, `git branch` will also show a list of branches.

**Comment by fish-4-fun** [comment]
Ok, so I copied your code and I noticed that the @spec annotation was not available, so silly me, I noticed I was on version 3.0.0 (my bad!).  And now....everything is working as expected. I think we can close this issue, but seeing your code leads me to think I need to really parse the documentation for more ways to customize.

Seeing that you can inject the @spec looks promising and convenient, so I have to ask if there are ways of getting other info.  So in my particular case, I am injecting the a PrintStream, so my commands can print out to the correct socket output stream when running. I can set the proper stream when using ```parseWithHandlers()``` for the automatic stuff, but when I need more custom control I need to either pass it in, OR return a Ansi.Text and have iterate through the results and print them to the socket. 

One particular thing I struggled with, was in my parent command (CLI) I wanted to override the help options (display string), so I augmented the string builder code in the docs...but...is there a way to have a command ```automatically``` print MY help string vs me having to check when help should be displayed and return my own string? Should I be implementing a HelpCommand? Just wondering if there is a canonical or endorsed way of doing this.

Anyways, thanks for the support. Super awesome library! Looking forward to making it a solution for us.

**Comment by remkop** [comment]
Have you specified `usageHelp = true` on the custom help option?
See https://picocli.info/#_printing_help_automatically

**Comment by remkop** [comment]
You may also be interested in the `@ParentCommand` annotation to allow subcommands to access global options defined on the parent command. 

Also check the “new and noteworthy” section of recent release notes: https://github.com/remkop/picocli/releases
