### ISSUE TITLE
Feature request: Different description based on display context

### ISSUE THREAD

**Issue by bbottema** [remkop/picocli#429]
Hey @remkop, awesome library! Such granular control, yet I still need more (or I'm doing it wrong) :)

Ok, so here's my case: I'm generating my CLI command tree using the programmatic API (thanks for including that btw), but I have two description types: an abbreviated one and an elaborate man-page kind of description.

I would like to use the abbreviated description for commands when listed as sub commands under _Commands:_, and the man-page-like description when --help is triggered directly on the command.

Is it possible to do this?

**Comment by bbottema** [comment]
Also, I could find any documentation on how multiple descriptions rather than a single one with newlines in it. 
I discovered I can replace newlines by having multiple descriptions in the description array, but in the _Command:_ listing then, only the first description from the array is shown, which is not the behavior I'm looking for.

**Comment by remkop** [comment]
Hi, picocli already shows a different description based on display context: only the first line of the header or description (header if both are defined) is shown in the subcommands listing as the brief description for each subcommand.

As for adding documentation for embedded newlines, I need to take another look.
If you are able to provide a pull request to improve the documentation that would be great!

**Comment by bbottema** [comment]
> picocli already shows a different description based on display context: only the first line of the header or description (header if both are defined) is shown in the subcommands listing as the brief description for each subcommand.

If #430 is solved, then yes, perfect. Going to test your change now...
