### ISSUE TITLE
Enhancement: printHelpIfRequested should support a custom ColorScheme

### ISSUE THREAD

**Issue by bbottema** [remkop/picocli#433]
The documentation [indicates](https://picocli.info/#_double_dash_code_code#_color_scheme) you can use a custom ColorScheme like so:
```java
CommandLine.usage(annotatedObject, System.out, colorScheme);
```
However, I have been unable to find a way to use a custom color scheme using `printHelpIfRequested`:
```java
CommandLine.printHelpIfRequested(pr.asCommandLineList(), out, err, Ansi.ON);
```
Is there a way to achieve this? Specifically I wish to assign a color to all subcommands listed under "_Command:_". UsageMessageSpec also doesn't allow this customization as far as I can see.

**Comment by remkop** [comment]
You can use the system properties [described in the manual](https://picocli.info//#_configuring_fixed_elements).

System Properties to Override the Color Scheme
```
picocli.color.commands
picocli.color.options
picocli.color.parameters
picocli.color.optionParams
```
For example:

```
java -Dpicocli.color.options=blink,blue -Dpicocli.color.parameters=reverse com.app.Main
```

System property values may specify multiple comma separated styles.

**Comment by bbottema** [comment]
Ahh, missed that one. Thanks, that solves it for me.

For a consistent API though, I would still argue for the above case. It feels a little strange to me that only CommandLine.usage(..) accepts a custom ColorScheme.

**Comment by remkop** [comment]
Let's leave this ticket open and I'll get to it at some point.
Unless you feel like providing a pull request to get it done faster. :-)

**Comment by remkop** [comment]
Fixed in master. Please verify.
If you have any code that could be added to picocli's unit tests to verify this, that would be very helpful.

**Comment by bbottema** [comment]
Yep works, added a junit test for you as well.

**Comment by remkop** [comment]
Thanks for the unit test!
