### ISSUE TITLE
How to expand path ?

### ISSUE THREAD

**Issue by bioinfornatics** [remkop/picocli#437]
Dear,

When I declare a parameter `File foo` and I provide this path `~/foo.txt` the command line parser create an object `File` with an unexpanded path. Which imply methods like `File.exists` can't resolve the path.

Is it possible to check if provided pah starts with `~` ?
And if true, expand it

```java
path = path.replaceFirst("^~",System.getProperty("user.home"));
```

Thanks

**Comment by RobertZenz** [comment]
You can do that afterwards as post processing, though. Anyway, `~` should have been extended by the shell, just like `$HOME`, so the question is why you end up with it.

**Comment by remkop** [comment]
@bioinfornatics  you can register a custom converter that replaces `~` with the user home directory before creating a File:

```
CommandLine cmd = new CommandLine(new MyApp());
cmd.registerConverter(File.class, s -> new File(s.replaceFirst("~", System.getProperty("user.home"))));
cmd.parseWithHandler(new CommandLine.RunLast(), args);
```

Or declaratively
```
class MyFileConverter implements picocli.CommandLine.ITypeConverter<File> {
    @Override public File convert(String value) throws Exception {
        return new File(value.replaceFirst("~", System.getProperty("user.home")));
    }
}
@CommandLine.Option(names = "-f", converter = MyFileConverter.class)
File file;
```

**Comment by bioinfornatics** [comment]
Thanks a lot, @RobertZenz  and @remkop it is well explained.

Have a nice day

**Comment by remkop** [comment]
Cool! Thanks for using picocli!
