### ISSUE TITLE
Annotated setter methods for multi-value options are invoked with accumulating values

### ISSUE THREAD

**Issue by zegelin** [remkop/picocli#438]
While I expected that that the setter method for an multi-value option (with a collection type and/or arity) would be called for each time the option is specified -- i.e., `-v a -v b -v c` would invoke the setter method 3 times.

What was not expected behaviour is that the passed collection parameter contains not just the current option value(s), but also all the previously processed values.

For example, given the following annotated setter method option definition:
```
@Option(names = "-v", arity = "1..*")
void setValue(final List<String> values) {
    System.out.println(values);
}
```

When invoked with these arguments:
`-v value1 value2 value3 -v value4 -v value5`

The result is:
```
[]
[value1, value2, value3]
[value1, value2, value3, value4]
[value1, value2, value3, value4, value5]
```

When the method is explicitly used as a setter (ie `this.field = parameter`) this behaviour is reasonable, but why have setters when you can just annotate fields?

Setter methods, as mentioned in the documentation, are good for validation or post-processing of option values.

The "unique property" example in the docs even has to work-around this behaviour. It checks to see if the key already exists, but then only throws an exception if the value for that key is different. The example could be simplified if the setter method was only passed _new_ values. It could simply check if the key exists, and if so, throw an exception.

For light-weight validation this behaviour is probably okay, but any heavy-weight validation/work would be re-executed multiple times.

Perhaps this behaviour could be made optional? Maybe a parameter annotation (so as not to clutter the `@Option` annotation with even more flags:
```
@Option(names = "-v", arity = "1..*")
void setValue(@NewValuesOnly final List<String> values) {
    System.out.println(values);
}
```

----

I was hoping to use a setter method to "expand" some options in a similar way to _@-files_ -- if an option value is prefixed with an `@` then assume the value is a file name and load the lines of the file as additional values.

With the current behaviour I'd be reading the files multiple times unless I keep track of which files I've already processed.

**Comment by remkop** [comment]
Thanks for the very lucid explanation. 

One problem I see is that this would make it impossible for picocli to reset the option to its initial value when the same `CommandLine` instance is used to parse different input:

```
CommandLine cmd = new CommandLine(new App());
String [] args = getUserInput();
while (args != null) {
    cmd.parseWithHandler(new RunLast(), args);
    args = getUserInput();
}
```

Picocli resets all options and positional parameters to their initial value at the beginning of a `parse` call. Next it sets the default values if any were specified, and finally it sets values parsed from the user input. 

This relies on the “overwriting” behavior that you mentioned.

**Comment by remkop** [comment]
Closing this ticket:
The behavior in the description of this ticket is the expected behavior.
