### ISSUE TITLE
Allow "interactive" arguments to be put in @-files while bypassing prompt

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#453]
Right now it appears that it is not possible to store "interactive" arguments in @-files without requiring the user to enter a value in stdin. It should be possible to allow batch mode for passwords, etc.

**Comment by remkop** [comment]
I’m not sure that I want to support this. 

Why not simply define a second option that’s non-interactive where users can supply the password in batch use cases.

**Comment by bobtiernay-okta** [comment]
From a user point of view, doesn’t  that strike you as confusing? —password and —password-batch?

I was thinking about this a bit more and was wondering if instead of “interactive” there could be a more expressive enum to support interactive, batch and both, with the default being batch.

As an aide, I had to rollback my use of the new interactive feature because this broke the @-files support (it seems)

**Comment by remkop** [comment]
From an end user point of view it’s very clear: one option will cause the application to wait for input on stdin, while the other option can execute immediately with parameters specified on the command line. 

I think what you’re really trying to do is support reading passwords from a file. Picocli provides the building blocks for this but you’ll need to build it in the application.

**Comment by remkop** [comment]
I’ll add some text to the user manual to explain that interactive options cannot be used when executing the command in (non-interactive) batch mode. 

I’ll add a recommendation that CLI app authors also provide non-interactive alternative options to allow end users to run the command interactively as well as in batch mode. 

Examples that avoid specifying the password in plain text on the command line: `--password:file=$HOME/mypasswordfile` (security based on file permissioning) or `--password:env=ENV-KEY` (where the application -not the shell- gets the value from the environment variables).

**Comment by remkop** [comment]
I've added some text to the [user manual](https://github.com/remkop/picocli/wiki/Manual-(3.6.0-SNAPSHOT)#interactive-password-options). Please let me know if this can be improved further.

**Comment by bobtiernay-okta** [comment]
Thanks, appreciate it!
