### ISSUE TITLE
Integrate completion generation into command itself

### ISSUE THREAD

**Issue by jvassev** [remkop/picocli#456]
Picocli is probably the greatest cli parser ever - language wide. It has helped me reduce my project size with 50%.

I am using this pattern to support autocompletion. I borrowed it from `kubectl completion bash`. I think other people may find it useful and you can this example in the dev guide

`kubectl`'s approach would dump the completion scripts to stdout. In picocli term it means just this:

```java
@Command(name = "bash",
        description = "Generate bash shell completion script"
)
final class BashCompletion implements Runnable {
    @Spec
    protected CommandSpec spec;

    @Override
    public void run() {
        CommandLine root = spec.commandLine();
        while (root.getParent() != null) {
            root = root.getParent();
        }
        String script = AutoComplete.bash(root.getCommandName(), root);
        System.out.println(script);
    }
}
```

The if your command is called `foo`, one can just do this:
```bash
eval "$(foo completion bash)"
```

picocli could also include a `Completion` command that users can just `add`. When zsh support arrives users will get `foo completion zsh` just by recompiling!

**Comment by remkop** [comment]
Very cool, thank you!

**Comment by bobtiernay-okta** [comment]
The downside of this is that it may be too slow for something like a bashrc file. However, it would be useful for exporting the completions from the binary to a file.

**Comment by remkop** [comment]
@jvassev Thanks again for raising this!

Your suggestion is now part of the documentation: https://picocli.info/autocomplete.html#_distribution
