### ISSUE TITLE
Any way to set an option value programatically using an arg string ?

### ISSUE THREAD

**Issue by NicolasMassart** [remkop/picocli#457]
Hi,
My use case is that I want a TOML config file with key/value matching the CLI options names : 
CLI : `myapp --option-one="super value"`
TOML : `option-one="super value"`

In the end I could have `myapp --config=my-toml-file.toml`

Then once the CLI is already parsed and initialised, that I'm running into the right command, I analyse if my app have a config file and if so, I want the config file values to override options default values or CLI passed value.

Then I get my option with `OptionSpec option = commandLine.getCommandSpec().findOption(optionNameWhichIsTOMLKey);`
and I would like to be able to set the new value of my option from the TOML value without having to convert it but simply by passing the String arg "super value" and let Picoli convert the value to the right type itself as it does when passing the arg on command line using converters:
`option.setValue(optionValueWhichIsTOMLValue);`
But the setValue() is typed.

I don't think parsing all args again is the way as I would like to keep all that was entered on CLI.
The thing I think about is having a setter with a string type for options that would be able to parse the parameter as it does during command line parsing but individually for the defined option.
Also do you see any other way to do what I want to do ?
Thanks.

**Comment by remkop** [comment]
I see what you mean. One problem is that there is no API to get the registered `ITypeConverter`s, but even if we added API for that, the logic of converting a String to a typed value is not straightforward if you want to support everything that picocli does (array types, collection types, Map types, and potentially multiple values separated by a `split` regex). This logic is spread over multiple methods in the internal `Interpreter` class in picocli.

Please take a look at https://github.com/remkop/picocli/issues/321. Would that meet your requirements? Basically this would allow you to read default option values from the config file. (A common pattern is to let the user have the final say, so user-specified values override configuration defaults. Are you sure you want the config file to override values that the user specified on the command line?)

If #321 is not useful, then the best I can do is provide some API to get the registered `ITypeConverter` for a class, and you would need to use this type converter to create the typed value from the string value in your application.

**Comment by NicolasMassart** [comment]
What you proposed is what I want my overriding order to be : defaults -> overridden by config if any -> overridden by CLI option if any.
So your default provider in #321 seems to have the right behaviour. I just still wonder how to add a config file in this step. Do you mean loading my file in the IDefaultValueProvider then I could use the ArgSpec parameter to find the current option name then retrieve the value from my file and return it as default ? If yes, this would be so great !

**Comment by remkop** [comment]
Glad to hear that!

I was thinking to add `IDefaultValueProvider` getter and setter methods to `CommandSpec`. In your application, all you would need to do is implement the `IDefaultValueProvider` interface to return values from a config file, and call the `commandSpec.defaultValueProvider` setter method with your implementation.

When the `parse` method is called, picocli will first set the defaults, and then parse the actual input. The exact initialization sequence will be:

1. clear the argSpec value 
2. if initial value exists, set this value (field value in the case of annotated fields)
3. if default value was specified, set this value
4. if default value provider has non-null value for this argSpec, set this value // <- this needs to be added
5. set value from user input

So in your application you won't need to get values from the default provider for each ArgSpec; this happens automatically. All you have to do is provide a `IDefaultValueProvider` implementation.

**Comment by NicolasMassart** [comment]
would be so great to have it directly as an @Option attribute. So In the implementation of IDefaultValueProvider if I well understand, I would just have to implement `String defaultValue(ArgSpec argSpec);` and return my string by reading my config according to the option name defined in the ArgSpec param ?
When do you think you will do that ? Not for urge you, just to have a vague idea ;)

**Comment by remkop** [comment]
Do you think you will be able to provide a pull request with unit tests? If so, we may be able to include it in the upcoming 3.6 release. I'm hoping to release 3.6 in a week or two. Otherwise I probably won't be able to get to it until the 3.7 release.

**Comment by remkop** [comment]
I updated #321 a bit.

**Comment by NicolasMassart** [comment]
I will try to provide something. Maybe I will have questions so, thanks for the help!

**Comment by NicolasMassart** [comment]
Will communicate for this issue in #321
