### ISSUE TITLE
Linux friendly manpage generation

### ISSUE THREAD

**Issue by kravemir** [remkop/picocli#459]
I'm using `picocli` for my project, and I would like to create manual page for it.

Is there any recommended approach to generate a manual page for standard linux's command `man` ?

Issue type, depending on possibilities: question, feature suggestion, or article/documentation improvement request.

**Comment by remkop** [comment]
That’s a great idea!
We can add a `DocGen` class that generates documentation from a `CommandSpec` in various formats. The first format could be manpage.

**Comment by remkop** [comment]
See also #299, which suggests using pandoc for this. 

Do you feel like providing a PR for this?

**Comment by remkop** [comment]
All good points. 

* a new artifact is a good idea. I’m thinking `info.picocli:picocli-docgen`. Let’s make a new module for this in the picocli project. 
* package: I’m thinking `picocli.docgen`
* class DocGen (no need to extend anything) 
* one idea is to have a static method `generateDocs(String contentType,  CommandSpec spec) : String`. 

The idea/hope is that content type (mime type) would make it extensible: `”text/html”` for HTML, etc. Not sure if this is a good idea. Do markdown and man pages have a standard mime type, for example?

Also not sure what the return type of the method should be. Either return a String, or void and print to standard out?

Thoughts?

**Comment by kravemir** [comment]
Also, output type can be DocBook SGML, which can be then converted to manpage using [`docbook-to-man`](http://manpages.ubuntu.com/manpages/bionic/man1/docbook-to-man.1.html)

**Comment by remkop** [comment]
> And, so you think of whole new artifact, and/or github project? Or, what's yours idea about new artifact picocli-docgen.

I was thinking to create a module `picocli-docgen` in the picocli project. The build would create a new `picocli-docgen-x.x.x.jar` in addition to the `picocli-y.y.y.jar`. No need for a new GitHub project. The `picocli-docgen` module may have external dependencies in addition to depending on picocli. 

About the `DocGen` API, what you’re saying makes a lot of sense. We can evolve this over time, I would be surprised if we got it perfectly right from the beginning. :-)

**Comment by remkop** [comment]
About mine type for man pages:

> Currently, troff documents are listed under the nonstandard application/x-troff and text/x-troff.  However, the IANA approved the standard text/troff MIME type on 2005-06-10.

according to https://bugs.freedesktop.org/show_bug.cgi?id=5072

**Comment by remkop** [comment]
I will rename the existing `examples` module to `picocli-examples`.

If you want, I can create a `docgen` branch and add a `picocli-docgen` module in that branch. That may make it easy to work together on this.

**Comment by remkop** [comment]
Perhaps [doxygen](http://www.doxygen.nl/) is a good tool to use for this ticket. 

Alternatively we can just generate raw [man groff macros](http://manpages.ubuntu.com/manpages/precise/man7/man.7.html). [This page](https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/) and [this page](http://www.linuxhowtos.org/System/creatingman.htm) show some examples. It looks reasonably straightforward.

@kravemir Are you still interested in this? Should I go ahead and create the `picocli-docgen` module?

**Comment by kravemir** [comment]
@remkop: yes, I'm interested in this. It's on my todo-list, but there are still some task before this. One was to create picocli debian package and get it uploaded to debian official repositories.

I saw readme, and thanks for attribution :-) Though, if you want to refer me on debian, you can use https://udd.debian.org/dmd/?kravec.miroslav%40gmail.com or https://qa.debian.org/developer.php?login=kravec.miroslav%40gmail.com.

And, regarding this feature. I thought about first implementing some solution directly for my tool, then make it as reusable solution, and create PR for picocli containing the implementation.

**Comment by remkop** [comment]
Understood. Thank you again for creating the debian package! I updated the links on the README page, let me know if these links need further correction.

About this ticket, glad to hear you are still interested.
Feel free to create a `picocli-docgen` module (#498) as part of the PR if this module does not exist by then.

**Comment by hupfdule** [comment]
> Also, output type can be DocBook SGML, which can be then converted to manpage using [`docbook-to-man`](http://manpages.ubuntu.com/manpages/bionic/man1/docbook-to-man.1.html)

I think DocBook is a very flexible way to support multiple output formats.
You should even consider generating an AsciiDoc document, which then can be converted to manpages directly (or HTML or PDF) or to DocBook which in turn can be converted to other formats.

There exists the [https://github.com/asciidoctor/asciidoctorj](AsciidoctorJ) project to parse or convert AsciiDoc documents programmatically. 

AsciiDoc is very easy to write for humans (also and very readable), however I don't know how easy it is for a machine to generate AsciiDoc or whether AsciidoctorJ provides an API to _create_ AsciiDoc documents.

**Comment by hupfdule** [comment]
A description on how to do it via commandline is given in
https://asciidoctor.org/docs/user-manual/#man-pages.

As far as I know, AsciidoctorJ also supports this.

There are some restrictions on the format of the AsciiDoc document, but that shouldn't be a problem.

**Comment by remkop** [comment]
An initial version of `picocli.codegen.docgen.manpage.ManPageGenerator` has landed in the `picocli-codegen` module in master.

You can test by checking out the latest master and building with:

```
gradlew clean publishToMavenLocal
```

That should publish `picocli-4.2.0-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.0-SNAPSHOT` dependency.

Here is an example Gradle `build.gradle` snippet:

```groovy
dependencies {
    compile "info.picocli:picocli:4.2.0-SNAPSHOT"
    annotationProcessor "info.picocli:picocli-codegen:4.2.0-SNAPSHOT"
}

mainClassName = "my.pkg.MyCommand"

task generateManpageAsciiDoc(type: JavaExec) {
    dependsOn(classes)
    group = "Documentation"
    description = "Generate AsciiDoc manpage"
    classpath(configurations.compile, configurations.annotationProcessor, sourceSets.main.runtimeClasspath)
    main 'picocli.codegen.docgen.manpage.ManPageGenerator'
    args mainClassName, "--outdir=${project.buildDir}/generated/docs"
}

apply plugin: 'org.asciidoctor.convert'
asciidoctor {
    dependsOn(generateManpageAsciiDoc)
    sourceDir = file('src/docs/manpage')
    outputDir = file('build/docs')
    logDocuments = true
    backends 'manpage'
}
```

The `generateManpageAsciiDoc` task generates `xxx.adoc` files in `build/generated/docs` for each command and subcommand.

The `asciidoctor` task converts adoc files in `src/docs/manpage` to `xxx.1` manpage files in `build/docs/manpage/`.

Note that the `sourceDir` for the `asciidoctor` task is the `src/docs/manpage` directory. In this directory, I have a manually maintained `xxx.adoc` file for each command and subcommand, to allow me to customize the resulting manpage.

In the manually maintained `xxx.adoc` files you can use AsciiDoctor's [include mechanism](https://asciidoctor.org/docs/user-manual/#include-directive). If you simply want to add some sections to the end of the page, you can pull in the full generated page with the `generated-manpage` tag, like this:

```
// src/docs/manpage/xxx.adoc
:includedir: ../../../build/generated/docs
include::{includedir}/xxx.adoc[tag=generated-manpage]

== Authors
My, myself and I.
```

It is also possible to include the picocli-generated sections individually, so that the generated sections can be customized with additional text that follows the generated text for the section. For example:

```
// src/docs/manpage/yyy.adoc
:includedir: ../../../build/generated/docs
include::{includedir}/yyy.adoc[tag=generated-man-header]

include::{includedir}/yyy.adoc[tag=generated-man-name-section]

This is a very good tool.

include::{includedir}/yyy.adoc[tag=generated-man-synopsis]

*mycommand* [-hVv] [a=VERY] [--different=synopsis]

include::{includedir}/yyy.adoc[tag=generated-man-description]

Here are some additional description lines.

include::{includedir}/yyy.adoc[tag=generated-man-arguments]

include::{includedir}/yyy.adoc[tag=generated-man-options]

include::{includedir}/yyy.adoc[tag=generated-man-commands]

include::{includedir}/yyy.adoc[tag=generated-man-exit-status]

include::{includedir}/yyy.adoc[tag=generated-man-footer]

[%hardbreaks]
Here is an extra example:
abc def ghi jkl mno pq
abc def ghi jkl mno pq
abc def ghi jkl mno pq

== Authors
All of us.

== Copyright
Just hand it out, it's fine.
```

(These tag names may be changed before the picocli 4.2.0 release.)

Of course, the `asciidoctor` task could also simply take the generated `build/generated/docs` as input directly if no customization is needed.


Known issues:
* custom option sections ([arggroup option sections](https://picocli.info/#_option_sections_in_usage_help)) are still ignored
* embedded markup like `@|bold hello|@` is rendered as ANSI escape codes and not yet converted to AsciiDoc markup

Feedback welcome!

**Comment by remkop** [comment]
@kravemir, @hupfdule,  All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including [this functionality](https://picocli.info/#_generate_man_page_documentation). Enjoy!
