### ISSUE TITLE
Issues using Picocli as source file directly in project

### ISSUE THREAD

**Issue by NicolasMassart** [remkop/picocli#464]
I tried to copy Picocli directly in my project (for testing of a modification) but I had to include more than the CommandLine.java file : 
- The CommandLine makes references to AutoComplete in comments like `{@link AutoComplete}` which produces errors on my IDE and CI.
- Picocli breaks rules on my Gradle build checks like the use of raw types `[rawtypes] found raw type` or redundant casts `[cast] redundant cast to T` and warnings are treated as errors in our checks...
- I have a strange 
```
error: cannot find symbol
                        ? Range.valueOf("" + ((MethodParam) member.accessible).position)
                                               ^
  symbol:   class MethodParam
  location: class Range
```
- My coding conventions are set to Google code style, and it reformats the code of the Picocli in a way that I can't even think of merging my modifications back to Picocli original project.
- we have to create a picocli package or change packages in CommandLine file -> changing all imports.

So I did my modifications in the Picocli project (my clone) and built the JAR to include in my other project.
I then asked myself, why as Picocli is intended to be used directly as a single source file ?
What have I missed ?
Thanks.

**Comment by remkop** [comment]
The background is in the FAQ: https://github.com/remkop/picocli/wiki/FAQ

But as you point out there may be practical issues. Particularly, you may need to exclude picocli from your project's checkstyle rules (picocli cannot follow rules of all possible projects).

Good point about the javadoc links causing IDE errors, I'll look at removing them.
What compiler do you find the "cannot find symbol MethodParam" with?

**Comment by remkop** [comment]
Also, what Gradle config do you have to treat raw types and redundant cast warnings as errors?

**Comment by NicolasMassart** [comment]
Don't worry, I know the background, I was just reporting issues I faced. But for me using it in a dependency system like gradle solves all my problems. I just wanted to point that the "only one file to include in your project" was perhaps not so easy to reach and I was hopping we could improve this experience, perhaps by adding more documentation on what you explain in your previous comment.
For the MethodParam error, it's with gradle and open jdk 1.8 and I admit I don't have a clue about the cause as I can see it and IDE can navigate perfectly to it.

**Comment by remkop** [comment]
I removed the {@link AutoComplete} from the javadoc, and
fixed compile warnings "use of raw types [rawtypes] found" and "[cast] redundant cast to T" in master.

**Comment by NicolasMassart** [comment]
Nice work, thanks !

**Comment by remkop** [comment]
I believe I also fixed this error you reported. MethodParam is now a package protected inner class of Model instead of a private inner class of Model.

```
error: cannot find symbol
                        ? Range.valueOf("" + ((MethodParam) member.accessible).position)
                                               ^
```
