### ISSUE TITLE
Add support for completing positional parameters in completion script

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#468]
Follow-up issue resulting from discussion on #461:

add support for completing positional parameters in addition to named options. This may be challenging as it requires the completion script to determine the position index in user input that contains a mixture of subcommands, positional parameters, named options and option parameters.

**Comment by dwalluck** [comment]
I would like to clarify something. Does picocli support subcommands inside other subcommands? How does picocli handle subcommands when there is also an argument to the parent command?

If I have a subcommand and a first parameter, it always seems to print "Missing required parameter".  I thought you had said on another issue that if there is a subcommand and a required argument in the parent command at position one that it would allow this and try to match the subcommand first.

I implemented a bash-completion script that mixes the completions for the commands with the completions with the first argument, but picocli itself doesn't seem to be able to handle it.

Would it be better to submit the pull request with the bash-completion generator even if it is not finished? I have a test program which is exhibiting this behavior.

**Comment by remkop** [comment]
> Does picocli support subcommands inside other subcommands? 
Yes, nested subcommands are supported to any depth.

> How does picocli handle subcommands when there is also an argument to the parent command?
The parser will first try to match options, then subcommands, then positional parameters and finally treat the argument as unmatched.

> If I have a subcommand and a first parameter, it always seems to print "Missing required parameter". I thought you had said on another issue that if there is a subcommand and a required argument in the parent command at position one that it would allow this and try to match the subcommand first

It will try to match the subcommand first, and if successful the subcommand ends up consuming the remaining arguments. This then leaves the parent command without a value for its required parameter, hence the error. Users may invoke a subcommand but that does not mean they can omit required parameters. It sounds like this is the expected behaviour.

**Comment by dwalluck** [comment]
Do you have bash-completion installed? It's probably best if you just try #502. No matter what number of parameters I pass, it seems to not parse successfully.

It does not support `Map` yet, but I think it supports all of the other types that it can support.

**Comment by remkop** [comment]
I would expect this input to pass without "Missing required parameter" error:

```
java BashCompletionAutoCompleteTestApp file1 file2 bar -b baz foo
java BashCompletionAutoCompleteTestApp file1 file2 foo -f 255.255.255.255
```

I noticed one small this: the `Foo` command has two positional parameters but they have the same index (the default, which is `"0"`). I think you want to give them separate positional indices:

```
@Parameters(index = "0", arity = "1", paramLabel = "HOST_ONE", description = "SRC")  
private InetAddress src;  

@Parameters(index = "1", arity = "1", paramLabel = "HOST_TWO", description = "DEST")  
private InetAddress dest;  
```

**Comment by dwalluck** [comment]
> I noticed one small this: the `Foo` command has two positional parameters but they have the same index (the default, which is `"0"`). I think you want to give them separate positional indices:

Is it possible to detect collisions here and cause an error?

**Comment by remkop** [comment]
That may be a good idea. Until now I deliberately allowed this because there may be use cases where an application wants to capture individual positional parameters in strongly typed fields but also capture all positional parameters as encountered in a list.

**Comment by dwalluck** [comment]
If that is a special case, you could always make it an option.

**Comment by remkop** [comment]
Making this an error is perhaps a bit strong, but showing a warning message may be a good idea (with perhaps a system property to suppress the warning).

**Comment by remkop** [comment]
Fixed with https://github.com/remkop/picocli/pull/505

**Comment by remkop** [comment]
@dwalluck, @yohanakh, All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including this fix. Enjoy!
