### ISSUE TITLE
Completion scripts have redundant case statement

### ISSUE THREAD

**Issue by dwalluck** [remkop/picocli#470]
I believe that we can simplify the competition scripts by using one case statement instead of two without losing any functionality. Replace:

```
case ${CURR_WORD} in
    foo)
      COMPREPLY=( $( compgen -- "" ) )
      return $?
      ;;
     *)
      case ${PREV_WORD} in
        foo)
          COMPREPLY=( $( compgen  -- "${CURR_WORD}" ) )
          ;;
    esac
esac
```

with

```
case ${PREV_WORD} in
    foo)
      COMPREPLY=( $( compgen -- "${CURR_WORD}" ) )
      return $?
      ;;
esac
```

**Comment by dwalluck** [comment]
This also seems to make competition of short options with an argument not complete correctly, although the long option version work.

**Comment by dwalluck** [comment]
It will fix the option argument handling, which I believe was a pre-existing bug. I have a pull request ready, but it's on top of #469.

**Comment by dwalluck** [comment]
I didn't see any regressions, but the following behavior is improved:

```
ARG_OPTS="-f --foo"
FOO_OPTION_ARGS="bar baz"
```

Then, `--foo<TAB><TAB>` always worked (and showed the options and allowed completing them), but `-f<TAB><TAB>` was showing `bar baz` but not complementing them (as a space is not being added after `-f` to trigger the competition).

**Comment by remkop** [comment]
Confirmed and merged. Nice work!
