### ISSUE TITLE
picocli help output is not GNU getopt compatible

### ISSUE THREAD

**Issue by dwalluck** [remkop/picocli#472]
Related to the the completion script, it looks like picocli `--help` output is not GNU compatible. We could consider making it compatible, or introducing ` --dump-options` (borrowed from `gpg2`) that simply dumps all options, one per line. One use for this is to allow bash-completion to automatically parse the help output. Another thing to consider is that even if it were compatible, we'd still likely have to strip the ANSI codes.

**Comment by remkop** [comment]
Can you clarify "GNU compatible", and where exactly is the help output not compatible?

**Comment by dwalluck** [comment]
I mean GNU `getopt` compatible. The output has the short and long options separated by a comma:  `-f FOO, --foo=FOO`.

**Comment by dwalluck** [comment]
Well, the point I think was that it expects a comma between the options in order to be able to parse. They could probably relax that function to except more types of input.

**Comment by remkop** [comment]
Can you expand a bit on how we could use this?

**Comment by dwalluck** [comment]
It is moreso to make picocli programs compatible with bash-completition. It is general purpose function that parses the `--help` output of any program so that arguments do not need to be manually specified in the script itself.

The way the scripts are written now for picocli, it it not directly useful, since the scripts spell out each and every option, even flag options that will have no special handling.

**Comment by remkop** [comment]
Looking at this again, I wonder: doesn't the picocli-generated help message have a comma between the options? See for example the JUnit5 `ConsoleLauncher` [usage help message](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher), generated by picocli:

```
...
  -u, --select-uri=URI       Select a URI for test discovery. This option can be repeated.
  -f, --select-file=FILE     Select a file for test discovery. This option can be repeated.
  -d, --select-directory=DIR Select a directory for test discovery. This option can be
                               repeated.
  -p, --select-package=PKG   Select a package for test discovery. This option can be repeated.
  -c, --select-class=CLASS   Select a class for test discovery. This option can be repeated.
  -m, --select-method=NAME   Select a method for test discovery. This option can be repeated.
  -r, --select-resource=RESOURCE
...
```

**Comment by dwalluck** [comment]
Yes, it's not the comma. That looks right to me.

But, if I try to parse my programs `--help` output using the bash-completion [`_parse_help()`](https://github.com/scop/bash-completion/blob/c2dd6745661d886327bb79591a6c6911f6f5c3f6/bash_completion#L791) function, for some reason, I am only getting the long options in the returned array. In any case, this will not play well with ANSI, and on Windows, ANSI appears to need to be forced.

**Comment by dwalluck** [comment]
OK, it appears to pick the short option only if no long option exists. The problem only appears to be related to ANSI codes, but I am not sure that anything can be done about this. The `Ansi.AUTO` mode doesn't work for me on Windows, but it seems the that JANSI code itself is not the best. My `TERM` is set to `cygwin` and I get ANSI codes. I think the code only checks for `xterm`. In any case, this problem does not appear to be related to the `--help` formatting at all. Sorry for the trouble!

**Comment by remkop** [comment]
You could set system property `picocli.ansi` to `false` before printing the help to force ANSI codes to be off, if that helps.

FYI: there is an effort ongoing (#483) to enable ANSI codes if the `System.out` stream has been replaced by Jansi. 

I opened #491 to track improving the `Ansi.AUTO` mode.

**Comment by dwalluck** [comment]
I will need a way to be able to pass JVM options to a program before it runs `--help`. The current shell script that the `AutoComplete` class outputs doesn't support this. Obviously, I don't want to put this in the script permanently, but rather, I think setting a variable inside the completion script before it calls this function may work the best.

**Comment by dwalluck** [comment]
The `_parse_help` function parses the `--help` output on the fly as part of the completion script itself, but this list seems to include less options than what we can already generate automatically.

Now that I've looked at it, it is not entirely useful. This function also forces the `=` separator at the end of long options. This means that even the completion scripts that ship with bash completion aren't consistent between completion scripts which use this function and those that don't.

**Comment by remkop** [comment]
Should we keep this ticket open? Is there any remaining work to be done for this ticket?

**Comment by dwalluck** [comment]
You can close it.
