### ISSUE TITLE
Circumvent classloading-related startup lag

### ISSUE THREAD

**Issue by jvassev** [remkop/picocli#482]
This is more of a question and sharing my solution for this - hoping there are safer ways.

Picocli has to introspect Command classes. Doing so causes many other classes to be loaded too. I was able to shave off 100ms from the startup time of my cli by avoiding this. Basically if you call Type.method() in your command's run() method the JVM has to load Type (in a cascading fashion) in order to verify your program - even if you are never going to call these methods.

I am using reflection to postpone any class loading until after the command is selected. This way only the command classes themselves are loaded and finally the classes which implement the single command requested by the user:

```java
abstract class BaseCommand implements Runnable {

    interface CommandExecutor {
        Object doExecute() throws Exception;
    }
 
    // find the CommandExecutor declared at the BaseCommand subclass.
    protected Object executeReflectively() throws Exception {
        Class<?> innerClass = getExecutorInnerClass();
        Constructor<?> ctor = innerClass.getDeclaredConstructor(getClass());
        CommandExecutor exec = (CommandExecutor) ctor.newInstance(this);
        return exec.doExecute();
    }

    private Class<?> getExecutorInnerClass() throws ClassNotFoundException {
        return getClass().getClassLoader().loadClass(getClass().getName() + "$Executor");
    }

    public void run() {
        try {
             executeReflectively();
       } catch(...){
          /// usual stuff
       }
    }
}

@Command(...) 
final class CopyProfile extends BaseCommand {
    @Option String source;
    @Option String dest;

    // class must NOT be static and must be called "Executor"
    public class Executor implements CommandExecutor {
        @Override
        public Object doExecute() throws Exception {
           // you can basically wrap your original run() with this boilerplate
           // all the CopyProfile's field are in scope!
          FileUtils.copy(source, dest);
        }
    }
}
```

It is not extremely type-safe but lets you just wrap your original run()/call() method in a simple 
```java
    public class Executor implements CommandExecutor {
        @Override
        public Object doExecute() throws Exception {
        // old body here
        }
    }
```
... and win a few millis!

**Comment by remkop** [comment]
I see what you mean. I've been thinking a bit about making a lazy-loaded CommandSpec but at first glance it does not seem trivial. Picocli builds the full hierarchy of commands and subcommands in order to parse command line arguments that may contain subcommands and provide usage help that lists the subcommands.

Perhaps the best way is to do the lazy loading in the application like in your example.

**Comment by remkop** [comment]
As a side-note, it may be good to have this question on StackOverflow to build a knowledge base for other picocli users. Would you be okay with moving this conversation to StackOverflow?

**Comment by jvassev** [comment]
Sure, I've moved the discussion to  https://stackoverflow.com/questions/52568432/how-to-reduce-slow-start-for-picocli-apps-due-to-reflection

**Comment by remkop** [comment]
Perfect! Thank you.
