### ISSUE TITLE
Auto detect Jansi

### ISSUE THREAD

**Issue by charphi** [remkop/picocli#483]
It would be usefull to make `Ansi.AUTO` detect if Jansi is available and enabled at runtime.
Thus, we wouldn't have to specify it manually.

For example:
```java
AnsiConsole.systemInstall(); // Jansi magic
CommandLine.run(new WindowsJansiDemo(), args);
AnsiConsole.systemUninstall();
```
instead of
```java
AnsiConsole.systemInstall(); // Jansi magic
CommandLine.run(new WindowsJansiDemo(), System.err, Ansi.ON, args);
AnsiConsole.systemUninstall();
```

**Comment by remkop** [comment]
Makes a lot of sense. 

What is a good way to detect that Jansi is installed? (I'm not sure that it is enough just to check that the Jansi jar is on the classpath...)

**Comment by charphi** [comment]
It seems that you just need to compare AnsiConsole.out and System.out such as:
`AnsiConsole.out == System.out`

Here is a quick example code:
```java
static boolean isJansiEnabled() {
	try {
		Class<?> ansiConsole = Class.forName("org.fusesource.jansi.AnsiConsole");
		Field out = ansiConsole.getField("out");
		return out.get(null) == System.out;
	} catch (Exception ex) {
		return false;
	}
}
```

**Comment by remkop** [comment]
Perfect!

Do you feel like providing a PR for this?

**Comment by remkop** [comment]
#486 has been merged. Thanks for the contribution!
