### ISSUE TITLE
Best way to specify option with optional value that prints current value when no value specified

### ISSUE THREAD

**Issue by marinier** [remkop/picocli#490]
I'm writing a REPL (so I'm using picocli internally to parse commands typed within the application, not to parse command line args), and I have a command with an option that I want to behave like this:

```
> cmd --myopt
Myopt value = 5
> cmd --myopt 4
> cmd --myopt
Myopt value = 4
```

That is, if the option is specified with no value, the current value of the parameter is printed, but if it is specified with a value, then the value is set. I was thinking to do this like this:

```java
int value = 5; // default
@Option(names = {"-e", "--epsilon"}, description="Acceptable values: [0, 1] default: ${DEFAULT-VALUE}", arity="0..1")
void setValue(String strValue) {
    if(strValue == "") printValue();
    else {
        try {
            value = Integer.parseInt(strValue);
            // validate value
        } catch(NumberFormatException e) {
            // print help for this option
        }
    }
}

```

Is that the best way? Is there a way to capture the default value in the description while still allowing no value to be passed to `setValue` (or at least `setValue` will know that no value was specified)?

**Comment by remkop** [comment]
@marinier  That is certainly one way to do it. Bear in mind that the setter method will be called multiple times: once to reset the default values, and then again each time the option is matched on the command line.

An alternative is to change the field type to `String`, put the annotation on the field, and call this logic (that is in the `setValue` method above) from your `run` or `call` method.

About your question:

> Is there a way to capture the default value in the description while still allowing no value to be passed to setValue (or at least setValue will know that no value was specified)?

I believe that the code you showed should accomplish this, but I haven't tried it. Is it not working as expected?

**Comment by remkop** [comment]
As a side-note, it may be good to have this question on StackOverflow to build a knowledge base for other picocli users. Would you be okay with moving this conversation to StackOverflow?

**Comment by marinier** [comment]
Thank you for your response; I'll post any followups on StackOverflow.

**Comment by remkop** [comment]
I went ahead and [posted](https://stackoverflow.com/questions/52444007/picocli-best-way-to-specify-option-with-optional-value-that-prints-current-valu) this question on StackOverflow.

**Comment by marinier** [comment]
Sorry, I misunderstood what you were asking. Thanks!
