### ISSUE TITLE
Document aliases parameter for @Command attribute

### ISSUE THREAD

**Issue by marinier** [remkop/picocli#492]
The `aliases` parameter of the `@Command` attribute doesn't appear to be documented at https://picocli.info/. (Perhaps another thing to consider is changing `name` to `names`, like `@Option`, and dropping `aliases`. The increased consistency may aid in discoverability of this feature.)

**Comment by remkop** [comment]
Interesting idea about using `@Command(names = { ... })`.  In the context of commands, the term "alias" is [fairly common](https://en.wikipedia.org/wiki/Alias_(command)), so I did not think of using `names`. I'll think about this some more. 

You're right about the lack of documentation. Do you think you will be able to provide a pull request to improve the doc?

**Comment by marinier** [comment]
I'm taking a look at the documentation to see how to best work this in. There doesn't seem to be a great place for it at the moment -- there's no explicit documentation on the `@Command` attribute, it's more mentioned in passing and shows up in lots of examples.

So I can imagine a few approaches here:
- Add a new section on the `@Command` attribute, probably a subsection under the Subcommands section?
- Mention it in passing; e.g., in section 13.2 where it says that `@Command`s must have a name. As this is related, it could fit there ok.
- Include it in some examples that already use `@Command` without really explaining it.

Clearly a dedicated section would be the greatest value, but also the most work, whereas one of the other approaches could be done immediately. Thoughts?

**Comment by remkop** [comment]
Away from pc now, but the Subcommands section seems like a good fit.

**Comment by marinier** [comment]
I finally decided on a brief new subsection for aliases; pull request submitted. I realized that trying to more completely document `@Command` was unnecessary, given that the javadocs essentially do that.

**Comment by remkop** [comment]
Thank you for the PR! I merged it. 

I’ll close this ticket after I get a chance to update the RELEASE-NOTES.md.
