### ISSUE TITLE
Add custom command to help menu

### ISSUE THREAD

**Issue by Zethson** [remkop/picocli#504]
Hi,

I love picocli and we use it extensively at our company. I'm running into the following limitation.
We're using picocli file arguments as config files and it works as expected.

However, when uses request help and the help menu is shown they do not see how config files can be used when running our tool.
-> it would be great if we could add a custom help message that looks like the following
@path/to/config.txt config file which sets property x,y,z
- input input file blablablabl
- output output file blablablabla

Do you have any suggestions as to how we can achieve this? If not I would like to request this feature.

**Comment by remkop** [comment]
Could you please share a small example command, and what you would like the usage help message to look like ideally?

**Comment by remkop** [comment]
After reading again I think I understand. (Sorry, brain is asleep.)

If you have some fixed argument files that are deployed with the command, you could mention the path to the argument file(s) in the footer. The footer is multi-line, and of unlimited length. See also https://picocli.info/#_header_and_footer

**Comment by Zethson** [comment]
Sounds like a great idea. Thank you very much!

**Comment by remkop** [comment]
No worries. Enjoy!
