### ISSUE TITLE
How picocli know if ANSI color is supported or not ?

### ISSUE THREAD

**Issue by sbernard31** [remkop/picocli#512]
I read the https://picocli.info/#_supported_platforms and saw picocli is able to adapt to the platform and only show color when supported.

How do it do that ?
What happened if I run it on a linux platform (supporting ANSI) in a console which does not support it. (e.g. eclipse console) ?

(I see there is idea about using TERM env to know if color is supported or not : https://github.com/mihnita/ansi-econsole/issues/34)

**Comment by remkop** [comment]
You are right that picocli cannot be 100% sure. It uses some heuristics (in plain words, it makes a guess). As you point out, there may be cases where it guesses wrong. 

The logic that makes the decision is here (suggestions for improvements are always welcome): 
https://github.com/remkop/picocli/blob/master/src/main/java/picocli/CommandLine.java#L9215

The end user has the final say: they can invoke the application with system property `picocli.ansi` set to `true` or `false` to force ANSI on or off.

**Comment by sbernard31** [comment]
Ok I get it. Thx a lot for your answer !

**Comment by vorburger** [comment]
This comes up first/early (for me) on a Google Search for something like "picocli color", so just FTR for other future readers: I learnt in #581 and [here](https://youtrack.jetbrains.com/issue/IDEA-205699/Provide-ANSI-detection-mechanism-for-console-applications-in-IJ-Terminal) that picocli also respects the `NO_COLOR` and `CLICOLOR_FORCE` environment variables from https://bixense.com/clicolors/ and https://no-color.org.

**Comment by remkop** [comment]
The full details of picocli’s logic on when to emit escape codes is documented in the user manual:

https://picocli.info/#_heuristics_for_enabling_ansi
