### ISSUE TITLE
feature request: ability to show header/banner at all times

### ISSUE THREAD

**Issue by picaron** [remkop/picocli#517]
I like having the ability to add a nice header in the @Command annotation

for example:

```
@Command(name = "git-star", header = {
        "@|green       _ _      _             |@", 
        "@|green  __ _(_) |_ __| |_ __ _ _ _  |@",
        "@|green / _` | |  _(_-<  _/ _` | '_| |@",
        "@|green \\__, |_|\\__/__/\\__\\__,_|_|   |@",
        "@|green |___/                        |@"},
        description = "Shows GitHub stars for a project",
        mixinStandardHelpOptions = true, version = "git-star 0.1")
```

it would be nice also to have the option to always show that header/banner when the program is running

**Comment by remkop** [comment]
Hi @picaron , you can achieve this with a little bit of code:

```
String[] banner = new String[] {
        "@|green       _ _      _             |@", 
        "@|green  __ _(_) |_ __| |_ __ _ _ _  |@",
        "@|green / _` | |  _(_-<  _/ _` | '_| |@",
        "@|green \\__, |_|\\__/__/\\__\\__,_|_|   |@",
        "@|green |___/                        |@"};
for (String line : banner) {
    System.out.println(CommandLine.Help.Ansi.AUTO.string(line));
}
```

**Comment by picaron** [comment]
@remkop I dont want to duplicate this banner in two places just to print it manually

since I'm using Kotlin, parameters to an annotation have to be compile time constant, I cannot assign it to a variable and use it in two places :(

**Comment by remkop** [comment]
Oh I see. You can get the banner from the usage help message. Suppose the class annotated with `@Command` is called `App`, then:

```
String [] banner = new CommandLine(new App())
    .getCommandSpec()
    .usageHelpMessage()
    .header();

// and print after converting markup to ANSI 
````

**Comment by remkop** [comment]
@picaron  Did this answer your question?

I was thinking, it may be good to also post this question on StackOverflow (like [this one](https://stackoverflow.com/questions/52444725/picocli-how-to-access-subcommands-after-parsewithhandlernew-runall-args) ) to create a knowledge base for picocli users. What do you think?

**Comment by remkop** [comment]
Putting it all together:

```java
@Command(name = "git-star", header = {
        "@|green       _ _      _             |@", 
        "@|green  __ _(_) |_ __| |_ __ _ _ _  |@",
        "@|green / _` | |  _(_-<  _/ _` | '_| |@",
        "@|green \\__, |_|\\__/__/\\__\\__,_|_|   |@",
        "@|green |___/                        |@"},
        description = "Shows GitHub stars for a project",
        mixinStandardHelpOptions = true, version = "git-star 0.1")
class GitStar implements Runnable {

  @Option(names = "-c")
  int count;

  @Spec CommandSpec spec;

  public void run() {
    // print banner every time the command is invoked
    String[] banner = new CommandLine(new GitStar()).getCommandSpec().header();
    // or: String[] banner = this.spec.header();
    for (String line : banner) {
      System.out.println(CommandLine.Help.Ansi.AUTO.string(line));
    }

    // business logic here...
  }

  public static void main(String[] args) {
    CommandLine.run(new GitStar(), args);
  }
}
```

Does this answer your question?

**Comment by picaron** [comment]
yes thank you very much @remkop !

**Comment by remkop** [comment]
This is a good question to put on StackOverflow to build a knowledge base for other users. Do you want to do this or shall I do it?

**Comment by remkop** [comment]
I created this StackOverflow question and answer: https://stackoverflow.com/questions/52928235/picocli-how-to-show-header-banner-at-all-times/52928236#52928236
