### ISSUE TITLE
Interactive shell with hierarchy navigation

### ISSUE THREAD

**Issue by DmitryAndreyeff** [remkop/picocli#520]
Hi! I'm looking for a way to build interactive shell for managing the configuration of a large system. The configuration has hierarchical structure, and I would like to provide user experience very similar to file system navigation where most used commands will be **ls** and **cd**. I would like to have autocompletion based on current "directory" content, and shell prompt to change dynamically to reflect current path in the hierarchy. Is this achievable with picocli?
Thanks!

**Comment by DmitryAndreyeff** [comment]
Thank you for the quick response! I will look into it.

**Comment by remkop** [comment]
@DmitryAndreyeff  Were you able to make progress? Do you have follow-up questions, or can this ticket be closed?

**Comment by DmitryAndreyeff** [comment]
Hi, I don't have questions for now. Thank you for assistance!

**Comment by bobtiernay-okta** [comment]
@remkop Having a lot of fun with this module 💯 !

One question though, why did you go with jline2 vs jline3? Was it a licensing concern?

**Comment by remkop** [comment]
JLine2 requires only Java5, like picocli. Also, I had the Completer code ready from my contributions to the Micronaut CLI. 

JLine3 requires Java 8. Planning to add a JLine 3 module later. 

If you feel like contributing a JLine 3-based Completer, we can add another module for JLine 3. Pull requests welcome!
