### ISSUE TITLE
Multi-value option overwriting

### ISSUE THREAD

**Issue by cebaa** [remkop/picocli#521]
This code:

```
class Params {
  @Option(names = "-a")
  private String a;

  @Option(names = "-b", split = ",")
  private List<String> b;
}

String[] args = new String[] {
   "-a", "10",
   "-a", "11",
   "-b", "20,21",
   "-b", "22,23",
};

Params params = new Params();

new CommandLine(params)
   .setOverwrittenOptionsAllowed(true)
   .parse(args);

System.out.println(params.a);
System.out.println(params.b);
```

prints:

```
11
[20, 21, 22, 23]
```

The docs only mention single-value (`-a` above) overwriting and it's working as expected. There doesn't seem to be a way to apply the same to multi-value (`-b` above) options.

**Comment by remkop** [comment]
The behavior you’re seeing is the expected behavior. 

If you want to restrict the elements stored in the list you can use an annotated setter method and implement logic to keep only the elements that were added last. That could look something like this:

```
private List<String> b = new ArrayList<>();
private int count = 0;

@Option(names = "-b", split = ",")
void setB(List<String> newValues) {
    // newValues is the full list 
    count += b.size();
    b = newValues.subList(count, newValues.size());
}
```

**Comment by remkop** [comment]
@cebaa Did this answer your question?

**Comment by cebaa** [comment]
@remkop 

To preface, all the below is just my 2c, since it does look a bit dismissive of the above, but just trying to explain my view and hopefully help the project, so don't get me the wrong way if possible :)

"The behavior you’re seeing is the expected behavior." I cannot agree with calling this "expected". I specified I want to allow overwriting and I expect parameters to be overwritten.

I understand your angle coming from the current design, but I would call this a limitation of the current approach, rather than an expected result. There's a non-obvious distinction between "overwrite single" vs. "overwrite list" parameters. Easier to miss as well, since `-a` works, only `-b` doesn't.

At worst, I feel this should be clearly documented. I am not the only one surprised by this.

A better approach IMHO would be to default to overwriting everything and, if it's desired, to have something along the lines of `setOverwrittenListOptionsAllowed` (defaulting to `true`) for allowing the current approach to be simulated by setting it to `false`.

The best would be to add a per-`@Option` specifier that can tweak this on top of the previous options.

Obviously, idk if all this is warranted given how the framework is used in the wild, so perhaps all is moot from that standpoint... :)

Your setter example needs to be modified for example as such (`subList` returns a view, so it throws a `java.util.ConcurrentModificationException` when `setB` is called for the 2nd time):

```
class Params2 {
  @Option(names = "-a")
  private String a;
  
  private List<String> b = new ArrayList<>();
  private int bCount = 0;

  @Option(names = "-b", split = ",")
  void setB(List<String> newValues) {
    bCount += b.size();
    b = new ArrayList<>(newValues.subList(bCount, newValues.size()));
  }      
}
```

I would not however call this a good solution, it's a hack. With more options, it'd be a mess compared to a very-readable original `Params` class.

When using a command line parsing framework, the one thing the users should definitely not worry about too much is the internals of parsing the command line.

**Comment by remkop** [comment]
Closing this issue. 
The current API supports the use case (via the `@Option`-annotated setter method).
