### ISSUE TITLE
require subcommand

### ISSUE THREAD

**Issue by alfonz19** [remkop/picocli#529]
I have defined command and several subcommands, but it seems, that subcommand is just optional. Is there/could there be a way, how to flag, that selection of some subcommand is required?

**Comment by remkop** [comment]
One way would be to show an error if the top-level command is invoked without subcommand:


```java
@Command(name = "top", subcommands = {Sub1.class, Sub2.class})
class TopCommand implements Runnable {
  public void run() {
    System.err.println("Please invoke a subcommand");
    new CommandLine(new TopCommand()).usage();
  }

  public static void main(String[] args) {
    CommandLine.run(new TopCommand(), args);
  }
}

@Command(name = "sub1)
class Sub1 implements Runnable {
    public void run() {
        System.out.println("All good, executing Sub1");
    }
}

@Command(name = "sub2)
class Sub2 implements Runnable {
    public void run() {
        System.out.println("All good, executing Sub2");
    }
}

**Comment by alfonz19** [comment]
Yes, thanks! (sorry for delay, I had to verify it).

But to proceed with this topic:
• if someone specified subcommands say via annotation, doesn't it mean, that one of them should be used?
• also there is some state, which I don't undestand: if I do what you adviced, I'd expect, that when subcommand is not specified, it will produce failure. But say when I pass "-V" and no command, it succeed. That's great, that's what it should do, but it's not what I expected. However if you pass another option of top command, it will fail. This brings me to idea, that there should be flag: fail on missing command. Which would be saving lots of boilerplace code when there is a hierarchy of commands.
• also it feels little bit weird, that I'm in middle of CommandLine processing and creating new instance, and I'm in TopCommand runnable and creating another one to print it's usages...

**Comment by remkop** [comment]
> if someone specified subcommands say via annotation, doesn't it mean, that one of them should be used?

Not necessarily, there may be command hierarchies where it is valid to invoke the top-level command.

> when I pass "-V" and no command, it succeed. That's great, that's what it should do, but it's not what I expected.

The `--version` and `--help` options are special: if these options are specified, the normal validation for missing required options etc is bypassed. Also, the `run` method is not invoked. See https://picocli.info/#_help_options for details. 

> there should be flag: fail on missing command. Which would be saving lots of boilerplace code when there is a hierarchy of commands.

I'm not sure I understand. Can you elaborate?

> it feels little bit weird, that I'm in middle of CommandLine processing and creating new instance, and I'm in TopCommand runnable and creating another one to print it's usages...

You are right, sorry. You can use `this` instead of creating a new `TopCommand` instance:

```
class TopCommand implements Runnable {
  public void run() {
    System.err.println("Please invoke a subcommand");
    new CommandLine(this).usage();
  }
```

**Comment by alfonz19** [comment]
Got it.
To elaborate on that "failOnMissing": you said, that there hierarchies, where it might be valid to skip command. There might be hierarchies, where it's invalid. But I doubt, that there will be hierarchy, where some of defined command will be optional and some not. If that's true, then there can be annotation option say "oneOfSubCommandRequired" with boolean value, and generated behavior as we're adding here with .usage() call.

btw. I know it's not related to this topic, but if we're already speaking I don't want to create separate thread for that — is it possible to have dependency between options? If `this` is specified, `that` has to be also? Or this is subject of manual coding? Thanks.

**Comment by remkop** [comment]
Soon: dependencies between options in on the TODO list: https://github.com/remkop/picocli/issues/295

I hope to be able to get to it in picocli 3.8 (but no guarantees). Until then applications will need to manually take care of this.

**Comment by remkop** [comment]
I've created this StackOverflow question to help build a knowledge base for other users: https://stackoverflow.com/q/53043937/1446916

**Comment by remkop** [comment]
@alfonz19  Let me know if you have any follow-up questions. If not, can this ticket be closed?

**Comment by alfonz19** [comment]
thanks for everything!
