### ISSUE TITLE
Optional interactive

### ISSUE THREAD

**Issue by Zethson** [remkop/picocli#536]
Hi,

I'm having the following issue: 
I have a password CommandLine.Option, which is currently interactive -> thus it asks the user for his password. 
However, I would like to skip the interactive question, if a password was already provided.

Is it possible to consume the interactive request?

**Comment by remkop** [comment]
@Zethson  At the moment picocli does not support this. There is a [section](https://picocli.info/#_interactive_password_options) in the manual about combining interactive use with non-interactive use.

Basically, if you need this, one idea is to have separate options, like `--password:hidden` for the interactive option, and `--password:clear` that accepts the password in cleartext as an option parameter on the command line. The latter is also suitable for batch scripts.

**Comment by Zethson** [comment]
I see, thanks!
I still would like to kindly request this feature. 

It's more or less the only thing that I miss from [Click](https://click.palletsprojects.com/en/7.x/) .

**Comment by remkop** [comment]
Understood. Not sure when I'll get to it.
I'm a bit worried about introducing ambiguity, for example:

```java
class App {
    @Option(names = "--password", interactive = true)
    String password;

    @Parameters
    String[] otherParams;
}
```

Now, if the end user specifies some input:

```
<command> --password aaa bbb ccc
```
Currently picocli will interactively ask for a password and put `aaa`, `bbb` and `ccc` in the `otherParameters` array.

This will change after this feature request is implemented: for the same input, the `aaa` parameter will now be interpreted as a password parameter value. Not sure yet how to deal with this...

**Comment by Zethson** [comment]
What Click does is that every parameter that is NOT passed and labeled as interactive is prompted. Everything that was passed is not going to be prompted.
<code>  --password aaa bbb ccc</code> 
is going to set aaa as value for password   
 
<code>  <command> aaa bbb ccc</code>
will open the interactive prompt and ask for the password, since no value for password was passed.

**Comment by remkop** [comment]
I guess I will either have to live with potentially breaking existing applications, or introduce some extra flag that needs to be set for picocli to accept values following `--password` as the password value.

**Comment by Zethson** [comment]
I'm afraid yes.

I prefer the potentially breaking change, but this is of course up to you.

Thanks!

**Comment by remkop** [comment]
JCommander actually implemented this feature request:

* https://github.com/cbeust/jcommander/issues/70
* https://github.com/cbeust/jcommander/issues/195
* https://github.com/cbeust/jcommander/issues/333

But that caused an issue in certain use cases (application did _not_ want to allow users to specify the password in plain text as an option parameter):

* https://github.com/cbeust/jcommander/issues/452

One possible solution for this last use case is to use `arity` to control whether option parameters are allowed: by default the arity for an `interactive = true` argument would be `0..1`, meaning end user may specify it as an option parameter, or may omit it and get prompted on the command line. 

If the application author defines the option with `arity = "0"`, picocli would not allow end users to specify it as an option parameter and always prompt for a value on the console.

**Comment by remkop** [comment]
@Zethson, it took a while, but this has finally been implemented. By default, interactive options now have `arity = "0"` (meaning they won’t consume any command line arguments but prompt the user for input instead), but if the option is defined with `arity = "0..1"`, it may optionally consume a parameter from the command line arguments. 

I’ll release 3.9.6 with this change soon.

**Comment by Zethson** [comment]
Amazing. Thank you for your hard work.
