### ISSUE TITLE
Path arguments include quotation marks

### ISSUE THREAD

**Issue by piegamesde** [remkop/picocli#540]
In my command line, I have something like this:

		@Option(names = { "--output", "-o" },
				defaultValue = "./",)
		private Path				output;
		@Parameters(index = "0")
		private Path				input;

And I call it like this:

		File out1 = ...;
		MainClass.main("-o=\"" + out1 + "\"", "\"./path/to/some/folder/\"");

This was no problem in version `3.3.0`, but since the upgrade to version `3.7.0` it includes the quotation marks into the file path, so that instead of `./path/to/some/folder/` I get `"./path/to/some/folder/"`. This is wrong because `input.resolve("foo")` will lead to `"./path/to/some/folder/"/foo` which will throw an exception.

**Comment by remkop** [comment]
Hi @piegamesde, yes, from v3.7.0 the default behaviour is to leave quotation marks instead of trimming them, but this is [configurable](https://picocli.info/#_quoted_values).

The `CommandLine.setTrimQuotes(boolean)` method allows you to switch this off.

**Comment by piegamesde** [comment]
Thank you, I wouldn't have found this option by myself. At first, this option was counter-intuitive to me, but then I remembered that the trimming is done by my Shell: `"/path with/spaces"` will automatically be trimmed. So when I called the main directly with the same arguments this went wrong.

**Comment by remkop** [comment]
Glad to hear it is resolved. Don't hesitate to let me know if any other issue.
Enjoy using picocli! :-)
