### ISSUE TITLE
Provide tools to help applications migrate from commons CLI/JCommander to picocli

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#542]

**Comment by Fernal73** [comment]
If tools are not ready, it would help to have documentation mapping JCommander classes to Picocli ones. A migration document would be useful.

**Comment by remkop** [comment]
I wrote [something like that](https://picocli.info/migrating-from-commons-cli.html) for Commons CLI.

Would you be willing to help write something for JCommander?

**Comment by Fernal73** [comment]
I'm afraid that's not possible.

What I could do is transcribe the JCommander examples I've used here to
Picocli.

https://github.com/Fernal73/LearnJava/tree/master/JCommander

I needed to know how difficult or easy it would be. My feeling is that it
isn't that hard since annotations are key in both.

Hence, a mapping.

**Comment by remkop** [comment]
There may be some difference in dealing with quotes (JCommander used to strip quotes by default, I think that was changed in later versions).

Another difference is that JCommander splits comma-separated option parameters automatically into list elements where picocli requires `split = ","` (this is by design). (Thanks to feedback from @juddgaddie on #738).

JCommander has its own syntax for `@-files`. This difference is [documented](https://picocli.info/#AtFiles) in the picocli user manual.

**Comment by Fernal73** [comment]
Thank you very much for your response.
Yes, Picocli now supports JCommander-like @files. I read that part of the documentation.

I'm more interested in whether properties files and overriding via command-line parameters is allowed. JCommander supports properties files but the current implementation does nothing with the values read in.

https://github.com/pmd/pmd/issues/2087

**Comment by remkop** [comment]
Is this what you are looking for?

https://picocli.info/#_default_provider
(See also the example link at the bottom of that section.)

**Comment by remkop** [comment]
This wiki page also documents some differences:

https://github.com/remkop/picocli/wiki/picocli-vs-JCommander

**Comment by Fernal73** [comment]
Yes, I've found that. I'm yet to test it to check if its values are
overridable via the command line i.e., using CommandLine.parseArgs.

The documentation says nothing about overriding parameter values
specifically single-valued parameters.

**Comment by remkop** [comment]
> The documentation says nothing about overriding parameter values specifically single-valued parameters.

Here is how it works: Options and positional parameters are first initialized to their default values,, then if the user specified a value on the command line, it overwrites the default value.

> Are you expecting the application programmer to do that instead? 

Sorry, I don't understand the question. Expecting the application programmer to do what?

>  the framework can easily override these default values from the file via the parse mechanism.

Yes, that is exactly what happens.

Ah hang on, I guess you mean the constructors. Yes, perhaps I should remove the other constructors (other than the default non-argument constructor) to avoid confusion.

**Comment by Fernal73** [comment]
I understand very well how it bloody damn well works. And I'm not in the mood right now to test whether your tool works as I expect it to work. I expect the annotation to allow me to specify a file path, if I need to change the default. My only concern would be what would happen if I need an additional parameter to specify a different property file from the command line. That would involve jumping through a few hoops. But that's the price of providing that flexibility.

**Comment by remkop** [comment]
I see. The annotations will only let you specify a class. It is possible to specify a file path programmatically, for example:

```java
public static void main(String[] args) {
    CommandLine cmd = new CommandLine(new MyCommand());
    File defaultsFile = new File("path/to/config/file.properties");
    cmd.setDefaultValueProvider(new PropertiesDefaultProvider(defaultsFile));
    cmd.execute(args);
}
```

Note that the default provider must be set prior to parsing command line arguments, so if you need a way to set the path to the defaults file from a command line parameter, we would need some kind of two-pass approach, where the first pass just detects the path to the defaults file, and the second pass would parse the remaining parameters. This sounds a bit complex in my opinion...

An alternative is to allow users to specify the path to the defaults file in a system property, something like this:

```java
    CommandLine cmd = new CommandLine(new MyCommand());
    String path = System.getProperty("command-defaults", "path/to/config/file.properties");
    File defaultsFile = new File(path);
    cmd.setDefaultValueProvider(new PropertiesDefaultProvider(defaultsFile));
    cmd.execute(args);
```

Would that meet your requirements?

**Comment by Fernal73** [comment]
I agree. It's complex.
Once it's coded, however, it will be transparent to the user.

E.g.,
https://metacpan.org/pod/perlcritic#OPTIONS

Perl-critic allows the user to specify a different profile outside of its
default one.

**Comment by remkop** [comment]
Even if arguments were parsed first and only the unset values were obtained from the provider, that is not sufficient: the library has no way of knowing which of the command line arguments to use to create a default value provider. This still needs to be done in the application.

That said, I took a stab at it and the complexity of a 2-pass approach turns out to be managable.
I uploaded some code to `picocli-examples`: [TwoPass.java](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/defaultprovider/TwoPass.java). Please take a look.

**Comment by Fernal73** [comment]
That's great. This is a great workaround. 
My approach would have been to annotate the profile file parameter. And work from there. You're right. That would have involved major changes in the API. Thank you for your patience.

**Comment by remkop** [comment]
I’m considering including `PropertiesDefaultProvider` in picocli 4.1. It just needs to be productionized with tests and documentation.

**Comment by Fernal73** [comment]
https://spotbugs.readthedocs.io/en/stable/running.html

"-userPrefs edu.umd.cs.findbugs.core.prefs:
Set the path of the user preferences file to use, which might override some of the options above. Specifying userPrefs as first argument would mean some later options will override them, as last argument would mean they will override some previous options). This rationale behind this option is to reuse SpotBugs Eclipse project settings for command line execution."

There's also this way of using a profile file.

**Comment by remkop** [comment]
Thanks for the additional use case. 
I raised https://github.com/remkop/picocli/issues/868 for this. It should make it in the next release (4.1).

**Comment by Fernal73** [comment]
https://prettier.io/docs/en/cli.html

Another tool, this time a formatter, that handles config files differently.

**Comment by remkop** [comment]
I think this issue can be closed. Good discussion, thank you for that!
