### ISSUE TITLE
Gradle Plugin for picocli-codegen

### ISSUE THREAD

**Issue by helpermethod** [remkop/picocli#548]
Wouldn't it be nice to have a Gradle plugin which generates the config? Maybe using something like https://github.com/classgraph/classgraph to automatically discover classes annotated with `@Command`?

I would gladly help out with this.

**Comment by remkop** [comment]
A Gradle plugin sounds awesome. I have some work in progress on a branch to add an annotation processor to the `picocli-codegen` module. This would analyse the code _at compile time_ and build a `CommandSpec` model. Subclasses of this annotation processor can then take this model and generate documentation, source code, configuration or other files. Planning to merge this to master in a few days.

I had not considered integrating this with Gradle as a plugin, that sounds pretty cool!

**Comment by helpermethod** [comment]
Such a plugin could be based on https://github.com/palantir/gradle-graal which greatly simplifies integration with Graal.

**Comment by bootstraponline** [comment]
> I have some work in progress on a branch to add an annotation processor to the `picocli-codegen` module.

does that remove the need for reflection? I have a `picocli` app that only compiles with graal if reflection isn't used.

**Comment by remkop** [comment]
> does that remove the need for reflection?

Potentially, yes. Some early thoughts on that topic are here: https://github.com/remkop/picocli/issues/539

**Comment by juddgaddie** [comment]
Is this theoretically resolved now with the annotation processor implementation?

**Comment by remkop** [comment]
@juddgaddie You may be right. The nice thing about the annotation processor is that it works for plain javac as well as Gradle and Maven. 

That said, some more work is required for Groovy and Kotlin. 
I need to take another look at using the Micronaut visitor API for this: https://github.com/micronaut-projects/micronaut-core/issues/739#issuecomment-430608376

**Comment by remkop** [comment]
Closing as this issue is superseded by the annotation processor.
