### ISSUE TITLE
Ignoring java -D options

### ISSUE THREAD

**Issue by KasperJanssens** [remkop/picocli#568]
Hello,

I cannot seem to find out how to have picocli's commandline parsing coexist with the java options (-Dxxx.yyy). For example, when I try to pass -Dlog4j.configurationFile=log4j.properties, picocli intervens telling me that it does not know that option. What is the best way forward for this? I thought I could get somewhere with the Unmatched stuff in picocli but I cannot seem to get that to work.

Edit: nevermind, I completely overlooked this

`commandLine.setUnmatchedArgumentsAllowed(true);`

I suppose that this is the correct way forward.

**Comment by remkop** [comment]
The problem should not happen if you run your command like this:

```
# pass system property to the JVM
java -Dprop=value com.your.package.MainCommand -a=b
```

So I am guessing that instead your script was executing something like this:

```
# pass system property-like option to your main class
java com.your.package.MainCommand -Dprop=value -a=b
```

If the latter is how things are invoked, I guess you have to handle them in your program.
This can be done with very little code though. For example:

```java
class MainCommand implements Runnable {

	@Option(name = "-a")
	String aOption;
	
	@Option(name = "-D", description = "System properties to pass to the JVM")
	void setProperty(Map<String, String> values) {
		for (String key : values.keySet()) {
			System.setProperty(key, values.get(key));
		}
		// in Java 8, this can be a one-liner:
		// values.entrySet().stream().forEach(e -> System.setProperty(e.getKey(), e.getValue()));
	}

	public static void main(String... args) {
		CommandLine.run(new MainCommand(), args);
	}

    public void run() { // business logic...
	}
}
```

**Comment by remkop** [comment]
The problem should not happen if you run your command like this:

```
# pass system property to the JVM
java -Dprop=value com.your.package.MainCommand -a=b
```

So I am guessing that instead your script was executing something like this:

```
# pass system property-like option to your main class
java com.your.package.MainCommand -Dprop=value -a=b
```

If the latter is how things are invoked, I guess you have to handle them in your program.
This can be done with very little code though. For example:

```java
class MainCommand implements Runnable {

    @Option(name = "-a")
    String aOption;
    
    @Option(name = "-D", description = "System properties to pass to the JVM")
    void setProperty(Map<String, String> values) {
        for (String key : values.keySet()) {
            System.setProperty(key, values.get(key));
        }
        // in Java 8, this can be a one-liner:
        // values.entrySet().stream().forEach(e -> System.setProperty(e.getKey(), e.getValue()));
    }

    public static void main(String... args) {
        CommandLine.run(new MainCommand(), args);
    }

    public void run() { // business logic...
    }
}
```

**Comment by remkop** [comment]
If you don't want the `-D` option to show in your usage help, you can declare it with `hidden = true`:

```
@Option(name = "-D", hidden = true)
void setProperty(Map<String, String> values) { // ...
```

**Comment by KasperJanssens** [comment]
You are right, I should have put the java options after the java command. Thanks for the extensive clarification!
