### ISSUE TITLE
Improve ANSI heuristics: add support for ConEmu, ANSICON, NO_COLOR and CLICOLOR

### ISSUE THREAD

**Issue by bbottema** [remkop/picocli#581]
I'm running ConEmu on Windows 10, but Ansi colored mode won't be turned on when using Ansi.AUTO, while Ansi.ON works just fine. How can I remedy this?

**Comment by remkop** [comment]
Looking at [this list](
https://conemu.github.io/en/ConEmuEnvironment.html#List_of_environment_variables_set_by_ConEmu), especially the `ConEmuANSI` variable looks relevant. Is this variable defined and what is its value?

**Comment by bbottema** [comment]
The following prints out "enabled"
```
if "%ConEmuANSI%"=="ON"  echo Enabled
if "%ConEmuANSI%"=="OFF" echo Disabled
```

**Comment by remkop** [comment]
Thank you for the information. 
I’ve been doing some research. 
Can you also give the value of the `CLICOLOR` and `CLICOLOR_FORCE` environment variables? These may be implemented as dynamic variables, so they won’t show up in the list printed by the `set` command. Instead please verify the value with:

```
echo %CLICOLOR%
echo %CLICOLOR_FORCE%
```

Thank you for the help!

**Comment by bbottema** [comment]
Both empty.

**Comment by remkop** [comment]
Cool, thanks!
I’m thinking to make the following enhancements for picocli 3.9:
(In addition to the existing Ansi enablement logic)

* disable Ansi when `CLICOLOR == 0` or `ConEmuANSI == OFF`
* enable Ansi  when `CLICOLOR == 1` or `ConEmuANSI == ON` or when `ANSICON` is defined 
* force Ansi ON when `CLICOLOR_FORCE == 1`

This should add ANSI color support for both ConEmu and AnsiCon, as well as add support for @jhasse ‘s https://bixense.com/clicolors/ proposal.

**Comment by remkop** [comment]
I’ll also add support for `NO_COLOR`: https://no-color.org/

**Comment by remkop** [comment]
(Note to self: read http://tldp.org/HOWTO/Text-Terminal-HOWTO-16.html )

**Comment by bbottema** [comment]
man, what a mess...

**Comment by remkop** [comment]
I've pushed a commit to master to improve picocli's heuristics for determining whether it should emit ANSI escape codes or not.

This should address the issue on your system. Can you verify?

I'm still keeping the ticket open because I'm planning to add more unit tests for this.

**Comment by bbottema** [comment]
Verified, it solves the problem in my situation.

**Comment by remkop** [comment]
Thanks for the confirmation.

Yes, planning to do a release within about a week (see [3.9 milestone](https://github.com/remkop/picocli/milestone/43)).
When exactly will depend a bit on how much more time it will take to [improve the test coverage](https://github.com/remkop/picocli/issues/571)...

**Comment by bbottema** [comment]
Hmm, what about IntelliJ? With AUTO it's turned off, but with ON it works fine. Is there a way of detecting ANSI support without manually configuring system variables?

**Comment by jhasse** [comment]
No, not that I know of. The idea would be that all consoles which support colors but don't are a tty, set `CLICOLOR_FORCE` to 1.

**Comment by remkop** [comment]
I created this ticket for IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-205699
