### ISSUE TITLE
Add documentation for generating autocompletion script during the build

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#584]
Based on @bobtiernay-okta 's example in #582.

**Comment by thekalinga** [comment]
@remkop Are there instructions for generating these during gradle build?

**Comment by thekalinga** [comment]
I could make this work for gradle (with kotlin DSL) by using following configuration

```kotlin
task<JavaExec>("generateShellCompletion") {
    dependsOn("assemble")
    description = "Generate shell completion"
    mainClass = "picocli.AutoComplete"
    classpath = sourceSets.main.get().runtimeClasspath
    args = listOf("--force", "--completionScript", "build/<command_app_name>_completion.sh", "com.path.to.MainCommand")
}
```

**Comment by thekalinga** [comment]
@remkop Would help if this becomes part of the documentation so unlike me, others will save some time.

Thanks.

**Comment by remkop** [comment]
Hello @thekalinga, are you aware of this page? https://picocli.info/autocomplete.html
It is linked from the [1.1 Overview](https://picocli.info/#_overview) section:

> Picocli-based applications can have [command line TAB completion](https://picocli.info/autocomplete.html) showing ...

The AutoComplete documentation section [2.5 Distribution](https://picocli.info/autocomplete.html#_distribution) mentions the the built-in `picocli.AutoComplete.GenerateCompletion` command and shows how to install it and how users can use it to install completion for your command by sourcing the output:

> `source <(mycommand generate-completion)`

Is this what you were looking for?

If not, I would appreciate it if you could create a new ticket. 😅 

Additionally, if you would like your effort to be useful to others, can you provide a pull request for the documentation?
