### ISSUE TITLE
picocli.AutoComplete should allow specifying the IFactory implementation

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#585]
Currently it isn't possible to create `@Command` objects without a no-arg constructor since `picocli.AutoComplete` is hardcoded to use the default `IFactory` implementation. This means it isn't possible to use constructor injection to set dependencies as `final` fields.

Possibilities include specifying the `IFactory` class name as an argument to the tool or using the Java service loader mechanism.

**Comment by remkop** [comment]
I pushed a change that implements this request to master.
This is the new option:
```
"  -c, --factory=<factoryClass>%n" +
"                             Optionally specify the fully qualified class name of%n" +
"                               the custom factory to use to instantiate the command%n" +
"                               class. When omitted, the default picocli factory is%n" +
"                               used.%n" +
```
Can you verify?

**Comment by bobtiernay-okta** [comment]
Sure thing. Is it possible to do this via a build artifact or would I need to do this locally?

**Comment by remkop** [comment]
The Travis continuous integration build hats are not published I think. You’ll probably need to build locally.

**Comment by bobtiernay-okta** [comment]
Confirmed this worked:

```
java -cp picocli-3.9.0-SNAPSHOT.jar:uber.jar picocli.AutoComplete -c runtime.Factory commands.Commands
```

Might want to add a comment in the docs at some point that the factory itself needs to have a no-arg constructor.

Thanks for your help here!

**Comment by remkop** [comment]
Good idea. Thanks for the confirmation!
