### ISSUE TITLE
Support quoted map keys with embedded '=' characters

### ISSUE THREAD

**Issue by pubudu91** [remkop/picocli#594]
I have the following map:
```Java
@CommandLine.Option(names = "-e")
private Map<String, String> runtimeParams = new HashMap<>();
```
If I give the key/val pair as follows, it splits the pair at the first "=" character it encounters. 
`$ <cmd> -e a=b=c=foo`

Is there a way to indicate to the parser from where to split this pair? For example, I was expecting something like the following to work:
`$ <cmd> -e "a=b=c"=foo`

In both of the above cases, the pair is split as `a` and `b=c=foo`.

**Comment by remkop** [comment]
This has been pushed to master. Can you verify?

**Comment by remkop** [comment]
Note: During testing I found some edge cases when the option has a `split` regex:

```java
class App {
  @Option(names = "--option", split = ",")
  Map<String, String> map;
}
```
Some examples:
```
# gives this map { "k1": "v1", "k2": "v2" }
--option=k1=v1,k2=v2

# gives { "k1": "v1 w1", "k2": "v2 w2" }
--option="k1=v1 w1","k2=v2 w2"

# not yet supported (needs #595)
--option="'k1=key'=v1 w1","'k2=key'=v2 w2"
```
It is not yet possible to combine quoted keys (with embedded '=') with quoted key-value pairs.

I raised https://github.com/remkop/picocli/issues/595 to support nested quoting in the future.

**Comment by pubudu91** [comment]
Thanks for the prompt response and solution! I tested it and it's working. :D I need the key with the quotes, so no worries with the problems with trimming.

**Comment by remkop** [comment]
Thanks for the confirmation!
