### ISSUE TITLE
codegenerator does not appear to run when program run in spinnaker pipeline

### ISSUE THREAD

**Issue by farrukhnajmi** [remkop/picocli#597]
I run my java main program with args using gradle application plugin's run task. The program uses picocli to parse command line args. This works fine when run in my Dev environment using following command:

```
./gradlew  run --args="-ahttp://foo.com/bar -dmydeviceid"
```

It also runs fine when I ssh into a docker container for my apps docker image. However, if I run the same Gradle run task in Spinnaker pipeline Run Job stage with same docker image it does not work. Log statements show that arguments are received by program correctly but are not processed by picocli. I am guessing it is because the code generator for picocli is not running in the Run Job of Spinnaker pipeline for some reason. 

Can someone please tell me:

- How is the code generator run normally when the program executes?
- What could cause the code generator to not run in some environment?
- What can I do to debug / fix / workaround this problem?

Here is a snippet of my program:

```
@CommandLine.Command(description = "Deploys apks to specified target device.",
        name = "apk-deployer-cli", mixinStandardHelpOptions = true, version = "apk-deployer-cli 1.0")
public class ApkDeployerCli implements Callable<Void>  {

    @SuppressWarnings("unused")
    @CommandLine.Option(names = {"-a"}, required = false, description = "The url to an apk to deploy to target device. ")
    String[] apkUrls;

    @SuppressWarnings("unused")
    @CommandLine.Option(names = {"-d"}, required = false, description = "Device id for device to deploy to")
    String deviceId;


    public static void main(String[] args) {
        CommandLine.call(new ApkDeployerCli(), args);
    }

    @Override
    public Void call() {
        ... do some stuff. Does not work because args are not parsed into member vars ...
        return null;
    }

}
```

**Comment by remkop** [comment]
@farrukhnajmi Can this ticket be closed?

**Comment by farrukhnajmi** [comment]
First thanks for a great project.

The underlying issue remains unresolved. I found a workaround.

Yes gradle 4.9 supports the run option and all works well in command line as well as when I ssh into docker container created by same image. The problem only happens in a spinnaker pipeline Run job with same image.

Since I do not have a minimal test case to reproduce the problem feel free to close the issue.

**Comment by remkop** [comment]
Did you have a chance to try the `-Dpicocli.trace=DEBUG` system property? That may give some insight on whether the problem is in picocli or in another layer of the stack.
