### ISSUE TITLE
i18n with subcommands

### ISSUE THREAD

**Issue by deining** [remkop/picocli#603]
I played around with i18n of subcommands and came across the follwing issue:

I successfully implemented i18n for the subcommand, if I issue
MyCommand help subcommand, I'm getting:

```
Usage: MyCommand subcommand ...
Localized usage.descriptionHeading for subcommand from resource bundle
...
```
So far, so good.

I also implemented i18n for the parent command, if I issue

> MyCommand help

 I'm getting:

```
Usage: MyCommand [-hvV] [COMMAND]
Commands:
  subCommand   
```

Note that the description for subcommand is blank.
Rather than having a blank description, I would like to see the localized description of the subcommand here:

```
Usage: MyCommand [-hvV] [COMMAND]
Commands:
  subCommand   Localized usage.descriptionHeading for subcommand from resource bundle
```
I can remedy the situation by adding a description to the @Command annotation of the subcommand, but that's not really what I want since this description is not localized and interferes with the description in the resource bundle. 

```
@Command(description = "Duplicate subcommand description (no i18n)", name = "xxx", resourceBundle = "my.package.bundleName")
```

Can this be improved? Any thoughts on this are appreciated.

**Comment by remkop** [comment]
Thank you for raising this issue. I’m away from my PC, will take a look as soon as I can. 
Would it be possible for you to provide a failing test to help me reproduce the problem?

**Comment by deining** [comment]
Here comes a simple failing test:

```
package test;

import static org.junit.Assert.*;
import org.junit.Test;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import java.util.Map;

public class HelpSubcommandsTest {

    @Test
    public void testShowDefaultValuesDemo() {

        CommandLine commandLine = new CommandLine(new ParentCommand());
        commandLine.addSubcommand("sub1", new SubCommand1());
        commandLine.addSubcommand("sub2", new SubCommand2());

        Map mapSubcommands =  commandLine.getSubcommands();
        CommandLine cmdSubcommand = (CommandLine) mapSubcommands.get("sub1");
        String usageMessageParent = commandLine.getUsageMessage();
        
        assertEquals(String.format("Usage: parent [COMMAND]%n" +
                                   "Commands:%n" +
                                   "  sub1  annotation text%n" +
                                   "  sub2  bundle text%n"),
                 usageMessageParent);
    }
}

@Command( name="parent" )
class ParentCommand {
}

@Command(name = "sub1", description = "annotation text")
class SubCommand1 {
}

@Command(name="sub2", resourceBundle = "test.Bundle")
class SubCommand2 {
}
```

Bundle.properties:

`parent.sub2.usage.descriptionHeading=bundle text`

Does this help?

**Comment by remkop** [comment]
I found the cause. The resource bundle key (`usage.descriptionHeading`) is incorrect and should be one of these:

```
parent.sub2.usage.header=bundle text
# or
parent.sub2.usage.description=bundle text
```

By the way, if your application does not use a single resourcebundle for all commands, you don't need to qualify the keys with the command names, so you could do this (but fully qualified keys is fine of course):

```
usage.header=bundle text
# or
usage.description=bundle text
```

The test you provided (thanks for that!) will pass with any of the above resource bundle keys.

**Comment by remkop** [comment]
Can you confirm that the above fixes the issue for you?

**Comment by deining** [comment]
Yes, everything looks great now, the issue is fixed..
Thanks for for guidance, I appreciate that!

**Comment by remkop** [comment]
Glad to hear that!
Enjoy!
