### ISSUE TITLE
Defining "spring.config.location" causes picocli parser to fail.

### ISSUE THREAD

**Issue by alistairrutherford** [remkop/picocli#604]
The Spring Boot parameter 'spring.config.location' allows you to specify an alternative location for your application.properties file. When I attempted to pass this along with other picocli define parameters it causes the parser to fail and I get help message. The only way I could get this to work was to define the 'spring.config.location' as an optional parameter. I can see why you wouldn't want to add special handling for spring boot for this so you might want to put a note into the documentation.

**Comment by remkop** [comment]
Thanks for raising this!
Improving Spring support is on the todo list so this is very useful!

My first thought is that defining `--spring.config.location` as a (non-required) option in the application is a good workaround. You may consider defining this as a “hidden” option if you don’t want this option to appear in the usage help message. 

I’ll probably add a Spring Integration section to the user manual. Any other things that should be mentioned in this section?

**Comment by remkop** [comment]
Would you mind sharing a simplified version of your code to show how to integrate picocli-based commands with Spring?

**Comment by remkop** [comment]
@alistairrutherford Would you mind sharing (a potentially simplified version of) your code to show how to integrate picocli-based commands with Spring?

**Comment by alistairrutherford** [comment]
In order the allow the Spring Boot application to accept the "spring.config.location" you simply add it to your Callable element. This will allow Spring boot to pick it up and stop picocli rejecting an unknown parameter.

`	@Option(names = { "--spring.config.location"}, paramLabel = "Config File", description = "the target config file", required=false, hidden=true)
	private String springConfigLocation;
`
You would follow this pattern for any other Spring Boot parameter you required.

**Comment by remkop** [comment]
Perfect, thank you!

**Comment by remkop** [comment]
For the next release, I updated the user manual: Dependency Injection is now a top-level section, with subsections for Guice, Spring Boot and Micronaut.

I used your code to create the Spring Boot example, and mentioned the `--spring.config.location` tip.
Can you verify?

If you run `gradlew ascii` the updated user manual is generated in `build/docs/html5/index.html`.

**Comment by alistairrutherford** [comment]
I reviewed the documentation section and it's looks fine. Good job.

**Comment by remkop** [comment]
Thanks for the confirmation!
