### ISSUE TITLE
defaultValue="false" + usageHelp/versionHelp=true does not cause detection of missing parameters

### ISSUE THREAD

**Issue by pietrobraione** [remkop/picocli#608]
Let us consider this situation:

    class App {
      @Option(names = "-h", usageHelp = true, defaultValue = "false")
      boolean helpAsked;

      @Option(names = "-V", versionHelp = true, defaultValue = "false")
      boolean helpAsked;

      @Parameters
      String compulsoryParameter;
    }

and the code:

    CommandLine commandLine = new CommandLine(new App());
    commandLine.parse(new String[0]);
    System.out.println("Success!");

The code prints "Success!", but it should raise MissingParameterException. By a superficial debugging of the picocli code it seems that the method `CommandLine.Parser.applyDefault(IDefaultValueProvider, ArgSpec, List<ArgSpec>)` does not set the correct default value to the usage and version help options when the `defaultValue` attribute is present in the `@Option` annotation. Thus picocli behaves as if the two options were active. By removing the `defaultValue` attributes everything works correctly.

**Comment by remkop** [comment]
Thank you for the bug report!
This has been fixed in master.
Can you verify?

**Comment by pietrobraione** [comment]
...give me some more time, I am too busy right now, but I will check it soon. Sorry for that and thank you for the quick fix.

**Comment by remkop** [comment]
No problem. Picocli 2.9.2 has been released which includes this fix, but please let me know if there’s any issue. Enjoy!
