### ISSUE TITLE
picocli does not seem to support - as a positional parameter

### ISSUE THREAD

**Issue by helpermethod** [remkop/picocli#613]
Hi,

I'm preparing some demo project for picocli and stumbled over some interesting, currently unsupported case.

Some shell commands, like `cat` accept `-` as a positional parameter

 ```sh
cat -
```

which means `cat` will read it's input from STDIN instead of a file.

But it seems picocli currently doesn't support such a case?

When I call

```java
@Command(name = "mst-cli", mixinStandardHelpOptions = true)
public class Cli implements Runnable {
    @Parameters(index = "0")
    private String json;
    @Parameters(index = "1")
    private String template;
    // more code
}
```

with the following parameters

    - ~/hello.mustache

picocli complains that the second parameter isn't set :/.

But 

    ~/data.json ~/hello.mustache

works.

**Comment by remkop** [comment]
I agree that `-` is a common argument like you describe and it should be possible to have a positional parameter in picocli take this value. I’ll look into it when I get to my PC.

**Comment by remkop** [comment]
Fixed in master.
Improved the heuristics for unmatched options: single-character arguments that don't exactly match options (like `-`) are now always considered positional parameters.

Please verify.

**Comment by remkop** [comment]
[Picocli 3.9.3](https://github.com/remkop/picocli/releases/tag/v3.9.3) has been released. This includes a fix for this issue.

Enjoy!

**Comment by helpermethod** [comment]
Thank you very much. Was very low on time the last few weeks so couldn't test the change :/.
