### ISSUE TITLE
showDefaultValues=true plus defaultValueProvider does not render defaultValues in usage help

### ISSUE THREAD

**Issue by sebthom** [remkop/picocli#616]
Specifying the default value of an option via an `IDefaultValueProvider` and setting `showDefaultValues = true` does not display the default vaulue as part of the standard usage help.

**Example Code:**
```java
@Command(name = "foo", //
    mixinStandardHelpOptions = true, //
    defaultValueProvider = FooCommandDefaultValueProvider.class, //
    showDefaultValues = true, //
)
public class FooCommand implements Runnable {

    public static class FooCommandDefaultValueProvider implements IDefaultValueProvider {
        @Override
        public String defaultValue(final ArgSpec argSpec) throws Exception {
            if ("DURATION".equals(argSpec.paramLabel())) {
                return "1200";
            }
            return null;
        }
    }

    @Option( //
        names = {"-d", "--duration"}, paramLabel = "DURATION", //
        description = { "The duration, in seconds." }, //
        arity = "1", //
        required = false //
    )
    protected Integer duration;
}
```

Only when I additionally set `@Option(showDefaultValue=Help.Visibility.ALWAYS)` for the respective option the value is displayed or when I explicitly set a default value directly via `@Option(defaultValue="1200")`

**Comment by remkop** [comment]
Thanks for the bug report! I'll take a look as soon as I can.

**Comment by remkop** [comment]
Fixed in master.
Please verify.

**Comment by sebthom** [comment]
@remkop thanks for the fast fix! where can I find the snapshot artifacts to verify the fix?

**Comment by remkop** [comment]
Can you build locally? I don’t publish snapshots but one of the Gradle tasks is to publish to the local Maven repo. You can then refer to the snapshot build in your project.

**Comment by remkop** [comment]
[Picocli 3.9.3](https://github.com/remkop/picocli/releases/tag/v3.9.3) has been released. This includes a fix for this issue.

Enjoy!
