### ISSUE TITLE
Feature suggestion: allow non-static inner classes to be subcommands of their outer class

### ISSUE THREAD

**Issue by ghost** [remkop/picocli#620]
For example, something like (not tested)

```
@Command(name="outer", subcommands={Inner.class})
public class Outer {

    @Command(name="inner")
    public class Inner {}
}
```

Currently this doesn't work, since `Inner` requires an instance of `Outer`. Would it be possible to make it so that when an instance of `Outer` is run via the `CommandLine` it will create an instance of `Inner` and use it as a subcommand? This would probably only really work if `Inner` is a subcommand of `Outer`, as opposed to a subcommand of a completely separate class. 

I know `Inner` could be made static, but then it loses the ability to use private variables of `Outer`, which is useful. Another possible way to do something like this (which I have not tested) might be to use a method as the command and have it run a new `Inner` object with all args it recieves. But even if that would work (and I'm not sure), it would be simpler to be able to be able to just put it in the `subcommands` section.

**Comment by remkop** [comment]
I think you can already accomplish this by using a factory that has a reference to the outer class.
Picocli has some tests that do this.
Please take a look at https://github.com/remkop/picocli/blob/master/src/test/java/picocli/InnerClassFactory.java

**Comment by PorygonZRocks** [comment]
That looks like it's what I need, thanks!

I'm thinking that with a loop checking `getEnclosingClass` it might be possible to make picocli automatically detect if a subcommand is an inner class of the main command, and automatically do something like that. If I did that and made a PR (no promises, but hopefully), would that be fine, or would you rather not have something like that in the default code?

**Comment by remkop** [comment]
I think the enclosing class may not be sufficient: we need a reference to an *instance* of the enclosing class. Or am I missing something?

**Comment by remkop** [comment]
So I don’t think this can be automatic but if I’m wrong please let me know. I always consider pull requests.

**Comment by PorygonZRocks** [comment]
Assuming there's a way to get the actual object from a `Command` (which I haven't checked), you should be able to run `getEnclosingClass` on the subcommand's object, and check it against the class of the command object. If they're the same, use the command object to create the subcommand. Sort of example of what I mean:

```
    Object cmdObject = cmd.getObject();
    Object subClass = sub.getClass();
    Object subObject = null;
    if (cmdObject.class == subClass.getEnclosingClass()) {
        subObject = subClass.getInstance(cmdObject);
    }
```
 Obviously the real code would probably look pretty different, but do you get what I mean?
