### ISSUE TITLE
new parse result handler

### ISSUE THREAD

**Issue by AlcaYezz** [remkop/picocli#624]
Hi, first thanks for your work on this tools.

I'm limited actually with handlers provided for "parseWithHandler".

I have a top command that should be executed to retrieve general option. And the last subcommand where the real action is done. In the middle there is some indirection subcommand used for dispatch.

If user stop its command on a  dispatching node, I would like to print help and stop. Currently runFirst and runLast doesn't meet my requirement. runAll don't give the hability to skip some node so help will be printed every time I pass on it.

An handler runFirstLast would work fine but I don't know if this is a great idea as it sound specific. An other way can be a flag on subcommand telling if it can be at the end.

**Comment by remkop** [comment]
Couldn't you just print help in the `run` method of the intermediate (dispatching) subcommand?

```java
@Command(name = "top", subcommands = Dispatcher.class)
class Top implements Runnable {
    @Option(names = "-x") String globalOption;

    public void run() {
        // ....
    }
}
@Command(name = "dispatch", subcommands = RealAction.class)
class Dispatcher implements Runnable {
    @Spec CommandSpec spec;

    public void run() {
        System.err.println("You need to specify a sub-subcommand");
        spec.commandLine().usage(System.err);
        //System.exit(1);
    }
}
```

**Comment by AlcaYezz** [comment]
I have tried this solution but with parseWithHandler and runAll, it will print the help even if I call a subcommand of the dispatcher

**Comment by AlcaYezz** [comment]
I think a flag for command that require subcommand would be a good idea, with this flag, one can tell if subcommand are required in the help message and stop the execution after the parsing before doing more processing.
I won't need a new handler with this solution.

**Comment by remkop** [comment]
I see what you mean now. Looks like this and #625 are similar.

So, just to clarify, you want to execute the top-level command, skip the subcommand, and execute the sub-subcommand (so you don't just want to use `RunLast` to run the last specified sub-subcommand).

Furthermore, you want to make sub-subcommands mandatory for one or more subcommands.

**Comment by AlcaYezz** [comment]
Yes that's it.
But skipping the subcommand is only valid in my use case and the overhead of call to an empty run isn't a problem. Some use case might require some general processing in the subcommand too as long as the sub-subcommand is present.

I close it as #625 as a better description of the problem.

**Comment by remkop** [comment]
Ok, understood. Thanks for raising this!
