### ISSUE TITLE
Invalid value for option '--xyz': '' is not an int

### ISSUE THREAD

**Issue by sebthom** [remkop/picocli#626]
For the following code:
```java
@Command(name = "foo", defaultValueProvider = FooCommandDefaultValueProvider.class)
public class FooCommand implements Runnable {

    public static class FooCommandDefaultValueProvider implements IDefaultValueProvider {
        public String defaultValue(ArgSpec argSpec) throws Exception {
            if ("DURATION".equals(argSpec.paramLabel())) {
                return "1200";
            }
            return null;
        }
    }

    @Option(names = "--delay", paramLabel = "DURATION", //
        description = "The delay time in seconds.", //
        arity = "0..1" //
    )
    protected Integer delayDuration;

    // ... more code
}
```

I would expect:
1. delayDuration is null if option "--delay" is not specified at all. (this works)
1. delayDuration is 4000 if option "--delay 4000" is specified. (this works)
1. delayDuration is 1200 if option "--delay" is specified without parameter where 1200 comes from the default value provider. However in that case I get the error:
`Invalid value for option '--duration': '' is not an int`

**Comment by remkop** [comment]
Actually, what happens during a call to `parse` is this:

1. First all options and positional parameters are reset to their initial values (field value in the declaration)
2. Next, default values are applied to all options and positional parameters
3. Finally, the input is parsed which may result in option and positional parameter values being overwritten with values matched from the command line 

So, if the option is not specified on the command line, it should get the default value. I’m surprised you are getting `null`, that should not happen. Can you run with -Dpicocli.trace=DEBUG` and post the output?

When the option is specified without a value, it is assigned an empty string. You can use a custom `typeConverter` for that option to convert this empty string to the desired value. See also the discussion in #280 about API to make this more convenient.

**Comment by sebthom** [comment]
Regarding: "When the option is specified without a value, it is assigned an empty string."
When I specify `artiy='0..1"` I am declaring that the parameter of the option is optional, so why would picocli then try to assign an empty string to as parameter value to the option of type integer?

**Comment by remkop** [comment]
The idea (see #279 and #280 for background) is that some applications want to distinguish between the option not being specified at all, and the option being specified without a value. 

In the latter case, picocli assigns an empty string. This is documented in the user manual: https://picocli.info/#_optional_values

With the current version of picocli, you need to specify a custom converter to replace the empty string with some legal value. This is not the most convenient way, so we’re looking for a better alternative in #280. 

By the way, were you able to verify that the default value is assigned when the option isn’t specified altogether?

**Comment by remkop** [comment]
By the way, any feedback, comments or suggestions related to syntax on #280 are welcome!

**Comment by sebthom** [comment]
I just checked again, you are right, when I don't specify the option, the default value is applied. I must have mixed this up during all the testing.

I am closing this in favor of #280
