### ISSUE TITLE
Include CommandLine$AutoHelpMixin and CommandLine$HelpCommand in graalvm reflection configuration

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#631]
Ensure the generated reflection configuration includes `CommandLine$AutoHelpMixin` and `CommandLine$HelpCommand`, to prevent

```
picocli.CommandLine$InitializationException: picocli.CommandLine$AutoHelpMixin is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations
 at picocli.CommandLine$Model$CommandReflection.validateCommandSpec(CommandLine.java:6549)
 at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:6395)
 at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3762)
 at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:4184)
 at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:6382)
 at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3762)
 at picocli.CommandLine.<init>(CommandLine.java:185)
 at picocli.CommandLine.<init>(CommandLine.java:164)
 at cli.java.Demo.mainCommand(Demo.java:444)
 at cli.java.Demo.testParseSubCommands(Demo.java:424)
 at cli.java.Demo.run(Demo.java:201)
 at picocli.CommandLine.execute(CommandLine.java:1160)
```

**Comment by remkop** [comment]
Closing this ticket since these classes are included automatically when used by the application.

**Comment by techthumb** [comment]
Hi @remkop ,

We are running into this issue. 

We are not using annotations for our commands as mentioned in #1141 

We are however using the `picocli.CommandLine$HelpCommand` via `CommandSpec.create().mixinStandardHelpOptions(true)` for the root command

We have configured the annotation processor. 
config json files are generated when we annotate a dummy command with `@Command` for the dummy command.

We are NOT however seeing entries for `picocli.CommandLine$AutoHelpMixin`.

We added `picocli.CommandLine$AutoHelpMixin` to `-Aother.proxy.interfaces`, but get an error saying that this should be an interface and not a class.

We'd appreciate some help on this front.


TIA

**Comment by remkop** [comment]
@techthumb OK. I will reply on the #1141 ticket, since it has more background information about your application.

**Comment by zipper01** [comment]
Same here. Code:
    @Command(name = "myapp", mixinStandardHelpOptions = true, description = "MyApp", version = "1.0")
    public class Main implements Callable<Integer> {
    
        //comman-line option to set tui mode under gui environment
        @Option(names = "--tui", description = "Use Text User Interface")
        boolean _tui;
    
        //command-line option to turn debug on
        @Option(names = "--debug", description = "Turn On Debug")
        boolean _debug;
    
        public static boolean supportGUI;
    	
    	static {
            try {
                supportGUI = !GraphicsEnvironment.isHeadless()
                        && GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices().length > 0;
            } catch (HeadlessException | java.lang.UnsatisfiedLinkError e) {
                supportGUI = false;
            }
        }
    
        @Override
        public Integer call() {
            //set debug
            if (_debug) {
                SYS.DBG_LEVEL = 2;
            }
    
            //set user interface
            if (supportGUI && _tui) {
                supportGUI = false;
            }
    
            if (supportGUI) {
    		    //Init GUI ...
            } else {
    		    //Init TUI ...
            }
            return SYS.ResultCode.SUCCEEDED;
        }
    
        public static void main(String args[]) {
            int exitCode = new CommandLine(new Main()).execute(args);
            System.exit(exitCode);
        }
    }

result running the generated native image it shows: _Exception in thread "main" picocli.CommandLine$InitializationException: picocli.CommandLine$AutoHelpMixin@74101cef is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations_. graalvm-ce-java17-22.3.0, picocli 4.7.0, os CentOS Linux release 8.2.2004 (Core).

**Comment by remkop** [comment]
@zipper01 I believe this is a separate issue, and I created #1916 to discuss further.
