### ISSUE TITLE
AutoComplete working only in Intellij Idea Terminal and not in Usual terminal

### ISSUE THREAD

**Issue by mrdantutunaru** [remkop/picocli#637]
When I enter an option and hit TAB in Intellij Idea, autocomplete works:
![image](https://user-images.githubusercontent.com/25580398/53243275-048cef80-36b0-11e9-8603-c865b0d7a792.png)
But, when I try from usual shell, Autocomplete is not working:
![image](https://user-images.githubusercontent.com/25580398/53244106-8847db80-36b2-11e9-8f45-8a15ebc0aac6.png)

Thanks

**Comment by remkop** [comment]
Did you source the completion script in the usual shell (and is this a bash shell)?

**Comment by mrdantutunaru** [comment]
Yes, this was the problem. thx
