### ISSUE TITLE
Default descriptionKey for options and parameters

### ISSUE THREAD

**Issue by Mikusch** [remkop/picocli#638]
In applications with a lot of commands, localizing argument descriptions is very tedious because you need to explicitly set `descriptionKey` on each option and positional parameter you wish to localize and ensure that the names match up with the keys in the resource bundle.

I propose a fallback resource bundle key that takes effect when both the `description` and `descriptionKey` attributes in `@Option` and `@Parameters` have not been set, similar to how the usage message already has pre-defined keys such as `mycommand.usage.customSynopsis`.

For a command `purge` with the `--verbose` option and ``files`` parameter the keys could be named `git.option.--verbose` or `git.option.verbose` and `git.param.files`.

If no mapping to that fallback key exists, it should do the same as it currently does when `descriptionKey` is missing and read the `description` attribute instead.

**Comment by remkop** [comment]
This is already implemented. Please see the javadoc for [@Option.descriptionkey](https://picocli.info/apidocs/picocli/CommandLine.Option.html#descriptionKey--) and [@Parameters.descriptionkey](https://picocli.info/apidocs/picocli/CommandLine.Parameters.html#descriptionKey--).

For options the fallback key is any option name without the leading dashes, for example:

```
# For option --verbose
verbose = Show more detail during execution. May be specified multiple times for increasing verbosity. 
```

For positional parameters the fallback key is the `paramLabel + [ index ]`, for example:

```
# For @Parameters(paramLabel="FILES") File[];
FILES[0..*] = The Files to process.
```

**Comment by Mikusch** [comment]
Interesting, I wasn't aware of the syntax for positional parameters. 

You may want to add that to the example resource file over at https://picocli.info/#_example_resource_bundle.

I apologize for making this issue, have a good evening.

**Comment by remkop** [comment]
That's a good idea, I added some text to that section just now. Thanks for the suggestion!
