### ISSUE TITLE
Feature request: pass full arg value (not split up parts) to custom converter

### ISSUE THREAD

**Issue by soenkeliebau** [remkop/picocli#642]
I have a command line option which will contain a filename, from which the Properties object will then need to be populated. So I figured I'd create a custom converter that loads the file and returns the parsed Properties for this.

I've defined my Option as follows:

```
@CommandLine.Option(names = {"-s", "--source-properties"}, required = true, converter = PropertiesConverter.class, description = "Properties file containing the configuration for the source cluster.")
private Properties sourceProperties = null;
```

And was expecting my PropertiesConverter to be called. However when I run this I get the following error message:

> Value for option option '--source-properties' (<String=String>) should be in KEY=VALUE format but was /home/...

Apparently this is due to the fact that Properties extends Map. When picocli encounters a parameter of type map it will run through some special parsing code, which tries to split the input string based on the assumption that it is in KEY=VALUE format.
This creates issues in my case, because the option is actually a filename that the KEY=VALUE pairs will then be read from.

**Comment by remkop** [comment]
When picocli sees that the type of an option is (or implements) `java.util.Map`, the parser
* assumes that values will be specified as key-value pairs in `KEY=VALUE` format
* assigns a separate converter for the key and for the value
* if the user specified a single custom converter, this becomes the converter for the key. If the user specified two custom converters, the second converter is for the value.

One other thing to note: if the option uses a `split` regex, the picocli parser will split the value into parts and use the converters to convert _each part_ to the target types.


This works well most of the time, but it does not allow users to specify a converter that is responsible for converting the full raw argument value  to the target type. The current logic always does some preprocessing and lets the converters convert a _part_ of the raw argument value.


We could introduce a parser configuration option that signals to the picocli parser to avoid the preprocessing and instead pass the full raw argument value to the option-specific custom converter.
When this parser configuration is specified, an option-specific custom converter would be mandatory (and only one converter should be specified).

Some ideas for names for this configuration:
* `CommandLine.setSkipPreprocessingForOptionSpecificConverters(boolean)`
* `CommandLine.setNoSplitForOptionSpecificConverters(boolean)`
* other?

**Comment by remkop** [comment]
An alternative is to have this configuration on the converter instead of globally on the command.
Converters that implement a marker interface (e.g., `interface ISkipPreprocessing`) or an annotation (e.g., `@SkipPreprocessing`) would be passed the full raw argument value instead of preprocessed parts.

For example:

```java
@SkipPreprocessing
interface PropertiesConverter implements ITypeConverter<Properties> {
    public Properties convert(String arg) throws Exception {
        Properties result = new Properties();
        try { InputStream in = new FileInputStream(arg)) {
            result.load(in);
        }
        return result;
    }
}

// or

interface PropertiesConverter implements ITypeConverter<Properties>, ISkipPreprocessing { ... }
```

**Comment by soenkeliebau** [comment]
For my use case I don't think I have any preference, as both would work. I think the way to go largely depends on potential other scenarios. 
Basically, is there a scenario where I'd reuse my converter in a way that depends on preprocessing, like having a map of Properties files like so:
--file configfile=/home/..,commandfile=/home/...

I struggle to construct something like that which does not require code changes in the converter tbh, but that doesn't say that it isn't possible.
For that case (and similar ones) having the option on the Command would give greater flexibility.

**Comment by remkop** [comment]
Wouldn’t it be more flexible to do the configuration on a per-converter basis? 

That would allow commands where some custom converters parse the raw value, where other custom converters parse preprocessed parts. 

If the configuration is on the command _all_ custom converters in that command would be required to parse the raw value. 

I’m not too concerned with reusing a converter for both raw values and preprocessed parts: the conversion logic would be very different so I can’t really imagine that use case.

**Comment by soenkeliebau** [comment]
Ah, that was my inexperience with picocli speaking in that case :)

I wasn't aware of the blast radius when putting that config on a command. Though, looking at the code again, what I meant, of course, was _option_ not _command_. 

But as we both can't really come up with a scenario where you'd want to reuse a converter I honestly think that it doesn't matter. Whichever fits better with the overall picocli style of doing things.

**Comment by remkop** [comment]
@soenkeliebau I believe what you asked for may be possible with the new [custom parameter consumer](https://picocli.info/#_custom_parameter_processing) feature introduced in picocli 4.0.

Something like this:

```
@Command
class MyApp {
    @Option(names = {"-s", "--source-properties"}, required = true, 
            parameterConsumer = PropertiesConsumer.class,
            description = "Properties file containing the configuration for the source cluster.")
    private Properties sourceProperties = null;
}

class PropertiesConsumer implements IParameterConsumer {
    public void consumeParameters(Stack<String> args, ArgSpec argSpec, CommandSpec commandSpec) {
        if (args.isEmpty()) {
            // throw ParameterException: parameter required for --source-properties
        }
        Properties p = new Properties();
        File f = new File(args.pop());
        if (!f.exists() || !f.isReadable()) {
            // throw ParameterException: specified --source-properties file does not exist / cannot read
        }
        try (InputStream in = new FileInputStream(arg)) {
            p.load(in);
        } catch (IOException e) {
            // throw ParameterException: problem while reading --source-properties from f.absolutePath + e.toString()
        }
        argSpec.setValue(p);
    }
}
```
