### ISSUE TITLE
Documentation: incorrect exception in programmatic API example

### ISSUE THREAD

**Issue by aluminais** [remkop/picocli#646]
The "Basic Processing" example here: 
https://github.com/remkop/picocli/wiki/Programmatic-API

Uses ParseException, which does not have a getCommandLine() method.  I believe this should be ParameterException.

**Comment by remkop** [comment]
You’re right. Thanks for pointing this out!

**Comment by remkop** [comment]
I fixed the wiki and the https://picocli.info/picocli-3.0-programmatic-api.html page.
I will soon add this to the release notes for the next release.
Thanks again for the heads-up!
