### ISSUE TITLE
How to declare subcommands using methods.

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#647]
I have a CLI application called `example`, with a subcommand `foo`, like this:

```java
@Command(name = "example", mixinStandardHelpOptions = true)
public class ExampleCli {

  @Command(description = "Does foo.")
  public void foo() {…}

}
```

That works nicely, so on the command line I can issue `example foo`.

But how do I add a subcommand to `foo` using the declarative approach with methods, so that I can issue `example foo bar`? Forgive me if I missed this in the user's guide.

Note that I'm using the following to kick the whole thing off:

```java
CommandLine.run(this, args);
```

**Comment by remkop** [comment]
Hi Garret,

The only way to declaratively add subcommands to `@Command`-annotated methods is by specifying a class in the `subcommands` attribute. The class can be a nested class though. Something like this:

```java
@Command(name = "example", mixinStandardHelpOptions = true)
public class ExampleCli  implements Runnable {

  @Command(subcommands = Bar.class, description = "Does foo.")
  public void foo() {…}

  @Command(name = "bar")
  static class Bar implements Runnable {
    public void run() {
      // bar business logic
    }

    @Command(description = "bar subcommand")
    public void baz() { 
      // baz business logic
    }
  }
}
```

**Comment by remkop** [comment]
@garretwilson  Did this answer your question?

**Comment by remkop** [comment]
@garretwilson Are you okay to close this ticket, or is there something to follow up on?

**Comment by garretwilson** [comment]
@remkop , thanks for being so attentive, and I apologize for the delay. I have two or three projects I'm working on. Your response sounds fine. If you don't mind waiting a few more days, I'll circle back and try this out, let you know, and close the ticket. Thanks!

**Comment by garretwilson** [comment]
I'm slowly coming back to this, but I wanted to ask one question: if Picicli sees that `Bar` is an internal static class of `ExampleCli`, and they are both marked with `@Command`, why can't Piclocli just assume that `Bar` is a subcommand of `ExampleCli`? Why do I need the `subcommands` designation?

Oh, I see, `foo` is a subcommand of `ExampleCli`, and you're making `bar` a subcommand of `foo`. OK, good to know.

But if I take out `foo()`, would `Bar` then become a subcommand of `ExampleCli` automatically, without any special designations? I can't think of why I would ever want to use an inner class of a command, both annotated with `@Command`, unless one was a subcommand of the other (assuming I didn't override this with `subcommands` as you have in the example).

Thanks in advance for clarification.

**Comment by remkop** [comment]
When `@Command` methods were added, it made sense to "automagically" make `@Command` methods subcommands of the enclosing `@Command` class. The `subcommands` mechanism already existed, but could not be used for `@Command` methods since it is not possible to explicitly specify method references in annotation attributes, like we can with class references.

I can see why we could consider retrospectively applying the same to `@Command` inner classes, but I'm not sure if it is a good idea... For one thing, existing application that for any reason did not make their nested static class a subcommand would all of a sudden behave differently.

**Comment by garretwilson** [comment]
> I can see why we could consider retrospectively applying the same to @Command inner classes, but I'm not sure if it is a good idea... For one thing, existing applications that for any reason did not make their nested static class a subcommand would all of a sudden behave differently.

That's a valid argument, but it has its limits—you don't want to be tied with things forever. At some point a new major version might be a good idea, allowing you to make breaking changes. (And it this case it might not even affect anyone—what are the chances of someone making an internal class for a non-subcommand?)

Anyway, a major version change might be a good chance to add that updated version provider interface, doing it the Right Way.

**Comment by remkop** [comment]
Hmm... I'm still not convinced that it is a good idea to automatically consider `@Command`-annotated inner classes subcommands of the outer class. I can easily imagine people would not want to nest classes too deeply, and prefer to use flatter structures like this:

```java
@Command(subcommands = Inner.class)
class Outer {

    @Command(name = "inner", subcommands = InnerSub.class)
    static class Inner {
    }

    @Command(name = "innersub")
    static class InnerSub {
    }
}
```

I know we are talking about defaulting and people could still accomplish the above by explicitly specifying which command is a subcommand of what, but at some point defaults can be more confusing than helpful. 

At the moment I'm happy with the current structure where `subcommands` needs to be specified explicitly for inner classes.

> Anyway, a major version change might be a good chance to add that updated version provider interface, doing it the Right Way.

I assume you are talking about #629. It's probably better to keep discussion about different topics on their own ticket to avoid confusion.

**Comment by garretwilson** [comment]
> Hmm... I'm still not convinced that it is a good idea to automatically consider @Command-annotated inner classes subcommands of the outer class.

That's another inconvenience but still not a deal-breaker. Yes, I agree that thinking about things before doing them is a good idea. This should probably be discussed in a separate ticket as well.

> I assume you are talking about #629. It's probably better to keep discussion about different topics on their own ticket to avoid confusion.

Yes, of course. I just mentioned it offhand as something related to a major version changed. I didn't mean to sidetrack the conversation here.

**Comment by remkop** [comment]
Reviewing outstanding open tickets; can this be closed?

**Comment by garretwilson** [comment]
Sorry, I haven't had time to come back to this with so many projects and deadlines. I won't get a chance to look at it for a couple of months at least.

**Comment by remkop** [comment]
No worries. 
Closing for now; I don’t think there’s any immediate tasks left. 
Feel free to open another ticket any time.
