### ISSUE TITLE
I18n resources and special characters

### ISSUE THREAD

**Issue by jrevault** [remkop/picocli#670]
Hi,

I use the **resourceBundle** parameter with a **@Command** annotation :
`@Command(name = "tests", aliases = {"t"}, resourceBundle = "i18n.SG_cli")`

It's working, I get my descriptions but when I use some french characters (é, è, à ...) it just shows bad characters.
With these resources values :
```
tests.auth.desc=Vérifie si l'utilisateur est connecte
tests.upload.desc=Tester le téléversement de fichiers.%nAttend un chemin complet de fichier.
```

I got :
```
Usage: SG client tests [-a] [-u=<upload>]
  -a, --auth              VÃ©rifie si l'utilisateur est connecte
  -u, --upload=<upload>   Tester le tÃ©lÃ©versement de fichiers.
                          Attend un chemin complet de fichier.
```
All files are correctly encoded in UTF-8 no bom.
Is there something I'm missing ?

**Comment by remkop** [comment]
That sounds like a bug... Let me take a look.

**Comment by remkop** [comment]
I was able to reproduce the issue. Still investigating.

**Comment by remkop** [comment]
I think I know what is happening. What version of Java are you executing your program on?

This problem does not happen if you run it on Java 9+.
Java 9 has been enhanced to [support resource bundle properties files in UTF-8](https://docs.oracle.com/javase/9/intl/internationalization-enhancements-jdk-9.htm).

Older Java versions will use ISO-8859-1 when reading the resource bundle, so you need to use the native2ascii tool to convert the special characters.

**Comment by jrevault** [comment]
Your right I'm on java 8...  It should be ok to move to 9 in my case.
Thanks

**Comment by remkop** [comment]
Cool , glad to hear that.

**Comment by jrevault** [comment]
A workaround for people stuck with jdk < 9 and using gradle :
```
import org.apache.tools.ant.filters.EscapeUnicode
tasks.withType(ProcessResources).each { task ->
    task.from(task.getSource()) {
        include '**/*.properties'
        filter(EscapeUnicode)
    }
}
```
