### ISSUE TITLE
Move module-info.class to root of jar?

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#674]
This is a follow-up item for #495. 
Having the `module-info.class` in `/META-INF/releases/9/` apparently also has drawbacks. 

Charles Nutter reported he had issues after putting the `module-info.class` in `/META-INF/releases/9/` : 
https://twitter.com/headius/status/1037931427000725504

So it may be safer to put it in the root of the jar after all. Since we publish two artifacts, old tools that cannot handle Java 9 bytecodes can always use the non-modular `picocli.jar`.

**Comment by Warkdev** [comment]
Hi, just revert this commit: 095ea30b6c7d02cf861b6e13bd7d9ebb90cdfdf9

Warkdev

**Comment by remkop** [comment]
Cool, thanks!
I’ll first try to reproduce the problem to see if this is really necessary.

**Comment by remkop** [comment]
(Note to self) The beryx/badass-jar-plugin has a setting to prevent the creation of a multi-release jar:

```
jar {
    ...
    multiRelease = false
    ...
}
```
