### ISSUE TITLE
Support option implications

### ISSUE THREAD

**Issue by qw3ry** [remkop/picocli#685]
I have a CLI option that implies another option, so in my `Runnable::run` I start with
```
if (foo) {
  bar = true;
}
```
This seems a bit out of place here. I'd like picocli to support the following instead:
```
class Options {
  @Option(name="--foo", implies="--bar")
  private boolean foo = false;
  @Option(name="--bar")
  private boolean bar = false;
}
```
Expected semantic: if `Options.foo == true` then `Options.bar == true` as well.

**Comment by remkop** [comment]
I'm not convinced this should be added to the library; as your example code demonstrates, the application can easily accomplish this with the current version of picocli.

What picocli _will_ offer from version 4.0 is [argument groups](https://github.com/remkop/picocli/releases#4.0.0-alpha-1-new), that can be used to define mutually exclusive options and mutually dependent options. This allows you to create commands where the `--bar` option becomes _required_ if the `--foo` option was specified. The relationship between such options is visually shown in the synopsis of the usage help message:

```
# mutually exclusive
mycommand (--foo | --bar)

# mutually dependent
mycommand (--foo --bar)
```
And additionally groups can be shown together in the option list in the usage help message with a dedicated heading.

I know this is not what you are asking for, but this is to illustrate the kind of features I am focusing on adding to the library: features that are less easy to provide for with custom application code.

**Comment by remkop** [comment]
Closing this ticket. Feel free to reopen if you want to discuss further and don't hesitate to create other tickets.
