### ISSUE TITLE
Passing args to another process (was: Confusing point about setStopAtPositional)

### ISSUE THREAD

**Issue by viliam-durina** [remkop/picocli#702]
I had a confusing point about `CommandLine.setStopAtPositional`. I use it to pass all arguments to a subprocess and the arguments for a subprocess start with an option.

Take this example:
```java
@Command
public class CmdLineTest implements Runnable {
    @Parameters
    private List<String> args;

    public static void main(String[] args) {
        CommandLine cmd = new CommandLine(new CmdLineTest());
        cmd.setStopAtPositional(true);
        cmd.parseWithHandler(new RunAll(), new String[]{"-c"});
    }

    @Override
    public void run() {
        System.out.println("args: " + args);
    }
}
```

It fails with:
```
Unknown option: -c
```
In this specific example we could use the `args` directly without any parsing, but in my real use case I also have subcommands and options.

I'm not proposing any change, just documenting this gotcha might be enough. Took me a while to figure out the issue. I worked it around in my case.

**Comment by remkop** [comment]
Maybe the option you are looking for is `CommandLine.stopAtUnmatched`?
https://picocli.info/#_stop_at_unmatched

I'm happy to improve the documentation, do you have any concrete suggestions?

**Comment by remkop** [comment]
I am not sure that I understand the problem. Was the problem "how to make picocli treat `-c` as a positional parameter"?

If that is the case, it may be useful to know that users can specify the end-of-options `--` delimiter as a command line option, and all arguments following the `--` will be treated as positional parameters (even if they resemble options).

**Comment by remkop** [comment]
Is your question related to [this StackOverflow question](https://stackoverflow.com/questions/56270505/a-way-to-configure-the-parser-using-annotations/56286370#56286370)?

**Comment by viliam-durina** [comment]
It's not really related to that question, but I'm the guy asking that question. I found `stopAtPositional`, but later found one gotcha I proposed to document in this issue.

I like the simple and predictable behavior of `stopAtPositional`. The documentation could for example say:

>You can use this flag to pass options to a subprocess that your command starts. For example:
>
> `<tool> [--tool option]..  [third-party-parameters]`
>
>If `stopAtPositional` is `true`, the options in `[command parameters]` will not be interpreted as `<tools>`'s options, but passed as positional arguments.
>However, if the `[third-party-parameters]` start with an option (an element starting with `-`), then that option will be interpreted as `<tool>`'s option. There has to be at least one parameter that's not an option to stop interpreting subsequent options.


`stopAtUnmatched` is unwieldy, it's not a good alternative. It will hide a typo in option and treat it as a positional parameter.

**Comment by remkop** [comment]
I see now, thanks for the clarification. I would recommend that you encourage the end users to specify the [end-of-options](https://picocli.info/#_double_dash_code_code) `--` delimiter before the 3rd party params:

```
<tool> [--tool option]... -- [3rd party params]
```

This is the most robust way to ensure that all 3rd party params (even ones that start with `-`) are treated as positional parameters. In that case you don't even need to use `stopAtPositional`.

**Comment by remkop** [comment]
The `--` end-of-options delimiter is actually a [POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) (see Guideline 10), and used in many tools, so it is likely that many of your users are already familiar with it.

**Comment by viliam-durina** [comment]
We work it around by specifying the command line in such a way that the 1st positional parameter is never an option, it's a third-party command name, so we no longer have this issue.

**Comment by remkop** [comment]
I see. 
In general it’s hard for the library to know which options it’s supposed to handle and which options it’s supposed to pass through. 

The `--` options delimiter is very useful for this but the application needs to inform users about its behavior. 


Is there anything left to do for picocli on this ticket?

**Comment by viliam-durina** [comment]
Mention that in javadoc. I can hack a PR...

**Comment by remkop** [comment]
Yes please.

**Comment by remkop** [comment]
FYI, The upcoming picocli 4.0.0-beta-2 will add better support for passing parameters to a 3rd party command. See https://github.com/remkop/picocli/issues/718

**Comment by remkop** [comment]
From 4.0.0-beta-2, the user manual has a section on using [custom parameter parsing](https://picocli.info/#_custom_parameter_processing) to pass parameters to a 3rd party command.

Does this feature meet your needs, or should this ticket remain open?

**Comment by remkop** [comment]
@viliam-durina Have you had a chance to look at [custom parameter parsing](https://picocli.info/#_custom_parameter_processing) as a way to pass parameters to a 3rd party command? 

Is there any work remaining on this ticket or can it be closed?

**Comment by remkop** [comment]
I'm closing this ticket since picocli 4.0 added support for [custom parameter parsing](https://picocli.info/#_custom_parameter_processing) in order to pass params to a 3rd party command. Feel free to reopen or open another ticket if there is any issue.
