### ISSUE TITLE
Variable interpolation in defaultValue are not expanded in standard help

### ISSUE THREAD

**Issue by mbarbero** [remkop/picocli#723]
When using an option with defaultValue=${sys:user.home}, the field value is properly set. However, when using standard help options mixin, the help string mentions "Default: ${sys:user.home}" while I think it should display the interpolated value.

**Comment by remkop** [comment]
That sounds like a bug. Can you paste some example code to help me reproduce the issue?

**Comment by remkop** [comment]
I've been able to reproduce the issue with this test:

```java
@Test
public void testIssue723() {
    @Command(mixinStandardHelpOptions = false, showDefaultValues = true)
    class Issue723 {
        @Option(names="--mypath", defaultValue = "${sys:user.home}",
                description = "Path. Default=${DEFAULT-VALUE}.")
        private String path;
    }
    String expected = String.format("" +
            "Usage: <main class> [--mypath=<path>]%n" +
            "      --mypath=<path>   Path. Default=%1$s.%n" +
            "                          Default: %1$s%n",
            System.getProperty("user.home"));

    String actual = new CommandLine(new Issue723()).getUsageMessage(CommandLine.Help.Ansi.OFF);
    assertEquals(expected, actual);
}
```

This currently prints:

```
Usage: <main class> [--mypath=<path>]
      --mypath=<path>   Path. Default=C:\Users\remko.
                          Default: ${sys:user.home}
```

If your issue is different, please let me know. I am investigating the above now.

**Comment by remkop** [comment]
Fixed in master. Can you verify?

**Comment by mbarbero** [comment]
Verified. Thanks for the quick turnaround and the good work on this project!

**Comment by remkop** [comment]
Thanks for the verification.
Please star the project on GitHub if you like it! 😉

**Comment by remkop** [comment]
FYI, 4.0.0-beta-2 has been released. It may take a few hours for Maven mirrors to update.
Thanks again for the bug report!
