### ISSUE TITLE
Feature Request: bash/zsh completion implemented inside App

### ISSUE THREAD

**Issue by yschimke** [remkop/picocli#726]
As mentioned in https://github.com/remkop/picocli/issues/725, calling into the app can provide a lot richer completions.

I've implemented this myself in my own apps, but it's very specific code with caching, but with graal startup speeds it's probably possible to do a much simpler implementation.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/231923/59554849-7cee2800-8fa1-11e9-8a0b-30d0879df6c1.png">

**Comment by yschimke** [comment]
_Feel free to close, this is a suggestion, I don't have plans to actively work on this._

**Comment by remkop** [comment]
Can you expand a bit on the "inside App"?

One idea is to have a command that generates the completion script (https://github.com/remkop/picocli/issues/456).
Another idea is to let the Bash completion script call the app itself to get completion candidates (https://github.com/remkop/picocli/issues/506) - this requires the Bash completion script to be able to invoke the command, so path, classpath etc. needs to be set up correctly.

Is this what you have in mind?

**Comment by yschimke** [comment]
#506 is exactly it. I think it’s a safe assumption if you can output as part of usage help a command name, that at completion time you can call that command and it should work. You can see how I do it for fish in the other issue I raised.
