### ISSUE TITLE
Feature Suggestion: exec method

### ISSUE THREAD

**Issue by yschimke** [remkop/picocli#728]
This method seems like a useful default to provide within the library.  Covers help, shell completion hooks, error handling etc.

https://github.com/rsocket/rsocket-cli/blob/master/src/main/kotlin/io/rsocket/cli/Main.kt#L363

```kotlin
private fun exec(runnable: Main, args: List<String>) {
      val cmd = CommandLine(runnable)
      try {
        val parseResult = cmd.parseArgs(*args.toTypedArray())

        if (cmd.isUsageHelpRequested) {
          cmd.usage(cmd.out)
          exitProcess(parseResult.commandSpec().exitCodeOnUsageHelp())
        } else if (cmd.isVersionHelpRequested) {
          cmd.printVersionHelp(cmd.out)
          exitProcess(parseResult.commandSpec().exitCodeOnVersionHelp())
        }

        if (runnable.completionScript) {
          print(picocli.AutoComplete.bash("rsocket-cli", cmd))
        } else {
          runnable.run()
        }

        exitProcess(0)
      } catch (pe: CommandLine.ParameterException) {
        cmd.err.println(pe.message)
        if (!CommandLine.UnmatchedArgumentException.printSuggestions(pe, cmd.err)) {
          cmd.usage(cmd.err)
        }
        exitProcess(cmd.commandSpec.exitCodeOnInvalidInput())
      } catch (ue: UsageException) {
        cmd.err.println(ue.message)
        cmd.usage(cmd.err)
        exitProcess(cmd.commandSpec.exitCodeOnInvalidInput())
      } catch (ex: Exception) {
        ex.printStackTrace(cmd.err)
        exitProcess(cmd.commandSpec.exitCodeOnExecutionException())
      }
}
```

**Comment by yschimke** [comment]
@remkop I might start with a PR for this function.  On the other random suggestions, let me know if you are keen and we can dicsuss on those issues what the APIs could look like and I'll contribute some PRs over time.

**Comment by yschimke** [comment]
Just found CommandLine.execute()

**Comment by remkop** [comment]
Oh, I see, I was looking at https://github.com/rsocket/rsocket-cli/commit/099792ffcca62383e9840b913d3d307709d394af and wondering if there was a problem with `CommandLine.execute()` that you needed to work around. :worried:
Mystery solved! :smile:

**Comment by yschimke** [comment]
It would be useful to have some of the value adds supported without additional main entry points e.g. generating the completion file. Would make installations simpler as they could call the app on the fly. But nope, all good. Just missed it.

**Comment by yschimke** [comment]
Is it mentioned in the getting started docs? It’s a useful first approach.

**Comment by remkop** [comment]
The `execute` API is relatively new (previously there were `run` and `call` static methods, but these didn’t have exit code support). 

I added a new section to the user manual. Maybe I should add additional pointers. 
Where would be a good place? The readme?

**Comment by yschimke** [comment]
I think as the first item for any user facing docs. The minimal example should be that method and a main class runnable with a few options.

**Comment by remkop** [comment]
Makes sense. I updated the README, will also update the javadoc for CommandLine and any other place I find.
