### ISSUE TITLE
Make the picocli jar OSGi friendly

### ISSUE THREAD

**Issue by raducotescu** [remkop/picocli#734]
I would like to use the picocli in an OSGi environment for a module of the Apache Sling project - see [0]. Currently, I've embedded the source code, but that makes our Sonar checks fail. Would it be possible to provide an OSGi-friendly jar? The effort should be minimal IMO and would really help us out, without any other implications for other consumers.

[0] - https://github.com/apache/sling-org-apache-sling-committer-cli/pull/4

**Comment by remkop** [comment]
I’d be happy to help. 
Can you clarify what concrete changes you need for the picocli jar to be an OSGi-friendly jar?

**Comment by raducotescu** [comment]
We just need to add some headers to the jar's manifest file. This is easily achievable with the `bnd-maven-plugin` [1]. In Sling we work with the `bnd.bnd` file, since it makes OSGi instructions easier to define and maintain. Should I come up with a PR for you?

[1] - https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin

**Comment by remkop** [comment]
Yes please, a PR would be great!

**Comment by remkop** [comment]
Note that picocli uses Gradle to build though. The `pom.xml` is for GitHub bookkeeping.

**Comment by remkop** [comment]
Merged into master. Please verify.
This will be included in the 4.0.0-beta-2 release later this week.
Many thanks for the PR!

**Comment by remkop** [comment]
FYI, 4.0.0-beta-2 has been released. It may take a few hours for Maven mirrors to update.
Thanks again for the PR!

**Comment by remkop** [comment]
@raducotescu Quick question: I notice that the `Bundle-SymbolicName` header is set to `picocli`. What are the conventions for the symbolic name? Should this be the "group name" of the artifact Maven coordinates (that is,`info.picocli`) instead? - Just wondering.

**Comment by raducotescu** [comment]
I've used the default the plugin sets, which is the name of the folder
where the `bnd.bnd` file is. It's just a name and doesn't really have much
importance in the OSGi world but if you prefer you can change it to
`<groupId>.<artifactName>` for the final release. Or it could stay like it
is, since it's anyways the name of the artifact, right?
