### ISSUE TITLE
Subcommand help not displayed if parent command has unfulfilled required params

### ISSUE THREAD

**Issue by rain-on** [remkop/picocli#743]
I have a parent command with a required parameter, there also exists a subcommand.
I would like to be able to show the subcommand's help text with:
parentCommand subcommand --help

However, a missing parameter exception is thrown (as the required param is not displayed).
I have tried tagging the subcommand with "isHelpCommand", however, this just removes the required check all together, such that when a non-help invocation is created, the main app throws due to missing data.

Is the only way around this, or do we just need to perform required checks in our app?

Kind regards.

**Comment by rain-on** [comment]
As an aside (with isHelpCommand disabled):

If "collectErrors" is enabled on the parser, then the help from the parentCommand is displayed, without the "missing parameters" message.

**Comment by rain-on** [comment]
This can probably be closed - the 'right' way to do this is:
parentCommand help subcommand ....

**Comment by remkop** [comment]
Thanks for raising this. I had not thought of this possibility.
It seems a bit inconsistent that `parentCommand help subcommand` works, 
while `parentcommand subcommand --help` complains about the missing required option...

I need to think about this a bit. Reopening this ticket so I won't forget about it.
I added this test to reproduce the issue:
https://github.com/remkop/picocli/blob/master/src/test/java/picocli/CommandLineHelpTest.java#L4085

**Comment by remkop** [comment]
Reviewing this ticket after some time has passed.
The current behaviour seems reasonable: there is a workaround (`parent help subcmd`) and changing the parser to accommodate this will likely lead to inconsistent behaviour elsewhere.
I agree with @rain-on's final assessment.
Closing this ticket.
