### ISSUE TITLE
Picocli should disallow `split` regex for single-value type options (was: Argument groups: false error message when using split regex)

### ISSUE THREAD

**Issue by deining** [remkop/picocli#745]
I'm running the minimum working example below:

```
package test;

import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

public class ArgGroupsTest {

    public static void main(String[] args) {
        CommandLine cmd = new CommandLine(new TestCommand());
        cmd.execute( "-option=1,2");
    }

    @Command(name = "ArgGroupsTest")
    static class TestCommand implements Runnable {

        @ArgGroup( exclusive = false)
        DataSource datasource;

        static class DataSource {
            @Option(names = "-option", split = "," )
            int value;
        }

        @Override
        public void run() {
            // nothing to do here
        }
    }
}

```

IMHO, the program should exit gracefully, however, an error message is thrown:

```
Invalid value for option '-option': '1,2' is not an int
Usage: ArgGroupsTest [[-option=<value>[,<value>...]]]
      -option=<value>[,<value>...]
```

Is this the intended behaviour?

**Comment by remkop** [comment]
In this case, I think the behaviour is as expected.

Picocli first looks at the type of the option (`int` in this example), and proceeds to process the parameter as a single value. The `split` attribute is ignored for single values. This behaviour is the same for simple commands without argument groups. This is documented in the [javadoc](https://picocli.info/apidocs/picocli/CommandLine.Option.html#split--), perhaps this should also be mentioned in the user manual?

The `split` attribute is honoured if the type of the option is multi-value (an array, Collection or Map).

To illustrate, I expanded on your example:

```java
@Command(name = "ArgGroupsTest")
static class CommandWithSplitGroup {

    @ArgGroup(exclusive = false)
    DataSource datasource;

    static class DataSource {
        @Option(names = "-single", split = ",")
        int single;

        @Option(names = "-array", split = ",")
        int[] array;
    }
}

@Test
public void testIssue745SplitErrorMessage() {
    CommandWithSplitGroup bean = new CommandWithSplitGroup();
    CommandLine cmd = new CommandLine(bean);
    
    // split attribute is honoured if option type is multi-value (array, Collection, Map)
    cmd.parseArgs("-array=1,2");
    assertArrayEquals(new int[] {1, 2}, bean.datasource.array);

    // split attribute is ignored if option type is single value
    // error because value cannot be assigned to type `int`
    try {
        cmd.parseArgs("-single=1,2");
        fail("Expected exception");
    } catch (ParameterException ex) {
        assertEquals("Invalid value for option '-single': '1,2' is not an int", ex.getMessage());
    }
}
```

**Comment by remkop** [comment]
Another idea to improve this is to generate an error or warning when the `split` attribute is used with a single-value type:

* Throw `InitializationException` from the `CommandLine` constructor 
* Add validation to the annotation processor to generate a compile-time error 

A drawback is that throwing a runtime exception may make some applications fail that used to work (and used to silently ignore the `split` attribute). 

I considered writing a warning to STDERR but we want to impact application authors, not end users.

**Comment by deining** [comment]
Thanks for the clarification.

>     * Add validation to the annotation processor to generate a compile-time error

I like this idea, for me, this seems to be the best approach to tackle this.

I think we have to see this from the user perspective. There is are clear usage instruction:

```
Usage: ArgGroupsTest [[-option=<value>[,<value>...]]]
      -option=<value>[,<value>...]
```

The user follows this instructions and is confronted with an error (because the application author erroneously specified a type (int) instead of a multi-value type (int[])). This fact is most likely unknown to the user, however. We have to assume that the issue remains mysterious to the user, which is a bad thing.

Another approach would be to change the usage instruction in this case:

```
Usage: ArgGroupsTest [[-option=<value>]]
      -option=<value>      description here
```

This seems akward to me, however.

I would clearly opt to generate a compile time error, if this can be implemented with reasonable effort.

**Comment by remkop** [comment]
Agreed. This is fairly straightforward to implement and will be useful for application authors who have the annotation processor configured. 

I’m most concerned with projects that don’t have the annotation processor configured. 
Your argument makes me think that it’s probably a good idea to additionally throw a (runtime) exception at initialization time for this. 

As you pointed out, it’s currently end users who pay the price for a misconfigured application. It’s better if picocli is strict about this. A major version increase like 4.0 is a good time for changes like this.

**Comment by deining** [comment]
You wrote:
> it’s probably a good idea to additionally throw a (runtime) exception at initialization time for this.

I fully agree. We shouldn't propagate the misconfiguration to the user and throw an exception here. It's more than justified.

**Comment by remkop** [comment]
Initial implementation pushed to master: runtime initialization exception from the `CommandLine` constructor and compile-time error by the annotation processor.
Still need to check and make changes to the documentation.

**Comment by remkop** [comment]
Done and pushed to master. Please verify.
