### ISSUE TITLE
CommandLine.execute: whitespace handling

### ISSUE THREAD

**Issue by deining** [remkop/picocli#747]
Minimum woking example, picocli 4.0.0-beta-2:

```
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

public class ExecuteTest {

    public static void main(String[] args) {
        CommandLine cmd = new CommandLine(new TestCommand());
        cmd.execute(args);
    }

    @Command(name = "ExecuteTest")
    static class TestCommand implements Runnable {

        @Option(names = "-foo" )
        static int foo;

        @Override
        public void run() {
            System.out.printf("foo = %s%n", TestCommand.foo);
        }
    }
}
```

I'm running this code, command line argument `-foo 78`. Result:

```
foo = 78
```

Now I'm replacing the code line `cmd.execute(args);` with `cmd.execute("-foo 78");`. Since I'm using exactly the same string, I expect to see the same result as above. However, an error message is presented:

```
Unknown option: '-foo 78'
Possible solutions: -foo
```

I know I can get the desired result with `cmd.execute("-foo", "78");`

What I'm asking for here is a convenience method `cmd.execute("whole command line argument string with spaces")`.
And it would be great if something like `cmd.execute("-x 3", "-y 4");` could work, too.

Can something like this implemented using a string tokenizer or so?

**Comment by remkop** [comment]
In my tests I sometimes write 

```
cmd.execute("-foo 78".split(" "));
```

Would this meet your needs?

**Comment by deining** [comment]
> Would this meet your needs?

Yes, that's very useful input, I didn't think of this.
This is sufficient here, closing this ticket.
