### ISSUE TITLE
How to pass multiple values to a Map?

### ISSUE THREAD

**Issue by feinstein** [remkop/picocli#753]
I have a `Map<String, Object>` object that's supposed to hold variables such as `"role","admin"`, `"level","10"`, `"enabled","true"`.

I tried to define it like:

```java
@Option(names = {"-m", "--map"}, description = "A map of values.")
    private Map<String, Object> myMap;
```

And call it like this in cli:

```
-m role=admin,level=10,enabled=true
```

But this results in a map of: `"role"` -> `"admin,level=10,enabled=true"`

What's the correct way to call it in the cli to get the full map of values?

**Comment by remkop** [comment]
Looks like you need to add `split = ","` to the option annotation.

**Comment by feinstein** [comment]
Shouldn't this be the default for a `Map`?

**Comment by remkop** [comment]
Picking good defaults is always tricky. 

I’m aware that JCommander splits automatically, and this may trip up people migrating from JCommander to picocli. That would be an argument for splitting by default. (Were you using JCommander previously?)

Currently picocli doesn’t split unless you tell it to. The drawback is somewhat more verbosity, the benefit is self-documentation: it’s clear which options split and which don’t, and it’s clear what the separator is.

**Comment by feinstein** [comment]
I wasn't in JCommander, I was just expecting a `Map` to be automatically populated as the docs imply it would. Actually the docs don't cover this particular case so it gets open to interpretation.

**Comment by remkop** [comment]
I see, yes, the [map](https://picocli.info/#_arrays_collections_maps) docs don't have an example that uses a split regex. Let's improve that. 

Do you think you'll be able to provide a patch or pull request?

**Comment by feinstein** [comment]
I don't think I can because I am not familiar with all the docs references that can be impacted by this issue, so I am afraid I might leave one out.

**Comment by remkop** [comment]
I was thinking to just add an example to the section on Maps (from line 614 in https://github.com/remkop/picocli/blob/master/docs/index.adoc). I don't think there are any references.

The HTML is generated from that AsciiDoc file (run `gradlew ascii` to generate `build/docs/html5/index.html`).

**Comment by remkop** [comment]
Alternatively, you can help by providing the text/example code in a comment here, and I will take care of integrating it into the user manual.

**Comment by feinstein** [comment]
This is easier for me now. I would add something like this at the end of the map section:

Be aware that if you wish to parse a multi-valued `Map` in a single input, a `split` character will be required. That is, if you expect to receive something like:

<command> -m role=admin,level=10,enabled=true

You have to define your @Options configurations as:

```java
@Option(names = {"-m", "--map"}, split = ",", description = "A map of multiple values.")
private Map<String, String> map;
```

Which will be converted to a `Map` containing {"role"="admin","level"="10","enabled"="true"}

**Comment by remkop** [comment]
Cool, thank you! I'll update here after I merged this in (hopefully tonight).

**Comment by remkop** [comment]
I decided to improve the example in the [Split Regex](https://picocli.info/#_split_regex) section of the user manual, and point to that section from the [Maps](https://picocli.info/#_maps) section (and also from the [Arrays and Collections](https://picocli.info/#_arrays_and_collections) section).

Thanks for calling this out!   :+1:
The [release notes](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md) for the next release mention you as a contributor.

**Comment by feinstein** [comment]
Thank you, it was my pleasure :)
