### ISSUE TITLE
Allow boolean options to get value from fallback instead of defaultProvider (Was: Negatable options interact badly with default providers)

### ISSUE THREAD

**Issue by adamsmd** [remkop/picocli#754]
I think I have discovered a problem with the design of negatable options.  Specifically, there is a problem when there is a default provider that dynamically calculates the default (e.g., it gets its values from a configuration file or environment variable).

For example consider a negatable option `foo`.  If the configuration file sets the default to `false`, then `--foo` sets the option to `true` and `--no-foo` sets the option to `false`.  However, if the configuration file sets the default to `true`, then these reverse and `--foo` sets the option to `false` while `--no-foo` sets the option to `true`.

I think this would a confusing behavior for the end user and that `--foo` and `--no-foo` should be consistent in what they set the option to regardless of what the default provider computes dynamically.

**Comment by remkop** [comment]
I am not sure I understand the problem.

Negatable options are [defined](https://picocli.info/#_negatable_options) to set the option to its default value. Based on the research I did for https://github.com/remkop/picocli/issues/694, this is consistent with the semantics of negatable options in other languages.

Isn't it up to the application to use this feature in a way that is as intuitive as possible for end users? In practice this means that negatable options are most useful with options whose default value is `true`.

**Comment by remkop** [comment]
I am not sure I understand the problem, or rather, I am not sure that picocli can solve this problem.

Negatable options are [defined](https://picocli.info/#_negatable_options) to set the option to its default value. Based on the research I did for https://github.com/remkop/picocli/issues/694, this is consistent with the semantics of negatable options in other languages.

Isn't it up to the application to use this feature in a way that is as intuitive as possible for end users? 
Changing the default value of a flag means you are changing the semantics of that option. Changing the meaning always has a risk of confusing the end users. Do you really want to make the meaning of an option configurable?

**Comment by adamsmd** [comment]
Given the current design, I don't think there is a way an application could use these two features together in an intuitive way.

For example, consider the `--status` and `--no-status` flags of `git commit` (see `man git-commit`) and the `commit.status` variable of the `.git/config` configuration file (see `man git-commit`). They behave as follows (which I consider intuitive).

- If `commit.status` is `false` in the configuration file and there no command line arguments, then `commit.status` is `false`.
- If `commit.status` is `false` in the configuration file and `--status` is a command line argument, then `commit.status` is `true`.
- If `commit.status` is `false` in the configuration file and `--no-status` is a command line argument, then `commit.status` is `false`.
- If `commit.status` is `true` in the configuration file and there no command line arguments, then `commit.status` is `true`.
- If `commit.status` is `true` in the configuration file and `--status` is a command line argument, then `commit.status` is `true`.
- If `commit.status` is `true` in the configuration file and `--no-status` is a command line argument, then `commit.status` is `false`.

Based on how the documentation is written (see https://picocli.info/#_default_provider), my understanding is that default providers are the recommended way to handle options that the end user can specify either on the command line or in a configuration file (with the command line overriding anything set in the configuration file).  However, if you use a default provider to implement the example above, you get the following results (which I consider not intuitive).

- If `commit.status` is `false` in the configuration file and there no command line arguments, then `commit.status` is `false`.  (Same as before.)
- If `commit.status` is `false` in the configuration file and `--status` is a command line argument, then `commit.status` is `true`.  (Same as before.)
- If `commit.status` is `false` in the configuration file and `--no-status` is a command line argument, then `commit.status` is `false`.  (Same as before.)
- If `commit.status` is `true` in the configuration file and there no command line arguments, then `commit.status` is `true`.  (Same as before.)
- If `commit.status` is `true` in the configuration file and `--status` is a command line argument, then `commit.status` is `false`. (Different from before.)
- If `commit.status` is `true` in the configuration file and `--no-status` is a command line argument, then `commit.status` is `false`. (Different from before.)

Is my understanding correct that default providers are how one should implement such a configuration file?

Is there some way to implement the first behavior?

**Comment by remkop** [comment]
@adamsmd  Okay, I understand better now. Thanks for the clarification!

Looks like this is a bigger topic than just negatable options: it holds for all boolean options, regardless of whether they are negatable. Let's try to find a solution that makes the common use case easy and your specific use case possible.

First, I believe that the "common use case" is that explicitly specifying a boolean option on the command line would result in a value that is the opposite of the default value. (Let me know if you agree.)

In the use case you describe, you need the ability to _decouple_ the value that is assigned when the option is specified on the command line from the default value. I propose that we use the `fallbackValue` for this, and we change the parser to behave like the below:

> If a boolean option is defined with a `fallbackValue`, then this fallback value (using `Boolean.parseBoolean`) is assigned when the option is specified on the command line, _not the opposite of the default value_. If the negative is specified, the opposite of the `fallbackValue` is assigned. Define boolean options with a `fallbackValue` to make the value to assign independent from the default value.

So, to implement your use case, you would do something like:

```java
@Command(name = "commit", defaultValueProvider = ConfigDefaultProvider.class)
class GitCommit {

    // this option has fallbackValue = "true", so when specified on the command line
    // it is assigned `true`, regardless of the default value
    @Option(names = "--status", fallbackValue = "true", negatable = true)
    boolean status;
}
```

Thoughts?

**Comment by adamsmd** [comment]
Yes, that would address my concerns, and it seems like a good design.

(By the way, thank you for all the work you do on this project. Both using the library and my interactions with you have been very positive experiences.)

**Comment by remkop** [comment]
Glad we found a good solution.

And thank _you_ right back! Your ideas and feedback have helped make picocli a better library! :+1:
(That said, I will happily take all the  GitHub stars you can scrounge up... :wink:)

**Comment by remkop** [comment]
Initial implementation pushed to master. Added a [simple test](https://github.com/remkop/picocli/blob/master/src/test/java/picocli/NegatableOptionTest.java#L280). 
Todo: documentation.

**Comment by remkop** [comment]
Final changes pushed to master.
I added a new section [Boolean Options](https://github.com/remkop/picocli/blob/master/docs/index.adoc#boolean-options) to the user manual.

**Comment by remkop** [comment]
Final changes pushed to master.
I added a new section [Boolean Options](https://github.com/remkop/picocli/blob/master/docs/index.adoc#boolean-options) to the user manual.

Please verify.
