### ISSUE TITLE
Option-specific overwritten options

### ISSUE THREAD

**Issue by adamsmd** [remkop/picocli#755]
Whether options can be overwritten is currently global to a `ParserSpec` and is specified by calling the `setOverwrittenOptionsAllowed`.  Would it be reasonable to support specifying this as an argument to a specific `@Option` or `@Command`?  For example, it might be useful to allow particular negatable options to be used multiple times, but not allowing this for other options.

**Comment by remkop** [comment]
Yes, it may be a good idea to allow specific options to be overwritten multiple times while other options should be specified only once.

That said, the todo list for [4.0](https://github.com/remkop/picocli/milestone/40) and [4.1](https://github.com/remkop/picocli/milestone/38) is already quite large, so I don't know when I will get to this. You can speed things up by providing a patch or pull request.

**Comment by remkop** [comment]
Note that applications can achieve this option-specific validation with an `@Option`-annotated setter method.

See also https://picocli.info/#_custom_validation

I don't see myself working on this in the near future.
