### ISSUE TITLE
PatternSyntaxException when using '\' as split regex 

### ISSUE THREAD

**Issue by deining** [remkop/picocli#763]
I'm running the minimum working example below (latest snapshot picocli-4.0.0-rc-1):

```
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

public class ExecuteTest {
    
    static CommandLine cmd;

    public static void main(String[] args) {
        cmd = new CommandLine(new TestCommand());
        cmd.execute("x", "a\\b");
    }

    @Command(name = "ExecuteTest")
    static class TestCommand implements Runnable {
        
        @Option(names = "x", split = "\\")
        static String[] parts = {};

        @Override
        public void run() {
        }
    }
}
```

This results in

```
PatternSyntaxException: Unexpected internal error near index 1
\ while processing argument at or before arg[1] 'a\b' in [x, a\b]: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
Usage: ExecuteTest [x=<parts>[\<parts>...]]...
      x=<parts>[\<parts>...]
```

**Comment by remkop** [comment]
It's fantastic that you keep finding edge cases! Please keep it up!

In this case, I think the `split` regex needs another backslash: to specify a literal backslash `\` regex, it needs to be escaped, so we need to specify `\\`.  In Java code, each of these backslashes needs to be escaped again, so the `split` regex for the option should be `@Option(split = "\\\\")`.

I made this test to verify, and it passes:

```java
@Test
public void testBackslashRegex() {
    assertArrayEquals(new String[]{"a", "b"}, "a\\b".split("\\\\"));
}
```

**Comment by remkop** [comment]
I'll close this ticket but feel free to reopen if I missed something.
Thanks again for helping to make picocli a better library!
