### ISSUE TITLE
split regexp with escaped chars: usage help

### ISSUE THREAD

**Issue by deining** [remkop/picocli#765]
I couldn't reopen #763, so I'm creating a new issue here:
Thanks for helping me out. There is still a minor issue when using split regex:

```
package test;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

public class ExecuteTest {
    
    static CommandLine cmd;

    public static void main(String[] args) {
        cmd = new CommandLine(new TestCommand());
        cmd.usage(cmd.getOut());
    }

    @Command(name = "ExecuteTest")
    static class TestCommand implements Runnable {
        
        @Option(names = "x", split = "\\|")
        static String[] parts = {};

        @Override
        public void run() {
        }
    }
}
```

This results in 

```
Usage: ExecuteTest [x=<parts>[\|<parts>...]]...
      x=<parts>[\|<parts>...]
```

IMHO, the backslash shouldn't appear in the usage message since it might confuse the user.

**Comment by remkop** [comment]
I agree. I was aware of this but you're right, it should be fixed.

**Comment by remkop** [comment]
I started to look at this again. I remember now why I didn't do anything about this earlier, it's actually quite tricky. Taking a look at the [spec](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html), you'll see that there are escaped characters that have special meaning and should not be "unescaped":

Regex|Meaning
-- | --
\d | A digit: [0-9]
\D | A non-digit: [^0-9]
\s | A whitespace character: [ \t\n\x0B\f\r]
\S | A non-whitespace character: [^\s]
\w | A word character: [a-zA-Z_0-9]
\W | A non-word character: [^\w]
\b | A word boundary
\B | A non-word boundary
\A | The beginning of the input
\G | The end of the previous match
\Z | The end of the input but for the final terminator, if any
\z | The end of the input

Simply removing the leading backslash from such regular expressions would be even more confusing... For example, changing `\d` to `d` completely changes the meaning...

So, here are the options that I can think of (let me know if you can think of alternatives):
* leave all regular expressions as is
* replace only `\|` by `|` and `\\` by `\` and leave all other regular expressions as is

I'm not sure that the second solution won't cause other problems later. I don't like the current situation but I'm not confident that we have a good (or even acceptable) solution yet...

**Comment by deining** [comment]
This is tricky, indeed.

> So, here are the options that I can think of
> (let me know if you can think of alternatives):

What about adding 'usageSplit' to the annotation?

@Option(names = "x", split = "\\|", usageSplit="|" )

Then the user has full control over the text used.
If usageSplit is not specified, the currently implemented usage text is printed.

Just an idea, WDYT?

**Comment by remkop** [comment]
Interesting! That is a better idea than what I was able to come up with.
I need to think about this a bit further.
