### ISSUE TITLE
How to disable Usage when required Option is not given?

### ISSUE THREAD

**Issue by chinnaharsha09** [remkop/picocli#768]
Hi Team,

I have a question here. I have a command which has 3options, among them 2 are manditory. If i miss any one among the manditory options, by default along with error it shows usageof command like:

Missing parameter *A* 
Usage: <main class>
-a description
-b description
-c description.

My requirement is just: if any of required parameter is not given it just has to show specific error.

When I say command -h then only it has to give usage of that command.

Can you please help me how to do this?

Thanks and regards,
Chinna

**Comment by remkop** [comment]
Hi! Your question looks similar to this: https://github.com/remkop/picocli/issues/480

The last comment in that ticket shows a custom `IParameterExceptionHandler`. I believe that this code (or something similar) will give you the desired behavior. 

This can be configured with `CommandLine.setParameterExceptionHandler`. Can you try and see if that does what you want?

**Comment by chinnaharsha09** [comment]
Hi,

_Thanks for your quick response._ 

How to use `IParameterExceptionHandler` for subcommands.


```java
@Command(name = "regen", subcommands = {Deploy.class, Rollback.class}, mixinStandardHelpOptions = true)
public class TestCli {

    public static void main(String[] args) {
        new CommandLine(new TestCli()).execute(args);
    }

    @Command(name = "deploy", description = "To perform Deploy operation.", mixinStandardHelpOptions = true)
    public static class Deploy implements Callable<Void> {

        @Option(names = {"-u", "--user"}, required = true, description = "User name of SaaSAdmin")
        private String user;

        @Option(names = {"-c", "--cmns-file"}, required = true, description = "A file containing CMN URIs. Each URI is line separated")
        private File cmnsFile;

        @Option(names = {"-p", "--password"}, required = true, description = " Password of the user to connects to the CMNs", interactive = true)
        private char[] password;

        @Override
        public Void call() throws Exception {
            System.out.println("Executed deploy!");

            return null;
        }
    }

    @Command(name = "rollback", description = "To perform RollBack operation.", mixinStandardHelpOptions = true)
    public static class Rollback implements Callable<Void> {

        @Option(names = {"-u", "--user"}, required = true, description = "User name of SaaSAdmin")
        private String user;

        @Option(names = {"-p", "--password"}, required = true, description = " Password of the user to connects to the CMNs", interactive = true)
        private char[] password;

        @Override
        public Void call() throws Exception {
            System.out.println("Executed rollback!");
            return null;
        }
    }
}
```

**Comment by remkop** [comment]
What I would do is take the code for the `ShortErrorMessageHandler` class from the last comment in #480, and copy it into your project. You can modify (simplify) it if necessary. 

Then use it by changing your `main` method to:

```java 
new CommandLine(new TestCli())
    .setParameterExceptionHandler(new ShortErrorMessageHandler())
    .execute(args);
```

**Comment by remkop** [comment]
Please let me know if that solved the issue (and this ticket can be closed) or whether you need more information. :smiley:

**Comment by remkop** [comment]
@chinnaharsha09 Can this ticket be closed?

**Comment by remkop** [comment]
Closing this ticket. Feel free to reopen or create another one if there is more work to be done on this.
