### ISSUE TITLE
zsh completion script should not assume `complete` command exists

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#772]
After recently upgrading my macOs to Mojave, I found out that my Picocli autocomplete script stopped working with the following error:

```
.my-completion.sh:2899: command not found: complete`
```

To solve the problem I needed to add the following prior to running the script:

```
autoload bashcompinit
bashcompinit
```

On further inspection, I noticed https://picocli.info/autocomplete.html#_install_completion_script illustrates in passing that [this](https://stackoverflow.com/a/27853970/527333) is required. I'm wondering if it makes sense to add that to the generated script if `complete` isn't defined. That would allow the instructions for `bash` and `zsh` to be the same.

**Comment by remkop** [comment]
I’m open to any improvements. 
Do you think you can provide a pull request?

**Comment by remkop** [comment]
The generated completion script itself now enables bash completion in zsh.

That means it is no longer necessary to run the below commands in ZSH before sourcing the completion script:

```zsh
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
```

Can you verify?
