### ISSUE TITLE
IntelliJ IDEA fails to compile project w/ annotation processor

### ISSUE THREAD

**Issue by triceo** [remkop/picocli#773]
The IDE's compiler says:

    Error:java: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: picocli.codegen.aot.graalvm.processor.NativeImageConfigGeneratorProcessor Unable to get public no-arg constructor

This can be worked around by disabling annotation processing in the IDE, but that setting then switches itself back on when the project's `pom.xml` is updated.

To reproduce, create a Maven project with `maven-compiler-plugin` configured with the Picocli annotation processor.

**Comment by remkop** [comment]
Thanks for the report. I’ll take a look ASAP.

**Comment by remkop** [comment]
What’s your Intelli/J version?

**Comment by triceo** [comment]
![About my IDE.](https://user-images.githubusercontent.com/247403/61953657-44396980-afb7-11e9-99ef-29509c94bd78.png)

**Comment by remkop** [comment]
I was unable to reproduce the issue with my version of IntelliJ (2019.1.1). I will try to upgrade next.

Meanwhile, the `picocli-examples` module has 2 example Maven projects, and this is what I did to try to reproduce the issue:

* check out the picocli project
* in IntelliJ, do File > New > Project from Existing Sources...
* specify the full path to `picocli-examples/annotation-processing/example-maven-project-shading/pom.xml`
* click OK, and Next, Next, ... through the next wizard screens

This successfully generates the project, and I can see the annotation processor generating files during compilation in IntelliJ.

Can you try the above steps and let me know if you can reproduce the issue that way?

**Comment by triceo** [comment]
Interesting. I wasn't able to reproduce using that approach.

Can you check out my project?
https://github.com/RoboZonky/robozonky

To get the compiler error, you shouldn't need to do anything else but 
Build > Rebuild Project

**Comment by triceo** [comment]
(I should also note that I am seeing this issue ever since I upgraded to IntelliJ 2019.2. I was not seeing it on your 2019.1.)

**Comment by remkop** [comment]
I am now trying to compile the robozonky project in IntelliJ 2019.1.1, but I am having trouble with the Java version. What is the required Java version for the project?

**Comment by triceo** [comment]
It requires Java 11 or later.

**Comment by remkop** [comment]
Thanks, made some progress but now bumped into a different error: 
Error:(64, 49) java: cannot find symbol
  symbol:   class NaturalLanguageStrategyParser
  location: class com.github.robozonky.strategy.natural.SideEffectFreeParser

I will check again later.

**Comment by triceo** [comment]
Yeah, that's a problem I have not yet resolved. :-(

If you `mvn clean install` from the command line in the `robozonky-strategy-natural` module, it will generate the parser and from that moment, IDEA project building will succeed.

**Comment by remkop** [comment]
Cool, let me try that.

**Comment by remkop** [comment]
I was able to successfully build the project in IntelliJ IDEA 2019.1.1. The problem does not manifest with that version.

After upgrading to IntelliJ IDEA 2019.2, I also see the error:

> Error:java: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: picocli.codegen.aot.graalvm.processor.NativeImageConfigGeneratorProcessor Unable to get public no-arg constructor

Investigating....

**Comment by remkop** [comment]
I added a public no-arg constructor to `NativeImageConfigGeneratorProcessor`, but it did not make a difference...

I tested by running `gradlew -x check pubToMavenLocal` in the picocli project, then change the robozonky project pom.xml to `<version.info.picocli>4.0.2-SNAPSHOT</version.info.picocli>`, re-import Maven config, I confirmed that IDEA picked up the changes (dependencies in project view show picocli 4.0.2-SNAPSHOT), rebuild the project... but got the same error. Will investigate further later.

**Comment by remkop** [comment]
I added constructors to all annotation processors: the `NativeImageConfigGeneratorProcessor` constructor is public, its superclass constructors are protected. 

I released picocli 4.0.2 with these changes. Can you verify with this version?

If the problem still exists there may be an issue in Intelli/J IDEA, or perhaps there’s another issue in picocli than the error message indicates. Either way we may need help from JetBrains.

**Comment by triceo** [comment]
Upgraded to 4.0.2, didn't help. :-( 
Filed a bug with Jetbrains: https://youtrack.jetbrains.net/issue/IDEA-220545

**Comment by triceo** [comment]
It seems fixed in IntelliJ 2019.2.4.

**Comment by remkop** [comment]
That's great. They did not give much feedback on that ticket, but glad it's fixed!
