### ISSUE TITLE
Argument groups ignored in mixins (was: Heading section ignored when used inside mixins)

### ISSUE THREAD

**Issue by teoincontatto** [remkop/picocli#776]
I am not sure if this is expected behaviour or a bug but here it goes.

When I declare some heading section to show in the help using a mixin those sections does not appear:

* Test code

```
import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Mixin;
import picocli.CommandLine.Option;

@picocli.CommandLine.Command(name = "test",
    description = "Picocli test.",
    abbreviateSynopsis = true,
    sortOptions = false,
    usageHelpAutoWidth = true)
public class Test {

  @Mixin
  TestConfig testConfig = new TestConfig();

  private static class TestConfig {
    @ArgGroup(validate = false, heading = "A1")
    private final A1 a1 = new A1();

    private static class A1 {
      @Option(names = {"-ta1", "--test-a1"})
      private String testA1;
      @Option(names = {"-ta2", "--test-a2"})
      private String testA2;
    }

    @ArgGroup(validate = false, heading = "A2")
    private final A2 a2 = new A2();

    private static class A2 {
      @Option(names = {"-tb1", "--test-b1"})
      private String testB1;
      @Option(names = {"-tb2", "--test-b2"})
      private String testB2;
    }
  }

  /**
   * Picocli test.
   */
  public static void main(String[] args) {
    new CommandLine(new Test()).usage(System.out);
  }

}
```

* Output

```
Usage: test [OPTIONS]
Picocli test.
      -ta1, --test-a1=<testA1>

      -ta2, --test-a2=<testA2>

      -tb1, --test-b1=<testB1>

      -tb2, --test-b2=<testB2>
```

Removing the mixin and defining the options directly in the command has the expected result:

* Test code

```
import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Option;

@picocli.CommandLine.Command(name = "test",
    description = "Picocli test.",
    abbreviateSynopsis = true,
    sortOptions = false,
    usageHelpAutoWidth = true)
public class Test {

  @ArgGroup(validate = false, heading = "A1")
  private final A1 a1 = new A1();

  private static class A1 {
    @Option(names = {"-ta1", "--test-a1"})
    private String testA1;
    @Option(names = {"-ta2", "--test-a2"})
    private String testA2;
  }

  @ArgGroup(validate = false, heading = "A2")
  private final A2 a2 = new A2();

  private static class A2 {
    @Option(names = {"-tb1", "--test-b1"})
    private String testB1;
    @Option(names = {"-tb2", "--test-b2"})
    private String testB2;
  }

  /**
   * Picocli test.
   */
  public static void main(String[] args) {
    new CommandLine(new Test()).usage(System.out);
  }

}
```
* Output:

```
Usage: test [OPTIONS]
Picocli test.
A1      -ta1, --test-a1=<testA1>

      -ta2, --test-a2=<testA2>

A2      -tb1, --test-b1=<testB1>

      -tb2, --test-b2=<testB2>
```

**Comment by remkop** [comment]
Thank you for the bug report and for the code to reproduce the issue.
I'm looking into this now.

**Comment by remkop** [comment]
Update: the problem is bigger than just the headers: it turns out that the logic for importing mixin elements does not take argument groups into account at all. Only the options and positional parameters are mixed in, but the argument group information is ignored.

This is an oversight, not by design. I'm looking now at how to address this.

----

_Side note:_

picocli does not add a newline after [section headings](https://picocli.info/#_section_headings). You may want to add a `%n` after the custom option section headings.

**Comment by remkop** [comment]
@teoincontatto Thank you again for raising this!
I'm planning to add some more tests but I believe I found a fix that addresses the issue you reported and the bigger problem that `@ArgGroup`s in mixins were ignored altogether.
I pushed a fix to master. Can you verify?

**Comment by teoincontatto** [comment]
Hi @remkop, glad to help picocli to get better with my 2 cents. Sorry for not being able to test the master branch with my code base. I'll try it out this monday hopefully.

Regards

**Comment by remkop** [comment]
Great! The easiest way to do this is to check out the project in git, then run `gradlew publishToMavenLocal` on the command line. 

After that you can use the `picocli-4.0.2-SNAPSHOT` dependency in your project.

**Comment by teoincontatto** [comment]
I was able to pass the simple test using the 4.0.2-SNAPSHOT version. Now I am facing a `DuplicateOptionAnnotationsException` in a more complex use case. I managed to generate a simple test case that reproduce the new issue:

```
@picocli.CommandLine.Command(name = "test-with-nested-mixin",
    description = "Picocli section test with nested mixin.",
    abbreviateSynopsis = true,
    sortOptions = false)
public class Test {
    @Mixin
    TestConfig testConfig = new TestConfig();

    private static class TestConfig {
      @ArgGroup(validate = false, heading = "A1%n")
      private final A1 a1 = new A1();

      private static class A1 {
        @ArgGroup(exclusive = true)
        private final NestedA1 nestedA1 = new NestedA1();

        private static class NestedA1 {
          @Option(names = {"-ta1", "--test-a1"})
          private String testA1;
          @Option(names = {"-ta2", "--test-a2"})
          private String testA2;
        }
      }

      @ArgGroup(validate = false, heading = "A2%n")
      private final A2 a2 = new A2();

      private static class A2 {
        @Option(names = {"-tb1", "--test-b1"})
        private String testB1;
        @Option(names = {"-tb2", "--test-b2"})
        private String testB2;
      }
    }
  }

  /**
   * Picocli test.
   */
  public static void main(String[] args) {
    new CommandLine(new Test()).usage(System.out);
  }
}
```

Since this seem to be unrelated to the original issue let me know if you want me to open a new one.

**Comment by teoincontatto** [comment]
If I do not use mixin then the result (with version 4.0.1 and 4.0.2-SNAPSHOT) is not trowing exception but it prints the nested options outside of the section in the help:

* Test code:

```
@picocli.CommandLine.Command(name = "test-without-mixin-and-nested-group",
    description = "Picocli section test without mixin and nested group.",
    abbreviateSynopsis = true,
    sortOptions = false)
public static class TestWithoutMixin {
  @ArgGroup(validate = false, heading = "A1%n")
  private final A1 a1 = new A1();

  private static class A1 {
    @ArgGroup(exclusive = true)
    private final NestedA1 nestedA1 = new NestedA1();

    private static class NestedA1 {
      @Option(names = {"-ta1", "--test-a1"})
      private String testA1;
      @Option(names = {"-ta2", "--test-a2"})
      private String testA2;
    }
  }

  @ArgGroup(validate = false, heading = "A2%n")
  private final A2 a2 = new A2();

  private static class A2 {
    @Option(names = {"-tb1", "--test-b1"})
    private String testB1;
    @Option(names = {"-tb2", "--test-b2"})
    private String testB2;
  }

  /**
   * Picocli test.
   */
  public static void main(String[] args) {
    new CommandLine(new Test()).usage(System.out);
  }
}
```

* Output:

```
Usage: test-without-mixin-and-nested-group [OPTIONS]
Picocli section test without mixin and nested group.
      -ta1, --test-a1=<testA1>

      -ta2, --test-a2=<testA2>

A1
      -tc1, --test-c1=<testC1>

A2
      -tb1, --test-b1=<testB1>

      -tb2, --test-b2=<testB2>
```

**Comment by remkop** [comment]
@teoincontatto Thanks a lot for finding more issues in this area!
It may be good to open a separate ticket for this, if you don't mind.
I will start investigating.

**Comment by remkop** [comment]
Something strange: 
In your last comment, the Output mentions an option `-tc1, --test-c1=<testC1>`, but I don't see a definition for that option in either the `Test` class or the `TestWithoutMixin` class...

**Comment by teoincontatto** [comment]
You right, I've mixed code and output with another test I did, I correct the output with the real one in the previous message.

In any case I'll open separates issues with corrected source and output.

**Comment by remkop** [comment]
@teoincontatto Thank you for raising separate tickets for the new issues. I have fixed (hopefully) #779, and provided some feedback on #778. Let's continue the discussion on the respective tickets.

About the original problem here (Argument groups ignored in mixins), I think that has also been fixed. Are you okay to close this ticket?

**Comment by teoincontatto** [comment]
Yes seems resolved.

**Comment by remkop** [comment]
Thanks for the confirmation!
