### ISSUE TITLE
Minecraft Forge - Passing in dependencies & 'DIY' command execution with subcommands

### ISSUE THREAD

**Issue by Rubyjunk** [remkop/picocli#782]
I'm trying to use this library with Minecraft Forge. Unfortunately, to send messages in Minecraft I need to call `ICommandSender#sendMessage`, and not `System.out` or any `OutputStream`. I might also need to pass in some other objects/dependencies to the command logic as well. Does this library support a usecase such as this?

**Comment by remkop** [comment]
Yes that should all be possible.
Picocli will instantiate subcommands and things like type converters and default providers, but the application can control what objects are created (and can pass in other dependencies) by specifying a custom [factory](https://picocli.info/#_custom_factory) to the CommandLine constructor.

For messages you will need to wrap the `ICommandSender` stuff in an adapter that implements  `java.io.Writer`. I believe only a few methods of that interface are actually used.

**Comment by Rubyjunk** [comment]
Hi, thanks for the info. I tried writing a wrapper class for PrintWriter but I was just wondering if there was a better way. I'll take a look later today, but it seems like using something other than CommandLine#execute becomes unnecessarily complicated when using subcommands because the logic for subcommands is not handled for you, that's correct?

**Comment by Rubyjunk** [comment]
I've gotten it working. For anyone else trying to use these libraries together, here's the PrintWriter wrapper class that worked for me

```
    class ChatWriter extends PrintWriter {

        ICommandSender sender;

        ChatWriter(ICommandSender sender) {
            super(new NullOutputStream());
            this.sender = sender;
        }

        @Override
        public void print(String string) {
            sender.sendMessage(new TextComponentString(string));
        }
    }
```

And the custom factory works flawlessly. Amazing library!

**Comment by remkop** [comment]
@Rubyjunk sorry for the late reply, I was climbing a mountain. :-)

Glad to hear you got it working and glad to hear you like picocli. Please star the library on GitHub and spread the word! :wink:

I'm always looking for ways to improve the library, and I'm still thinking about your comment that "using something other than CommandLine#execute becomes unnecessarily complicated when using subcommands". If you have ideas or suggestions to improve things I am certainly interested. 

Cheers! -Remko
