### ISSUE TITLE
Passing option of one command to the next one

### ISSUE THREAD

**Issue by meshiruff** [remkop/picocli#783]
After inserting an option and running a command, and then running another command, the option of the first command is overwritten. is it possible to save the first option i enter and pass it to the next command?

Thanks.

**Comment by remkop** [comment]
As you mentioned, picocli will ensure all options and positional parameters are set to either their default value or the value specified on the command line. This is to ensure that applications can reuse a `CommandLine` instance for multiple invocations _without_ seeing the result of a previous invocation. 

One idea is to create a new `CommandLine` instance for each invocation, and pass the previous instance to the next command. Would this work for you?

**Comment by remkop** [comment]
@meshiruff Don't hesitate to let me know if you have more questions.

**Comment by meshiruff** [comment]
Hi,
I want to save the values of the command and pass it to the others, but i cant find the object that contains the values of the options, just the originalArgs list.

can you help me with that?
thanks

**Comment by remkop** [comment]
Okay, my suggestions below may not work for your use case (I have no idea what your application looks like), but let me give it a try.

Suppose you have a command class with some options, like in this (very simple) example:

```java
class MyCommand {
  @Option(names = "-x")
  int x;

  MyCommand previousInput;
}
```

Now, in your application you parse the user input, let's assume that the user input has already been tokenized into an array of `String`s:

```java
class App {
  private MyCommand previousInput;

  // let's assume that your interactive application calls this method repeatedly,
  // every time user input becomes available.
  // if your app works very differently, please share your code so we can discuss details.
  void parseUserInput(String[] args) {
      MyCommand options = new MyCommand(); // construct a new instance of your user object
      options.previousInput = previousInput; // we pass the previous input to your user object

      CommandLine cmd = new CommandLine(options); // construct a CommandLine with it

      // now we can either use cmd.execute() or cmd.parseArgs()... which are you using?
      cmd.parseArs(args); // parseArgs will populate the MyCommand options object

      // and we store the current input so it becomes "previous input" for the next invocation
      this.previousInput = options;
}
```

**Comment by meshiruff** [comment]
I use parseWithHandlers for excuting the command, and i want to add to the parseResult the options that was there before

**Comment by remkop** [comment]
`parseWithHandlers` has been superceded by `CommandLine.execute` in 4.0 (`execute` does the same as `parseWithHandlers` but gives more flexiblity, see https://picocli.info/#_migration). 

Do you have a custom `IParseResultHandler2` or are you using one of the built-in ones (e.g. RunLast)?

>  i want to add to the parseResult the options that was there before

How would your `Runnable` or `Callable` commands get those previous values from the `ParseResult`? 
Wouldn't it be easier to add previous parse results to a user object (like the `MyCommand` class in my previous comment's example)?

**Comment by remkop** [comment]
@meshiruff Did that answer your question?

**Comment by remkop** [comment]
Closing this ticket. Feel free to open another one if you have more questions.
