### ISSUE TITLE
picocli migration guide: 3.x -> 4.x

### ISSUE THREAD

**Issue by daggerok** [remkop/picocli#785]
Hello,

Please let me know if there are some migration guides available from picocli 3 to picocli 4?
I upgraded my cli app 3.9.6 -> 4.0.2 and found quite a lot of braking changes, it would be good, if you already have some common list of most asking question I could read to do all needed changes.

Thanks!

---
Regards, Maksim

**Comment by remkop** [comment]
Hi,

The [4.0 release notes](https://github.com/remkop/picocli/releases#4.0.0) has a section on [potentially breaking changes](https://github.com/remkop/picocli/releases#4.0.0-breaking-changes). 

Also, the user manual has a [section on migrating](https://picocli.info/#_migration) to the new `execute` API. 

Let me know if there’s other issues not covered and I’ll update the documentation.

**Comment by daggerok** [comment]
Hello @remkop 
Thanks for your feedback. I will check and come back with updates in case if anything else

**Comment by remkop** [comment]
Note:  I will add something about custom factories to the breaking changes section:

From 4.0, picocli instantiates all `Collection`s via the factory. It is recommended that custom factories should fall back to the default factory.

See https://github.com/remkop/picocli/issues/784 for details.

**Comment by remkop** [comment]
Documentation regarding factories updated.

Can you explain about the breaking changes you found?

**Comment by daggerok** [comment]
sorry, wasn't able to collect problem list -- busy with different taskd and migration is postponed now^ but I plan to look ob #784 and if needed let you know. Thanks for support

**Comment by remkop** [comment]
No worries, that’s fine!
Enjoy picocli!
