### ISSUE TITLE
Approximate `istty()` by checking `System.console() != null`

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#79]
Use reflection to avoid introducing dependency on Java 6.

As indicated [here](http://stackoverflow.com/questions/1403772/how-can-i-check-if-a-java-programs-input-output-streams-are-connected-to-a-term?noredirect=1&lq=1), this is not entirely correct, but still better than no check at all...

**Comment by bric3** [comment]
Hi,

It seems that in JDK 22, checking is `System.console()` returns `null` might not be enough. With JDK 22 there is now a `Console::isTerminal` as the new default console is based on JLine.

It still doesn't allow to be specific about which side is interactive or not though.

**Comment by remkop** [comment]
> Hi,
> 
> It seems that in JDK 22, checking is `System.console()` returning `null` might not be enough. With JDK 22 there is now a `Console::isTerminal` as the new default console is based on JLine.
> 
> * https://bugs.openjdk.org/browse/JDK-8309155
> * [openjdk/jdk@bae2247](https://github.com/openjdk/jdk/commit/bae224793812cb0a0aa67e399062498d3b13fdb3)
> 
> It still doesn't allow to be specific about which side is interactive or not though.

@bric3 Please refer to https://github.com/remkop/picocli/issues/1104, https://github.com/remkop/picocli/issues/2083 and https://github.com/remkop/picocli/pull/2084 ; is there still an issue?

**Comment by bric3** [comment]
Oh thank you @remkop I wasn't looking for these keyword so I didn't find them.

No issue I was just exploring available options to detect if stdin or stdout were interactive (e.g. when piping). And I stumbled on this PR so I made the comment, but I'm way late as other work has been done.
