### ISSUE TITLE
Retrieve execution result when only a single execution occurred

### ISSUE THREAD

**Issue by prd-fox** [remkop/picocli#801]
Hi,

I wondered if it was possible, or if it could be added, to be able to fetch an execution result of a sub-command from the top level `CommandLine.getExecutionResult()`?

I followed the instructions in section `9.6.4` to follow the execution tree down and get the result, but feel as though this shouldn't be needed if only a single execution occurred.

This would only apply if a single execution occurred, such as with `RunFirst` or `RunLast`, and perhaps throw an exception in other cases.

This is purely a shortcut for users, and doesn't add any new functionality, so if you feel as though its too much effort for something that can already be achieved, then I understand.

Thanks!

**Comment by remkop** [comment]
Hi @prd-fox, 

My thinking was that following the command tree down to the command that executed and retrieving the result from that command has the advantage that the application knows which command was actually executed, which gives some context that may be necessary to process the result. The current API also caters for IExecutionStrategies like `RunAll` which may return multiple results.

I can see how what you propose would be more convenient for some users, but on the other hand I can also imagine it would be confusing to get the execution result of one command from the definition object of a different command...

Also, I don't like changing the semantics of an existing method...

How about adding a different method?

**Comment by prd-fox** [comment]
Adding a different method is good, actually I would agree that it's the preferable option.

I haven't thought through other edge cases (like `RunAll`), but I imagine a "fail-fast" approach would be the easiest - of course, that is up to you.

**Comment by prd-fox** [comment]
> I can see how what you propose would be more convenient for some users, but on the other hand I can also imagine it would be confusing to get the execution result of one command from the definition object of a different command

I certainly agree with this, by the way, and I think it may be how I view the `CommandLine` object. Even though it is the `<main class>` command, I view it as the co-ordinator of execution, with the `<main class` being the first command it checks.

**Comment by remkop** [comment]
Do you think you’ll be able to provide a pull request for this with unit tests and documentation?

**Comment by prd-fox** [comment]
Definitely.

I don't really have a timeline for when, but I'll try and give it a go either this weekend or next.

**Comment by prd-fox** [comment]
I (finally) got around to taking a look at implementing this, and came across the `ParseResult#asCommandLineList` method. This takes care of a large amount of the heavy lifting, as at that point it is just looping over the list and seeing which of the the commands give a non-`null` execution result.

I'm no longer convinced implementing my request above gives any major benefit, especially as how it will not work in cases of multiple execution results, and may be confusing.

My only concern is this attached note to the method: `* For backwards compatibility with pre-3.0 methods. */`. Does this mean it is likely to marked as deprecated at some point, and if so, can I use this issue to make the case against that?

**Comment by remkop** [comment]
Thanks for pointing that out.

At the time, I was introducing the `ParseResult` class and I was thinking to eventually deprecate the `asCommandList` method. However, we are now 18 months later, it is still used internally and I find it convenient to use as well. There is no need to remove it.

I clarified the javadoc.

**Comment by prd-fox** [comment]
Thanks @remkop. As I said, I don't think this is worth the extra complexity is understanding its use cases, since it is limited and users may use it being unaware. If you still think it is worth adding, please leave the issue open, otherwise close it - I won't be making the change unless some other compelling reason presents itself.

**Comment by remkop** [comment]
All good. Closing this ticket.
