### ISSUE TITLE
ArgGroup validate ignored (4.0.3)

### ISSUE THREAD

**Issue by cranphin** [remkop/picocli#807]
With Java 11, Picocli 4.0.3:
I would expect this code to accept '-s -v' as arguments, since validate is set to false:
```java
import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Option;

public class ArgTest implements Runnable {

    @ArgGroup(validate = false, heading = "%nGlobal options:%n")
    protected GlobalOptions globalOptions = new GlobalOptions();

    static class GlobalOptions {
        @Option(names = "-s", description = "ssss")
        boolean slowClock = false;

        @Option(names = "-v", description = "vvvv")
        boolean verbose = false;
    }

    public static void main(String[] args) {
        new CommandLine(new ArgTest()).execute(args);
    }

    @Override
    public void run() {
    }
}
```

Instead I get:
```
Error: -s, -v are mutually exclusive (specify only one)
Usage: <main class> [-sv]

Global options:
  -s     ssss
  -v     vvvv
```

**Comment by remkop** [comment]
Thank you for raising this! This certainly looks like a bug. I will take a look.

**Comment by remkop** [comment]
Thanks again for the bug report!
I pushed a fix to master.
Can you verify?

**Comment by remkop** [comment]
I went ahead and included the fix in the picocli 4.0.4 release that I just published to Maven.
Please let me know if there are still any issues.
Thanks again for raising this!

**Comment by cranphin** [comment]
It certainly solves my use case, awesome! :)

**Comment by remkop** [comment]
Great! If you like the project please star it on GitHub and tell your friends! ;-)
