### ISSUE TITLE
Output completion script as a subcommand in an existing command

### ISSUE THREAD

**Issue by gastaldi** [remkop/picocli#809]
It would be nice if there was an option to output the bash or zsh script for a given command through a Subcommand. 

eg.
`checksum completion zsh` outputs the ZSH script in the standard out, making it possible to do something like:

```bash
source <(checksum completion zsh)
```

**Comment by remkop** [comment]
That is a good idea! You can already accomplish this with the building blocks that the library provides (see example below), but it may be good to add something to the documentation, perhaps show this example in the [TAB Autocomplete](https://picocli.info/#_tab_autocomplete) section of the user manual (`docs/index.adoc`). Would you be able to provide a pull request to update the doc? Feel free to alter the example as needed.

```java
import picocli.AutoComplete;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "mycommand", subcommands = Completion.class)
public class CommandWithCompletionSubcommand implements Runnable {

    @Override // top-level command business logic here
    public void run() { }

    public static void main(String[] args) {
        new CommandLine(new CommandWithCompletionSubcommand()).execute(args);
    }
}

@Command(name = "completion",
        description = "Generate a completion script for the parent command")
class Completion implements Runnable {

    @Override
    public void run() {
        System.out.println(
                AutoComplete.bash("mycommand", spec.parent().commandLine()));
    }
}
```

**Comment by remkop** [comment]
@gastaldi  Thanks again for raising this!

Your suggestion is now part of the documentation: https://picocli.info/autocomplete.html#_distribution

**Comment by remkop** [comment]
Reopening since I am considering adding a `GenerateCompletion` subcommand implementation.

```java
import picocli.AutoComplete;
import picocli.CommandLine.Spec;

@Command(name = "generate-completion",
       hidden = true, // TBD
  description = "Generate bash/zsh completion script for ${PARENT-COMMAND-NAME}")
class GenerateCompletion implements Runnable {

    @Spec CommandLine.Model.CommandSpec spec;

    public void run() {
        String script = AutoComplete.bash(
                spec.parent().name(),
                spec.parent().commandLine());
        System.out.println(script);
    }
}
```
