### ISSUE TITLE
Negatable boolean @Option with default value "true" is not negated as expected

### ISSUE THREAD

**Issue by YannRobert** [remkop/picocli#813]
Hi

I have a boolean `Option` that I want to be `true` by default.
I also want the user to be able to set this option to `false`.

I want the `Option` name to be explicit enough to be self-documenting (actual code provides a description though)
The ```--(no-)option``` modifier seems like a perfect fit at first. Even if ```--option``` is redundant with default value.

In order to do this, I use the following code : 

```
	@CommandLine.Option(
			names = "--demote-first",
			defaultValue = "true",
			negatable = true
	)
	private boolean demoteFirst;
```

Using latest version as of now (version 4.0.4)

When default value is `true` : 
- using the negative modifier of a boolean `Option` does not change the value to `false`.
- using the `Option` does change the value to `false`

I think this is counter intuitive.
Is this the expected behavior ?

In order to avoid this, I have to change the code to : 

make the `Option` not `negatable` (this is my favorite)
```
	@CommandLine.Option(
			names = "--no-demote-first",
			defaultValue = "true"
	)
	private boolean demoteFirst;
```

or

make the `Option` `negatable` and also `required` (without any default value otherwise `required` is ignored)
```
	@CommandLine.Option(
			names = "--demote-first",
			//defaultValue = "true",
			negatable = true,
			required = true
	)
	private boolean demoteFirst;
```

For Options with a `false` default value, we do not observe this.

This means that usage is not consistant depending on the default value.

**Comment by remkop** [comment]
You raise a good point. Double negatives are always a source of confusion... 

If your option is called `--no-demote-first`, then its "negated form" is `--demote-first`. The negated form sets the default value. The original form (`--no-demote-first`) sets the opposite of the default value.

Inspired by your feedback, I updated the user manual: https://picocli.info/#_negatable_options
Can you take a look and let me know if that is sufficient?

**Comment by remkop** [comment]
@YannRobert Sorry if I wasn't clear.

You can still make the option negatable, even if you give it the name `--no-demote-first`:

```java
@Option(names = "--no-demote-first", defaultValue = "true", negatable = true)
private boolean demoteFirst;
```

When the user specifies `--no-demote-first`, the value is set to `false` (the opposite of the default). When the user specifies the negated form `--demote-first`, the value is set to `true` (the default).

I believe this is how it should work. The key is to name the option `--no-xxx` when the default value is "true".

Does that make sense?

**Comment by remkop** [comment]
@YannRobert I added this test. I believe it is working as expected.

```java
@Test
public void testIssue813() {
    class App {
        @Option(names = "--no-xxx", defaultValue = "true", negatable = true)
        boolean xxx;

        @Option(names = "--yyy", defaultValue = "false", negatable = true)
        boolean yyy;
    }

    App app = new App();
    new CommandLine(app).parseArgs("--xxx", "--yyy");
    assertTrue(app.xxx);
    assertTrue(app.yyy);

    new CommandLine(app).parseArgs("--no-xxx", "--no-yyy");
    assertFalse(app.xxx);
    assertFalse(app.yyy);
}
```

Is this useful to help resolve the issue?

**Comment by YannRobert** [comment]
Hi @remkop 

I think your addition to the documentation is helping very much.

Also you additional test is helping,

but I would complete the test like this, maybe :

```java
	@Test
	public void testIssue813_you_probably_should_not_use_it_this_way() {
		// see doc : Negatable options that are true by default
		class AppDont {
			@CommandLine.Option(names = "--zzz", defaultValue = "true", negatable = true)
			boolean zzz;
		}

		AppDont app;

		app = new AppDont();
		new CommandLine(app).parseArgs();
		assertTrue(app.zzz);

		app = new AppDont();
		new CommandLine(app).parseArgs("--zzz");
		assertFalse(app.zzz); // don't expect true

		app = new AppDont();
		new CommandLine(app).parseArgs("--no-zzz");
		assertTrue(app.zzz); // don't expect false

	}

	@Test
	public void testIssue813_but_you_probably_should_do_this() {
		// see doc : Negatable options that are true by default
		class AppDo {
			@CommandLine.Option(names = "--no-zzz", defaultValue = "true", negatable = true)
			boolean zzz;
		}

		AppDo app;

		app = new AppDo();
		new CommandLine(app).parseArgs();
		assertTrue(app.zzz);

		app = new AppDo();
		new CommandLine(app).parseArgs("--zzz");
		assertTrue(app.zzz);

		app = new AppDo();
		new CommandLine(app).parseArgs("--no-zzz");
		assertFalse(app.zzz);

	}
```

**Comment by remkop** [comment]
@YannRobert  Excellent, glad to hear that!
I will add your suggested tests when I get a chance.

If you like picocli, please star the project on GitHub and tell your friends! :sweat_smile:

**Comment by remkop** [comment]
P.S. Your contribution is mentioned in the [release notes](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md#-picocli-405-unreleased) for picocli 4.0.5.

**Comment by YannRobert** [comment]
Thanks 👍
