### ISSUE TITLE
Picocli clashes with auto-service

### ISSUE THREAD

**Issue by martinpaljak** [remkop/picocli#825]
If I use both picocli and auto-service in the same Maven build, it fails with a cryptic "unknown compilation error" exception and as much information in the trace.

What helps is adding the picocli annotation processor and specifying both picocli and google auto-service as annotation processors:
```
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-compiler-plugin</artifactId>
+                <version>3.8.1</version>
+                <configuration>
+                    <annotationProcessorPaths>
+                        <path>
+                            <groupId>info.picocli</groupId>
+                            <artifactId>picocli-codegen</artifactId>
+                            <version>4.0.4</version>
+                        </path>
+                        <path>
+                            <groupId>com.google.auto.service</groupId>
+                            <artifactId>auto-service</artifactId>
+                            <version>1.0-rc6</version>
+                        </path>
+                    </annotationProcessorPaths>
+                    <compilerArgs>
+                        <arg>-Aproject=${project.groupId}/${project.artifactId}</arg>
+                    </compilerArgs>
+                </configuration>
+            </plugin>
```

**Comment by remkop** [comment]
Can you provide more details on the configuration where the error occurred so I can try to reproduce?

**Comment by martinpaljak** [comment]
Here you go: https://github.com/martinpaljak/picocli-issue. Just having two dependencies without configuring preprocessor will make the mvn build fail with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project picocli-issue-show: Compilation failure
[ERROR] An unknown compilation problem occurred
```

**Comment by remkop** [comment]
I suspect that it’s the `com.google.auto.service:auto-service` dependency rather than picocli. 

Picocli’s annotation processor is in a separate module, `picocli-codegen`, whereas in the `auto-service` case there’s one module that’s both a dependency and an annotation processor. 

You can try by removing the  `picocli-codegen` configuration from the annotation processor  config section (and only leaving the `auto-service` annotation processor  config). My theory is that this will also fix the “unknown compilation problem” issue.

**Comment by martinpaljak** [comment]
Would be nice if I should not be required to change anything, as both dependencies work as expected separately, but no when used together. Is this a bug for auto-service instead?

**Comment by remkop** [comment]
With my version of Maven, I see this warning:

```
[WARNING] Some problems were encountered while building the effective model for com.github.martinpaljak:picocli-issue-show:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ line 42, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```

Version info:
```
C:\Users\remko\IdeaProjects\picocli-issue825>mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T16:58:13+09:00)
Maven home: C:\apps\apache-maven-3.5.2\bin\..
Java version: 1.8.0_202, vendor: Oracle Corporation
Java home: C:\apps\jdk1.8.0_202\jre
Default locale: en_GB, platform encoding: MS932
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by remkop** [comment]
I think the problem may have been this compiler arg, which disallows any warnings:

```
<arg>-Werror</arg>
```

The below configuration now works for me:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <artifactId>picocli-issue-show</artifactId>
    <groupId>com.github.martinpaljak</groupId>
    <version>0.0.1-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
            <version>4.0.4</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <version>1.0-rc6</version>
            <optional>true</optional>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <compilerArgs>
                        <arg>-Xlint</arg>
<!--                        <arg>-Werror</arg>-->
                        <arg>-Aproject=${project.groupId}/${project.artifactId}</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
<!--                        <path>-->
<!--                            <groupId>info.picocli</groupId>-->
<!--                            <artifactId>picocli-codegen</artifactId>-->
<!--                            <version>4.0.4</version>-->
<!--                        </path>-->
<!--                        <path>-->
<!--                            <groupId>com.google.auto.service</groupId>-->
<!--                            <artifactId>auto-service</artifactId>-->
<!--                            <version>1.0-rc6</version>-->
<!--                        </path>-->
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

You can optionally un-comment any of the annotation processors, or both, and the build will not fail.

**Comment by martinpaljak** [comment]
Compiling with `-Werror` is a perfectly sane thing and I'll not remove that. I did not see any visual warnings? Is there a silent exit code swallowing or something similar taking place? Who emits the warning? This seems like a bug or missing assumption/documentation, but where exactly... maven compiler plugin? auto-service? picocli? As there is no sensible indication of failure, could be maven compiler plugin instead ?

**Comment by remkop** [comment]
I don't see compiler warnings on the command line with Maven, but there may be an option to show them. When building in the IDE I see these warnings:

* Warning:Output path C:\Users\remko\IdeaProjects\picocli-issue825\target\generated-sources\annotations intersects with a source root. Only files that were created by build will be cleaned.
* Warning:java: Supported source version 'RELEASE_6' from annotation processor 'picocli.codegen.aot.graalvm.processor.NativeImageConfigGeneratorProcessor' less than -source '1.8'
* Warning:java: No processor claimed any of these annotations: picocli.CommandLine.Option,picocli.CommandLine.Command,com.google.auto.service.AutoService

I plan to fix the "Supported source version 'RELEASE_6'" warning in the next picocli-codegen release. (See #826)

As far as the other warnings are concerned; it is normal to have annotations that are not processed (see https://github.com/spring-projects/spring-boot/issues/6421 for a discussion on the same warning for Spring's `@SpringBootApplication` annotation). You may like the workaround [suggested](https://github.com/spring-projects/spring-boot/issues/6421#issuecomment-273907960) in that ticket:

> You can add `-Xlint:-processing` to your compiler arguments to silence this warning. You can combine this with `-Xlint` or `-Xlint:all` to still run lint on everything else.

**Comment by martinpaljak** [comment]
Indeed, adding `<arg>-Xlint:-processing</arg>` makes things work and I think will be for now my preferred solution. I think this is a bug for Maven to give sensible errors (as the behavior is here with v3.6.2). Their Jira seems so ...  inaccessible to normal folks, unfortunately, and contains a bunch of issues related to annotation processing.

**Comment by remkop** [comment]
The compilation warnings themselves are probably generated by javac, but the fact that they are not printed to the console by default with Maven makes it difficult to understand what is going on...

**Comment by martinpaljak** [comment]
Filed an issue with maven-compiler-plugin as well. https://issues.apache.org/jira/browse/MCOMPILER-401

Will see if #826 changes anything before closing this one.

Thanks!

**Comment by remkop** [comment]
#826 will make only one of the three warnings go away, so by itself is not enough to allow `-Werror`. 
You will still need `-Xlint:-processing` even after #826. 

Thanks for raising the Maven Compiler [issue](https://issues.apache.org/jira/browse/MCOMPILER-401) to not suppress warning details.

Can this ticket be closed, or is there any work remaining?

**Comment by martinpaljak** [comment]
A note https://picocli.info/#_getting_started would be great! Other than that, I think the issue is in fact with Maven and this here can be closed.

**Comment by remkop** [comment]
That’s great to hear!
