### ISSUE TITLE
Runtime autocompletion

### ISSUE THREAD

**Issue by Rubydesic** [remkop/picocli#831]
I've been using this library for writing a Minecraft mod. Tab-autocompletion with Minecraft Forge is evaluated at runtime. For example, if a user types the command

`/command auto<tab>`

I have to return a `List<String>` of things that they might've been looking for, like `[autocomplete, automobile]`. 

Frankly, I get very confused trying to understand the code to generate bash autocompletion scripts and I don't think they're terribly applicable to my use-case, so how should I go about doing this, esp. for options?

**Comment by remkop** [comment]
I agree that the bash autocompletion script stuff is not applicable.

However, the `AutoComplete` class also has a public static `complete` method that can generate completions into a list (the `candidates` parameter is an out-parameter: generated completions are added to this list).

You can see how it is used in the [PicocliJLineCompleter](https://github.com/remkop/picocli/blob/master/picocli-shell-jline2/src/main/java/picocli/shell/jline2/PicocliJLineCompleter.java) class in the `picocli-shell-jline2` project.  [This test](https://github.com/remkop/picocli/blob/master/src/test/java/picocli/AutoCompleteTest.java#L925) may also be helpful in understanding how the return value and other parameters are used.

Let me know if you have any questions.

**Comment by Rubydesic** [comment]
Thanks so much! The following code works for me for anyone else who may have this use-case:

```java
@Override
public List<String> getTabCompletions(MinecraftServer server, ICommandSender sender,
    final String[] splitArgs, @Nullable BlockPos targetPos) {
    // parse the args like a normal program instead of the string#split() way that forge does it. 
    String[] args = VSCommandUtil.toProperArgs(splitArgs); 

    CommandSpec spec = CommandSpec.forAnnotatedObject(new MyCommand());
    List<CharSequence> candidates = new ArrayList<>();

    if (args.length == 0) {
        AutoComplete.complete(spec, args, 0, 0, 500, candidates);
    } else {
        AutoComplete.complete(spec, args, args.length - 1,
            args[args.length - 1].length(), 500, candidates);
    }

    return candidates.stream()
        .distinct()
        .map(CharSequence::toString)
        .map(s -> args.length > 0 ? args[args.length - 1] + s : s)
        .collect(Collectors.toList());
}
```

**Comment by remkop** [comment]
Glad to hear that!

I started to look a bit at Minecraft Forge and custom commands. If picocli is useful to create custom commands, would it be interesting to do a write-up to show others how to do this? Or even publish the picocli-based implementation of `ICommand` as a library? Would this be interesting?

**Comment by Rubydesic** [comment]
Yea, definitely. Most Minecraft mods have very ugly homebrew command handling systems and this library is very helpful. I don't mind doing a write-up at all, I'm just sort of testing everything out and finding out how to implement it best.

My current implementation is in [Valkyrien Skies](https://github.com/ValkyrienSkies/Valkyrien-Skies/blob/5783ab7e7a38b64c16c37450096646b3475c61be/src/main/java/org/valkyrienskies/mod/common/command/framework/VSCommandBase.java) if you want to take a look at that.

**Comment by remkop** [comment]
Cool! For the factory, you may want to fall back to the `CommandLine.defaultFactory()` if your factory runs into an exception. For example:

```java
public class VSCommandFactory implements CommandLine.IFactory {
    private ICommandSender sender;

    VSCommandFactory(ICommandSender sender) {
        this.sender = sender;
    }

    @Override
    public <K> K create(Class<K> aClass) {
        // first try constructor injection with a ICommandSender
        try {
            Constructor<K> constructor = aClass.getDeclaredConstructor(ICommandSender.class);
            constructor.setAccessible(true);
            return constructor.newInstance(sender);
        } catch (Exception ex) {
            // log error?
        }

        // fall back to the default picocli factory
        try {
            return CommandLine.defaultFactory().create(aClass);
        } catch (Exception ex) {
            throw new IllegalStateException("Could not instantiate " + aClass, ex);
        }
    }
}
```
