### ISSUE TITLE
No issues at all - an amazing piece of software :-)

### ISSUE THREAD

**Issue by sgoeschl** [remkop/picocli#838]
Hi Remko ,

just wanted to state the obvious - "picocli" is an amazing piece of software. So I added a big "thank you" here instead of the usual issues / bugs :-)

Siegfried Goeschl

**Comment by remkop** [comment]
Haha! 
Thank you!
Should I resolve this as “won’t fix”? :-)

**Comment by sgoeschl** [comment]
Well, either "won't fix" or "done" ...

**Comment by ddsharpe** [comment]
I *second* that!  Well done! Thank you @remkop

**Comment by remkop** [comment]
@sgoeschl @ddsharpe 
‪Sorry if this is a bit late, but I want to ask 2 things:‬
‪* What is it about picocli that makes you happy with it?‬
‪* What would you do if picocli did not exist?‬
‪

**Comment by sgoeschl** [comment]
I used Apache commons-cli on a couple of command-line applications (mostly together with Groovy) and usually had some minor (but at least for me annoying) issues - e.g. to trigger online help without error message when mandatory command line arguments are defined. Having said that it is very likely my mistake - I could have spent more time on the documentation, maybe this was an issue fixed ages ago or I was not smart enough to fix my problem.

Some background: last year I migrate my Groovy & commons-cli code

* I noticed the Groovy is promoting picocli 
* Since I migrated the Groovy code to Java I hat to touch command-line processing code anyway
* I decided to give picocli a chance (while not being entirely eager to do so)

The things making me happy

* The examples & documentation got me going in short time - basically worked out of the box
* Whenever I need another feature I found it in the documentation and got it working, e.g. version provider

On an even more subjective level

* You clearly wanted to solve command line processing for JVM and put it in a tremendous amount of effort for a rather "un-sexy" topic
* I really appreciate that  since I know the pains of doing open source work

Without picocli I still would use Apache commons-cli :)

**Comment by ddsharpe** [comment]
Prior to using picocli, I used custom CLI code for each project.  Occasionally, I would use Apache commons-cli but found it too cumbersome for most things.  The number one benefit of picocli was the speed of getting started.  I was able to take a large number of parameters and jump right in to the business logic of my tools without having to spend a lot of time coding the parsing and basic validation.  The second benefit was the support of command line completion that I never had in any of my tools before.  Although, this feature still seems broken on Mac when certain characters are on the command line (like @).

**Comment by remkop** [comment]
@sgoeschl @ddsharpe Thank you for the feedback!

@ddsharpe autocompletion improvements ([positional parameter completion](https://github.com/remkop/picocli/pull/505), [MacOS improvements](https://github.com/remkop/picocli/issues/396), and [cleaned up shellcheck warnings](https://github.com/remkop/picocli/pull/671)) will be in the upcoming picocli v4.2.0 release. You can test by checking out the latest master and building with:

```
gradlew clean publishToMavenLocal
```

That should publish `picocli-4.2.0-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.0-SNAPSHOT` dependency. Feedback very welcome!

**Comment by remkop** [comment]
@sgoeschl and @ddsharpe Thank you again for your feedback! 😃 ❤️
