### ISSUE TITLE
Autocomplete for a File provided by @Parameters

### ISSUE THREAD

**Issue by yohanakh** [remkop/picocli#852]
I have a command with File that is retrieved by @Parameters.
I see if a parameter is retrieved via @Option and the type if file then the autocomplete works but not with @Parameters.
Is there a way to make it work? Is it planned to be supported in next versions?

**Comment by remkop** [comment]
Hi, there was some work in progress on improving bash completion for positional parameters (https://github.com/remkop/picocli/issues/468, there was even a pull request https://github.com/remkop/picocli/pull/505) but the last time I looked at it it still had issues. 

I’d be happy to improve this area but I currently don’t have time to work on it myself, so I’d need help. 

Would you be able to review and test the previous pull request, or alternatively provide a pull request yourself?

**Comment by remkop** [comment]
Fixed with https://github.com/remkop/picocli/pull/505
