### ISSUE TITLE
Printing help without specify help option 

### ISSUE THREAD

**Issue by kunlk** [remkop/picocli#854]
Hello,

Wonder to know if there is a way to print help without help option. For example, if I input git without option, I can have :

C:\Users\User.Name\git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

**Comment by remkop** [comment]
I added [this example](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/git/Git.java). Basically, in the `git` command's `run` method, show the usage help message.

**Comment by remkop** [comment]
@kunlk I added [this example](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/git/Git.java) that shows how to do this. Basically, in the `run` method of the top level command (`git` in our case), call `CommandLine.usage` to show the usage help message.

**Comment by kunlk** [comment]
@remkop thank you so much ! This is exactly what I want -:)

**Comment by remkop** [comment]
Glad to hear that! Enjoy using picocli!
