### ISSUE TITLE
Consider adding a picocli-minecraft module

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#855]
See https://github.com/remkop/picocli/issues/837

For reference: https://github.com/Mojang/brigadier

**Comment by Rubydesic** [comment]
Here is a very basic implementation designed for Minecraft Forge 1.12.2 (Versions below 1.13 do not use Brigadier, the library referenced above) 

https://github.com/Rubydesic/MinecraftPicocli

if there is demand I can look into updating the integration for different modding frameworks like Bukkit and different Minecraft versions.

**Comment by remkop** [comment]
Very nice! I added a link to MinecraftPicocli from the [picocli readme](https://github.com/remkop/picocli).
