### ISSUE TITLE
Support documentation of Environment variables

### ISSUE THREAD

**Issue by sdavids** [remkop/picocli#856]
It would be nice if one could also document environment variables.

Something along the lines:

``` shell
$ foo help
Usage: foo [COMMAND]
Creates foos.
Commands:
  new      Creates a new foo
  help     Displays help information about the specified command
Exit Codes:
   0   Success
Environment Variables:
  FOO_CREATOR   The foo's creator
```

**Comment by remkop** [comment]
@sdavids This can be done with a [custom help section](file:///C:/Users/remko/IdeaProjects/picocli3/build/docs/html5/index.html#_reordering_sections).

I added [an EnvironmentVariablesSection example](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/customhelp/EnvironmentVariablesSection.java) to show the details.

**Comment by sdavids** [comment]
Thanks, please close ...

**Comment by remkop** [comment]
@sdavids If you like the project, please star picocli on GitHub and tell your friends! :wink:

**Comment by remkop** [comment]
@sdavids the next version of picocli will have more convenient API for this. See https://github.com/remkop/picocli/issues/865
