### ISSUE TITLE
Create Architecture (Internal?) Docs

### ISSUE THREAD

**Issue by akamanocha** [remkop/picocli#858]
This is in reference to Micronaut at large. And is an enhancement request not a bug.

Reference to this issue
https://github.com/micronaut-projects/micronaut-core/issues/445

@graeme suggested that there could be separate issue raised for creating architecture docs.

The rationale for the same could be:

- It will give more contributors to the project, may be?, cause the consumers of this would be core developers / contributors at large and thus it's not just user guide.
- It will also help in self led contribution from other projects let's say @nats_io for example who have expertise in their project but don't have heady start in micronaut.
- It will give the good looking architecture diagram too :) in short
- It will be a good nice back also to ASM, and APT

A random view on who should take this PR / do it? 
I can also help, but I am not very well versed with ASM, and Annotation Processing (and I am not bringing the groovy and kotlin support here)
Individual effort so far have taken me to io.micronaut.annotation.processing. BeanDefinitionInjectProcessor just to build on, my idea is to reach to a component level diagram in the end with the explanation text of course, to give out the doc that how does the framework boots up.

**Comment by remkop** [comment]
@akamanocha I think your intention was to raise this ticket in the Micronaut project instead of the picocli project. You may want to raise a new ticket in the Micronaut project. 

It sounds like an interesting effort. Graeme’s recent presentation may be useful. 

Slides: https://www.slideshare.net/graemerocher/micronaut-deep-dive-devoxx-belgium-2019

Video: https://www.youtube.com/watch?v=S5yfTfPeue8

**Comment by akamanocha** [comment]
Oh yes! such a bad start to week. Awful Monday morning. But many thanks! I will correct the mistake.

**Comment by remkop** [comment]
@akamanocha No problem at all. Please try picocli in your projects, you may like it! :wink:
