### ISSUE TITLE
use different options base on parent option input

### ISSUE THREAD

**Issue by kunlk** [remkop/picocli#859]
Hello,

Is there a way to implement something like sub-options. The term sub-options may not appropriate, so let me explain my requirement:

Like I have a CTL name as myctl and one command 'config'.  There is an option '-t' that represent different type.  If I input -t A, I would like have options A1 and A2, if I input -t B, I would like have options B1 and B2.

myctl config -t type

if(type.equals("A"))
	use option -A1  -A2
	
if(type.equals("B"))
	use option -B1  -B2

**Comment by remkop** [comment]
Do you mean validation? So, if the user specified `-t=A -B1`, you want to show an error message?

Picocli cannot do that, so you would need to code this validation logic in your application:

```java
enum MyType { A, B }

@Command(name = "config")
class Config implements Callable<Integer> {
    @Option(names = {"-t", "--type"}, required = true) MyType myType;

    @Option(names = "-A1") String a1;
    @Option(names = "-A2") String a2;
    @Option(names = "-B1") String b1;
    @Option(names = "-B2") String b2;

    public Integer call() {
        if (myType == MyType.A && (b1 != null || b2 != null)) {
            System.err.println("Options -B1 or -B2 cannot be used with --type=A");
            return picocli.CommandLine.ExitCode.USAGE;
        } else if (myType == MyType.B && (a1 != null || a2 != null)) {
            System.err.println("Options -A1 or -A2 cannot be used with --type=B");
            return picocli.CommandLine.ExitCode.USAGE;
        }
        // we have a valid combination of options... let's do the business logic
    }
}

@Command(name = "myctl", subcommands = Config.class)
class MyCtl implements Callable<Integer> {
    public Integer call () {
        System.err.println("Specify a subcommand");
        return picocli.CommandLine.ExitCode.USAGE;
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new MyCtl()).execute(args);
        System.exit(exitCode);
    }
}
```

**Comment by kunlk** [comment]
@remkop sorry I may not describe the things clearly, the question is if I input the command 
myctl config -t A  
How could the Picocli prompt the  option A1 and A2 are missing ?

**Comment by kunlk** [comment]
And yes, I can code that logic in application, such as if the user input myctl config -t A and enter ,

public Integer call() {
        if (myType == MyType.A && (a1 == null || a2 == null)) {
            System.err.println("Options -A1 or -A2 are missing be used with --type=A");
            return picocli.CommandLine.ExitCode.USAGE;
        }
    }

But just want to know if there is built-in API to handle this .

**Comment by remkop** [comment]
Understood. Picocli cannot do _conditional_ validation like you describe: options `-A1` and `-A2` are only mandatory if `--type=A` was specified, but are not mandatory with `--type=B`.

If you need that exact behaviour you would need to code it in the application, like in the above example.

However, picocli _does_ have argument groups, which you can use to define [mutually dependent options](https://picocli.info/#_mutually_dependent_options). This allows you to make options `-A1` and `-A2` mandatory if the `--typeA` option was specified, and `-B1` and `-B2` mandatory if the `--typeB` option was specified. Note that for this to work you will have separate `--typeA` and `--typeB` options, instead of a single `--type=<type>` option.

**Comment by kunlk** [comment]
@remkop I read the mutually dependent options, but I still prefer to use one generic type options. So I will handle the logic in my app. Thanks again for your quick response and kindly help!

**Comment by remkop** [comment]
You are welcome! :smiley: 
I will close this ticket but feel free to open another one if you have more questions.
