### ISSUE TITLE
Loading CommandLine$DefaultFactory fails on Windows?!

### ISSUE THREAD

**Issue by sormuras** [remkop/picocli#863]
Hi!

I just created the following issue at https://bugs.openjdk.java.net/browse/JDK-8234076 to determine the underlying cause of a Windows-only fatal error when launching JUnit 5's Console Launcher. That in turn uses Picocli version `4.0.2`, I guess.

Sometimes(!) a run either crashes silently or creates a `hs_err_pid...log` file and the last class that was loaded is:

`[0.278s][info][class,load] org.junit.platform.console.shadow.picocli.CommandLine$IExecutionExceptionHandler source: file:/.../lib/org.junit.platform.console-1.6.0-M1.jar`

Sometimes(!) the run continues with `CommandLine$DefaultFactory` and the entire program execution succeeds.

`[0.231s][info][class,load] org.junit.platform.console.shadow.picocli.CommandLine$DefaultFactory source: file:/.../lib/org.junit.platform.console-1.6.0-M1.jar`

Could this be related to #794?

### Reproduction

- Clone https://github.com/sormuras/bach-air - and switch to branch `JDK-8234076`.
- Call `java src\bach\Build.java`. Sometimes it runs, sometimes not.

### CI

- Java 11 https://github.com/sormuras/bach-air/runs/300828140
- Java 13 https://github.com/sormuras/bach-air/runs/300828148

![image](https://user-images.githubusercontent.com/2319838/68763255-4c75ed00-0618-11ea-9dd3-fbe66f761ae7.png)

**Comment by sormuras** [comment]
Using SNAPSHOT version of JUnit Platform Console, which shadows Picocli `4.0.4`, also shows an error like above.

**Comment by remkop** [comment]
Hi @sormuras that looks nasty. I’ve looked at the JDK ticket but nothing jumped out at me yet. I will try to reproduce this tomorrow. 

About your question: I am fairly sure that #794 is not related. The annotation processor only runs at compile time, while the issue you describe happens at runtime.

**Comment by sormuras** [comment]
With required modules located in `lib/`, running

`java --module-path=lib --module=org.junit.platform.console --help`

does provoke the error. Sometimes.

Omitting the `=` characters does **NOT** provoke the error...

`java --module-path lib --module org.junit.platform.console --help`

🤔

**Comment by sormuras** [comment]
The `=` between `module` and `org.junit.platform.console` causes the error. Having `--module-path=lib` is fine.

**Comment by remkop** [comment]
Nice detective work!

If I clone the project, and run 

```
%JAVA_11_HOME%\bin\java src\build\Build.java
```

I see this:

```
...
C:\Users\remko\IdeaProjects\bach-air>%JAVA_HOME%\bin\java src\build\Build.java
Build.java
| javac --version
javac 11
| jar --version
jar 11
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.jupiter:junit-jupiter:5.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.jupiter:junit-jupiter-api:5.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.jupiter:junit-jupiter-engine:5.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.jupiter:junit-jupiter-params:5.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.platform:junit-platform-commons:1.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.platform:junit-platform-console:1.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.platform:junit-platform-engine:1.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.platform:junit-platform-launcher:1.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.junit.platform:junit-platform-reporting:1.6.0-M1
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.apiguardian:apiguardian-api:1.1.0
| cmd /C mvn --quiet org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -DoutputDirectory=lib -Dtransitive=false -Dartifact=org.opentest4j:opentest4j:1.2.0
Compile main modules
| javac --module=de.sormuras.bach.air --module-source-path=src/*/main/java --module-path=lib -d bin/build/main/classes
| jar --create --file=bin/build/main/modules/de.sormuras.bach.air.jar -C bin/build/main/classes/de.sormuras.bach.air .
| jar --describe-module --file=bin/build/main/modules/de.sormuras.bach.air.jar
de.sormuras.bach.air jar:file:///C:/Users/remko/IdeaProjects/bach-air/bin/build/main/modules/de.sormuras.bach.air.jar/!module-info.class
exports de.sormuras.bach.air
requires java.base mandated

Compile test modules
| javac --module=it,de.sormuras.bach.air --module-source-path=src/*/test/java;src/*/test/module --module-path=bin/build/main/modules;lib --patch-module=de.sormuras.bach.air=src/de.sormuras.bach.air
/main/java -d bin/build/test/classes
| jar --create --file=bin/build/test/modules/it.jar -C bin/build/test/classes/it .
| jar --describe-module --file=bin/build/test/modules/it.jar
it jar:file:///C:/Users/remko/IdeaProjects/bach-air/bin/build/test/modules/it.jar/!module-info.class open
requires de.sormuras.bach.air
requires java.base mandated
requires org.junit.jupiter
contains it

| jar --create --file=bin/build/test/modules/de.sormuras.bach.air.jar -C bin/build/test/classes/de.sormuras.bach.air .
| jar --describe-module --file=bin/build/test/modules/de.sormuras.bach.air.jar
de.sormuras.bach.air jar:file:///C:/Users/remko/IdeaProjects/bach-air/bin/build/test/modules/de.sormuras.bach.air.jar/!module-info.class open
exports de.sormuras.bach.air
requires java.base mandated
requires org.junit.jupiter

Running tests per module
| C:\apps\jdk-11\bin\java.exe --module-path=bin/build/test/modules/it.jar;bin/build/main/modules;bin/build/test/modules;lib --add-modules=it --module=org.junit.platform.console --select-module=it
Exception in thread "main" java.lang.Error: Non-zero exit code: -1073740940
        at Build.start(Build.java:123)
        at Build.main(Build.java:67)
```

**Comment by sormuras** [comment]
> Exception in thread "main" java.lang.Error: Non-zero exit code: -1073740940

Aye. This is the other way the process fails, sometimes. Repeat the `%JAVA_11_HOME%\bin\java src\build\Build.java` some more times, and eventually a fatal error is logged.

**Comment by sormuras** [comment]
Or just copy and execute the last command:

```
C:\apps\jdk-11\bin\java.exe --module-path=bin/build/test/modules/it.jar;bin/build/main/modules;bin/build/test/modules;lib --add-modules=it --module=org.junit.platform.console --select-module=it
```

**Comment by sormuras** [comment]
Or, to limit the players involved:

`%JAVA_11_HOME%\bin\java --module-path=lib --module=org.junit.platform.console --help`

**Comment by sormuras** [comment]
...btw, I don't know if Picocli is the root cause here. Some thoughts:

- `java` supports the `=` character in long options as its `--help` text suggests at the end -- could be bug in the `java` launcher, though
- Module `org.junit.platform.console` shadows Picocli -- are we doing it right? Missing out some things?
- Why does it work approx. 4 out of 5 times?
- Why is only Windows affected?

**Comment by sormuras** [comment]
One last comment for the time being:

- Why does the crashing process stop after loading a bunch of `org.junit.platform.console.shadow.picocli.CommandLine$...` types?
- If the process does not crash, the class loaded directly after the "bunch" is: `org.junit.platform.console.shadow.picocli.CommandLine$DefaultFactory`

`java -verbose:class --module-path=lib --module=org.junit.platform.console --help`

**Comment by sormuras** [comment]
_sigh_

Got a new one, using exactly the command from above:
- Console log excerpt: https://gist.github.com/sormuras/c475f230c61fca0fb75f8efdc78dc4a2
- HotSpot error log: [hs_err_pid452.log](https://github.com/remkop/picocli/files/3844584/hs_err_pid452.log)

Interesting to see, that `--module=org.junit.platform.console` is transformed to `-Djdk.module.main=org.junit.platform.console org.junit.platform.console`

**Comment by remkop** [comment]
I tried adding these options: "-Xcheck:jni", "-XX:+ShowMessageBoxOnError", "-verbose:jni", "-verbose:class", and the problem stopped occuring. I have not been able to reproduce it any more, even after reverting my changes.

* If the problem is really related to the `=` character in `--module=org.junit.platform.console`, then I agree that suggests a problem in the `java` launcher rather than a problem in picocli; still weird that it would not occur in the JVM process startup but later...
* I looked at the `org.junit.platform.console`; I could not spot anything unusual; maybe add `--version`?

**Comment by remkop** [comment]
Weird: in that last crash, the thread that got the access violation is tid=8: WatcherThread (not the main thread)

```
=>0x0000021ccb0f3000 WatcherThread [stack: 0x0000008cf1600000,0x0000008cf1700000] [id=8]
```

**Comment by sormuras** [comment]
Added all 4 options 

`java -Xcheck:jni -XX:+ShowMessageBoxOnError -verbose:jni -verbose:class --module-path=lib --module=org.junit.platform.console --help`

and got:

![image](https://user-images.githubusercontent.com/2319838/68826961-88ed2b80-06a0-11ea-8eea-436f48149968.png)

**Comment by sormuras** [comment]
And again, omit the `=` ... and the error doesn't happen anymore. 😕

**Comment by remkop** [comment]
Ok, I can reproduce that, about once every 10-15 invocations.

**Comment by sormuras** [comment]
_Smells like a race condition of some kind..._

**Comment by remkop** [comment]
One of my crashed was in the VM Thread (but the process dump shows the WatcherThread is absent - ??):

```
Other Threads:
=>0x000002c32c6ab000 VMThread "VM Thread" [stack: 0x000000d1e0b00000,0x000000d1e0c00000] [id=24348]
  0x000002c3098cc800 GCTaskThread "GC Thread#0" [stack: 0x000000d1e0000000,0x000000d1e0100000] [id=26776]
  0x000002c3098ce800 GCTaskThread "GC Thread#1" [stack: 0x000000d1e0100000,0x000000d1e0200000] [id=25936]
  0x000002c3098d1800 GCTaskThread "GC Thread#2" [stack: 0x000000d1e0200000,0x000000d1e0300000] [id=18452]
  0x000002c3098d7800 GCTaskThread "GC Thread#3" [stack: 0x000000d1e0300000,0x000000d1e0400000] [id=15344]
  0x000002c309924800 ConcurrentGCThread "G1 Main Marker" [stack: 0x000000d1e0400000,0x000000d1e0500000] [id=5364]
  0x000002c309925800 ConcurrentGCThread "G1 Conc#0" [stack: 0x000000d1e0500000,0x000000d1e0600000] [id=19912]
  0x000002c329904800 ConcurrentGCThread "G1 Refine#0" [stack: 0x000000d1e0600000,0x000000d1e0700000] [id=17640]
  0x000002c329905000 ConcurrentGCThread "G1 Refine#1" [stack: 0x000000d1e0700000,0x000000d1e0800000] [id=26116]
  0x000002c329906000 ConcurrentGCThread "G1 Refine#2" [stack: 0x000000d1e0800000,0x000000d1e0900000] [id=18440]
  0x000002c329909000 ConcurrentGCThread "G1 Refine#3" [stack: 0x000000d1e0900000,0x000000d1e0a00000] [id=25204]
  0x000002c32990c800 ConcurrentGCThread "G1 Young RemSet Sampling" [stack: 0x000000d1e0a00000,0x000000d1e0b00000] [id=25924]
```

**Comment by sormuras** [comment]
Further runs are "recorded" here: https://twitter.com/shipilev/status/1194894927915823104

**Comment by sormuras** [comment]
Finally managed to create a minimal example that shows the issue.

Project: https://github.com/sormuras/JDK-8234076
CI build log: https://github.com/sormuras/JDK-8234076/runs/303494999

##### `java --module-path=mods --module com.greetings/com.greetings.Main --help`
Using `--module NAME`: `First application arg index: 4` with `argv[4] = --help`

##### `java --module-path=mods --module=com.greetings/com.greetings.Main --help`
Using `--module=NAME`: `First application arg index: -1` with `argv[3] = --help`

**Comment by sormuras** [comment]
FYI: https://mail.openjdk.java.net/pipermail/core-libs-dev/2019-November/063573.html

Closing this issues, as Picocli is not the root of the bug.

**Comment by remkop** [comment]
Thanks for the update, and again, nice detective work! :-)

**Comment by sormuras** [comment]
Fix merged to OpenJDK, will ship with JDK 14: https://github.com/openjdk/jdk/commit/ce7ede95eb1c3ad99d4654bdcbc2574013461bd3

**Comment by remkop** [comment]
Very nice!!
