### ISSUE TITLE
spring-boot-starter example uses single hard-wired command

### ISSUE THREAD

**Issue by unixunion** [remkop/picocli#869]
Hi, I am trying to create a scaffold for a multiple command and subcommand project, and the example for spring-boot-starter very specifically wires only a single command into the run method.

        @Override
	public void run(String... args) throws Exception {
		exitCode = new CommandLine(myCommand, factory).execute(args);
	}

I am at a bit of a loss for how to get this to work for multiple commands and sub-commands, as I would like to rely on the annotations for them.  Can you please tweak the example for two commands with sub-commands so I can follow this better

**Comment by remkop** [comment]
Hi, please take a look at the sample command in the tests: https://github.com/remkop/picocli/blob/master/picocli-spring-boot-starter/src/test/java/picocli/spring/boot/autoconfigure/sample/MyCommand.java

The main command has a subcommand, which itself also has a sub-subcommand. 
Would that help?

Note that an application always has one entry point, so there will always be one top-level command that starts the application (with as many subcommands as you like), but perhaps this is a terminology issue?

**Comment by remkop** [comment]
Perhaps we can make it easier to explain with a concrete example. What is your application called, and what are some of the multiple commands and subcommands called in your project?

**Comment by unixunion** [comment]
Thanks, with this I managed to figure it out.

**Comment by remkop** [comment]
Glad to hear that!
Please star the project on github if you like it and tell your friends! :-)
