### ISSUE TITLE
ArgGroup - requiring one of several password types if userid is provided

### ISSUE THREAD

**Issue by ddsharpe** [remkop/picocli#873]
This may be user error, but I cannot seem to figure out the right combination (and assuming its a bug, or not implemented yet).

The behavior that I am after:  If the user specifies a userid on the command line (like -u remmy), then password should be required.  This part works with the simple ArgGroup(exclusive = false) where the group options are required.  But when I say that password can be one of 3 options in a separate group, it all falls apart.  If I need the required password and the password can be either a file, an environment variable, or an interactive input, I don't seem to be able to make that work.

After numerous permutations, the closest I came to getting it working was:

```java
public class CredentialOptions {
    @Option(
        names = {"-u"},
        required = true,
        description = "user Id"
    )
   String userid;

    @ArgGroup(multiplicity = "1")
    PasswordOptions passwordOptions = new PasswordOptions();

    static class PasswordOptions {
        @Option(
            names = {"-p", "--password"},
            required = true,
            interactive = true,
            description = "interactive password entry"
        )
        String password;

        @Option(
            names = {"--passwordFile"},
            required = true,
            description = "path to file containing password"
        )
        Path passwordFile;
    }
} 
```

**Comment by ddsharpe** [comment]
After switching to 4.1.0, ArgGroup is working correctly (I think).  The only issue is the interactive password.  Without specifying the "-p" or "--password" on the CLI, the user is not prompted for the password.  My expectation for a required interactive was that the interface would prompt for it when not provided.

**Comment by remkop** [comment]
@ddsharpe Sorry for my late reply. 
Picocli currently requires the `-p` option to be specified before it prompts the user for the argument. (see also https://github.com/remkop/picocli/issues/800) 
However, I will look into if it is possible to do what you describe.

**Comment by ddsharpe** [comment]
Closing this issue, as I think the tool is working as designed.  Please continue to look into prompting for the password for mandatory interactives, as I think this would be more inline with most peoples' expectations.

**Comment by remkop** [comment]
@ddsharpe I created https://github.com/remkop/picocli/issues/882 for this.
