### ISSUE TITLE
Generation of autocomplete script: enforcement of required parameters

### ISSUE THREAD

**Issue by deining** [remkop/picocli#884]
I'm using the GenerateCompletion subcommand introduced with picocli 4.1 and stumbled across the following issue:

**Minimum example**
```
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

@Command(name="CompletionTest", subcommands = { picocli.AutoComplete.GenerateCompletion.class, CommandLine.HelpCommand.class } )
public class GenerateCompletionParametersTest implements Runnable {

    @Parameters(arity = "2..*")
    String[] file;
    
    public static void main(String[] args) {
        CommandLine cmd = new CommandLine(new GenerateCompletionParametersTest());
        cmd.execute(args);
    }

    @Override
    public void run() {
        System.out.println("Parameter given: " + file);
    }
}
```

I'm now running the command with command line args `generate-completion`:
While I expected to get the completion script as output, I was confronted with the following error message:

```
$ java GenerateCompletionParametersTest generate-completion
Missing required option 'params[0..*]=<file>'
Usage: CompletionTest <file> <file>... [COMMAND]
      <file> <file>...
Commands:
  generate-completion  Generate bash/zsh completion script for CompletionTest.
  help                 Displays help information about the specified command
```

While the error message is clear, it took me quite some time to realize what's wrong here:

Required parameters are enforced, so in order to get the completion script as output, you actually have to specify the required parameters:

```
$ java GenerateCompletionParametersTest file1 file2 generate-completion
#!/usr/bin/env bash
#
# CompletionTest Bash Completion
# =======================
#
...
```
This behaviour looks really weird to me. For my understanding the built-in subcommand `generate-completion` should be treated equal to the `help` subcommand. Parameters are **not** enforced when requesting usage help, and from my point of view, they shouldn't enforced when requesting the completion script via the built in subcommand either. From my point of view enforcing the parameters is not what the user expexts here.

What do you think?

**Comment by remkop** [comment]
You are absolutely correct. 
I can’t believe I missed that. 

The `GenerateCompletion` command should have `helpCommand = true` in its  `@Command` annotation. 

I pushed a test and a fix for this to master. Can you verify?

**Comment by deining** [comment]
I just verified, and yes, the subcommand now works like expected.

**Comment by remkop** [comment]
Thank you. I’ll probably do another release for this in a few days.
