### ISSUE TITLE
Subcommands hidden from usage help shown as suggestions

### ISSUE THREAD

**Issue by deining** [remkop/picocli#887]
**Minimal example**

```
1  import picocli.CommandLine;
2  import picocli.CommandLine.Command;
3
4  @Command(name="Completion", subcommands = { picocli.AutoComplete.GenerateCompletion.class, CommandLine.HelpCommand.class } )
public class CompletionSubcommandDemo implements Runnable {
6
7      public static void main(String... args) {
8          CommandLine cmd = new CommandLine(new CompletionSubcommandDemo());
9          CommandLine gen = cmd.getSubcommands().get("generate-completion");
10          gen.getCommandSpec().usageMessage().hidden(true);
11          cmd.usage(System.out);
12          // cmd.execute("ge");
13      }
14
15      @Override
16      public void run() {
17      }
18  }
```

If I run this, I'm getting:

```
Usage: Completion [COMMAND]
Commands:
  help  Displays help information about the specified command
```

Subcommand `generate-completion` is ommited from the command list, as requested in code.

No, remove comment in line 12 and comment out line 11. Run again, this time you are getting as output:

```
Unmatched argument at index 0: 'ge'
Did you mean: generate-completion?
```

What puzzles me here:
If one wants to omit the subcommand from the usage help message, there is most likely a good  reason for this. However, the suggestion for completion now exactly shows the subcommand that is supposed to be hidden from the usage help, which might be unwanted. IMHO, it were better here to exclude the `generate-completion` subcommand from the suggestions given. The same is true for tab completion that can be put in place for the command: here, once the user presses TAB after typing in the command name, the subcommand `generate-completion`is printed out as suggested command, too:

```
$ MyCommand
generate-completion   help
```

Bug or feature? What do you think?

**Comment by remkop** [comment]
It makes sense to exclude hidden subcommands from auto-completion or unmatched argument suggestions. Currently neither auto-completion nor the unmatched argument suggestions take `hidden` into account (for subcommands, but also for options and positional parameters)...

Perhaps it should be configurable, where the default is that hidden options/subcommands are not suggested, but applications who like the previous behaviour can get it if they want.

**Comment by remkop** [comment]
Fixed in master. (I did not make it configurable.)
Please verify if you have a chance.
