### ISSUE TITLE
Compiler overloaded method resolution problem with Callable under Scala 2.11.10 and PIcocli 4.1.2

### ISSUE THREAD

**Issue by mmisiewicz** [remkop/picocli#896]
I seem to be having an issue with Scala 2.11 and Picocli 4.1.2. I'm not quite sure what the issue is, but one thing of note is that I'm using `java.util.concurrent.Callable` rather than `Runnable` as in the example in #183. Here's what I've got:

```scala

import java.util.concurrent.Callable

import picocli.CommandLine
import picocli.CommandLine.{Command, Option}

@Command(
  name = "TestProcessor",
  mixinStandardHelpOptions = true,
  version = Array("0.0.1"),
  description = Array("Test test")
)
class TestProcessor extends Callable[Unit] {

  @Option(names = Array("-a"), description = Array("A Number"))
  val a = 0;

  @Override def call(): Unit = {
    val a = List(1,2,3,4,5).map(_.asInstanceOf[java.lang.Object])
    val b = String.format("{} {} {} {} {}", a: _*)
    println(b)
    println(s"Hello $a")
  }

  def main(args: Array[String]) : Unit = {
    CommandLine.call(new TestProcessor(), args: _*)
  }
}

```

Unfortunately this won't compile with:

```
[error] TestProcessor.scala:27:17: overloaded method value call with alternatives:
[error]   [C <: java.util.concurrent.Callable[T], T](x$1: Class[C], x$2: picocli.CommandLine.IFactory, x$3: String*)T <and>
[error]   [C <: java.util.concurrent.Callable[T], T](x$1: C, x$2: java.io.PrintStream, x$3: String*)T <and>
[error]   [C <: java.util.concurrent.Callable[T], T](x$1: C, x$2: String*)T
[error]  cannot be applied to (com....TestProcessor, String)
[error]     CommandLine.call(new TestProcessor(), args: _*)
```

It does seem to compile with `Runnable` though which is curious. I'm stumped, is there anything that would allow Runnable to work but not Callable in picocli?

**Comment by mmisiewicz** [comment]
I realized I'm missing a companion object as in #183. Still, it has no effect. Adding:

``` scala
object TestProcessor {
  def main(args: Array[String]) {
    CommandLine.run(new TestProcessor(), args: _*)
  }
}
```

still results in the same error:

```
[error]    overloaded method value call with alternatives:
[error]   [C <: java.util.concurrent.Callable[T], T](x$1: Class[C], x$2: picocli.CommandLine.IFactory, x$3: String*)T <and>
[error]   [C <: java.util.concurrent.Callable[T], T](x$1: C, x$2: java.io.PrintStream, x$3: String*)T <and>
[error]   [C <: java.util.concurrent.Callable[T], T](x$1: C, x$2: String*)T
```

**Comment by remkop** [comment]
Thanks for raising this!

That is strange: we’re getting an error for `call` being overloaded even after changing `TestProcessor` to be `Runnable` and calling `CommandLine.run`? Or did you mean the companion object calls `CommandLine.call`?

What version of picocli were you using previously that didn’t have this problem?

From picocli 4.0, the static `call` and `run` methods have been deprecated in favor of the non-static [`execute`](https://picocli.info/#execute) method. I expect the problem will go away if you update `TestProcessor` to use the `execute` method like the updated [scala example](https://picocli.info/#_scala) in the user manual. 

That still doesn’t explain why you’re seeing that error; I’ll look into this in more detail when I get to my computer.

**Comment by mmisiewicz** [comment]
Hi! 

Yes really strange. The compiler error was occurring where I invoked `CommandLine.call`, which was in my companion object, and was mitigated by switching to `run` and `Runnable`. Really weird because you can clearly see the correct method is in the list of candidates. So it seems like more likely something to do with Scala. I have been using picocli 4.0.4 in Java using `Callables` with no issues but I only tried 4.1.2 under Scala.

In any case, switching to `execute` worked - `Callable` and all, so I'll just stick with that.

Thanks for your help!

**Comment by remkop** [comment]
Glad to hear that!
I hope you like picocli.

**Comment by mmisiewicz** [comment]
Yes! It's wonderful. Thank you so much for such a great library! I have really enjoyed using it.
