### ISSUE TITLE
Outdated wiki page(s)

### ISSUE THREAD

**Issue by deining** [remkop/picocli#898]
I just stumbled across the outdated wiki page [Quick Guide (work in progress)](https://github.com/remkop/picocli/wiki/Quick-Guide-(work-in-progress)). I think it's better to place a link to the latest quick quide on the wiki (as done for the programmatic API).
I realised there is a wiki page for the manual, too. I asked myself whether it makes sense to have two manual versions available. Sooner or later, they will diverge, which is undesirable.

Just my thoughts, keep up your good work!

**Comment by remkop** [comment]
Yes, good point, I’ll do so. 

I created these wiki pages when the docs were still under development so I could work on them during my commute using my phone. 
I should clean things up. :-)

**Comment by remkop** [comment]
I finally had a chance to fix this. 
I believe all wiki pages that were duplicates now link to their picocli.info equivalent. 
Please let me know if I missed anything. 

Thanks again for raising this!

**Comment by remkop** [comment]
@deining I think this is done, so I will close this ticket, but please let me know if I missed anything.
Thanks again for raising this!
