### ISSUE TITLE
missing period (full stop) in help subcommand description

### ISSUE THREAD

**Issue by garretwilson** [remkop/picocli#899]
I'm just now getting to upgrade to picocli 4.x and so far everything is working well. The error reporting and handling is nice.

Here's a issue that's trivial but nonetheless something you might want to fix the next time you're in the code:

```java
@Command(name = "help", header = "Displays help information about the specified command",
   synopsisHeading = "%nUsage: ", helpCommand = true,
```

The sentence `"Displays help information about the specified command"` is missing a `.` full-stop character at the end. It sort of leaves the help message hanging, as if picocli got interrupted in the middle of thought. 😄

**Comment by remkop** [comment]
Glad to hear it is going well.

Thanks for pointing out the doc improvement! 

Unrelated: One new [4.1](https://github.com/remkop/picocli/releases/tag/v4.1.0) feature that may be nice for your users is that picocli now offers a built-in `generate-completion` command (`picocli.AutoComplete.GenerateCompletion`) that can be used as a subcommand (similar to the built-in `HelpCommand`) to generate a bash/zsh completion script. 

This allows users to install completion with `. <(mycommand generate-completion)`, and from that moment, `mycommand` will have tab completion in that shell session.

See also https://picocli.info/autocomplete.html#_distribution

**Comment by garretwilson** [comment]
> This allows users to install completion …

I noticed this auto-completion stuff, and I tried to read a little about it, but I didn't completely understand it. (I read very quickly because I didn't want to get too distracted from my other tasks.) The important thing I came away with is that users have to install something else or do extra steps to somehow enable this, right?

Many users for my particular application may be barely grasping the command line, so I don't want to distract them with extra steps. Of course there will eventually be many power users of my application, so at some point I'll want to come back and read more about it. Thanks.

**Comment by remkop** [comment]
Sure, no worries.

This is only relevant for bash/zsh users of your CLI app. The idea of the new feature is that it makes installation/enabling much easier. No need for you to distribute completion scripts, your users can get tab completion in the shell by executing one command: `source <(cmd generate-completion)`. But yes, that step is still there. 

Note to self: I should simplify the AutoCompletion documentation. :-)
