### ISSUE TITLE
Hi, Remko - here's an update for you!

### ISSUE THREAD

**Issue by bbottema** [remkop/picocli#900]
Hi Remko, I just thought to let you know I just released [Simple Java Mail 6.0.0-rc1](https://github.com/bbottema/simple-java-mail#latest-progress) with [CLI support](http://www.simplejavamail.org/cli.html#navigation) based on your excellent library.

It's a pretty neat trick that I pulled off by taking A). the fluent builder API of Simple Java Mail for building emails and mailers and B). the Javadoc embedded in runtime by [therapi javadoc](https://github.com/dnault/therapi-runtime-javadoc) and then generating CLI options in runtime using both.

It works well, it looks great and for a big part I have you to thank for it! So thanks!!

**Comment by remkop** [comment]
Hi Benny,

Congrats on the new release! Very nice work!
I hope you don't mind, but I added a link to Simple Java Mail in the picocli [README](https://github.com/remkop/picocli#adoption). 😄 

Glad you found picocli useful!
