### ISSUE TITLE
Can't split multi-value option with: split = " "

### ISSUE THREAD

**Issue by masupilami** [remkop/picocli#917]
Hi,
We are trying to migrate from args4j. 
For multi-value options I am using args4j's [StringArrayOptionHandler](https://github.com/kohsuke/args4j/blob/master/args4j/src/org/kohsuke/args4j/spi/StringArrayOptionHandler.java):
```
@Option(name = "-text", handler = StringArrayOptionHandler.class)
private List<String> text;
```
so that the option can be used like this: `<command> -text foo bar`. The List `text` then contains ["foo", "bar"].

Currently I have found no way to replicate this behavior with picocli:
```
@Option(names = "-text", split = " ")
private List<String> text;
```
this only works if the argument is put in quotes (`<command> -text "foo bar"`), otherwise `bar` is not matched.
thanks

**Comment by remkop** [comment]
@masupilami Take a look at the user manual for [multiple values](https://picocli.info/#_multiple_values), specifically the section on [arity](https://picocli.info/#_arity).

The default arity for a multi-value type (like `List<String>`) is one, so by default picocli will only match one value for each occurrence of the `-text` option.

If you want picocli to consume as many parameters as possible after a single occurrence of `-text`, then you can set the arity to `1..*`. Note that this means that picocli will put all arguments following `-text` into the `List`, until it encounters either another option or another subcommand. 

Does this meet your requirements?

**Comment by masupilami** [comment]
yes that works
thanks
