### ISSUE TITLE
Add jbang under packaging in the user manual

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#929]
Example text:

## Packaging Your Application

...

### jbang

[jbang](https://github.com/maxandersen/jbang) allows you to write scripts in Java that use external dependencies.
You use it with a `//DEPS` comment, similar to the [`@Grab`](http://groovy-lang.org/grape.html) annotation in Groovy.

Use `jbang --init=cli helloworld.java` to create an initial script with a picocli template.
This [asciinema presentation](https://asciinema.org/a/AVwA19yijKRNKEO0bJENN2ME3?autoplay=true&speed=2) shows what is possible.

----

@maxandersen Feedback welcome, this is just a draft.

**Comment by maxandersen** [comment]
Looks good to me - thanks!

**Comment by remkop** [comment]
Manual and README updated. Closing for now.
Thanks again, Max!
