### ISSUE TITLE
Ensure value always exists in set

### ISSUE THREAD

**Issue by carragom** [remkop/picocli#939]
Hi there,

I have the following option

```java
@Option(names = { "-w", "--writer" }, description = "Optional list of writers to output the data with")
    Set<StandardWriter> writers = new HashSet<>(Arrays.asList(StandardWriter.CSV));
```

Where `StandardWriter` is an `Enum`. It works well, I get as many values as `-w` options I pass to my program. Also as expected if I don't pass any `-w` options I always have `CSV`. But there is a peculiar behavior. If I pass a `-w` option that is no `CSV`, let's say `TSV` I don't get `CSV`. Is there a way to ensure that `CSV` is always in the list no matter what?. Thanks.

**Comment by remkop** [comment]
I see what you mean. Picocli considers the initial field value to be the default. This default is only used if the option is not specified on the command line, otherwise the specified values are used.

However, with a small change we can ensure that `CSV` is always in the list:
we put the `@Option` annotation on a setter method instead of on a field, and in the method we add some logic to add `CSV`. For example:

```java
enum StandardWriter {CSV, TSV, XLS, JSON}
@Test
public void testIssue939() {
    class MyApp implements Runnable {
        Set<StandardWriter> writers = new HashSet<StandardWriter>(Arrays.asList(StandardWriter.CSV));

        @Option(names = { "-w", "--writer" }, description = "Optional list of writers to output the data with")
        void setWriters(Set<StandardWriter> newValues) {
            if (!newValues.contains(StandardWriter.CSV)) {
                System.out.println("Missing CSV... Let me fix that.");
                newValues.add(StandardWriter.CSV);
            }
            System.out.println("Setting " + newValues);
            writers = newValues;
        }

        public void run() {}
    }
    MyApp myApp = new MyApp();
    new CommandLine(myApp).execute();
    assertEquals(new HashSet<StandardWriter>(Arrays.asList(StandardWriter.CSV)), myApp.writers);

    myApp = new MyApp();
    new CommandLine(myApp).execute("-w=TSV");
    assertEquals(new HashSet<StandardWriter>(Arrays.asList(StandardWriter.CSV, StandardWriter.TSV)), myApp.writers);

    myApp = new MyApp();
    new CommandLine(myApp).execute("-w=TSV", "-w=XLS");
    assertEquals(new HashSet<StandardWriter>(Arrays.asList(StandardWriter.CSV, StandardWriter.TSV, StandardWriter.XLS)), myApp.writers);
}
```

**Comment by carragom** [comment]
Thanks a lot, that should do it

**Comment by remkop** [comment]
Cool!

Please star picocli on GitHub if you like the project. :-)
