### ISSUE TITLE
Typo - Semicolon: Picocli.info website

### ISSUE THREAD

**Issue by ztbx** [remkop/picocli#944]
[Link to Picocli.info](https://picocli.info/#_arrays_collections_maps)
Section `4.4.2. Maps`

> @Option(names = {"-p", "--proxyHost"});

>  @Option(names = {"-u", "--timeUnit"});

Semicolon should not be present at the end of the statement.

**Comment by remkop** [comment]
Thank you for raising this!
I’ll fix this soon.

**Comment by remkop** [comment]
Fixed.
Thanks again for raising this!

**Comment by remkop** [comment]
Please star picocli on GitHub if you like the project.
