### ISSUE TITLE
Options must be exactly in between subcommand and sub-subcommand?

### ISSUE THREAD

**Issue by sahilsachdeva** [remkop/picocli#948]
I am trying to structure my project into sub-command and sub-sub-commands. Sub-commands have some options that apply to all sub-sub-commands. Like so:

```
@CommandLine.Command(name = "foo")
public class FooSubcommands {

    @CommandLine.Option(names = {"-b", "--baz"}, required = true)
    String baz;

    @CommandLine.Command(name = "bar")
    public void bar() {

        System.out.println(baz);

    }

}
```

The option 'baz' is only detected if it is exactly between 'foo'  and 'bar'. Is this Intended behaviour? I think `foo bar -baz=<something>` should be supported too

**Comment by remkop** [comment]
@sahilsachdeva Your question is very timely: [picocli 4.2](https://github.com/remkop/picocli/releases/tag/v4.2.0) was just released, with a new feature that helps with your use case:

* mixin classes can now have a `@ParentCommand` field
* the user manual has a [new section](https://picocli.info/#_use_case_sharing_options) about sharing options between commands and subcommands. The section has example code and is close to your use case.

Please let me know if that answers your question.

**Comment by remkop** [comment]
@sahilsachdeva Did this answer your question?

**Comment by remkop** [comment]
Related: https://github.com/remkop/picocli/issues/958 (this will be included in the next release).

**Comment by remkop** [comment]
@sahilsachdeva, picocli currently does not have a convenient syntax for "global" options, but I am [looking at adding this](https://github.com/remkop/picocli/issues/649) in the upcoming picocli 4.3 release.

As a workaround for your use case, in picocli 4.2 you could put the `-baz` option in a mixin that delegates to the `FooSubcommands` top-level command using the `@ParentCommand` field. That would look something like this:

```java
@Command(name = "foo")
public class FooSubcommands {

    @Option(names = {"-b", "--baz"}, required = true)
    String baz;

    @Command(name = "bar")
    public void bar(@Mixin MyMixin mix) { // add the -baz option to the `bar` subcommand
        System.out.println(baz);
    }
}

class MyMixin {
    @ParentCommand FooSubcommands root;

    @Option(names = {"-b", "--baz"}, required = true)
    public void baz(String newValue) {
        root.baz = newValue; // delegate to the parent
    }
}
```

The upcoming picocli 4.3 release will provide more convenient syntax to create shared options, without the need to create a mixin class.

This is still work in progress (so the below may still change), but creating a global option may look something like this:

```java
@Command(name = "foo")
public class FooSubcommands {

    // This option is shared on all descendant commands (subcommands, sub-subcommands, etc.)
    @Option(names = {"-b", "--baz"}, required = true, scopeType = ScopeType.SUBTREE)
    String baz;

    @Command(name = "bar")
    public void bar() {
        System.out.println(baz);
    }
}
```

The above definition will allow user input like this:

```
foo bar -baz=<something>
```

**Comment by sahilsachdeva** [comment]
@remkop sorry for the late reply. The proposed syntax for the next release looks perfect.
I understood the work around proposed by you, but I ended up not using it. I will complete the restructuring after 4.3.
