### ISSUE TITLE
Consider using Gradle Use Latest Versions Plugin

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#950]
See https://github.com/patrikerdes/gradle-use-latest-versions-plugin

**Comment by ebramirez** [comment]
Or you could enable Dependabot, which would automatically create the update PRs.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

**Comment by remkop** [comment]
Thanks for the tip, @ebramirez !
(I do confess I am a bit hesitant about getting too many PRs, but it's worth trying for a while to see what the workload would be...)
