### ISSUE TITLE
Make annotation processor quiet by default (was: better defaults for docgen)

### ISSUE THREAD

**Issue by maxandersen** [remkop/picocli#952]
the docgen feature is nice but it’s a bit annoying its bundled with the graalvm codegenerator and that it doesn't have usable default for project output when outsoide a maven/gradle scenario.

The current default behavior means I'm forced to do this in jbang to have it not generate  files i'll never need:

```
//DEPS info.picocli:picocli:4.2.0 info.picocli:picocli-codegen:4.2.0
//JAVAC_OPTIONS -Aproject=. -Adisable.proxy.config -Adisable.reflect.config -Adisable.resource.config
...
        ManPageGenerator.main(new String[] { "tz", "--outdir=.", "-v" });
...

``` 

and still in output I get:
```
Note: ReflectConfigGen is not enabled
Note: ResourceConfigGen is not enabled
Note: ProxyConfigGen is not enabled
Generating man page ./tz.adoc
```

any chance of splitting them out in separate artifacts and possibly default output to current dir if running outside maven/gradle ?

**Comment by remkop** [comment]
I need to think about splitting out the docgen from the annotation processor.

The default value for the `--outdir` option for the man page generator is `"."`, so if the current directory is what you want, you do not need to specify this option. This should already work. Did this not work as expected?

One other thing I'm getting from your feedback is that you don't want to see the `Note: blah is not enabled` output. I will add an option to the annotation processor to suppress output at `Diagnostic.Kind.NOTE` level. Something like  `-Aquiet=true`, or ideally just  `-Aquiet`.

(PS. I think you can omit the `-Aproject=.` option in `JAVAC_OPTIONS`. It is only used by the annotation processor, not by the `ManPageGenerator` tool.)

**Comment by maxandersen** [comment]
I think if you explicitly disable a setting via properties then no need to tell that to user unless he asked to be verbose.

**Comment by remkop** [comment]
Yes, that’s what I should have done originally. Now the annotation processor is verbose by default; it tell you both when files are generated and when not generated. 

Generally I am very hesitant to change any defaults (unless the default is causing a serious issue) because I have no idea what it will break...

Hence my proposal to introduce a `quiet` option.

**Comment by maxandersen** [comment]
its been less than a week it was released ; you think someone by now is reliant on the system.out output of the processor when *not* used for asciidoc ? Personally I Think its fine to consider this a bug rather than a feature - but your choice :)

**Comment by remkop** [comment]
Strictly speaking, that system output was not introduced with the AsciiDoc generator; it has been there since the processor was introduced in 4.0 and is not related to the AsciiDoc generator.

But anyway, you are proposing to change the default to quiet and introduce an option `-Averbose` instead of the other way around. I do like that behaviour better, I'll just need to agonize a bit longer over the trade-offs of changing the default... :-)

**Comment by remkop** [comment]
By the way, could you confirm that the default directory is indeed the current directory, or was there a problem there that I need to look into?

**Comment by remkop** [comment]
I've given this more thought and I now think the annotation processor should be quiet by default.

I will add a `-Averbose` option to the annotation processor to show output like:

```
Note: ReflectConfigGen is not enabled
Note: ResourceConfigGen is not enabled
Note: ProxyConfigGen is not enabled
Generating man page ./tz.adoc
```

**Comment by remkop** [comment]
Implemented and pushed to master.

To verify, you can do this:

```
git clone https://github.com/remkop/picocli.git
cd picocli
gradlew publishToMavenLocal
```

That should publish `picocli-4.2.1-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.1-SNAPSHOT` dependency.

**Comment by maxandersen** [comment]
> By the way, could you confirm that the default directory is indeed the current directory, or was there a problem there that I need to look into?

so when I just enable the codegenrator, with no configuration I just get:

```
Note: ReflectConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/reflect-config.json
Note: ResourceConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/resource-config.json
Note: ProxyConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/proxy-config.json
```

and the files does actually gets generated into the class output and does end up in the jar.
so thats good ;)

**Comment by remkop** [comment]
Thanks for confirming!
