### ISSUE TITLE
allow defining nesting of command methods to reduce necessary scaffolding

### ISSUE THREAD

**Issue by maxandersen** [remkop/picocli#953]
This idea might be completely crazy, but in `jbang` I'm really trying hard not having to add support for multiple files (I will probably eventually have to but lets see how far we can stretch it :)

In my work on doing a kubectl plugin I end up with a [lot superflous classes](https://github.com/maxandersen/k8s-cli-java/blob/d210435cab427b7f50d9110467e7a53373f42889/kubectl-example).

Most of these could just be a command method, BUT command methods can't be nested.

I was wondering if we could somehow utilize method references to allow arbitrary nesting/combination.

So instead of requring 5 classes I could just have one class with a 5-7 command methods.  

Something like:

```
@Command(name="example",  addMethodSubcommands = false, 
submethods = {
     KubectlExample::resource, 
     KubectlExample::pod})
class KubectlExample {
    @Command(submethods = {
                  KubectlExample::resourceList,
                  KubectlExample::resourceAdd,
    })
    public void resource() {}

   @Command(name="list")
   public void resourceList() { ... }

   @Command(name="add")
   public void resourceAdd() { ... }

   @Command(submethods = {
                  KubectlExample::podList,
                  KubectlExample::podAdd,
    })
    public void pod() {}

   @Command(name="list")
   public void podList() { ... }

   @Command(name="add")
   public void podAdd() { ... }

}
```

Just a thought - and would also reduce the amount of state passing/management needed as could just be kept in the main class, but still allow inject context state via the method parameters.

I probably miss something obvious her but this to me feels like a good somewhat typesafe middleground compared to programmatic configuration and would for some cases at last help reduce the amount of code/classes necessary.

wdyt?

**Comment by remkop** [comment]
Interesting. I don’t think Java supports method references in annotations, but I could be wrong. 

So the best we could do would be to have a `submethods` (or similar) annotation attribute that takes a String value which is either the method name or the subcommand name. 

Note that the goal of a single source file can already be accomplished with the current version of picocli by using static inner classes. 

```java
@Command(subcommands = {B.class, C.class})
class A implements Runnable {
    public void run() {
    }
    @Command void subA1() {}

    @Command void subA2() {}

    @Command(subcommands = {X.class})
    static class B implements Runnable {
        public void run() {
        }
        @Command void subB1() {}

        @Command void subB2() {}
    }

    @Command
    static class C //...

    @Command
    static class X //...
}
```

**Comment by maxandersen** [comment]
you don't have to have the classes nested, non public classes works just as fine - but it still makes the code more verbose than it have too imo.

and yeah, annoatations don't allow type references...sadly...sorry for not checking that first.

**Comment by remkop** [comment]
I know what you mean, it just “feels” verbose to create an extra class, even if the physical difference is only 2 lines: one that says `class X implements Runnable {` and another line for the closing curly brace`}`.

On the bright side: these inner classes and their nested `@Command` methods provide a structure in the code that matches the command hierarchy which is very intuitive and helps maintainability. 

Overall not such a bad trade-off. :-)

**Comment by remkop** [comment]
@maxandersen Do you want to discuss this further?

**Comment by maxandersen** [comment]
I'm just allergic to unnecessary classes these days (jbang did that to me :) but i grok why it isn't a great win....especially as it can't just be method refs so its less typesafe. so all okey for closing this if considered not worth it ;)

**Comment by remkop** [comment]
Ok, in that case I will close this ticket. Thanks!
