### ISSUE TITLE
have handler for force ex.printstacktrace

### ISSUE THREAD

**Issue by maxandersen** [remkop/picocli#954]
would it not make sense to make the printstacktrace at https://github.com/remkop/picocli/blob/master/src/main/java/picocli/CommandLine.java#L1924 something that users can control ?

especially I would like to be able to do something that have access to the commands

```
void handleException(@Mixin mycmd, Exception e) {
    mycmd.info(e.getMessage());
    if (mycmd.verbose) {
		e.printStackTrace();
	} else if (e.getCause() != null) {
		mycmd.info("Run with --verbose for more details");
	}
}
```

for now if I just wrap a try/catch around the execute() call I always get the full stacktrace printed which just aren't nice and its tedious having to add try/catch in all command call points.

**Comment by remkop** [comment]
This facility exists: you can set a custom `IExecutionExceptionHandler`. 

See section 9.8.2. “Business Logic Exceptions”:
https://picocli.info/#_handling_errors

**Comment by remkop** [comment]
The line you highlighted is what gets executed if the custom error handler itself throws an exception.

**Comment by maxandersen** [comment]
I could have sworn I saw it print ..well, that’s why I shouldn’t open bugs after midnight :)

...but how does one best figure out if the "verbose" option is set...would I need to look that up dynamically somehow in CommandSpec/Commandline ?

**Comment by remkop** [comment]
Sorry, I was unclear. The default handler actually simply rethrows the error, then the fallback handler (that you linked to) catches it and prints the stacktrace. 

To figure out if verbosity, you can either get a reference to your application via `CommandLine.getCommand()`, or get the specified option value from the parse result via `parseResult.matchedOptionValue()`. For example:

```java
// assume we have this option
// @Option(names = {"-v", "--verbose"}) boolean[] verbosity = new boolean[0];

public int handleExecutionException(Exception ex,
                                    CommandLine commandLine,
                                    ParseResult parseResult) {
    commandLine.getErr().println(ex.getMessage());

    MyApp app = commandLine.getCommand();
    System.out.printf("app.verbosity.length=%d%n", app.verbosity.length);
    if (app.verbosity.length >= 2) {
        ex.printStackTrace();
    }

    // alternatively, we can get the verbosity from the parse result:
    boolean[] verbosity = parseResult.matchedOptionValue("verbose", new boolean[0]);
    System.out.printf("parseResult.matchedOption(verbose).length=%d%n", verbosity.length);
    if (verbosity.length >= 1) {
        commandLine.usage(commandLine.getErr());
    }
    return commandLine.getCommandSpec().exitCodeOnExecutionException();
}
```

**Comment by remkop** [comment]
@maxandersen Did this answer your question?

**Comment by maxandersen** [comment]
yes, excellent @remkop ! thanks.
