### ISSUE TITLE
Default value should only be applied if value is missing (was: ITypeConverter called for default value only if value is missing)

### ISSUE THREAD

**Issue by chirlo** [remkop/picocli#961]
As of 4.2.0, if:

- a parameter has a default value and a  `ITypeConverter` defined,

- **and** a value is provided for this parameter

then the converter gets called twice, once with the default value and a second time with the provided value. 
For example, for the following parameter

    @Parameters(index = "0", description = "name", defaultValue = "alice", converter = NameTypeConverter.class)
    Name name;`

The call `cmd bob` will call the `NameTypeConverter#convert(String)` once with the parameter `alice` and once with `bob`.

I have a use-case where a given json file is parsed to a POJO , with a default value of `config.json`. If the parameters is specifically provided as `my_config.json` , the converter will fail trying to parse the default value of `config.json`, since it doesnt' exist.

Ideally, since converters can fail or do some  extra checks, I'd suggest that the default value should only be evaluated if not specifically specified.

**Comment by remkop** [comment]
Hi @chirlo,

I see what you are saying. 

For background, picocli must behave well when a single `CommandLine` instance is used multiple times to parse different sets of command line args.

For that reason, all options and positional parameters are first "reset" to their initial value (if they were declared with an initial value), next they are set to their default value (if defined), and finally a value may be assigned (overwritten again) when the option is matched on the command line.

I can look into doing this the other way around: parse the input, remember which options and positional parameters were matched, and only set the default/initial value on options and positional parameters that were not matched. This will require a bit more book-keeping, and the timing of when to apply defaults becomes a bit more tricky, but it should be possible. It may take some time though.

Are you interested in providing a pull request for this?

In your application, were you able to work around this?

**Comment by remkop** [comment]
Fixed in master.

To verify this, check out picocli master locally, and build it with `publishToMavenLocal`. That should publish `picocli-4.2.1-SNAPSHOT` to your local .m2 Maven cache.

```
git clone https://github.com/remkop/picocli.git
cd picocli
gradlew publishToMavenLocal
```

You can then try this in a project that uses the `info.picocli:picocli:4.2.1-SNAPSHOT` dependency. Feedback very welcome!
