### ISSUE TITLE
CliBuilder: Grape issue with Groovy 3.0.1

### ISSUE THREAD

**Issue by 0branch** [remkop/picocli#970]
Consider the following minimal script:

    @Grab('info.picocli:picocli:4.2.0')
    import groovy.cli.picocli.CliBuilder

    def cli = new CliBuilder()
    
Under Groovy 2.5.9, this runs without error; with 3.0.1, however, I see:

    $ groovy cli.groovy 
    Caught: java.lang.NoClassDefFoundError: picocli/CommandLine$ParameterException
    java.lang.NoClassDefFoundError: picocli/CommandLine$ParameterException
            at cli.run(cli.groovy:4)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    Caused by: java.lang.ClassNotFoundException: picocli.CommandLine$ParameterException
            ... 4 more
            
Can anyone account for the `ClassNotFoundException`? The jar is definitely downloaded to `~/.groovy/grapes` and both versions of Groovy output

    Resolving dependency: info.picocli#picocli;4.2.0 {default=[default]}
    Preparing to download artifact info.picocli#picocli;4.2.0!picocli.jar

when `-Dgroovy.grape.report.downloads=true` is supplied.

Thanks in advance.

**Comment by remkop** [comment]
@0branch Thank you for raising this. This seems to be a Groovy issue rather than a picocli issue (especially considering that it manifests with Groovy 3.0.1 but not with 2.5.9).

Would you mind raising this in the Groovy JIRA issue tracker (https://issues.apache.org/jira/browse/GROOVY)? I will help out there if I can.

**Comment by 0branch** [comment]
@remkop sure, will do.

Thanks.

**Comment by 0branch** [comment]
Filed as https://issues.apache.org/jira/browse/GROOVY-9432.

**Comment by remkop** [comment]
The picocli docs will also mention `@GrabConfig(systemClassLoader=true)` for Groovy scripts from the next release.
