### ISSUE TITLE
Allow repetitions of co-occuring arg groups

### ISSUE THREAD

**Issue by fbiville** [remkop/picocli#977]
Picocli version: `4.2.0`

I have a group of options that are required together:
```java
class InputBinding {

	@Option(required = true, names = {"-ig", "--input-gateway"}, paramLabel = "INPUT GATEWAY")
	GatewayAddress gatewayAddress;

	@Option(required = true, names = {"-it", "--input-topic"}, paramLabel = "INPUT TOPIC")
	String topicName;
}
```
I want this group of options to be specified at least once. But I also want to allow repetitions, hence the use of a List in the top-level command:
```java
@Command(name = "generator")
public class MyCommand implements Runnable {

	@ArgGroup(exclusive = false, heading = "INPUT BINDINGS (1..n)")
	List<InputBinding> inputBindings;

	@Override
	public void run() {
		System.out.println("hello");
	}

	public static void main(String... args) {
		CommandLine commandLine = new CommandLine(new LocalBindings());
		commandLine.registerConverter(GatewayAddress.class, GatewayAddress::parse);
		System.exit(commandLine.execute(args));
	}
}
```

However, if I try to run this with several repetitions of the co-occurring group such as `./myCommand -ig some.address -it topic1 -ig some.address2 -it topic2`, this fails as follows:

```
Error: expected only one match but got [-ig=INPUT GATEWAY -it=INPUT TOPIC]={--input-gateway=some.address --input-topic=topic1} and [-ig=INPUT GATEWAY -it=INPUT TOPIC]={--input-gateway=some.address2 --input-topic=topic2}
```

Is there a way to allow repetitions of co-occurring arg groups?

**Comment by fbiville** [comment]
I somehow completely missed https://picocli.info/#_repeating_composite_argument_groups 🤦‍♂

**Comment by remkop** [comment]
@fbiville I believe specifying `multiplicity = "*"` on the arg group should solve the issue. 

You closed the ticket, so I hope it’s all good now; let me know if there’s anything else.

**Comment by fbiville** [comment]
`multiplicity = "1..*"` does exactly what I want. Thanks for the reply and the extensive documentation!

**Comment by remkop** [comment]
Glad to hear that! Enjoy picocli!
(If you like picocli, please star the project on GitHub.) :wink:
