### ISSUE TITLE
Parameter validates an unknown option

### ISSUE THREAD

**Issue by FSchermann** [remkop/picocli#982]
Hi, 
I have the same issue as described in https://github.com/remkop/picocli/issues/282. I'm using version 3.9.6.
Problem description:
Using a parameter with arity "1..*" adds unkown or unhandled options to the list. Known options are handled correctly.  
Can you fix that?

**Comment by remkop** [comment]
Can you please provide the steps to reproduce the issue? Perhaps a small sample application that demonstrates the issue?

**Comment by FSchermann** [comment]
`import picocli.CommandLine;
import picocli.CommandLine.Parameters;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class PicoBug implements Runnable {


    @Parameters(paramLabel = "FILES", arity = "1..*", description = "List of files")
    private List<File> files = new ArrayList<File>();

    // Uncomment to validate @Parameter arity = "1..*",
    //    @CommandLine.Option(names = {"-v"}, description = "Print output")
    //    private boolean verbose;

    public static void main(String[] args) {
        args = new String[]{"FILES testfile1 testfile2 --unknown","-unknown"};

        CommandLine.run(new PicoBug(), System.out, args);
    }

    public void run() {
        System.out.println("DONE");
    }

}`

Example to reproduce.

**Comment by remkop** [comment]
Thank you. That clarifies the issue.

Please use `arity = "1"` instead of `arity = "1..*"`. 

Even with `arity = "1"` the list will capture multiple positional parameters, but it will no longer greedily consume option-like values. The user is still required to provide at least one positional parameter.

----
I recommend upgrading to 4.2.0. That has support for exit codes, among many other new features.

```java
public class PicoBug implements Runnable {
    
    @Parameters(paramLabel = "FILES", arity = "1", description = "List of files")
    private List<File> files = new ArrayList<File>();

    public static void main(String[] args) {
        args = new String[] {"FILES testfile1 testfile2 --unknown","-unknown"}; // error unknown option
//        args = new String[] {"a", "b", "c"}; // prints multiple values
//        args = new String[] {}; // error: missing required positional param

        int exitCode = new CommandLine(new PicoBug()).execute(args); // 4.x execute API
        System.exit(exitCode);
    }

    public void run() {
        System.out.println("DONE: " + files);
    }
}
```

**Comment by FSchermann** [comment]
Perfect, that solved the issue.
I just also had to remove the index filed, otherwise the second argument is marked as unknown.
Thanks for your quick help :)

**Comment by remkop** [comment]
My pleasure!
Please star the project on GitHub if you like the project! :wink:
