### ISSUE TITLE
how can i realize multi level help

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [remkop/picocli#986]
like this:
git --help
git commit --help

I can't find an example.

thx!

**Comment by remkop** [comment]
Sure, picocli makes that very easy. For example:

```java
@Command(name = "git", mixinStandardHelpOptions = true,
        subcommands = GitCommit.class,
        description = "Commit stuff...")
class Git implements Runnable {
    public void run() { // business logic here
    }

    public static void main(String[] args) {
        new CommandLine(new Git()).execute(args);
    }
}

@Command(name = "git", mixinStandardHelpOptions = true,
        description = "Commit stuff...")
class GitCommit implements Runnable {
    public void run() { // business logic here
    }
}
```

See also the user manual section on Subcommands: https://picocli.info/#_subcommands

And examples in the project: https://github.com/remkop/picocli/tree/master/picocli-examples/src/main/java/picocli/examples/subcommands

**Comment by remkop** [comment]
@CanYouGiveMeAName I updated my answer. Did this answer your question?

**Comment by CanYouGiveMeAName** [comment]
Thanks a lot. I wil try.

**Comment by CanYouGiveMeAName** [comment]
> @CanYouGiveMeAName I updated my answer. Did this answer your question?

Yes

**Comment by remkop** [comment]
@CanYouGiveMeAName Glad to hear that you were able to make progress!

Please star picocli on GitHub if you like the project! 😉
