### ISSUE TITLE
Option group sections should include subgroup options

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#988]
Currently, if an argument group has an option and a nested sub-group, the usage help will only show the options that are _directly_ in the group under the heading for that group.

Instead, the usage help should also include the options for the nested subgroups, unless this subgroup has its own heading.

**Comment by remkop** [comment]
This can be worked around by giving the subgroup an empty string `""` heading.

**Comment by Linyer-qwq** [comment]
Hi, I want to try to fix that issue. Could you give some testcases? Thanks. XD

**Comment by remkop** [comment]
@Linyer-qwq  Thank you for your offer! I pushed a failing test case: [ArgGroupTest::testIssue988OptionGroupSectionsShouldIncludeSubgroupOptions](https://github.com/remkop/picocli/blob/master/src/test/java/picocli/ArgGroupTest.java#L3394).

The test passes if we use the workaround (giving the subgroups an empty string `""` heading), but
the goal is to get the expected output without that workaround.

**Comment by Wycers** [comment]
Thanks for the test case! I am also working on this issue and I fix it by the commit above... But I may not fully understand its logic.

**Comment by remkop** [comment]
Thanks for the PR! I have some other commitments; it may take me some time before I can review it...
