### ISSUE TITLE
Detecting terminal width fails on non-English Windows versions

### ISSUE THREAD

**Issue by S-Gaertner** [remkop/picocli#991]
Dynamically detecting the terminal width (e.g. when specifying `usageHelpAutoWidth` on a command) fails on non-English Windows versions and runs into a 2 second timeout.

The output of `cmd.exe /c mode con` is the following on a German Windows:
```
Status von Gerät CON:
---------------------
    Zeilen:          9001
    Spalten:         148
    Wiederholrate:   31
    Verzögerungszeit:1
    Codepage:        850
```

This obviously fails to match the regex pattern in `CommandLine.java:6573`:
```
Pattern pattern = Pattern.compile(".*olumns(:)?\\s+(\\d+)\\D.*", Pattern.DOTALL);
```

The timeout occurs because termination of the helper process is not detected directly but by monitoring the `size` value - which does not change in this case.

I'd like to propose two improvements:
* A more robust regex that also suits international Windows versions. That might be tricky though because the general structure of the output might not be comparable between different localizations.
* A second monitoring variable for detecting process termination that is not used for any other purpose. This allows to fail faster and thus improves user experience.

**Comment by remkop** [comment]
Thank you for raising this!
I like your proposed improvements. Will you be able to provide a pull request?

**Comment by S-Gaertner** [comment]
Sure, I can do that!

**Comment by remkop** [comment]
Merged the PR into master.
Thank you again for raising this and thank you for the contribution!
