### ISSUE TITLE
Default values should not be applied to inherited options

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#996]
When a subcommand is matched on the command line, picocli will instantiate the associated user object and (re)set the options and positional parameters to their initial value.

Ticket #649 provided support for inherited options.
Inherited options are special: their setter actually sets the value on the command where the option was defined, not on the command where the option is inherited.

The current implementation will incorrectly overwrite the value that was specified on the top-level command (but not on a subcommand) with the default value when the subcommand is processed.

**Comment by Linyer-qwq** [comment]
Hello. I find that, in the testcase above, the "bean.xvalues" will not be reset to the initial value when the command is reused whether the "xvalues" is "INHERIT". Is this another bug?

**Comment by remkop** [comment]
Hi @Linyer-qwq, thanks for checking! 

Sorry for the confusion; the `@Option(scope = INHERIT)` feature is new and will be first released with picocli 4.3. 

I raised this issue (with a failing test case and additional tracing) because the "inherited options" implementation is still incomplete: some work is still remaining with regards to default values.

I hope to finish that work today. When this is complete, the test should pass. I will comment on this issue when I make progress.
