### ISSUE TITLE
Update manual: quote option parameter with pipe characters in fix split regex example (was:  Improving fix split regex example?)

### ISSUE THREAD

**Issue by galderz** [remkop/picocli#998]
I've tried out the split regex example [here](https://picocli.info/#_split_regex), but I feel the `fix` example could be slightly misleading.

In a UNIX env, `|` is use for pipes, so if you stick that into a command line argument, shells will split the command at that point and fail. I guess in Windows it might work?

**Comment by galderz** [comment]
Of course, a simple workaround exists: use a List and manually split the regex for each entry.

**Comment by remkop** [comment]
Ah, interesting point! 

For background: in the FIX protocol, an unprintable character (`0x01`) is used as the separator between fields. People commonly use the pipe character `|`  as a printable alternative to show a readable version of the FIX message. 

I used this because I was looking for an example to demonstrate that the `split` regex does not always need to be a comma.

However, you are right that the example is misleading because it cannot be executed as is.
Perhaps the option value should be quoted in the example, like this?

```
-fix "8=FIX.4.4|9=69|35=A|49=MBT|56=TargetCompID|34=9|52=20130625-04:05:32.682|98=0|108=30|10=052"
```

I believe that quoting the value should prevent the shell from interpreting the `|` characters as pipes for unix processes. Can you try?

**Comment by galderz** [comment]
I'm not 100% sure but I don't think quoting is enough. In any case, a very easy workaround is available, which I've easily applied in my code.

In any case, I've created an [example](https://github.com/galderz/jawa/blob/master/jbanging/src/picocli_fix_params.java) to demonstrate the `|` issue. You can run that with @maxandersen's [jbang](https://github.com/maxandersen/jbang) to see it in action.

On macOS, the output is swallowed and no error thrown:
```
$ jbang src/picocli_fix_params.java -fix 8=FIX.4.4|9=69
```

If you quote the parameter, the error is produced:
```
$ jbang src/picocli_fix_params.java -fix "8=FIX.4.4|9=69"
${HOME}/.sdkman/candidates/jbang/current/bin/jbang: line 33: 9=69: command not found
```

On linux:

```
$ jbang src/picocli_fix_params.java -fix 8=FIX.4.4|9=69
-bash: 9=69: command not found
```

```
$ jbang src/picocli_fix_params.java -fix "8=FIX.4.4|9=69"
/home/g/.sdkman/candidates/jbang/current/bin/jbang: line 33: 9=69: command not found
```

I'm not 100% sure some of this behaviour (e.g. not dealing with double quotes) is influenced by `jbang`, but since `jbang` is what I'm using to drive the code I use to run picocli, that's what I'm assuming. I'm leaving up to others to test it in a different way.

**Comment by maxandersen** [comment]
@galderz to check if you are being potentially affected by the extra layer of the jbang bash script run it first with `jbang --verbose` and at the end it should give you the actual way to run it with pure java.

Then try your combinations and have at least ruled out jbang shell script sideeffects.

**Comment by maxandersen** [comment]
and I just tried - it fails using jbang script but not when using with java directly. 

Not sure what we need to do here but I'm pretty sure its a bash/shell quoting issue that needs fixing in jbang  than picocli.

**Comment by maxandersen** [comment]
btw. the way to do it that should work in most places are: `-fix "8=FIX.4.4\|9=69"`

quotes + escaping |

**Comment by remkop** [comment]
What about single quotes instead of double quotes (without escaping the pipe `|` characters with backslashes)?

**Comment by galderz** [comment]
> btw. the way to do it that should work in most places are: `-fix "8=FIX.4.4\|9=69"`
> 
> quotes + escaping |

Right, but that's clunky. I'd rather avoid that and just use multiple parameter occurrences.

E.g. instead of:

```
--additional-test-args quarkus=-rf,:quarkus-integration-test-tika|quarkus-platform=-Dcamel-quarkus.version=1.1.0-SNAPSHOT,-Dquarkus.version=999-SNAPSHOT
```

Do:

```
--additional-test-args quarkus=-rf,:quarkus-integration-test-tika \
--additional-test-args quarkus-platform=-Dcamel-quarkus.version=1.1.0-SNAPSHOT,-Dquarkus.version=999-SNAPSHOT
```

**Comment by remkop** [comment]
I finally had some time to try this, and I agree with @maxandersen's conclusion that this is an issue in jbang, not in picocli.

I used this class to verify:
```java
public class Tool implements Runnable {
    @Option(names = "-fix", split = "\\|")
    Map<Integer, String> message;

    @Override
    public void run() {
        System.out.println(message);
    }

    public static void main(String[] args) {
        new CommandLine(new Tool()).execute(args);
    }
}
```

I then built an uberjar `myjar.jar` that contains picocli as well as the `Tool` class, with `Tool` as the main class in the manifest, so it becomes an executable jar. Test results:

```
# double quotes (without escapes): works fine

java -jar myjar.jar  -fix "8=FIX.4.4|9=69|35=A|49=MBT|56=TargetCompID|34=9|52=20130625-04:05:32.682|98=0|108=30|10=052"
{8=FIX.4.4, 9=69, 35=A, 49=MBT, 56=TargetCompID, 34=9, 52=20130625-04:05:32.682, 98=0, 108=30, 10=052}
```

On Linux, both single quotes and double quotes work fine. On Windows only double quotes work.
I will update the [example](https://picocli.info/#_split_regex) in the picocli user manual to ensure that it uses double quotes.

Note that **no escaping with backslashes is necessary**.

Perhaps this should be a ticket in the `jbang` issue tracker? @maxandersen Can you do the honors?

**Comment by maxandersen** [comment]
issue opened - not sure if there is a good cure besides protective quoting ;/

**Comment by remkop** [comment]
I commented on https://github.com/maxandersen/jbang/issues/87; it may be possible to improve things by changing the jbang shell script.

**Comment by remkop** [comment]
I updated the user manual.
This will be reflected in the published user manual with the next picocli release.

Thanks again for raising this and the analysis!
